### ISSUE TITLE
Lists nest unexpectedly if you change type

### ISSUE THREAD

**Issue by teddyzetterlund** [ianstormtaylor/slate#100]
You get an (invalid) endless nesting of lists of you switch type of list (unordered/ordered):

![slate-nesting-list-bug](https://cloud.githubusercontent.com/assets/1955/16893027/e4456dda-4b28-11e6-858a-86fcd0b828d4.gif)

**Comment by ianstormtaylor** [comment]
Hey @teddyzetterlund, thanks for catching this! It's related to this issue: https://github.com/ianstormtaylor/slate/issues/99 since the list items aren't properly being "unwrapped" from their container. Hoping to solve this this week!

**Comment by ianstormtaylor** [comment]
Solved in `0.3.0`! Thanks for reporting this!
