### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by suhaotian** [ianstormtaylor/slate#101]
I found the cursor change every time, the whole DOM tree `re-render` every time. 
Is it?

**Comment by ianstormtaylor** [comment]
Hey @suhaotian, thanks for reporting this! I believe this is in connection to a bug that I just opened here: https://github.com/ianstormtaylor/slate/issues/112, and also to this improvement we can make: https://github.com/ianstormtaylor/slate/issues/65

Working on a fix for this now!

**Comment by ianstormtaylor** [comment]
Fixed in `0.1.15`!

**Comment by suhaotian** [comment]
@ianstormtaylor :+1:
