### ISSUE TITLE
Add note about debugging in the browser to Contributing.md

### ISSUE THREAD

**Issue by danburzo** [ianstormtaylor/slate#1010]
I was wondering how to use the `debug()` function that's called on various methods throughout Slate's codebase, and I found you can set `localstorage.debug = "*"` to enable it in the browser. 

I can make a PR if this is the appropriate usage, I just need a confirmation.

**Comment by tobiasandersen** [comment]
I also think that would be a good idea! The [info here](https://github.com/visionmedia/debug#browser-support) is pretty helpful.

**Comment by tobiasandersen** [comment]
I also think that would be a good idea! The [info here](https://github.com/visionmedia/debug#browser-support) is pretty helpful.
