### ISSUE TITLE
Editor component factory function

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#1013]
There are some `Editor` `props`, `schema` and `plugins` for example, which, for their nature, generally, remain constant over the lifecycle of the component.
Nevertheless keeping them as `props` forces us to check at each rendering if they are mutated even if this seldom happens.
Moreover, the way that check is done at moment is error prone; it just consists in an object reference comparison between the old and the new value. So those values can, in fact, change without triggering it.

For all these reasons I wonder if it isn't better to remove these `props` and, in place of them, introduce an editor factory function. Something like

```
createEditor(options: Object) => EditorComponent
```

where `options` is an object containing data passed before as component `props`

```
options = {
  plugins,
  schema,
  ...
}
```

What do you think?

**Comment by danburzo** [comment]
> Nevertheless keeping them as `props` forces us to check at each rendering if they are mutated even if this seldom happens.
Moreover, the way that check is done at moment is error prone; it just consists in an object reference comparison between the old and the new value. So those values can, in fact, change without triggering it.

The shallow comparison should be quite fast, as it only checks reference equality on a handful of properties. It will also ignore any change inside the properties, and I think discouraging mutating props is a good idea.

Additionally:
* `schema` is a plugin-like property, and is in fact a shortcut to defining a schema in a separate plugin.
* `plugins` can very well be variable throughout the lifecycle of the editor

But now that you mention, I *think* there might be a potential bug regarding the shallow comparison, where sending `placeholderStyle` as an object will unnecessarily call re-render but I'd need to check.

**Comment by danburzo** [comment]
As for the suggestion, I think that there exist several approaches to achieving what you want (Higher-Order-Component, extending the Editor class, creating a factory method), and it may be best to leave it to userland?

**Comment by danburzo** [comment]
Also I think the intention here is to only reset the Stack _once_ if any property changes, but it seems it may be resetting once for every property that changes:

https://github.com/ianstormtaylor/slate/blob/239d97fcad6d097d564674846a08924e78d2a503/src/components/editor.js#L147-L154

**Comment by AlbertHilb** [comment]
Hi @danburzo. :blush:

> The shallow comparison should be quite fast

Even the fastest comparison is too slow if it's unneeded! :grimacing:

> I think discouraging mutating props is a good idea

If we want discourage mutating props maybe we should require them to be immutable structures.

> plugins can very well be variable throughout the lifecycle of the editor

Yes, they can. But seldom with respect to how many times the `Editor` re-renders. And in such rare cases you should just re-create the editor component.

> there exist several approaches to achieving what you want (Higher-Order-Component, extending the Editor class, creating a factory method)

Indeed, this idea was born just writing a plugin in the form of High Order Component. At moment an author must bother to check at each rendering if `plugins` or `schema` are changed, and until mutable structures are allowed he cannot safety rely on shallow comparison.

**Comment by danburzo** [comment]
I agree that there may be bugs lurking when re-initializing some of the editor props. I found another example here (constructor for Editor component):

https://github.com/ianstormtaylor/slate/blob/239d97fcad6d097d564674846a08924e78d2a503/src/components/editor.js#L127-L134

Seems to be binding editor methods to the first stack, which in the meantime will be recreated, and so stack.plugins will have a different value.

**Comment by ianstormtaylor** [comment]
I believe this is slightly better now in `0.42` since proper "stacks" are created from each middleware in each plugin. Although since middleware are functions we can never guarantee that they don't change their behaviors over time.

That said, I'm going to close this out, because a factory would be strictly less flexible that the current solution, and folks can create their own factory from the current one if they'd like to. (Kind of like how HOCs are strictly less flexible than render props.)
