### ISSUE TITLE
React and ReactDOM appears in final webpack bundle

### ISSUE THREAD

**Issue by kvolkovich-sc** [ianstormtaylor/slate#1014]
Hi!
In webpack config we have externals field for `react` and `react-dom`

```
externals: {
  react: {
    root: 'React',
    commonjs2: 'react',
    commonjs: 'react',
    amd: 'react'
  },
  'react-dom': {
    root: 'ReactDOM',
    commonjs2: 'react-dom',
    commonjs: 'react-dom',
    amd: 'react-dom'
  }
}
```

When we import `slate` we get `react` and `react-dom` in final bundle (about 200KB redundant size).

> Use https://github.com/th0r/webpack-bundle-analyzer to inspect final bundle

It happens because  *html serializer* uses `ReactDOMServer` which implicitly requires  `react` and `react-dom`.

One of possible solution - import each slate part using explicit file path through whole project.

Another possible solution - creating custom **slate.js** file:

```
... all slate imports

... replace `Html` by copy-pasted **serializers/html.js** with removed `options.render`

... all slate exports
```

Then replace all slate imports `... from 'slate'` => `... from '../slate'` 

All it looks tricky.

@ianstormtaylor , do you have some thoughts on this?

**Comment by ianstormtaylor** [comment]
Hey @kvolkovich-sc I think this should be solved now with the separate packages!
