### ISSUE TITLE
Placeholder is selectable and prevents paste in IE 11

### ISSUE THREAD

**Issue by mahlero** [ianstormtaylor/slate#1015]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

Using IE 11, the text of the placeholder can be selected and if the cursor is placed somewhere else than at the beginning of the placeholder text, it is not possible to paste (using shortcut or context menu).

![test](https://user-images.githubusercontent.com/1461674/29511711-35b20a52-8660-11e7-867d-4b0271e90939.gif)

Tested with the rich-text example http://slatejs.org/#/rich-text in IE11 on Windows 7 and Windows 10.

#### What's the expected behavior?

The placeholder can not be selected and the cursor can not be placed somewhere within the placeholder text, preventing the user from pasting.

#### Research / Workaround

In slate, there is an editor element with `contenteditable` set to `true`. It contains the placeholder as a child which has `contenteditable`set to `false`. 

The HTML5 specs say: a `contenteditable=false` element within a `contenteditable=true` element is not editable.

I discovered that IE 11 seems to have a somewhat weird interpretation of the spec and does it the other way round: only child elements with `contenteditable=true` are not editable.

I tried to fix that issue by setting the placeholder element to`contenteditable=false` but that introduces some other weird behaviour.

My current workaround is to provide an own placeholder component that is placed as a sibling to the editor component. The downside is that I have to reimplement the show/hide logic.

**Comment by YurkaninRyan** [comment]
Should the placeholder just have `pointer-events: none` by default?  I think that would prevent this behavior.

**Comment by mahlero** [comment]
It already has `pointer-events: none` so that doesn't seem to work:
![image](https://user-images.githubusercontent.com/1461674/30420730-c8ea3cd0-993a-11e7-8e15-9130fab0d0c8.png)
(taken from http://slatejs.org/#/rich-text)

**Comment by ianstormtaylor** [comment]
@mahlero is this still an issue in the newest version of Slate?

**Comment by kudlajz** [comment]
@ianstormtaylor We're using version `0.33.4` and the problem still persists 😞

**Comment by Lukavyi** [comment]
We have the same issue

**Comment by ianstormtaylor** [comment]
I think this might be fixed in `slate-react@0.21`, could someone check?

**Comment by brendancarney** [comment]
Appears to be fixed: 
![ie11](https://user-images.githubusercontent.com/2984336/53288857-a31e5c80-3753-11e9-9d91-f4fa64df8b5c.gif)

**Comment by comerc** [comment]
I have the same bug for two or more placeholders (not only for IE 11, but for Chrome too):

![Снимок экрана от 2019-04-26 21-41-22](https://user-images.githubusercontent.com/1025241/56829354-2a7b6f80-686c-11e9-878f-d9b5a1ec25c8.png)

![Снимок экрана от 2019-04-26 21-29-20](https://user-images.githubusercontent.com/1025241/56829366-30715080-686c-11e9-963d-7fd9af345ed6.png)

(second image - it is [my solution](https://github.com/ianstormtaylor/slate/pull/2460#issuecomment-477987121) of placeholders for forced-layout)

Please reopen this issue.
