### ISSUE TITLE
JSFiddle template for Slate does not run in IE11

### ISSUE THREAD

**Issue by mahlero** [ianstormtaylor/slate#1018]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

The [JSFiddle template for Slate](https://jsfiddle.net/2zokvrvt/7/) from the [Contributing Page](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md) does not run in IE11 and there are error messages in the console.

![slate-jsfiddle-ie11-bug](https://user-images.githubusercontent.com/1461674/29519490-f335e6bc-867d-11e7-8046-f690f52df94b.jpg)

#### What's the expected behavior?

The JSFiddle template should run in IE11 so it is possible to submit code samples for bug reproduction.

#### Research / Workaround

I tried to fix the JSFiddle template and included babel-polyfill (https://cdn.polyfill.io/v2/polyfill.js?feature=es6) right before slate.js is included, switched the language from Babel/JSX to JavaScript 1.7 and used plain old javascript syntax - but that only produced other errors.

**Comment by kvolkovich-sc** [comment]
Fixed here https://github.com/ianstormtaylor/slate/pull/996, but not released yet

**Comment by mahlero** [comment]
Thanks, looking forward to the release!

**Comment by ianstormtaylor** [comment]
Should be released now!
