### ISSUE TITLE
Deleting a selected block causes the following block to get the deleted block's style

### ISSUE THREAD

**Issue by hubgit** [ianstormtaylor/slate#1021]
#### Do you want to request a *feature* or report a *bug*?

Report a bug

#### What's the current behavior?

When a block is selected by triple-clicking, then deleted, the following block takes on the style of the deleted block.

![slate-delete-block](https://user-images.githubusercontent.com/14294/29619852-152d65be-8814-11e7-9aea-560541ceb18f.gif)

https://jsfiddle.net/hubfiddle/ks2pmhy0/

macOS 10.12.6, Chrome 60, Slate current release.

#### What's the expected behavior?

The selected block should be deleted, and the following block should stay as it was.

**Comment by skogsmaskin** [comment]
This will be fixed with #1072 commit 50bc821
