### ISSUE TITLE
Horizontal Rules in markup?

### ISSUE THREAD

**Issue by anewusr** [ianstormtaylor/slate#1036]
Should a < hr > tag/dividing line that contains no children be implemented as a mark or as a block with custom behavior?

Not quite sure how to tackle this, so I would appreciate any input.

**Comment by dmitrizzle** [comment]
Definitely a block. I had it set up in my schema as:
```javascript
    divider: props => {
      const { node, state } = props
      const focus = state.isFocused && state.selection.hasEdgeIn(node)
      const className = focus ? "focus" : "nofocus"
      return <hr className={className} />
    },
```
Above adds a class name to your `<hr/>` when it's selected; it will be removed with backspace.

**Comment by YurkaninRyan** [comment]
@anewusr `isVoid`, is the property you should look up.  It was an a-ha moment for me.  Basically is just a node without editable content

**Comment by anewusr** [comment]
Excellent advice! Thanks @YurkaninRyan  and @dmitrizzle
