### ISSUE TITLE
Leaf Block Discussion

### ISSUE THREAD

**Issue by YurkaninRyan** [ianstormtaylor/slate#1039]
Recently, I've noticed bugs in `slate-edit-list` and `slate-edit-table`, where upon pasting, the inner most child would end up as the first block, and then after it the container would be pasted.  After digging into the code I think I found a couple of pain points.

`insertFragmentAtRange` does logic involving `firstBlock` and `lastBlock` being the same block.  I think this is where these two plugins start to fall apart.  `getBlocks` only returns leaf blocks, so you won't get your full table, or your bulleted list.  You'll get the inner most bullet, or a table cell.

Now, I know I've heard before that a lot of operations refer to Leaf Blocks, however, i'm wondering if that means we should rethink things like `wrapBlock`.  What do we need to fix here?  `insertFragment`'s behavior?

**Comment by ianstormtaylor** [comment]
Hey @YurkaninRyan, search issues for `insertFragmentByKey`, I think there's a discussion of it. Let me know if you think that would solve the issue. I might be misunderstanding though.

**Comment by YurkaninRyan** [comment]
@ianstormtaylor I think it just might, i'll take a crack at it
