### ISSUE TITLE
Bug - isEmpty at top level not working

### ISSUE THREAD

**Issue by tathagatbanerjee** [ianstormtaylor/slate#1050]
Bug

#### What's the current behavior?

On retrival of a state from the db, the isEmpty computed property is incorrect. 

![image](https://user-images.githubusercontent.com/11780602/30095667-594c4c5c-9317-11e7-88ed-165b770e04be.png)

Output - 

![image](https://user-images.githubusercontent.com/11780602/30095714-9c191d94-9317-11e7-889f-ec4e65a19151.png)

#### What's the expected behavior?

It can be seen that the raw.isEmpty is incorrect at the top level showing true, but correct at the lower List, where isEmpty is correct showing false, and the text can be seen.

I did not put in the JSFiddle as this seems pretty obviously an oversight. Am using "slate": "^0.21.4"

**Comment by ianstormtaylor** [comment]
Hey @tathagatbanerjee I think you want `state.document.isEmpty`. Definitely confusing, maybe we should change the name of `state.isEmpty` in the future to avoid confusion.
