### ISSUE TITLE
shouldComponentUpdate and Selection

### ISSUE THREAD

**Issue by YurkaninRyan** [ianstormtaylor/slate#1058]
While upgrading `slate-sticky-inlines` to `slate@0.22.4` I noticed some strangeness with #1029 and inlines.  For `blocks` it works perfectly, but `inlines` aren't guaranteed to re render even if their selection has changed, because a parent node could choose to not update, which disrupts the entire chain.

Should it be that the only nodes the implement shouldComponentUpdate are leaf nodes/text nodes?  It feels like every node should have a chance to say whether or not it should update.

@tobiasandersen

**Comment by ianstormtaylor** [comment]
Actually, looking at that PR again, I think it will also fail for nested blocks/inlines, since `state.blocks` and `state.inlines` only ever contains the leaf blocks and root inlines. So if it's nested, it will never show up as selected?

**Comment by YurkaninRyan** [comment]
So I wonder what the possible solutions are 🤔  is Selection Changes the only real use case we have where parents wouldn't easily know if their children would need to update or not?

**Comment by tobiasandersen** [comment]
You're right, I didn't take those cases into consideration. Not sure what the best solution is though. We could always take back the old logic as well, but we still wouldn't cover all use cases, right?
