### ISSUE TITLE
undo steps don't mimic other rich-text editors

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1069]
Specifically looking at the difference between Slate and Google Docs. Right now Slate requires undoing extra times, because there are undo steps that are purely for moving the selection to the right place.

For example in Google docs, you just have two undo steps:

![](http://g.recordit.co/MMiHRLyNbo.gif)

But in Slate, for the same edits, you have three (the second is a selection move):

![](http://g.recordit.co/plvFTMSNFX.gif)

This turns out to be slightly harder to fix than I thought, since it's tricky to get the right undo UX while also maintaining the properly saving logic. If anyone wanted to research and dive into this to help it would be super appreciated!

**Comment by YurkaninRyan** [comment]
This is a super hard issue.  I've written logic that skips through any undo/redo operations that only have a single `set_selection`.

However, I conditionally use this logic,  because sometimes that `set_selection` is very important.  Also it seems a `set_selection` is applied to undos when the editor is blurred?  It seems a lot easier to get into a set_selection loop when undoing/redoing now

**Comment by ianstormtaylor** [comment]
@YurkaninRyan hmm you might be right about the blurring. Previously `onBlur` wasn't using `save: false` either, but the new history changes might have exposed that issue. If that's the case, I'd gladly accept a PR that fixes that!

And I totally agree with you, this is a hard issue to wrap your mind around. I refactored a few different ways when trying to solve it for `History` and never found the right now, so left it unfinished.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
