### ISSUE TITLE
Doesn't work on ipad

### ISSUE THREAD

**Issue by fractalf** [ianstormtaylor/slate#107]
ipad 2, demo on slatejs.org is just blank, not working.
Tried ff, chrome and dolphin

**Comment by oyeanuj** [comment]
Additionally, the formatting options on the context menu need to be disabled on iOS devices since they don't really take effect.

**Comment by ianstormtaylor** [comment]
Hey @fractalf thanks for reporting this! What version of Safari/iOS is your iPad running?

**Comment by fractalf** [comment]
ios 8.3. no safari, ff, chrome & dolphin

**Comment by ianstormtaylor** [comment]
Fixed with the latest release! A rogue dev dependency in the examples wasn't compiled for ES6 before being published to npm, so I swapped it out. Thanks @fractalf!

**Comment by fractalf** [comment]
Still the demo don't work at http://slatejs.org/.
I see that it now redirects to http://slatejs.org/#/rich-text?_k=ezj8yw , but the page is blank

**Comment by ianstormtaylor** [comment]
@fractalf could you enable the dev console and copy any errors that are output? I've tested it on iOS `9.3.1` in Safari, Chrome and Firefox and it works in that case. Must be some other Javascript APIs that weren't available in `8.3`.

**Comment by fractalf** [comment]
Sorry, I don't have a mac, so that would just be too much hassle ;)
And I like to stay on 8.3 so I don't want to upgrade.
Maybe you can run it in some emulator with 8.3?
