### ISSUE TITLE
Plain serializer runs into 'Text.isTextList is not a function'

### ISSUE THREAD

**Issue by stefanheine** [ianstormtaylor/slate#1076]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

Every click of keypress in the **Plain** editor results in an error message in the console:
**Uncaught TypeError: Text.isTextList is not a function**

https://jsfiddle.net/stheine/2zokvrvt/175/

Linux, Firefox & Chrome, **Slate 0.22.8**

#### What's the expected behavior?

No error

**Comment by YurkaninRyan** [comment]
Duplicate of #1073 will be fixed with #1071

**Comment by ianstormtaylor** [comment]
Thanks @stefanheine!
