### ISSUE TITLE
add `isSelected` prop to Nodes?

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1080]
We've [got issues](https://github.com/ianstormtaylor/slate/issues/1058) with re-rendering and maintaining `shouldComponentUpdate` for `Node` components, because people want to be able to toggle whether they are selected or not. I was just wondering, what if we just pass down a `props.isSelected` property that would simplify people having to re-invent the wheel all the time. 

Since we're going to have to calculate this logic already for `shouldComponentUpdate` I don't think it will have any negative performance impact.

And that way we could standardize selection handling for void nodes. Allowing us to potentially more gracefully handle the [triple-click problem](https://github.com/ianstormtaylor/slate/issues/752) because we'd just special-case that to be `isSelected: false`.

cc @sethmcleod @YurkaninRyan @tobiasandersen

**Comment by YurkaninRyan** [comment]
This is a great idea

**Comment by sethmcleod** [comment]
Agreed, I think this would be a great solution for the _triple select_ issue.

**Comment by tobiasandersen** [comment]
Yeah I also think that'd be really great!
