### ISSUE TITLE
triple-click to select a whole block doesn't work on certain blocks

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#109]
In the current examples it doesn't work on the;

- 2nd paragraph in `rich-text`.
- 1st paragraph in `auto-markdown`.
- 3rd paragraph in `auto-markdown`.
- 1st paragraph of `tables`.

Only thing I can see right now that they all have in common is that they end in a `:`. Odd!

**Comment by mathieudutour** [comment]
no, the thing they have in common is that they are follow by a non-standard block

**Comment by ianstormtaylor** [comment]
Haha that makes a lot more sense. I'll check this one out soon!

**Comment by ianstormtaylor** [comment]
Looks like this is fixed in the lastest releases now, not sure what was going on.
