### ISSUE TITLE
consider combining `Change` and `State`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1094]
Warning: this isn't a well fleshed out idea, just a quick thought that might solve issues. If you have thoughts, please tell me them!

---

I was thinking about this. It seems like there are a few cases where you actually end up wanting to receive the `state` and the `operations` at the same time, but ideally not by receiving a `Change` object, but by receiving just a `State` to render.

(One of them is `isNative` which sounds like it's going away, so take that with a grain of salt.)

Right now you either receive `Change` or `State`.

At first it seemed weird for `State` to contain the previous `operations` that were applied to it, but then I realized that it already contains `History` which is exactly that. So that's not weird actually, just a mis-conception.

There's no real technical reason why the two couldn't be combined, and that each state would have a record of the operations that led to it from the previous state.

History might even be re-structured to both keep track of groups of operations that constituted a "change", as well as "save points"—right now it doesn't keep the change groups, choosing the distort them in favor of keeping save points.

---

Just a vague idea, but it might be useful later. And for others to think about.

**Comment by isubastiCadmus** [comment]
@ianstormtaylor it would be great if slate have a way to differentiate between "undo/redo/cut/paste" on "save points". now I believe it can be done but with external "OT" tracker using combination of keyDown, toolbar and onChange.

**Comment by ianstormtaylor** [comment]
@isubatiCadmus can you elaborate? Why do you need that?

**Comment by isubastiCadmus** [comment]
@ianstormtaylor just for clearer differentiation as you might want to understand the actual action(redo, undo, cut, paste) instead of just got text/style inserted/removed from the state. This could be useful for debugging purposes as well

**Comment by TimYi** [comment]
@ianstormtaylor `Change` now contains a state, I think it's reasonable. Any change or operation is only available on it's born document state. So a Change object contains it's current state is necessary to generate later operations.
If ignore the process which produce changes, like `onKeyDown` method, I only need the current state to render, and the operations for collaborating need in `onChange` method.
`Change` does need to contain a state object, then api can be changed from Change.addMark() to Change.addMark(State). But in concept, a change is only available on it's born state, it has a state in mind.

**Comment by ianstormtaylor** [comment]
Closing since I'm not sure this is reasonable anymore. Could be opened in the future if anyone has convincing ideas or other thoughts though!
