### ISSUE TITLE
Issue selecting inline void nodes.

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#1102]
Open "Emojiis" example, place the caret on the left of an emojii ((few chars away), then move the caret to the right, the emojii does not appear selected (no blue outline).
If you select the emojji with a mouse click, the blue outline appears but remains there even if you move away the caret pressing left or right arrows.

**Comment by AlbertHilb** [comment]
The problem stays inside the `Node` `shouldComponentUpdate` [method][1]:

```
 if (n.isSelected != p.isSelected) return true
```
The above line does not trigger update of a node (and, therefore, of its children) that is and, already, was selected, even in the case the selection state of its children is changed.

[1]: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/node.js#L119

**Comment by YurkaninRyan** [comment]
I believe https://github.com/ianstormtaylor/slate/pull/1124 would fix this issue

**Comment by AlbertHilb** [comment]
Thanks to have pointed me to #1125. :blush:
I've just proposed another possible solution (#1125).

**Comment by ianstormtaylor** [comment]
Hey you two, thanks for these! I'm worried about a few things... 

For @YurkaninRyan's PR I worry about the performance of basically saying that all Block and Inline nodes will always re-render. I don't think we can get away with this on large documents. 

And for @AlbertHilb's I'm worried that were complicating the `isSelected` variable in a way that's going to cause UX friction just to solve an internal issue. 

I think there's actually a solution that's a restricted version of #1124 that has better performance:

If we only return `return true` if `!Text.isTextList(nextNode.nodes)` AND if the node is currently selected and will stay selected. Because it seems like it only needs to trigger for nested inline/blocks, and only if their parent maintains its selected true state.

Let me know what you think, and if either of you are down to try that!

**Comment by ianstormtaylor** [comment]
(And by `return true` I mean `false` :smile:)

**Comment by YurkaninRyan** [comment]
But what if you leave the parent completely, while also leaving the child.  With that logic the child wouldn't update because the parent would return false i believe

**Comment by ianstormtaylor** [comment]
Not sure exactly if I follow. But by `return false` I actually mean not returning man but just also not returning true from that condition :smile: sorry about that! Basically just restricting #1124's returning true with further checks to make it more performant.

**Comment by AlbertHilb** [comment]
> I'm worried that were complicating the isSelected variable in a way that's going to cause UX friction just to solve an internal issue.

I does understand what you mean. In #1125 `isSelected` remains untouched.
It only changes two chars :wink:, from
```
if (n.isSelected != p.isSelected) return true
```

to
```
if (n.isSelected || p.isSelected) return true
```

**Comment by YurkaninRyan** [comment]
Here is my comment in #1124  that outlines what I'm trying to say a bit better @ianstormtaylor 

```
This assumes your one condition which is (n.isSelected && p.isSelected)
Say your selection is inside a child inline. You click on another line entirely. now:

p.node.isSelected is true
n.node.isSelected is false
The child still has the isSelected prop of true
In this scenario, you are also no longer selecting the child, but since we would return false because the parent isn't staying selected, the child never gets a chance to update it's props.

The reverse is true as well. What if you click from a line, into a line that wasn't previously focused, into a child inline. Now we have:

p.node.isSelected is false
n.node.isSelected is true
the child still has isSelected prop of false
This also wouldn't update the inline to have the proper isSelected. The parent somehow needs to know if it has a child that needs to be allowed to update
```

@AlbertHilb I think your check could also benefit from `Text.isTextList`. I think what you have is
 a more performant version of what i'm trying to do

**Comment by ianstormtaylor** [comment]
@AlbertHilb ah oops, sorry! I was on my phone and got confused by the description I think. But your solution actually sounds good.

@YurkaninRyan you're totally right, I wasn't considering the reverse case where the selection moves away at all. Good call.

So it sounds like #1125 is the way to go then?

**Comment by YurkaninRyan** [comment]
I would think so, that along with the TextList check should be a more performant approach that hits all cases :+1:
