### ISSUE TITLE
focus the editor

### ISSUE THREAD

**Issue by mathieudutour** [ianstormtaylor/slate#111]
* when trying to focus the editor using `Editor.focus()`, nothing happens
* when manually creating a `Transform` with `focus()` (with or without `collapseTo{Edge}`), nothing happens
* when trying to trigger the `focus` event on the div (`findDOMNode(this.refs.editor).focus()`), the editor does get focused but:
    * an error occurs: `Uncaught TypeError: Cannot read property 'key' of null` in `normalizeKey()` in `node.js`
    * the first block is getting duplicated and messed up the entire editor afterwards

**Comment by ianstormtaylor** [comment]
Interesting, question for you: what are the `state.selection` object's properties set to when `focus()` is triggered? Off the top of my head, my guess is this is because it's on initial focus, before the selection has a proper value? Might not be though.

**Comment by mathieudutour** [comment]
yeah, the selection is on another input

**Comment by ianstormtaylor** [comment]
Okay, should be fixed now in `0.1.16`! I chose to remove the idea of selections being "unset" where they don't have a `anchorKey` or `focusKey` defined, and instead they just get normalized to have the first text node focused. So by default it will focus to the beginning of the editor.

**Comment by mathieudutour** [comment]
Yep it's fixed 👍
