### ISSUE TITLE
fix Node circular dependencies

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1112]
There's an issue where `Block/Inline/Document` all depend on `Node` because they inherit from it. But `Node` also depends on them to do a few things, which causes a circular dependency. Usually it's fine, but sometimes it results in bugs. Need to fix this so it doesn't keep cropping up. I think we can just use `import` at the top to solve it, but we might need to use `require` at runtime if not.

**Comment by zhujinxuan** [comment]
Shall we close this issue, as https://github.com/ianstormtaylor/slate/pull/1881 is merged?

**Comment by ianstormtaylor** [comment]
Sounds good, thanks @zhujinxuan!
