### ISSUE TITLE
add doc of best practices for writing plugins

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1121]
I think this would probably be useful, keeping track of some best practices:

- Always write plugins as a function that takes an `options` object, for future-proofing.
- When accepting defaultBlock/Mark/etc. arguments, use the `Node.create()` and `Node.createProperties()` static methods for standardizing these, just like core does.
- When allowing customization of what changes will actually be applied to the document, use a change function with signature `(change, ...args)` like core does.

If anyone thinks of others, feel free to add them here so we don't forget!

**Comment by oyeanuj** [comment]
Something I've liked from your plugins and incorporated in my code is the use of `onlyIn` and `exceptIn` options - so that the plugins can tailor their behavior based on where the action occurs.

**Comment by ianstormtaylor** [comment]
@oyeanuj Ah yes agreed! Actually I realized that I want to change up how those work by creating a separate plugin soon called `slate-only-in` that you can wrap any other plugins with. That way it doesn't have to be repeated in all plugins code bases

**Comment by oyeanuj** [comment]
Another idea, which was triggered by #1111, is that having templates or best practices based on types of plugins? I frequently have plugins that both introduce `schema` and behavior. So I think one of the best practices would be to expose each separately. This is most helpful when building `readOnly` editors where any extra behavior code is just dead weight. 

Somewhat unrelated: I recently came upon (`SlateLiteRenderer`)[https://github.com/GitbookIO/slate-lite-renderer], which seems to be the above idea but for the core editor.

**Comment by Soreine** [comment]
@oyeanuj `slate-lite-renderer` was just an attempt at making an optimized renderer for Slate, in read-only mode. At first we thought it that Slate was doing a lot of work that is not needed for simply rendering a document. Then we realized that the initial normalization was responsible for 80% of the time spent to render the document. And since we need normalization, as a retro-compatibility layer for old documents in our database, this project will probably be stopped.

**Comment by ianstormtaylor** [comment]
Added to the [Plugins guide](https://docs.slatejs.org/guides/plugins)!
