### ISSUE TITLE
Drag&Drop is broken

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#1123]
Open an Example, select a word, drag it around, then drop it.
The word disappears in the original position but nothing is inserted in the drop position.
That happens because the drag&drop `fragment` is empty.
This regression has been introduced by PR #836.

**Comment by YurkaninRyan** [comment]
@ianstormtaylor  Was wondering if you had any insight on what should be going on at this step inside `onDragStart`

```js
    // If it's a node being dragged, the data type is already set.
    if (data.type == 'node') return

    const { state } = this.props
    const { fragment } = state
    const encoded = Base64.serializeNode(fragment)

    setTransferData(dataTransfer, TRANSFER_TYPES.FRAGMENT, encoded)
```

From some debugging, it looks like `state.fragment` is always going to return an empty document node?  When you select a word, you get a data-type `html` with html, but then we add this empty document fragment to the `dataTransfer` which gets consumed in `onDrop` inside of `Content` here

```js
    const window = getWindow(event.target)
    const { state, editor } = this.props
    const { nativeEvent } = event
    const { dataTransfer, x, y } = nativeEvent
    const data = getTransferData(dataTransfer)
```

However, now that there is a fragment added, data thinks it's main type is always going to be `fragment` and `fragment` will always be empty.

Do you know what that `state.fragment` line might be trying to do?  I tried to chase it down, but I had trouble finding it after the monorepo line to try and blame it

**Comment by ianstormtaylor** [comment]
I'm not totally sure because I haven't looked at the drag/drop functionality in a long time. But shouldn't the fragment be whatever is currently selected instead of empty? Then the problem would be solved?

**Comment by YurkaninRyan** [comment]
Looking at it deeper it seems to be a bug with `getFragmentAtRange`.  When the `startKey` and the `endKey` are the same, the `startIndex` actually ends up 2 higher then the `endIndex`, which causes no nodes to come from the slice.

**Comment by AlbertHilb** [comment]
Unfortunately this bug report should be reopened. :cry:
Open "Rich Text" example, select a word ("semantically" for example), drag it around then drop it onto another position (right after the word "turn" for example), you'll get a messed up text.

**Comment by ianstormtaylor** [comment]
@AlbertHilb commit incoming to fix it.

**Comment by AlbertHilb** [comment]
Great! :blush:
