### ISSUE TITLE
Pasting external HTML does not work with Slate example

### ISSUE THREAD

**Issue by dmitrizzle** [ianstormtaylor/slate#1129]
### Current behaviour

Right now pasting HTML into `PasteHTML` example works **only if I was to copy HTML from Slate editor**:

![slate-to-slate-paste](https://user-images.githubusercontent.com/8587882/30461863-af746de6-99eb-11e7-8cb4-b97dfffe6c8e.gif)

**However, if I am to paste HTML from any other source Chrome 60 throws an error:**

![html-to-slate-paste](https://user-images.githubusercontent.com/8587882/30461888-d26da68c-99eb-11e7-8cf9-f7c936797a6f.gif)

```
build.prod.js:4902 Uncaught TypeError: Cannot read property 'find' of undefined
    at Object.deserialize (build.prod.js:4902)
    at Html.deserializeElement (build.prod.js:98382)
    at build.prod.js:98341
    at Array.forEach (<anonymous>)
    at Html.deserializeElements (build.prod.js:98340)
    at next (build.prod.js:98368)
    at Html.deserializeElement (build.prod.js:98402)
    at build.prod.js:98341
    at Array.forEach (<anonymous>)
    at Html.deserializeElements (build.prod.js:98340)
```

### Expected behaviour

Pasting HTML from any source should work.

### Context
I am using Chrome 60 on macOS 10.12.6, presumably Slate v0.24.1 - since that's the latest version posted (but I can't guarantee that's the same version as what slatejs.org uses in the above examples; above gifs were created shortly after v0.24.1 release was posted).

There's an issue #734 which addresses a similar problem but _I don't think it's relevant anymore_, since it described actions with much older versions of Slate. It was opened mentioning v0.19.16.

### More context
v0.20.7 > v0.21.0 `parse5` replaced `cheerio` but pasting caused JavaScript errors (see #948) which were fixed with #985. I’m not sure if pasting HTML has been tested for with the above PR, since the functionality never returned for pasting form the external sources.

### My understanding
After DOMParser has replaced Cherio in Slate pasting HTML from external sources became broken. Most likely it's because there's no test to check for this case and a bug has slipped in.

**Comment by ianstormtaylor** [comment]
Hey @dmitrizzle thanks for opening this. Can you try with copying a more regularly structured piece of content? Like maybe just a section of a GitHub readme. It could be just a problem with certain bits of HTML in the copy.

**Comment by travisperson** [comment]
A simple example is pasting a div with an inline link.

--------------
<div>This is a <a href="#">link</a> inline with text</div>

--------------

**Source**
```html
<div>This is a <a href="#">link</a> in line with text</div>
```

**Comment by dmitrizzle** [comment]
It seems that pasting any text that isn't plaintext causes this error. Below are gifs of me pasting a large section of readme and Travis' simple link example:

#### Readme copy-paste:
![paste-readme](https://user-images.githubusercontent.com/8587882/30509189-95cf3efe-9ad4-11e7-98b9-faeee0ba2b63.gif)

#### Simple link copy-paste:
![paste-link](https://user-images.githubusercontent.com/8587882/30509192-a8809aa2-9ad4-11e7-8ce0-4352c62c3ecf.gif)

#### Pasting text containing no HTML (works):
![paste-plaintext](https://user-images.githubusercontent.com/8587882/30509219-2c751216-9ad5-11e7-9799-80319840f126.gif)

**Comment by YurkaninRyan** [comment]
Hey everyone,

This bug is due to to the fact that the upgrade makes it so we now get HTML-like elements.  `.find` won't work for two reasons. 

1. `node`.attrs isn't a thing anymore, you need to do `.attributes`
2. `.find` isn't going to work, because you get a named node map back from `.attributes` so you would have to turn it into an object.

Basically, the example just needs to be updated to handle the new nodes

**Comment by ppvolto** [comment]
Hey everyone,
i current have the same Problem with Pasting and this error only triggers when i have All elements in the Editor selected for Replacement when one Element is not Fully Replaced then it works without a Problem...

**Comment by ianstormtaylor** [comment]
Hey @ppvolto can you open a new issue with a GIF explaining your use case? I believe this one was solved.
