### ISSUE TITLE
blink when typing chinese words

### ISSUE THREAD

**Issue by imlgm** [ianstormtaylor/slate#114]
when I using slatejs editor and typing chinese words, there are a few wired responses like blinking and words lost, and  deleting do not work correctly.

I made a screen recording put it in youtube becuase uploading video  was not allowed  here。
 
[Demo video](https://youtu.be/YVfjg7GmY-w)

**Comment by ianstormtaylor** [comment]
Hey @imlgm thanks for reporting this! I think this is probably the same issue as in https://github.com/ianstormtaylor/slate/issues/74 for composition-based input.

**Comment by ianstormtaylor** [comment]
Hey @imlgm I've just added the most basic composition support in `0.2.2`, could you test it out again and see if that works for you? Thanks!

**Comment by imlgm** [comment]
@ianstormtaylor Hi, I tested the 0.2.2 version, it seems the blink problem is gone, but a worse bug appeared, [Demo Video](https://youtu.be/u_actNqmDTo)
I used NoisyTyper to indicate the typing : ).

**Comment by imlgm** [comment]
![image](https://cloud.githubusercontent.com/assets/5555305/16937943/d3841422-4da5-11e6-8a93-1e38f5846b31.png)
console log

**Comment by ianstormtaylor** [comment]
Thanks for the second video @imlgm! I think I've narrowed it down to the bug being thrown whenever compositions start in an empty block. Looking into this now!

**Comment by ianstormtaylor** [comment]
Okay @imlgm, I've just published `0.2.5` which should fix this issue! Can you let me know if everything works as you'd expect now?

**Comment by imlgm** [comment]
@ianstormtaylor Hey, I updated the code to version 0.2.7 and run the demo again, this bug seems not being fixed. After I pressed the Enter and tried to type  chinese words, it  crushed again.

![image](https://cloud.githubusercontent.com/assets/5555305/16973543/00d46a8c-4e67-11e6-8e8a-71443a9938c6.png)

The same error as yesterday
![image](https://cloud.githubusercontent.com/assets/5555305/16973552/18be8704-4e67-11e6-8768-ca390ca33910.png)

**Comment by ianstormtaylor** [comment]
Hey @imlgm by any chance did you not run `make dist && make examples` to update the example build? Would you mind trying the same thing on http://slatejs.org ? I can't reproduce it like I could before.

**Comment by imlgm** [comment]
@ianstormtaylor yes, I can't not reproduce it too ^^.  Good job!
