### ISSUE TITLE
Rename of "el.children" to "el.childNodes" is not mentioned in Changelog

### ISSUE THREAD

**Issue by sdemontfort** [ianstormtaylor/slate#1144]
#### What's the current behavior?

Between 0.23 and the latest, it seems `el.children` was renamed to `el.childNodes` in the HTML Serializer rules.  This is not documented in the Changelog.md

#### What's the expected behaviour

Mention the change as a breaking change in the appropriate version (not sure which version)

I would submit a PR but not sure exactly when the change happened :)

**Comment by ianstormtaylor** [comment]
@sdemontfort I think this happened in [`0.21`](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#0210--july-20-2017)?

**Comment by sdemontfort** [comment]
Oh okay. Was it mentioned in the 0.21 Changelog? I can't see it in there.

**Comment by ianstormtaylor** [comment]
The HTML serializer change is mentioned there, although it could be expanded with common places that need to change if you want to PR!
