### ISSUE TITLE
After undo using apply cause strange bugs

### ISSUE THREAD

**Issue by testbuddy** [ianstormtaylor/slate#1151]
I dont know if its a bug in my code but when i using 
>       state = state
>         .transform()
>         .undo()
>         .apply();
i can go back more then allowed, which result in an error screen. When i dont use apply() it works as expected. Is this a bug in general ? Or did i do something wrong in my code ?

**Comment by YurkaninRyan** [comment]
Could you please give some more context on this or show a JSfiddle?  It's not obvious what's going on, or what version of Slate you are even using

**Comment by testbuddy** [comment]
sry that it takes so long but this is my first time with jsfiddle :(

(https://fiddle.jshell.net/ad61x74c/1/)

just open the console and enter some letters in the editor. Then press multiple times the undo button. There should be a foreach error. If i write the undo function like : 

```
    let { state } = this.state;
    if (state.hasUndos) {
      state = state
        .transform()
        .undo();
      this.setState({ state: state.state });
    }
```
no error occurs.

**Comment by YurkaninRyan** [comment]
I get the feeling that you are on a new version of slate that uses `change`.  Can you `console.log` the state you are calling `transform` on here?  Does it log as a `Change`?

In the newer versions of slate you don't call `transform` anymore you call `change` to turn it into a change object (which has state as a property on it ).  Also, you no longer call `apply` as it's been deprecated.

**Comment by YurkaninRyan** [comment]
I'm not sure if that Fiddle has been saved either, it's throwing errors for me, can you double check?  I do that all the time XD

**Comment by testbuddy** [comment]
I use the version 0.20.4. When i try to use `change` on the state i get an error. With `transform` it is working.  
Hmm dont know, i try the jsfiddle on a second pc and it is working. I try another one. This time with an jsfiddle account.

(https://jsfiddle.net/csnk/9o8d8Ltd/)

**Comment by YurkaninRyan** [comment]
You are using a version of Slate where `hasUndos` was broken I believe.  You are going to need to get the `size` or `length` of `history` (it's located on state at state.history.undos) and use that to figure out if you can undo or not.  I don't think this has anything to do with the use of apply or not

**Comment by testbuddy** [comment]
Okay thank you :)
