### ISSUE TITLE
Error when calling `focus()` on an empty editor

### ISSUE THREAD

**Issue by rgrove** [ianstormtaylor/slate#1161]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

Calling `focus()` on an empty editor after it's mounted causes an exception:

```
Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: null
    at normalizeKey (https://npmcdn.com/slate@0.25.1/dist/slate.js:14384:9)
    at Document.getFurthestAncestor (https://npmcdn.com/slate@0.25.1/dist/slate.js:12810:13)
    at Document.object.(anonymous function) [as getFurthestAncestor] (https://npmcdn.com/slate@0.25.1/dist/slate.js:19296:28)
    at Document.getSelectionIndexes (https://npmcdn.com/slate@0.25.1/dist/slate.js:13493:26)
    at Content.render (https://npmcdn.com/slate-react@0.1.8/dist/slate-react.js:8409:30)
    [ ... ]
```

This was working as recently as 0.24.5, so the breakage must be pretty new.

https://jsfiddle.net/rgrove/sjcc7p0e/2/

![kapture 2017-09-21 at 14 47 08](https://user-images.githubusercontent.com/1465/30720409-31fac374-9edc-11e7-9173-1999608762e4.gif)

#### What's the expected behavior?

The editor should be focused.

**Comment by ianstormtaylor** [comment]
Hey @rgrove, in this case there isn't anything to "focus" because there are no nodes in the editor's `document`. If you change the initial state to have at least one node this should go away.

**Comment by ianstormtaylor** [comment]
Actually, maybe you're suggesting that it should not throw an error, which seems very reasonable to me 😄  if you want to PR!

**Comment by rgrove** [comment]
> Actually, maybe you're suggesting that it should not throw an error, which seems very reasonable to me 😄 if you want to PR!

Thanks for the guidance!

I took a stab at this, but it looks like `focus()` was a red herring. It turns out even trying to type in an editor that's initially empty leads to errors at various levels since the initial range's `startKey` and `endKey` are always `null`. I'm not sure if that's expected or not, so I didn't dive in further. Seems easier just to ensure the editor always has at least one node.

**Comment by skogsmaskin** [comment]
It could warn and suggest to write a schema ormalization rule.

**Comment by anewusr** [comment]
I don't think this is a red herring. 

After upgrading to 0.25.1, I get this error whenever I call "focus", i.e. `myEditor.focus()` 

Focus works fine when clicking into the editor, however. 

``` 
   state = {
      state: html.deserialize('<p></p>')
   };

    focus() {
        const { state } = this.state;
        const change = state.change().focus();
        this.onChange(change);
    }

    onChange = (change) => {
        let {state} = change;
        this.setState({ state })
    };
```
![screen shot 2017-09-25 at 1 20 06 am](https://user-images.githubusercontent.com/23392285/30793398-b1b5ae66-a18f-11e7-85d3-613528d244f8.png)

**Comment by anewusr** [comment]
After further testing, clicking first into the slate editor will ensure that all future focusing via a ref calls will work without errors. 

I set a debugger on the slate editor's `setState` but couldn't find a reason why the pre-click state refuses to be programmatically focused.

**Comment by YurkaninRyan** [comment]
I would be interested in what is getting passed into that `getFurthestAncestor` call, that seems to be where it is dying.  I would assume that it's undefined or something and that there neesd to be an edge case for that

**Comment by anewusr** [comment]
@YurkaninRyan a `null`. When clicking a "6" is passed instead. 

I have worked around the issue by replacing the contents of the "focus" method with:
```
        setTimeout(() => {
            ReactDOM.findDOMNode(this.refs.editor).focus();
        })
```

The pre-focus state being unable to accept focus points to a deeper issue which will likely feed into another bug into the future. I still have to learn the ins-and-outs of slatejs before I can begin submitting PRs.

**Comment by ms88privat** [comment]
Why was this closed? We are also running into this.

The solution above doesn't work for me. It will not focus the editor content

**Comment by comerc** [comment]
My solution:

```js
    const { editor } = this.props
    if (!editor.value.selection.isFocused) {
      const containerNode = this.containerRef.current
      const documentNode = containerNode.querySelector(`[data-key="${editor.value.document.key}"`)
      documentNode.focus()
    }
```

Enjoy!
