### ISSUE TITLE
Drag&Drop issue

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#1170]
Open "Images" example (on Chrome or Firefox), select a word and drag it over the image, the feedback shows a caret on the left side of the image but on drop the word is removed from the original position and nothing is inserted at the image side.

**Comment by ianstormtaylor** [comment]
Hey @AlbertHilb I think this issue is no longer there now, although it seems like dropping on images doesn't work entirely? Either way, I'm going to close this one, but feel free to open more!
