### ISSUE TITLE
Selection sync issue on drop

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#1173]
1. Open an example, "Rich Text" for instance, 
2. select a word,
3. drag&drop the word into another place in the document, let X be the position of the caret after the drop,
4. move the cursor to another position, Y, with the arrow keys,
5. press backspace,
6. a char is deleted at position X.

**Comment by tobiasandersen** [comment]
This sounds very related to https://github.com/ianstormtaylor/slate/issues/907.

**Comment by ianstormtaylor** [comment]
Here's a GIF:

![](http://g.recordit.co/9rcSW1rdDI.gif)

Interestingly, it seems to only happen in certain scenarios?

**Comment by tobiasandersen** [comment]
I can confirm that this is the same issue as #907, and that it's a problem with React and not Slate.

**Comment by tobiasandersen** [comment]
Should be ok to close this one now with #1309
