### ISSUE TITLE
Link example partly not functional

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#118]
Not sure if I am following the instructions incorrectly in the example (using Chrome 52 on Mac) but this part of the example doesn't seem to work for me -

> if you want in on a little secret, copy a URL to your keyboard and paste it while a range of text is selected.

Nothing happens when I do that apart from the text just being pasted.

Additionally, if I just type www.google.com or http://www.google.com, the link is not detected either but I am not sure if that is out of scope or what the example was trying to show.

**Comment by ianstormtaylor** [comment]
Sorry about that, so secret I forgot to implement it. Just added on master!
