### ISSUE TITLE
Empty Blocks don't show a selection when selected by highlight

### ISSUE THREAD

**Issue by YurkaninRyan** [ianstormtaylor/slate#1181]
You can recreate this by just making a bunch of empty lines in any of the examples and highlighting them.  I'm proposing that instead of not showing anything, it should show a highlight as if there was a space there.

I think this could be achieved by replacing the leaf code that renders a `br` and instead render a span with `display: block` that includes one of the browser specific spaces.

**Comment by Slapbox** [comment]
I solve this with CSS. There may be unforeseen consequences to this, but I've not noticed any yet.

```
.myEditor p::before {
    content: " ";
}
```

**Comment by ianstormtaylor** [comment]
Open to any working solutions for this! As long as they don't add adverse effects in browsers

**Comment by Slapbox** [comment]
I'm actually not even seeing this anymore in Chrome on the Rich Text example without any changes. @YurkaninRyan what browser and which example are you seeing this issue in?

**Comment by ianstormtaylor** [comment]
@Slapbox I still see this behavior with Chrome. For example:

![](http://g.recordit.co/ku4Q1WxbkX.gif)

**Comment by Slapbox** [comment]
I also see this behavior in Chrome 61. I wonder what build I was running 23 days ago.

It's possible I was playing with a tab I had been experimenting with, but I'm almost certain I had opened a new tab to be sure.

**Comment by brendancarney** [comment]
Duplicat of https://github.com/ianstormtaylor/slate/issues/838
