### ISSUE TITLE
slatejs.org does not work in IE 11

### ISSUE THREAD

**Issue by echenley** [ianstormtaylor/slate#1186]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What's the current behavior?

Via browserstack:

![screen shot 2017-09-27 at 11 31 21 am](https://user-images.githubusercontent.com/6344219/30925455-880ae9fc-a377-11e7-9836-854ab1005ed0.png)

None of the examples seem to work, and errors are thrown when switching between them.

**Comment by kvolkovich-sc** [comment]
In our we added array es7 polyfill for `Array.prototype.includes`

https://github.com/OpusCapita/react-markdown/blob/3396bd9653e8c4c86484681cc8a13868422354b1/config/doc/webpack.config.js#L16

Maybe it related to this issue.

**Comment by ianstormtaylor** [comment]
Hey @echenley thanks for reporting this. I'm going to close this one because it doesn't have enough information for us to fix the issue. But please do open another issue with the breaking cause and we can hopefully fix it. Like @kvolkovich-sc mentions, polyfills are needed for IE11.
