### ISSUE TITLE
IE11 Selection Blur Bug

### ISSUE THREAD

**Issue by echenley** [ianstormtaylor/slate#1187]
#### Do you want to request a *feature* or report a *bug*?

Bug 

#### What's the current behavior?

Editor breaks onBlur in IE 11.

#### Replication Steps

1. Type into the editor
2. Click outside of the editor
3. Editor blows up

Example of blurring the editor in IE via browserstack:

![4989bbc29a68c0f7a0060db13a76b70f](https://user-images.githubusercontent.com/6344219/30926731-be397ce2-a37b-11e7-82cd-b9aad1becaa5.gif)

#### Stacktrace

![screen shot 2017-09-27 at 11 24 30 am](https://user-images.githubusercontent.com/6344219/30926927-5ca99af6-a37c-11e7-9add-36201154b2c8.png)

Relevant line https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L207

#### Versions
OS: Windows 7
Browser: IE 11
React: 15.3.0
Slate: 0.21.2

**Comment by brendancarney** [comment]
Can't reproduce in latest SlateJS
