### ISSUE TITLE
Error inserting text with hanging selection (slatejs.org)

### ISSUE THREAD

**Issue by echenley** [ianstormtaylor/slate#1189]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What's the current behavior?

![2513bc427fe3f3226b94fbffcd2bd27e](https://user-images.githubusercontent.com/6344219/30940285-2a591b24-a3a6-11e7-97fa-8a7832d6e810.gif)

1. Triple click to select entire block
3. Type or paste some text.

It seems to have something to do with the selection wrapping to the beginning of the next block.

**Comment by echenley** [comment]
Did a little bit of digging today. It seems to have to do with the isHanging special case in deleteAtRange. The target block for the paste is being deleted because of this.

I can think of two non-ideal options to fix it:

1. Use the same behavior regardless of isHanging, i.e. merging the next block into the first. This is not ideal because if the second block has a different type, it will be converted to the first type, even though the selection doesn't *appear* to cover the second block. However, this may be technically "correct".

2. Pretend that the selection is not hanging during a paste, i.e. change endKey and endOffset to cover the previous block so it is replaced instead of deleted.

I have a feeling this is problematic for all rich text editors (not just Slate). Here is similar buggy behavior in Apple Mail:

![41a250fa6a9b2933c966b49fac2f7343](https://user-images.githubusercontent.com/6344219/31256226-c8e7a142-a9f6-11e7-8d0c-8d54a4cdcc63.gif)

**Comment by echenley** [comment]
A hacky but effective fix:

```js
function handleKeyDown(e, data, change) {
  // ...
  if (state.startKey !== state.endKey && state.endOffset === 0) {
    const endNode = state.document.getFurthestBlock(state.endKey)
    const prevNode = state.document.getPreviousSibling(endNode.key)
    change.extendToEndOf(prevNode)
  }
  // ...
}
```

**Comment by ianstormtaylor** [comment]
I think this is due to [these lines of code](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/changes/at-range.js#L228-L234) where the start block will actually be removed in the hanging case, so when it goes to insert text into it it's no longer there.

**Comment by czechdave** [comment]
Managed to figure out a possible fix to this issue. Let me know if it's a reasonable PR or if it needs any additional work or different approach @ianstormtaylor 

https://github.com/ianstormtaylor/slate/pull/1432

**Comment by rubyonrailsStar** [comment]
Hello @czechdave 

I have some questions.
Using SlateJS, if one character is deleted, can I delete all the character in the content ?

I don't know it is  possible.
