### ISSUE TITLE
Correctly show selection on custom marker (children not only plain text)

### ISSUE THREAD

**Issue by eromoe** [ianstormtaylor/slate#1191]
#### Do you want to request a *feature* or report a *bug*?

I think this can be classified as a bug , because it does affect using.

#### What's the current behavior?

```
    const renderMark = (mark, color='red') => (props) => (
      <mark onClick={this.onMarkClick} data-entity={mark}>
        {props.children}
        <span color={color}>{mark}</span>
      </mark>
    )
```

selection not show correctly (but actually work) on custom mark
![image](https://i.imgur.com/ZjQqJQ1.gif)

**Comment by ppvolto** [comment]
The Custom Element Example shows one difference from your code and thats the `props.attributes`
so the following can work..
```
const renderMark = (mark, color='red') => (props) => (
  <mark onClick={this.onMarkClick} data-entity={mark} {...props.attributes}>
    {props.children}
    <span color={color}>{mark}</span>
  </mark>
)
```

**Comment by eromoe** [comment]
I find the problem,  no matter with `props.attributes`

If I remove `span` inside `mark`, like
```
  <mark onClick={this.onMarkClick} data-entity={mark} {...props.attributes}>
    {props.children}
  </mark>
```
selection works.

**Comment by eromoe** [comment]
@ianstormtaylor  
Hi, but this not solved, because I don't want to remove the `span` inside `mark`, I only mean that affect selection showing.

If a user build a custom mark, they should take the responsibility to make selection works,  I think slate could provide some methods to help .

**Comment by ianstormtaylor** [comment]
Hey @eromoe, please check out "void" nodes from the docs. You cannot add custom child nodes to marks like you're doing, Slate doesn't support that. If you have questions, please ask them in the Slack channel, thanks!
