### ISSUE TITLE
Slate base64 serializer and SSR

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#1198]
Hey, 
I tried using the base64 serializer with my SSR enabled nodejs app and an error was thrown since `window` is used. Also, `atob` and `btoa` isn't available in node.

I could do a PR, but how would you like this solved? We could polyfill these two methods directly
```
function atob(str) {
  return new Buffer(str, 'base64').toString('binary');
}
function btoa(str) {
  let buffer;

  if (str instanceof Buffer) {
    buffer = str;
  } else {
    buffer = new Buffer(str.toString(), 'binary');
  }

  return buffer.toString('base64');
}
```
or make it a requirement that a global polyfill for these is available.  Either way, we should get rid of the window references.

**Comment by ianstormtaylor** [comment]
@bkniffler good call. I think we should just have a `if` statement that checks if the window methods are defined, and tries to use them, or falls back to `Buffer.from()`, or errors out if there is no implementation to use. I'd love a PR on this!

**Comment by isubastiCadmus** [comment]
@ianstormtaylor atob/btoa conversion doesn't really work out of the box for non ASCII character such as emoticons.

**Comment by ianstormtaylor** [comment]
@isubastiCadmus what happens with it? what bug does it create?

**Comment by isubastiCadmus** [comment]
@ianstormtaylor if the unicode is bigger than U+00FF, it will errors out see [btoa](https://html.spec.whatwg.org/multipage/webappapis.html#dom-windowbase64-btoa)

**Comment by ianstormtaylor** [comment]
@isubastiCadmus do you have a situation that causes that error?

**Comment by isubastiCadmus** [comment]
@ianstormtaylor looking at the code for base-64-serializer, you're already doing window.encodeURIComponent and window.decodeURIComponent which solves the atob/btoa error on emoji so all good. should have checked the source code before making comments, my bad. I can make a PR on this.
