### ISSUE TITLE
Is something wrong with the docs?

### ISSUE THREAD

**Issue by emilbruckner** [ianstormtaylor/slate#1201]
Seems to me like [https://docs.slatejs.org/reference/](https://docs.slatejs.org/reference/) should be there …

**Comment by SamyPesse** [comment]
@emilbruckner Slate switched to the new beta version of GitBook last week, you can access the documentation at https://docs.slatejs.org/

The new version of the documentation should handle redirections for URLs of the previous GitBook, 
 but the url `https://docs.slatejs.org/reference/` was broken when Slate switched to mono-repository architecture.

I think what you are looking for is now located at https://docs.slatejs.org/slate-core
