### ISSUE TITLE
Weird behaviour when inserting links

### ISSUE THREAD

**Issue by rovansteen** [ianstormtaylor/slate#1217]
At the [link example](http://slatejs.org/#/links) I'm having some weird behaviour in Safari and Chrome. If you clear out the example, and add a link with the text the cursor is inserted before the word on Safari, but after the word on Chrome. 

Now if I hit enter after a link, type a word and select that word and hit backspace it only deletes the last letter and not the entire (selected) word. Even after clearing everything this behaviour continues where it only deletes the last character of a selection.

Another weird thing I noticed is that if you empty the example, type a word, select it, add a link and then hit enter again. After that type another word, select that and add a link to it, it does not notice the selection and asks for text in addition to a URL.

**Comment by AlexeiAndreev** [comment]
Another bug with link example page, probably related.

* Position cursor at the very end of the last paragraph.
* Insert a link with some text.
* If you move the text cursor left and then right (with keys!) you'll notice that there is an extra (zero width?) character that was inserted at the end. If you try typing inside the link, the characters will be inserted in incorrect place.
* Mouse clicking on text fixes this issue.

**Comment by ashutoshrishi** [comment]
I got the same issue while trying to insert a custom inline node using `change.insertInline`. A Zero-Width-Joiner is inserted alongside an inline node. When you move your cursor over that Zero-Width-Joiner character and get `state.marks`, an exception is thrown: 

```
Uncaught TypeError: Cannot read property 'marks' of undefined
    at Document.getMarksAtRangeAsArray
```

Gif showing the Zero-Width-Joiner character appearing in the Links example:

![slate-inline-zwj](https://user-images.githubusercontent.com/176255/31751969-362f7a08-b4d4-11e7-9f5a-7f10707177f1.gif)

**Comment by AlexeiAndreev** [comment]
As far as I can tell, the Zero-Width-Joiner is inserted correctly, but what's broken is the cursor position. Right after inserting the link there are two possible positions for the cursor right after the link: 1) inside the link inline node, and 2) outside of the link inline node (inside the zero-width-joiner). (There is an identical problem at the beginning of the link too.)
