### ISSUE TITLE
Use MobX

### ISSUE THREAD

**Issue by nego25** [ianstormtaylor/slate#1220]
Hi!
In our project we use MobX to display on the screen in several places one change in the object 
There is one subtask - if two editors are simultaneously opened with the same document, it is necessary that the changes in one editor are immediately displayed in the second editor. Is it possible? 
In both editors I pass the same Document object. But the changes are not translated from first editor into the second editor. 
How can this be done on immutable objects? 
Thanks.

**Comment by tobiasandersen** [comment]
If you only care about displaying the changes from **one** of the editors into the other, there's nothing stopping you. But if you're looking to edit in **both** documents at the same time, i.e. collaborative editing, you'd need to implement some variation of OT (see https://github.com/ianstormtaylor/slate/issues/624 for more info).

**Comment by ianstormtaylor** [comment]
Like @tobiasandersen mentioned, there's nothing stopping this right now for local-only cases. You can either pass the same `state` object into both of the editors, if they share a common parent component. Or you can use event emitters or something else to transmit the `change.operations` between them and apply them if they don't. Check out the `syncing-operations` example for how this might work.
