### ISSUE TITLE
activeMarks throws error when no text is selected

### ISSUE THREAD

**Issue by cberkom** [ianstormtaylor/slate#1227]
On the latest slate release (0.26.1), an error is thrown when checking `state.activeMarks` if no text is selected.

**[JSFiddle demonstration](https://jsfiddle.net/2zokvrvt/194/)**

Also, the [official slate examples](http://slatejs.org/#/rich-text) seem to have the same problem.

**Comment by ianstormtaylor** [comment]
Hey @cberkom thanks for reporting this. I was seeing a slightly different error, but via your reproduction steps. I've just published `slate-react@0.3.3` which fixes this. Thank you!

**Comment by cberkom** [comment]
Seems to work, thanks!
