### ISSUE TITLE
[Doc] Link to Chinese Translation

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/slate#1228]
#### Do you want to request a *feature* or report a *bug*?
Feature

Slate is awesome and very well documented. For a more prosperous community, multi language documentation support seems to be a good plus. As a Chinese developer, I'm maintaining a [Chinese doc translation](https://doodlewind.github.io/slate-doc-cn/) for Slate. It's based on Slate `v0.24.1` and still in progress. Currently translations for `slate` and `slate-react` are mostly done. After all docs in `v0.24.1` are translated, I'll sync changes from upstream, like introducing the new fancy Gitbook theme and more. Here is the [repo](https://github.com/doodlewind/slate-doc-cn).

Is it possible to add a translation part with a link to Chinese doc in Slate's [Introduction page](https://docs.slatejs.org/), just like what [MobX](https://mobx.js.org/) did?

By the way, several typos are found and corrected during translation, I may submit a PR after proofread. 🤓

**Comment by ianstormtaylor** [comment]
Hey @doodlewind, absolutely! That's awesome 😄 

I've just added a **Translations** section to the docs and readme, right after the **Documentation** section, with your translation in it. If you find any typos, I'd love PRs!
