### ISSUE TITLE
add modifyNode Transform

### ISSUE THREAD

**Issue by mathieudutour** [ianstormtaylor/slate#123]

**Comment by mathieudutour** [comment]
Actually I realise that `updateDescendant` already exists and is exactly the same as `modifyNode`. 
```
const newState = state.merge({
          document: state.document.updateDescendant(node.merge({
                data: node.data.set('href', e.target.value)
          }))
})
```
Any reason why it's not expose under Transform?

**Comment by ianstormtaylor** [comment]
No good reason, just hadn't thought about how to structure "node" transforms yet (everything's range-based so far), but down to have it added and work from there!
