### ISSUE TITLE
[Doc] Missing new GitBook theme config

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/slate#1234]
#### Do you want to request a *feature* or report a *bug*?
Bug.

I'm trying to sync new doc theme to its [Chinese version](https://doodlewind.github.io/slate-doc-cn/), but the `book.json` config in this repo is just the same as before, neither can I find any doc-related build config in `package.json`. Noticed that the [doc hosted on GitBook](https://ianstormtaylor.gitbooks.io/slate/content/) also uses old theme with new content. This is a bit confusing. How is slate's official doc site built from?

**Comment by ianstormtaylor** [comment]
Good question! I think this is because we're in the beta of the new GitBook. Cc @SamyPesse
