### ISSUE TITLE
Changing the type of a selected block also applies the type to the subsequent block

### ISSUE THREAD

**Issue by hubgit** [ianstormtaylor/slate#1247]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

http://slatejs.org/#/rich-text

1. Triple-click to select the first paragraph.
1. Apply the "blockquote" style.

Both the first and second paragraphs will be converted to blockquotes.

![slate-select](https://user-images.githubusercontent.com/14294/31675657-35b1383c-b35d-11e7-97c2-87ad467ebf72.gif)

Environment: macOS, Chrome 61.

#### What's the expected behavior?

Only the type of the selected paragraph should change.

---

This is probably related to #1189 and #1021

**Comment by qgerome** [comment]
Hello ! We have the same problem :( On triple-click, Chrome starts the selection with the current nodeElement and ends it with the next node at offset 0. We are looking into it right now but we don't have a clue on how to handle this...

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
