### ISSUE TITLE
Bug: Selecting newly typed text, then bolding, gets into bad state

### ISSUE THREAD

**Issue by jessep** [ianstormtaylor/slate#125]
Steps to reproduce:

1) Type 'asdf'
2) Shift + backarrow to select it
3) bold it with button or keyboard shortcut
4) Notice you lose the selection
5) click somewhere else, start typing
6) See the thing you bolded, far from the cursor, get replaced with your newly typed text.

It also happens sometimes if you select the text with mouse instead of keyboard, but I haven't nailed that one down 100% consistently. Also happens with italics, etc.

**Comment by ianstormtaylor** [comment]
Hey @jessep thanks for reporting this! I've isolated it to: "make a backward selection and add a mark". And it looks like it's the backward-selection-handling logic that is incorrect. Looking into this!

**Comment by ianstormtaylor** [comment]
Fixed on `0.2.3`, thanks for reporting! Let me know if you run into anything else.
