### ISSUE TITLE
switch to BYO polyfills

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1252]
It seems unfortunate to have to bundle `es6-map`, `lodash/find`, etc. and to have to maintain utils like `find-closest-node` when the browser support for lots of the things we're polyfilling is good. It makes the bundle sizes needlessly bigger. 

So I think it makes sense to stop polyfilling these things and to instead have people BYO polyfill to the environment using something like [polyfill.io](https://polyfill.io/v2/docs/).

Would be good to know what other commonly used libraries are doing on this front.

**Comment by renchap** [comment]
It would be great to document which polyfills might be needed in the docs, so people can easily add them and not miss any, depending on what browsers they want to support.

**Comment by kvolkovich-sc** [comment]
Can you place information about browser support at README.md?
