### ISSUE TITLE
expressive schemas

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1258]
One of the trickiest parts about using Slate in more complex situations, especially once nested blocks are concerned, is ensuring that your document is in a "normalized" state with respect to your schema.

Since the schema is completely customizable, Slate doesn't help you by default. You have to add logic to ensure that states you don't want are normalized away.

A few examples of the kind of things you might want to enforce...

#### Quotes
- `quote` blocks always contain block nodes.
- `quote` blocks always contain at least on `paragraph`.

#### Lists
- `list` blocks contain only `list_item` blocks.
- `list_item` blocks contain only `paragraph` blocks.

#### Images
- `image` blocks are always wrapped in a `figure` block.
- `image` blocks always have a `data.src` attribute.
- `figure` blocks contain one `image` and an optional `figure_caption` block.
- `figure_caption` blocks only ever appear inside `figure` blocks.

#### Code
- `code` blocks contain only `code_line` blocks.
- `code` blocks always have a `data.language` attribute.
- `code_line` blocks contain only text nodes.
- Text nodes in `code_line` blocks have no marks.

#### Links
- `link` inlines always have a `data.href` attribute.

#### Comments
- `comment` marks always have a `data.author` attribute.

---

Right now you can do this via schema rules, by defining a set of `match, validate, normalize` functions that will correct any invalid states, like so:

```js
{
  match(obj) {
    return obj.kind == 'block' && obj.type == 'quote',
  },
  validate(quote) {
    const invalidChildren = quote.nodes.filter(n => n.kind != 'block')
    if (!invalidChildren.size) return
    return invalidChildren
  },
  normalize(change, quote, invalidChildren) {
    invalidChildren.forEach((node) => {
      change.removeNodeByKey(node.key)
    })
  },
}
```

But while this gives you the maximum flexibility, it's hard to read and write. It's hard to tell if you're leaving certain cases unhandled.

There's [prior art from Prosemirror](https://prosemirror.net/docs/guide/#schema) of having schemas that are more expressive.

I'd like to see if we can find something that Slate core could provide that could make managing schemas easier for people. Ideally it would solve the 90% cases well, and leave the underlying function-based approach for the other 10%.

---

There are a few hard challenges...

One issue is just of the complexity in allowing for all of the "common" schema-based restrictions. You should be able to... restrict the `kind` of child nodes, restrict the number and types of child nodes, restrict marks, restrict data properties, etc.

That said, although it will be more to learn, I do think that 90% of cases can be handled by _not too many_ keywords/syntaxes. So although it'll take research to figure them out, this should be solveable.

Another problem is that the `normalize` function of schema validations can often be context-specific, to be the least destructive possible. For example, in the case of...

> `figure_caption` blocks only ever appear inside `figure` blocks.

...if you see a rogue `figure_caption` at the top-level of the document, you could remove it. But instead, it you converted it to a `paragraph`, you'd avoid accidentally deleting content. Like so:

```js
{
  match: (object) => {
    return object.kind == 'block' && object.type != 'figure'
  },
  validate: (block) => {
    const invalids = block.nodes.filter(n => n.type == 'figure_caption')
      return invalids.size ? invalids : null
    },
  normalize: (change, block, invalids) => {
    invalids.forEach(n => change.setNodeByKey(n.key, 'paragraph'))
  }
},
```

But how do you get the expressive schema definitions to understand these kinds of complexities and perform the least destructive normalizations? I'm not exactly sure here. One idea could be exposing the `reason` that a schema rule failed, and maybe the normalizations are always left up the user. Or maybe the user can choose to opt-in to more fine-grained normalizing logic if the default doesn't suit them.

---

I'd love to hear people's ideas about what a nice, expressive schema API might look like!

**Comment by oyeanuj** [comment]
@ianstormtaylor +1 to more expressive schemas. To bring back an old open issue (#735), I found myself wanting the schema to be able to handle the following two issues:

1. Hierarchies/nesting of nodes. It seems that ProseMirror with its `groupSchema` supports that by listing the nodes within that group. It provides for a shorthand, and a quick readable way of knowing of how that `node`/`nodeGroup` behaves. Generalizing the ask, should we have the concept of `group` of nodes in Slate, like ProseMirror does?

2. Moving `isVoid` to the schema level. This would lead to less issues where if you are inserting a block, you don't need to always mention it, provide clarity when reading through a schema, and eliminate a few rules.

Abstracting out the two asks above, do we think that descriptive properties of a node type which are not likely to change for the node should probably be in the `schema`? If you look at it that way, then `placeholder`, `isVoid`, `nesting` could be argued to be present in the `schema`.

---

+1 to adding reasons why schema rules failed!

---

> .. is ensuring that your document is in a "normalized" state with respect to your schema.

It would be super cool if Slate at some point in the future (atleast in development mode) can warn if this is not the case, for any method of change.

**Comment by SamyPesse** [comment]
I think we can keep the current schema syntax that gives us the maximum flexibility, but create some tooling around it to build powerful schemas easily (schemas that scale with the application).

This is something that I've started implementing for GitBook.

The main issue we have with the current solution is the size of our schema with rules coming from multiple plugins.
Some rules are quite expensive, for example validate that a node of type `A` only has a parent of type `B`, it requires validating all nodes, and so it computes a lot of validations when typing a single char.

The idea I've discussed internally with @Soreine and @Zhouzi was to create a tool `slate-schema` that compile an expressive schemas into a reduced list of "normal" slate rules.
Then to have all of our plugins (`slate-edit-list`, `slate-edit-code`, etc) export both the compiled schema and the expressive one:

```js
import compileSchema from 'slate-schema';

function EditCode(options) {
    const CODE_SCHEMA = {
        [options.type]: {
            data: {},
            nodes: [
                ['text']
            ],
            // No marks allowed in code lines
            marks: []
        }
    };
    

    return {
        SCHEMA: CODE_SCHEMA,
        schema: compileSchema(CODE_SCHEMA),
        ...
    };
}

export default EditList;
```

Then using a method `merge` from `slate-schema`, we'll be able to merge the `SCHEMA`

**Comment by Soreine** [comment]
> Then to have all of our plugins export both the compiled schema and the expressive one

Plugins could actually not expose the already compiled schema, since we want to encourage using the expressive form that can be optimized.

> One idea could be exposing the reason that a schema rule failed, and maybe the normalizations are always left up the user.

I agree. Having control over the normalization is key. We want the user to be able to do the right normalization, because it's a pain to lose content while editing. And contrary to validations, normalization are rarely called and don't need to be optimized.

To make Slate easy to use, maybe we can provide a default normalization that make sense depending on the `reason`, or provide common normalization functions. But that's an extra.


### What do we need to express ?

Having a list of features for the expressive format will help us design it. Am I missing something?

1. What children a node is allowed to have
  - What kind of children is allowed (`block`, `inline+text`, `text`)
  - What types are allowed (`paragraph`, `list-item`).
  - How many of these are allowed (at least N, exactly N).
  - (extra) What should be the order of these children (`heading` first, then any number of `paragraph`)
  - (extra) For normalization, what is the default child (default to containing a `paragraph`)
1. What parent a node is allowed to have
  - Direct parent check (a `list-item` can only live inside a `list-container`)
  - (extra) Any ancestor check
1. What data a node is allowed to have (`comment` mark must have `data.author`, `image` should be `void`)

**Comment by ianstormtaylor** [comment]
@SamyPesse @Soreine thank you!

For the case of "what a parent node is allowed to have", it seems like we should always be able to express it as "`x` should not contain `y`", instead of "`y` can only be in `x`"? So wouldn't that be the same as limiting what kinds of children are allowed?

What are the optimizations you are thinking of with the expressive schema?

**Comment by ianstormtaylor** [comment]
Thinking this through a bit... I can see at least three different approaches to how to define the actual schema rules: (Open to more if you think of some!)

### 1. Using a Regex-like Syntax

This is the approach Prosemirror takes, which ends up looking something like:

```js
{
  paragraph: {},
  figure_caption: {},
  quote: {
    kinds: 'block+',
  },
  figure: {
    nodes: '(image|video),figure_caption?',
  },
  heading: {
    data: {
      level: isHeadingLevel,
    },
  },
  image: {
    isVoid: true,
    data: {
      src: isUrl,
    },
  },
  video: {
    isVoid: true,
    data: {
      src: isUrl,
    },
  },
  code: {
    nodes: 'code_line+',
    data: {
      language: isCodeLanguage,
    },
  },
  code_line: {
    kinds: 'text',
    marks: '',
  },
}
```

This has the benefit of things being super terse. But there are a few downsides. One, we have to end up parsing this new, potentially-complex syntax, which seems annoying. Two, in the case of having type names defined as constants, you'd end up having to do lots of string interpolation to insert them into these regex-like strings.

### 2. Using a Proptypes-like Syntax

This approach would be something more like `prop-types` in React:

```js
{
  paragraph: {},
  figure_caption: {},
  quote: {
    nodes: Schema.kindsOf(['block']),
  },
  figure: {
    nodes: Schema.exactly([
      Schema.typesOf(['image', 'embed']), 
      Schema.oneOrNoneOf({ type: 'figure_caption' }, 1),
    ])
  },
  heading: {
    data: {
      level: isHeadingLevel,
    },
  },
  image: {
    isVoid: true,
    data: {
      src: isUrl,
    },
  },
  code: {
    nodes: Schema.typesOf(['code_line']),
    data: {
      language: isCodeLanguage,
    },
  },
  code_line: {
    marks: [],
    nodes: Schema.kindsOf(['text']),
  },
}
```

This has the benefit of the edge cases like "defining exact children order" being a bit more understandable, since you can easily read `exactlyOf`, `anyOf`, etc. 

But this is kind of not nice in that it's optimizing for these edge cases at the expense of having to add these functions for even the 90% cases that are almost always just restricting child types, kinds and node data. And plugins would then have to import this collection of schema functions to be able to define things, which is more of a pain.

### 3. Using A Plain Object Syntax

Something that's more plain and simple maybe:

```js
{
  paragraph: {},
  figure_caption: {},
  quote: {
    nodes: [
      { kind: 'block' },
    ]
  },
  figure: {
    nodes: [
      { type: ['image', 'embed'], min: 1, max: 1 }, 
      { type: 'figure_caption', min: 0 },
    ]
  },
  heading: {
    data: {
      level: isHeadingLevel,
    },
  },
  image: {
    isVoid: true,
    data: {
      src: isUrl,
    },
  },
  code: {
    nodes: [
      'code_line'
    ],
    data: {
      language: isCodeLanguage,
    },
  },
  code_line: {
    marks: [],
    nodes: [
      { kind: 'text' }
    ]
  },
}
```

This has the benefit of being able to even be pure JSON in non-complex cases. (See `normalize` property coming up soon...) And if we do end up making this consumable, editable, etc. then having it in pure JS objects is going to be simplest for consumers.

This seems like it might be the best, and maybe is what you all came up with in your discussions too since it seems similar to that snippet above. 

---

I think we could assume some defaults for blocks that would make it easier:

```js
{
  marks: undefined,
  data: undefined,
  isVoid: false,
  nodes: [
    { kind: ['text', 'inline'], min: 1, max: Infinity }
  ]
}
```

And for inlines:

```js
{
  marks: undefined,
  data: undefined,
  isVoid: false,
  nodes: [
    { kind: ['text'], min: 1, max: 1 }
  ]
}
```

And then the entire thing would go inside a nested object that splits up the different object kinds for simplicity and so you don't have to redefine that each time:

```js
{
  blocks: { ... },
  inlines: { ... },
  marks: { ... },
}
```

There could potentially even be a `document` top-level property since it's somewhat common to have blocks that shouldn't even be found at the top-level:

```js
{
  document: {
    nodes: [
      'paragraph',
      'quote',
      ... // but not 'figure_caption' or 'code_line'
    ]
  }
}
```

And we could later, somehow, maybe even allow marks to be validated and fixed too:

```js
{
  marks: {
    bold: {
      data: { ... },
      marks: [ ... ], // marks that it is allowed to coexist with
    }
  }
}
```

---

One unknown I have is how should the "merging" happen?

Can we get away with just merging inside `blocks/inlines/marks` and not having to merge individual node definitions? 

That won't really work for `document` though... so it seems like we'd need to special case that? Or just require that `document`-level schema be added by something that knows the "full picture" and not have it be added to by lower-level plugins. But that kind of defeats the purpose? Maybe not.

---

@SamyPesse @Zhouzi @Soreine what do you think? Have you already solved some of these things in your discussions or code?

Also, would you be open to this being called `slate-schema`, but being managed as part of the core monorepo? Just thinking that it would be nice to maintain closely alongside the other core pieces, would allow us to get it more engrained into examples, and would make adoption/standardization better I think.

**Comment by Soreine** [comment]
I am currently replying on your PR. I think we will need to deeply merge the rules.

> ```js
> quote: {
>   nodes: [
>     { kind: 'block' },
>   ],
>   normalize: (change, reason, node, child) => {
>     if (reason == 'child_kind_invalid') {
>       change.wrapBlockByKey(child.key, 'quote')
>     }
>   }
> }
> ```
> 

Is there an infinite loop in this normalization rule ?

**Comment by ianstormtaylor** [comment]
@Soreine If I'm reading it right then yes there is, but why would that be the normalization solution to that validation reason? If quotes can't contain non-blocks, how would wrapping in a quote help fix the issue?
