### ISSUE TITLE
cursor won't move up/down/right when using arrow keys in chrome, firefox

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#126]
On the [demo site](http://slatejs.org/#/rich-text?_k=msm0gm) I can only navigate with the left arrow key. When pressing up/down/right nothing happens. Chrome and FireFox on most recent versions.

**Comment by ianstormtaylor** [comment]
Sorry about that, I just introduced this bug while working on IME input for other languages. Fixed!
