### ISSUE TITLE
Inconsistencies in schema documentation

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#1261]
https://docs.slatejs.org/slate-core/schema

1. Under [rules](https://docs.slatejs.org/slate-core/schema#rules) example `match` is given as `match: { kind: 'block', type: 'code' }`, but right below under Rule Properties, it's `match: Function`

2. Under [match](https://docs.slatejs.org/slate-core/schema#match): `Function match(object: Node || Mark)`  
But I'm pretty sure match never gets passed a Mark.

**Comment by ianstormtaylor** [comment]
I believe this should be fixed now with the new Schema and docs.
