### ISSUE TITLE
Request: access to parent node or document in schema rules

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#1263]
Right now there is no way to get the parent of a node when specifying schema rules. (Unless I'm missing something.) This means there is no way to enforce a rule like: in any block, if an inline node of type X exists (with some custom data), another inline node of type X has to exist (with some other custom data). I guess for every block you could iterate through all the children, but it's definitely less efficient than just writing a rule for nodes of type X.

**Comment by ianstormtaylor** [comment]
Hey @AlexeiAndreev this is unfortunately how the schema works. The rules are memoized based on the nodes themselves, such that they can be cached when the node hasn't changed. But if you want to perform a normalization based on multiple nodes, you have to use their parent instead.

I'd be open to a `rule.next/previous` similar to `rule.parent` though, if someone wanted to add that functionality to the schema.
