### ISSUE TITLE
support carrying over marks between paragraphs

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1269]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What's the current behavior?

If you split a block, the "active" marks aren't carried over:

![](http://g.recordit.co/SvjgUx7E2K.gif)

#### What's the expected behavior?

When you press enter, any active marks should stay active.

**Comment by oyeanuj** [comment]
@ianstormtaylor @justinweiss Coming to this a little late, but pressing 'enter' would take you to a new block, conceptually often a new paragraph. So, it is a little odd for the marks to be continued to the new paragraph, to be the default behavior.

FWIW, Medium and Dropbox Paper don't seem to have this behavior.

**Comment by ianstormtaylor** [comment]
@oyeanuj damn, that is interesting. I only actually looked at Google Docs, and they did carry on the formatting, so I assumed it was good to do. It looks like these editors **do**:

- Google Docs
- Draft.js
- Quill.js
- Trix.js

And these ones **don't**:

- Medium
- Dropbox Paper
- Notion
- Quip
- WordPress
- Prosemirror.js

Given that it's split, and that more of the actual product editors don't do it, and that deciding not to do it is the least "invasive"... that does seem like a good argument to require this to be a user-land behavior instead of baked into core. 

For things like **bold** or _italic_ it makes sense to carry them on, but for more complex marks like `comment` or `highlight` it might be weird to do that.

@justinweiss I hope that makes sense.

Feel free to reply with counter arguments!

@oyeanuj @justinweiss would either of you be up to write a PR that reverts this?

**Comment by justinweiss** [comment]
Huh, that's interesting. I didn't expect that behavior to be different between editors -- I've been using Google Docs and Apple Notes as my test cases, and they both carry over formatting. Assuming we can do it in userland, I'm totally OK with that (I'm, like, 90% sure we can). If not, getting the ability to change it in userland is probably the bug 😄
