### ISSUE TITLE
active marks aren't working in safari?

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1270]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What's the current behavior?

Pressing <kbd>cmd-b</kbd> in the `rich-text` example doesn't set active marks on the next character in Safari:

![](http://g.recordit.co/kPPMcDU4kx.gif)

#### What's the expected behavior?

It should! Just like Chrome, etc.

**Comment by justinweiss** [comment]
It looks like the difference in behavior here might be Safari using onNativeBeforeInput, and Chrome using onBeforeInput.

**Comment by justinweiss** [comment]
Actually, to be consistent with Chrome, it looks like I also need to clear them after input. Same way we do in `insertText`.
