### ISSUE TITLE
Selection issue on insert inline

### ISSUE THREAD

**Issue by davidebianchi** [ianstormtaylor/slate#1276]
#### Do you want to request a *feature* or report a *bug*?
A bug

#### What's the current behavior?
When I insert an inline using `insertInline` function, the selection doesn't work as expected, but when you start writing the cursor position is not correct.

The bug is present in http://slatejs.org/#/emojis
http://g.recordit.co/7Z23jL3Mnq.gif
Is on chrome and firefox on osx, but not on safari

When we start to write, it appear in console:
Unable to find a native DOM range from the current selection.

#### What's the expected behavior?
The expected behavior is that writin after the insert of inline, the selection doesn't return behind the letter already written.

**Comment by iKorso** [comment]
Same question here, windows chrome.
It looks like something wrong with Range object params, when you inserting inline with `isVoid`, slate inserting void text node with empty text before and after inline node. And this last one void text node somehow has wrong selection params.
