### ISSUE TITLE
Drag events are swallowed by Slate

### ISSUE THREAD

**Issue by echenley** [ianstormtaylor/slate#1277]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What's the current behavior?

https://jsfiddle.net/6n439eh9/1/

Drag events do not propagate outside of Slate. This was introduced in https://github.com/ianstormtaylor/slate/pull/1193 (cc @AlbertHilb). While the onDragEnter/Leave/Over hooks work on the Editor component itself, any drag hooks outside of the editor will not be called. This makes using something like ReactDropzone alongside Slate difficult if not impossible.

@ianstormtaylor mentioned in slack that it should be possible to do this without using stopPropagation: https://slate-js.slack.com/archives/C1RH7AXSS/p1508433948000130

#### What's the expected behavior?

Drag events should propagate normally.

Tested using slate-react version 0.7.0 (introduced in 0.6.0).

**Comment by ianstormtaylor** [comment]
Fixed now!
