### ISSUE TITLE
DefaultPlaceholder does not apply placeholderClassName and placeholderStyle

### ISSUE THREAD

**Issue by renchap** [ianstormtaylor/slate#1279]
This is a bug. The doc states that `Editor` accepts `placeholderClassName` and `placeholderStyle` props but they are not applied since https://github.com/ianstormtaylor/slate/pull/1253

I think this is an easy fix, `DefaultComponent` just need to read them and set the class / merge the style.

I can create a PR for this, but I am unsure if the docs (and `editor.js`, as the props are still defined there) are a leftover from the above PR and should be removed in favor of custom placeholder, or if they need to be added back to `DefaultComponent`. I would prefer the latter as this seems a common usecase and the implementation is quite simple.

**Comment by renchap** [comment]
The latest version changed the placeholder management again, removing the default component in favor of `renderPlaceholder`. This does not change the issue and the possible fix (use `placeholderClassName` and `placeholderStyle` in `renderPlaceholder`).

**Comment by ianstormtaylor** [comment]
Hey @renchap what are you trying to accomplish with `placeholderClassName` and `placeholderStyle`? Just curious to see what the use case is. Thanks!

**Comment by renchap** [comment]
I need to be able to style the placeholders differently, specifically remove `whitespace: no-wrap; width: 0px;` from the style as my editors can be narrow and the placeholder text needs to wrap.

I can either use `placeholderClassName` or `placeholderStyle`, but as both are in the docs I put them both in this issue 🙂

**Comment by ianstormtaylor** [comment]
@renchap you'd also need to position them absolutely or something then right? To make them not take up the space? Or some sort of other tweaks?

I'm curious about the use case. I'd be open to tweaking the default placeholder rendering styles, similar to how we've tweaked the <Void> styles—as long as they still apply to the general case of mimicking the native `<input/textarea>`.

If it's not something that applies to the general case though, I think going forward I'm going to recommend using a custom `renderPlaceholder` function instead to keep core simpler.

**Comment by renchap** [comment]
See an example here: https://www.talegraph.com/tales/hX2bWZixOK?d

When editing the chapter's title, I want the placeholder to be rendered like the normal text, but in grey, like this:
![screen shot 2017-10-27 at 18 55 39](https://user-images.githubusercontent.com/42070/32115807-8541e926-bb48-11e7-9545-624ff1f8431f.png)

I can definitely use a custom `renderPlaceholder` function and I understand that you want to keep the core simple, but in this case you need to remove mention of `placeholderClassName` and `placeholderStyle` in code/docs, and probably add an example with a custom placeholder as it is currently quite hard to figure it out from the docs/examples.

**Comment by ianstormtaylor** [comment]
This should be solved these days by implementing your own `renderPlaceholder` prop to render the placeholder with whatever extra styles you'd like.
