### ISSUE TITLE
Discuss differences between slate and scribe

### ISSUE THREAD

**Issue by skeggse** [ianstormtaylor/slate#128]
How does slate compare to [scribe](https://github.com/guardian/scribe)? It seems to have many of the same features and goals, especially given that they both have first-class plugin support. It'd be nice if there were a section or addendum in the README about this.

**Comment by ianstormtaylor** [comment]
Good question, I'll investigate and add one, I hadn't seen it until now. Looks interesting!

**Comment by wearhere** [comment]
One difference I am particularly curious about, re:

> you can think of [this] like a pluggable implementation of `contenteditable`

is, does this project actually use `contenteditable`? Or does it just resemble `contenteditable`. Scribe actually uses `contenteditable`.

**Comment by arekkas** [comment]
@wearhere it's a controlled contenteditable environment. @skeggse scribes datastructure is not as clean as slates, it was hard to use it with server side node and it works only in a few browsers. I can't recommend it.

**Comment by oyeanuj** [comment]
While we're at it, I think having *Medium-Editor* be on there would be useful as well. It has an extension-first architecture as well and is probably the one of the most popular choice in the non-react world.

https://github.com/yabwe/medium-editor

**Comment by skeggse** [comment]
@arekkas can you expand on the datastructure not being as clean as slate's? the other two concerns aren't important to me

**Comment by ianstormtaylor** [comment]
Hey all, thanks for opening this. I've added Scribe and Medium Editor to the Readme's comparison. For a quick summary the main issues are:

> The issues I found with Scribe are: that it works direclty on the DOM and its goal is to simply "fix" contenteditable, such that all userland and plugin logic still has to account for x-browser differences, that its data model is tied to the DOM, so serialization to formats besides HTML is more complex, that without a backing data model collaborative editing is much more difficult to layer in, and that it lacks broader mobile and browser support.

> The issues I found with the Medium Editor are: that it doesn't actually pave over `contenteditable`, so you continue wrestling with the DOM, that the concept of a "toolbar" is tightly coupled with core in many respects making it harder to customize, that the extension system requires learning an entirely new view abstraction, and that the editor relying on the DOM's HTML as its data model makes collaborative editing much more difficult.

@skeggse as for data structure, since Scribe works directly on the DOM, that DOM structure is your data structure. Which can be good if you only care about HTML, or if you don't care about collaborative editing (and probably other things I'm not thinking about right now). But if you do want those things, you'd probably want a backing data model that isn't tied to the DOM.

**Comment by ianstormtaylor** [comment]
Ah, also @wearhere as far as `contenteditable` goes, there's a big difference between Slate and Scribe. Scribe basically works to make `contenteditable` less inconsistent, whereas Slate abstracts away `contenteditable` so that you can just treat it as a controlled React input component.

**Comment by wearhere** [comment]
Great analysis @ianstormtaylor et. al, thanks!

**Comment by bronson** [comment]
> [scribe] lacks broader mobile and browser support.

Just curious: is mobile a target for Slate?  I sure hope so, but the demo doesn't appear to work on my Android phone.

Either way, it would be nice to have a tiny paragraph in the docs describing what to expect from trying Slate on iOS and Android.

**Comment by arekkas** [comment]
Android Browser or Chrome browser? Also, how old is your Android.

**Comment by bronson** [comment]
Oop, good point: Firefox on latest Android.  Forgot I switched default browsers.

I'm actually happy that no one has spent dev time getting Slate to work on my oddball combination... Just hoping for a quick blurb about Slate's intentions on mobile devices.

**Comment by ianstormtaylor** [comment]
@bronson good call, added a note for myself here: https://github.com/ianstormtaylor/slate/issues/446
