### ISSUE TITLE
remove the need for `props.attributes`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1282]
This is one of the most awkward things when defining custom Node components. Right now you have to remember to mix in `<Component {...props.attributes} />` to your components, because some things depend on it...

- `findDOMNode` depends on an `attributes.data-key` property being set.
- Right-to-left text direction depends on an `attributes.dir` property being set.

But why not solve this with React's `refs` instead? In the core `<Node>` component, when the ref is established it could just use `ReactDOM.findDOMNode` itself and set those two properties on the node's element? 

This prevents the user from specifying exactly which element to mix the attributes in on, but I'm not sure that's even a thing we want to allow...

Feels like this would be a super simple, but nice API improvement. If anyone sees holes in the plan please point them out!

**Comment by twobit** [comment]
Downshift takes a similar approach to mixing in library controlled props with [prop getters](https://github.com/paypal/downshift#prop-getters). Also check out the [blog post](https://blog.kentcdodds.com/how-to-give-rendering-control-to-users-with-prop-getters-549eaef76acf) with more details.

**Comment by ianstormtaylor** [comment]
@twobit interesting, thanks for the links!

**Comment by AlbertHilb** [comment]
@ianstormtaylor 
It would be beautiful to remove `props.attributes`, but we should avoid overusing `ReactDOM.findDOMNode`.
`findDOMNode` is considered an anti-pattern and could be removed in a future React release.
See [this discussion][1] for example.

[1]: https://github.com/yannickcr/eslint-plugin-react/issues/678

**Comment by ianstormtaylor** [comment]
@AlbertHilb very good point!

**Comment by ianstormtaylor** [comment]
I think this isn't a great idea anymore.
