### ISSUE TITLE
can not support chinese

### ISSUE THREAD

**Issue by lengjing** [ianstormtaylor/slate#1284]
![untitled](https://user-images.githubusercontent.com/5450712/31984705-201cd9b0-b928-11e7-9491-7aa15c7676c6.gif)

**Comment by doodlewind** [comment]
Same as described in #1229

**Comment by ianstormtaylor** [comment]
Hey, thanks for reporting this. I think this is actually a duplicate of #1229, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!
