### ISSUE TITLE
Infinite `onChange` loop

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/slate#1294]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?

https://jsfiddle.net/doodlewind/6t8db72u/2/

1. Select some text.
2. Click on `delete`.

Then `onChange` is continuously called, page is stopped.

#### What's the expected behavior?

`onChange` should only be called once.

It seems that `flushChange` and `queueChange` in `<Editor />` are looping. Similar with #1293 

Edit: This only happens when passing `onFocus` handler to `<Editor />` .

**Comment by ianstormtaylor** [comment]
It seems like this also happens when passing only `onKeyDown`, instead of `onBlur` or `onFocus`. So potentially it's a bug from passing any of the "editor plugin" props.
