### ISSUE TITLE
Unable to perform delete when inline node is at the end of parent block.

### ISSUE THREAD

**Issue by chemzqm** [ianstormtaylor/slate#1295]
#### What's the current behavior?

https://jsfiddle.net/2zokvrvt/265/

Put cursor at the end of `sup` tag, and then press `delete`,  nothing would happen,  
the delete would works after type `<left>` to move the cursor a bit left.

* OS: MacOS
* browser: Chrome
* Slate:  0.28.0

#### What's the expected behavior?

The `sup` should be removed after type `delete`

**Comment by YurkaninRyan** [comment]
I believe I found the reason for this,  the range is returning a startOffset of 1 even though, there are no characters in the the text.  This is because in the span there is a zero-width space, but in the text model it's totally empty
