### ISSUE TITLE
Plugin `render()` methods are never called

### ISSUE THREAD

**Issue by rgrove** [ianstormtaylor/slate#1303]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

Plugin `render()` methods are never called.

JSFiddle: https://jsfiddle.net/rgrove/4xa6rrag/

This issue can also be seen in the [Plugins example](http://slatejs.org/#/plugins), which should render a word count but currently doesn't.

#### What's the expected behavior?

Plugin `render()` methods should be called when the editor is rendered.

**Comment by ianstormtaylor** [comment]
Shoot, I'm sorry about this @rgrove. It was actually a breaking change that I forgot to document in the Changelog for `slate-react`. It's been renamed from `render` to `renderEditor`. I've just updated the Changelog and `examples/plugins` to match. Thanks for catching this!

**Comment by rgrove** [comment]
Ah, no worries. Thanks!
