### ISSUE TITLE
Unaccessible history state

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/slate#1305]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?
https://jsfiddle.net/doodlewind/wo348Lc0/

1. Using the <kbd>delete</kbd> button to delete some selected text.
2. Focus on text, press `cmd-z`.

Previous state can't be replayed with `cmd-z` since the editor is again blurred.

Behavior with `cmd-z` that loses focus:

![bug-cmd-z](https://user-images.githubusercontent.com/7312949/32087213-031d3ba6-baa0-11e7-814d-0f35116ce82b.gif)

#### What's the expected behavior?

`cmd-z` shouldn't blur the editor. Expected Behavior with <kbd>undo</kbd> and <kbd>redo</kbd> button:

![normal-undo-redo](https://user-images.githubusercontent.com/7312949/32087215-06051d66-baa0-11e7-801d-fb03d12bfe4b.gif)

#### Some investigations
This behaviour is regularly encountered in my editor project and it's frustrating, since user will think their changes are 'lost'. But in fact the history stack is preserved.

In Slate's default examples, toolbar buttons doesn't trigger this issue since changes are fired from `onMouseDown` and prevented default, editor is still focused afterwards. But when building advanced toolbar with color pickers or table pickers, mouse events can still blur the editor. In this case `cmd-z` is not usable.

IMHO it makes sense to **always** focus after redo or undo, the question is the place for the logic. Calling `redo().focus()` and `undo().focus()` as a workaround will break history stack and throw errors. Another workaround that calls `delete().focus()` is also awkward.

**Comment by ianstormtaylor** [comment]
Hey @doodlewind I can repeat what you're saying in the JSFiddle, but I'm not sure how to solve it. Since clicking the button is inherently blurring the editor, I'm not sure there's much we can do?

I'm open to ideas, but I'd need to have solutions proposed because I'm not sure I fully understand.

**Comment by doodlewind** [comment]
@ianstormtaylor can we ensure editor is always focused after calling `undo()`?

Several approaches I can think of:

1. Add logic in `Changes.undo` and `Changes.redo` that always focus editor after applying history state, just like replacing `change().undo()` with `change().undo().focus()`.
2. When pushing into history stack, discard all `blur` operations. So when calling `undo()` editor would never blurred.
3. Customize `onKeyDown` logic as plugin, overriding default `cmd-z` behaviour.

The second one is the most attracting to me, but I'm not sure if it'll be breaking. 😅

**Comment by ianstormtaylor** [comment]
But why should we ensure that it's always focused? It seems like a leaky abstraction, and it would prevent cases where you don't want to override the focus state?

What's the issue with requiring `onMouseDown` or similar, to ensure that the editor isn't blurred in the first place?

**Comment by doodlewind** [comment]
@ianstormtaylor I've met a few use cases:

1. Color/table picker **popup** in toolbar that requires user's second click to choose color.
2. **Modal** to edit embed attrs with `<input />` inside, focus is changed to input then.
3. With some custom blocks that support **resizing**, it's easy to lose mouse event.

Also we can restrict the range: this issue only happens when:

1. Previous stack state is **merely blur**
2. User triggers undo from **keyboard shortcuts**.

Does a specific workaround make sense?

**Comment by doodlewind** [comment]
Worth noticing that chaining changes after `undo` breaks history stack for now, when history stack size equals to 1, calling `undo().focus()` raises following error:

```
history.js:134 Uncaught TypeError: Cannot read property 'slice' of undefined
    at History.save (http://localhost:8080/build.dev.js?1509124818089:111651:31)
    at Change.applyOperation (http://localhost:8080/build.dev.js?1509124818089:110803:27)
    at Changes.select (http://localhost:8080/build.dev.js?1509124818089:109269:10)
    at Change.call (http://localhost:8080/build.dev.js?1509124818089:110847:10)
    at Change.(anonymous function) [as select] (http://localhost:8080/build.dev.js?1509124818089:110921:15)
    at Changes.(anonymous function) (http://localhost:8080/build.dev.js?1509124818089:109521:12)
    at Change.call (http://localhost:8080/build.dev.js?1509124818089:110847:10)
    at Change.(anonymous function) [as focus] (http://localhost:8080/build.dev.js?1509124818089:110921:15)
    at Object.onKeyDown (http://localhost:8080/build.dev.js?1509124818089:104194:28)
    at Stack.run (http://localhost:8080/build.dev.js?1509124818089:117181:38)
```

@ianstormtaylor is it an anti-pattern chaining changes after `undo`? Or do we have some other workarounds?

**Comment by ianstormtaylor** [comment]
Hmm that's bad, nope it shouldn't break. Can you open another issue for that?

I see what you mean. What if instead of discarding only blurs, we actually change `undo/redo` to ignore all changes to `isFocused`, so that the focused state will never change when undoing, it will remain whatever it currently is?

**Comment by doodlewind** [comment]
That's cool! I'm yet not confident enough modifying Change's internal behaviour, while I indeed found an upper-level workaround as alternative. Feel free to use it or not 😅

**Comment by ianstormtaylor** [comment]
Okay cool. I think that change isn't quite what we want, but I'm down to accept the more correct version from you or anyone who can put together a PR in the future. Thanks!

**Comment by isubastiCadmus** [comment]
@ianstormtaylor it seems that with the newest version of slate, the first operation is set_value which cause the error on undoing when history stack size is equal to 1. 
I got around this with ```hasUndo```/```hasRedo``` helpers that filters out stack that only have set_selection(focus/blur) or set_value(initialization) operation and handleRedo and handleUndo change function that check if it has undo/redo and run ```change.redo()```/```change.undo()``` till the change is not a set_selection operation.

**Comment by chemzqm** [comment]
For user experience, I would expect the operation which not change document like selection change to be merged into next operation before saving into history, so that every history undo & redo operation have document change.

**Comment by doodlewind** [comment]
@chemzqm That's exactly what #1330 implements.
