### ISSUE TITLE
State sometimes change twice after one change

### ISSUE THREAD

**Issue by chemzqm** [ianstormtaylor/slate#1308]
#### Do you want to request a *feature* or report a *bug*?

**BUG**

#### What's the current behavior?

https://jsfiddle.net/31tb8gyx/30/

Select some text and click bold button, and you will see the `onChange` event fired twice, and as a result, the history state of editor is undesierable.

This issue happens only when call `e.preventDefault` in `onMouseDown` handler,  but without `e.preventDefault`, the editor would blur and user could not continue editing, which is also too bad.

* OS: MacOS
* Browser: Chrome
* Slate: 0.28.2

#### What's the expected behavior?

No twice state change, no unnecessary rerender, the history state should be clean.

**Comment by doodlewind** [comment]
IMHO this is the same issue with #1069 since slate's history stack records selection change.

**Comment by ianstormtaylor** [comment]
When I click <kbd>bold</kbd> in that JSFiddle I only see a single change firing. If I click <kbd>undo</kbd> I see two changes firing though, because it's using `onClick` instead of `onMouseDown`.

Can you clarify what you mean here?

**Comment by chemzqm** [comment]
@ianstormtaylor one change without text selection, but two changes with text selection.
Same issue exists on Safari and Firefox.

**Comment by isubastiCadmus** [comment]
I can confirm this. but it only happens on drag selection, not double click/triple click selection. What's the difference in drag/double click/triple click that can possibly cause a set_selection operation needed after toggling mark @ianstormtaylor ?

**Comment by isubastiCadmus** [comment]
@ianstormtaylor actually there is a more specific case when this occurs, @chemzqm can you clarify this as well. So with the drag selection, if the selection is forward selection it seems to be running onChange only once. It doesn't seem to be the case on backward selection, on backward selection it triggers onChange twice.

**Comment by chemzqm** [comment]
@isubastiCadmus yes, the problems exists for backward selectin only, not forward selection.

**Comment by isubastiCadmus** [comment]
@chemzqm yeah, for some reason it run's a selection change that flips the selection from backward to forward if the selection is backward. still trying to chase the problem down.

**Comment by ianstormtaylor** [comment]
@chemzqm I'm still not clear on what you are talking about. If you change the `undo` handler to be `onMouseDown`, then there's no issue with undoing.

**Comment by isubastiCadmus** [comment]
@ianstormtaylor the problem seems to be on backward selection, when we click on a button such as bold (with ```onMouseDown``` and ```event.preventDefault()```), it will trigger ```onSelect``` after the ```toggleMark``` change which changing the selection from backward selection to forward selection. I'm guessing this is because editor loose focus and native Selection on ```onSelect``` can't differentiate between forward/backward selection and decided to update the selection because it looks different from the current selection?

**Comment by ianstormtaylor** [comment]
@isubastiCadmus sounds like it's definitely possible, I'd accept a PR that fixes that checking logic.
