### ISSUE TITLE
State considering schema in equality checks, increasing the number of onChange generated

### ISSUE THREAD

**Issue by lxcid** [ianstormtaylor/slate#1318]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

Since `0.28.0`, `State` model stores `schema` as a property in its immutable `Record`. As far as I know, `schema` is a computed value. (They are not serialised too) This increase the cases where onChange get invoked. I'm still in the midst of investigating, but I'm realising that in my implementation, where I treat `<Editor />` as a controlled component, `schema` kept computing different values, generating 12 changes (without any input) by the following code:

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/before.js#L106

In my use case, I create more than one editor components, thus, this issue is a lot more severe for me. So if I have 20 editors, I end up with 240 changes at one of my debug session.

I'm still investigating and if I have more findings, I'll drop more information.

#### What's the expected behavior?

I'm hoping State generates less unnecessary changes. Hopefully only when (serialised) states are different or selection related.

**Comment by ianstormtaylor** [comment]
@lxcid can you give a code sample of how you render your editor? That might help figure out what's going on here. Thanks!

**Comment by lxcid** [comment]
Thanks @ianstormtaylor for the fast response!

I crafted up a jsfiddle that mimic my issue.

https://jsfiddle.net/lxcid/4s83hg8q/

If you open the console, you will see that onChange got invoked 210 times when I only render 20 `<Editor />` and without any interaction yet.

**Comment by lxcid** [comment]
Hey @ianstormtaylor, thanks so much for the fix! The built up of `onChange()` event is definitely gone.

I'm facing a new issue though, as we are using `setTimeout()` for the new behaviour, on browser like Safari that does not aggressively process those timeout in a timely manner, you can see that timeout build up as well. So if I duplicate the number of editors by 10x in the jsfiddle running inside Safari, the console will slowly print out the debug statement one after another.

I understand I am using Slate very differently from the normal path, but this is a regression for me, before the change, older version was very capable on rendering hundreds of `<Editor />` components.

Analysing the situation, I identify the following issues:

- flushing of changes only happen in `componentDidMount()` and `componentDidUpdate()`, although you have specifically documented the rationale for having change queue, it doesn't seems like a bad idea to trigger the `onChange()` event immediately during these component life cycle.
- `setTimeout()` might not be immediate.
- Value's schema must be exact reference to Editor's schema (identity), even if their value is the same, if not, `onChange()` event is fired.
- There's no way we can pass in a schema from the outside (update Value's schema) so as to suppress the `onChange()` situation.

I'm still digging the code to see if I can workaround the issue. I haven't gotten up to speed with the latest changes, will keep you updated!

### References

- [setTimeout() - Reasons for delays longer than specified](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified)
