### ISSUE TITLE
Value.toJSON() is not compatible with JSON.stringify()

### ISSUE THREAD

**Issue by lxcid** [ianstormtaylor/slate#1321]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

In the `Value` model, toJSON accepts an argument called `options`.

https://github.com/ianstormtaylor/slate/blob/c9f1168cd7cd46ef6ceea265de52a1bbed64418f/packages/slate/src/models/value.js#L629

In [JSON.stringify()'s `toJSON()` behavior section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior), it is specified that `toJSON()` receives a string argument describing the key it is to stringify to.

This breaks tools like Redux DevTools which attempt to serialise action with `JSON.stringify()` and throws the following error:

```
Cannot use 'in' operator to search for 'preserveStateData' in key
```

#### What's the expected behavior?

I think for it to be compatible with `JSON.strinigfy()`, we have to check the argument type beforehand?

**Comment by ianstormtaylor** [comment]
Hey @lxcid, good call. I think we should solve this with https://github.com/ianstormtaylor/slate/issues/1325 to match how Immutable.js is moving towards solving it in the next release.

**Comment by lxcid** [comment]
Thanks @ianstormtaylor! Since the removal of deprecation warnings, this is no longer an issue for me.

Closing in favour of #1325…
