### ISSUE TITLE
flaky renderEditor

### ISSUE THREAD

**Issue by tpreusse** [ianstormtaylor/slate#1323]
JSFiddle: https://jsfiddle.net/maosf2j4/

Run the example and change the selection to see the flaky `renderEditor` in action: 
![oct-28-2017 20-10-25](https://user-images.githubusercontent.com/410211/32137242-4dd9432e-bc1c-11e7-9d9b-c5d451f50174.gif)

Observed: `renderEditor` of a plugin is only rendered on every second React render
Expected: `renderEditor` of a plugin is rendered on every React render

**Comment by ianstormtaylor** [comment]
Thanks for reporting this @tpreusse. Was a very weird one to track down 😄  but I figured out it was because I was accidentally mutating the plugins array with a `.reverse()` call without copying it first.  Fixing incoming.

**Comment by tpreusse** [comment]
Thank you for the fast fix.

I really like all the new APIs and guides, keep up the amazing work 🚀
