### ISSUE TITLE
Throw an error if on create if document doesn't have top-level blocks

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#135]
Right now it's possible to create "invalid" documents. For now Slate requires that the top-level children of each document be `Block`-type nodes, but you can create an invalid document by passing in `Inline` or `Text` top-level nodes, which leads to weird behavior later. Better to throw early so that this doesn't happen.

**Comment by darobin** [comment]
There are use cases for rich text editing of inlines only (eg. a title that can contain some styling, a single-paragraph abstract). Right now I'm handling this by wrapping my input in `<p>` and removing that when returning a serialised value (which is fine), but I wonder if this might not be a chance to support that directly by automatically wrapping this type of structure in some for of anonymous `Block` (that serialises to just its children), sort of a `DocumentFragment` as it were.

**Comment by ianstormtaylor** [comment]
Hey @darobin, good question. I think if we were to go that route, we should change the internal logic to not need the constraint in the first place. But for now I think it's simplest to just use that serialization technique. I do something similar!

**Comment by ianstormtaylor** [comment]
Closing because this is no longer an issue due to normalizing with the core schema in `0.15`. Woot! Props to @SamyPesse and @Soreine 🎉
