### ISSUE TITLE
Update React component by `node.key`

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/slate#1352]
#### Do you want to request a *feature* or report a *bug*?
Feature

We discussed in #1349 about certain cases that states are better storing in React's stateful components:

> Say we have an editor supports **attachment upload**, during uploading we insert a custom block with **progress bar** updated realtime, and after upload is done we replace it. So IMO what user expects is:
> 1. During uploading, cmd-z should directly removes the progress bar.
> 2. After upload is done, cmd-z should also directly removes the attachment block.
> 3. cmd-z shouldn't change the state of progress bar.

Adding `node.state` to Slate is duplicate of React, while IMHO it's still a great plus to use React's stateful components in Slate. Similar to calling `change.setNodeByKey`, can we support a change looks like `change.setComponentByKey` that updates this node's React component? This change is `{ save: false }` by default, thus updating component state won't effect history.

Here is another possible use case:

1. User selects among some blocks.
2. User clicks on toolbar button, changing selected blocks.

In this case it's a pain point for me **updating selected React component's state**, since I can only get their key in Slate's land, instead of React. Maybe I'm missing some API, any suggestions?

**Comment by chemzqm** [comment]
`change.setComponentByKey` would change the react compoennt without change the state document model?  Looks like not a good idea.  The feature you need could be done with `change.setNodeByKey` to modify the `data` of slate node (like `{data: {loading: true}`}) and use React to render it accordingly, you just need an option to make some operation not saving to history.

**Comment by doodlewind** [comment]
@chemzqm I know what you mean, you can check out discussion #1349 for details. My point is that in this case, **neither should progress bar's state serialized into `node.data`**, so updating it through Slate's model isn't that intuitive.

**Comment by chemzqm** [comment]
I see, what you need is just change the state of a wrapped component of img, so I think just make slate-react expost a API likst `findReactComponent` like `findDOMNode ` would fine, that change should not belong to `Change` I think.

**Comment by doodlewind** [comment]
@ianstormtaylor How do you think about adding a `node.ref` field, which is default to null, then we link it to our custom react components? This gives us the functionality calling component's instance methods. Things like `TableCell` in `Table` can make use of this, e.g. calling `Table`'s method to its state in `TableCell` without using the unsafe Context API.

If it's worth doing I'll try!

**Comment by ianstormtaylor** [comment]
I'm not sure exactly what you mean, could you give a code sample?

I don't think the Slate data model should have any references to the React components though. That seems like a weird relationship. You can refer the other way (by using `node.key`) but I don't think the data model should be referring to the view layer.

**Comment by doodlewind** [comment]
Say we have an `Attachment` custom block, with a `progress` state. And attachment can be inserted by clicking on button in `Toolbar`.

When user click on toolbar, we normally perform a `change.insertBlock` to insert an attachment component. Then during uploading we want to update the progress bar, and now how to update its `progress` state? I can find the attachment's key in slate's document model, and even find its DOM node. But still no idea about referring this key to its React component. @ianstormtaylor is there some utils I'm missing?

**Comment by doodlewind** [comment]
I read through React's doc and `node.state`/`node.ref` looks more like a hack.

For my case it'll be enough to simply introduce `node.data.state` storing temporary states, updating them with `change.setNodeByKey` with `save: false`, and simply omit this field when serializing.
