### ISSUE TITLE
Latest release breaks the JSfiddle for replicating errors

### ISSUE THREAD

**Issue by anewusr** [ianstormtaylor/slate#1382]
<img width="1417" alt="screen shot 2017-11-06 at 11 46 35 am" src="https://user-images.githubusercontent.com/23392285/32452694-40dfdcfa-c2e8-11e7-9923-f877e990fd11.png">

![screen shot 2017-11-06 at 11 46 26 am](https://user-images.githubusercontent.com/23392285/32452695-40ef8ace-c2e8-11e7-9758-714d33599f48.png)

Seems like the fiddle needs to be updated and/or the link in the Github issues updated as well.

**Comment by chemzqm** [comment]
That's because `setState` has changed to `setValue`, and `state` prop has changed `value`

**Comment by ianstormtaylor** [comment]
If someone could submit a PR that would be very appreciated!

**Comment by schneidmaster** [comment]
Looks like this is fixed in https://github.com/ianstormtaylor/slate/commit/237ae9fc2f146b5d18ae9702c6bd0bad12ce6152
