### ISSUE TITLE
`readOnly` not responding to updated values

### ISSUE THREAD

**Issue by ctrlplusb** [ianstormtaylor/slate#139]
Sorry to hassle again! :)

Having an `Editor` instance with `readOnly={false}` and then changing it's props (via update) to `readOnly={true}` doesn't result in `Editor` becoming read-only.

The bool value is computed dynamically in my case.

**Comment by ianstormtaylor** [comment]
Good call, due to `shouldComponentUpdate` on `<Content>` not being thought through. Might optimize it more later, but for now I removed the bug cause. Thanks!
