### ISSUE TITLE
Slate vanishes with error: Unable to find DOM node...

### ISSUE THREAD

**Issue by joaomlap** [ianstormtaylor/slate#1390]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?
Implementing the Slate Text Editor inside an **iframe**, when calling `this.setState({ value })` like on the following example the editor vanishes with the error message:
`Uncaught Error: Unable to find a DOM node for "3". This is often because of forgetting to add 'props.attributes' to a custom component.` But I don't have any custom component as you can see in the example:

```js
class App extends React.Component {

  state = {
    value: initialValue
  }

  onChange = ({ value }) => {
    this.setState({ value })
  }

  render() {
    return (
      <Editor
        value={this.state.value}
        onChange={this.onChange}
      />
    )
  }

}
```

#### What's the expected behavior?
I was expecting the editor to call the function and deal with the result properly :)

Thank you! :)

**Comment by bruno12mota** [comment]
Having the same problem after upgrading. was using `react-frame-aware-selection-plugin` before and it seems to no longer work. Any plans to support slate inside iframes out of the box? It's a fairly common use for styles encapsulation

**Comment by lxcid** [comment]
I did have a use case for iframe and can confirm this is throwing the above issue.

**Comment by joaomlap** [comment]
We create a PR that solves this issue, for anyone interested in using it already we created an npm package with the name `slate-react-iframe` that already uses the solution replacing `slate-react`.

**Comment by sethmcleod** [comment]
Thank you @joaomlap!
