### ISSUE TITLE
Firefox code block navigation

### ISSUE THREAD

**Issue by illesg** [ianstormtaylor/slate#1393]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

If you navigate into a code block, you cannot 'get out' of that block with keyboard arrows in Firefox

![slate-codeblock-nav-bug](https://user-images.githubusercontent.com/1759425/32599332-7b820d46-c53c-11e7-8bc7-de7189140ab8.gif)

Firefox 56.0.2 (64-bit)
Mac OS 10.12.6
"slate": "0.30.6"
"slate-react": "0.10.11"

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
