### ISSUE TITLE
Editor onChange is called after unmount

### ISSUE THREAD

**Issue by danielsarin** [ianstormtaylor/slate#1395]
#### Do you want to request a *feature* or report a *bug*?

Bug?

#### What's the current behavior?

After mounting the `Editor` component from slate-react, if it unmounts very quickly, onChange is  called after unmount. Because I use `setState` in the change handler, it results in this warning:

> Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

https://jsfiddle.net/g0ghks7q/

I know it's not ideal to unmount the editor almost immediately, but this happens in our app because of how it's built, and it is somewhat difficult to change.

#### What's the expected behavior?

Could the unmount be handled internally in the Editor component, so that it would not call the onChange handler after unmount?

**Comment by ianstormtaylor** [comment]
That workaround sounds great to me, cancelling the propagation if it unmounts before it's triggered.
