### ISSUE TITLE
Allow overriding `fragment` in onCutOrCopy

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1410]
#### Do you want to request a *feature* or report a *bug*?

Request a feature.

#### What's the current behavior?

If you want to change the fragment that gets copied in onCopy, you have to reimplement the entire function, including all of the encoding and browser compatibility quirks. 

For example, if I have a table, and I want to programmatically copy a non-continuous range of cells onto the clipboard, I have no way to do that.

#### What's the expected behavior?

My plugin should be able to define a method that onCutOrCopy will call to get the fragment here: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/after.js#L164. 

`after.js` can hold the default behavior of returning `value.fragment`. This will allow a plugin author to customize just the part of copying that will most likely need to be changed.

**Comment by ianstormtaylor** [comment]
Is there a way we might instead package up the `onCutOrCopy` logic into a helper similar to `getEventRange` or `getEventTransfer` that could be used. That way there wouldn't need to be interdependency between plugins, but just a util that gets used that contains the majority of the complex logic?

**Comment by justinweiss** [comment]
Yep, that would more-or-less solve #1411, I think. It'd also solve my use case here, if there were a way to pass a fragment into `onCutOrCopy`.

**Comment by tobiasandersen** [comment]
I've been wanting to do similar things as @justinweiss, and the idea proposed by @ianstormtaylor sounds perfect to me.

**Comment by justinweiss** [comment]
@ianstormtaylor I took a stab at this in https://github.com/ianstormtaylor/slate/pull/1429.

**Comment by ms88privat** [comment]
That's a step in the right direction. I'm upgrading slate to the new version since 0.20 and I see that the "beforePlugin` can also not be overwritten? Is this statement correct?

**Comment by majelbstoat** [comment]
It has since become very hard to do this again. Possibly during 0.50 rearchitecture? The only approach appears once more to reimplement the full logic of setFragmentData from slate-react because it isn't exported.

I'm putting together a proposed PR to make this flexible again.
