### ISSUE TITLE
Allow overriding of delete behavior in `onCut`

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1411]
#### Do you want to request a *feature* or report a *bug*?

Request a feature

#### What's the current behavior?

Say I have a table with some selected table cells. When a user cuts the cells, I would like the cells to be cleared instead of deleted. In order to make this work, I need to override onCut, and reimplement all of the clipboard and browser compatibility pieces of onCutOrCopy.

#### What's the expected behavior?

In my plugin, I should be able to write a function that specifies the behavior onCut should use to delete the selected content. It should run somewhere around here : https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/after.js#L124
, and it should be able to defer to the existing behavior in the same way other plugins do.

We can default to the current behavior in `after.js.`

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
