### ISSUE TITLE
Navigation issue with line break at the end of a text node

### ISSUE THREAD

**Issue by illesg** [ianstormtaylor/slate#1413]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

If you have a text node with one or multiple line breaks (\n) at the end, the caret jumps the whole block if you navigate from the bottom with the UP arrow key
JSFiddle: https://jsfiddle.net/yrwunmck/
GIF:
![navigation-bug](https://user-images.githubusercontent.com/1759425/32895202-8defd032-cadf-11e7-9e1a-5d1340ed6566.gif)

Mac OS 10.12.6
Chrome 62.0.3202.94
"slate": "^0.30.7",
"slate-react": "^0.10.12",

#### What's the expected behavior?

the caret shouldn't jump the block

**Comment by justinweiss** [comment]
This seems to have been fixed sometime in the last year -- I haven't been able to reproduce it under 0.47.

**Comment by illesg** [comment]
yup, it looks like it's fixed, I couldn't reproduce it either 
thanks
