### ISSUE TITLE
Markdown Preview Example does not apply mark type 'punctuation'

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1419]
The issue is somewhere in the `decorateNode` function, my skills are enough to (maybe) have identified the issue, but not enough to fix it.

1. The `getLength()` function appears to possibly be broken (always returns 0?)
2. The code doesn't seem to traverse downward into the content of the tokens, so it doesn't apply marks to the inner tokens (in this case the punctuation)

https://github.com/ianstormtaylor/slate/blob/master/examples/markdown-preview/index.js#L116

**Old behavior (pre-schema changes):**

![image](https://user-images.githubusercontent.com/6835891/32984008-0b29520c-cc6c-11e7-8993-f274c18c8bf6.png)

**New behavior:**
![image](https://user-images.githubusercontent.com/6835891/32984011-1395c3b2-cc6c-11e7-9439-9048c4d9a4e7.png)

**Comment by dskeppstedt** [comment]
@ianstormtaylor Any comment on this? 
I'm also struggling to incorporate this example into the rich text example, the marks does not seem to be applied correctly.. Any pointers?

**Comment by Slapbox** [comment]
This (outdated) package builds off the original code for the markdown example: https://github.com/withspectrum/slate-markdown

**Comment by ianstormtaylor** [comment]
I think this is one of those cases where it's out of scope for the example. When previewing Markdown I feel like you don't really want the punctuation highlighted? Either way, the example is meant to be a super simple version of a real editor.
