### ISSUE TITLE
Carret position and copy paste is broken on latest firefox

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#142]
![slate-ff-broken](https://cloud.githubusercontent.com/assets/3372410/17014915/7c7ef1dc-4f27-11e6-80ff-6bfb98ba81eb.gif)

**Comment by arekkas** [comment]
On FireFox, the console shows an error:

![fferr](https://cloud.githubusercontent.com/assets/3372410/17015107/91b7827a-4f28-11e6-842d-d3b056da14d8.PNG)

On Chrome, there's also a selection issue which is causing the console to throw some errors:

![chrome](https://cloud.githubusercontent.com/assets/3372410/17015076/7a3d343c-4f28-11e6-8b2e-ada7944e7762.PNG)

**Comment by ianstormtaylor** [comment]
Fix incoming. Apparently Firefox doesn't like the newer `selection.selectAllChildren()` approach, so I fell back to the older `range`-based one.
