### ISSUE TITLE
Examples use event.metaKey to capture ctrlKey, but on Windows this does not work

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1422]
On Windows event.metaKey is false when using the `Ctrl` key. This leads to the plugin examples not working on Windows and the same for any other code copying this method: https://docs.slatejs.org/walkthroughs/using-plugins

**Comment by potatopotaro** [comment]
I might be mistaken, but I believe metaKey is the Windows button itself:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

Unless you're using Firefox > 48

**Comment by Slapbox** [comment]
Correct, but on Mac it's the Command Key (the Clover), which is used in place of Ctrl in Mac often if I'm not mistaken, for example Command+C to copy instead of Ctrl+C. Someone correct me if I'm wrong.

**Comment by Slapbox** [comment]
I realize by the way that I wasn't clear. This is only an issue in the guides such as: https://docs.slatejs.org/walkthroughs/using-plugins not in the `/examples/` folder. I will try to get around to fixing these soon.

**Comment by Soreine** [comment]
What we did in `slate-edit-table` was to use [`is-hotkey`](https://github.com/ianstormtaylor/is-hotkey/) to properly define shortcuts using the `Mod` alias. This was done by slate itself before.

**Comment by schneidmaster** [comment]
This should be fixed by #1601

**Comment by Slapbox** [comment]
Whoops. Really dropped the ball here. This was specifically about the walkthrough using `metaKey` instead of `ctrlKey`, which won't work for Windows.

Do the examples as written (now using `ctrlKey`) work on Mac? If so this issue is properly closed.

**Comment by schneidmaster** [comment]
Yep no worries! `event.ctrlKey` works as expected on Macs as well so I think we're all set.
