### ISSUE TITLE
Jumpy scroll behavior - Cannot reproduce in fiddle, but have identified the cause

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1423]
This jumpy behavior identified first by @erquhart first appears as far as I can tell in `slate-react@0.10.12` @isubastiCadmus attempted to recreate this issue but could not. I am using flexboxes to enclose the editor and running in Electron. @erquhart are you using either of these? I can't understand why this issue is so hard to recreate in the browser, but clearly we're both having it.

![kapture_2017-11-16_at_17 26 49_480](https://user-images.githubusercontent.com/6835891/32997140-e41b9f46-cd59-11e7-88ed-fab7a65c2725.gif)

The cause for this jumpy behavior is the changes to `lines 76 - 78` in this commit https://github.com/ianstormtaylor/slate/commit/b973580c54be4cfddd3e7b61e6c7f4222d6ee5b2#diff-b806990bb5947c2478afde90966b8a83

I tried fixing this with CSS display type and overflow rules, but no luck. I edited these lines in chrome developer tools while the code was running to revert to the old behavior and the issue is immediately resolved. Without these changes the scroll to move the focused point onto the screen is overly aggressive, but no longer jumps erratically.  I actually attempted a very similar solution for a hovering menu using offsets based on `getBoundingClientRect()` and it also lead to jumpy behavior in the menu.

Recommend reverting to the following code until a better solution to overly aggressive scroll behavior can be found.
```
    yOffset = scrollTop
    xOffset = scrollLeft
```

**Comment by dmitrizzle** [comment]
Can confirm scrolling is a little nuts. Can't put my finger on where exactly since it's happening in a variety of cases (like after I modify the link or focus on void block - sometimes) but it certainly feels a bit out of control.

**Comment by Slapbox** [comment]
For me at least I can consistently reproduce it by placing the cursor within 3 lines of the edge of visibility. 4 lines sometimes. And modifying elements in the dead center of the page sometimes (with checkboxes based on the example page for one)

**Comment by echenley** [comment]
I believe this is a dupe of https://github.com/ianstormtaylor/slate/issues/1416 and https://github.com/ianstormtaylor/slate/issues/1032.

**Comment by Slapbox** [comment]
@echenley You are correct. I swear I looked for duplicates, but I must be blind because #1416 is about as recent as they come.
