### ISSUE TITLE
Editor doesn't immediately normalize/validate after changing schema.

### ISSUE THREAD

**Issue by potatopotaro** [ianstormtaylor/slate#1426]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?
Upon receiving a new schema, the editor does not normalize/validate according to the new schema's validation rules. Instead, it relies on the previous schema.

JSFiddle: https://jsfiddle.net/fj9dvhom/14/

GIF: http://g.recordit.co/GfBFoB3OKh.gif

#### What's the expected behavior?
If i'm not mistaken, the editor should normalize/validate **upon** getting a new schema rather than **after**.

**Comment by Slapbox** [comment]
Not sure if this is related or different, but my schema validation seems to be applied one change after I would expect.

For example if I forbid putting an `h1` in a `list-item` it will place the `h1` block in there anyway if I ask it to, and remove it the very next time `onChange` is called.

**Comment by potatopotaro** [comment]
That is probably related.

After looking closely, I also noticed that the Editor's value prop is not updated using the new schema prop until onChange is called; even though it render's the value with the new schema applied.

**Comment by lxcid** [comment]
I wrote up an analysis on another ticket relating to the new schema behavior, I was wondering is it related to this?

https://github.com/ianstormtaylor/slate/issues/1401#issuecomment-344264598

I’m currently away and might have some difficulties contributing for next few weeks. But will follow closing…
