### ISSUE TITLE
Bug: Cursor jumps when line-height is applied to editor

### ISSUE THREAD

**Issue by mattmazzola** [ianstormtaylor/slate#1436]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
If there is custom line-height applied to the editor the cursor jumps positions when there is no text.

See recording:
I start with line-height using default, but half way through apply line-height of 2em and notice when there is no text the cursor jumps up

http://recordit.co/EoWVXHfDBB

#### What's the expected behavior?
I think the cursor should stay on the same line.

**Comment by Slapbox** [comment]
This is likely due to empty spans used as placeholders like this:

`<span data-slate-zero-width="true">&#8203;</span>`

In the cases where this causes issues for me, I apply custom CSS like this:

```
span[data-slate-zero-width='true'] {
    position: relative;
    top: -3px;
}
```

Hope this helps!

**Comment by sebas5384** [comment]
Can confirm this is happening.

**Comment by isubastiCadmus** [comment]
I have the same thing happening but solved it by using custom renderPlaceholder so that the placeholder has `float: left`

**Comment by mattmazzola** [comment]
Any update on this bug?

In some cases it's just slightly off, but in this case it's really off:
![image](https://user-images.githubusercontent.com/2856501/52891585-ca1bd380-3140-11e9-8395-977ad76a29e6.png)

@isubasti Can you share example of this?

I tried using something like https://github.com/ianstormtaylor/slate/commit/a09c3c2fdfe87605988a13e968643f81b4936978#diff-c9782a4dca34d1f2858bab56d1202753L110

But it seems the node schema has changed and it errors. If I always returns the `<span>` is stays even after the user enters text which it should remove the placeholder.

**Comment by comerc** [comment]
@mattmazzola - thanks! your solution work fine for me:

```css
  [data-slate-editor='true'] span[contenteditable='false'] {
    float: left;
  }
```

**Comment by isubasti** [comment]
using `contenteditable=false` selector is probably not a good idea as void elements will have that as well. ideally you want to style the placeholder itself which you can do by creating your own placeholder plugin or wait till https://github.com/ianstormtaylor/slate/pull/2667 to add style to the placeholder or create a PR to add `float:left` to default placeholder's style.

**Comment by comerc** [comment]
@isubasti, thanks! 

> create a PR to add float:left to default placeholder's style.

@ianstormtaylor, do you want this PR?

**Comment by namnm** [comment]
Any news?

**Comment by dylans** [comment]
Tested this against the latest slate and it appears that this was fixed a while ago.

If not, please provide a test case and we'll get it fixed. Thanks!
