### ISSUE TITLE
editor loose focus unexpectedly after rerender

### ISSUE THREAD

**Issue by raffy2010** [ianstormtaylor/slate#1437]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
When autoFocus flag is set for Editor, it's focused in DOM but not in Slate selection
after it's mounted to DOM. So another rerender will make it blurred unexpectedly.

here's [fiddle link](https://jsfiddle.net/eL397ztr/1/)

```js

const App = () => {
  return (
    <Editor
      autoFocus
    />
  )
}
```

#### What's the expected behavior?
I think it should be keep focused until user interaction changes it.

**Comment by raffy2010** [comment]
#1438

**Comment by Slapbox** [comment]
#1438 alone may not be enough to fix this.

Calling the `.focus()` method can lead to instant blur of the editor in `Slate 0.31.x` - Not sure how to reliably reproduce this though, and therefore cannot rule out my own mistakes causing it.

**Comment by benjycui** [comment]
@raffy2010 @Slapbox https://github.com/ianstormtaylor/slate/pull/1733 had fixed this issue, just try the latest slate.

And you can close this issue now.
