### ISSUE TITLE
Operations don't round-trip through JSON

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1439]
#### Do you want to request a *feature* or report a *bug*?

Report a bug.

#### What's the current behavior?

https://jsfiddle.net/gm13srfv/1/

Open the console and trigger a change (set_selection by clicking in the editor should be enough). You'll see the following error: 

> `Operation.fromJSON` was passed a “set_selection” operation without the required “value” attribute.

#### What's the expected behavior?

I would expect to get an Operation back that could be used like the original Operation.

It looks like the `value` attribute gets stripped in `toJSON`, but Slate tries to parse it back in in `fromJSON`.

I _think_ the value is only used for local undo / redo, it which case I think it should be stripped in `toJSON` and not expected in `fromJSON`. But I wanted to confirm before I send a PR. Either way, it should be consistent.

**Comment by ianstormtaylor** [comment]
@justinweiss you're absolutely correct in your description at the end there, I'd love a PR to fix that, thanks!
