### ISSUE TITLE
switch to production build of React on slatejs.org

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#145]

**Comment by arekkas** [comment]
Is the distributed npm package built in React production mode?

**Comment by arekkas** [comment]
Also it would be great to have both on slatejs.org:

* Production: `slatejs.org/`
* Development: `slatejs.org/debug/`

**Comment by ianstormtaylor** [comment]
Fixed as:

- `slatejs.org`
- `slatejs.org/dev.html`
