### ISSUE TITLE
Select all + enter results in an error when there is a trailing empty block

### ISSUE THREAD

**Issue by zGrav** [ianstormtaylor/slate#1452]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

Refer to #1447 

Issue can be reproduced on the default fiddle: https://jsfiddle.net/fj9dvhom/1/

#### What's the expected behavior?

should be able to type.

**Comment by ianstormtaylor** [comment]
This is fixed in the latest versions of Slate.
