### ISSUE TITLE
Bug in table undo: The last cell is not restored after delete->undo change

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1455]
#### Do you want to request a *feature* or report a *bug*?

 A Bug

#### What's the current behavior?

Unexpected `undo` behavior in re-inserting a table;  See the gif below

![tfpwgw4hyb](https://user-images.githubusercontent.com/746159/33671576-f898ae36-da75-11e7-895b-b4d2712b667e.gif)

#### What's the expected behavior?

The last cell should be in the cell.

**Comment by zGrav** [comment]
Possibly could be fixed with #1456 if a solution is developed for it.

**Comment by zhujinxuan** [comment]
@zGrav  I am not sure whether bundle change could solve the problem.  I try undo multiple times but the last cell is still not restored

**Comment by CameronAckermanSEL** [comment]
This should be resolved in #1594

**Comment by zhujinxuan** [comment]
@CameronAckermanSEL  Fixed.  Thank you.
