### ISSUE TITLE
Delete key behaves more like backspace when selected block is empty

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1457]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?

When the selection is on an empty block, the delete key behavior is more like backspace.

This causes an odd behavior where the cursor moves to the previous sibling when delete key is pressed instead of staying at the same block. Additionally, delete does not promote the content next sibling block to the current selected block as expected.

http://recordit.co/cBMAOQVAr8

#### What's the expected behavior?

Expected behavior is that delete key always maintains current block selection.

**Comment by Slapbox** [comment]
This can be confirmed on any of the live examples: http://slatejs.org/#/rich-text

**Comment by zGrav** [comment]
I do not suffer from this issue at this point, will try to investigate

**Comment by zGrav** [comment]
I am not being able to replicate this on a empty block even on the demo, weird

**Comment by CameronAckermanSEL** [comment]
Reproduces in Firefox and Chrome.

**Comment by zGrav** [comment]
Interesting, opening the demo on Chrome 62 on OS X, I am not being able to reproduce it

**Comment by CameronAckermanSEL** [comment]
http://osxdaily.com/2013/04/26/delete-key-mac-forward-del/ 

> The delete key on a Mac keyboard functions like a backspace key on a Windows/PC keyboard, deleting a character a time backwards from where the cursor is located.

On windows, the delete is a forward delete, so this is doing the wrong thing.

**Comment by zGrav** [comment]
Aha, I see. Sneaky OS X...

**Comment by zGrav** [comment]
Fixed, I believe.
