### ISSUE TITLE
scroll-to-selection: doesn't scroll all the way down

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#1461]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
It doesn't scroll all the way down:
![Before](http://g.recordit.co/A4MombAG5B.gif)

It should scroll all the way down:
![After](http://g.recordit.co/9paIsM0Dpf.gif)

The problem seems to be here:

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/scroll-to-selection.js#L120

```
const selectionFocusTop = backward ? selectionRect.top : selectionRect.bottom
```

Should  be the other away:

```
const selectionFocusTop = backward ? selectionRect.bottom : selectionRect.top
```

EDIT: [updated proposal to fix](https://github.com/ianstormtaylor/slate/issues/1461#issuecomment-350358506)

**Comment by skogsmaskin** [comment]
@echenley Was that order intentional, or was it just a code error?  There are some many edge cases with this, so I figured I would make an issue before submitting a PR.

**Comment by echenley** [comment]
@skogsmaskin The top one looks correct to me. I was under the impression it should be moving to the edge of the selection, not the whole block. That said, this code was there before my refactor and I left it intact. I think it's basically just there to figure out which side the cursor is on, so if the selection is backward, the cursor is at the top.

**Comment by skogsmaskin** [comment]
Ok, I just git blamed the line. I will investigate further and probably make a PR. The way it is now is not very user friendly. People should be able to see part of the below context they are editing in. And if they are one the end of the document, it should scroll all the way down.

**Comment by echenley** [comment]
Could you add padding to the scrollable container instead of having a bottom margin on the block? I believe that could give you the behavior you're looking for without changing the scroll logic. In that case, the bottom of the selection would be the bottom of the container.

**Comment by skogsmaskin** [comment]
No, I tried that and at least 10 other hacks. The logic is just wrong.

**Comment by echenley** [comment]
Okay, I'll take a look. Thanks for the bug report.

**Comment by skogsmaskin** [comment]
I see it was @ianstormtaylor which introduced that logic to begin with. Maybe he has has an opinion here. I think the correct logic is something like:

1) User is in the end of the document. Scroll all the way down.
2) User is somewhere in between (scroll like today, but add a couple of lines for the user to see context below
3) User is in the top of the document. Scroll all the way to the top.
4) Something that deals with backward selections and add a little context on top.
5) Profit.

**Comment by echenley** [comment]
@skogsmaskin Can you check to see if my PR works for your use case?

**Comment by skogsmaskin** [comment]
@echenley Thank you for the PR, unfortunately my issue was not solved by this.

I think it is as I say, there is something wrong with the logic itself, and I think I see what is wrong. It doesn't take into account that the selection can be collapsed. And when it is collapsed, it is always backward. 

So the proper thing to do is something this:

```
  let selectionFocusTop = selectionRect.bottom
  if (range.collapsed && selectionRect.top > (height / 2)) {
    selectionFocusTop = selectionRect.bottom
  } else if (range.collapsed) {
    selectionFocusTop = selectionRect.top
  } else {
    selectionFocusTop = backward ? selectionRect.top : selectionRect.bottom
  }
```

Your PR fixes another important issue though, it also has to respect the padding!

**Comment by echenley** [comment]
@skogsmaskin You're right that something is off. Pinged you on the slack channel if you could take a look.

**Comment by skogsmaskin** [comment]
Let's discuss this further in https://github.com/ianstormtaylor/slate/pull/1462.

Closing this as @echenley 's PR makes an acceptable solution to this.
