### ISSUE TITLE
Do we need a `wrapSelectionInline()` method?

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#1463]
#### Do you want to request a *feature* or report a *bug*?
Feature

#### What's the current behavior?
Just stumbled into this unexpected behavior with `wrapInline()` method inside a single inline parent. The current behavior splits the parent inline into 3 inlines and wraps the middle into the one supplied to the method. This is apparently very much intentional. I'm failing to come up with any use case that I would want this to happen.

#### What's the expected behavior?
I would expect my selection to be wrapped by the inline and not have side effects on parts that I haven't selected. Here's the expected use case:
https://github.com/ianstormtaylor/slate/pull/1460/files

So my question here is obvious: Is there a different method to achieve this? How are you guys using `wrapInline()`? How do I wrap my selection in an inline without destroying the parent structure?

**Comment by ianstormtaylor** [comment]
@czechdave I'm having a hard time thinking about when you'd want the current logic as well. It matches the "wrap" behavior of block kinda, but that's not a great reason I think.

**Comment by czechdave** [comment]
I'm implementing "citations" into my editor and I'm using inlines as the docs says they can be nested so they seem ideal. The issue arises if I create an inline node over a whole sentence and then want to create another nested one around just one word.

Is there a different way to accomplish this by using some other method than `wrapInline()`?

**Comment by crisward** [comment]
Just came across this - also having this problem. Any progress been made on this? It would be ideal if it  worked the same way as `addMark`.
