### ISSUE TITLE
Any reason EventHandlers are just a subset of React's Synthetic Events?

### ISSUE THREAD

**Issue by lomaxap** [ianstormtaylor/slate#1464]
I need to make use of the onDrag event for my editor. The [event-handlers](https://github.com/ianstormtaylor/slate/blob/a3d91b6daae95642f19fd2b2fd7e3308c88113ac/packages/slate-react/src/constants/event-handlers.js#L8-L29) constant, however, only lists a subset of react's Synthetic Events. Any reason? 

I've added onDrag to my local copy, and it works fine. Happy to submit a PR that adds events if there's no reason not to.

**Comment by ianstormtaylor** [comment]
Nope, no reason, I just forgot that one. I've love a PR! Thanks

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
