### ISSUE TITLE
Default schema normalization infinite loop

### ISSUE THREAD

**Issue by tommoor** [ianstormtaylor/slate#1466]
#### Do you want to request a feature or report a bug?

Bug

#### What's the current behavior?

In the latest versions of Slate nested marks when the schema specifies `marks: ['']` results in an infinite loop attempting to normalize. See JSFiddle reproducing the issue here:

https://jsfiddle.net/fj9dvhom/20/

Screenshot of stack:
![image](https://user-images.githubusercontent.com/380914/33922898-bd563570-df82-11e7-8c78-97e2dbb39752.png)

#### What's the expected behavior?
The expected behavior is that the node would have all marks removed. Perhaps there is a better way of specifying that a node should only be plain text with no children or marks? If that's the case I'd be happy to put in a PR improving the docs on this usecase 😄

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
