### ISSUE TITLE
Slate fires blur and focus events when moving caret over void nodes

### ISSUE THREAD

**Issue by delijah** [ianstormtaylor/slate#1467]
# Software versions
OS: macOS Sierra v10.12.3
Browser: Google Chrome 62.0.3202.94
slate: 0.31.5
slate-react: 0.10.20

# Problem
The newest slate version renders void nodes differently than older versions (in particular where the contenteditable attribute is applied has been changed). This causes the browser to fire blur and focus events, each time you move the caret from a void node to text or the other way around. This did not happen before. We believe the new behaviour is wrong. The user is not really leaving the editor, he is only moving the caret trough the editor (why should a blur event been fired?).

A short example how void nodes were rendered before and how they are rendered now.

Before:
```
<div data-slate-void="true" ...>
    <span ...>
        <!-- Zero width space -->
    </span>

    <div contenteditable="false">
        <!-- My custom void node contents --->
    </div>
</div>
```

Now:
```
<div data-slate-void="true" contenteditable="false" ...>
    <div data-slate-spacer="true" contenteditable="true" ...>
        <!-- Zero width space -->
    </div>

    <div draggable="true">
        <!-- My custom void node contents --->
    </div>
</div>
```

Since in the new version a `contenteditable="true"` is inside a `contenteditable="false"`, the browser kind of thinks the zero width space is a "new" editor and fires a blur event for the outer editor (the actual slate editor) and a focus event for the inner editor (zero width space) when moving the caret by using the keyboards arrow keys.

# Actual behaviour
When moving the caret through the editor and passing by void nodes, blur and focus events are fired.

# Desired behaviour
Blur and focus events should not be fired when moving the caret through the editor since we are not really leaving nor entering the editor. The focus stays within the editor during the whole process.

We have created a small test project to easily see the different behaviours. Just switch slate-react between the above mentioned version and PR #1465 by using `npm link`:
https://github.com/DND-IT/slate-void-node-blur-showcase

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
