### ISSUE TITLE
*bug* iOS backspace and enter keystrokes not registering correctly with autocorrect.

### ISSUE THREAD

**Issue by davidlibland** [ianstormtaylor/slate#1471]
**What is the current behavior?**
1) When pressing backspace, the iOS autocorrect bar does not register the change. For example if you type "The", and then delete all the characters to "", the iOS autocorrect bar still thinks "The" is the current state. If you then type "none", it thinks you've typed "Thenone".
2) When pressing enter, the iOS autcorrect bar does not register the change. For example, if you type "none<enter>pere" it thinks you typed "nonepere" (one word, no space).

![slate_ios_autocorrect](https://user-images.githubusercontent.com/19326411/33981534-24f37622-e062-11e7-9cb6-570a2453f229.gif)

**What is the expected behavior?**
1) When pressing backspace, the iOS autocorrect bar should update appropriately.
2) When pressing enter, the iOS autocorrect bar should update appropriately.

**Which versions of slate and which browser / OS are affected by this issue?** 
Tested on iOS safari with:
"react": "16.2.0",
"react-dom": "16.2.0",
"slate": "0.31.7",
"slate-react": "0.10.22"

Note that draft.js has a very similar issue (cf. https://github.com/facebook/draft-js/issues/1574)

**Comment by rgrove** [comment]
I think the right way to fix this is to handle these input types in `<Content>`'s [`onNativeBeforeInput`](https://github.com/ianstormtaylor/slate/blob/4e021f58b5186e61d7ace2a89a3052412d8ff5e7/packages/slate-react/src/components/content.js#L359) handler, similarly to how text input is handled. This seems to be the only way to play nicely with iOS's native autocorrect behaviors.

**Comment by davidlibland** [comment]
@rgrove I've looked at a lot of your work regarding `onNativeBeforeInput` (thanks, by the way! Excellent job!). Unfortunately, no `beforeInput` event is triggered by either `Backspace` or `Enter`; I think that's part of the problem. Any ideas?

**Comment by davidlibland** [comment]
@rgrove, for example (logging events using your fiddle), when pressing a regular key like "T", we get 
```
[Log] {type: "keydown", code: "KeyT"}
[Log] {type: "keypress", code: "KeyT"}
[Log] {type: "textInput", data: "T"}
[Log] {type: "beforeInput", inputType: "insertText", data: "T", dataTransferText: null, targetRanges: Array}
[Log] {type: "selectionChange"}
[Log] {type: "keyup", code: "KeyT"}
[Log] {type: "selectionChange"}
```

whereas for backspace, we get:
```
[Log] {type: "keydown", code: "Backspace"}
[Log] {type: "selectionChange"}
[Log] {type: "keyup", code: "Backspace"}
[Log] {type: "selectionChange"}
```
and for enter we get:
```
[Log] {type: "keydown", code: "Enter"}
[Log] {type: "selectionChange"}
[Log] {type: "keyup", code: "Enter"}
[Log] {type: "selectionChange"}
```

**Comment by rgrove** [comment]
@davidlibland Using a [more recent testbed](https://codepen.io/rgrove/pen/aLROMw?editors=1010) that captures more detail, I'm seeing iOS Safari generate `deleteContentBackward` input types on backspace/delete, and `insertParagraph` on return. I think this should be enough to fix this.
