### ISSUE TITLE
Concurrent problems whith collaborative editing

### ISSUE THREAD

**Issue by TimYi** [ianstormtaylor/slate#1472]
Collaborative editing algorithm like operational transformation require an operation can only be applied on the document state from which this operation was generated.

Even thougn javascript is single thread, however react's setState method is asynchronous, this may lead to some puzzle when desiging collaborative editor.

Case 1:

Let the initial state of the document be Ds.

An local operation is generated by slate editor, name it Lo1. Lo1 will be send to onChange method until react method componentDidUpdate is called. This is an asynchronous process.

Assume this Lo1 is generated and waiting to be updated, maybe in an setTimeout. At this time, slate's document state does not change, is still Ds. Collaborative algorithm don't know there's a Lo1, and a remote operation Ro1 arrives, Ro1 is generated on state Ds, so collaborative algorithm thinks Ro1 should be applied instantly, then it will call slate's change method. And slate apply this Ro1, but Ro1 is actually applied on document state Ds + Lo1, and should not be applied on Ds directly.

Then onChange method receive Lo1 after componentDidUpdate is called, and send it to collaborative kernel, collaborative kernel don't know Lo1 is generated on document state Ds, it regards Lo1 as generated on state Ds + Ro1. Collaborative kernel then append Lo1 after Ro1, and send Lo1 to the remote.

Then convergency may be broken by this process.

A correct process of this story should be:

Slate generate an local operation Lo1, no matter when react should update the ui, Lo1 should be instantly applied to slate document, call onChange method and notice collaborative kernel Lo1 is generated on Ds, then quit this synchronous process.

We assume the collaborative kernel does not submit Lo1 instantly, may be the net state is not good.

Then collaborative kernel receive a remote operation Ro1, it knows Ro1 and Lo1 is current operation, and apply transformation on them, which transform Ro1 to Ro1', Lo1 to Lo1', satisfy Ds + Lo1 + R1' = Ds + Ro1 + Lo1'.

Then collaborative kernel apply Ro1' on slate editor, the collaborative kernel stores all changes as Ro1 + Lo1', then it send Lo1' to the remote.

This is the correct process, it ensure convergency because it obey constrains of ot algorithm.

As a conclution, slate should guarantee:

Whenever an operation is generated or applied, slate's document state should be updated synchronously, no matter if ui will be updated synchronously. Otherwise, the base for collaborative editing is broken.

We are reconstruct our collaborative editor on slate, but we met the concurrent puzzle above, have slate considered these things, what should we do to avoid these problems?

**Comment by thesunny** [comment]
Hi @TimYi

I may be misunderstanding the issue here but in case I can lead you down the right path I thought I’d comment.

What I’ve done in cases where the setState sync lag is unacceptable is to use a property on the component as the source of truth and only using setState to convey rendering.

So, for example, when an onChange event comes in, you can store values directly on the component like this.localState = someValue. I would still also use setState to convey rendering but not rely on it for the source of truth.

The this.localState however will be set synchronously which should satisfy your requirement.

When a new incoming remote operation arrives you can use the value in this.localState to calculate the merged state because it will be current even if this.state is not yet updated.

**Comment by TimYi** [comment]
Thank you @thesunny 

Your solution may solve my problem, but I am worried whether this will cause the following problem.

When I receive a remote operation, say I add a new character at position 2, I transform and apply it on the localState synchronously, and then change state of slate edithr asynchronously. Client user may input another character at position 3. If slate state is not updated yet, it will generate an incorrect change, after apply this change to the localState, the localState and the slate state will end up in different state.

I read some react.setState related information, It seems that setState is not really 'asynchronous' like what setTimeout(func,0) is. If you call several setState inside one invocation(for example a eventHandler) react will do only on update synchronously at the end of this invocation. So for a invocation like websocket onMessage callback, we can regard it synchronous.

So I think I just need to take care of  my use of setState, and don't worry about the concurrent problem.
