### ISSUE TITLE
Could we have rules to deserialize <body>?

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1476]
#### Do you want to request a *feature* or report a *bug*?

Feature

#### What's the current behavior?

In the current code of slate-html-serializer, the <body/> is deserialized by 
``` 
    const children = Array.from(fragment.childNodes)
    let nodes = this.deserializeElements(children)
    ....
    const json = {nodes}
    return {Value.fromJSON(json)}
```

However, it becomes difficult when parsing some crazying html full of span and br, because `nextSibling` and `prevSibling` cannot have enough information.
```
body
  span
  br
  span {font-size = 10pt}
    span
     br
     ul
```

#### What's the expected behavior?
I think it might be better if user can customize the deserialize of the body, just like other el nodes.

**Comment by zGrav** [comment]
It is possible, I am doing something similar to handle special cases on pasting and such...

It's a tad ugly, but hey, it works...

https://gist.github.com/zGrav/440fdbe83d7eca8455362ccfd2e58662

**Comment by zhujinxuan** [comment]
@zGrav My personal solution is to rewrite the parseHTML for replacing body with body>div:

My ugly solution:
https://gist.github.com/zhujinxuan/1ddaf3bea314f6cc5c04ecdb9c99830c
