### ISSUE TITLE
Race condition caused by Editor queuing/flushing changes

### ISSUE THREAD

**Issue by lxcid** [ianstormtaylor/slate#1479]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

I have contributed to the discussion around here about how the behaviour of Editor queuing/flushing changes is detrimental for a multi-editor environment, performance wise (mainly due to the need to use `setTimeout()`). See #1401 & https://github.com/ianstormtaylor/slate/issues/1318#issuecomment-341956697.

But recently, I realise that this behaviour also introduce race condition if you want to use it in a collaborative multi-editor environment.

I'll try to walkthrough what's going on and will also accompany by [an example](https://jsfiddle.net/lxcid/q91uydtz/) that will require #1478 to be merged to be able to reproduce.

First of all when you instantiate an `<Editor />`, it will queue a change (the change have operation) immediately.

https://github.com/ianstormtaylor/slate/blob/22576e521fc956563996e91de23551ca03cce312/packages/slate-react/src/components/editor.js#L90-L95

That is because `value.schema` and `editor.schema` are different. During `Editor.constructor()`, `value.schema` likely contains only a default `Schema` while `editor.schema` is assigned a newly created `Schema` with plugins resolved from the `Editor.props`.

https://github.com/ianstormtaylor/slate/blob/22576e521fc956563996e91de23551ca03cce312/packages/slate-react/src/plugins/before.js#L113-L126

Thus, this explain that `Editor` will always generate and queue a change on `Editor.constructor()`.

The issue lie in that the `Editor.constructor()` decide to queue the change. So during `Editor.componentDidMount()`, when `Editor` finally decide to flush the change, instead of processing it immediately, it delay it slightly with `setTimeout()`.

https://github.com/ianstormtaylor/slate/blob/0afe15fa7694e53bad1d9843a15486a56d0ad91e/packages/slate-react/src/components/editor.js#L181-L192

`setTimeout()` is unpredictable and if multiple `setTimeout()` is called (happen during multi-editor environment), you are likely see significant delay and cause performance issue.

At this point, I would like to note a few points:

- this is a regression, old version of slate was capable of large number of editors.
- this behaviour break the predictability of React model

Now I move on to the part where I explain why this also introduce a _race condition_, which I believe is the more serious of problem here.

Most of us will store the `Value`s somewhere and might manipulate it outside the component. For my use case, remote changes can arrive in real time.

If the remote changes come in the following order:

1. `Create an Editor at Location A`
2. `Insert Text in Editor of Location A`

Change 2 (Insert Text) will be overwritten by the schema change being scheduled by the `Editor.constructor()` if happen fast enough.

A rough pseudo code explaining the race condition:

- Receive `Create an Editor at Location A` change request
- Receive `Insert Text in Editor of Location A` change request
- Process `Create an Editor at Location A`
- Instantiate a `Value` object, bind it to `Location A` and save it to our store.
- Detect changes in store, React attempt to re-render.
- `Editor` at `Location A` got instantiated and queue `Schema change` change.
- `Editor` is mounted, queue flushed and `Schema change` change get scheduled.
- Process `Insert Text in Editor of Location A`
- Find `Value` object that is bind to `Location A` in store, insert text to it and save back to store.
- Detect changes in store, React attempt to re-render.
- Insert text get rendered by React.
- Scheduled `Schema Change` change finally arrive, `onChange` fired.
- We response to `onChange` by saving `Value` to store (controlled component)
- Detect changes in store, React attempt to re-render.
- Insert text goes missing when rendered by React.
- Because of immutability, the scheduled `Schema Change` change did not pick up the `Insert Text` change while it is being scheduled, thus losing the `Insert Text` change to race condition.

https://jsfiddle.net/lxcid/q91uydtz/

Here's a simple example on JSFiddle that replicate the bug, note that #1478 must be merged to be able to replicate the issue.

#### What's the expected behavior?

The correct behaviour should be no race condition. In the example, the insert operation should not be lost.

**Comment by ianstormtaylor** [comment]
Hey @lxcid thank you for writing this up so well. I believe this is fixed now in `0.42` and `0.19` with the new `Editor` controller updating its value synchronously, and flushing queued changes in `componentDidMount` without a `setTimeout` anymore. Thank you!
