### ISSUE TITLE
consider changing `kind` to `object`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1482]
This is a minor thing, but an annoyance with the current API.

The difference between `kind` and `type` is not clear, and easily leads to confusion. The "kind" is really just a property that's on all objects (not just blocks/inlines) that reflects what type of object it is, so you can easily differentiate between objects. I think it would be nice to follow Stripe's API's example and name this property `object` instead for clarity.

**Comment by CameronAckermanSEL** [comment]
All for it. In code review meetings we had difficulty explaining this difference. Thanks :)

**Comment by skogsmaskin** [comment]
Sounds good to me. I'm pretty into Slate, but I still get confused every now and then. To add to the confusion  we operate with a "type"  in our source data as well.
