### ISSUE TITLE
Undo deletion of list restores final list item as a paragraph 

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1485]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

After deleting a list and then undoing the change, the list is recreated in the editor, but the final list item is restored as a paragraph.

http://recordit.co/eUi7ix9PLW

#### What's the expected behavior?

When list is restored, all list items have the correct type

PS. Apologies if this is a duplicate, there seem to be some other flavors of this bug already reported.

**Comment by zGrav** [comment]
Sadly, I had this issue myself on copy/pasting lists and undoing.

My workaround of it was w/ a custom copy/paste plugin that handles lists/tables in a special way and so far it seems to work fine...

**Comment by CameronAckermanSEL** [comment]
Thanks for the tip :)

**Comment by rema7** [comment]
I've got another issue when you delete blocks and undo it, the last block got wrong blocks data structure.
It got it from the previous block in the document.

http://recordit.co/DgFrqgge98

**Comment by CameronAckermanSEL** [comment]
I've been looking at this one for a bit over the last couple of days. It's a pretty complicated one. 

It seems to be because when the mergeNode operation (that results from when the block after the deleted fragment gets merged with the block preceeding the deleted fragment) does not keep track any properties of the block after the deleted fragment. So when we go to undo that change, the inverse operation splitBlock will simply split the block into an identical one, and has no way of restoring the old properties.

I've played with having the mergeNode operation put the original block in the operation object, but still having some trouble getting splitNode to restore it properly. I'll keep beating on it.
