### ISSUE TITLE
bug: if all the text under an inline node selected, and new text is typed, the new text does not keep the format 

### ISSUE THREAD

**Issue by amitm02** [ianstormtaylor/slate#1494]
In slatejs playground, [http://slatejs.org/#/links](http://slatejs.org/#/links):
If you select all the text of the link ("hyperlinks"), and type the keyboard, the first letter is in right "link" format, but the following letters are in not.

![qkxcux2lhd](https://user-images.githubusercontent.com/1888927/34417371-cd081dd2-ec00-11e7-84e4-16a24101ca8f.gif)
[gif](http://g.recordit.co/qkxcUx2LHD.gif)

compared to underline & bold:
![gnfp53cftr](https://user-images.githubusercontent.com/1888927/34417403-f6d6b916-ec00-11e7-8362-a1e8d7e80357.gif)
[gif](http://g.recordit.co/GnFP53cfTr.gif)

compared to a regular editor (e.g Word
![yw7lbocfl8](https://user-images.githubusercontent.com/1888927/34417386-e56213ce-ec00-11e7-8abc-73697013736c.gif)
[gif](http://g.recordit.co/Yw7lbOCFL8.gif)

**Comment by ianstormtaylor** [comment]
Interestingly, both Medium and Dropbox Paper have the same failure as Slate currently. I'd be open to a pull request that fixes this by going the Google Docs route, where none of the text has a link when it is replaced. (Going the Microsoft Word route that maintains the link is going to be too complex.)

**Comment by amitm02** [comment]
I have a use case in which it is important to be able to replace a text under an inline node in the manner described above. Any suggestions on how to go about it?

**Comment by ianstormtaylor** [comment]
What's your use case? I'm not really sure. It would require investigation to figure out why the change happened, and whether it's possible to have the old behavior back in a cross-browser way.

**Comment by amitm02** [comment]
I want to build a custom “field” node with a fieldID attribute (E.g “personName” ). I want  it to have the following behavior. 
1. When the cursor is inside the field node, select all the text in the node. 
2. When typing the keyboard text, the pervious text in the field is replaced with what is typed. 
3 I can access the field content via the fieldID. E.g get the “personName” field content from the document. 

I’m not suf

**Comment by ianstormtaylor** [comment]
Is there a reason the `field` node needs to be inline? could it be a block instead?

**Comment by amitm02** [comment]
I want a paragraph to be able to contain multiple fields or have a field for just a "number". So it seemed to me that Inline is the right approach. But come to think about it, I have to admit i don't fully understand the difference between Block node and Inline node (apart from that an Inline node can not contain a Block node).

Will using a Block node solve the Issue?
What would be the thumb rule regarding to when choosing Inline over Block custom nodes?

p.s Apologies to hijacking the bug thread. Great project. Happy new year!

**Comment by ianstormtaylor** [comment]
If you want multiple fields to exist in an inline fashion (in terms of layout) than you'll need to use inline nodes I think, yup. If that wasn't a concern, then you could use blocks.

**Comment by amitm02** [comment]
Putting my use case aside, there is something fundamental i fail to understand.
I assume using Inline nodes for Bold or Underline is a reasonable choice (i know it is currently implemented as Marks). So one should be able to set a format at the cursor position and start typing at that set format. Shouldn't Inline nodes support it?

**Comment by ianstormtaylor** [comment]
Inlines for bold/underline currently isn't a reasonable choice I'd say. If you search issues I think there are a few discussions (recently even) about the difference between inlines/marks. But for pure formatting concerns, marks are the way to go. Inline nodes are about a specific chunk of text with semantic meaning that cannot be spliced/reordered without changing that meaning.

**Comment by zhujinxuan** [comment]
@ianstormtaylor @amitm02   I tried to use `change.collapseToStart({normalize:false})` in the `insertTextByKey`.  And find that the `onChange` will set the selection to the next text.

However, I cannot find the related normalization function in the code base

**Comment by zhujinxuan** [comment]
Demo for a bypass solution: https://zhujinxuan.github.io/slate-on-select/ 

https://github.com/zhujinxuan/slate-on-select
@amitm02  Hi, would you like a browser compat tests?  @ianstormtaylor  and I have discussed about the solution, but we are not sure whether the solution work consistently on all browsers. (I can only test on browsers run on Mac or Linux... I have no windows machine)

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
