### ISSUE TITLE
when I use slate in mobile env,once I input chinese words,the input will be canceled.

### ISSUE THREAD

**Issue by HellowVirgil** [ianstormtaylor/slate#1499]
#### What's the current behavior?

when I input chinese in mobile env,the words I input can not show.

#### What's the expected behavior?

how can I use Slate in mobile env?thx~

And this is the capture:

when I input the chinese and confirm，the words I input was cleared.

![image](https://edu-wenku.bdimg.com/v1/na/f38ed6027fe0ce8e6c3697690-1515122736458.gif)

**Comment by HellowVirgil** [comment]
I already add the gif.I think the performance may caused by onChange.

**Comment by sethyuan** [comment]
Same here. I tried the walkthrough on iPad (11.x) and encountered the same issue. IME opens normally, I typed some words, confirm the input and IME is closed automatically and nothing was entered.

**Comment by pizn** [comment]
The same question as https://github.com/ianstormtaylor/slate/issues/1584

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368.
