### ISSUE TITLE
`change.unwrapBlock` sometimes incorrectly modifies block selection

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1500]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

When `change.unwrapBlock` is called when there is an expanded selection on a block within a list, sometimes the selection will be modified by this operation, and subsequent operations will not apply to the original selection.

There's a specific case where this is a problem. If the user has highlighted a list item within a list and tries to change the list type for the selected list item, then we see the odd behavior below where the blocks preceding the original selection are selected after the `change.unwrapBlock` operation and then get wrapped in a list (so many words!!) 

Here's the gif to accompany my word heap :)

![](http://g.recordit.co/LzVU9xiPci.gif)

#### What's the expected behavior?

`change.unwrapBlock` should not modify the selection in this way.

**Comment by darkyshiny** [comment]
I've been messing with this quite a bit in a project that I am working on and will share what I have gathered so far.

As far as I have been able to tell during my testing this bug only occurs when doing a backwards selection on a single row in a list **that is not the last item in the list**. When triggered `change.unwrapBlock` will extend the selection all the way to the begging of the list in question.

![slate-unwrapblock-bug](https://user-images.githubusercontent.com/16773900/35323576-473d0516-00ee-11e8-9d97-79e12b50351d.gif)

A hacky workaround that anyone facing this can use until it is properly fixed is checking if the `selection.isBackward` and simply calling `change.flip()` before and after unwrapping/rewrapping to avoid having a backwards selection at the time of unwrapping the list.

I might take a crack at looking into a PR for this later this week if I find the time for it. 👍
