### ISSUE TITLE
Selecting with arrow keys and shift fails with links

### ISSUE THREAD

**Issue by rmckayfleming** [ianstormtaylor/slate#1502]
#### What's the current behavior?
I experienced this first in my own code and noticed that it happens on the slatejs homepage as well. Visit http://slatejs.org/#/links, beside the hyperlink delete the !, now hold shift and hit the arrow key left. Instead of selecting 's' it moves the cursor to the left of the s.

#### What's the expected behavior?
Arrow selection for inline nodes should work the same as for marks. Also, this doesn't happen if the link is not the last node on the line. If you add a space after the s and do the above it works properly.

**Comment by ianstormtaylor** [comment]
This is fixed in the latest version of Slate.
