### ISSUE TITLE
Changelog links don't work

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1507]
https://docs.slatejs.org/general/changelog

**Comment by ianstormtaylor** [comment]
@SamyPesse @Soreine any idea why this is happening? The links aren't relative in the Markdown file in Git, but when they get to GitBook they are becoming relative — https://github.com/ianstormtaylor/slate/blob/master/docs/general/changelog.md

**Comment by SamyPesse** [comment]
We are investigating the issue, since these pages are not part of your `SUMMARY.md`, it should be replaced by an absolute url to `https://github.com/ianstormtaylor/slate/blob/master/packages/slate-base64-serializer/Changelog.md`, etc
