### ISSUE TITLE
White space always in a line, can't Line Wrap

### ISSUE THREAD

**Issue by sunjingwu** [ianstormtaylor/slate#1516]
#### What's the current behavior?
The behavior is this：
![behavior](http://sunjingwu.oss-cn-shanghai.aliyuncs.com/others/GIF.gif)

My env:

Windows 10，（64 位）
Chrome  63.0.3239.132（正式版本） （64 位）
Slate  0.31.7

#### What's the expected behavior?

White space Can Line Wrap

**Comment by sunjingwu** [comment]
jsfiddle ::
[jsfiddle ](https://jsfiddle.net/fj9dvhom/1/)

**Comment by SmilinBrian** [comment]
This is exactly how Pages on Mac works. I'm guessing Microsoft Word works the same.

What is the rational for changing the behavior? I see matching mainstream word processors as desirable.

**Comment by sunjingwu** [comment]
Oh
