### ISSUE TITLE
I think master was recently broken with enter creating a double-enter on iOS 11 (possibly other versions as well)

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#1519]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

on an iPad if I hit enter on a line I get a double enter

#### What's the expected behavior?

Should insert a single paragraph, not two.

I was trying to submit my PR and couldn't for the life of me figure out why my code kept inserting a double ENTER. Turns out, after cloning the repo from scratch, that this bug is on master.

Anybody that accepted a PR recently, please check on iOS 11 iPad. Probably affects other devices as well.

**Comment by thesunny** [comment]
Here's a video showing the bug on iOS Simulator.

http://recordit.co/6nCQtGICoc

I'm hitting enter once and it is double-inserting. I'm also only hitting backspace once and it's double-deleting.

**Comment by thesunny** [comment]
I just confirmed that this bug appears on iOS 10 as well.

It does not happen on Chrome or Safari on OSX so is likely an iOS specific bug.

**Comment by ianstormtaylor** [comment]
@rgrove I think this might be due to the cleanup of #1475 — maybe your initial reaction to have individual `IS_IOS` guards was a good once because the `enter` (any maybe more?) one was needed after all?

**Comment by rgrove** [comment]
@ianstormtaylor Uh oh. I’ll take a look.

**Comment by rgrove** [comment]
@ianstormtaylor Fixed in #1520. Sorry about that!

**Comment by ianstormtaylor** [comment]
@rgrove no worries! Thanks for the quick fix.
