### ISSUE TITLE
Would you like to add flow type check in some files?

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1527]
#### Do you want to request a *feature* or report a *bug*?
feature;

#### What's the current behavior?
Some plugins are using flow to type check with the slate.  However, flow is not smart enough to intercept some types inside the slate. 

I am just wondering whether or not it is appreciated of submitting PRs of adding flow annotation for type checking in some files?

Thank you
Jinxuan Zhu

**Comment by ianstormtaylor** [comment]
Hey @zhujinxuan, good question. I don't want to add Flow to the codebase though. If we were to consider one of the type systems down the road it would be TypeScript, but even that I think should be punted for nearer to a 1.0 release.

I think plugins can do whatever they please on this front, but it doesn't need to impact the core codebase.
