### ISSUE TITLE
Plugin support for onMouseOver, onMouseOut etc.

### ISSUE THREAD

**Issue by majelbstoat** [ianstormtaylor/slate#1535]
#### Do you want to request a *feature* or report a *bug*?

Feature

#### What's the current behavior?

If a plugin wants to handle onMouseOver or onMouseOut events, it either needs to bind arguments in the render method, or store data in a data-attribute. The specific use case I'm trying to achieve is taking action based on mark data on mouse over.

```javascript
class Plugin {

  static onMouseOver(event) {
    console.log(event.target.getAttribute('data-foovalue')
  }

  static renderMark() {
    const fooValue = props.mark.data.get("foo");
    return (
      <span data-foovalue={fooValue} onMouseOver={Plugin.onMouseOver}>
        {props.children}
      </span>
    )
  }

}
```

#### What's the expected behavior?

It would be great if onMouseOver and onMouseOut were supported "naturally", such that we got an `event` _and_ a `change`, so we had access to value, document, fragment, or mark data. We wouldn't need a renderMark function then, and could do something like:

```javascript
class Plugin {

  static onMouseOver(event, change) {
    // vague-ish pseudo-code. could also handle this by addition
    // of a new `hover` range to the change object, similar to selection.
    const node = findNode(event.target, change.value)
    const marks = node.getMarksAtRange(rangeOfNode), 
    console.log(marks[0].data.get("foo"))
  }
}
```

I'm happy to put together an initial pass at this, if it's likely to be accepted in principle, and if I can be pointed in the right direction :)

**Comment by zhujinxuan** [comment]
Hi, I small question about that;

Suppose there is a following toolbar plugin that 
```
renderPortal => {
  <div>
  <Toolbar />
  <Editior />
</div>
}
```

Shall the plugin handle move out from `<Toolbar />?

**Comment by majelbstoat** [comment]
That's a good question. I guess I would expect the same semantics as onClick.

**Comment by AndreiRailean** [comment]
IMHO your proposal would introduce too much performance overhead for the browser. The editor would be firing onMouseOvers for anything and everything and all plugins would have to be called to see if they should handle the event... all the time

not sure what you mean by 
> needs to bind arguments in the render method

are you trying to avoid something like this? `onMouseOver={() => { console.log(fooValue) }`
or in your example it would be
```
  static renderMark() {
    const fooValue = props.mark.data.get("foo");
    const onMouseOver = () => { console.log(fooValue) }
    return (
      <span onMouseOver={onMouseOver}>
        {props.children}
      </span>
    )
  }
```

**Comment by majelbstoat** [comment]
> not sure what you mean by "needs to bind arguments in the render method"

I mean needing to either have a data-foovalue on the dom node, do your way, or do this:

```
class Plugin {
  static onMouseOver(fooValue, event) {
      console.log(fooValue)
    }

  static renderMark() {
    const fooValue = props.mark.data.get("foo");
    return (
      <span onMouseOver={Plugin.onMouseOver.bind(null, fooValue)}>
        {props.children}
      </span>
    )
  }
}
```

Neither of those are great, as they will create a new function on every re-render of the mark.

> The editor would be firing onMouseOvers for anything and everything and all plugins would have to be called to see if they should handle the event... all the time

That depends how the plugin event handlers are stored. If they were stored in a map by event type, it's O(n) over the total number of plugins that define a given handler. Something like: 

```
handlers: {
  onMouseOver: [PluginA.onClick],
  onClick: [PluginA.onClick, PluginB.onClick]
}

handleEvent(event) {
  handlers[event.type].forEach((handler) => handler(event))
}
```

If someone wants to add a couple dozen plugins that define onMouseOver, then sure, but a couple would be fine.

FWIW, Medium's codebase has a similar plugin architecture to Slate's and binds onMouseOvers in a bunch of places (used judiciously, of course). It would be great to have an actual assessment of the impact of browser performance before closing off the possibility.

**Comment by AndreiRailean** [comment]
I see, you're optimising for memory. Perhaps it's worth writing a proper component and letting react optimise for multiple instances of the same component

```jsx
const MySpecialMark = ({fooValue, children}) => {
  const onMouseOver() => consoleLog(fooValue)
  return (
      <span onMouseOver={onMouseOver}>
        {children}
      </span>
  )
}
```
and
```js
  ...
  static renderMark() {
    const fooValue = props.mark.data.get("foo");
    return <MySpecialMark fooValue={fooValue} />
  }
```
I guess it's similar to my other suggestion.
---
Your suggestion seems like a common pattern in Slate.js so it's quite easy to reason about. Serialisation rules work in the same way: loop over all rules, find one that can generate a node from content. Having convenient access to the `value`, `change` is important, but pure components don't need to know anything about it - just feed them callbacks.

Anyway, sounds like you already know how to implement it. 
Give it a go!

**Comment by AndreiRailean** [comment]
Also, devs should try to break everything down into tiny plugins. I hope that most of them implement `onMouseOver` to make the editor more interactive and not rely on toolbars alone.

**Comment by Kitefr** [comment]
Hello, 

I wanted to know the progress on this feature. Is it still going ?

**Comment by mmdonaldson** [comment]
Any updates on this?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
