### ISSUE TITLE
How to batch `validateNode` changes so they all run before `validateNode` is called again?

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1542]
I use `validateNode(node)` to do custom schema validations.

In my case, `validateNode` ensures `document.data.nextId` exists and is initialized to 1. It also ensures that each `block.data.id` exists.

When I ensure `block.data.id`, I set its value from `document.data.nextId` and increment `document.data.nextId`. I "enqueue" these two changes as part of one `validateNode` call.

```
return change => change
  .setNodeByKey(node.key, { data: { id: id } })
  .setNodeByKey(doc.key, { data: { nextId: nextId } })
```

However, after each of these sub-changes is called, `validateNode` is called. This is a problem, because the document state received by `validateNode` does not include all the pending changes that are already queued. The result is that `validateNod` re-discovers problems that have already been fixed with pending changes, so it then queues up further changes that are either duplicates or out of sync.

A solution is to have `validateNode` only be called after *all* the pending changes are run, instead of after *each* change is run.

Another solution could be introducing transactional semantics, like

 ```
change.transaction([
  change1 => {...}, 
  change2 => {...},
])
```

**Comment by zhujinxuan** [comment]
use `change.setNodeByKey(..., {normalize: false})`

**Comment by tashburn** [comment]
@zhujinxuan Thanks for the idea, but it doesn't work for me --
```
return change => change
  .setNodeByKey(node.key, { normalize: false, data: { id: id } })
  .setNodeByKey(doc.key, { normalize: false, data: { nextId: nextId } })
```
Even if it worked, it's awkward. I'd need to determine which change is the last one in a batch, *before* creating the changes. Or, I'd have to make sure *all* of my document changes are in one batch.

**Comment by CameronAckermanSEL** [comment]
@tashburn the snippet should be

```
return change => change
  .setNodeByKey(node.key, { data: { id: id }}, { normalize: false })
  .setNodeByKey(doc.key, { data: { nextId: nextId }}, { normalize: false })
```

**Comment by tashburn** [comment]
@CameronAckermanSEL Thanks for the correction and elaboration. It *does* work.

In fact, after a batch of changes on the `Document` where all changes have `{normalize:false}` , `validateNode` is called on `Document`. This is the behavior I want.

I didn't find this parameter in the documentation. Is it there somewhere?

Does every `Change` method have this parameter as an undocumented last parameter?

**Comment by CameronAckermanSEL** [comment]
It is deliberately undocumented because it's unsafe and may create unintentional schema violations in your document state. The flag is available on all change operations. Just use carefully and reinforce with tests.

**Comment by tashburn** [comment]
Ok, thanks.
