### ISSUE TITLE
Fail to "yarn run bootstrap", lerna not found

### ISSUE THREAD

**Issue by trompx** [ianstormtaylor/slate#1546]
#### BUG

Hello,

I try to run the example in an Ubuntu VM, running inside a Virtualbox Vagrant VM on Windows 8.1.
I managed to make the `yarn install` works with the `--no-bin-links` tag.
But when I run `yarn run bootstrap`, I get the following:

```
sh: lerna: not found
error An unexpected error occurred: "Command failed.\nExit code: 127\nCommand: sh\nArguments: -c lerna bootstrap && yarn run build\nDirectory: /var/www/myproject/editor/slate\nOutput:\n".
```
while the lerna has been installed and is present in the node_modules folder.
I tried to upgrade to lerna 2.8.0 but the issue persists.

**Error.log output:**
```
Arguments: 
  /usr/bin/node /usr/bin/yarn run bootstrap

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.4.0

Node version: 
  6.10.3

Platform: 
  linux x64

Trace: 
  Error: Command failed.
  Exit code: 127
  Command: sh
  Arguments: -c lerna bootstrap && yarn run build
  Directory: /var/www/myproject/editor/slate
  Output:
  
      at ProcessTermError.Error (native)
      at ProcessTermError.MessageError (/usr/lib/node_modules/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/usr/lib/node_modules/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:30822:17)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:886:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by schneidmaster** [comment]
Hi there! Installing with `--no-bin-links` is the cause of the second problem -- the [bootstrap](https://github.com/ianstormtaylor/slate/blob/master/package.json#L68) command expects `lerna` to be available in the bin. If you need to use `--no-bin-links` due to VirtualBox, you might consider manually running the commands using the full path to lerna.
