### ISSUE TITLE
Feature request - Change method: setTextByKey

### ISSUE THREAD

**Issue by bergalv** [ianstormtaylor/slate#1547]
A Feature request

There is a missing and needed Change method: "setTextByKey"
Currently there is no straight way to replace text in a Node.
I can append text to Node (insertTextByKey) or remove text from Node (removeTextByKey). However, for replacing the text, one can not merely remove the text and re-insert it. This is because removing the text of the Node will cause for its deletion (empty Nodes gets deleted automatically).

**Comment by zhujinxuan** [comment]
How about `deleteAtRange(Range.create().moveToRangeOf(text.key), {normalize: false})).insertTextAtRange(Range.create().collapseToStartOf(text.key), "some texts")`

**Comment by zGrav** [comment]
Hey @bergalv , I believe I built what you wanted 👍

**Comment by ianstormtaylor** [comment]
I'd be open to a `replaceTextByKey` change method if someone wants to add it, it should just call into the existing `removeTextByKey` and then `addTextByKey`, but it does seem like a nice convenience.

**Comment by benjycui** [comment]
> How about deleteAtRange(Range.create().moveToRangeOf(text.key), {normalize: false})).insertTextAtRange(Range.create().collapseToStartOf(text.key), "some texts")

The problem is, when users try to undo, they need to undo twice to revert back to previous text.

**Comment by zhujinxuan** [comment]
@benjycui Yes, I forgot that....  It should be `removeTextByKey(....).insertTextByKey(...) `
but I think it would be much better to have an `replaceTextByKey`. I will submit a PR about that.

**Comment by ianstormtaylor** [comment]
Actually, I think having both `replaceTextByKey` (which takes a `offset, length, text`) and `setTextByKey` (which takes just a `key`) would both be useful. Open to PR's that implement either of them.

**Comment by zhujinxuan** [comment]
@ianstormtaylor How about another thing:
for insertTextAtRange and insertText, if range is expanded but startKey and endKey is the same, use replaceTextByKey and do not use snapshot and deleteAtRange

**Comment by zhujinxuan** [comment]
@ianstormtaylor

About marks of setTextByKey, there are two choices.  Which one would you prefer?
   1. `setTextByKey(key: string , text: string|Text) `
   2. `setTextByKey(key: string, text: string, marks?:  Set<Marks>)`

Another question is shall we inherit `activeMarks` in repalceTextByKey and insertTextByKey?

**Comment by ianstormtaylor** [comment]
For `setTextByKey`, let's go with the same arguments as `insertText` (except without the `offset`).

And for `replaceTextByKey`, I think it would be good to inherit the active marks the same way as if the replacement happened with `remove` then `insert`.

**Comment by zhujinxuan** [comment]
Done in https://github.com/ianstormtaylor/slate/pull/1745
