### ISSUE TITLE
Enter on selected link causes error

### ISSUE THREAD

**Issue by svenadlung** [ianstormtaylor/slate#1562]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
Selecting a link and pressing Enter results in an error. 
http://slatejs.org/#/links

![jan -26-2018 15-46-02](https://user-images.githubusercontent.com/11420688/35444850-15b34cd0-02b0-11e8-877d-682f02f9301e.gif)

![slate](https://user-images.githubusercontent.com/11420688/35444732-bb8f6626-02af-11e8-9c2d-9353720fb659.png)

#### What's the expected behavior?
It should behave the same like regular text (split).

**Comment by benjycui** [comment]
See: https://github.com/ianstormtaylor/slate/pull/1739
