### ISSUE TITLE
The Docs Site Is Broken 

### ISSUE THREAD

**Issue by jessep** [ianstormtaylor/slate#1565]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
All links to the docs site are broken
![screen recording 2018-01-26 at 10 36 am](https://user-images.githubusercontent.com/37623/35454949-f416bd62-0284-11e8-8002-0b948ac6dbe1.gif)

I'm on Chrome Version 63.0.3239.132 (Official Build) (64-bit), on a Mac OS 10.13.1

#### What's the expected behavior?
Docs site should load helpful docs :)

**Comment by schneidmaster** [comment]
Hey @jessep -- I'm able to load the docs site without issue. Are you perhaps having local network/DNS resolution issues?

**Comment by jessep** [comment]
Seems likely :) Tried a different network and it still didn't work, but if it's working for others then it must be somewhere between me and the internet.

**Comment by jessep** [comment]
Okay, yeah, was able to load it by tethering to my phone. Def a network issue.
