### ISSUE TITLE
[BUG] Line breaks not working

### ISSUE THREAD

**Issue by lucadegasperi** [ianstormtaylor/slate#1572]
#### Do you want to request a *feature* or report a *bug*?

BUG

#### What's the current behavior?

```"slate": "0.32.2",
"slate-html-serializer": "0.5.2",
"slate-react": "0.11.2",
"slate-soft-break": "0.6.0",
````

I've updated to the latest slate version and soft breaks no longer work.
Somehow when serializing the soft breaks they do get serialized indeed, but when deserializing they disappear (from the slate editor only) when serializing again, they do indeed appear in the html.

Here's the serialization/deserialization function I'm using. Is this wrong?

```{
        deserialize(el) {
            if (el.tagName.toLowerCase() !== 'br') return;

            return {
                object: 'text',
                text: '\n',
            };
        },
        serialize(object, children) {
            if (object.object !== 'text') return;
            if (children !== '\n') return;

            return (
                <br/>
            );
        }
    },
```

#### What's the expected behavior?

Line breaks should be deserialized correctly and rendered in the slate editor but they are not.

**Comment by CameronAckermanSEL** [comment]
This is possibly related to https://github.com/ianstormtaylor/slate/pull/1503

**Comment by lucadegasperi** [comment]
I'm closing this because it seems like <br> serialization/deserialization is now handled by the html serializer by default. I've removed my custom serializer and things do work again.
Sorry I've bothered you all!
