### ISSUE TITLE
Cannot input when I use IME in IOS

### ISSUE THREAD

**Issue by harveyprince** [ianstormtaylor/slate#1584]
It looks like I cannot use IME to input when I set UserAgent to IOS 11 (both real IOS device and mac safari).
![-2](https://user-images.githubusercontent.com/5565183/35669330-b1865774-076f-11e8-82d8-6b9ae5f7dd11.gif)
Any idea to fix this?

**Comment by pizn** [comment]
After CompositionEnd, the beforeInput return, so...user input IME got nothing...
https://github.com/ianstormtaylor/slate/blob/fc264841b6512f17c3e987b3c90a7d934e106e9b/packages/slate-react/src/plugins/before.js#L54

**Comment by hkbarton** [comment]
any update on this?

**Comment by HereSinceres** [comment]
@pizn But this does not solve the problem,it is still a problem under IOS（no test android）

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
