### ISSUE TITLE
Walkthrough - metaKey example fails on Windows

### ISSUE THREAD

**Issue by wasabigeek** [ianstormtaylor/slate#1590]
Referring to: https://docs.slatejs.org/walkthroughs/applying-custom-formatting, the `meta+B` shortcut doesn't work, although `meta+backtick` does. I believe this is because Windows already maps that [particular shortcut](https://support.microsoft.com/en-sg/help/12445/windows-keyboard-shortcuts). 

Suggest to reuse the CTRL key example from the previous!

**Comment by schneidmaster** [comment]
@wasabigeek The help please label generally just means that a PR would be welcomed to address the issue. In this case I think a PR changing the example to use `ctrl` instead of `meta` (assuming that works cross-platform) would be great 👍

**Comment by schneidmaster** [comment]
Fixed in #1601
