### ISSUE TITLE
Feature Request: Support for Angular 5

### ISSUE THREAD

**Issue by shyamal890** [ianstormtaylor/slate#1600]
Can slate work with Angular?

**Comment by schneidmaster** [comment]
Hi there! Slate intentionally keeps a very lean core in the `slate` package itself, with `slate-react` containing the logic to render Slate as a React component. It would likely be possible to develop a plugin analogous to `slate-react` to render a Slate editor in Angular. I believe there are also plugins that let you render React components within Angular that you could try with `slate-react`. However, I don't think any sort of official support for Angular is in the cards, at least in the near future.
