### ISSUE TITLE
Firefox: selection.collapse() throws exception when selection leaves contentEditable=false block

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1609]
#### Do you want to request a *feature* or report a *bug*?

Bug. 

#### What's the current behavior?

Unfortunately, I am unable to create a fiddle that reproduces the defect because it is hard to reproduce. 

I am experiencing a defect described in the final post of this PR here: https://github.com/ianstormtaylor/slate/pull/1386

Basically, in Firefox an `NS_ERROR_FAILURE` is thrown when `selection.collapse()` is called on an element with `contentEditable=false`.  Specifically, the line here is what throws: https://github.com/illesg/slate/blob/4353fce7f6212c215f5232214fb6c5feab32df41/packages/slate-react/src/components/content.js#L206

We have `contentEditable=false` on our table elements (reenabled on our tbody elements) to disable the firefox resizer controls. Also, `contentEditable=false` gets thrown on void nodes, so this problem has been frequently hitting our users.

I can toggle off the problem if `native.collapse(...); native.extend(...)` calls are reverted back to `native.setBaseAndExtent(...)`. We can make the compatibility fix for IE continue to work if we check for `native.setBaseAndExtent` where we check for `native.extend` and still achieve the desired effect :) 

https://developer.mozilla.org/en-US/docs/Web/API/Selection/setBaseAndExtent

I would love to submit a PR but we'd like to get some feedback first. We couldn't tell if there was as specific reason that the `native.setBaseAndExtent(...)` calls were replaced with the separate ones, aside from the IE compatibility fixes which can't use the `native.expand()` call anyway. 

#### What's the expected behavior?

The expected behavior is that no exception happens.

**Comment by CameronAckermanSEL** [comment]
Hey @illesg, sorry to drag you into this but do you have any insight?

**Comment by illesg** [comment]
Hey @CameronAckermanSEL, no problem :)
The setBaseAndExtent feature check sounds great if it solves the FF problem. 
The last post you mentioned (#1386) sounds like some kinda focus issue, the first thing came to my mind is this part of the code: [https://github.com/illesg/slate/blob/4353fce7f6212c215f5232214fb6c5feab32df41/packages/slate-react/src/components/content.js#L218-L223](https://github.com/illesg/slate/blob/4353fce7f6212c215f5232214fb6c5feab32df41/packages/slate-react/src/components/content.js#L218-L223) 
some setTimeout stuff with a focus call, i'm not sure if it has anything to do with these NS_ERROR exceptions, but with the setTimeout it can cause some weird issues

**Comment by tobiasandersen** [comment]
I had the same problem @CameronAckermanSEL, and made https://github.com/ianstormtaylor/slate/pull/1603 to work around it. Using `setBaseAndExtent` gave the same result as my PR. Please give it a try!

**Comment by CameronAckermanSEL** [comment]
Hey @tobiasandersen , it looks like the defect you've encountered is similar, except hat this defect involves an exception originating from `selection.collapse`, so #1603 does not alleviate the problem at all.

I think we need to change it to `setBaseAndExtant` but we should make sure the error you're experiencing is also resolved. By chance is there a simple set of steps for reproducing your issue?

**Comment by tobiasandersen** [comment]
So the `collapse()` actually throws for you when it fails at setting a collapsed selection? For me it fails silently. Not sure if it's a Chrome thing, or if I'm doing things differently. 

I _think_ the issue I'm seeing occurs when I try to give focus to a void node, when the focus is currently inside a `contentEditable="true"` element, that itself is inside that void node (hope that makes sense). 

`setBaseAndExtent` didn't really help in my case. It had the same behavior as `collapse` in that it just failed silently (so it kind of helped since it didn't throw).

**Comment by CameronAckermanSEL** [comment]
Yep, we have a very similar error condition.

For our tables, we have a `contentEditable="false"` on the <table> and a `contentEditable="true"` on the <tbody> so that the resizer controls in firefox are disabled (there are other grosser ways to achive this but this works best for us). The best way to trigger this defect is then to click inside any cell, then click somewhere out of the table.

But yeah the exception only throws in firefox, so this is very specific to that ecosystem.

**Comment by CameronAckermanSEL** [comment]
fixed by @tobiasandersen in #1603. Thank you so much :)

**Comment by lxcid** [comment]
Amazing fix @tobiasandersen! Thank you so much!
