### ISSUE TITLE
[Discussion] Asynchronously set cache of some expected nodes?

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1615]
#### Do you want to request a _feature_ or report a _bug_?

feature;

#### What's the expected behavior?

Think about `getAncestors(key)` that
```
getAncestors(key) {
  const childAncestors = this.nodes.find(.....);
  const foundChild = childAncestors.first();
  new Promise(() => {
     this.nodes.findLast( n=> {
        if (n === foundChild) {
             return true
        }
        n.__cache.getDescendant[key] = null;
         return false
     })
  })
  new Promise(() => {
    this.nodes.find( n=> {
        if (n === foundChild) return true;
        childAncestors.forEach(c => n.__cache.getDescendant[c.key] = null)
    })
  })
  return childAncestors.unshift(this);
}
```

Perhaps, the updated cache can speed up some operations.

**Comment by ianstormtaylor** [comment]
@zhujinxuan can you explain what you're proposing more?

**Comment by zhujinxuan** [comment]
I am thinking about this: 
for `getAncestors`, suppose we run `document.getAncestors('_cursor_')` on 
```
<p key=1> cat</p>
<quote><cursor/>cat</quote>
<p key=2> another cat</p> 
```
We will have `getAncestors('_cursor_')` cached result in `<p key = 1>` and `<quote>`; but in `<p key=2>` the cache is not set.

If we expect that keys are not duplicated in the document, I think we can expect a cache result of `<p key===2>.getAncestors('_cursor_') === null`.  Therefore, I am thinking about an asynchronous approach to update the cache.

Because most node method calls the `getAncestors` indirectly, I think we only need to implement this feature on `getAncestors` method.

**Comment by zhujinxuan** [comment]
The second promise is to speed up `getAncestors` of other nodes in the ancestors of `child`.  Then we can do the following code in a perhaps faster way:
```
const startBlock = document.getClosestBlock(startKey) 
const pathToBlock = document.getPath(startBlock)
```

**Comment by zhujinxuan** [comment]
The feature is tried in https://github.com/ianstormtaylor/slate/pull/1618
