### ISSUE TITLE
Exception in deserializeNode from slate-base64-serializer

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1616]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?
When `slate-base64-serializer.deserializeNode` is called, an exception is thrown.

This is reproducible in the `rich-text` example when the user tries to paste into the rich-text example, they now get this error: 

![image](https://user-images.githubusercontent.com/14242948/35934126-7accfd1a-0bf1-11e8-8b94-a80f31b367de.png)

Looks like the require call isn't recognized anymore.

https://github.com/ianstormtaylor/slate/blob/de4c9e478af601a63633f080506f98f997b4e92f/packages/slate-base64-serializer/src/index.js#L51

#### What's the expected behavior?
No exception

**Comment by ianstormtaylor** [comment]
Fixed in the latest release, thank @CameronAckermanSEL!

**Comment by CameronAckermanSEL** [comment]
@ianstormtaylor thanks for the quick turnaround on this, really appreciate it
