### ISSUE TITLE
cmd+shift+backspace in nested block errors out

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1617]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

If you're inside a list item (or probably any nested block situation) and you press <kbd>cmd+shift+backspace</kbd> to delete to the start of the line, and then start typing you'll get an error that kills the editor.

![kapture 2018-02-07 at 12 00 20](https://user-images.githubusercontent.com/311752/35938628-86247398-0bfe-11e8-8d3f-ce49ce66908b.gif)

#### What's the expected behavior?

No error.

**Comment by thetutlage** [comment]
Have similar issue, but in my case, only last character is deleted. I have no custom code handling Backspace

![delete-selected-text](https://user-images.githubusercontent.com/1706381/36797454-00d6f612-1cce-11e8-8834-4f060c5807c4.gif)
