### ISSUE TITLE
cmd+backspace deletes the entire block, not just the current line

### ISSUE THREAD

**Issue by steobrien** [ianstormtaylor/slate#1623]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Here's a gif of the problem in our Slate editor, compared with a native mac app like textedit. Command and backspace currently deletes the entire paragraph/block. Although the gif shows our use case, this is easily reproducible on the examples at http://slatejs.org/.

![image](https://user-images.githubusercontent.com/83981/35825396-b1cee6c6-0a83-11e8-8926-73b056980dbe.gif)

#### What's the expected behavior?

Only the current line should be deleted.

Note: cmd+shift creates the correct selection, so one way of phrasing the expected behavior is "it should do what cmd+shift, followed by backspace, does today".

**Comment by ianstormtaylor** [comment]
@steobrien this is a tricky one. The reason we do until the start of the block is because I think it's hard (or impossible, not sure?) to determine where lines start/end and how that converts back into which characters to erase.

I'm open to ideas here for how to achieve it!

**Comment by steobrien** [comment]
Got it. My first thought was to try and copy the cmd+shift implementation, as that leads to the correct selection of just the current line.

Or perhaps Slate defers to the browser for that?

**Comment by zhujinxuan** [comment]
Hi, I published a package on npm with name `slate-delete-one-line` to fix the problem.

Can you have a try?

```
import LineDelete from 'slate-delete-one-line'
const plugin = LineDelete()
```

**Comment by steobrien** [comment]
Hey @zhujinxuan, I've taken this for a spin and it seems to work great!

**Comment by ianstormtaylor** [comment]
Very cool @zhujinxuan! If you wanted to PR that, I'd love to be able to have that behavior in core. I didn't realize it was even possible 😄

**Comment by zhujinxuan** [comment]
@steobrien Great.  The package address is https://github.com/zhujinxuan/slate-sensible
I will finish the document this weekend.

**Comment by zhujinxuan** [comment]
@ianstormtaylor I'd like to submit the PR.  But the solution depends on get rect bound of range.  It seems react-native does not support DOMRange.getBoundingClient?  Is there a polyfill way to get Rect for Android and iOS?

**Comment by ianstormtaylor** [comment]
@zhujinxuan I’m not sure. Although I think we already do tons of stuff that’s not react native compatible?

**Comment by zhujinxuan** [comment]
@ianstormtaylor It becomes much easier if we do not need to consider react-native.
I will submit a PR next weekend

**Comment by steobrien** [comment]
Hey @zhujinxuan, `slate-delete-one-line` is working pretty nicely for us, but I’m wondering if you’re still planning to add this to core? I posted a [bounty](https://www.bountysource.com/issues/54819156-cmd-backspace-deletes-the-entire-block-not-just-the-current-line) a while back in case that helps!

**Comment by zhujinxuan** [comment]
@steobrien Sorry.  I am not planning to add it to core at this moment, because these codes cannot be tested in slate-react currently.  I think I will add it to slate-core after I get slate-react tested with Chrome headless.

**Comment by ianstormtaylor** [comment]
This should now be easier to do, by overriding the `delete_forward/delete_backward` commands only when the `unit: 'line'` for DOM behaviors. If someone wants to add this to the `withReact` plugin that would be awesome!

**Comment by austin94** [comment]
👋 Hi all. I've linked #3364 which addresses this issue.
