### ISSUE TITLE
Newlines aren't preserved when copying

### ISSUE THREAD

**Issue by tobiasandersen** [ianstormtaylor/slate#1635]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
If I copy text from within the editor, all empty blocks are stripped away. So if I write a paragraph, press enter a few times, then write a new paragraph, ending up with e.g:
```
A line of text in a paragraph.


A line of text in a paragraph.
```

And now copy all that, my `plain/text` clipboard will be only:
```
A line of text in a paragraph.
A line of text in a paragraph.
```

Note that it's only for the `plain/text` clipboard, so pasting inside the slate editor works fine.

To reproduce, copy the content in [this fiddle](https://jsfiddle.net/832672pe/1/), and paste somewhere outside of slate. 

#### What's the expected behavior?
Newlines should be preserved when copying.

**Comment by tobiasandersen** [comment]
We didn't have this problem before (haven't been able to pinpoint exactly when it started to occur, but it worked a few months ago). I can get it to work if I remove [this line in `cloneFragment`](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/clone-fragment.js#L68):

```
zws.forEach(zw => zw.parentNode.removeChild(zw))
```

But i suspect it's useful for other stuff?

**Comment by ianstormtaylor** [comment]
@tobiasandersen sounds like we need to be able to differentiate between zero-width nodes that are there for cross-browser fixing, and those that are there for keeping empty blocks from collapsing? And then instead of removing them all, some of them should be replaced with normal spaces?

**Comment by tobiasandersen** [comment]
Indeed! There's no COMPAT comment above this line though (and no real explanation on what it's for). I can see why it would be useful to do this for void nodes, but not really for anything else. Am I missing something? Do you remember why it was added in the first place? It seems it was added before [this](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/leaf.js#L123-L126):
```
// COMPAT: If the text is empty, it's because it's on the edge of an inline
// void node, so we render a zero-width space so that the selection can be
// inserted next to it still.
if (text == '') return <span data-slate-zero-width>{'\u200B'}</span>
```

**Comment by ianstormtaylor** [comment]
I think we use zero-width spaces in three(?) places:

1. Inside void node's as spacers to catch the cursor.
2. Inside empty text nodes next to inline nodes, to catch the cursor.
3. Inside empty text+block nodes to prevent the blocks from collapsing.

But this might be outdated/wrong.

I think (3) was introduced recently-ish, so might be the cause of the issue. I think we used to use a `\n` character instead? So if those are getting removed now that could do it? Not sure.

**Comment by tobiasandersen** [comment]
Okay looked into it a bit more. I think the problem was introduced with https://github.com/ianstormtaylor/slate/pull/1353, since this was removed from leaf nodes:
```
if (text == '' && parent.object == 'block' && parent.text == '') {
  return <span data-slate-empty-block>{'\n'}</span>
}
```
I'm tempted to just add it back, but @blakeembrey said:

> I killed the data-slate-empty-block span because it made things more complicated

Not sure what that actually means, but I assume it's about IMEs. I have no experience around those, so it's hard for me to tell what consequences it'll have.

**Comment by blakeembrey** [comment]
Sorry about this. I have an alternative PR and thought I had tested that use-case, but it was more complex so I went a little simpler. I'll test and submit the alternative now which kept the new lines in the text.

**Comment by blakeembrey** [comment]
Took a lot longer than expected to fix but I described why you need to keep the "zero width space" in the linked PR. However, we can swap it out at copy and paste time by keeping it identified.

**Comment by tobiasandersen** [comment]
Looking great, thanks @blakeembrey! (I'll comment some more on the PR instead)
