### ISSUE TITLE
Cannot delete the whole document content when the document starts with a void block

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1639]
#### Do you want to request a _feature_ or report a _bug_?

bug
#### What's the current behavior?

Select all and hit a-z in the following gif:
![](http://g.recordit.co/vVfdrBEfnu.gif)

I also tried backspace and backspace is not working.

**Comment by benjycui** [comment]
Slate's void node will be render as `contentEditable=false`, which will affect behavior of browser's `window.getSelection`.

You can try to debug in `onSelect` of Slate's after plugin, and then `mod+a`, you will see what I mean.

**Comment by benjycui** [comment]
https://github.com/ianstormtaylor/slate/pull/1734 will fix this issue.
