### ISSUE TITLE
[bug] onDrop of a fragment renders a wrong type by the end of paragraph

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1640]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?
See below, when dragging a fragment on another paragraph, the end of paragraph becomes a block.
![](http://g.recordit.co/YvOpYCZX15.gif)

#### What's the expected behavior?
Fixed by #1553 
See as below
![](http://g.recordit.co/WHsFnTsdKz.gif)

**Comment by zhujinxuan** [comment]
The reason is there is a empty quote block by triple selection is copy/paste.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
