### ISSUE TITLE
Node.removeTextByKey() bug?

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1641]
A call to `Change.removeTextByKey(key, offset, length)` throws this error:

```
Uncaught TypeError: node.getLeaves is not a function
```

I believe my use of `removeTextByKey` is correct.

I don't see a `Node.getLeaves()` function in the documentation either.

**Comment by zhujinxuan** [comment]
are you sure document.getNode(key) renders a Text, not a Node?

**Comment by tashburn** [comment]
Ah! I think that's the problem, thanks.
