### ISSUE TITLE
Trying to overwrite multiple selected lines when first line is empty 

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1646]
This issue appears to affect all examples as well as my implementation in my app.

http://recordit.co/rKPdP1PEE4

Error is:
`Uncaught TypeError: Cannot read property 'marks' of undefined`

Reproducible in Chrome and Firefox. Slate version 0.32.4 affected.

**Comment by Slapbox** [comment]
The only thing that can overwrite the selection as shown is pressing `Enter`

No characters can overwrite the selection.

**Comment by Slapbox** [comment]
Not present in Slate `0.32.0`, but is present in `0.32.2`

I'm guessing related to this change: https://github.com/ianstormtaylor/slate/commit/4e8dd7405a5134a79dbd2a23ccdaef77a6745579#diff-51457ab8a40ed0f3535aa76b3188685b

**Comment by czechdave** [comment]
This seems fixed in latest master https://github.com/ianstormtaylor/slate/blob/f7546d3c7ce8578ea98cf0c16f5d89c4fc9f37b7/packages/slate/src/models/node.js#L1112-L1114
