### ISSUE TITLE
Updating from 0.32.2 to 0.32.3/0.32.4 causes 100x slowdown in `Value.fromJSON()` call.

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#1650]
When I run my project on slate `0.32.2`, `Value.fromJSON()` call takes about ~100ms.
When I run my project on slate `0.32.3` or `0.32.4`, `Value.fromJSON()` call takes about ~10000ms.

From the git history it's really hard to tell what exactly changed to locate what caused the slowdown:
https://github.com/ianstormtaylor/slate/compare/slate@0.32.2...slate@0.32.3
If anyone has any ideas on where to look I'm happy to run more tests and identify what's the exact cause of this major performance hit.

**Comment by zhujinxuan** [comment]
Interesting.  Do you have `{schema: schema}` in running `Value.fromJSON()`?

**Comment by czechdave** [comment]
I do not. I'm including schema through `<Editor schema={schema} />`.

My calls are: `Value.fromJSON({ document })`

**Comment by julienp** [comment]
I'm observing similar issues with large documents. It would be interesting to know the memory usage you see during validation.

https://github.com/ianstormtaylor/slate/commit/b1e5330ad5e2862d3e870ab718b2d01f6225f35a changed how normalization works, resulting in calls to refindNode for all the nodes of the document, which in turn calls getDescendants. This method is memoized and thus causes a huge amount of memory being used if it's called for every node of the document.

See also #1402 

I'm not sure yet what the best solution is, but arguably it doesn't make much sense to memoize function calls during full document normalization, as it causes large memory usage for little gain.

**Comment by czechdave** [comment]
@julienp running performance inside Chrome DevTools shows the very same linear memory usage rise as shown in [#1402](https://github.com/ianstormtaylor/slate/issues/1402)

A document with some ~200 top level nodes takes over 10 seconds to consume and uses upwards of 600MB of memory 😞

**Comment by DamareYoh** [comment]
@czechdave the purpose of that change was to fix a major defect where normalization would be run against blocks that were no longer in the actual `change.value` object or had outdated state. The tests that could have been added were effectively normalizations of very deep structures, but otherwise regression tests were probably sufficient.

**Comment by DamareYoh** [comment]
https://github.com/ianstormtaylor/slate/issues/1528

**Comment by czechdave** [comment]
@DamareYoh thank you for shedding some light on this! Your fix is definitely very much valid though we might have to look into how to make it more performant. I’ll look into creating a sample document structure or a test case to reproduce this issue so we can look into fixing this.

**Comment by czechdave** [comment]
@DamareYoh @julienp Here's a benchmark test that surfaces this issue.
When run on slate@0.32.2 the benchmark produces results as usual.
When run on slate@0.32.3 I get:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

```js
/* eslint-disable react/jsx-key */

import { Value } from '../..'

export default function(json) {
  Value.fromJSON(json)
}

export const input = {
  document: {
    nodes: Array.from(Array(100)).map(() => ({
      type: 'list',
      object: 'block',
      isVoid: false,
      data: {},
      nodes: Array.from(Array(10)).map(() => ({
        type: 'list-item',
        object: 'block',
        isVoid: false,
        data: {},
        nodes: [
          {
            leaves: [
              {
                object: 'leaf',
                marks: [],
                text: '',
              },
            ],
            object: 'text',
          },
          {
            type: 'link',
            object: 'inline',
            isVoid: false,
            data: {
              id: 1,
            },
            nodes: [
              {
                leaves: [
                  {
                    object: 'leaf',
                    marks: [],
                    text: 'Some text for a link',
                  },
                ],
                object: 'text',
              },
            ],
          },
          {
            leaves: [
              {
                object: 'leaf',
                marks: [],
                text: '',
              },
            ],
            object: 'text',
          },
        ],
      })),
    })),
  },
}
```

**Comment by julienp** [comment]
@czechdave #1661 seems to fix this for me (using a build of slate 0.32.5 + that change)

**Comment by czechdave** [comment]
I can confirm that the benchmark posted above works on `0.33.0` with the PR merged [#1661](https://github.com/ianstormtaylor/slate/pull/1661)

**Comment by Soreine** [comment]
The mentionned PR was merged. Is the performance issue here resolved?

**Comment by czechdave** [comment]
Yes
