### ISSUE TITLE
[Feature] Do not allow '\n' in inline nodes

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1651]
#### Do you want to request a _feature_ or report a _bug_?
feature

#### What's the current behavior?

By `insertText('\n')`, we can have `\n` in the inline nodes with the plugin soft-break;  However, I think allowing `\n` in the inline node makes no sense.  

Do you think it is good to have a validateNode in slate-core to splitInline and unwrap `\n` as a text node? (I can submit PR if you think it is good)

**Comment by bryanph** [comment]
This can be done in a plugin, checking for a new line and transforming data structure accordingly.
