### ISSUE TITLE
How can I have the cursor in an empty Editor be pre-marked?

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1652]
When my users click a button to change the current block type to a "block-quote", I want their cursor to be in the new block-quote and marked `italic`. The user can click a toolbar button to  un-italicize it if they want.

I've tried `change.setBlock(json)` and passed the JSON for a text node with the italic mark. Doesn't work. The mark gets removed by Slate.

I've tried `change.setBlock('block-quote').addMark('italic')`. Doesn't work either. The user-entered text is not italic.

How can I do this?

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
