### ISSUE TITLE
Wrong behavior when changing block type with a hanging selection.

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#1655]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Hanging selection causes the following block to incorrectly change type.

#### What's the expected behavior?
Only selected block changes type.

![hanging selection block type](https://user-images.githubusercontent.com/8127927/36450719-ae4483d2-1643-11e8-9bc1-de9148b04bd2.gif)

**Comment by CameronAckermanSEL** [comment]
I think we just had a PR that fixed this. Are you on latest? (i think from other conversations this isnt the case)

**Comment by czechdave** [comment]
Unfortunately I'm locked down to `0.32.2` until [#1650](https://github.com/ianstormtaylor/slate/issues/1650) is fixed.

Feel free to close if this has already been fixed.

**Comment by RickyRoller** [comment]
This seems to be fixed on latest with the bold mark, but not with making a list. See gif.

![2018-06-05 10 07 50](https://user-images.githubusercontent.com/7373982/40991338-5f58271c-68a8-11e8-9760-b5c4c06d8b8f.gif)

**Comment by ianstormtaylor** [comment]
See https://github.com/ianstormtaylor/slate/issues/2746

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
