### ISSUE TITLE
Not every node affected by a change is revalidated

### ISSUE THREAD

**Issue by marian-c** [ianstormtaylor/slate#1657]
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?

When a change affects multiple adjacent inlines, validateNode prop only triggers for one of them.
To be more specific: adjacent inlines in a common immediate parent.

Steps to reproduce:
1: select text spanning 2 inlines
2: press the space bar
3: observe the console

Note that the problem seems to be more general, when the inlines don't have the same parent, the validateNode prop gets triggered on both of them, but then only on one parent.

```
├─ slate-react@0.11.4
└─ slate@0.32.4
```
http://recordit.co/pUupvM4Xh9
https://jsfiddle.net/fj9dvhom/141/

#### What's the expected behavior?

Every node that was affected by the change should be re-validated.

Edit:
It's worth mentioning that if instead of the space key, you press the delete key (mac) then the expected behavior happens, all nodes affected are re-validated

**Comment by zhujinxuan** [comment]
I think it is a bug existing in both insertTextAtRange and insertFragmentAtRange;

The deleteAtRang shall normalize the commonAcestor of startKey and endKey. However, insertFragmentAtRange normalize the parent of startBlock, and insertTextAtRange normalize the parent of startKey.
