### ISSUE TITLE
Keyboard selection won't extend across inlines

### ISSUE THREAD

**Issue by marian-c** [ianstormtaylor/slate#1658]
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?

You cannot keyboard select across inlines.

1: start the document with a paragraph containing two inline nodes
2: put the cursor in the first inline node
3: press `shift` + `->` enough times so that the selection should also move to the next inline.

Note that selecting with the mouse has no issue.

http://recordit.co/JKTVPna6qN
https://jsfiddle.net/fj9dvhom/141/

slate-react 0.11.4
slate 0.32.4
chrome
OS X

#### What's the expected behavior?
Selection also covers the second inline

**Comment by Soreine** [comment]
Is this related ? https://github.com/ianstormtaylor/slate/issues/1502

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
