### ISSUE TITLE
Documentation is missing properties for Plugins and Editor

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1668]
The [documentation for Plugins](https://docs.slatejs.org/slate-react/plugins) seems to be missing these properties: `renderMark`, `renderNode`, `renderPlaceholder`, `validateNode`, `decorateNode`, `renderPortal`. Any others?

These undocumented properties are hinted at in the [Plugins Guide](https://docs.slatejs.org/guides/plugins) --

```
...
RenderMark('bold', props => <BoldMark {...props} />),
...
```

The documentation should probably mention that these plugin functions are only called if the `Editor` component taking those plugins doesn't have that function explicitly passed in.

A Slack discussion pointed out that the docs should probably mention any concerns or cautions with using Plugin methods like `renderNode`, `renderMark`, etc. (that "it can get out of control quickly").

Also, `renderMark`, `renderNode`, etc seem to be missing on this documentation for the `Editor` --

https://docs.slatejs.org/slate-react/editor

**Comment by oyeanuj** [comment]
> A Slack discussion pointed out that the docs should probably mention any concerns or cautions with using Plugin methods like renderNode, renderMark, etc. (that "it can get out of control quickly").

I'm curious what the concerns here are, and if they are specific to `renderNode`, `renderMark`? Like the guide illustrates, they seem the logical function to use for encapsulation?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
