### ISSUE TITLE
Autofocus does not always result in the cursor being placed in the document

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1669]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

The autofocus prop currently focused the editor, but a cursor does not appear.

This is because autofocus does not actually select a block! So no block is selected and therefore the cursor does not appear.

#### What's the expected behavior?

The autofocus prop should by default try to figure out a sensible block to select (usually the 0 index of the first block in the document), unless the `value` already has a selection defined. 

This would allow the user to turn on the autofocus behavior, but still be able to control where the cursor shows up. 

Alternatively, the user could also provide a function for resolving selection during autofocus that would allow for more complex default selection rules (for instance, in editors with a Title block, users typically want the cursor to show up after the title).

**Comment by benjycui** [comment]
See: https://github.com/ianstormtaylor/slate/pull/1733
