### ISSUE TITLE
[Bug] Documentation for Schemas needs a small fix

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1672]
In [the documentation for `Schema`](https://docs.slatejs.org/slate-core/schema), in the "blocks" section,

`{ nodes: ... types: ... }`

Should be

`{ nodes: ... objects: ... }`

**Comment by CameronAckermanSEL** [comment]
If you're referring to this section https://docs.slatejs.org/slate-core/schema#blocks

Then I think the documentation is right. `type` refers to the subtype of the block, and `object` refers to the subtype of the node (such as `leaf`, `text`, `document`, `block`)

**Comment by ianstormtaylor** [comment]
I'm not exactly sure what you mean. In this case I think a PR is the preferred way to bring up an issue like this, since it will be much more clear, yet just as easy to do.

**Comment by tashburn** [comment]
You're right, this documentation is fine... my bad.
