### ISSUE TITLE
undo broken after using `Change.setValue`

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#1675]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

When you use the currently undocumented `change.setValue` feature, undo stops working unless you pass the option `{save: false}` to it.

#### What's the expected behavior?

Undo should continue to work after using `change.setValue` even if you don't add the option `{save: false}`

**Comment by thesunny** [comment]
This is a mentioned as a pre-requisite for submitting a PR to update documentation to add `change.setValue` here https://github.com/ianstormtaylor/slate/pull/1670

**Comment by CameronAckermanSEL** [comment]
Hey @thesunny, I took a whack at reproducing this in a fiddle and I didn't have much luck. 

This is what I tried https://jsfiddle.net/nuk24Lfx/

**Comment by thesunny** [comment]
This conversation was further carried out in Slack but just updating this Issue.

It appears that using `setValue` with a JavaScript object like `{data: someDataObject}` works.

However, when I tried to update the entire `Value` object, that's when things went weird.

Here's a fiddle:

https://jsfiddle.net/nuk24Lfx/18/

Note that in my original bug I had a different error message but was running off a slightly older version of Slate.

**Comment by ianstormtaylor** [comment]
Hey @thesunny, updating the entire value like that isn't supported.
