### ISSUE TITLE
Suggestion: Render placeholders after regular node children for consistent cursor behavior.

### ISSUE THREAD

**Issue by lukasbuenger** [ianstormtaylor/slate#1678]
#### Do you want to request a _feature_ or report a _bug_?

Kind of a feature request, more like a suggestion 

#### What's the current behavior?

slate-react's Node component renders the placeholder from `Plugin.renderPlaceholder` before the regular children of the node.

https://github.com/ianstormtaylor/slate/blob/3339d088e14ad0bf04a674c14834179403ae369f/packages/slate-react/src/components/node.js#L158 

#### What's the expected behavior?

I'd expect Placeholder components to get rendered *after* the regular (and probably empty) children of a node in order to have consistent cursor positioning (at start and before the placeholder) even when the placeholder is not absolutely positioned:

`children = [...children, placeholder,]`

**Comment by vilic** [comment]
@ianstormtaylor Any updates on this? I tried this in my own build previously, and it works in my case.

Related to #1344
