### ISSUE TITLE
add a `<Node>` wrapper component

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#168]
Right now using `renderNode` is kind of nice how simple it is to just return a component. But a few things about it are awkward:

- **Remembering to add `props.attributes`.** This is required for `findDOMNode` to work to get the DOM node to do things like position placeholders/menus absolutely. Not too tedious, but easy to forget. (Could be solved by asserting that it exists I think.)

- **Adding your own `shouldComponentUpdate` that's performant.** This one is trickier, since it's easy to do `shallowEqual`, but that's not actually the most performant thing, since `state` is passed to all nodes, and if the selection changes, then `shallowEqual` with still cause an update.

- **Adding your own `<Placeholder>` text.** This one is not horrible right now, but it's slightly more complex that it needs to be for the 90% use case. The `<Placeholder>` component gives you flexibility to add placeholders in places like image captions, where even though the document has text, you actually want to trigger the placeholder based on whether a specific block has text. But the most common case is going to be just going it for the whole document.

- **Using the `<Void>` wrapper.** This isn't strictly an issue right now, it's just slightly more verbose than needed, and if it happens to be made easier all the more reason. It's required to make void nodes handled properly in `contenteditable`, and to allow you to style based on the `:focus` of the nested void. 

To solve this, I was thinking about a `<Node>` component. (Or potentially two separate ones: `<Block>` and `<Inline>`.) It would look like:

```js
function QuoteBlock(props) {
  return (
    <Node>
      <blockquote>{props.children}</blockquote>
    </Node>
  )
}
```

Instead of the current:

```js
function QuoteBlock(props) {
  return (
    <blockquote {...props.attributes}>{props.children}</blockquote>
  )
}
```

---

The downside is that you have to always wrap things returned from `renderNode` in `<Node>`. But the upside is that it's harder to screw things up in the common use cases:

#### Attributes

`<Node>` would handle adding the `props.attributes` to the highest component for you (potentially only if a child doesn't already have it added). You could override this by just adding them deeper:

Current:

```js
function CodeBlock(props) {
  return (
    <pre><code {...props.attributes}>{props.children}</code></pre>
  )
}
```

With `<Node>` general case:

```js
function CodeBlock(props) {
  return (
    <Node>
      <pre><code>{props.children}</code></pre>
    </Node>
  )
}
```

With `<Node>` override case:

```js
function CodeBlock(props) {
  return (
    <Node>
      <pre><code {...props.attributes}>{props.children}</code></pre>
    </Node>
  )
}
```

#### shouldComponentUpdate

`<Node>` would automatically add it's own generally most performant `shouldComponentUpdate` function, for the 99% cases. Which you could override if you needed to with a `suppressShouldComponentUpdate` prop (mimicking React's native suppress props):

Current:

```js
class CodeBlock extends React.Component {
  shouldComponentUpdate(props, state) {
    ...
  }
  render() {
    return (
      <pre><code>{props.children}</code></pre>
    )
  }
}
```

With `<Node>` general case:

```js
function CodeBlock(props) {
  return (
    <Node>
      <pre><code>{props.children}</code></pre>
    </Node>
  )
}
```

With `<Node>` override case:

```js
class CodeBlockBody extends React.Component {
  shouldComponentUpdate(props, state) {
    ...
  }
  render() {
    return (
      <pre><code>{props.children}</code></pre>
    )
  }
}

function CodeBlock(props) {
  return (
    <Node suppressShouldComponentUpdate>
      <CodeBlockBody {...props} />
    </Node>
  )
}
```

#### Placeholders

`<Node>` could also expose an easy way to get the most general placeholder support with a `placeholder` attribute that takes a `String || Element`. Which could be overridden by just using the built-in `<Placeholder>` component yourself:

Current:

```js
function QuoteBlock(props) {
  return (
    <blockquote>
      <Placeholder {...props} parent={props.node}>...</Placeholder>
      {props.children}
    </blockquote>
  )
}
```

With `<Node>` general case:

```js
function QuoteBlock(props) {
  return (
    <Node placeholder="Enter some text...">
      <blockquote>{props.children}</blockquote>
    </Node>
  )
}
```

With `<Node>` override case:

```js
function QuoteBlock(props) {
  return (
    <Node>
      <blockquote>
        <Placeholder {...props} parent={props.node}>...</Placeholder>
        {props.children}
      </blockquote>
    </Node>
  )
}
```

#### Void

`<Node>` could handle the `isVoid` wrapping automatically, but still expose the `className` and `style` attributes that are critical for being able to style the void's contenteditable wrapper's `:focus` styles:

Current:

```js
function ImageBlock(props) {
  return (
    <Void className="image-wrapper">
      <img src={props.node.data.get('src')} />
    </Void>
  )
}
```

With `<Node>`:

```js
function ImageBlock(props) {
  return (
    <Node className="image-wrapper">
      <img src={props.node.data.get('src')} />
    </Node>
  )
}
```

---

If you're already using these types of use cases let me know what you think!

**Comment by arekkas** [comment]
Couldn't you make `<Node>` optional instead of mandatory?

**Comment by ianstormtaylor** [comment]
It could be optional, but then it means that a few of the hard-to-realize bugs surface again:

- `props.attributes` is easy to forget to add, not the worst thing in the world.
- `shouldComponentUpdate` is easy to forget, leading to way worse performance.
- Void nodes have to be wrapped in something, might as well make it `<Node>`.

**Comment by mathieudutour** [comment]
how about a high order component instead of a component that need to be imported in your renderer?

**Comment by ianstormtaylor** [comment]
@mathieudutour can you give an example of how it'd work?

**Comment by arekkas** [comment]
I think this is what @mathieudutour had in mind:

```es6
import React from 'react'
import {connect} from 'slate'

const Paragraph = ({children}) => <p>{chilren}</p>

export default connect(Paragraph)
```

**Comment by ianstormtaylor** [comment]
Would that be effectively the same thing but instead of wrapping it in `<Node {...options}>`, you'd be wrapping it in `connect(..., options)`?

**Comment by arekkas** [comment]
> You could simplify it to something like connect:

exactly

**Comment by mathieudutour** [comment]
Effectively it's the same, conceptually it's completely different:
 - in one case (Node), you need to tie your component to slate on the render function (bad)
 - in the other, you _[compose](https://en.wikipedia.org/wiki/Composition_over_inheritance)_ .

You can even do something like this:
```
const NODES = bindAttributesToRenderers({
  code: MyComponent
})
```
where `bindAttributesToRenderers` would iterate over the keys of the object and call `connect` on them (same way you have `bindActionCreators` in redux).

But I don't like `connect` because it is already use in redux. So if I use redux and slate at the same time (likely), I won't know which one is which.

**Comment by arekkas** [comment]
> But I don't like connect because it is already use in redux. So if I use redux and slate at the same time (likely), I won't know which one is which.

`import { connect: foobar } from 'slate'`

**Comment by mathieudutour** [comment]
How about calling it `foobar` directly? ;)

**Comment by mathieudutour** [comment]
because it's not really connecting anything anyway.

**Comment by arekkas** [comment]
>"There are only two hard problems in Computer Science: cache invalidation and naming things." *-- Phil Karlton*

**Comment by SamyPesse** [comment]
Does slate supports mixing editable / non-editable content inside the editor? For example to add a selector for the syntax of a code block:

```js
function CodeBlock(props) {
  return (
    <div>
        <select onChange={...} value={props.syntax}>
            <option>JavaScript</option>
            ...
        </select>
        <Node>
          <pre><code>{props.children}</code></pre>
        </Node>
    </div>
  )
}
```

Basically I'm trying to evaluate if this issue could make it possible to add "interactive" widgets in the editing area (Something similar to the [TeX example of Draft](https://github.com/facebook/draft-js/blob/master/examples/tex/js/components/TeXBlock.js)).

**Comment by mathieudutour** [comment]
@SamyPesse I implemented a similar thing like this: https://gist.github.com/mathieudutour/589bfa64f8daa64e91528b587adc4c6b

**Comment by SamyPesse** [comment]
@mathieudutour Thanks! 👍 So Slate supports it without range/content errors? Prosemirror fails to handle non-editable content inside its views (and Draft supports it, but doesn't support nested blocks ..).

**Comment by ianstormtaylor** [comment]
But @mathieudutour they both are "composing", one is just slightly less abstracted, a but more verbose, but maybe slightly less magic. 

With `<Node>` exposed you could write an equivalent `connect` (or `wrap`). And with `wrap` exposed you could write and equivalent `wrapRenderers`. Right?

One's a higher-order component, and one's a factory for creating higher-order components?

**Comment by ianstormtaylor** [comment]
Currently thinking about exposing something called `Renderer` or `Wrapper` and an equivalent factory called something like `render` or `wrap`.

**Comment by ianstormtaylor** [comment]
(I want to stay about from a `bindAll` type factory because there will be many cases that involve individual-level configuration, like `draggable: true`, `placeholder: '…'`, etc.)

**Comment by ianstormtaylor** [comment]
Hey all, got this working on a separate branch. @mathieudutour was right on all accounts, and I've got something similar to:

```js
import { wrap } from 'slate'

const NODES = {
   code: wrap()(props => <pre><code>{props.children}</code></pre>
}
```

As well as a `wrapAll` that lets you do more:

```js
import { wrapAll } from 'slate'

const NODES = wrapAll()({
  code: props => <pre><code>{props.children}</code></pre>,
  ...
}
```

And @arekkas is also correct that, unless we are okay with extra `<div>`s and `<span>`s in the rendered DOM, people will still have to mix in `...props.attributes`, sadly. (I'd rather not have extra elements, especially for cases like `<table>` or others where the browser will complain about DOM structure.)

Once that convenience is gone, which is the biggest pain of the ones I mentioned, we're left with:

- `shouldComponentUpdate` more performant 
- `<Placeholder>` easier
- `<Void>` easier

As far as `<Placeholder>` goes, with the `wrap()` API it's going to feel awkward as it is:


```js
import { wrap } from 'slate'

const NODES = {
   code: wrap({ placeholder: 'Enter some text...' })(props => <pre><code {...props.attributes}>{props.children}</code></pre>
}
```

And the `<Void>` convenience also will end up being slightly awkward for not that much gain. `<Draggable>` is another wrapper component that I'm going to add, and it too will be slightly more convenient, but not by much, and in a way that's magicky.

And then `shouldComponentUpdate`, which is actually the most important from a Slate-being-performant perspective, seems like we could just implement that by wrapping internally with a `<Node>` component that people never need to worry about...

So I'm thinking about just nixing this idea completely after all that, and just sticking to the more explicit `<Void>`, `<Draggable>`, `<Placeholder>` helpers that people can opt-in to if they want.

Let me know if you see holes in my logic (bound to be some), and if I should re-open this!
