### ISSUE TITLE
Pasted copy with carriage returns doesn't render the carriage returns

### ISSUE THREAD

**Issue by adrianclay** [ianstormtaylor/slate#1681]
#### What's the current behavior?

When pasting existing copy with solo carriage returns `\r` these aren't rendered by SlateJS

Given `This has a different new line\r\r\r\rThis is the final line.` in the clipboard when pasting into Slate no lines are rendered as shown below.

SlateJS vs Draft JS
![feb-28-2018 14-12-16](https://user-images.githubusercontent.com/976274/36792096-70381ec4-1c91-11e8-82fb-98ada28dec35.gif)

#### What's the expected behavior?

That the carriage returns are correctly rendered as shown in Draft JS

**Comment by DamareYoh** [comment]
Developers can write custom deserializer rules in their paste handlers that convert '\r' to newline.

**Comment by ianstormtaylor** [comment]
Could be solved here:

https://github.com/ianstormtaylor/slate/blob/2bf04b4a8c770692eea750c641b631ea2d2ad3bd/packages/slate-plain-serializer/src/index.js#L30

I'm not sure what the most standard behavior is though. I know nothing about the differences between `\n` and `\r` enough to make the decision. If anyone has prior art to point to that would be great!

**Comment by thesunny** [comment]
In terms of OS, the enter representation is:

- `\r` for Mac before OSX
- `\n` for OSX Mac and Unix
- `\r\n` for Windows

When doing a search replace, I search for `\r\n` first, then `\r` and `\n`. If you don't do the Windows style first, you end up with too many [ENTER]s.

**Comment by ianstormtaylor** [comment]
@thesunny but shouldn't we fix this in the `slate-plain-serializer` then to properly handle the Windows-style breaks?

**Comment by thesunny** [comment]
Oops, sorry, I actually hit the wrong button. I didn't mean to close this!

**Comment by zhujinxuan** [comment]
My naive solution about this:
https://github.com/zhujinxuan/slate-better-soft-break

**Comment by ianstormtaylor** [comment]
I'm fairly sure this is still an issue for the basic plaintext pasting. If anyone wants to help solve this, I think it would involve changing the default logic to split on any of the line break combinations instead of just `\n` in the `insert_data` command of `withReact`.

**Comment by thallada** [comment]
It looks like this issue is also occurring with plain text with normal `\n` newlines in 0.57.1.

I opened a PR to fix both styles of newlines: https://github.com/ianstormtaylor/slate/pull/3472
