### ISSUE TITLE
onBeforeInput is not triggered as advertised

### ISSUE THREAD

**Issue by marian-c** [ianstormtaylor/slate#1688]
I _think_ this is a bug.

The documentation mentions that this event (`onBeforeInput`) is triggered "right before a string of text is entered into the `contenteditable` element".

This is not the case, when I paste into the editor, the event is not triggered.

**Comment by davidchang** [comment]
@marian-c if you feel like it's unclear in the documentation, feel free to submit a PR? otherwise, were you blocked by this? seems like `onBeforeInput` is meant for actually manually inputting text, while pastes are covered by `onPaste`

**Comment by marian-c** [comment]
Closing this since it's not an actual bug, docs can be improved tough, might submit a PR if time permits.

Thanks
