### ISSUE TITLE
readOnly is not properly being set after selecting slate instance

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#169]
1. Have `<Slate readOnly={false} />`
1. Select slate instance with cursor and optionally write something
2. Set `<Slate readOnly={true} />`
3. Slate instance still renders `contenteditable=true`
4. Write something in that instance
5. Slate instance now sets `contenteditable=false`

This does not happen when the slate instance was not selected.

Probably something to do with some shouldComponentUpdate somewhere in slate.

![slateselect](https://cloud.githubusercontent.com/assets/3372410/17083729/2969f08a-51a9-11e6-8a7e-9c6bb5addab3.gif)

**Comment by ianstormtaylor** [comment]
Oops sorry accidentally marked read and didn't check it out. I'll get it tomorrow!

**Comment by ianstormtaylor** [comment]
Fixed in `0.7.5`!
