### ISSUE TITLE
Latest release has unmet peer dependencies?

### ISSUE THREAD

**Issue by bengotow** [ianstormtaylor/slate#1690]
Hey! The latest Slate release which bumped `slate` to 0.33.0 is causing issues for me. It looks like `slate-plain-serializer` and the other packages had their `devDependencies` bumped but not the `peerDependencies`, which means they still look for `slate@0.32.x` at install time and npm complains about an `UNMET PEER DEPENDENCY`:

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-plain-serializer/package.json#L20

This may not have been an issue for the last several releases because the carat matched the patch version bumps.

**Comment by tashburn** [comment]
I'm getting the same warnings by (I think) webpack -- 

```
warning " > slate-html-serializer@0.5.6" has incorrect peer dependency "slate@^0.32.1".
warning " > slate-react@0.12.0" has incorrect peer dependency "slate@^0.32.1".
warning "slate-react > slate-base64-serializer@0.2.25" has incorrect peer dependency "slate@^0.32.1".
warning "slate-react > slate-plain-serializer@0.5.6" has incorrect peer dependency "slate@^0.32.1".
warning "slate-react > slate-prop-types@0.4.23" has incorrect peer dependency "slate@^0.32.1".
```

**Comment by ianstormtaylor** [comment]
Thanks for the note. Should be fixed now, it was due to the new Lerna where `peerDependencies` aren't automatically bumped, which is good.

**Comment by bengotow** [comment]
Awesome - thank you! 👍

**Comment by tashburn** [comment]
Super! Thanks.
