### ISSUE TITLE
Copy of a word within a marked set of text copies all characters prior to and including the selected word.

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1693]
#### Do you want to request a _feature_ or report a _bug_?
Bug 

#### What's the current behavior?

When copying a word from a block that has a `mark` starting at the beginning of the text, all of the text prior to the selected word is also applied to the clipboard.

http://recordit.co/8dapGX4bRF

#### What's the expected behavior?

Only the selected word is copied.

**Comment by zhujinxuan** [comment]
I do some logs in the devTool.  I am sure that the problem is the fragment contains no marks in insertFragmentAtRange

I think the problem is by getFragmentAtRange

**Comment by benjycui** [comment]
The bug relate to browser compatibility.

In Firefox, what we copy is:

```html
<div style=\"position: absolute; left: -9999px; border: 0px none; padding: 0px; margin: 0px; top: 52px;\" contenteditable=\"true\"><span style=\"white-space: pre;\" data-slate-fragment=\"JTdCJTIyb2JqZWN0JTIyJTNBJTIyZG9jdW1lbnQlMjIlMkMlMjJkYXRhJTIyJTNBJTdCJTdEJTJDJTIybm9kZXMlMjIlM0ElNUIlN0IlMjJvYmplY3QlMjIlM0ElMjJibG9jayUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwYXJhZ3JhcGglMjIlMkMlMjJpc1ZvaWQlMjIlM0FmYWxzZSUyQyUyMmRhdGElMjIlM0ElN0IlN0QlMkMlMjJub2RlcyUyMiUzQSU1QiU3QiUyMm9iamVjdCUyMiUzQSUyMnRleHQlMjIlMkMlMjJsZWF2ZXMlMjIlM0ElNUIlN0IlMjJvYmplY3QlMjIlM0ElMjJsZWFmJTIyJTJDJTIydGV4dCUyMiUzQSUyMmJvbGQlMjIlMkMlMjJtYXJrcyUyMiUzQSU1QiU3QiUyMm9iamVjdCUyMiUzQSUyMm1hcmslMjIlMkMlMjJ0eXBlJTIyJTNBJTIyYm9sZCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlN0QlN0QlNUQlN0QlNUQlN0QlNUQlN0QlNUQlN0Q=\">bold</span></div>
```

In Chrome, what we copy is:

```html
<meta charset='utf-8'><strong style="color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Since it's rich text, you can do things like turn a selection of text bold</strong>
```

As you can see, `data-slate-fragment` is missing in Chrome's copied HTML. So that we cannot extract fragment from the HTML:

https://github.com/ianstormtaylor/slate/blob/4346ad0e3f4a956e40a71f3cfd36682be6f90f4a/packages/slate-react/src/utils/get-event-transfer.js#L43-L47

So that the paste logic is affected.

**Comment by benjycui** [comment]
You can try to copy from Firefox, and then paste in Chrome, it works fine.

And if you copy from Chrome, and then paste in Firefox, it is broken.

**Comment by tobiasandersen** [comment]
We have the same problem as described by @benjycui when copying void nodes. See #1543 for some more info around it...

**Comment by CameronAckermanSEL** [comment]
latest slate and slate-react dont resolve this issue unfortunately

**Comment by zhujinxuan** [comment]
We have a similar discussion in https://github.com/ianstormtaylor/slate/issues/1799 

It seems div.innerHTML is text/plain sometimes

**Comment by tobiasandersen** [comment]
I think #1815 might have fixed this. @CameronAckermanSEL you think you could verify?
