### ISSUE TITLE
Korean language input bug, missing chars, eventually freezing

### ISSUE THREAD

**Issue by doortts** [ianstormtaylor/slate#1701]
#### Do you want to request a _feature_ or report a _bug_?

First, I want to say thank you for your awesome editor. I'm a maintainer of project hosting software [Yona](https://github.com/yona-projects/yona)
We want to change our main editor to slate. But there are problems now. I hope it is resolved.

#### What's the current behavior?

When I type Korean, if I type more than 3 Korean chars, it doesn't work.

There are obvious few symptoms of it.

- missing chars 
- and eventually freezing editor
- at every end of line, we have to type return key twice to change line.

First one, I just typed 3 Korean chars, 언제나 
but you can see only two.

![korean-missing-chars](https://user-images.githubusercontent.com/520523/37326691-a3cf4e34-26d6-11e8-96de-66d4c4fe7835.gif)

And more type, more broken. you can see even freezing at some moment and go on at another moment.
![korean-missing-chars](https://user-images.githubusercontent.com/520523/37326994-e418fbec-26d7-11e8-85e7-4b1d22fb2087.gif)

#### What's the expected behavior?

- No missing chars
- No need to type Enter key end of line

I've read your principles very well. I hope we can use your editor!

**Comment by doortts** [comment]
# update 18.05.03

According to the test of http://slatejs.org/#/rich-text 

It seems Korean character disappearing problem is solved now.

Remaining problem is no new line when to type Enter key. 
When type Enter in the middle of compositioning state, it just ened composition state and no new line.

I think this problem is related with composition state.

Even though it isn't 'compositionend', when user type Enter key, the new line should be followed instantly.  

Example.
---
I typed few Korean (one of CJK) and pressed Enter key.
It should be ended with new line.

Draft.js: Working right.
![draft-case](https://user-images.githubusercontent.com/520523/39570357-081163ba-4f03-11e8-95fe-8b988c3db477.gif)

Slate.js: I typed Enter key in the end. But no new line. Just cursor moved and compositionend state.

![slate-case](https://user-images.githubusercontent.com/520523/39570447-56e4bb36-4f03-11e8-9fac-0121f84b6d34.gif)

See: https://developer.mozilla.org/en-US/docs/Web/Events/compositionend

I really want to make some slate plugin contribution for Korean. But IME problem stopped me already few times. 

@ianstormtaylor I need your help.

**Comment by designforhuman** [comment]
I have the same issue here.

**Comment by doortts** [comment]
@ianstormtaylor 
We've been trying to change our main markdown editor. 
At first, mentioned above, we had tried to adopt Slate editor. But unfortunately, we had to wait until this problem resolved. And it seems it doesn't resolve, still. 

Recently, another guy recommended us 'StackEdit'. it was a very good editor, too. 
But sadly, the same problem existed. So, I reported it. 
And a few days ago, they found the way to fix it.

https://github.com/benweet/stackedit/issues/1376

I hope also it will be helpful to Slate editor.
Thanks!

**Comment by doortts** [comment]
@ianstormtaylor Is there any update? 
Or if you can explain the codes of composing chars or events, I'll participate in investigating it.

**Comment by nayunhwan** [comment]
I have another issue related to Korean.

After typing Korean, In order to remove all string in a line at once time, I pressed `cmd` + `del`.
Then, the editor showed the error message and broke down.

But this issue had not happened in English.

![slate 1](https://user-images.githubusercontent.com/7167731/46448627-c0fa1d80-c7c2-11e8-984f-179e1c95c7d0.gif)

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
