### ISSUE TITLE
IE11 Soft Breaks not Working

### ISSUE THREAD

**Issue by lucadegasperi** [ianstormtaylor/slate#1703]
#### Do you want to request a _feature_ or report a _bug_?

A BUG

#### What's the current behavior?

```
"slate": "0.33.0",
    "slate-html-serializer": "0.5.6",
    "slate-react": "0.12.0",
    "slate-soft-break": "0.6.0",
```

```
const plugins = [
    SoftBreak({
        shift: true
    })
];
```

Using the following packages when doing a `shift + enter` on the keyboard in IE, the cursor starts moving around and the next character I type on the keyboard makes the editor crash.

![schermata 2018-03-14 alle 10 22 01](https://user-images.githubusercontent.com/820687/37393528-9f3ad64a-2771-11e8-9b7a-a1562af59902.png)

#### What's the expected behavior?

A soft break `<br>` should be inserted and everything should work normally.

If anyone can point me in the right direction on how to create a JS fiddle with slate-soft-break in it, I'll try my best to recreate the issue. Thank You!

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
