### ISSUE TITLE
Not able to delete list item bullet

### ISSUE THREAD

**Issue by harryprimoko** [ianstormtaylor/slate#1706]
Dear Team,

I'm facing a issue with list items when i try to make a list like : 

- A
- B
- C

when doing Backspace first bullet item is not getting delete
- 

Any help and suggestion would be appreciated. Thanks

**Comment by CameronAckermanSEL** [comment]
Could you elaborate a bit more on the expectations, and provide a GIF? The issue template has a tool that you can use to generate one.

Thanks :)

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortun...
