### ISSUE TITLE
IME - Japanese input - some characters get erased

### ISSUE THREAD

**Issue by illesg** [ianstormtaylor/slate#1710]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

MacOS High Sierra (10.13.3)
Chrome 64.0.3282.186 using input method: **Hiragana (Google)**

**expected behavior:** if you type the characters: nn[space]wo, the expected output is: ンを

**current behavior:** currently in slate, the output is: ンお  (character sequence: nn[space]o, w gets erased)

It looks like the editor's forced re-render causes the issue in the compositionStart and compositionEnd event handlers.

Related bug: #1708

**Comment by 21-Hidetaka-Ko** [comment]
Same as me. Thanks for issuing.

**Comment by doortts** [comment]
It also happens in Korean. https://github.com/ianstormtaylor/slate/issues/1701

I think slate have CJK problems.

@ianstormtaylor How can I/we help you to solve these problems?

**Comment by 21-Hidetaka-Ko** [comment]
We can't launch by you fix this issues. Could you solve this if you can ?
