### ISSUE TITLE
cloneFragment is broken when multiple <Editor /> instances are present

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#1722]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
If we have multiple instances of <Editor /> on one page, it is impossible to copy text from any but the first instance in the DOM.

#### What's the expected behavior?
We should be able to copy from any editor instance.

This bug is caused by the `cloneFragment` function always selecting the first instance in the DOM regardless of which instance the copy event was triggered from:
https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/clone-fragment.js#L99

**Comment by tobiasandersen** [comment]
Fixed by @czechdave in #1728 🎉
