### ISSUE TITLE
feature request: image resize

### ISSUE THREAD

**Issue by Hongbo-Miao** [ianstormtaylor/slate#1724]
#### Do you want to request a _feature_ or report a _bug_? feature request

It would be great to support resizing image when an image is selected, something like

![image](https://user-images.githubusercontent.com/3375461/37860578-4577fc3e-2ee5-11e8-87c0-008eac062a23.png)

Please correct me if I missed something, thanks!

BTW, the package looks very promising!

**Comment by tobiasandersen** [comment]
Hi! I think features like this makes more sense to create as plugins outside of Slate. Hopefully people will do this and release as open source. I'd try the slack channel in the meantime and see if anyone can help you!
