### ISSUE TITLE
Remove draggable attribute in nodes.

### ISSUE THREAD

**Issue by chilijung** [ianstormtaylor/slate#1726]
#### Do you want to request a _feature_ or report a _bug_?

Now every node will wrap with a `div` container with draggable attribute, this will conflict with customized dnd features, source: https://github.com/ianstormtaylor/slate/blob/3339d088e14ad0bf04a674c14834179403ae369f/packages/slate-react/src/components/void.js#L79

![](https://user-images.githubusercontent.com/3375461/37860520-4a44dee0-2ee4-11e8-8129-f8020aaeae90.png)

Code source: https://github.com/Canner/slate-editor-icons/blob/master/packages/slate-editor-renderer/src/ImageNode.js#L128

You could try it live here: https://canner.github.io/slate-editor-icons/

#### What's the current behavior?

Wrap every node with draggable attribute.

#### What's the expected behavior?

The attribute should be remove.

**Comment by pizn** [comment]
Handle image resizing can use `mouseDown`/`mouseMove`/`mouseUp` event. And void node support `draggable` attribute is needed.

**Comment by chilijung** [comment]
@pizn, I think slate shouldn't default add `draggable` attribute, there are many dnd libraries that do better jobs. Right now it's interfering other libraries.

**Comment by pizn** [comment]
Maybe can support custom defined `draggable` attribute, default is true.

**Comment by tobiasandersen** [comment]
Yeah I've also found myself work around this. Couldn't people just set the `draggable` attribute themselves if they want it, but also where they want it?

**Comment by czechdave** [comment]
Just ran into an issue with the forced `draggable` attribute too. What is the reason Slate does anything related to draggability? As far as I can tell that attribute should just be removed.

**Comment by ianstormtaylor** [comment]
I’m down for it to be opt-in. If whoever submits the PR can also make it so that the images and emoji examples remain draggable that would be perfect.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
