### ISSUE TITLE
[Idea] Abstract Delta Operations

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#1730]
This is basically the same as #1456, but I will describe an approach here in the hope to get some feedback and to start a discussion. This is a first (perhaps naive) attempt at describing a possible approach.

### Reasons
* For storing delta operations in a back-end, it would be more efficient to store abstract operations which can later be converted to detailed operations,
* Allow undoing of user-defined groups of actions

### Data structures
Two Operation datastructures:
* Operation: the existing low-level operation designed to be minimally expressive
* AbstractOperation: user-defined collection of Operations to be applied

![image](https://user-images.githubusercontent.com/3816712/37973433-bd899cf8-31da-11e8-8e66-1a0de8d9bdfd.png)
Here OP represents an Operations and Aop an AbstractOperation (sorry for the terrible camera quality (and drawing ability ;))). As you can see, Aop's are composable and the top-level nodes are the "sources of truth" so to say. These can then be unpacked into their original Op's to actually apply the changes by the editor.

### Determining AbstractOperations from Operations
When applying operations, these should then be converted to one AbstractOperation that represents the series of changes.
For example, when inserting a series of characters and we have an "insertWord" AbstractOperation; when the user adds characters, these should be combined into the "insertWord" AbstractOperation until the user presses "space", then when typing new letters, the operations will be combined in a separate AbstractOperation.

### Code implications
* These AbstractOperations must be registered somewhere so that the editor is able to determine AbstractOperations from Operations and can succesfully compose them.
* This would replace the functionality here for merging Operations in the history (https://github.com/ianstormtaylor/slate/blob/3339d088e14ad0bf04a674c14834179403ae369f/packages/slate/src/models/history.js#L133)
Instead, registered Abstract operations should be given the chance to allow merging of operations. The merging functionality for text as it works right now could be replaced by an AbstractOperation instance which represents the merged behaviour.

### AbstractOperation data structure
??? todo

### Other possible solutions
* Allow the user to give a "label" to a change object (which represents a series of change operations).

**Comment by majelbstoat** [comment]
At Medium (not using Slate, but similar architecture), we call these Commands. They also function as atomic undo checkpoints. For example, when undoing the insertion of an image, we also have to remove the caption block too. It's a pretty fundamental part of the architecture, and seems like it's generally applicable to editors.

**Comment by ianstormtaylor** [comment]
Open to ideas here for how this might be implemented. Would be great to see some pseudo-code samples at the least. I'm not sure I follow exactly what these types of things would be.

**Comment by bryanph** [comment]
I will just close this for now until someone can actually write down a proper spec of what this would require. I actually think this should be done in user-land as a separate package. (just like OT)

**Comment by FezVrasta** [comment]
Has there been any progress on this front? Any 3rd party package I could use?

**Comment by Immortalin** [comment]
@FezVrasta either use JSON diff on the onChange value or you can use the batched Operations. See the withHistory package
