### ISSUE TITLE
Chinese input make video refresh

### ISSUE THREAD

**Issue by wagon1104** [ianstormtaylor/slate#1738]
#### What's the current behavior?

![](https://wagon1104.github.io/image/embeds-bug.gif)

**Comment by intellild** [comment]
Is this solved?
I have nerver seen it after slate upgrade to 0.33.5
@ianstormtaylor

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
