### ISSUE TITLE
value.inlines : no value.activeInlines ? 

### ISSUE THREAD

**Issue by EricAmilhat** [ianstormtaylor/slate#1749]
First of all, thank you guys for the amazing job with Slate JS.

#### Do you want to request a _feature_ or report a _bug_?

I wish to request a feature

I want to implement a highlight feature, with multiple colors.

I have currently done this using marks, but I have quickly realized that this highlight feature shouldn't use marks but Inlines instead. 

This is because highlighting a word that has already been highlighted with another color has to disable the other highlights marks, so it doesn't behave like a mark but more like an Inline (because it cannot have more than one highlight color).

I am now trying to implement this feature with inlines. The only problem is that when I make a selection, I now need to be able to know if the current selection has activeInlines (like I was able to do with activeMarks) in order to adapt the behavior of the highlighting.

For example : 
- if selection contains only highlighted text, unhighlight.
- if selection contains highlighted text and no highlighted text, highlight.

Without Value.activeInlines, I don't see how I could acheive that.

#### What's the current behavior?

value.inlines gives all inlines for the current selection. There is no way to know if the selection uniquely contains inlines.

#### What's the expected behavior?

Is there any way SlateJS could implement the value.activeInlines (like activeMarks) ?
If not, how could I acheive this ?

Thank you so much for your help

**Comment by thomaswhyyou** [comment]
I haven't had the need to implement multi-color highlight personally so I can't confirm with certainty, but I think you might be able to pull this off with `Mark`? Looking at the latest Slate [doc for Mark page](https://docs.slatejs.org/slate-core/mark), its properties support `data` where you can store arbitrary meta data. 

```
Mark({
  data: Data,
  type: String,
})
```
Couldn't you have one mark type  (e.g. `highlight`) and store color info in `data` (with some default color)? Then when you are applying a color to some text that already has existing `highlight` marks, you could either choose to remove or overwrite - but since color variants are all of the same type, that means a given text shouldn't have more than one color at a given time. Hope I understood your objective correctly and this is helpful.

**Comment by EricAmilhat** [comment]
You did correctly understand my objective and indeed, I wasn't aware of the possibility to add arbitrary data to a mark, this is very helpful, thank you!

I guess using Marks would be better way then. Although, if I want to style the highlight (with border and border radius), this happens : 

![highlight](https://user-images.githubusercontent.com/29569614/38199288-81139fb6-3690-11e8-92b0-c4dca2a4c6a3.gif)

So was wondering, is there any way to tell Slate which mark should have "priority" on wrapping other marks ? 

Again, thank you for your help !

**Comment by EricAmilhat** [comment]
As stated in the docs : 

> - Marks represent unordered, character-level formatting.
> - Inlines represent contiguous, semantic elements in the document.

I'm guessing this highlight feature should be contiguous ?

**Comment by thomaswhyyou** [comment]
> Although, if I want to style the highlight (with border and border radius), this happens 

The issue you are describing here isn't specific to highlighting though it seems, and not necessarily to Slate.js either (see 'Well-Behaved Content' section of this [post] for the difficulty around document modeling and rendering (https://medium.engineering/why-contenteditable-is-terrible-122d8a40e480)).

Typically (in my experience), you want to render marks in a way that they are indifferent to the number/order they are applied, and whether they are contiguous or not. Not sure of your requirements, but border/border-radius would be tricky with marks

> is there any way to tell Slate which mark should have "priority" on wrapping other marks ?

I'm not aware something like this exists.

**Comment by CameronAckermanSEL** [comment]
> I'm not aware something like this exists.

This is correct, marks are not stored like this. The `text` of a `TextNode` is broken up into several `Leaf` blocks based on what marks exist on that segment of the text. 

For instance, the text 

`<b>this <i>has several</b> styles</i> on it`

looks like

```
{
  object: text,
  nodes: [
    {
      object: leaf,
      text: 'this ',
      marks: ['bold'],
    },
    {
      object: leaf,
      text: 'has several',
      marks: ['bold', 'italics],
    },
    {
      object: leaf,
      text: ' styles',
      marks: ['italics],
    },
    {
      object: leaf,
      text: ' on it',
      marks: [],
    },
  ]
}
```

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
