### ISSUE TITLE
Dragging text node to empty line results in key change for both lines, making action impossible to undo

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1759]
#### What's the current behavior?

For bugs, you **must** include the following: 

  - A JSFiddle that minimally reproduces the issue: **Reproducible on official examples**
  - A GIF showing the issue in action: http://recordit.co/vGe5NmjzTC
  - Information about your OS, browser, Slate version, etc:

`Windows 7`
`Chrome 65`
`Slate 0.33.4`

#### What's the expected behavior?

Dragging text to an empty node does not change the keys of the relevant nodes, allowing the action to be undone.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
