### ISSUE TITLE
Unexpected call to onChange when a different value is provided

### ISSUE THREAD

**Issue by Zhouzi** [ianstormtaylor/slate#1762]
**Steps to reproduce:**

1. Create an editor with an initial value and no schema
2. Change that editor's value somehow, still without any schema (e.g by clicking a button)
3. `onChange` is called

[Reproduction](https://codesandbox.io/s/74km4o5n1)

There is no normalization happening so `onChange` shouldn't be called. After digging deeper, it seems that the only difference comes from `schema.Stack`

_Same reproduction with an older version of Slate, the bug was not present: [reproduction](https://codesandbox.io/s/z3v7x31mlx)._

**Comment by zhujinxuan** [comment]
It seems `slate-react/src/components/editor` does not have `shouldComponentUpdate`

**Comment by alexandcote** [comment]
I think this issue is solved or at least, your reproduction code doesn't trigger onChange with the last version of slate. Can we close this issue?

**Comment by zhujinxuan** [comment]
I think we can close the issue if the problem does not occur anymore.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
