### ISSUE TITLE
Pasting very huge document freezes the editor, taking more than 10 minutes to finally paste

### ISSUE THREAD

**Issue by chitezh** [ianstormtaylor/slate#1768]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Pasting a very huge document like the one contained in this file [https://www.dropbox.com/s/wpefhhwrivvajvc/huge.text?dl=0](https://www.dropbox.com/s/wpefhhwrivvajvc/huge.text?dl=0) on slatejs.org demo app freezes the app. I didn't see the need to make a jsfiddle example as it's happening on slate demo

#### What's the expected behavior?
It appears within seconds like it does on facebook.com, draft.js, http://prosemirror.net/, https://quilljs.com/

**Comment by CameronAckermanSEL** [comment]
Was this using the paste html example?

**Comment by chitezh** [comment]
I tried it on richtext and huge document examples(clearing existing contents first).

Note, I pasted the content on the linked file [https://www.dropbox.com/s/wpefhhwrivvajvc/huge.text?dl=0](https://www.dropbox.com/s/wpefhhwrivvajvc/huge.text?dl=0) not the dropbox page

**Comment by CameronAckermanSEL** [comment]
I don't know that those examples have paste handlers, so maybe check what happens with the Paste HTML example because that's specifically implemented to showcase the paste handling and how that works.

It might have the same performance problems, but it also might not.

**Comment by chitezh** [comment]
Just tried pasting on `Paste HTML` example; same result

**Comment by zhujinxuan** [comment]
I do not find a easy way to solve the problem.  It seems we have to async the serializer to solve the problem.

**Comment by Slapbox** [comment]
Woah yeah that document destroys my editor. It's been several minutes now since the cursor even blinked. I eventually had to restart, as I have no idea how much longer that might have gone on for.

**Comment by zhujinxuan** [comment]
I have a hypothesis.  The slate creates a list of characters when creating texts.  If we change the structure of text, use leaf rather than characters as the base of text.  It would solve the problem.

However, I would begin on performance issue when and only when my finishing https://github.com/ianstormtaylor/slate/pull/1765

**Comment by benjycui** [comment]
The bottle neck is `node.mapDescendants`, not serializer. See: https://github.com/ianstormtaylor/slate/pull/1783

**Comment by zhujinxuan** [comment]
@benjycui Do you mean the paste problem is fixed after that PR?

**Comment by chitezh** [comment]
Thanks, will do

**Comment by chitezh** [comment]
Great improvement!

However, it did freeze the editor for an average of **38s** which is a significant improvement from the **2m11s** on slate.org. 
Also, it still did show the `unresponsive page warning`
![image](https://user-images.githubusercontent.com/7795177/38930238-1e4b6462-4307-11e8-97fe-30e6f0aadb63.png)

**Comment by benjycui** [comment]
@chitezh you need `NODE_ENV=production` to use production version when you test it locally.

**Comment by chitezh** [comment]
this is no longer an issue in newer versions
