### ISSUE TITLE
Copying a selection starting with an empty block fails to preserve formatting on paste

### ISSUE THREAD

**Issue by bsouthga** [ianstormtaylor/slate#1775]
#### Do you want to request a _feature_ or report a _bug_?

It looks like there is a bug around copy / pasting lists (and possibly other blocks) when the selection starts with an empty block.

#### What's the current behavior?

When copying a selection starting with an empty block, the pasted result is unformatted plaintext. However, if the selection starts with a non-empty block, formatting is retained. 

See gif below (reproduced in playground on [slatejs.org](http://slatejs.org/#/rich-text)):

![copy](https://user-images.githubusercontent.com/4740806/38741934-2c3456a8-3f09-11e8-9b1d-78ee1a8ee7c0.gif)

#### What's the expected behavior?

Formatting for subsequent non-empty blocks remains after pasting

**Comment by jvdsande** [comment]
Hi, I can confirm having this issue on all major browsers.

I actually made a PR fixing this issue a few days back: https://github.com/ianstormtaylor/slate/pull/1748

Regards, 
Jeremie

**Comment by jvdsande** [comment]
I should note that this affects more than lists: it's all blocks and all marks, as the slate-data-transfer attribute is not set at all, resulting in complete plain-text copy.

**Comment by jvdsande** [comment]
The 'data-slate-fragment' attribute, to be correct.

**Comment by Slapbox** [comment]
This seems to be resolved, at least, the demo case. Can anyone produce a demonstration of this issue for Slate 37?

**Comment by bsouthga** [comment]
I can't reproduce this in current slate, happy to close
