### ISSUE TITLE
Question - embedding editors within editors (editor inception)

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#178]
I am wondering the best approach for placing editors within editors. On the surface this seems very trivial with Slate compared to other WYSIWYGs, however I need the histories (undo/redo) of the editors to be connected.

My use case goes like this:

1. User types text into editor.
2. User highlights inline text and adds a "popup" (ie. annotation). This action pauses the original editor and opens a second editor for the popup's contents.
3. User decides after creating the popup that they don't want the popup, so they press Cmd-z to undo. Ideally this would reverse the previous state, destroying the popup and returning to the original text.
4. Then the user decides they really did want the popup, so within the original editor the press Cmd-Shift-z thus redoing the previous action and returning to the popup mode.

After a brief reading of the Transform, State and Document code this seems rather doable by sharing the History object between editor states. What is tripping me up is how to let the states know which editor the history was made in so it can smartly switch between editors as the user undoes and redoes changes.

I would like to mention that I have implemented this scenario in many, many different WYSIWYGs with varying degrees of success. The closest I have come so far is with Quill, which our production application is currently running. Not a single editor manages to come close to having undo/redo support with embed editors and all of them had issues with switching between two editors. To me this is the true power of Slate and IMO is the absolutely the future of WYSIWYG on the web. So kudos for doing what everyone else has fallen short at.

**Comment by ianstormtaylor** [comment]
Thanks 😄  glad you like it!

Question, since you have more context on this than me, what changes would you make to the architecture to make this possible?

**Comment by tyler-johnson** [comment]
Okay after giving this a lot of thought and a thorough reading of Slate's code, I guess what I am asking for is **multiple document/editor support**.

I'm not totally sure how this manifests itself in Slate, but in my mind documents/editors would share a couple of features:

- Undo/redo history. Ideally typing cmd-z in one editor would undo a change in different editor (if that was the last change in history). I know with immutability this may be difficult to do transparently, however I think there is a real use case here. Our users have been asking for it for a while now, but it has been incredibly complex to achieve in Quill.
- *Some, but not all* plugins. Obviously this already doable, however I'm thinking more that there is a shared state of sorts so that plugins could be aware of all the connected documents/editors.

**Comment by ianstormtaylor** [comment]
The history one makes sense to me. What is the "some, but not all plugins" need for?

**Comment by tyler-johnson** [comment]
I just meant that I would have some plugins that are just for individual editors and some plugins that all the editors would share. Of course there may not be any difference in the API for this.

I'm going to close this issue since I consider it solved. We do not need support for multiple documents anytime soon, so I will probably open an issue for this down the road, assuming it doesn't get solved in the mean time. Thank you for all your help!

**Comment by ianstormtaylor** [comment]
Ah gotcha, sounds good thanks man!
