### ISSUE TITLE
`decorateNode` update does not proplerly re-render decorations

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#1790]
# Description

If you change the list of plugins you pass to `Slate.Editor` in a way that would affect the `decorateNode` of the resulting `Stack`, the decorations may not be properly re-rendered.

*This is not a common use-case*. So it might not be important to fix.

# Explanation

This is because the `shouldComponentUpdates`, [like the one of `Node`](https://github.com/ianstormtaylor/slate/blob/a943eada8534ccdff05a770ad84ac599bd7b3682/packages/slate-react/src/components/node.js#L63), cannot be aware of the new `decorations` of their children, and thus prevent updates.

For example, if my new `decorateNode` function affects `code` blocks and I have a document like this:

```jsx
decorateNode = (props) = {
  if (props.node.type === 'code') {
    return computeDecorations();
  } else {
    return null;
  }
}

<document>
  <quote>
    <code>function () {}</code>
  </quote>
</document>
```

Then the `<quote>` will not update because its `node` has not changed (nor its `decorations = []`), and no check is done about an updated `schema`.

**Comment by ianstormtaylor** [comment]
Ah interesting. Would the same issue then apply to `renderNode`?

I’d be down to have it check to see if the schematic is changed and re-render if so.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
