### ISSUE TITLE
this.document.getPreviousInline is not a function

### ISSUE THREAD

**Issue by kalley** [ianstormtaylor/slate#1794]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
When calling `value.previousInline`, and error gets thrown because `this.document.getPreviousInline` is not a function

fiddle: https://jsfiddle.net/qmxu8ocy/ (type anything)

OS: mac
browser: Chrome
slate version: 0.33.4

#### What's the expected behavior?
It would return the previous inline if it existed.

I'm getting around it right now by using `value.document.getPreviousSibling` and checking if it's inline or not. I looked through history and I'm not sure that `getPreviousInline` ever existed :man_shrugging:

**Comment by davidchang** [comment]
seems like https://github.com/ianstormtaylor/slate/blob/9e50bc6b1fd881e7a913ae890481316714c7bf59/packages/slate/src/models/value.js#L472-L490 should be removed from the value API, though that might warrant a minor version bump? looks like neither `previousInline` nor `nextInline` in the Slate codebase itself. unless we want to implement `getPreviousInline` and `getNextInline` on document

**Comment by ianstormtaylor** [comment]
Open to a PR that adds those two.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
