### ISSUE TITLE
CI is now breaking due to node 10 / upath bug

### ISSUE THREAD

**Issue by jasonphillips** [ianstormtaylor/slate#1795]
Check out these failing Travis builds across latest PRs:

https://travis-ci.org/ianstormtaylor/slate/jobs/371132970
https://travis-ci.org/ianstormtaylor/slate/jobs/371138323

The problem shows up here:
![image](https://user-images.githubusercontent.com/5672408/39258812-85537960-487a-11e8-824e-51ae169c82b8.png)

And is caused by Travis now grabbing the latest Node release, which as of today is 10.0:
![image](https://user-images.githubusercontent.com/5672408/39258826-8ec2f1ec-487a-11e8-8993-fcc9787cfcfa.png)

The underlying issue has been noted on upath, here:
https://github.com/anodynos/upath/issues/14

To resolve it, we either need to manually specify a different version of node for Travis, or update `yarn install` to use the `--ignore-engines` flag.

**Comment by ianstormtaylor** [comment]
Thanks for the heads up @jasonphillips. Just fixed on master!
