### ISSUE TITLE
add `Decoration` object instead of re-using `Range`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1807]
Right now for `value.decorations` we're re-using the `Range` objects, because they refer to two points with marks. But I think there is more we'll want to do with decorations, and as currently architected any new properties that decorations support have to be added to `Range` which is awkward.

Instead, I think we should separate out decorations into their own `Decoration` model:

```js
new Decoration({
  anchorKey,
  anchorOffset,
  focusKey,
  focusOffset,
  marks,
})
```

This would allow us to add a `data` property holding arbitrary end-user data. And a `key` property holding a unique identifier to identify the decorations across renders/updates.

**Comment by zhujinxuan** [comment]
About `decorations`, do we need `anchorKey !== focusKey`? how about `key, startOffset, endOffset`. I will be much easier in generating leaves (without calling `areDescendantsSorted`)

**Comment by ianstormtaylor** [comment]
@zhujinxuan I think we do. I was considering not needing the “direction” of a range, but I think even that is important if decorations are used for multiple selections. 

Ideally decorations would be keyed somehow though so that they can be easily added/removed.

**Comment by zhujinxuan** [comment]
How about that, 

getDecorationsFromRange( range) => List< Decoration(key1, marks), Decoration(key2, marks), Decoration(key3, marks) ) ... >

We use decorations somehow as internal object.  Though `https://github.com/ianstormtaylor/slate/pull/1801` is a great solution, personally I think things are much easier if we split as different decorations rather a decoration with a range of keys. 

Another advantage is that we can easily compare decorations in componentShouldUpdate

**Comment by ianstormtaylor** [comment]
@zhujinxuan I'm not sure I understand what you mean, can you explain it?

**Comment by zhujinxuan** [comment]
Hi, I am worry about the rendering of `components/text.js` in `slate-react`

<img width="1652" alt="screen shot 2018-05-03 at 4 34 51 pm" src="https://user-images.githubusercontent.com/746159/39601488-0c2566f8-4ef0-11e8-9170-dac914567089.png">

If we have a `startKey !== endKey`, then every text rendering has to know whether the its key is between decoration ranges.  It potentially cause a DFS by number of texts times.  But if decoration key is single, and we split range to a List of decorations by getTextsAtRange, we can use the short-circuit in the changed part `if (startKey === endKey && startKey !== text.key) return isDecorated = false`.  It is only as complex as one DFS. 

That is why I think, at least in rendering, we perhaps shall have decorations as a set of Records with single keys.

**Comment by ianstormtaylor** [comment]
@zhujinxuan ah interesting, that sounds like a cool optimization to do at render time. It might also be something we could do in the data model itself, but I'm not sure. Feel free to explore here if you want... about to write up some new ideas too...

**Comment by ianstormtaylor** [comment]
I think we should actually change `Decoration` to be slightly more like marks, and make them a separate concept...

Right now we're using `Range` and `Mark` in combination via `range.marks`. This is nice, but we're missing a few different abilities that would be nice. For example:

- It would be good to be able to reference decorations easily, to be able to remove or update them as things change. The current implementation just has a `value.decorations` which isn't keyed by anything, or typed in any way, so plugins can't know which ones to remove/update if the state changes.

- It would be good to be able to associate arbitrary data with decorations. Right now technically this is possible via using `range.marks`, but it feels hacky.

Also right now, you're almost always going to just have a single mark inside the decoration's marks, so we're not really gaining anything there.

I think instead, we need a separate object...

```js
Decoration {
  anchorKey: String,
  anchorOffset: Number,
  focusKey: String,
  focusOffset: Number,
  type: String,
  data: Map,
}
```

It instead becomes a new object, that offers range-like properties and mark-like properties. This way you could have a "search highlight" decoration for example:

```js
Decoration.create({
  type: 'search_highlight',
  ...
})
```

Or you could use them to represent multiple cursors:

```js
Decoration.create([
  type: 'cursor',
  data: {
    user_id: '...',
  }
})
```

And be able to reference them easily. And since they have `type` and `data`, you can replace/update them as they change too. They would be updated the same way that marks are, with `addDecoration`, `removeDecoration`, `replaceDecoration` change methods.

cc @jasonphillips since he was working in this area recently too.

**Comment by zhujinxuan** [comment]
What is the difference between decoration and mark?  Do you mean we can have `renderDecoration` function?

**Comment by ianstormtaylor** [comment]
@zhujinxuan yup, we would introduce a `renderDecoration` prop for rendering them. The difference is that they are applied to ranges of the document without affecting the document’s data directly, versus marks which are applied to the text itself.

**Comment by jasonphillips** [comment]
>  - It would be good to be able to reference decorations easily, to be able to remove or update them as things change. The current implementation just has a value.decorations which isn't keyed by anything, or typed in any way, so plugins can't know which ones to remove/update if the state changes.    
>  - It would be good to be able to associate arbitrary data with decorations. Right now technically this is possible via using range.marks, but it feels hacky.

These are issues I've had to work around recently (basically: updating a large set of decorations essentially requires dropping / rebuilding them since no consistent id exists; and we attach data to them but it ends up looking like `decoration.marks[0].data` everywhere, which isn't pretty). So I think a new type of Object to handle these in a more focused way than Range+Mark sounds great.
