### ISSUE TITLE
https://glamorous.rocks/ component in renderNode causes memory issue

### ISSUE THREAD

**Issue by matt-erhart** [ianstormtaylor/slate#1809]
Drops into a debug mode in file called clean.js or crashes chrome. Sorry for the format, got to post before I step out or I'll forget about it. I just switched back to styled components and that's fine, but something weird is happening and you should probably know. Feel free to close.

**Comment by tobiasandersen** [comment]
Without more info I'm afraid it's hard to do anything constructive here. I'd also suggest maybe it's an issue with glamorous (or at least the use of it). If you could post a small example that highlights the issues with slate, feel free to re-open :)

**Comment by matt-erhart** [comment]
https://codesandbox.io/s/409rxn0my7 see line 45 of index.js. Be ready to crash your browser.
