### ISSUE TITLE
Give marks a way of declaring that they are mutually exclusive with other marks

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1814]
#### Do you want to request a _feature_ or report a _bug_?

Feature 

#### What's the current behavior?

Currently there isn't a great way to deal with marks that are mutually exclusive with other marks, and it leads to people continuously reinventing the wheel to deal with this sort of issue.

A perfect example of this is with text color. Typically people will try to implement text color as a mark, either with a mark specifically for the color or a mark that is a generic color mark that has the color in the data property (can elaborate but don't feel like this is completely pertinent to the suggestion).

Ultimately though users still have to do something like
1. Check whether the range contains a color mark already.
2. Remove the color mark on the range where the new color mark will be applied.
3. Apply the color mark.

There are some variations to this, but it'd be nice if Slate did this automatically.

#### What's the expected behavior?

We should consider adding a slate schema property for marks that indicates that 1. they belong to a certain 'family' of marks, and that only one mark of that 'family' can exist on a given leaf of text at one time.

Names pending, that might look like this:

```
const schema = {
   marks: {
      types: [
          { type: 'bold' },
          { type: 'color-blue', family: 'color' },         
          { type: 'color-red', family: 'color' },
          { type: 'color-green', family: 'color' },
      ],
   },
}
```
or also equivalent but more concise
```
const schema = {
   marks: {
      types: [
          { type: 'bold' },
          { type: 'color', family: 'color' }, // would be used if the data property has the color
      ],
   },
}
```

In the above schema examples, we could declare that the 'color' mark types belong to the 'color' family, and that there should only be one mark of the 'color' family applied to the text at one time. When slate detects that this condition is violated, it could then remove the old conflicting mark and apply the new one in its place at the specified range.

**Comment by zhujinxuan** [comment]
It is too complex to add to the current codebase. 
I would suggest, `marks {type: isDeepCompare:.. }`.

**Comment by ianstormtaylor** [comment]
I'd be curious to hear if there are any use cases where you want specific "families" of marks that isn't just "this mark should only occur once". I assume it's mostly the uniqueness case, and in that case I'd think that it could be represented as something like:

```js
const schema = {
  marks: {
    color: {
      isUnique: true,
    }
  }
}
```

**Comment by CameronAckermanSEL** [comment]
I thought about that, but that would force people to use a pattern where they have the color stored in the mark data as opposed to just having a mark type for each color. I think for this specific example of color, having the color hex in the data is the vastly preferred pattern, but there might be a case where they'd want to have different mark type names and have them associated with each other.

But for this color case, the `isUnique` flag would definitely work very well.

**Comment by CameronAckermanSEL** [comment]
Yeah you know, I think you're probably right. I spent a while thinking about it and bounced it off a few other folks I work with and we couldn't come up with anything. So the simplicity of the `isUnique` would be welcome.

**Comment by danielstaleiny** [comment]
is there a example on how to create mutually exclusive marks and blocks ??? I have a case where you can add font 12-18 and align block left-center-right and they have to be unique in that sense :)).

**Comment by majelbstoat** [comment]
I'd also like to see a solution for this. I do a lot of `removeMark(oldMark).addMark(newMark)` in my codebase. I would even settle for `removeMark` only taking the string type and removing anything that matched, regardless of data, e.g. `.removeMark('attribution').addMark({type: 'attribution', data: {})`

**Comment by ianstormtaylor** [comment]
I believe there’s an old issue about allowing remove mark to take a string. If someone wants to make a PR I’m happy to break backwards compatibility for that. 

And also happy to merge a PR that implements the `isUnique` feature discusses above.

**Comment by ianstormtaylor** [comment]
I believe this is no longer applicable now that marks are removed and `slate-schema` is removed. People can achieve these things in their own custom `normalizeNode` functions.
