### ISSUE TITLE
Error in core.js - char is undefined

### ISSUE THREAD

**Issue by ctrlplusb** [ianstormtaylor/slate#182]
It doesn't seem to break the editor.

Happens with basic text typing events.

<img width="798" alt="screenshot 2016-07-27 13 29 52" src="https://cloud.githubusercontent.com/assets/12164768/17175249/4ff97e62-53fe-11e6-9574-3497380908d9.png">

**Comment by ianstormtaylor** [comment]
Thanks for reporting! I've got t fixed locally and will push it live soon! Happens on first character of new blocks.

**Comment by ianstormtaylor** [comment]
Fixed in `0.7.8`, thanks for catching this!
