### ISSUE TITLE
Bug: Strange insertion of a period in text after double spaces in certain places... it's like an easter egg.

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1820]
Go to [this example](http://slatejs.org/#/plain-text)

Put the cursor after the "s" in the first word, "This".

Then press the spacebar twice. A `". "` will be inserted at the cursor.

So the text changes from

```
This is editable plain text, just like a <textarea>!
```

to

```
This .  is editable plain text, just like a <textarea>!
```

Even though all you do is press spacebar twice.

I get this unexpected behavior in all text blocks.

Perhaps this was some debugging for AutoReplace that wasn't removed in production?

**Comment by davidchang** [comment]
I think you may just be running into custom Mac behavior: https://www.tekrevue.com/tip/macos-sierra-add-period-double-space/ . I was able to reproduce it on a Macbook inside of the Notes app.

**Comment by tashburn** [comment]
@davidchang Wow, you're right. I didn't know about this mac feature, which was enabled by default for me (even thought it's apparently not supposed to be enabled by default). Closing this issue.
