### ISSUE TITLE
More Real Benches

### ISSUE THREAD

**Issue by benjycui** [ianstormtaylor/slate#1821]
Actually, slate's benches is too simple.

I think that we should test `value.document` with 1000+ descendants, and we need to test several edge cases for each API, such as:

```jsx
document.getParent(first.key)
document.getParent(middle.key)
document.getParent(last.key)
```

cc @ianstormtaylor @zhujinxuan 

Ref: https://github.com/zhujinxuan/slate/pull/3

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
