### ISSUE TITLE
when I use slate in mobile env,once I input words,the words will show,but no triggle change function, no modify value,

### ISSUE THREAD

**Issue by HereSinceres** [ianstormtaylor/slate#1826]
#### What's the current behavior?

![default](https://user-images.githubusercontent.com/11225986/39703639-477496f4-523b-11e8-897f-956fa993e0f8.gif)

**Comment by vshia** [comment]
I think you're encountering the same problem described in https://github.com/ianstormtaylor/slate/issues/725

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
