### ISSUE TITLE
Can Page-Header,Page-Footer,Multi-Page be supported?

### ISSUE THREAD

**Issue by sunjingwu** [ianstormtaylor/slate#1828]
## request a feature 

I want create a webapp like google doc with function like Multi-Page, can slate be used?
Any Suggestions for me?

**Comment by Erklik** [comment]
This seems more of a question rather than a feature request. Suggest you ask here : https://slate-slack.herokuapp.com/

**Comment by tobiasandersen** [comment]
As @Erklik says, the Slack channel is a better place for stuff like this :)
