### ISSUE TITLE
Selection is visually collapsed on click outside of editor

### ISSUE THREAD

**Issue by alexeychikk** [ianstormtaylor/slate#1835]
#### Do you want to request a _feature_ or report a _bug_?
bug (not sure)

#### What's the current behavior?

Selection is visually collapsed on click outside of editor but it's actually not collapsed as shown on gif. It has only lost focus.

https://jsfiddle.net/fj9dvhom/349/
https://drive.google.com/file/d/1i2OWR_9eWlfdrcL2gSFGIEXMM72L8pTK/view?usp=sharing
Windows 10
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Slate v0.33.4

#### What's the expected behavior?

Probably the selection should be collapsed in JS or maybe it should not be collapsed visually.

**Comment by alexeychikk** [comment]
Seems like it's the expected behavior. I used `selection.isCollapsed || selection.isBlurred` instead to achieve what I need.

**Comment by tobiasandersen** [comment]
Glad you solved it! And yeah I think the current behavior makes sense :)
