### ISSUE TITLE
Quickest way to wrap just selected text in a block?

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#184]
I know there is probably a way to do this easily, however I am getting tripped up with transforms and selections.

I know about `wrapBlock()` however it wraps the entire block and not just the selection. I desire functionality like `wrapInline()` where only the portion of the block that is in the selection is wrapped. How might I accomplish this in a single transform?

**Comment by ianstormtaylor** [comment]
Good question! I don't believe there's a way to do this in a single transform, at least not right now. What are you using it for? Just curious for thinking through the use case.

But off the top of my head I think you could do:

```js
const { selection } = state
const next = state.
  .transform()
  .splitBlockAtRange(selection.collapseToEnd())
  .collapseToStart()
  .splitBlock()
  .wrapBlock(...)
```

Not the simplest, but you have to split at the end block first, because if you split at the start first you might end up splitting the current node before the ending point, invalidating the current selection.

It's not amazing that `wrapBlock` and `wrapInline` have different splitting methods, but when I wrote `wrapBlock` that seemed like the most common way you'd want it. Perhaps they both need a `{ split: true }` option or something. (Although they'd need to take the depth as well.)

**Comment by tyler-johnson** [comment]
Ah yes the `.splitBlockAtRange(selection.collapseToEnd())` is what I believe I was missing. I will make another attempt at this tomorrow. I am still a novice at this immutability stuff and it didn't occur to me that I could transform the content without moving the selection around. Thanks.

As for the use case, I am looking for alternative ways to solve #178. I was thinking that perhaps the popup could be embedded in the document next to the inline text it is linked to. Since the popup content will require block nodes, I assumed that all the parent nodes would need to block nodes as well. Truthfully an Inline node would fit better. So I guess this leads to another question: Can Inline nodes contain Block nodes as children?

---

Personally I think the functionality of `wrapBlock` and `wrapInline` are to be expected as the documentation describes them as "Wrap the {Inline/Block} nodes in the current selection". To me that says that *no* splitting of blocks or inlines will take place at the selection boundaries and new nodes will simply wrap the existing ones. Additionally, it makes sense that `wrapInline` would split Text nodes when there are no inline nodes to wrap. I would expect the same functionality from `wrapBlock` if the document just had text nodes but it seems like documents always contain blocks.

Perhaps you could add two new methods with names like `wrapRangeWithBlock` and `wrapRangeWithInline`?  Interestingly these could have the added benefit of wrapping *inside* the current block or inline instead of wrapping on the outside (assuming that's how `wrapBlock` and `wrapInline` work currently).

**Comment by tyler-johnson** [comment]
So I have implemented what you had suggested, and it is close to what I am looking for not exactly right. Perhaps there are some limitations around what sort of siblings a block node can have, I'm not sure.

What I am looking to create from a serialized standpoint is structure that looks like this. If before the transform I have this:

```yaml
nodes:
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        text: before word after
```

I am looking to turn it into this:

```yaml
nodes:
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        text: before
      - kind: block
        type: paragraph
        nodes:
          - kind: text
            text: word
      - kind: text
        text: after
```

Notice the inner block is surrounded by text nodes. Is this possible? Totally fine if it is not as now that I attempt to explain it I realize there may be some issues with it. 😆

As for the `splitAndWrapBlock` and `splitAndWrapInline`: I will definitely try implementing them!

**Comment by ianstormtaylor** [comment]
Ah yeah, blocks can only have either `Block` children or `Inline/Text` children, but not mixed. I would say that this is not enforced very well anywhere right now though. Need to add it in to `.normalize` to make it truly enforced, good call!

**Comment by tyler-johnson** [comment]
Okay no problem thanks for clarifying this!
