### ISSUE TITLE
Double-clicking word with mark selects only part of the word

### ISSUE THREAD

**Issue by alexeychikk** [ianstormtaylor/slate#1840]
#### Do you want to request a _feature_ or report a _bug_?
Bug.

#### What's the current behavior?
Selection by double-click is not working properly on word with mark, it selects only part of word instead of the whole word.
https://jsfiddle.net/fj9dvhom/351/
https://drive.google.com/file/d/1IUdhTjrxe5bi3A9ZCWOB5fMSQ1sWE_KL
Windows 10, Chrome 66.0.3359.170 (Official Build) (64-bit), slate v0.33.6"

#### What's the expected behavior?
When you double-click word with mark - the whole word should be selected, not just its part.

**Comment by alexeychikk** [comment]
Cannot reproduce this bug anymore.

**Comment by alexeychikk** [comment]
I was able to reproduce it again but only in **production** mode.

**Comment by alexeychikk** [comment]
It happens not only to words with mark(s) but also for some regular text.

**Comment by kode-ninja** [comment]
Same here. Chrome 72 on Win 10.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
