### ISSUE TITLE
renderEditor only works in plugin, not in Editor

### ISSUE THREAD

**Issue by klis87** [ianstormtaylor/slate#1841]
#### Do you want to request a _feature_ or report a _bug_?
Potential bug or not update doc

#### What's the current behavior?
`renderEditor` doesn't work when defined as `Editor` prop, only as plugin.
See https://jsfiddle.net/fj9dvhom/352/

#### What's the expected behavior?
`renderEditor` should be added to implicit `editor` plugin and called, currently it is ignored

**Comment by luolonghao** [comment]
these tags of Toolbar should be inserted before Editor.

```
render() {
    return (
    	<div>
        <div>Toolbar</div>
        <Editor
          placeholder="Enter some text"
          onChange={change => this.onChange(change)}
          value={this.state.value}
        />
  	  </div>
    )
  }
```

**Comment by klis87** [comment]
I could, but then I wont have access to editor related props, and anyway according to docs using `renderEditor` should be possible.
