### ISSUE TITLE
Very slow with both decoration and search highlight

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1843]
#### Do you want to request a _feature_ or report a _bug_?

bug 

#### What's the current behavior?

copy from the huge document, paste to the search highlight example, try to search anything in search box. It will consume about 5 seconds to highlight.
After hightlight, keys like enter, insert text will takes about 0.5 seconds to re-render

**Comment by zhujinxuan** [comment]
Perhaps, characters/leaves will partially solve the problem

**Comment by zhujinxuan** [comment]
I do some break point tests, most time is consumed by 
```
    const children = document.nodes.toArray().map((child, i) => {
      const isSelected = !!indexes && indexes.start <= i && i < indexes.end

      return this.renderNode(child, isSelected, childrenDecorations[i])
    })
```

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
