### ISSUE TITLE
Bug: insert Chineses characters made links error

### ISSUE THREAD

**Issue by Durianicecream** [ianstormtaylor/slate#1848]
#### What's the current behavior?

![screenshot](https://user-images.githubusercontent.com/16221326/40220466-ca8ce97e-5aab-11e8-94fb-ca59df2d8af1.gif)

the link disappear when I enter a chinese character  
it looks like a rendering error, beacause I cheked the Value it seems right

**Comment by SmilinBrian** [comment]
Pretty sure this is the same issue as #1829

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
