### ISSUE TITLE
Drag dropping a node between branches crashes

### ISSUE THREAD

**Issue by alaindresse** [ianstormtaylor/slate#1850]
#### Do you want to request a _feature_ or report a _bug_?

A bug

#### What's the current behavior?

Dragging a node between two editors generates the error "Could not find a node with id ...".

See https://codesandbox.io/s/q9lyy6k5mq for a codesandbox reproducing the issue. See also the following gif illustrating the issue.

I first show drag drop works within same editor, then I try to drag the image node between editors.

![slateissue](https://user-images.githubusercontent.com/1415531/40233525-a5b4f50e-5aa3-11e8-94b5-49181518e0a2.gif)
 

#### What's the expected behavior?

Dropped node should be copied to the new editor.

**Comment by bryanph** [comment]
I know draft.js solves this by having a unique key for every draft editor and checking onDrop whether the keys match (in which case the block should be moved).

As I see it there are these two cases:
1. Drag within editor: slate-editor-key is equal => move_node
2. Drag between editors: slate-editor-key is different => insert_node at the target (clone the node at the target)
