### ISSUE TITLE
check that `props.attributes` are spread in development

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1853]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Right now you'll get errors like:

```
Uncaught Error: Unable to find a DOM node for "19". This is often because of forgetting to add `props.attributes` to a custom component.
```

Which often mean that you forgot to mix in `{...props.attributes}` into your rendered component. It's kind of annoying to track these down though, and easy to forget.

#### What's the expected behavior?

Instead, in development we could just check in `componentDidMount` whether the `attributes` were mixed in, and warn much earlier to avoid those cryptic errors.

Not only that, but it would be nice to improve the error to show the `object` and `type` of the node to make tracking down the error easier. Something like:

```
Uncaught Error: Unable to find a DOM node for "quote" block with key "19". This is often because of forgetting to add `props.attributes` to a custom component. Check the render function of your "quote" block.
```

**Comment by zhujinxuan** [comment]
Use slate-dev-logger as the logger?

**Comment by zhujinxuan** [comment]
Then perhaps we need to use ref or ReactDOM.findDOMNode here?

**Comment by ShiroYacha** [comment]
Hi @ianstormtaylor ,
I have a question, I am spreading `props.attributes` on the top level of my custom component but i still run into a lot of problems when my custom component created some new elements at runtime (i.e. creating some inline editors or some libraries that have some DOM manipulation). Then I got the error with data-key different then that of the props.attributes one... 

I also try to set `isVoid: true` but I am still getting exceptions like this, and it's causing crashes... Is there something I did wrong?

**Comment by eroepken** [comment]
I'm having the same issue as @ShiroYacha, except when I add `isVoid: true`, I'm not seeing the error, but I'm not getting my desired result, which is to be able to edit the content in that component.

No matter how I send in the attributes, unless I specify that this is a void component, it kills the editor.
![screen shot 2019-02-26 at 11 06 00 am](https://user-images.githubusercontent.com/502492/53427687-65ba0900-39b7-11e9-98a8-92d9611fbcf0.png)

**Comment by ianstormtaylor** [comment]
I think unless other libraries with DOM props start doing this, we should consider it out of scope.
