### ISSUE TITLE
change `Model.create` to `new Model`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1855]
#### Do you want to request a _feature_ or report a _bug_?

An improvement.

#### What's the current behavior?

Right now to create models, we use a static `create` method, like so:

```js
const block = Block.create({
  type: 'paragraph',
  nodes: [...],
})
```

#### What's the expected behavior?

But this is kind of confusing—it's easy to forget and to try to use `new` instead. It would be nice if we could deprecate them. I can't remember why I went with `create` in the first place. But if someone did research into Immutable.js and found out that it was possible for us to just subclass them and override the `constructor`, it would be nice to be able to do:

```js
const block = new Block({
  type: 'paragraph',
  nodes: [...],
})
```

**Comment by zhujinxuan** [comment]
A problem is that Text.create can use the interface of Text.fromJSON, and Text.fromJSON converts the array to list, then use the interface new Block

If we use new Block as the only interface, it seems we have to move the `Array` to `List` (which shall be in Block.fromJSON) into the constructor as well.

**Comment by zhujinxuan** [comment]
Do you mean something like this: https://github.com/ianstormtaylor/slate/pull/1856

**Comment by zhujinxuan** [comment]
But there is still a problem: Block.create do not need to call super when attrs is a Block, saving some time.  
https://github.com/facebook/immutable-js/issues/964#issuecomment-283282006

**Comment by ianstormtaylor** [comment]
> If we use Block.create, then Block.isBlock(attrs) is faster.

@zhujinxuan wow, that's good to know! I didn't realize there was a penalty for using `new` like that, very interesting. In that case it sounds like we should stick to the `.create` methods instead.

Unless we could actually do `Block({})` with nothing to mimic Immutable more. That sounds like it would be the ideal?

**Comment by ianstormtaylor** [comment]
(Also it might be worth waiting until Immutable.js `4.0` since it sounds like they will change things a little to make it more clear.)

**Comment by zhujinxuan** [comment]
@ianstormtaylor We cannot do `Block({})` because ES6 requires class constructor can only be called with new, and extended constructor must have `this` and `super`.  The immutable-js uses a babel plugin to overwrite the babel's `createClass`, which allows calling class contructor like a function.


https://stackoverflow.com/questions/32619382/why-do-immutable-js-classes-not-require-new

**Comment by ianstormtaylor** [comment]
But does using `new` for Immutable records result in the same slow performance? Should be using `Block({ ... })` internally too? In other words, does removing the `new` in our existing `create` static methods improves performance?

As for eliminating `new` or `create` publicly, it sounds like we might need to see what Immutable.js does in 4.0 and then copy them.

**Comment by zhujinxuan** [comment]
Hi, I think we shall use `Block.create()` internally.   

1. Unfortunately, ES6 does not allow `Block({...})`. `Immutable` did that by using their own transpiler rather than babel-preset-env.
2. The easiest way to eliminate most `new` is like this:
```
let EMPTY_BLOCK
function getEmptyBlock() {
  if (!EMPTY_BLOCK) EMPTY_BLOCK = new Block()
  return EMPTY_BLOCK
}
class Block extends Record(DEFAULTS) {
    static create(attrs = {}) {
    if (typeof attrs === 'string') {
      attrs = { type: attrs }
    } else if (Block.isBlock(attrs)) {
      return attrs
    } else if (!isPlainObject(attrs)) {
      throw new TypeError('attrs must be string, plain object or Block')
    }
    return getEmptyBlock().merge(Block.getAttrsFromJSON(attrs))
  }
}
```

**Comment by ianstormtaylor** [comment]
@zhujinxuan ah nevermind, sorry I missed something. I realized that you can actually do:

```js
const Block = Record({ type: String, ... })
const block = Block({ type: 'paragraph', ... })
```

And it works. But only if you don't want to extend `Block` with other methods. Otherwise you'd need to use `class ... extends` to be able to augment the prototype. (Although I wonder if there was a way we could achieve the same thing by changing the prototype directly... not sure.)

But since we need to do add methods, you're right we have to use `new`. Oh well!
