### ISSUE TITLE
Chrome android: when long pressed delete error

### ISSUE THREAD

**Issue by damaera** [ianstormtaylor/slate#1857]
On chrome on android device.

Open slatejs.org, or another editor which use it, like: https://framesia.com/try-editor

try to type some text then delete it with long press delete. until `text.length === 0`

The error happens in each node with the same message:
```
Error: Unable to find a DOM Node for "N".
This often because of forgetting to add `props.attributes` to a custom component
```

**Comment by raymestalez** [comment]
Same here. It happens when you delete a block.
![slate-bug](https://user-images.githubusercontent.com/4761235/40426061-f5229c6e-5e4e-11e8-9da8-046722e189ee.png)

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2062, if you think this is unrelated let me know and we can reconsider.
