### ISSUE TITLE
Bug occurs when USING IME.

### ISSUE THREAD

**Issue by marszhou** [ianstormtaylor/slate#1861]
Thank you for your great job. I'm glad that Slate is a lot easier of using than Draft-Js.

I found this bug when I use Chinese IME on MacOSX (I consider that other language which is input by IME will also cause the same problem, not verified).

You can duplicate it by doing this:

ex: 

- Add 3 blocks, and every block contain some letters.
- Then select multilines.
- Then type a letter when Chinese IME is active.
- Then press spacebar or return key, exception comes out.

> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

https://jsfiddle.net/fj9dvhom/1/

![](https://ws3.sinaimg.cn/large/006tNc79gy1frnqyzu8hlg30hs0b4x4g.gif)

**Comment by tommoor** [comment]
I've seen the same issue on Chrome 68 - I don't think this is exclusive to IME in any way: 

![image](https://user-images.githubusercontent.com/380914/40912202-dfb19690-67be-11e8-9299-96fd6b8f175f.png)

**Comment by SmilinBrian** [comment]
I think this is fixed by PR #2218

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
