### ISSUE TITLE
Drag and drop does not remove original text/block

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1871]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When a selected fragment is dragged then dropped into another location of the editor, the original selected fragment is not removed.

http://recordit.co/6NMojTC5Cp

 The current behavior results in duplication of text, and in some cases the extra blocks left behind can cause problems if there are any unique identifier keys stored in the data property.

#### What's the expected behavior?

The original fragment is removed.

**Comment by CameronAckermanSEL** [comment]
Can currently be suppressed with a plugin that does

```
{
  onDrop: (event, change) => {
    return change;
  },
},
```

**Comment by gggdomi** [comment]
```
if (isDraggingInternally) {
  change.delete()
}
```
 in `slate-react/src/plugins/after.js` line 234 must be the culprit, coupled with the `isDraggingInternally = false` in `onDragOver` (line 167) that disable deletion
