### ISSUE TITLE
Published Slate UMD modules are out of date

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1872]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

In several Slate published packages (I checked `slate-dev-environment` and `slate-react`), the files in `dist/` are out of date with the files in `lib/`. For example, `dist/slate-dev-environment.js` is missing the `IS_OPERA` constant added in v0.1.2. The constant is included in the same package's `lib/slate-dev-environment.es.js`.

You can test this yourself by `npm i slate-dev-environment`, and inspecting the installed files.

(BTW, this could be why we've been seeing bugs that have been fixed, still reproducible in the test fiddle).

#### What's the expected behavior?

For any published package version, files in dist/ and lib/ should be generated from the same version of the source files.

**Comment by davidchang** [comment]
dupe of https://github.com/ianstormtaylor/slate/issues/1767, one of these could be closed
