### ISSUE TITLE
Copy paste introduces zero-width spaces for empty blocks

### ISSUE THREAD

**Issue by gggdomi** [ianstormtaylor/slate#1877]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

When copy-pasting an empty block, it includes a zero-width character

![recordrtc-201855-7tdis3yoask](https://user-images.githubusercontent.com/11262934/40976041-29b6407e-68cd-11e8-9a99-e97f1ff8866a.gif)

Chrome 67 on macOS 10.12

#### What's the expected behavior?

Empty blocks should be pasted as empty lines.

I believe this has been introduced with #1815.

**Comment by tobiasandersen** [comment]
I've made a fix for this in https://github.com/ianstormtaylor/slate/pull/1865.

**Comment by gggdomi** [comment]
That was fast, thanks @tobiasandersen! I submitted an useless PR meanwhile, closing it.
