### ISSUE TITLE
Chinese input - slate crashes with "Unable to find a DOM node..." in certain cases

### ISSUE THREAD

**Issue by k7d** [ianstormtaylor/slate#1879]
How to repeat (on OS X 10.13.4, Chrome 66):

1) Open [Slate example editor](http://slatejs.org/#/rich-text)
2) Select Pinyin - Traditional input source
    ![image](https://user-images.githubusercontent.com/181645/41053816-d9c20ef6-6979-11e8-9c02-c8a2ed6c5e8c.png)
3) In a new line type A, A, 1, then select the 2 just inserted characters and type A, A, 1 again
4) Slate crashes with `Error: Unable to find a DOM node for "10". This is often because of forgetting to add props.attributes to a custom component.`. See the gif below:

![composition-crash](https://user-images.githubusercontent.com/181645/41053924-2bb5d936-697a-11e8-9671-931d6ba9ed22.gif)

**Comment by kulukyo** [comment]
I've the same issue. It happens when a whole selected line is about to be replaced.

![20180613_141832](https://user-images.githubusercontent.com/38679950/41333651-26b6186a-6f15-11e8-99c3-5f90bccea1b2.gif)

**Comment by zhujinxuan** [comment]
@k7d @kulukyo I was investigating that issue.  The strange thing is that the chinese input method does not trigger onInput or onBeforeInput, but triggers onChange.

I will work on that when I have time.  Perhaps four weeks later at least.

**Comment by yunwuxin** [comment]
It's still like that.

@ianstormtaylor
