### ISSUE TITLE
ctrl+backspace throws an error at line start

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1887]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?
In http://slatejs.org/#/rich-text:
Using Mac, when `ctrl+backspace` at beginning of line, it will throw an error in "http://slatejs.org/#/rich-text"

#### What's the expected behavior?
Do nothing when `n===0`

**Comment by zhujinxuan** [comment]
Strange, I cannot reproduce it now.  I did that a few minutes ago but I cannot reproduce the problem at this moment.

**Comment by zhujinxuan** [comment]
My mistake, it is ctrl+delete not cmd+delete;

I am working on that.

**Comment by zhujinxuan** [comment]
Fixed in #1888 1888

**Comment by thesunny** [comment]
@zhujinxuan I think this is the exact same bug I ran across when backspacing in Android but it's just failing to catch a different type of backspace.

https://github.com/ianstormtaylor/slate/pull/1935#issuecomment-400079031

**Comment by zhujinxuan** [comment]
@thesunny Can you have a try on whether https://github.com/ianstormtaylor/slate/pull/1888 fixes the bug in Android?

**Comment by thesunny** [comment]
I'll check this when I get back from vacation. I don't have a virtual Android set up on my laptop and all the stuff I'm travelling with are iOS devices.

**Comment by zhujinxuan** [comment]
Close this PR because it will be fixed in #1888
