### ISSUE TITLE
Code coverage analysis

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1890]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

SlateJS is complex enough, and is requiring tests.  But we cannot clearly know which part of code are not tested yet.  Code coverage can help us find out untested code in `packages/src/slate`

#### What's the expected behavior?
I think it will be good to have coveralls.io introduced in slate.  However, only maintainer/owner can set up code coverage analysis in coverall.io. @ianstormtaylor @Soreine @SamyPesse

**Comment by zhujinxuan** [comment]
I find how to do that.  I will submit a code coverage PR this weekend.

**Comment by ianstormtaylor** [comment]
Thanks @zhujinxuan!
