### ISSUE TITLE
Documentation is missing for Leaf

### ISSUE THREAD

**Issue by travigd** [ianstormtaylor/slate#1906]
#### Do you want to request a _feature_ or report a _bug_?
Documentation issue.

There is no documentation for the `Leaf` model, including associated methods like `Text.getLeaves()`.

**Comment by RXminuS** [comment]
Sorry if it's not great, but though i'd just get a PR started since I was working on the Typescript definitions anyways.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
