### ISSUE TITLE
Feature request: More granular readOnly control - Selection vs Content

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1909]
It would be great if setting `readOnly` still allowed changes to selection, or if there was another option to allow modifying only the selection but not the text.

This is achievable most easily (though not safely if you're saving changes) in the interim by setting all of the elements in the editor to use the following CSS, and setting `readOnly` to false;

```
 .yourEditor * {
      -webkit-user-modify: read-only;
      -moz-user-modify: read-only;
      user-modify: read-only;
  }
```

**Comment by ianstormtaylor** [comment]
Fun fact, just discovered that there is sort of a semi-precedent for this with the `contenteditable` attribute being spec'd to take multiple different values: https://w3c.github.io/editing/contentEditable.html#editing-states

**Comment by Slapbox** [comment]
Huh I never knew there were settings besides true.

I forget why exactly this was an issue. One would assume selection would still be available even if it was `readOnly`, right? Is `readOnly` set via `contentEditable="false"` or some other method? Is there something Slate is doing that disables selection?

For all my time working with `contentEditable`s, I've never really dove that deep into the finer points.

**Comment by isubasti** [comment]
looks like for now the accepted values for contentEditable for now are only `true/false`. the [w3c.github.io/editing/contentEditable.html#editing-states](w3c.github.io/editing/contentEditable.html#editing-states) is still a draft

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
