### ISSUE TITLE
support custom schema normalize iteration limit

### ISSUE THREAD

**Issue by intellild** [ianstormtaylor/slate#1919]
It is really a pitty to make it compatible with old data produced by other editors, like this:
![default](https://user-images.githubusercontent.com/8379858/41633550-156ee688-7472-11e8-8cf0-0cbc05b817e9.png)
and it is difficult normalize it with very limited iterations (for now it's plugin counts plus one)

**Comment by intellild** [comment]
https://github.com/ianstormtaylor/slate/blob/1cc486e28c88593bdae04bc4161b28a962c78d33/packages/slate/src/changes/with-schema.js#L97-L101 

Sorry for my bad English, I mean make the `max` here customizable.

**Comment by ianstormtaylor** [comment]
@intellild can you explain what the data is and why it takes so many normalization passes? I agree with you that `schema.stack.plugins.length + 1` seems pretty arbitrary.

Do you have an idea for how it should be customized?

**Comment by intellild** [comment]
@ianstormtaylor 
If my schema looks like this:
```js
 {
  document: {
    nodes: [
      {
        types: [
          'paragraph',
        ],
      },
    ],
    normalize(change, reason, { node, child }) {
      switch (reason) {
        case CHILD_TYPE_INVALID:
          return change.setNodeByKey(child.key, 'paragraph')
      }
    },
  },
};
```
and got a data like this:
```html
<div id="1">text</div>
<div id="2">text</div>
<div id="3">text</div>
```
after the first iteration the document is still invalid (`div#1` -> `p#1`), and in next iterations `#2` and `#3` will be nomalized.
If the document is large, it is easy to result in `A schema rule could not be validated after sufficient iterations.`

**Comment by intellild** [comment]
I think add a property in the schema object is reasonable, eg:
```js
const schema = {
  iterationLimit: 50,
  document: {
    // ...
  }
}
```

**Comment by ianstormtaylor** [comment]
@intellild the maximum iterations logic was changed to be wider now, does it help you?

**Comment by intellild** [comment]
@ianstormtaylor legacy data is really a pitty so I wrote normalize functions by hand, thanks a lot anyway
