### ISSUE TITLE
Selecting behaviour on check list item

### ISSUE THREAD

**Issue by laurensiusadi** [ianstormtaylor/slate#1920]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

https://www.slatejs.org/#/check-lists.

I want to select all check-lists, I can only select one.

![2018-06-18_14-42-50](https://user-images.githubusercontent.com/5661040/41523980-0fa6ddcc-7306-11e8-81ea-c4d80d4a6413.gif)

#### What's the expected behavior?

Select between list item like normal bullet list or numbered list

![2018-06-20_12-21-57](https://user-images.githubusercontent.com/5661040/41638654-b7683234-7484-11e8-9418-65a0cd8ccbc2.gif)

**Comment by justinweiss** [comment]
I think this happens because, in the demo, the enclosing `div` is marked `contenteditable=false`. If only the checkbox `span` is marked `contenteditable=false`, I think this will work correctly -- at least, it did when I was messing with it in Web Inspector!
