### ISSUE TITLE
Link preview on mouse click

### ISSUE THREAD

**Issue by matthewberkompas** [ianstormtaylor/slate#1936]
#### Do you want to request a _feature_ or report a _bug_?
Request a Feature

#### What's the current behavior?
Currently, you can create a link by selecting some text in the editor, clicking the hyperlink button, inputting the desired URL and clicking save. However, when you put your curser on the text that is hyperlinked, no preview of the URL appears like you would expect. 

#### What's the desired behavior?
When you create a link and then place your cursor over the hyperlinked text, a preview of the link should appear so you can actually see where the link leads without opening it.

Is this available already but just undocumented or is there an external solution people are using? Thanks in advance!

**Comment by tobiasandersen** [comment]
Hi, this is definitely possible to do, but you have to implement it yourself. I'd suggest asking in the [Slack channel](https://slate-slack.herokuapp.com/) instead!
