### ISSUE TITLE
Collaborative editing how do I read the change.operation value from the backend and render?

### ISSUE THREAD

**Issue by lingxiao** [ianstormtaylor/slate#1937]
I am connecting a `slate.js` component with firebase realtime database towards collaborative editing. Right now I have a simple master-slave setup between two editors that are from two different accounts. The master account reads the `change` in the `onChange` function and save the `change.operations` in the firebase realtime database. the slave account should `readChange` the database and write the value to the `state.value`. However currently I am not sure how to call the slave's `writeChange` function so that the slave renders the updated text from the master. The naive solution of putting the `writeChange` function in the `onChange` listener crashes the app on load. Code below: 

    export class SlateContainer extends Component {
    
      	constructor(props){
    
    		super(props);
    
    		this.state = { value  : initVal
    			         , pid    : '' 
    			         , master : false
    			     	};
    
    	}
    
    	// set master slave status. user prop is loaded
    	// as a consumer context from another container
        componentWillMount(){
    
        	const email = this.props.user.email;
    
        	if (email === 'master9@gmail.com')
        		this.setState({ master : true })
    
        }
    
    
    	// after mounted, load project
        componentDidMount(){
    
    		const name = 'slate-project';
    
    		this.state.master 
    		? this.loadMasterProject(name)
        	: this.loadSlaveProject (name);
    
        }
    
    
        // load project if exists, else create one
    	loadMasterProject = async (name ) => {
    		// load project from master perspective
    	}
    
    
    	loadSlaveProject = async (name) => {
    		// load as slave
    	}
    
    	onChange = change => {
                 
                // the bug is here: if I run readChange from the slave side
               // then the app crashes on load. what works is just: 
             // `this.state.master ? this.writeChange(change) : false`
    		this.state.master
    		? this.writeChange(change)
    		: this.readChange()
    
    	}
    
    	writeChange = (change) => {
    
    		const ops = change.operations
    			.filter(o => o.type !== 'set_selection' && o.type !== 'set_value')
    			.toJS();
    
    		this.setState({ value : change.value });
    		Project.save( this.props.user.id, this.state.pid, JSON.stringify(ops))
    	}
    
    
    	/**
    		Listen to server for change and apply value. where would I call this function?
    	*/
    	readChange = () => {
    
    		const id  = this.props.user.id;
    		const pid = this.state.pid    ;
    
    		firebaseApp.database().ref('path/to/project-id').on('value', snap => {
    
    			const raw_ops = snap.val().delta;
    			const ops = JSON.parse(raw_ops);
    			const value  = this.state.value;
    
    			// this throw the error on load
    			// const change = value.change().applyOperations(ops);
    			// this.setState({ value : change.value });
    
    		})		
    	}
    
    	render (){
    		return (
    			<Editor className='editor'
    				value     = {this.state.value}
    				onChange  = {this.onChange}
    				onKeyDown = {this.onKeyDown}
    			/>
    		)
    	}
    }

Note the data is properly passed through the realtime db, so this is not a firebase db problem.

**Comment by ianstormtaylor** [comment]
Hey @lingxiao, we can't answer detailed questions here, but check out the `#collaboration` channel in the Slack for people who may be able to help.

**Comment by ccorcos** [comment]
It would be nice to followup here so others don't have to signup and go hunting through Slack :)
