### ISSUE TITLE
Edge with input method produces random characters

### ISSUE THREAD

**Issue by intellild** [ianstormtaylor/slate#1940]
#### What's the current behavior?
Can be reproduced with
https://www.slatejs.org/#/plain-text

1. detele all text. so we can see the placeholder
2. input whatever with an input method
3. some random characters come out
![qq20180627-103741-hd](https://user-images.githubusercontent.com/8379858/41949929-497e6492-79f6-11e8-9fde-8ff84c055480.gif)
Windows 10
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

#### What's the expected behavior?
No random characters.

#### My work around
in renderPlaceholder:
```jsx
  if (editor.state.isComposing) {
    if (IS_EDGE && !editor.props.value.document.text) {
      // noop
    } else {
      return;
    }
  }
```

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
