### ISSUE TITLE
CloneFragment throws errors on IE11

### ISSUE THREAD

**Issue by Dtphelan1** [ianstormtaylor/slate#1941]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Copying plain text in IE causes multiple errors, rooted in code found in `slate-react/utils/cloneFragment` that is not cross-browser compatible. Specifically: 
1.  Line 36: `contents.childNodes.forEach` and Line 62: `contents.querySelectorAll(ZERO_WIDTH_SELECTOR)).forEach` produce the error `SCRIPT438: Object doesn't support property or method 'forEach'`.  This is because NodeList.forEach is [not supported on any versions of IE](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility).  
2. Line 93: ` event.clipboardData.setData(TEXT, div.textContent)` produces the error `SCRIPT65535: Unexpected call to method or property access.`. This is because, while setData is defined for IE, it's only valid arguments are 'Text' and 'Url'; we pass 'text/plain'. 

Neither the JSFiddle nor the example pages loaded for me on IE11, so I can't include a link to that, but I imagine any rudimentary fiddle implementing the editor would expose these bugs, as I've traced them back to the `cloneFragement` function present in slate-react.
 
Information re: the system that reproduces the bug: 
- OS: Windows 10, version 10.0.16299 
- Browser: IE11
- Slate: 0.34.0

#### What's the expected behavior?
Basic copying of the text.

#### Possible Solutions:
1. Wrap any NodeLists in the `Array.from()` function to ensure that all these objects are arrays, which do have a [forEach function defined in IE>=9](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Browser_compatibility). *Concern:* this may have some performance impacts, but I'm not familiar with how resource intensive this operation is.
2. On Line 91 we have a condition check for deciding whether or not we should use the `setData` function. Since this function throws an error on IE, we should change the condition to ensure the browser isn't IE. That is, add this import to the top of the file: `import { IS_IE } from 'slate-dev-environment'` and replace Line 91 with `if (event.clipboardData && event.clipboardData.setData && !IS_IE) {`.

**Comment by ianstormtaylor** [comment]
Hey @Dtphelan1 thanks for this. We do this with a handful of methods that older versions of IE don't support, and instead ask that people who need support for older browsers being their own polyfills to handle these things. (`NodeList.forEach`, `el.closest`, etc.)

It sounds like Polyfill.io has an open issue for someone to add support, in case that's the one you'd like to use: https://github.com/Financial-Times/polyfill-service/issues/1233

**Comment by Dtphelan1** [comment]
Thanks for the feedback! For what it's worth, these are issues with the most recent version of IE, making this is a compatibility issue with IE11 as a current, up-to-date browser, not an issue with outdated, older versions of IE. If you'd still like to pass on those just let me know and I'll remove those changes from my PR!   
  
  
  
 Thanks again for the response.   
  
  
  
  

  
  

  
  
>

**Comment by ianstormtaylor** [comment]
Hey @Dtphelan1, yeah anything that can be polyfilled that the majority of modern browsers already support should be, that way Slate can continue to maintain a small bundle size for most people.

I'll accept IE11 compatibility fixes, but only for internal logic, where it isn't something that can be fixed by just bringing your own polyfill.

**Comment by Dtphelan1** [comment]
Thanks for the info, having a clearer understanding of your motivations helps me paint a more detailed picture of what’s at play. I’ll work on fixing up my PR once in back at a computer!   
  
  
  

  
  

  
  
>
