### ISSUE TITLE
refactor to make `shouldNodeComponentUpdate` part of core plugins

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1947]
There's no reason the current `shouldNodeComponentUpdate` logic couldn't just be part of the `after.js` plugin, which would make it completely override-able by end users in their own plugins.

**Comment by RXminuS** [comment]
Isn't it already like that? The shouldNodeComponentUpdate seems to be looked up from the plugin stack. Can't you just supply a function there? Or is that not what you mean

https://github.com/ianstormtaylor/slate/blob/e4ff1972d79911baf8a6aed683765b66107b09a4/packages/slate-react/src/components/node.js#L67

**Comment by ianstormtaylor** [comment]
We want to get rid of this thing anyways, so we can close this.
