### ISSUE TITLE
Off-by-one errors in getMarksAtOffset()

### ISSUE THREAD

**Issue by majelbstoat** [ianstormtaylor/slate#1954]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

```js
const old = text.characters.get(i).marks
const new = text.getMarksAtIndex(i)
```

These two methods have an off-by-one difference, where `text.getMarksAtIndex` returns the marks before the character, not of the character.

#### What's the expected behavior?

I would expect `text.getMarksAtIndex` to give the same result as `text.characters.get(i).marks`.

Repro case is here: https://jsfiddle.net/fj9dvhom/1234/
(Open the console to see the difference)

Confirmed happening in slate 0.34.3-0.34.5.

**Comment by zhujinxuan** [comment]
For this function, this function serves `getMarksAtRange` and `getMarksAtPoint` that obtain marks by the Range. 
Then for n characters, there is potentially n+1 marks to obtain for this function. 

I remember all text functions are range/point prior than characters.(for convenience of rendering, deleting and modifying)  So....

**Comment by majelbstoat** [comment]
That makes sense. (Ironically, I'm trying build the inverse, `getRange(s)OfMark`)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
