### ISSUE TITLE
Delete selection marked text doesn't work correctly

### ISSUE THREAD

**Issue by befront** [ianstormtaylor/slate#1955]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

In the example above: https://www.slatejs.org/#/rich-text.

If you for example write some text with bold mark and then select all text and click backspace only the text is deleted and mark not be reseted. It only reproduces if you select and remove more than one character. 

#### What's the expected behavior?

Delete selection text move to deleting mark.

**Comment by zhujinxuan** [comment]
It is expected, I think.  

I implement this feature for this case: some users select all and mark with `font-size: 16px` or `font-family: times-new-roman` and expected the mark will be the default mark.  For example:
```
<b>
<paragraph>Cat</paragraph>
<paragraph>is</paragraph>
<paragraph>cute</paragraph>
</b>
```

Suppose user delete the `is` and then insert, the user may expect the text is a bolded region, and would like to have the insert text bolded. 

Similar happens on the first and last paragraph.  Therefore I implement the marks for empty text feature.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
