### ISSUE TITLE
Setting focus and selection with toggleMark destroys mark

### ISSUE THREAD

**Issue by uipoptart** [ianstormtaylor/slate#1962]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Programmatically setting selection and/or focus at the same time as toggleMark results in the newly applied mark being lost.

http://g.recordit.co/wi96Bp20tk.gif
https://jsfiddle.net/321nvc4k/

Mac OS 10.13.5
Google Chrome 67.0.3396.87
Slate version: Using forked current JS fiddle to reproduce

#### What's the expected behavior?
The editor will take focus with the desired selection. Typing will result in text with desired mark applied. 

#### When this matters
If a user tries to select font family, size, etc before clicking in the editor the controls will appear as if they don't work.

**Comment by Soreine** [comment]
In the JSFiddles, it does not actually update the selection at all.
