### ISSUE TITLE
Cursor positioned incorrectly in Chrome when next to a large void inline node

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1963]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

Fiddle here: https://jsfiddle.net/fj9dvhom/1308/

In Chrome, if you place the cursor to the right of the image, it shows up in the wrong place:

<img width="691" alt="2018-07-09 at 3 32 pm" src="https://user-images.githubusercontent.com/1020/42479363-5e4dacd4-838d-11e8-9f2b-5db1679e5c2b.png">

#### What's the expected behavior?

In Safari, the cursor fills the entire height of the image. In Firefox, it shows up next to the text. Either of those would be fine, I think.

The problem seems to be the `contentEditable=false` on the void node -- when contentEditable is true, Chrome has the same behavior as Safari, with a cursor filling the entire height.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
