### ISSUE TITLE
Select All, Backspace doesn't work

### ISSUE THREAD

**Issue by t3chguy** [ianstormtaylor/slate#1983]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

If your selection starts at the start of the editor and is expanded, and you press Control Backspace
(as in you're doing Control A, Backspace too quickly and don't let go of Control quickly enough) it won't remove anything and instead just collapses the focus left. This does not match regular text field/textarea behaviour.
![slate](https://user-images.githubusercontent.com/2403652/42875234-2682ddfc-8a7b-11e8-96bf-9478b7701d36.gif)

#### What's the expected behavior?

Same behaviour as `<textarea>`/`<input/>` where it removes the selection anyway.

**Comment by zhujinxuan** [comment]
The control-backspace has a bug, and it will be fixed in https://github.com/ianstormtaylor/slate/pull/1888

**Comment by seunggs** [comment]
There's still a bug regarding this - if the first node in the editor is a list then select all + backspace will not delete the list wrapper (ul/ol) which makes it impossible to erase the list wrapper.

**Comment by meedwire** [comment]
> Ainda há um bug em relação a isso - se o primeiro nó no editor for uma lista, selecione todos os + backspace não excluirá o invólucro da lista (ul/ol), o que torna impossível apagar o invólucro da lista.

Any update on this issue?
