### ISSUE TITLE
Performance issues with normalizeNodeAndChildren

### ISSUE THREAD

**Issue by drewler** [ianstormtaylor/slate#1986]
#### Do you want to request a _feature_ or report a _bug_?

Report a _bug_

#### What's the current behavior?

For a certain inputs containing many nodes and marks (around 3000 nodes in the provided example), Slate is taking a very long time to process (about 10 seconds in the provided example). This behaviour is caused by normalization performed at the `normalizeNodeAndChildren` function. Inside it, iterations over the immutable node lists consume most of the time. Javascript is blocked until normalization ends, making the UI unresponsive. Immutable seems to be the core of the issue.

You can see an example here: https://jsfiddle.net/drewler/ojv7t3rp/

Browser: Chromium 67.0.3396.99
OS: Linux (Arch Linux)
Slate version: 0.34.5 (also tested with 0.32)

![normalizeNodeAndChildren](https://i.imgur.com/2PLA63f.png)

`normalizeNodeAndChildren` running

![iterate](https://i.imgur.com/BATU2XP.png)

Multiple calls to `iterate`

#### What's the expected behavior?

The input should be processed without taking that much time. Maybe I'm missing a workaround?

**Comment by zhujinxuan** [comment]
Have you turned on the memoize cache?  The normalization is speeded up by memoizing the `validate` function in `model/node.js`.

**Comment by ianstormtaylor** [comment]
A lot of this logic has changed in recent releases of Slate. The performance for first-run normalization is still much slower than it could be if someone invested some time in it. But I'm going to close this since it's out of date. Feel free to open new peformance issues with specific steps.
