### ISSUE TITLE
how to merge adjacent block nodes?

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#199]
I cannot seem to merge block nodes once they are split. I think I am on the right track but I'm not sure if there are bugs preventing this or if I'm totally off.

I am attempting to implement logic that merges list blocks after an item in the middle of the list is deleted. As you can see in this GIF, the rich-text example will split block when a list-item is removed:

![output](https://cloud.githubusercontent.com/assets/310038/17229649/e24db602-54d5-11e6-90df-c9f373a5b086.gif)

I have attempted this a few different ways, none of which have panned out.

#### First Attempt

1. Remove the empty line
2. Unwrap and rewrap the two nodes together

This first attempt failed to do the complexness of selections and transforms. I know that should be possible, but it tough to make modifications to state without messing with selections.

#### Second Attempt

1. Get a fragment of the second list.
2. Insert the fragment into the end of the first list.
3. Remove the second list and the empty line between them.

On this second attempt, I have a line of code like `document.getFragmentAtRange(selection.moveToRangeOf(nextBlock))`, but I get the error of `Uncaught TypeError: Cannot read property 'take' of undefined`. I can't tell if thats a bug or if I am just calling the methods incorrectly. Either way, I can't past the first step.

**Comment by ianstormtaylor** [comment]
Definitely a bug, just fixed in `0.9.1`.

Problem was that internally `delete` needs to split at both selection edges, but it was splitting up the the `document` level, instead of to a `commonAncestor` level, which was the reason a second list wrapper was being created.
