### ISSUE TITLE
Version on documents

### ISSUE THREAD

**Issue by antherkiv** [ianstormtaylor/slate#1992]
#### Do you want to request a _feature_ or report a _bug_?
__feature__

#### What's the current behavior?
The documents are not versioned, it could be very useful, for example in cases where some functionality stops to work due to breaking changes (it allows to write custom parser to handle the values before injecting it to he editor)

Cheers.

**Comment by bryanph** [comment]
This could go together with some sort of migration tool that automates migrating between schemas.

**Comment by ianstormtaylor** [comment]
This sounds useful, but it seems outside the scope of Slate's core to me. Versions can currently be managed by folks on their own, and might include their own schema-specific concerns, and stored with the documents.

**Comment by ianstormtaylor** [comment]
Closing because of ^ that it's outside of Slate's concern. But you can definitely have versioning in your own data model however you store it.
