### ISSUE TITLE
Limit decorateNode() to only the focused line?

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1998]
Any thoughts on passing the `editor` prop to `decorateNodes` for the purpose of scoping decorations to the currently selected block? I'm sure there are other use cases as well.

**Comment by ianstormtaylor** [comment]
Hey @Slapbox please search for the other issues that asked for `value` to be passed down. It's not possible as currently architected, because of memoization.

**Comment by Slapbox** [comment]
@ianstormtaylor understood. Thanks very much as always for taking the time to reply.
