### ISSUE TITLE
'Plugins' example not working

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#200]
(Continuing my regular QA of examples for some reason) Found that all three cases with that example (on Mac, Chrome 52) were not working for me.

1. The auto-replacer functionality doesn't work.

2. Selecting some text and pressing escape doesn't do anything either.

3. Pressing 'enter' is supposed to do a soft return but it doesn't seem to be doing anything.

Recent breakage, maybe?

**Comment by yrezgui** [comment]
<img width="521" alt="screen shot 2016-07-29 at 08 39 42" src="https://cloud.githubusercontent.com/assets/1113976/17233129/39ed2bee-5568-11e6-9259-8f478977c089.png">

**Comment by ianstormtaylor** [comment]
Ah, forgot to bump the versions of the plugins in `devDependencies` after updating them for the breaking changes `0.8.0`. Fixed live now, thanks!
