### ISSUE TITLE
make `mapRanges` usage smarter

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2003]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the expected behavior?

Following from https://github.com/ianstormtaylor/slate/pull/1993#issuecomment-408546270 it would be nice if the `value.mapRanges` uses could be made smarter. It should be possible to calculate what the next `anchorPath` and `focusPath` should be for all of those updates instead of setting them to `null` to be re-calculated in `Range.normalize` by using the `key -> path` mapping (which can be slow to compute).

**Comment by jtadmor** [comment]
taking a look at this right now.

fwiw, it does look some behavior was broken for `selection` based on the one test i have added so far (not sure if that has to do with how the test is set-up, possibly not calling `Range.normalize` in the `operations` tests).

**Comment by ianstormtaylor** [comment]
Moving away from even having this logic exposed, and it can be made more performant as an internal helper in core instead as needed.
