### ISSUE TITLE
Selecting all and then checking whether the value isEmpty throws

### ISSUE THREAD

**Issue by kalley** [ianstormtaylor/slate#2004]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

Go to: https://www.slatejs.org/#/hovering-menu

Click inside and <kbd>command+a</kbd> (or <kbd>ctrl+a</kbd>) to select all. You'll see an error.

This is coming from `value.isEmpty` being called in the check. I'm not sure what should change though.

#### What's the expected behavior?

Expected behavior would be that it selects all and does not error out.

**Comment by linonetwo** [comment]
Try https://deploy-preview-1985--slatejs.netlify.com/#/hovering-menu
Seems to be fixed in https://github.com/ianstormtaylor/slate/pull/1985 by @zhujinxuan

**Comment by steida** [comment]
@linonetwo For some reason, the fix does not work in my app.

**Comment by zhujinxuan** [comment]
Try https://github.com/ianstormtaylor/slate/pull/1888?

**Comment by steida** [comment]
It looks like number passed where a string is expected. Btw, what is the difference between isCollapsed (which works) and isEmpty (which fails for now)?

**Comment by zhujinxuan** [comment]
I think it is perhaps related to https://github.com/ianstormtaylor/slate/pull/1997.

**Comment by kalley** [comment]
I think I've narrowed it down to [`getFragmentAtRange`](https://github.com/ianstormtaylor/slate/blob/638d3e8e61c7f52b09e2860729710061e5601c5f/packages/slate/src/models/node.js#L695) not passing a `path` to `splitNode`. I'm still getting up to speed with `path`s, so wanted to put this here in case someone sees a quick fix.

**Comment by zhujinxuan** [comment]
@kalley splitNode is not a change method.  (It is a method under the same model/node.js....) . I think the error is perhaps from somewhere else.

**Comment by kalley** [comment]
This is not about a change method. This is about `value.isEmpty` being called after a change action in an component update call. So you have to follow the call stack from `value.isEmpty`, which is how I figured that the while loop is passing a number to `splitNode`. I just don't know enough about `path`s yet to figure out what should be happening.

**Comment by steida** [comment]
isCollapsed is quick workaround, working isEmpty would be better ofc.

**Comment by ianstormtaylor** [comment]
Fixed by #2012, thanks for reporting @kalley.
