### ISSUE TITLE
Add ability for `renderMark` to return a React component

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#201]
Following https://github.com/ianstormtaylor/slate/issues/188, it would be nice to be able to use full-fledged components as mark renderers. This would make re-using styles a lot easier, but also allow for things like styling marks on `:hover`, etc.

**Comment by SamyPesse** [comment]
👍  an example of usecase is the [prism](https://github.com/SamyPesse/slate-prism) plugin, which currently can't use the CSS class from Prism's themes.

I'll try to make a PR to fix this issue.
