### ISSUE TITLE
add `Node.createRange` method

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2011]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Right now when you want to create one-off ranges, you use `Range.create()` and pass in the anchor/focus properties manually. But this is error prone, and the range you create isn't guaranteed to be "valid" for the document you need it for. This is especially true now that ranges contain both keys and paths, which should be in sync.

#### What's the expected behavior?

Instead, it would be good to add a `Node.createRange` method, such that you can pass in either paths or keys. And you can pass in either block node keys or text node keys. All of the logic currently in `Range.normalize` could be controlled helpfully by the node instead. 

```js
const range = document.createRange({
  anchorKey: 'a',
  anchorOffset: 1,
  focusKey: 'b',
  focusOffset: 37,
})
```

In almost all situations you have access to the document you want to create a range for, so this would make things easier.

And then we can quit doing `range = range.normalize(this)` when accepting `range` arguments for the other node methods, which can be unnecessarily expensive when the range is already known to be valid, and instead enforce that the user provide valid ranges.

And, nicely enough, this mimics the existing DOM API of [`Document.createRange`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createRange).

**Comment by zhujinxuan** [comment]
I think we can have `Document.createRange()` in `model/document.js`.  For blocks and inlines, it seems that we cannot get the path of the range.

**Comment by ianstormtaylor** [comment]
@zhujinxuan I agree that it makes most sense in terms of documents, but I think artificially restricting it isn't necessary. Since the lower-level nodes can actually use relative ranges if they want to. I don't think there's anywhere we do it in core, but it's simpler to keep things consistent I think.
