### ISSUE TITLE
Wrong import for 'react-portal'

### ISSUE THREAD

**Issue by jfrolich** [ianstormtaylor/slate#2017]
The `Portal` is imported as a default import: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editor.js#L2

This probably works with the non-es version of the package, however if you use the es-bundle this will crash the build. The correct way to import 'react-portal' is (https://github.com/tajo/react-portal/blob/master/README.md):

```
import { Portal } from 'react-portal';
```

Changing this, will fix the build.

**Comment by ianstormtaylor** [comment]
I think it might be because we're using an older version of `react-portal`?

**Comment by jfrolich** [comment]
That was what I thought as well, but the version in the package.json is: `"react-portal": "^3.1.0",`, which is the latest (major) version. Also I went back in the history of react-portal and the export code did not change for a long time (at least a year). 

It's probably a mistake that slipped in, that didn't cause issues when the code is transpiled.

**Comment by isubasti** [comment]
yarn.lock has both version 3 & 4, that is why it's not working properly

**Comment by zhujinxuan** [comment]
If it is upgraded to react-portal 4, we are dropping the support of react v15.

I do not think it is good at this moment.

**Comment by jfrolich** [comment]
It's not, it includes backward compatibility for React 15.x.
