### ISSUE TITLE
input text inside an inline block

### ISSUE THREAD

**Issue by yeuem1vannam** [ianstormtaylor/slate#2019]
#### Do you want to request a _feature_ or report a _bug_?
**bug**

#### What's the current behavior?
I'm trying to add an inline input where user can insert value into. Basically it looks like
![image](https://user-images.githubusercontent.com/2409560/43506256-7f2184f2-95a4-11e8-8768-e0506c990a1c.png)

However, when user type the text inside the inline input, the cursor jump to outside
![Image from Gyazo](https://i.gyazo.com/c2de20b1cb38ee8a0f05ed76dce7304e.gif)
When checking the DOM, we can see that the value is inserted into next `Text` node instead of the `Text` node inside the inline input.
![slate](https://user-images.githubusercontent.com/2409560/43507041-f8fa9d70-95a6-11e8-899a-f25c7702fce5.png)
You can check it on https://jsfiddle.net/yeuem1vannam/Lvsn3exy/

**UPDATE**
I checked the example on mobile device, it works as expected. 
https://youtu.be/kSm1-mWONPU
You can visit a clone here
https://yeuem1vannam.github.io/slate/#/inline-input

#### What's the expected behavior?
The cursor should be stay inside the inline input, and the value added to the children `Text` block

**Comment by alfechner** [comment]
I've exactly the same problem. Any update on this?

**Comment by zhujinxuan** [comment]
@alfechner Not yet according to my knowledge, but you can write a plugin to correct selection by cursor position.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
