### ISSUE TITLE
deprecate `Value` shortcut properties

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2028]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Right now there are a handful of "shortcut" getters defined on `Value` objects, for example `startKey` or `endBlock` or `anchorText`. The idea behind adding these was that they were common use cases, and it would make writing things a lot more terse to be able to de-structure them directly from `value` instead of dropping into the `document` or `selection`.

However, I think some of them are actually resulting in slightly more confusion, since it's not always clear exactly what is returned (eg. `startBlock`, `endInline`). And for others, the shortcut doesn't save you that much but it does complicate the API and makes deprecations slightly harder.

#### What's the expected behavior?

I think we should just deprecate and then later remove all of them. Specifically there are a handful of different groups of shortcuts...

There are selection shortcuts:

```js
const { startKey, anchorPath, endOffset } = value
```

These can be pretty easily changed to:

```js
const { selection } = value
const { startKey, anchorPath, endOffset } = selection
```

And then there are the node shortcuts:

```js
const { anchorText, startBlock, endInline } = value
```

These are slightly more verbose, but can be changed, and end up more clear since you can see the actual getter used on the `document`:

```js
const { document, selection } = value
const { anchorPath, startPath, endPath } = selection
const anchorText = document.getNode(anchorPath)
const startBlock = document.getClosestBlock(startPath)
const endInline = document.getClosestInline(endPath)
```

(You're also free to use the `assert*` variant of the getters for cases where you don't want to bother with handling `null` values, which the current shortcuts can't do. In general they're going to be more flexible.)

Finally, there are also the "weird hard to understand shortcuts" like:

```js
value.isEmpty
value.isInVoid
```

Which aren't clear at first glance exactly what they do. (`isEmpty` happens to mean either collapsed or with an empty amount of text. And `isInVoid` happens to mean a collapsed selection that is inside a void node.)

All of these removals would make future iterations on the library easier, since the same decisions aren't made in multiple different places. And it would make `Value` objects more of a thin wrapper around their data.

I'd be curious to hear others's thoughts here as well.

**Comment by justinweiss** [comment]
It'd be a widespread change for us, but I think it's worth it.

**Comment by ianstormtaylor** [comment]
As of #2102 everything but the "node shortcuts" from above are deprecated. I'm not sure about the node ones, since they are useful and are a combination of information that `Value` is uniquely in the position to offer. I'm going to close for now since this is mostly done, but we can revisit the others later.
