### ISSUE TITLE
consider dropping IE11 support at some point

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2029]
#### Do you want to request a _feature_ or report a _bug_?

Debt.

#### What's the current behavior?

There are IE11-specific hacks in the codebase, and it's really becoming an outdated browser. [Thread on Twitter.](https://twitter.com/jamiebuilds/status/1022568918949408768) Khan Academy officially dropped support for it.

The thing is, for non-rich text behaviors, supporting IE11 isn't as hard, since you can just polyfill things like `el.closest` or whatever. For but rich-text, you need proper copy/paste support, proper range creation/updating support, proper input event support, etc. Things that are much harder, if not impossible to polyfill.

#### What's the expected behavior?

Not a current priority, but at some point in some amount of months it'll probably make sense to drop support for it and remove the IE11 hacks from the codebase. This will be even more important as we look to start supporting the newer `beforeinput` event APIs.

**Comment by schneidmaster** [comment]
Totally understand the motivations here, but I'd love if we could at least just extract the hacks into a separate package or something. If you're using Slate in any sort of enterprise software then the reality is that you're still stuck supporting IE11 probably until Microsoft kills it (it's still a double-digit percentage of browser share for users in corporate environments, most of whom are restricted from using a better browser by security policies).

**Comment by mike-hewitson** [comment]
Wow. While I also understand, we've also got the challenge of supporting IE11 as well. On that vein, I cannot open slatejs.org in IE11, so it looks like compatibility is already gone/compromised? All other browsers (including Edge 15) seem fine.

**Comment by nikushx** [comment]
@mike-hewitson I believe that's because the main Slate package won't include the polyfills for IE11, you need to add them yourself

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
