### ISSUE TITLE
consider adding `set*` methods for all properties

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2030]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Right now the Immutable.js `.set` and `.merge` methods are still used for some cases (eg. setting `anchorKey` on a range, or `isVoid` on a node) by users as the public API. They're not really encouraged at all, but not explicitly discouraged.

But I think this isn't great because it makes things harder to validate/migrate when APIs change. For example, if `isBackward` is removed, there's no way to offer a deprecation warning if people are doing `range.set('isBackward', false)` because it will just error out.

#### What's the expected behavior?

Instead, it might be nice for all models to expose setter methods of `.set*()` for each of their properties, that can be the canonical way to change properties in a low-level manner. This way they can have type validations, normalizations, etc. since they are custom methods.

For example:

```js
range.setIsFocused(true)
```

```js
node.setNodes(nodes)
```
```js
value.setDocument(document)
```

Or in the newer `Range/Point` combination:

```js
range.setAnchor(anchor)
```
```js
point.setOffset(offset)
```

They are still low-level, and rarely used, but they are at least standardized and more flexible in terms of versioning/improving the API over time.

**Comment by Dundercover** [comment]
Is it not possible to override `set` with our own that can warn for properties we deprecate? It might be better usability to have explicit methods like you proposed though but a custom `set` might be easier to implement and maintain?

**Comment by Dundercover** [comment]
I tried overriding the `set` method in all classes that extends `Record` (and added a deprecation warning) but the problem is that `set` is used internally by `immutablejs` in `deleteIn` and `setIn` so as long as we use those methods, `set` needs to work as it does in its current form. With that said, we only use those methods at one place each so it might be possible to just to roll our own solution for those use cases.

**Comment by Dundercover** [comment]
@ianstormtaylor what do we do with `merge`?

**Comment by ianstormtaylor** [comment]
I think we might want to punt this one and just get rid of the need for confusion when we migrate to plain objects instead.

**Comment by Dundercover** [comment]
Sounds good @ianstormtaylor, let me see if I can salvage anything I've written so far. I did write custom implementations of those single use cases where we used `deleteIn` and `setIn`, maybe those could be useful if we are moving away from `immutablejs`?

**Comment by Dundercover** [comment]
I'll just stash it for now, it might very well not be needed at all depending on the solution we're replacing `immutablejs` with (if we're using `immer` then I don't think we need anything from this).

**Comment by ianstormtaylor** [comment]
Yup, not going to end up needing this. Once we drop Immutable.js in favor of using `immer` we won't need to have setter functions at all!
