### ISSUE TITLE
Code Highlighting Example - Select dropdown option text is included in text selection

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2034]
In the [code highlighting example](https://www.slatejs.org/#/code-highlighting), selecting the text of the document also selects the text of the dropdown options.

[Issue demonstration](http://recordit.co/5OOU7cctM1)

This occurs because the `Select` element gets wrapped up into the selection. This occurs even if you set the element's CSS to `user-select: none;`

![image](https://user-images.githubusercontent.com/6835891/43654860-b6019dbe-971a-11e8-9097-84a9b916610b.png)

I'm running into issues related to this issue in my application. Is there some way to exclude items like this from the selection? If not, is there a better way to go about rendering elements like this in the editor?

**Comment by ianstormtaylor** [comment]
Interesting, I’m not sure. Portals probably? But I’d be curious if someone found a way without portals too since they are often a pain to manage.

**Comment by Slapbox** [comment]
Even `display: none;` on the select box doesn't remedy this... Crap...

The options I see are:

1. Process out the data on clipboard copy
2. Use portals

Portals seem like the best option, and perhaps there is no better option available, though if anyone has an idea I'm all ears.

**Comment by Slapbox** [comment]
@ianstormtaylor what do you think of adding a specific `data-` tag which will be excluded via `cloneFragment`? Something like `data-slate-exclude-from-selection`.

This isn't exactly pretty, but it seems likely to be much more maintainable for the community than requiring portals to avoid this.

**Comment by Slapbox** [comment]
Okay so rather than the clunky solution above, we could also consider using the HTML serializer if people pass their preferred serializer rules to the `editor` as a prop. 

This would produce pretty darn good results I think, however it might cause issues in cases where people have used the HTML serializer to serialize objects in a weird way. For example, I serialize my `checkboxes` to `labels` for the purpose of saving.

Is it better to integrate such a solution into Slate, or to leave it to the user to implement a filter like this themselves on the clipboard data?

**Comment by ianstormtaylor** [comment]
Maybe omitting anything with `contenteditable=false`? But I think the first step would be to prove that there's no way around this with styling/etc. first in JSFiddles.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
