### ISSUE TITLE
Mirroring changes from an editor to another causes an infinite rendering loop

### ISSUE THREAD

**Issue by codeclown** [ianstormtaylor/slate#2041]
#### Do you want to request a _feature_ or report a _bug_?

Not exactly a bug, but I am curious about the behaviour of onChange locking into an infinite loop.

I was playing around with Slate and wanted to mirror changes from an editor to another, and bumped into an infinite rendering loop (see jsfiddle below).

```js
// Simplified example

class MyEditor extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      value: initialValue,
      mirrorValue: initialValue
    }
  }

  onChange({ value }) {
    this.setState({ mirrorValue: value }) // Mirror change from one editor to the other
  }

  render() {
    return (
      <div>
        <Editor
          placeholder="Enter some text..."
          onChange={change => this.onChange(change)}
          value={this.state.value}
        />
        <Editor
          placeholder="Enter some text..."
          value={this.state.mirrorValue}
          readOnly={true}
        />
      </div>
    )
  }
}
```

(I am aware that this simplified example does not make sense because changes are not updated to the main editor.)

#### What's the current behavior?

Rendering goes into infinite loop.

https://jsfiddle.net/fj9dvhom/1597/

#### What's the expected behavior?

I am not sure if the current onChange infinite loop is intended. I am posting this issue because I want to hear a collaborators take on this. Maybe I'm thinking about the data flow wrong.

**Comment by ianstormtaylor** [comment]
@codeclown rendering the same value in two different editors isn't actually supported because the nodes have `key` attributes that should be unique. I'm not totally sure what's going on with the infinite loop, but I'd first try to make the editors not use the same value object. (Check the "syncing operations" example for ideas.)

**Comment by ianstormtaylor** [comment]
@codeclown I'd definitely consider it, but yeah I'd need some more information to figure out what exactly is causing the infinite loop.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
