### ISSUE TITLE
Fix for Android: Looking for helpers August 13-17 to participate

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2047]
I promised in https://github.com/ianstormtaylor/slate/issues/725#issuecomment-398152295 to spend a week in August to get Android working with Slate. I'll start on Monday August 13 and am looking for collaborators. I'll probably start around 10-11AM PST.

Here's how you can help:

* *Provide Live Feedback Aug 13-17:* To help, just read comments posted in this issue during August 13-17 and provide any insights or ideas. In order to provide better feedback, I recommend reading the relevant resources below (you can skip "Roadmap"). It's a bit of a personal psychology hack but I think better when there is back and forth or even if I have to describe a problem knowing somebody is actually listening.
* *Active Contribution:* I would love it if somebody could actively collaborate with me to work through issues on the week of. You should be willing to set up an Android test environment locally https://thesunny.gitbook.io/slate/v/doc-dev-guides/contributing/android-dev-guide

Here are the relevant resources for background reading (you can skip Roadmap but I leave it here for context)

* Roadmap to Slate Mobile: https://github.com/ianstormtaylor/slate/issues/1720
* Input is wonky on Android Devices: https://github.com/ianstormtaylor/slate/issues/725
* RFC Fix for Android Devices (not merged): https://github.com/ianstormtaylor/slate/pull/1935

*First Approach*
The most progress was made from the PR https://github.com/ianstormtaylor/slate/pull/1935 contributed by @mattkrick who ended up using another Editor but the PR is the closest we've come.

At the time, I recommended declining the PR because depending on whether we had a setTimeout delay or not, it worked in normal gboard but not IME or visa versa.

My first approach will be to see if we can detect IME mode and provide a different delay setting depending on whether IME is active or not.

@ianstormtaylor @Slapbox @mattkrick @zhujinxuan @zaaack @oyeanuj @javan @nathanfu88 @danburzo

**Comment by Slapbox** [comment]
@thesunny are you planning to use @mattkrick's work as a starting point? Specifically: https://github.com/mattkrick/slate/tree/slate-fast

I think this is a great place to start and probably further along than #1935

**Comment by thesunny** [comment]
@Slapbox Yes, I believe #1935 is from slate-fast but for clarity, I'll start with the latest version.

**Comment by thesunny** [comment]
Just a heads up @Slapbox that I'm going to start by filling in the missing bits in the issue posted here https://github.com/ianstormtaylor/slate/issues/2062 as I think helping Ian is the fastest way to move this forward.

If you or anybody wants to jump in, we can coordinate doing this. I'm basically following @ianstormtaylor template and posting things in DropBox Paper.

**Comment by thesunny** [comment]
Closing this issue. There is progress going on and all the updates are happening in https://github.com/ianstormtaylor/slate/issues/2062
