### ISSUE TITLE
Schema normalization doesn't seem to work as outlined in the changelog

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2049]
I'm trying to update my schema, but it seems like the _only_ method for matching that works is to write rules exactly like this:

```javascript
const schemaRules = {
  blocks: {
    list_item: {
      nodes: [
        { match: { type: 'paragraph' } },
        { match: { type: 'ol_list' } },
        { match: { type: 'ul_list' } },
      ],
      normalize: (change, error) => {
        //  Some code
      }
    }
  }
}
```

Trying something like this has no effect:

```javascript
const schemaRules = {
  blocks: {
    list_item: {
      nodes: [{ type: 'paragraph' }, { type: 'ol_list' }, { type: 'ul_list' }],
      normalize: (change, error) => {
        //  Some code
      }
    }
  }
}
```

I tried with the property name `node` and `nodes` but no effect. Am I doing something wrong here? More examples would be great!

**Comment by ianstormtaylor** [comment]
@Slapbox that's correct, the second syntax is the old syntax and isn't valid any more.

**Comment by ianstormtaylor** [comment]
If you're looking to only allow certain types of nodes, it would be:

```js
const schemaRules = {
  blocks: {
    list_item: {
      nodes: [
        { 
          match: [{ type: 'paragraph' }, { type: 'ol_list' }, { type: 'ul_list' }]
        }
      ],
      normalize: (change, error) => {
        //  Some code
      }
    }
  }
}
```

**Comment by Slapbox** [comment]
Thanks for the clarification @ianstormtaylor, I see my misunderstanding now.

This choice makes a lot of sense. Thanks for the constant improvements!
