### ISSUE TITLE
onChange fires multiple times

### ISSUE THREAD

**Issue by bragovo** [ianstormtaylor/slate#2055]
On default demo https://www.slatejs.org/#/history onChange fired many times.
3 times on simple focus (and increase history size), 3 times on any blur. Few times on any modifier like shift.

![mm26f8cxul](https://user-images.githubusercontent.com/822911/43836498-35b496b8-9b1e-11e8-9047-dd94a0734025.gif)

When I add onChange on input field, this function triggered only when value is changed. So I can't detect when content is really changed.

**Comment by zhujinxuan** [comment]
I think it can be fixed by https://github.com/ianstormtaylor/slate/pull/1975

**Comment by bragovo** [comment]
@zhujinxuan thanx for this PR. I tried 0.37 version, but onChange fires at same times. Maybe it's not a bug, because change uses in blur and focus. And onChanges fired when I changing Range.
I think maybe it's normal behaviour, because selection is a part of value. 

But how I can recognise when edited exactly content, not selection? Is it possible to add some flag for it? For example `change.value.isContentChanged` or `change.value.selection.isChanged` and `change.value.document.isChanged` or something like this.

Now I see only one way — manually compare documents from state and Change, but it's really ineffective -(

**Comment by zhujinxuan** [comment]
@bragovo I tried with https://www.slatejs.org/#/history , it seems `slate:editor onChange` fires only one time per rendering.

Can you check the version of slate-react you are using

**Comment by bragovo** [comment]
The last one 0.15.9. Yes, one time then you open this page and one time on any focus and one time on any blur. But content not changed (except selection).. when you open page content initialised, not changed. When you focus editor — Undos +1 (this is bug I think). When you move pointer and change selection onChange fires on any changing symbol.

**Comment by zhujinxuan** [comment]
@bragovo I see.  Currently we stores selection change in history stack and use componentDidUpdate to keep value.selection and dom selection consistent.  I think it is reasonable that selection changes caused `onChange` if someone tries to implement an selection based normalization logic with slate.

**Comment by bragovo** [comment]
Ok, is it possible to recognise selection or content changes?

**Comment by bryanph** [comment]
@bragovo you can compare change.value with the previous change.value. If the reference changed, the value changed.

**Comment by bragovo** [comment]
@bryanph yeah, but how?  `change.value == this.state.values.text` always false, because Value is a big object. I see only two ways compare each element or compare by hash, but is very long operations.
https://stackoverflow.com/questions/201183/how-to-determine-equality-for-two-javascript-objects -

**Comment by zhujinxuan** [comment]
In componentDidUpdate compare prevState.value.document and this.state.value.document

**Comment by bragovo** [comment]
@zhujinxuan thank you, it works for me.

**Comment by z0d14c** [comment]
I hate to perform necromancy here, but... I could be doing something wrong, but the documents are always equal for me ^
