### ISSUE TITLE
Slate data fragments from one editor should not be accepted by another

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2065]
Slate will continue to become more popular and the issue will become that Slate will accept encoded fragments from any source and attempt to merge them into Slate without checking whether they belong as Slate fragments or regular HTML in this particular editor.

This leads to unpredictable paste behavior when pasting data between Slate editors, and could potentially insert malicious data into a node's data structure as well. Primarily though, my concern is formatting. Malicious data seems a very low probability risk.

**I think the best solution for this is including a hash of the schema in the slate data fragment appended to HTML pastes. This would provide a reasonably simple way to ensure the pasted data comes from an editor with the same schema specifications.**

This would also provide `nonce`-like security against potentially malicious data being added to a block's data section. The security provided would be very weak and easily bypassed by someone targeting a particular implementation, but it would be better than trusting all fragments. 

All the same security could be provided via schema rules, but this leaves the onus on Slate users. Like I said though, I see this is a very low risk as is and I'm really more interested in avoiding formatting troubles.

**Comment by ianstormtaylor** [comment]
Sounds good to me, good writeup @Slapbox!

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/1024
