### ISSUE TITLE
don't re-render editor during compositions

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2067]
#### Do you want to request a _feature_ or report a _bug_?

Bug,

#### What's the current behavior?

Right now [we re-render the editor to show/hide the placeholder](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/before.js#L144-L170) during `compositionstart` and `compositionend` events. But this results in the composition being aborted/broken in some IMEs.

#### What's the expected behavior?

We need to change this logic to no re-render the editor, but just re-render the placeholder itself I think. This could be accomplished with some sort of "connected" `<Placeholder>` component I believe, which can be toggled from the plugin code.

This is related to #2062.

**Comment by zhujinxuan** [comment]
Hi, I am not sure why we put isComposing in state.  `this.setState` is not immediate, and can cause re-render.

Is there a special reason of putting isComposing in state?

**Comment by ianstormtaylor** [comment]
@zhujinxuan check out the comments in the source linked above.
