### ISSUE TITLE
[Bug] selection not synchronized between collaborative editors

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#2070]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?
See the gif below with collaborative editing example.
![](http://g.recordit.co/JQGf2wxEO7.gif)
1. select a word in editor one, mark and then demark
2. select another word in editor two, mark.

We can see the mark is operating on the first selected word.

#### What's the expected behavior?

We shall expect the mark is consistent with new selection

**Comment by maikelmclauflin** [comment]
why is this a bug? isn't this something that only happens when 2 editors are in the same document?

**Comment by ianstormtaylor** [comment]
@maikelmclauflin you're absolutely right. I didn't realize that the GIF shows hitting the top editor's bold button, instead of the bottoms editor's. @zhujinxuan this isn't a bug, this is just how that example is implemented. It doesn't sync `set_selection` operations.
