### ISSUE TITLE
Suggestion: simplification for Selection

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2075]
# Selection states
Currently there are three selection states possible:

1. Selection of blocks
2. Selection of inline elements (text and inlines)
3. A combination of the two

My proposed change is to make the third state impossible. This can significantly simplify making changes to the editor and will result in needing a lot fewer operations to make changes to the document.

# Changes

### selecting inline elements within a block
Remains the same as the current behaviour

### selecting blocks
I will use Workflowy as an example because they have the same behaviour as I propose here:
![screencast-workflowy com-2018 08 12-14-31-25](https://user-images.githubusercontent.com/3816712/44002044-b7320aa6-9e3c-11e8-871e-514d7564da16.gif)
As the cursor moves up from the inline elements and moves over to the block that is above it, the selection changes from an "inline selection" into a "block selection". Afterwards, moving the arrow further up just selects other blocks.

I feel like the behaviour shown above is the right behaviour in pretty much all situations. I can't think of a situation where you would want to have a selection anchor and focus with elements at a different hierarchy.  The only situation I can possibly think of is a selection between paragraphs (although this is also very rare in my experience because blocks can still be merged).

Another upside is that with this behaviour it becomes possible to select blocks that contain text nodes. In the current behaviour, it is only possible to select a Node if it has no text nodes (at least from a user perspective).

# ---
So a selection can then either be:

1. a block selection
2. an inline selection

What do you think?

## Advantages
* Greatly simplifies selection handling (determining what blocks are in the selection, etc.).
* Reduces the number of operations needed to apply certain actions (when selecting multiple blocks for example)
* Replaying operations becomes a lot easier
* Better performance due to the above
* ?

## Disadvantages
* There might be some scenarios that warrant a selection of combined inlines and blocks at anchor and focus (although I can't think of any significant ones)
* ?

**Comment by brendancarney** [comment]
I think this would be too restrictive to have as the default, unless I'm misunderstanding. Most text editors allow you to select text between two different blocks, and I think it would be confusing for users to not have selection behave normally.

**Comment by ianstormtaylor** [comment]
Agreed with @brendancarney, this is not something we want to restrict in core, because it's extremely common to want to select across two paragraphs and join them together. This would be something to do in a userland plugin instead.
