### ISSUE TITLE
Node is inserted+removed instead of moved on drag+drop internally

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2076]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
The node is removed and inserted again instead of moved when dragging and dropping blocks within the editor.

As can be seen in the code here: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/after.js#L318

#### What's the expected behavior?
The node is moved

**Comment by bryanph** [comment]
This requires the addition of a change.move() method which moves the selection instead of deleting and inserting it. One question: since there is no "move_text" operation, how should the case of text nodes being selected be handled?

**Comment by ianstormtaylor** [comment]
Hmm that is interesting. I wonder if a `move_text` operation is merited. I think the other operational transform situations I looked at actually didn't cover the drag/drop text case, since they only have `insert/remove` too.

**Comment by clauderic** [comment]
Solved by #4238
