### ISSUE TITLE
How to insert an inline void node (image)?

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#208]
The "Images" example only shows block images, What is the best way to insert inline images?

```html
<p><span>text</span></p>
<p><span>before </span><img src="test.png" /><span>after</span></p>
```

Expending the "Images" example to showcase inline void node would be awesome.

This issue may be related to #23

**Comment by ianstormtaylor** [comment]
Good question! I actually had started adding `insertBlock[AtRange]` and `insertInline[AtRange]` transforms for this purpose but hadn't finished them. Just published `0.10.7` with them finished and document, and the `images` example ported to use `insertBlock({ ... })`.

They're slightly different than what `insertNodeByKey` would be. (It would be very low-level, not splitting or account for the current state at all, basically just a `.push()`.)

Instead, `insertBlock` acts like you'd expect when trying to insert a new block at a location, splitting the blocks as necessary to make it occupy the same depth. (Like the `images` example did previously.)

And `insertInline` acts like you'd expect for inserting inline elements like emoji or similar, splitting the text at the cursor.

Let me know if you run into any issues/ideas with them!

**Comment by Kushan-** [comment]
Hey i am trying to find my way out to inset caption underneath the image. 
`case 'image':{
          const src = node.data.get('src')
          console.log(props)
          console.log(props.editor)
          const { document } = props.editor.value
          //console.log(editor)
          console.log(this.editor)
          return (
            <figure>
              <Image src={src} selected={isFocused} {...attributes} />
              <figcaption>
                <span
      style={{ display: 'inline-block', width: '0', whiteSpace: 'nowrap', opacity: '0.33' }}
    >
      {
       this.editor.props.placeholder
      }
    </span>
                </figcaption>
            </figure> 
          )
      }`

I am using this block of code under renderNode function, but i am not sure how to make span editable. If this is not correct way may you please help me out??

**Comment by jonybekov** [comment]
Hi. Has insetInline function been implemented? I couldn't such functionality from latest version

**Comment by Davidkle** [comment]
@jonybekov it's on version 0.47. It's not on main.
https://docs.slatejs.org/v/v0.47/slate-core/commands#insertinline

@ianstormtaylor was `insertInline` removed for some reason?
