### ISSUE TITLE
Japanese characters break Editor

### ISSUE THREAD

**Issue by jcmitch** [ianstormtaylor/slate#2092]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When typing in Japanese Editor doesn't seem to correctly recognize characters. The text is entered but the cursor jumps to the start of the textarea. As soon as you try and move the cursor and put it at the end Editor gets completely confused and placeholder text returns below the entered Japanese text.

OS: Mac Sierra 10.12.6
Browser: Chrome 68
https://jsfiddle.net/ynb3p94t/2/
![intlbug](https://user-images.githubusercontent.com/6447475/44277461-9bf42000-a1ff-11e8-9ee0-b8687157c9ab.gif)

#### What's the expected behavior?
Japanese text works the same as english or other languages.

**Comment by thesunny** [comment]
Working on this in this issue https://github.com/ianstormtaylor/slate/issues/2062

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
