### ISSUE TITLE
Cursor is placed at start of uncommitted string while composing

### ISSUE THREAD

**Issue by birtles** [ianstormtaylor/slate#2094]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

1. Navigate to https://www.slatejs.org/#/plain-text
2. Focus the text box
3. Activate an IME
4. Type some text
5. Notice that the cursor is placed at the **start** of the string being composed.

Occurs on Windows with Microsoft IME in Chrome 68 and Firefox 63. (I thought I could reproduce in Edge but now it appears to be working correctly in Edge. Odd.)

Firefox:
![firefox](https://user-images.githubusercontent.com/1232595/44298339-14500380-a31c-11e8-9b83-a7461f1501ff.gif)

Chrome:
![chrome](https://user-images.githubusercontent.com/1232595/44298366-a2c48500-a31c-11e8-9dc0-1f264baed7a6.gif)

#### What's the expected behavior?

The cursor is placed at the **end** of the string being composed.

cf. Draft JS (shown in Firefox below):
![draftjs](https://user-images.githubusercontent.com/1232595/44298311-a6a3d780-a31b-11e8-8362-624b4036dcf2.gif)

**Comment by thesunny** [comment]
Note: Working on this in this issue https://github.com/ianstormtaylor/slate/issues/2062

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
