### ISSUE TITLE
When switching focus between editors in Firefox, the initial selection does not match the click position

### ISSUE THREAD

**Issue by birtles** [ianstormtaylor/slate#2095]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

1. Open https://jsfiddle.net/birtles/s3fp8qrj/ in Firefox (I am testing with Firefox 63 on Windows 10)
2. Click somewhere in the middle of the second line of text
3. Notice that the cursor jumps to the start of the line

If you click again in the same line, it will update correctly. The first click after changing editor focus does not respect the mouse position.

![focus](https://user-images.githubusercontent.com/1232595/44298515-5c245a00-a31f-11e8-99c1-e288c166b856.gif)

#### What's the expected behavior?

The cursor is positioned somewhere in the vicinity of the mouse click. Chrome 68 and Edge show the expected behavior.

Note that Draft JS previously had a very similar issue: https://github.com/facebook/draft-js/issues/1055. In that case IE11 also experienced the same issue. I haven't been able to try these steps in IE11 however since I can't even get jsfiddle to load there.

**Comment by birtles** [comment]
So I only had a fairly brief look at this but I suspect the problem is something like the following.

1. When we change editors we call `updateSelection` in the `Content` component.
2. That triggers a call to [`removeAllRanges`](https://github.com/ianstormtaylor/slate/blob/e9c3c39d69f0388b2ffc496dc2e40fa86ea13ae8/packages/slate-react/src/components/content.js#L154)
3. In Firefox that updates the selection more-or-less immediately (compare the behavior of [this jsbin](http://jsbin.com/sahanirolu/edit?html,js,console,output) in Firefox and Chrome)
4. As a result when we get the (debounced) call to `onNativeSelection` → `this.props.onSelect` → `Editor.onEvent` → ... `onSelect` (after.js) → `findRange` which calls `window.getSelection()` the selection will already be cleared in Firefox but not in Chrome.

The discussion in https://github.com/facebook/draft-js/issues/1055#issuecomment-320107175 suggests that Chrome is probably wrong here.

Locally I can confirm that simply commenting out the call to `removeAllRanges` fixes the problem but I suspect it's there for a reason so I need to work out how this is expected to work.

**Comment by pascalw** [comment]
@birtles did you ever get anywhere with this? I'm running into the same issue on FF 64 on macOS.

**Comment by ianstormtaylor** [comment]
Has anyone tried in the latest versions of `slate` and `slate-react`? This might be fixed now with the recent selection fixes.

**Comment by birtles** [comment]
@pascalw I'm afraid not.
@ianstormtaylor [The fiddle](https://jsfiddle.net/birtles/s3fp8qrj/) is referencing the versions published on npmcdn: https://npmcdn.com/slate/dist/slate.js and https://npmcdn.com/slate-react/dist/slate-react.js. Checking again now I still see this issue (testing on Firefox 65 on Ubuntu FWIW) so assuming those versions are up-to-date, I guess this is still not fixed.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
