### ISSUE TITLE
When typing Japanese on Linux (Mozc) updates clobber the composition string

### ISSUE THREAD

**Issue by birtles** [ianstormtaylor/slate#2096]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

1. Go to https://www.slatejs.org/#/input-tester on Linux with a Japanese IME (I am using Mozc)
2. Type something in Japanese
3. Notice how the composition string keeps getting clobbered.

In Firefox it's quite severe:

![linux](https://user-images.githubusercontent.com/1232595/44298601-f46f0e80-a320-11e8-9cd5-82a468a60fc8.gif)

In Chrome it's also odd but less consistent:

![chrome](https://user-images.githubusercontent.com/1232595/44298621-5def1d00-a321-11e8-9558-ff8ff8f23556.gif)

It seems to be fine on the plain-text example, however. I've seen it in another app too and I believe both this other app and the input-tester example are triggering updates during composition.

#### What's the expected behavior?

The input is not clobbered.

**Comment by thesunny** [comment]
May be related to this issue https://github.com/ianstormtaylor/slate/issues/2062

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
