### ISSUE TITLE
No longer seeing 'key' property on points in selection.toJS()

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2099]
I'm not sure when I last saw them, but I'm definitely not seeing them anymore with the following versions:

Slate@0.37.7
Slate-React@0.15.7

**Comment by isubasti** [comment]
it looks like it got deleted on this line https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/point.js#L398
so try with `selection.toJS({preserveKeys: true})`

**Comment by Slapbox** [comment]
@ianstormtaylor is there a reason for this choice?

Also worth mentioning that `delete` throws a wrench into the V8 optimizations

![image](https://user-images.githubusercontent.com/6835891/44359208-2f8a5280-a485-11e8-9fbf-61ed008dfc5f.png)

[Source](https://github.com/davidmarkclements/v8-perf)

**Comment by ianstormtaylor** [comment]
Yeah, it’s to match the existing behavior in nodes. Keys aren’t static across serializations, so they aren’t serialized by default, only paths.  It you can opt in to have keys serialized too.

**Comment by Slapbox** [comment]
Oh `.toJS()` is used in serialization? I hadn't realized that. Thanks for the explanation.

It would probably be more performant from a V8 standpoint to do something like this if it's workable for the use case.

```javascript
const object = {
      object: this.object,
      key: options.preserveKeys ? this.key : undefined,
      offset: this.offset,
      path: this.path && this.path.toArray(),
    }
```
I know sometimes you really do need to use `delete` though. I had to use it in one function in my project.

**Comment by Slapbox** [comment]
Yeah I seriously doubt it is, but you know better what that function's used for than I. 

I'm not sure if the performance effects continue downstream for the life of the object which has had `delete` used on it, or if the object is re-optimized when the operation is complete.

This comment sheds a bit more light: https://www.nearform.com/blog/node-js-is-getting-a-new-v8-with-turbofan/#comment-3439322768

**Comment by ianstormtaylor** [comment]
@Slapbox nice, thanks for the link. If someone is having performance issues and they want to investigate that, they're welcome to.
