### ISSUE TITLE
Providing editor style causes input characters to be duplicated

### ISSUE THREAD

**Issue by darobin** [ianstormtaylor/slate#210]
See https://jsfiddle.net/robinberjon/ubexaufa/2/. Typing any character causes it to be inserted twice. I'll admit to being a bit baffled by this one.

**Comment by ianstormtaylor** [comment]
Wow that is a strange one, thanks for reporting! A `shouldComponentUpdate` check failure, fix incoming!

**Comment by ianstormtaylor** [comment]
Fixed in `0.10.2`!

**Comment by ianstormtaylor** [comment]
Actually fixed in `0.10.4`.
