### ISSUE TITLE
Better documentation on custom nodes

### ISSUE THREAD

**Issue by chrbala** [ianstormtaylor/slate#2101]
#### Do you want to request a _feature_ or report a _bug_?
I have something somewhere between a feature request and a question. I tried asking on the slack channel, but didn't get an answer. I think there should be better documentation on the usage of custom nodes.

#### What's the current behavior?
I'm trying to get a Slate input to rerender based on some state external to the Value object. How do I do this? It seems that the default shouldComponentUpdate logic is blocking the rerender. I found https://docs.slatejs.org/slate-react/custom-nodes#shouldnodecomponentupdate but it's not clear to me how or where to actually put that. I also found a related commit: https://github.com/ianstormtaylor/slate/commit/33a36679d9c840c8e9a857b0d3a850c8c275ad06

#### What's the expected behavior?
The documentation on custom nodes should be more detailed. In particular, there should be a complete example of a custom node in use. I couldn't find much information on how to use them at all.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
