### ISSUE TITLE
add `Node.isNodeInRange` helper method

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2103]
#### Do you want to request a _feature_ or report a _bug_?

Feature.

#### What's the current behavior?

Right now it's harder than it should be to answer the question of if a given node is in a given range. I think having this method would help.

#### What's the expected behavior?

```js
node.isNodeInRange(key, range) => Boolean
node.isNodeInRange(path, range) => Boolean
```

**Comment by zhujinxuan** [comment]
Shall it be `isNodeInRange` or `isDescendantInRange`?

**Comment by ianstormtaylor** [comment]
I think `isNodeInRange` would be most flexible, using `getNode/getPath`. We have the `*Descendant` and `*Child` alternatives for access, but these are more edge cases I think.
