### ISSUE TITLE
change `.getClosest` to include the node itself

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2111]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Right now the `.getClosest` method doesn't return the node itself if it matches the iterator. This is confusing because it's different than the behavior of the DOM's native [`el.closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) API.

#### What's the expected behavior?

It should return the node itself if it matches too.

**Comment by Dundercover** [comment]
Are you saying that these methods also need to change?

- `getClosestBlock`
- `getClosestInline`
- `getClosestVoid`

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
