### ISSUE TITLE
Firefox bug: Dragging void block next to editor inserts it instead of moving it

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2115]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
![ezgif-4-ca56486de4](https://user-images.githubusercontent.com/3816712/44494024-8ac96a00-a66a-11e8-95b8-c5b37aa8b100.gif)

#### What's the expected behavior?
Either nothing happening like in chrome, or moving the node

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
