### ISSUE TITLE
Firefox bug: arrow down from void block not moving selection down

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2116]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
In the image example: arrow down from void block not moving selection down

#### What's the expected behavior?
the selection moves to the beginning of the next block

**Comment by ravi-braj** [comment]
Also having this bug. Arrow down is working from some void block types but not all. See loom video
https://www.useloom.com/share/65144344a6cc4e6e9c62376d59bfab24 
For the void block type that isn't working
- Moving down into a void block works fine, but moving down out of the block isn't working
- Moving up into the void block isn't working
- Left and right arrow keys are all working fine

**Comment by ericedem** [comment]
Just as a data point, disabling this selection workaround lets you navigate down after only two button presses 😅 

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L230-L236

**Comment by skogsmaskin** [comment]
I think maybe it is related to ``contentEditable={false}`` not being respected the same way in Firefox as in i.e. Chrome. I am having issues in Firefox when adding some div inside a node renderer with ``contentEditable={false}``. Chrome will ignore it, while Firefox will not (it still takes cursor and focus). But only at one single position regardless of the text content within that div.

What is also worth noticing is that Firefox also will not respect the CSS property ``user-select: none`` on that div's content.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
