### ISSUE TITLE
Feature: Way to determine if drag was initiated from another editor in API.

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2117]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?
Currently isDraggingInternally is not exposed as an API. This is quite useful for plugins when they want to implement different behaviour for dragging an object within the editor and between editors.Right now the user has to set a onDragStart handler, set a flag and check for this flag in onDrop and unset it in onDragEnd. 

Not that big of a deal, but including a isDraggingLocally() method (or something similar) in the API seems like it might be logical to me. The same holds for a more generic isDragging method. What do you think?

**Comment by ianstormtaylor** [comment]
@bryanph can you explain more what you mean?

**Comment by bryanph** [comment]
@ianstormtaylor sorry that was really vague, I updated it. It's not that important honestly, you can close as you see fit. I just implement this with a boolean flag in my code. Its probably more interesting to think about the general case of being able to determine from what editor a drag came from. This requires every slate editor to have something like a unique key.

**Comment by ianstormtaylor** [comment]
With `0.50` and these event handlers being out of the plugin realm I think it doesn't make sense at Slate's core level to provide these anymore, but people can do it in their own React-land.
