### ISSUE TITLE
Unable to set cursor between void inline nodes

### ISSUE THREAD

**Issue by uipoptart** [ianstormtaylor/slate#2121]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
- Insert two void inline nodes side by side. 
- Click between them.
- One of the nodes becomes selected

![cursor](https://user-images.githubusercontent.com/1156239/44555829-ebe55200-a6eb-11e8-8894-c6c97b0c84ec.gif)

I did notice there's a moment where sometimes you can see the cursor while the mouse button is still clicked. You can see an example of that at the start of the gif. If you type without releasing the click the cursor will remain there.

Didn't include a JSFiddle because it can be reproduced with the emoji example: https://www.slatejs.org/#/emojis

Mac OS 10.13.6
Google Chrome 67.0.3396.99

#### What's the expected behavior?
The cursor is placed between the two nodes.

**Comment by ianstormtaylor** [comment]
This is fixed in later versions of Slate.
