### ISSUE TITLE
Unable to copy/cut when only void inline node is selected

### ISSUE THREAD

**Issue by uipoptart** [ianstormtaylor/slate#2124]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

- Insert void inline node 
- Click on a void inline node it’s state to selected (in this case it gets a black outline)
- Use the keyboard or dropdown menu to copy 
- Paste
- The copied node is not actually copied to the clipboard. The same behavior happens with cut.

![copy](https://user-images.githubusercontent.com/1156239/44598762-ec7ff600-a788-11e8-998d-fc0b7cedac7c.gif)

Didn't include a fiddle as this happens in the current emoji example.
https://www.slatejs.org/#/emojis
Mac OS 10.13.6
Google Chrome 67.0.3396.99

Some background:
In our use case, the void node contains underlying data that customized by the user. Like the emoji, some of it is displayed by the inline for the user to see. This scenario makes just inserting another instead of copy/pasting much more time consuming. 
![copy](https://user-images.githubusercontent.com/1156239/44598608-6fed1780-a788-11e8-8b2a-64d75bd2e3a4.gif)

#### What's the expected behavior?
The inline node is copied (or cut) to the clipboard

**Comment by uipoptart** [comment]
Looks like the issue is in `cloneFragment` where we use `value.document.getClosestVoid` to find the startVoid. If only a node is highlighted `getClosestVoid` returns undefined so the next line down returns: 
`if (native.isCollapsed && !startVoid) return `

I've also noticed if an inline node is last or first thing in a selection the text will copy but the node is left out, which might be another issue but seems related.

**Comment by ianstormtaylor** [comment]
Due to the tangential discussion in #1744 I've rolled this back. We need to find a solution that solves this without breaking the existing behaviors.

**Comment by laobeijing0806** [comment]
I have the same issue here, any updates?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
