### ISSUE TITLE
Deleting only child void node throws an exception

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2140]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Trying to delete an inline void node that is the only leaf throws an exception `Uncaught TypeError: Cannot read property 'text' of null`

[This JSFiddle](https://jsfiddle.net/fj9dvhom/1821/) sets things up.
1. Select the void node, or select after it.
2. Hit backspace.

Browser: Chrome: Latest

![kapture 2018-08-30 at 17 01 28](https://user-images.githubusercontent.com/1060669/44885577-6bd46480-ac76-11e8-9fe4-42cffcc16a0a.gif)

#### What's the expected behavior?

Should be able to backspace to delete, or select and delete the void node.

**Comment by ericedem** [comment]
Ok it looks like the problem above is that the "voidness" needs to be specified in the schema, rather than the data itself. I wonder if there should be a warning or error if someone tries to set `isVoid`. Here is a modified fiddle that works: https://jsfiddle.net/fj9dvhom/1843/

**Comment by JinJieTan** [comment]
I still haven't solved this problem. Your code hasn't solved my problem. When I deleted the only image content of the Editor, I was prompted that I Cannot read property 'text' of null   ，please,hele me !

**Comment by kocka5** [comment]
I have same error. Full stack is here:
[slate_error.zip](https://github.com/ianstormtaylor/slate/files/3739376/slate_error.zip)

I use slate version 0.47.8

**Comment by mhaagens** [comment]
Same issue here.
