### ISSUE TITLE
Backspacing with no content in iOS throws an exception

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2143]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Backspacing with no content in iOS throws an exception.
Try the rich text example: https://slatejs.org

1. Delete all the text.
2. Hit backspace
3. 💥 

![kapture 2018-08-31 at 9 26 28](https://user-images.githubusercontent.com/1060669/44924399-0331ca00-ad00-11e8-9f8f-bc827410a5eb.gif)

#### What's the expected behavior?

Shouldn't throw an error.

**Comment by ericedem** [comment]
From errors I have seen in our app, it looks like the last block itself may be getting deleted, which throws the editor into chaos.

**Comment by ericedem** [comment]
It looks like now the last block is able to get deleted. I was able to workaround this locally by adding the following to our schema:

```
document: {
  nodes: [
    {
      match: { object: 'block' },
      min: 1
    }
  ],
  normalize(change, error) {
    if (error.code === SlateSchemaViolations.CHILD_REQUIRED) {
      // We can't use change.insertBlock() because the first thing it will
      // do is try to find a `startBlock` which will throw an exception,
      // since there are no blocks.
      change.insertNodeByKey(
        error.node.key,
        0,
        { object: 'block', type: EditorConstants.NODE_TYPE_PARAGRAPH }
      );
    }
  }
}
```

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
