### ISSUE TITLE
slate-react@0.18.4 breaks editor focus on desktop (Safari, Chrome, Firefox)

### ISSUE THREAD

**Issue by zarv1k** [ianstormtaylor/slate#2147]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
Current latest slate stack:
slate@0.40.2
slate-react@0.18.4

Empty editor can't take focus: https://jsfiddle.net/zarv1k/vcdpn74j/
So it's impossible to add anything into the editor.

The issue is not only reproduced in empty editor. After clicking in blurred editor on the area after text content, focus loses immediately.

#### What's the expected behavior?
Empty editor can take focus, user can add anything into the editor:
slate@0.40.2
slate-react@0.18.3
https://jsfiddle.net/zarv1k/wv5ky9fq/1/

**Comment by briandk** [comment]
Anyone have thoughts on how to fix this? If so, I'm happy to work on a PR.

**Comment by dmitrizzle** [comment]
Same issue in Chrome 68.0.3440.106 macOS (looking at jsFiddle).

**Comment by ericedem** [comment]
Oh nope, this is definitely because of `onNativeSelectionChange()` getting added.

**Comment by ericedem** [comment]
For anyone looking for a workaround for the time being, you can do this:

```
<Editor
  ...
  onFocus={(event, change) => change.focus()}
/>
```

We were already doing this to workaround focus breaking when tabbing into the editor, which seems like it is probably a related issue.

**Comment by zarv1k** [comment]
@dmitrizzle can't agree with you about FF in my FF v.61.0.2 on macOS 10.13.6. It looks like editor has focus (you can see the caret), but you can't add anything into the editor.

**Comment by zarv1k** [comment]
> @zarv1k What browser is it failing for you? I confirmed Chrome is broken as well.

In all browsers on macOS 10.13.6:
Safari 11.1.2
Chrome 68.0.3440.106
Firefox 61.0.2

**Comment by dmitrizzle** [comment]
@zarv1k I use 61.0.2 on macOS 10.12.6 and I can edit the text. Very strange.

**Comment by zarv1k** [comment]
Some screen recordings:
[Safari](https://www.dropbox.com/s/0nr9riu402vdus7/ios-slate-react-0.18.4.mp4?dl=0) on iOS 11.4;
[FF 61.0.2](https://www.dropbox.com/s/tj5rxnpbg3f8eqi/FF-slate-react0.18.4.mov?dl=0) on macOS 10.12.6.

**Comment by ericedem** [comment]
When I remove this bit of code https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L152-L160 things seem to work.

It looks like the selection event is firing before things can be unblurred correctly, so the editor thinks it should be blurring, when it is currently in the process of being unblurred.

Some additional info, this is the order of operations that happens when you click the empty editor after blurring:

![image](https://user-images.githubusercontent.com/1060669/45038746-bce9ad00-b016-11e8-85dc-fe01b1f53f9c.png)

**Comment by steobrien** [comment]
> We were already doing this to workaround focus breaking when tabbing into the editor, which seems like it is probably a related issue.

@ericedem I'm also seeing this problem in our implementation. Should I open a Slate issue for it, or is there one already open?

**Comment by ericedem** [comment]
@steobrien There isn't a specific issue as far as I'm aware.

**Comment by steobrien** [comment]
Thanks @ericedem. I’ve gone ahead and opened https://github.com/ianstormtaylor/slate/issues/2352.
