### ISSUE TITLE
Weird cursor behavior on inline node with `display: inline-flex`

### ISSUE THREAD

**Issue by DanweDE** [ianstormtaylor/slate#2148]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When you render an inline node with `display: inline-flex` it causes weird cursor behavior. E.g.
 - when the cursor is placed in a text line a few words before the inline element, pressing arrow down/up  the cursor jumps to the inline element and back instead of to the next line and back:
![inline-cursor-up-down](https://user-images.githubusercontent.com/101926/44961362-59755780-af10-11e8-8c67-ce19ce639e17.gif)
 - the inline element's left edge seems to be "sticky", which first looked like a pleasant surprise. The right edge behaves differently though and considering other inline elements do not have sticky edges by default, this is just buggy: 
![inline-sticky-edge](https://user-images.githubusercontent.com/101926/44961381-9f322000-af10-11e8-843a-0703d972d881.gif)

#### What's the expected behavior?

An inline element with `display: inline-flex` should just behave like an inline element with `display: inline`.

#### Reproduce

You can use the [Slate links demo](https://www.slatejs.org/#/links) and simply add `display: inline-flex` to the link inline node.

**Comment by skogsmaskin** [comment]
Maybe somehow related to https://github.com/ianstormtaylor/slate/issues/2069?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
