### ISSUE TITLE
change.insertText(...).extend is not a function

### ISSUE THREAD

**Issue by victor2405** [ianstormtaylor/slate#2164]
after updating slate version got error: 
change.insertText(...).extend is not a function. The same error on examples here:https://www.slatejs.org/#/links. Any suggestion?

**Comment by ericedem** [comment]
Looks like this one got missed, `extend()` has been renamed to `moveFocus()` in 0.37.x https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#0370--august-3-2018

**Comment by ericedem** [comment]
I don't have collaborator status to reopen, but there is a fix ☝️

**Comment by maysam** [comment]
TypeError: change.insertText(...).moveFocus is not a function
