### ISSUE TITLE
Incorrect Core Schema Rules, or rules need explanation

### ISSUE THREAD

**Issue by SmilinBrian** [ianstormtaylor/slate#2170]
#### Do you want to request a _feature_ or report a _bug_?

Core Schema rule source code appears to be incorrect, but perhaps something subtle is happening which would benefit from a comment in the code.

Apologies for not fitting the standard bug template, especially on my first issue here.

As pointed out on Slate Slack by user "de83c 78d1f",

> Hello again, guys, we just read some source code and the question appeared: https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/schema.js#L61 here are rules forbidding blocks as inline children. Next we go to https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/schema.js#L99 - here are rules, which point to ability of blocks being inline children - as for our picture of 61 line rules - 99+ ain't even used ever (for blocks part). We kinda don't understand what are those 99+ line rules for. Do we miss some logic?

It does seem like the `first`, `last`, `previous`, and `next` rules on lines 99-102 should all have the `{ object: 'block' }` part removed. It should not be possible to have `Block` children of `Inline` per the `// Only allow inline and text nodes in inlines.` rule on line 61, which I think get applied before the line 99 rule. Alternatively, a comment that explains why the rule should be operational as it stands would expand people's understanding of the Core Schema rules.

**Comment by ericedem** [comment]
I think this is a typo, there is no way `first` and `last` could be blocks due to the rule you mentioned. However, `previous` and `next` could be blocks. It also looks like blocks and inlines can't be siblings due to this rule: https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/schema.js#L35-L57

**Comment by SmilinBrian** [comment]
But `previous` and `next` rules are only applied when iterating the **children** of the node that triggered testing. That is, when the Inline is "found" and this particular rule gets analyzed, it's only going to apply the `first`, `last`, `previous` and `next` rules to the children of the Inline, so it still seems like `{ object: 'block' }` should be removed from all of those.

And I agree that the rules in lines 35-57 should already cover the possibility of Blocks and Inlines being siblings.

**Comment by ericedem** [comment]
Hmm I think `first` and `last` apply to the children, but `previous` and `next` apply to siblings.

**Comment by SmilinBrian** [comment]
OK, I see now I missed that `validateNode(node)` is the "root" call, and it calls `validateRules(node, /* matching */ rules, this.rules, { every: true })` so that even though the 'matching' rules control part of the evaluation, `this.rules` ("all the rules") are there being passed to `validateNodes()` (the children).

In other words, it's not just the "matching" rule that gets applied when examining the children of any given node, it's all of them. Interesting.
