### ISSUE TITLE
I got a `type error`  in `slate-dev-warning` at ios 9.3

### ISSUE THREAD

**Issue by heyhuzi** [ianstormtaylor/slate#2172]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

I got a `type error`  in `slate-dev-warning` at ios 9.3;

this is good;
```
console.warn('something');
```

but this will get a bug;
```
var log = console.warn;
log('something');
```

#### What's the expected behavior?
just work fine;

**Comment by brendancarney** [comment]
Hi @heyhuzi, this issue as been inactive for a few months and needs more info. I'm going to close it, but if you're still having problems and can provide more information and/or an example using jsfiddle, we'd be happy to reopen. Thanks!
