### ISSUE TITLE
change.moveToRangeOf is not a function

### ISSUE THREAD

**Issue by benoneal** [ianstormtaylor/slate#2173]
#### What's the current behavior?

I get this error: `Uncaught TypeError: change.moveToRangeOf is not a function` when attempting to call that function on a change model. This is an issue in version 0.30, but was not an issue in version 0.27. The documentation still lists this as a supported method.

#### What's the expected behavior?

I expect the function to exist, because it's documented, and I'm not aware of any viable alternatives.

**Comment by moinism** [comment]
Try `moveToRangeOfNode` instead.

**Comment by ericedem** [comment]
Hmm, this was an API change in 0.37 https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#0370--august-3-2018

Not sure how it failed for in 0.30

**Comment by benoneal** [comment]
Sorry that was a typo. I meant v0.40. Thanks for providing the new alternative 👍
