### ISSUE TITLE
Add id prop that gets put on the top level DOM element of Editor

### ISSUE THREAD

**Issue by jclangst** [ianstormtaylor/slate#2184]
#### Do you want to request a _feature_ or report a _bug_?
Feature

It would be nice to have control over the `id` of the top level `div` that renders in the `Editor` `slate-react` component, especially if you have more than one editor going at once. For example, switching focuses between editors could be accomplished much easier. This would be a small addition, but I wanted to get approval before submitting a PR.

**Comment by ianstormtaylor** [comment]
Sounds good to me!
