### ISSUE TITLE
Using KeyUtils with Typescript

### ISSUE THREAD

**Issue by jonnyelliot** [ianstormtaylor/slate#2189]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

It isn't possible to use KeyUtils with the Typescript bindings. The example below gives the TS error `'KeyUtils' only refers to a type, but is being used as a value here.`

```
import { KeyUtils } from 'slate'

KeyUtils.setGenerator(() => '1')
```

Using:
@types/slate@0.40.0
slate@0.40.2
typescript@2.9.2

#### What's the expected behavior?

That I can import and use `KeyUtils.setGenerator` as the docs suggest.

**Comment by MathiasKandelborg** [comment]
I'm experiencing this bug as well. 

@types/slate@0.40.0
slate@0.40.2
typescript@3.0.1

**Comment by sgreav** [comment]
While not ideal, you can temporarily workaround this issue by doing the following: 

```
const slate = require('slate')
slate.KeyUtils.setGenerator(() => foo())
```

**Comment by ianstormtaylor** [comment]
The TypeScript bindings aren't something that is officially supported here, so you'll have to bring that up with the bindings maintainers themselves.
