### ISSUE TITLE
slate-hyperscript ignores some empty texts

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#2199]
#### Do you want to request a _feature_ or report a _bug_?

Reporting a bug

#### What's the current behavior?

I can't create document like this out of the box, to get this, I need to run Slate's normalization:

```jsx
<paragraph>
  <text />
  <link>Some inline link</link>
  <text />
</paragraph>
```

Here is a reproducible example, using hyperscript

```js
import Slate from 'slate'
import hyperscript from 'slate-hyperscript'

hyperscript(
  'block',
  { type:'paragraph' },
  [Slate.Text.create(''), Slate.Inline.create({ type: 'link' }), Slate.Text.create('')]
)

/*
Block { 
  "data": Map {}, 
  "key": "15", 
  "type": "paragraph",
  "nodes": List [
     Inline { "data": Map {}, "key": "12", "nodes": List [], "type": "link" },
     Text { "leaves": List [ Leaf { "marks": Set {}, "text": "" } ], "key": "13" } 
  ]
}
*/
```

#### What's the expected behavior?

The first `Text` is not kept. It should be present in the output.

#### Possible source of the bug

I have looked into `slate-hyperscript` source, but I could not fix it. I just identified that during the creation of the block, the `createChildren` function is called with `[Text, Inline, Text]` but the first `Text` is never pushed into the final children array.

**Comment by ericedem** [comment]
Probably related to: https://github.com/ianstormtaylor/slate/issues/2176

**Comment by Soreine** [comment]
This bug exists in 34.7 as well

**Comment by ericedem** [comment]
I did some debugging, and this is the spot where text nodes are getting normalized away:

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-hyperscript/src/index.js#L356-L363

The general behavior seems to be to collapse any child text nodes together, and then only add them as children if there is actually text. I'm not familiar with the use cases for `slate-hyperscript` so I'm not sure what the actual behavior is supposed to be. Is the output always supposed to match the input?

Regardless @Soreine here is a gist for a fixture that tests the first broken case you mentioned which does fail:

https://gist.github.com/ericedem/66248a1e5fe707004b426c11a65cd153
