### ISSUE TITLE
slate-react@0.18.4 introduced breaking change on onChange and selection

### ISSUE THREAD

**Issue by lichenglu** [ianstormtaylor/slate#2200]
#### Do you want to request a _feature_ or report a _bug_?

A bug I suppose.

#### What's the current behavior?

For `slate-react@0.18.4`, when selecting text, `onChange` is only triggered when the mouse is up (released). However, `onChange` is called repeatedly for previous version (`0.18.0` - `0.18.4`) as well as the current version (`0.18.9`). By `being called repeatedly`, I meant `onChange` is invoked whenever the selection range changes, without releasing the mouse.

It is really easy to reproduce, you just need to install `slate-react@0.18.4`, and log in `onChange`, and you will see it behaves differently from other versions.

OS: Mac OS 10.12.6
Browser: Chrome 69
Slate: 0.40.4

GIF:

For `0.18.14`
http://g.recordit.co/hrbh5lF7lp.gif

For others:
http://g.recordit.co/6NCDoGirhi.gif

#### What's the expected behavior?
If the behavior in `0.18.4` is unexpected, then I should there should be a documented text/announcement. I happened to start my slate journey with `0.18.4`, and I thought the behavior was working as designed.

#### A question
How would I achieve the effect that `onChange` will only be triggered when selection is ended (e.g. mouse-up)?

**Comment by ianstormtaylor** [comment]
@lichenglu can you clarify exactly which versions do and do not exhibit this behavior? I'm not sure what would have changed.

**Comment by ericedem** [comment]
For some context, there was discussion about this in the slack channel: https://slate-js.slack.com/archives/C1RH7AXSS/p1537558670000100

The gist was that 0.18.4 broken a whole bunch of things and also inadvertantly "fix" this bug just for taht version. This bug has been around for a while, though unclear as for how long.

**Comment by lichenglu** [comment]
@ianstormtaylor, sure!

I have tested in versions `0.18.0, 0.18.1, 0.18.13, 0.18.4, 0.18.5, 0.18.9`.

Through my testing, `0.18.4` is the ONLY version that DOES NOT trigger `onChange` when cursor moves. `onChange` is ONLY triggered when mouse is up (text selection finishes).

Other versions (including the latest `0.18.9`), namely, `0.18.0, 0.18.1, 0.18.13, 0.18.5, 0.18.9` triggers `onChange ` whenever the cursor moves.

Hope this clarifies the issue. I am not sure if the inconsistency is a bug for `0.18.4` or other versions, but I am wondering how can I achieve the behavior of `0.18.4` (wait until selection finishes to trigger onChange) on purpose?

**Comment by lichenglu** [comment]
Hi @ianstormtaylor, any update?

**Comment by ianstormtaylor** [comment]
@lichenglu this isn't what `onChange` was designed for, at least not with the current architecture. But maybe you can use `onSelect` for that, not sure.
