### ISSUE TITLE
Not able to pick suggested value on mobile browser

### ISSUE THREAD

**Issue by mddanishyusuf** [ianstormtaylor/slate#2202]
#### Do you want to request a _feature_ or report a _bug_?
report a _bug_

#### What's the current behaviour?
I was testing the editor in mobile browser. So, keyboard suggested work is not taking as input to the editor. IDK why. is there any plugin for this things?

#### What's the expected behaviour?
The editor should take the suggested input when we click on the word. I'm attaching the screenshot over here.

![img_20180924_234525](https://user-images.githubusercontent.com/9165019/45970577-8838a680-c054-11e8-8543-22d1cc15a4e6.jpg)

Anyone know the solution for this problem? 

Thanks

**Comment by ericedem** [comment]
@mddanishyusuf Can you please provide a fiddle or example where this is happening? As well as which browser / mobile device along with versions? Thanks!

**Comment by Slapbox** [comment]
@mddanishyusuf this is a well known and heavily worked on issue. We need more contribution towards a fully working mobile solution, especially for Android.

This thread covers a lot of the discussion and work, but there's a lot more in other threads too.

**Comment by fariz6480** [comment]
Fariz6480

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2062, if you think this is unrelated let me know and we can reconsider.
