### ISSUE TITLE
Unable to focus on empty editor on mobile

### ISSUE THREAD

**Issue by alanctkc** [ianstormtaylor/slate#2208]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

On mobile/touch devices, a tap on an empty `Editor` does not focus the editor. If the editor already has text, it's fine.

In the GIF, there are multiple clicks/touches, but no focus. [Here](https://jsfiddle.net/fj9dvhom/2341/) is the fiddle shown.

![peek 2018-09-25 21-39](https://user-images.githubusercontent.com/273453/46054134-939ad900-c10b-11e8-9cc3-197b93d44eaa.gif)
#### What's the expected behavior?

A tap on an empty `Editor` should focus for editing.

**Comment by ericedem** [comment]
I can't find the older issue that discusses this problem right now, but you can workaround this with:

```
<Editor
  onFocus={(event, change) => change.focus()}
/>
```

**Comment by alanctkc** [comment]
Thank you! This works for now.

**Comment by alanctkc** [comment]
So, it ends up that `change.focus()` hack really messes with a lot of other things (focus is initially/briefly in the wrong spot when clicking into the editor, scroll position gets messed with to focus the other position, etc.).

Any idea what the underlying cause is?

**Comment by shahkashani** [comment]
Yeah, seems to happen with or without a placeholder. If the form is empty, you can't ever seem to be able to enter text. I tried to add that workaround above, but the editor throws an error. Same thing happens on the demo site:

![slate](https://user-images.githubusercontent.com/1395893/48026602-84e51000-e114-11e8-9825-ef0d5e348141.gif)

**Comment by ianstormtaylor** [comment]
Can you see if this is focused now with https://github.com/ianstormtaylor/slate/pull/2396 merged?

**Comment by shahkashani** [comment]
I can no longer reproduce the crash, which is great. Things generally work fine in empty editors that have the placeholder. But sometimes you get into this weird state where there is no placeholder (and there should be), and in those situations you can't type.

![ezgif-4-952897590c82](https://user-images.githubusercontent.com/1395893/48646930-5985df00-e9b8-11e8-9c71-52416e59d52c.gif)

**Comment by steida** [comment]
@shahkashani How you made that gif? Thank you.

**Comment by shahkashani** [comment]
@steida No problem! That one was made using the built-in iOS screen recorder and then converting the video to a GIF on ezgif.com! Hope that helps.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
