### ISSUE TITLE
Inserting text at a range instead inserts at the current selection in some situations

### ISSUE THREAD

**Issue by alanctkc** [ianstormtaylor/slate#2209]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

When applying `instertTextAtRange`, if the editor is focused on a different line (text node) than the node in the range passed to `insertTextAtRange`, the text will be inserted at the current focus (selection) instead of the range specified.

![peek 2018-09-26 07-22](https://user-images.githubusercontent.com/273453/46079578-20ba4e00-c15d-11e8-802e-910d71fc81c1.gif)

[Here](https://jsfiddle.net/fj9dvhom/2350/) is the fiddle for the above.

#### What's the expected behavior?

`insertTextAtRange` should always insert text at the specified range, regardless of the current editor selection.

[Here's a test case](https://github.com/alanctkc/slate/blob/ff7c422c0e3d2693c0cf1dbd5092d313c4d8aefd/packages/slate/test/changes/at-range/insert-text-at-range/non-matching-section-and-range.js) that fails on the bug:

```javascript
export default function(change) {
  const { key } = change.value.document.getFirstText()
  const range = new Range({
    anchor: new Point({ key, offset: 0 }),
    focus: new Point({ key, offset: 3 }),
  })
  change.insertTextAtRange(range, 'That')
}

export const input = (
  <value>
    <document>
      <line>The change will be here.</line>
      <line>
        The cursor is <cursor />over here.
      </line>
    </document>
  </value>
)

export const output = (
  <value>
    <document>
      <line>That change will be here.</line>
      <line>
        The cursor is <cursor />over here.
      </line>
    </document>
  </value>
)
```

#### The cause

These are the offending lines:

https://github.com/ianstormtaylor/slate/blob/6813ac41b5eba4211e87fdb998752c937279960f/packages/slate/src/changes/at-range.js#L809-L813

After the range is deleted, the start key is reset to the start of the current selection. This is presumably to handle key changes and what not after deleting multiple lines, but it's wrong to assume the current selection will reflect the original range. Maybe there's another way to achieve the same behavior after delete without using current selection?

**Comment by ericedem** [comment]
Weird, I'm not sure why there is selection logic in there at all. It seems like we could just delete that block and have:

```
change.withoutNormalizing(() => {
  if (range.isExpanded) {
    change.deleteAtRange(range)
  }

  change.insertTextByKey(key, offset, text, marks)
})
```

**Comment by alanctkc** [comment]
Yup, deleting the block works for my case, but it looks like #1189 may be the initial reason for the logic.

The change came in #1432.

**Comment by ericedem** [comment]
Interesting, it looks like the main problem with #1189 is that `deleteAtRange()` can actually remove the first block. It seems like since every node must contain text that there would always be a valid start / offset left over, and the block should just stay there.

Maybe there should be a simpler method like `deleteTextAtRange` that doesn't delete the start block? Or maybe `deleteAtRange` should rely on normalization to take care of empty blocks.

Another option might be to use paths, though it could get awkward because if `deleteAtRange()` could destroy the block containing the selection then you would have to rebuild it.

**Comment by alanctkc** [comment]
@czechdave @echenley A fix in #1432, addressed #1189, but introduced this bug. Do either of you understand the original issue well enough to know how to fix the bad side effect here and still solve what you were aiming for when it was introduced?

I haven't dug in deeply enough to understand the problem, but deleting those lines that update the range after delete eliminates this issue.

**Comment by alanctkc** [comment]
I did actually get your tests to fail, @czechdave, so thanks for adding those!

**Comment by alanctkc** [comment]
I made a failing test case for this bug [here](https://github.com/alanctkc/slate/blob/ff7c422c0e3d2693c0cf1dbd5092d313c4d8aefd/packages/slate/test/changes/at-range/insert-text-at-range/non-matching-section-and-range.js) and pasted into the description above.

**Comment by alanctkc** [comment]
cc @blakeembrey, it seems like you were maybe trying to address a similar bug with your contribution checking that the start key really had changed after delete?
