### ISSUE TITLE
Editor cursor doesn't always display when tabbing to Editor

### ISSUE THREAD

**Issue by javery014** [ianstormtaylor/slate#2210]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
When tabbing through a document to a Slate editor, the cursor in the Slate editor doesn't always appear. It seems that the cursor will only appear if the previous cursor location in the Slate editor was anywhere else but the very start of the editor. 

![editor-tabbing-issue](https://user-images.githubusercontent.com/10987301/46107566-4e28eb00-c1a1-11e8-9325-6268bcb6bf72.gif)
https://jsfiddle.net/fj9dvhom/1/

#### What's the expected behavior?
I would expect whenever I tab to the Slate editor, the cursor would be visible at the start of the editor (or the end, looking at #1964).

**Comment by everdimension** [comment]
I'm also bothered by this bug, but for the time being I'm using this for the fix (using `slate-react`):

```jsx
<Editor
  onFocus={(event, change) => { change.focus(); }} // <-- the fix
  value={this.state.value}
  onChange={this.handleChange}
/>
```
