### ISSUE TITLE
Editor crashes when last character is removed in mobile browser

### ISSUE THREAD

**Issue by Pranab16** [ianstormtaylor/slate#2220]
#### Do you want to request a _feature_ or report a _bug_? 
Bug

#### What's the current behavior?

 - Open https://www.slatejs.org/#/plain-text in mobile browser or using device toolbar in desktop chrome. 
 - Select all text and remove it (you can remove text one by one)
 - Now try to enter any text.
 - The editor will break or you won't be able to enter any text (this doesn't happen in desktop)

<img width="662" alt="screen shot 2018-10-01 at 7 38 17 pm" src="https://user-images.githubusercontent.com/4946120/46293584-9422ec00-c5b1-11e8-87ef-8f2ef5e9ae5e.png">

**Comment by ericedem** [comment]
@Pranab16 I'm having trouble reproducing this. Could you provide browser / version info as well? Thanks!

**Comment by Pranab16** [comment]
@ericedem I am using Chrome browser Version 69 (latest). 
Sorry for the missing info.

**Comment by Findeton** [comment]
I'm also experiencing this problem in Android, in the latest version 69 of Chrome.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2062, if you think this is unrelated let me know and we can reconsider.
