### ISSUE TITLE
State is reset when clicking on a void node

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#223]
When clicking on a void node (for example, an image, the content is reset).

### Steps to reproduce it:

Open the jsfiddle reproducing the issue: https://jsfiddle.net/u9zugkr2/

1. Type some text at the end of the editor (for example insert a new paragraph, etc)
2. Click on the image
3. Sometimes you have to click again on the text before it resets it.

### Expect behaviour:

The selection should be move to the image node, but the content should stay identical.

**Comment by ianstormtaylor** [comment]
Fixed in `0.11.1`!
