### ISSUE TITLE
Adding and removing inline voids cause editor crashes in Mobile Chrome

### ISSUE THREAD

**Issue by dodgecm** [ianstormtaylor/slate#2237]
Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

Reproduced on https://www.slatejs.org/#/emojis

I used the debugger to set Chrome in Mobile mode, and I set the device type to iPhone 6/7/8.  This is important, as the bug does not appear to occur if the device type is set to Responsive.  Make sure you refresh the page after setting the device type.

![crash](https://user-images.githubusercontent.com/6513692/46645106-395d3780-cb51-11e8-8178-747a0bcef853.gif)

To reproduce, add a few emojis like in the gif, and then try to delete them using backspace.  Pressing backspace two or three times should trigger the crash.

![screen shot 2018-10-08 at 11 26 30 pm](https://user-images.githubusercontent.com/6513692/46645166-a2dd4600-cb51-11e8-817f-85829ac26a1f.png)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
