### ISSUE TITLE
Hovering Menu Example broken after latest update

### ISSUE THREAD

**Issue by mehdikazi** [ianstormtaylor/slate#2241]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
The hovering menu example on https://www.slatejs.org/#/hovering-menu is broken after the latest update. 
<img width="789" alt="screen shot 2018-10-09 at 9 52 52 pm" src="https://user-images.githubusercontent.com/14842579/46713905-b64de700-cc0d-11e8-94a8-0bcc6aee2b46.png">

#### What's the expected behavior?
The editor should be able to render without errors and have a functional hovering toolbar. 

#### What I noticed
I was trying to refactor my current code to fit the newest slate update involving the Editor Controller and it looks like the problem comes from renderEditor getting passed the next function and not the editor as the second argument. It also seems like props.children does not exist.

**Comment by ianstormtaylor** [comment]
Oops, sorry about that @mehdikazi. I've just pushed https://github.com/ianstormtaylor/slate/commit/9c597cf97f07c834ea0a3686d7d7d1db4322900d which fixes it. Thanks!
