### ISSUE TITLE
re-render the editor make the BeforePlugin to a  new instance

### ISSUE THREAD

**Issue by yunwuxin** [ianstormtaylor/slate#2242]
https://github.com/ianstormtaylor/slate/blob/9c597cf97f07c834ea0a3686d7d7d1db4322900d/packages/slate-react/src/plugins/before.js#L167

re-render the editor make the BeforePlugin to a  new instance

so in `onInput`  `isComposing`  is always false

**Comment by ianstormtaylor** [comment]
@yunwuxin can you provide a code sample of how you’re rendering your editor?

**Comment by ianstormtaylor** [comment]
Nevermind @yunwuxin, I discovered the bug and fixed it in https://github.com/ianstormtaylor/slate/commit/6168ce932ec6c8a7eb4b8e4f62dccb77bc8ae7b2. Thank you for reporting this!
