### ISSUE TITLE
add `pluckNodeByKey`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2246]
#### Do you want to request a _feature_ or report a _bug_?

Feature.

#### What's the expected behavior?

Right now we have `unwrapNodeByKey`, which can be helpful. But there's another use case where you want to remove a specific node, and let its children take over its spot in the tree.

Alternative name could be `extractNodeByKey`.

**Comment by bryanph** [comment]
This is very useful for nested lists for example; when removing the parent we often want the children to take its place instead of also removing the children

**Comment by ianstormtaylor** [comment]
Added in https://github.com/ianstormtaylor/slate/commit/93df22a128b23c3b533ee91ba66076f96e62ee54 as `unwrapChildrenByKey/Path`.
