### ISSUE TITLE
deleting inside an empty non-void inline should remove it

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2250]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Consider this document:

```jsx
      <document>
        <paragraph>
          wo<link><cursor /></link>rd
        </paragraph>
      </document>
```

If you do `deleteBackward()` here, it will end up removing the `'o'` before the cursor, and not removing the non-void `<link>` inline node too

#### What's the expected behavior?

It should remove the `<link>` and the `'o'` I think.

**Comment by lapico** [comment]
Hi,

My text is only composed of inline nodes inside paragraphs.

Delete / backspace is not removing the inline node even though it's empty.

When doing so on the first line / first offset, editor crashes with this error:
```
TypeError: Cannot read property 'text' of null
push../node_modules/slate/lib/slate.es.js.Commands$1.deleteBackwardAtRange
node_modules/slate/lib/slate.es.js:6050
  6047 | 
  6048 | while (n > traversed) {
  6049 |   node = document.getPreviousText(node.key);
> 6050 |   var next = traversed + node.text.length;
       | ^  6051 | 
  6052 |   if (n <= next) {
  6053 |     offset = next - n;
```

**Comment by dminkovsky** [comment]
When you backspace and the cursor and empty inline are at the beginning of a block, you get:

```
slate.es.js?d1a0:5849 Uncaught TypeError: Cannot read property 'text' of null
    at Commands$1.deleteBackwardAtRange (slate.es.js?d1a0:5849)
```

For the user, this causes the backspace to fail. My workaround is specifying inlines `isVoid` (per the mentions example)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
