### ISSUE TITLE
Composer loses focus after using character picker

### ISSUE THREAD

**Issue by dbkr** [ianstormtaylor/slate#2251]
#### Do you want to request a _feature_ or report a _bug_?

Bug report

#### What's the current behavior?

https://jsfiddle.net/pqu2aj39/
![oct-11-2018 12-37-27](https://user-images.githubusercontent.com/986903/46801389-79d7d380-cd52-11e8-9f51-2a3b5413c2e0.gif)

When using the OS X character picker to insert the first character in the composer, the composer loses focus after entering the character. This bug only happens if there's an element in the DOM after the slate editor (I've added a div after the composer in the jsfiddle). I can only reproduce it on Chrome (Safari and Firefox, both also on OS X, are fine). I've tested on Chrome 69 and 71 (stable and Canary at time of writing).

Repro steps:
 * On mac, open the js fiddle in Chrome
 * Click in the slate editor to focus it
 * Hit ctrl+cmd+space to open the character picker
 * Choose a character and press enter / click on it to insert it
 * Type some letters. Observe that no text appears in the editor. There's also no cursor in the editor.
 * Press space. The space is inserted in the editor and the cursor re-appears. You can now type as normal.

#### What's the expected behavior?

Typing a letter after inserting the character with the character picker as above should enter the letter into the editor. The cursor should appear after inserting the character from the character picker.

**Comment by ianstormtaylor** [comment]
Can you see if this is focused now with https://github.com/ianstormtaylor/slate/pull/2396 merged?

**Comment by dbkr** [comment]
I've tried to re-test but now the placeholder text doesn't appear, so there's nothing to click on to start entering text. Similarly if I add a text node in the initial value as in the base jsfiddle and then backspace to delete all the text, the editor vanishes: test by deleting the top line of text here: https://jsfiddle.net/ghcky2fa/

Missing editor if initial value has no text:
![screenshot 2018-11-09 at 13 03 46](https://user-images.githubusercontent.com/986903/48264044-18258a80-e420-11e8-8cd2-7e7b01365925.png)

Disappearing editor:
![editor_vanish](https://user-images.githubusercontent.com/986903/48264053-21aef280-e420-11e8-9462-7d8874ad50c8.gif)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
