### ISSUE TITLE
Fyi: Slate does wrongly trigger onChange event after plugins are registered

### ISSUE THREAD

**Issue by ms88privat** [ianstormtaylor/slate#2254]
Slate does wrongly trigger onChange event after plugins are registered. This did happen somewhere between v30 and v34, it was not the case before that. You can see the difference in the immutable state, at first the plugin stack only contains some plugins ("before plugins"?) and after that it will add more plugins ("custom" and "after plugins"?), which will result in a different overall value, which will then trigger the onChange event.

All the plugins are defined as soon as the editor is mounted, so there is no change at all, which should not result into an editor onChange.

We noticed this at work because it was a breaking change for us and planned to invest some time to pinpoint the version and also provide a minimal example reproducing the issue. Currently our project is under a lot of pressure so we went with a simple solution to our problem by wrapping the editor and doing our own shallow compare without comparing the schema of the value, before triggering onChange.

Still wanted to let you know, if somebody else has this problem and doesn't know why. I'm not 100% sure if this is reproducible in a minimal example, or if there is more to it.

**Comment by ianstormtaylor** [comment]
@ms88privat I'm not sure about this, but this logic has changed a lot in `0.42`, so I'm going to close this out for now. If you discover this issue again feel free to re-open.

**Comment by valorize** [comment]
@ianstormtaylor Hey Ian, the current behaviour is that despite being readOnly the editor still triggers the onChange callback right?

**Comment by ms88privat** [comment]
We did not upgrade to 0.42, so we can not confirm this yet.

@valorize Which version are you talking about? In principle if nothing changes, it should not trigger onChange, so if it is readOnly it should never trigger. But I think you are mention the same bug as me, that the initialising of the plugins alone will trigger an onChange event, which will also happen in the readOnly mode

**Comment by valorize** [comment]
@ms88privat, @ianstormtaylor  A editor selection / focus is a change and I wonder if it is ignored in readOnly mode or not. And if it should or should not be ignored. (A selection change for a readOnly editor could be interesting for some minor usecases I guess).
If a selection change should be ignored in readonly mode, than this is a bug in slate and we should create a bug issue for this.
