### ISSUE TITLE
renderEditor props.children is undefined

### ISSUE THREAD

**Issue by klis87** [ianstormtaylor/slate#2259]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Since upgrade to newest version of slate `0.42.2` from `0.41.0` and slate-react `0.19.3` from `0.18.0`  `renderEditor`, which I use to wrap `children` to generate toolbar doesnt work anymore, `props.children` is `undefined`, I think the rest props is still there

I prepared demo showing this issue: https://codesandbox.io/s/1z1lyjp00q
Is this some regression or I do sth wrong?

#### What's the expected behavior?
`renderEditor` should have access to `props.children`

**Comment by isubasti** [comment]
children is renderered using next https://github.com/ianstormtaylor/slate/blob/master/examples/plugins/word-count.js#L14

**Comment by klis87** [comment]
@isubasti Thx, it works! However, https://docs.slatejs.org/slate-react/plugins#rendereditor doesn't mention this, should it? 

I am slightly confused here, I guess it is done this way to be able to use `renderEditor` multiple times, so each plugin could wrap `children` with another component which could be passed to next `renderEditor` callback. Maybe renaming `next` to `nextChildren` could help?

**Comment by klis87** [comment]
Or maybe not :) `next` will just always mean, give me return value of previous method of this type, in this case it should be React component so it seems logical after all. 

If you think it is worth adding to docs, I could do it.

**Comment by SmilinBrian** [comment]
I think it's worth adding to the plugins documentation. Pretty sure I saw a question essentially just like this on the Slate Slack a few days ago, so you're not the only one confused about `next` and rendering.

**Comment by klis87** [comment]
@ianstormtaylor I am closing this issue as PR is there if you would like to merge it, if u wanna change sth just give me a hint in the PR
