### ISSUE TITLE
input in void node doesnt handle onChange

### ISSUE THREAD

**Issue by klis87** [ianstormtaylor/slate#2261]
#### Do you want to request a _feature_ or report a _bug_?
Bug, regression from 0.41.0 to 0.42.0

#### What's the current behavior?
`onChange` handler of inputs inside void node isn't called, while it should. Here is the demo: https://codesandbox.io/s/kzo229q53

#### What's the expected behavior?
`onChange` should be called, like in previous Slate version - https://codesandbox.io/s/5y5n7qlvwk

**Comment by gnestor** [comment]
Thanks for this example, @klis87. This is a known issue being discussed at https://github.com/ianstormtaylor/slate/issues/1744 and I'm seeing some discussion in the Slack. This is a regression as the "Embed" example (which has an input for changing the embed source URL) used to work but doesn't anymore. We just need to figure out what changed from 0.41 to 0.42 that caused this and patch it. Feel free to close this and chime in at https://github.com/ianstormtaylor/slate/issues/1744.

**Comment by klis87** [comment]
@gnestor Thx for hunting this down in related issue, closing this to avoid duplicates
