### ISSUE TITLE
Cut near inline nodes causes the whole line to delete

### ISSUE THREAD

**Issue by mehdikazi** [ianstormtaylor/slate#2262]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
When you are cutting text near an inline node the entire line will be deleted. This can be seen in both the link and emoji example on slatejs.org. 
![2018-10-15 02 32 09](https://user-images.githubusercontent.com/14842579/46942599-8b56ff00-d022-11e8-951b-13bcb24d8b27.gif)
![2018-10-15 02 32 45](https://user-images.githubusercontent.com/14842579/46942647-a3c71980-d022-11e8-9f29-24c5de3b9b0b.gif)

#### What's the expected behavior?
Only the selected text should be deleted.

**Comment by ianstormtaylor** [comment]
Fixed now!
