### ISSUE TITLE
Void blocks break CMD + right on macOS

### ISSUE THREAD

**Issue by PierBover** [ianstormtaylor/slate#2268]
#### What's the current behavior?

It seems void blocks break something in Slate. When there are void block in the editor content the **CMD + right** (go to the end of the line) macOS shortcut does not work anymore. **CMD + left** works fine.

Selecting to the end of the line with **CMD + right + SHIFT** works fine, but when moving the cursor the selection moves with it.

Here is a video that shows these behaviors:
https://www.youtube.com/watch?v=UAnNlhMcPLc

This happens on the Slate examples: https://www.slatejs.org/#/images

#### What's the expected behavior?

**CMD + right** should go to the end of the line. After doing a selection and moving the cursor the selection should disappear.

**Comment by PierBover** [comment]
It would seem this is related to https://github.com/ianstormtaylor/slate/issues/2069

**Comment by ericedem** [comment]
@PierBover Can you take a look and see if my PR fixes this in the way you expect?

https://github.com/ianstormtaylor/slate/issues/2069

The PR is deployed here: https://deploy-preview-2169--slatejs.netlify.com/#/images

It looks like it's working better now.

**Comment by PierBover** [comment]
Yes that fixes it @ericedem !
