### ISSUE TITLE
prevProps.editor equals props.editor in shouldNodeComponentUpdate

### ISSUE THREAD

**Issue by grsmvg** [ianstormtaylor/slate#2269]
See this bug in action here:

https://jsfiddle.net/gersomvg/fj9dvhom/2480/

I can try to PR this myself, after this is confirmed by someone else as a bug.

**Comment by isubasti** [comment]
duplicate of https://github.com/ianstormtaylor/slate/issues/2159

**Comment by grsmvg** [comment]
Ah, sharp. I didn't look back that far

**Comment by ianstormtaylor** [comment]
Closing in favor of #2159.
