### ISSUE TITLE
Select all + Cut crashes the editor

### ISSUE THREAD

**Issue by linvain** [ianstormtaylor/slate#2279]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

1. `Ctrl + A`
2. `Ctrl + X`
3. Press any button
4. Error

![gif](https://user-images.githubusercontent.com/42490556/47141160-b8c4d680-d2c8-11e8-9968-20213049c351.gif)

**Comment by javascriptlove** [comment]
Just noticed that too, very annoying

**Comment by ericedem** [comment]
It looks like all the blocks are getting deleted in addition to all the text. Something is goin haywire with the delete in https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/after.js#L216

**Comment by ericedem** [comment]
It looks like there are two problems happening:

1. When you cut, the first cut happens and deletes the content. Then for some reason another cut happens after the first one when there is no content left.
2. Calling delete (cut in this case) with no content deletes the paragraph (oops!).

This test illustrates 2: https://gist.github.com/ericedem/9e51a181689769ae9510fb02428fc1d8

**Comment by ericedem** [comment]
@linvain due to the 0.43 release that just went out. 0.42 should be working.

**Comment by skogsmaskin** [comment]
Fixed again in https://github.com/ianstormtaylor/slate/pull/2343
