### ISSUE TITLE
Documentation for Fragment is confusing

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#228]
`Fragment` is a confusing part of Slate, sometimes in the doc it's referred as `List<Node>` ([lib/models/transforms.js#L297](https://github.com/ianstormtaylor/slate/blob/master/lib/models/transforms.js#L297)).

But in practice, it's a `Document` (see the [paste-html](https://github.com/ianstormtaylor/slate/blob/master/examples/paste-html/index.js#L201) example) ?

I think the document should contain a section about `Fragment`:

- How to create one
- How to insert one
- ...

**Comment by ianstormtaylor** [comment]
Good catch on those source comments, fixed those. And made a small mention of "fragments" in the `Document` model reference, and linked to the `Document` reference from the `insertFragment*` transforms as well. I hope that's enough for now!

**Comment by SamyPesse** [comment]
Perfect 👍 thanks!
