### ISSUE TITLE
No keyboard: Can't type on empty editor in iOS

### ISSUE THREAD

**Issue by Findeton** [ianstormtaylor/slate#2284]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behaviour?

In iOS browsers (tested Safari, Chrome and Firefox), I can't type on an empty editor because the keyboard doesn't appear.
![ios](https://user-images.githubusercontent.com/3913223/47235425-e85f0600-d3d0-11e8-94d6-3d4f6f30745c.jpg)

You can reproduce it by visiting the demos webpage from an iOS phone/device: 

1. Go to https://www.slatejs.org
2. Select all text.
3. Delete all text.
4. Click somewhere else.
5. Click on the editor again.

The keyboard doesn't appear. Thus I can't type anything.

#### What's the expected behavior?

Keyboard should appear when I click on an empty editor in iOS.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2208
