### ISSUE TITLE
Removing the last block breaks selection

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2297]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

Removing the last block, or starting with no blocks, leaves the selection in a broken state once blocks are added. I was able to reproduce this with several test cases, this one tests insterting a block into an empty document:

```jsx
/** @jsx h */

import h from '../../../helpers/h'

export default function(change) {
  change.replaceNodeByKey('a', { object: 'block', type: 'quote' })
}

export const input = (
  <value>
    <document>
      <paragraph key="a">one</paragraph>
    </document>
  </value>
)

export const output = (
  <value>
    <document>
      <quote />
    </document>
  </value>
)
```

With the resulting output:
https://gist.github.com/ericedem/21bd5aa094268b89b5e7d79bfc1b7ab8

I think this is causing or at least related to a few issues opened since 0.42 namely: #2289, #2279 

#### What's the expected behavior?

I think what should happen is that the selection should be restored to the beginning of the first block when one is inserted. Though this still leaves the editor in a strange state if someone removes a node and tries to do something in the middle.

Anyone got any ideas on how this should behave?

**Comment by ianstormtaylor** [comment]
I'm not really sure about a good solution here. It might be things to fix at the source in the specific places it's causing issues, not assuming that a selection is "set".

One "solution" would be to use unset selections more often, whenever something is blurred, so that people don't assume the selection will always be set?

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
