### ISSUE TITLE
Schema normalization rules no longer seem to have a limit to prevent infinite loops

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2301]
This feature in previous versions of Slate was really helpful, but in 0.42.x it doesn't seem to be there; at least I'm not seeing it.

`Error: A schema rule could not be normalized after sufficient iterations. This is usually due to a `rule.normalize` or `plugin.normalizeNode` function of a schema being incorrectly written, causing an infinite loop.`

I've been waiting to hit the maximum callstack while debugging some normalization rules and it made me realize how much I appreciated that failsafe. Was this intentionally removed, or did I break something?

**Comment by Slapbox** [comment]
Schema iteration count doesn't increment in most cases when dealing with a schema rule that causes infinite loops. I have found that it incremented for some rules, but in the cases that are actually infinite loops it doesn't seem to count up.

https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/controllers/change.js#L235

[Brief video of debugger at the statement that checks for the limit](http://recordit.co/y8zJL2AGl7)

**Comment by Slapbox** [comment]
@ianstormtaylor can you point towards where this iterating was handled prior to the introduction of the `change` controller in `0.42.x` ? I don't see any obvious problem within the current function. I rolled back to an old commit to try just searching everything for the function name, `normalizeNodeByPath` but I guess it was named differently in the past too.

**Comment by ianstormtaylor** [comment]
If you search for `iterate(` that should find it I think.

**Comment by Slapbox** [comment]
Great, I found it! Thanks Ian!

**Comment by Slapbox** [comment]
Whoops, I guess I forgot to update. I took a look for a while and couldn't find anything wrong. I hadn't come to that conclusion, but I think you're right. Hitting the maximum call stack before you hit the 1000 recursions is definitely possible with complex rules and a mistake that cause a loop.

**Comment by ianstormtaylor** [comment]
I think your point is good though that `1000` is too high to be useful so let's keep this open til we fix it.

**Comment by ianstormtaylor** [comment]
Just decreased to `100` so hopefully that helps.
