### ISSUE TITLE
Focusing/selecting void blocks within scrollable containers causes incorrect scroll behaviour

### ISSUE THREAD

**Issue by benoneal** [ianstormtaylor/slate#2302]
#### What's the current behavior?

(I'm not including a fiddle because I've pinpointed the problem and potential solution)

Currently, the inline styling of `data-slate-spacer` elements sets them as `position: absolute`. All void nodes (such as images) render a spacer as a _sibling_ to their content. This spacer is the element which receives focus/selection events. As its positioning removes it from document flow, the `scrollToSelection` utility receives a `boundingClientRect` for the selection range that is parented by this spacer that is not part of the document flow, and therefore returns offsets that are far beyond the actual expected offsets of the void node's "real" content. The result is that the container is scrolled much further, taking the void node well out of view for long content. 

This is reproducible in the latest version of slate-react.

#### What's the expected behavior?

When focusing/selecting void nodes, the scrollToSelection method should scroll the scrollable container to the content of the void node, and not to the absolutely positioned sibling spacer.

#### What's the simple solution?

In my codebase, to workaround this issue I've applied the following css style:

```
[data-slate-void='true'] {
  position: relative;
}
```

This has the desired effect, in settings spacers within void nodes to obey document flow, and focusing/selecting void nodes now correctly scrolls them into position as expected.

**Comment by crisward** [comment]
Found something similar with the slate-spacer, so added...

```css
[data-slate-void='true'],[data-slate-spacer="true"]{
  position: relative!important
}
```
Not sure if this will break anything.

**Comment by zaqzaq163** [comment]
> Found something similar with the slate-spacer, so added...
> 
> ```css
> [data-slate-void='true'],[data-slate-spacer="true"]{
>   position: relative!important
> }
> ```
> 
> Not sure if this will break anything.

it's work    .  thx

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by calvinwyoung** [comment]
It looks like this is still an issue in v0.50+. The workarounds suggested above still achieve the desired behavior, but it's unclear whether they break anything else.

Does anyone know why spacers have `position: absolute` by default? Would it be worth changing the default behavior to `position: relative` to fix this permanently?
