### ISSUE TITLE
Inline void node without text at start will be removed when paste something

### ISSUE THREAD

**Issue by icarusysuper** [ianstormtaylor/slate#2303]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

- select some text
- copy
- focus at the end of inline void node(emoji node)
- paste
- the inline void node(emoji node) will be removed

![gif](http://g.recordit.co/6640So4xd0.gif)

This happens in the current emoji example.
[https://www.slatejs.org/#/emojis](url)
Win 7 (so my emoji can't show T^T)
Google Chrome 67.0.3396.87

#### What's the expected behavior?
the inline void node will not be removed

**Comment by kilrain** [comment]
I'm not able to reproduce this... I'm seeing a similar bug in an older version (slate 0.45, slate-react 0.21.20). I'm thinking taking the effort to update might fix my problem then...

**Comment by icarusysuper** [comment]
Yeah. This bug is been fixed...
