### ISSUE TITLE
It's possible to remove every node in Slate 0.42.x, even when the schema prescribes required first and last nodes

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2305]
I'm not sure how to reproduce this yet, but I just ran into a state where my editor was devoid of any blocks.

This can be fixed via schema rules, but in previous versions this was not possible to do, so I'm unsure if this is an intentional change or a potential bug.

To prevent this, use a rule like:

```js
document: {
  nodes: [
    {
      match: [
        { type: 'paragraph' },
      ],
      min: 1, //  This line fixes the issue
    }
  ]
}
```

**Comment by Slapbox** [comment]
Possibly caused by #2264

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2312.
