### ISSUE TITLE
Schema rules not consistently applied

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2306]
**I can't say with certainty, but it seems like `object_required` and `invalid_object` work all the time, but `invalid_type` seems not to work very consistently**

____

In my app with 0.42.x, using a rule like the below will not normalize until a block is inserted somewhere else in the document:

```js
const schema = {
  document: {
    first: [{ type: 'h1' }, { type: 'paragraph' }]
  }
}
```

In this Fiddle I made, it seems that `first` is not enforced. Perhaps I'm doing something wrong, but this code works perfectly in `0.39.3`

Fiddle: https://jsfiddle.net/Slapbox/yn0omjfs/1/
Steps to reproduce in this fiddle: http://recordit.co/JNMGa81bDy

**Comment by Slapbox** [comment]
### Followup:

It seems like most schema normalization in my project are not having any effect until at least one block level change occurs `0.42.x`.

**Comment by Slapbox** [comment]
Probably duplicate of #2264

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2312.
