### ISSUE TITLE
Suggestion: Utility Examples

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2308]
I think it would be helpful for reproduction purposes to consider adding a few examples under a subdirectory of the examples directory, so something like https://slatejs.org/util.

The idea struck me because of this issue that can only be created with an editor that's empty from the start: https://github.com/ianstormtaylor/slate/issues/2260

But it would be useful for far more than just that if we had ready-built examples to make reproduction easier locally and for sharing. My only immediate suggestion is the empty editor, but there's no doubt some other ready-made scenarios we could provide that would be helpful.

**Comment by ianstormtaylor** [comment]
I like this idea, but I think the examples are already a lot of maintenance work, so it might be better as fiddles that people can use themselves instead.
