### ISSUE TITLE
cannot run examples locally

### ISSUE THREAD

**Issue by podviaznikov** [ianstormtaylor/slate#231]
I followed instructions here https://github.com/ianstormtaylor/slate/tree/master/examples
but after running `npm run examples`
I've got following error:
```
Error: Cannot find module 'fbjs/lib/keyOf' from '/Users/podviaznikov/os-libs/slate/node_modules/react-frame-aware-selection-plugin/dist'
```

Not sure why that is happening since `npm install` worked without errors

**Comment by ianstormtaylor** [comment]
Odd I'm not getting that, but what version npm are you using? I'm on:

```
$ npm -v
3.10.3
```

Might be an issue for `2.x` versions?

If so, can you try doing `npm install --save-dev `fbjs` and see if that fixes the issue? or if there are any others that are missing for `2.x`? If so I can make a quick commit with dev dependencies of whatever else is missing. Thanks!

**Comment by podviaznikov** [comment]
Yeah, I was using npm@2.8.3.

`npm install --save-dev fbjs` solved the problem. Thanks!
