### ISSUE TITLE
Easy way to test old versions in fiddles.

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2313]
#### Do you want to request a _feature_ or report a _bug_?

_idea_

#### What's the expected behavior?

It would be great to be able to test against previous versions easily in fiddles so that we can tell where a bug may have come in. I'm not sure if there are already versioned assets out there, but maybe there is an easy way to switch between them?

Maybe it would be good to have a custom example fiddle for each major version? Though I'd hate to have yet one more maintenance step.

cc @Slapbox

**Comment by Slapbox** [comment]
Yeah I noticed yesterday that it didn't seem possible. @ianstormtaylor I know you've got a lot on your plate, but in the interest of trying to take some of that off in the future, how are you hosting the current version on slatejs.org? Would it be possible to host old versions as well? I'd be happy to help with this if I can.

**Comment by ianstormtaylor** [comment]
I think you should be able to use Unpkg to point to any of the older releases of the `slate-*` libraries. It the JSFiddle you'd replace the existing URL to Slate with the old-versioned URLs instead.

**Comment by Slapbox** [comment]
@ianstormtaylor you are indeed correct. I didn't realize they were all cached up in there automatically.

I still think it would be potentially more helpful to host the old versions of examples for quicker/easier reproduction, but for now anyone who needs to use an old version of Slate related libraries can use this as a template to figure out what the URL they need is:

https://unpkg.com/slate@0.41.0/

![image](https://user-images.githubusercontent.com/6835891/47460333-3ba7ce80-d7ac-11e8-8fb8-3b99ee285797.png)

Then just point the fiddle at the relevant file inside the `dist` directory

**Comment by ianstormtaylor** [comment]
Right now it's hosted on Netlify. If someone knows of an easy way to opt-in to having multiple builds for each release I'm down, but I don't want to add complication to the system otherwise. If people need it they can create a JSFiddle with it I think.

**Comment by Slapbox** [comment]
Makes perfect sense to me. I don't know if Netlify for open source is limited, but this doc indicates it might be possible and easy. If accurate, it sounds like the main difficulty would be making those addresses publicly available automatically.

https://www.netlify.com/docs/versioning-and-rollbacks/

> Versioning & Rollbacks
> Netlify versions all deploys. From the “Deploys” tab for your site in the netlify UI, you can browse any deploy you’ve ever made and preview it from a unique URL.

**Comment by Slapbox** [comment]
Codesandbox is better - You can simply define versions in a package.json and it loads them

https://codesandbox.io/s/6wm7p6vmn
