### ISSUE TITLE
make `insertBlock` work with unset selections

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2329]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Right now `insertBlock` inserts based on the current selection. But if the selection is unset because there are no nodes in the document, it will fail.

#### What's the expected behavior?

Instead, I think it should default to inserting at the end of the document in this case, and focusing the editor. This way you don't have to always make this distinction yourself and branch in your own code, since it's a common use case.

**Comment by ericedem** [comment]
Where would the selection go, probably at the end of the inserted block?

**Comment by ianstormtaylor** [comment]
@ericedem yup!

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
