### ISSUE TITLE
`replaceNodeByPath/Key` should maintain selection

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2330]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Right now if you use `replaceNodeByKey` to replace the node that contains the current selection, it will end up unset.

#### What's the expected behavior?

It should preserve the current selection offset into the new node.

**Comment by zhujinxuan** [comment]
Hi, two small questions:
1. Shall we add an operation as replace_node?  Because inversing `insert_node + remove_node` cannot restore selection.
2. What shall we do if the new node's text length is smaller than the current offset.  For example, replacing
```
<block>cat<cursor/></block>
```
with 
<block>a</block>

**Comment by ianstormtaylor** [comment]
Hey @zhujinxuan good questions!

1. I think we don't need `replace_node` yet, and we can have the extra `set_selection`, since this isn't operation-level but a command instead.
2. I think we'd put it at the end of the block in that case, the closest it can get to where it previously was inside the block.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
