### ISSUE TITLE
add `indent/outdentBlocks` commands

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2331]
#### Do you want to request a _feature_ or report a _bug_?

Feature.

#### What's the expected behavior?

There are lots of use cases that make use of "indenting" and "outdenting". The native `beforeinput` events even tap into them too. I think it would be good to standardize `change.indentBlocks` and `change.outdentBlocks`, so that other plugins can build on them. For example, a quote behavior plugin could listen for `'indentBlocks'` and do quote-specific behaviors.

By default, I think it should look for the top-level blocks and double nest them. Such that this:

```jsx
<quote>
  <paragraph>
    <anchor />one
  </paragraph>
  <paragraph>
    two<focus />
  </paragraph>
</quote>
```

Would turn into:

```jsx
<quote>
  <quote>
    <paragraph>
      <anchor />one
    </paragraph>
    <paragraph>
      two<focus />
    </paragraph>
  </quote>
</quote>
```

**Comment by Dundercover** [comment]
I think there are quite a few different approaches people take to denote indentation. Those I've guessed are the most used:

- **Double nest single block.** Like you described above. Could also be leaf block. 
- **Double nest multiple blocks.** Like with html `ul`/`ol` + `li`.
- **Additional data on block node.** Like `{ indent: 2 }` or something.

Default behaviour of this command wouldn't be able to handle all of these but support for them would be nice somehow.

Maybe we could make a plugin which you could configure for your use case? (If it doesn't already exist such plugin?)

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
