### ISSUE TITLE
add `Hotkeys` plugin

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2332]
#### Do you want to request a _feature_ or report a _bug_?

Feature.

#### What's the expected behavior?

Right now we're defining all of the hotkeys in one-off `keydown` logic. It would be nice to pull this out into a hotkey-specific plugin called `slate-hotkeys` and expose it for others to use in their own codebases.

For example, it would look like:

```js
Hotkeys({
  hotkeys: {
    'escape': (event, change) => {
      event.preventDefault()
      change.moveToStart()
    },

    'shift+enter': (event, change, next) => {
      if (!change.isSoftBreakEnabled(change.value)) return next()
      event.preventDefault()
      change.insertText('\n')
    },

    'mod+enter': (event, change, next) => {
      if (change.isCodeBlockActive(change.value)) {
        event.preventDefault()
        change.moveToStartOfNextNode()
      } else {
        return next()
      }
    },

    'mod+a': (event, change, next) => {
      change.selectAll()
    },
  }
})
```

We can then define all of the core hotkeys in `slate-react` using this plugin, cleaning things up a bit. This encourages the architecture we want to encourage which is that hotkeys are small handlers that call into "commands" as soon as possible. This keeps things easier to test.

Along with this, we would deprecate the current `slate-hotkeys` package which contains the hotkey constants. This is by design, because we don't want people relying on constants. They should hook into commands with `onCommand` instead.

**Comment by Dundercover** [comment]
Are we creating a new package or just change what's inside?

**Comment by brendancarney** [comment]
Oh nice, I hadn't seen this issue and was thinking the same thing: https://github.com/ConvertKit/slate-plugins/tree/master/packages/slate-keymap

@ianstormtaylor if you want this in core, I'd be happy to add it and deprecate our package. The only real difference appears to be that we support a string argument to call a command:

```
Keymap({ enter: "softBreak" })
```

We could go with or without that functionality, up to you.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
