### ISSUE TITLE
simplify the "Change vs. Editor" question

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2334]
#### Do you want to request a _feature_ or report a _bug_?

Idea.

#### What's the current behavior?

This is something I was discussing with @alanctkc in Slack. Right now, there are two "main" instances that you care about when developing plugins: the `Editor` and the `Change`.

This issue is that they are used semi-interchangeably, but they're different. For example commands receive a `change` object. Whereas queries receive an `editor` object. And event handlers receive a `change` object. But components should receive an `editor`.

That alone isn't a huge deal, but it does complicate things.

But things get worse when you consider that there is confusion between `editor.value` and `change.value`—people might not even realize they are different. But `editor.value` is the currently rendered value of the editor, and it only changes after new props are passed in. Whereas `change.value` is the most-up-to-date value object that has the newest operations in the change applied to it.

This distinction is a bit complex. It means that you can't just access `editor.value` in your queries and have everything work as expected.

#### What's the expected behavior?

A fairly simple solution that @alanctkc came up with is to change queries to actually be passed a `change` object, which will default to the currently active change. This seems strange, but it's actually kind of ingenious because it means that queries can always access `change.value` as the most-up-to-date.

This could work.

---

I was wondering though, if there might be a slightly different solution that we could use, by getting rid of the current `Change` object altogether. Sounds drastic, but it might actually result in a simpler mental model.

It would entail...

- [ ] **Registering commands and queries directly on editor.** Right now if you want to invoke a command on the editor you do `editor.command('insertText', 'word')`. Whereas if you want to invoke it on a change you do `change.insertText('word')`. Under the new architecture, the commands and the queries would be available as top-level methods on the editor itself:

```js
editor.insertText('word').splitBlock()
```
```js
if (editor.isQuoteAllowed()) {
  editor.setQuoteBlock()
}
```

- [ ] **Tweak changes would be emitted asynchronously.** To make this possible, we'd tweak the current logic to emit changes via `onChange` in an asynchronous way, more similarly to how `setState` works. (The current synchronous architecture might [already be causing problems](https://github.com/ianstormtaylor/slate/issues/2282).) Any command would queue a change (just like React state does) and then the queue is flushed on the next tick. That way you can continue chaining commands synchronously just like you can now.

- [ ] **Change `editor.value` and `editor.operations` to update synchronously.** As you invoke commands, the `editor.operations` will now hold all of the operations that have been created, and `editor.value` will now update to reflect those operations being applied. This means that you can always grab `editor.value` and know that it is the most up-to-date state, without worrying about any sort of race conditions. Although changes are emitted asynchronously, the `editor.value` stays up to date, so testing remains straightforward:

```js
it('my test', () => {
  ...
  fn(editor)
  assert.deepEqual(editor.value.toJSON(), expected.toJSON())
})
```

- [ ] **Remove the need for `editor.change`.** With the commands registered directly on the editor, and the changes emitted asynchronously, you no longer need to do `editor.change(change => change.splitBlock())`, because you can call `editor.splitBlock()` directly. This would reduce a decent amount of verbosity in the codebase.

- [ ] **Remove the current `Change` object.** With all of that, you no longer need the `Change` object as we know it today, since all of its behaviors are present on the editor. Instead, we'd introduce a super-super-thin `Change` model which holds `value/operations` and is emitted to `onChange`. This is the only place we still benefit from having a separate "change" that can be referred to on its own.

- [ ] **Pass `editor` to commands and handlers.** With the `change` objects eliminated, all of the middleware can now receive the `editor` directly, so there's no confusion. And commands, queries, and event handlers become even simpler to reason about:

```js
onKeyDown(event, editor, next) {
  if (event.key === 'Enter' && event.shiftKey && editor.isParagraphActive()) {
    event.preventDefault()
    editor.insertText('\n')
  }
}
```

- [ ] **Allow `editor.command/query` to take functions.** One thing that is useful on the current `change` object is the `change.call` method. This functionality can easily be added to the `editor.command` and `editor.query` methods instead, which actually makes plugin development even easier because users can supply commands as name strings or as custom functions:

```js
Linkify({
  when: 'isLinkAllowed',
  command: 'setLink',
})
```
```js
Linkify({
  when: editor => ...,
  command: (editor, url) => ...,
})
```

- [ ] **Remove the `editor.event` method.** This is low-level, but eliminating the need for `Change` objects allows us to remove one more method on the editor, because the `editor.event` method was only needed to create an interim change object. Without them, we can use `editor.run` directly in tests:

```js
editor.run('onKeyDown', { key: 'Tab', ... })
```

- [ ] **Potentially introduce a "flags" concept.** Right now there are some native flags that are special-cased: `withoutNormalizing`, `withoutSaving`, etc. These *can* be implemented in userland, but it's sort of hacky. We could choose to add a "flags" concept, which could allow them to be "registered" just like commands and queries are:

```js
onConstruct(editor, next) {
  editor.registerFlag('saving')
  next()
}
```

**Comment by bryanph** [comment]
So how would you compose multiple changes without a Change model? Say I want to call
```
editor.insertText('abc')
editor.insertBlock(...)
...
```
And have it be one atomic change?

Either way I think it is probably a good change for newcomers to the library.

**Comment by ianstormtaylor** [comment]
@bryanph good question!

All of the commands executed before a change is "flushed" on the next tick would have their operations grouped into a single "change" that is passed to `onChange`. This is pretty much the same way it is today, since you can't effectively separate out operations into two changes (almost ever, although a few cases can).

(Note that this is separate from how the history chooses to group them.)

Later on, if we wanted to introduce a proper feature for "grouping" changes in the history, I think it would make sense. And it would benefit from having the `editor.change()` grouping removed in terms of conceptual overload too I bet.

**Comment by grsmvg** [comment]
This looks really good. Takes away a lot of the confusion and it doesn't seem to limit any of the stuff I'm already doing now.

Btw; what happens if you invoke a command from within a query? Are those changes emitted or do they only live for the lifetime of the query?

**Comment by ianstormtaylor** [comment]
@grsmvg glad to hear it 😄 And good question! Technically you could invoke commands from inside queries, and they'd be just like normal. Although this is probably an anti-pattern and wouldn't be recommended.

**Comment by grsmvg** [comment]
Yeah, it's definitely an anti-pattern. I was also not planning on doing that, but just wondering since editor.change does get passed to the query. We could shut down this loophole by:

1. Passing a read-only version of the editor into a query function
2. Turn it into a feature, making changes inside a query scoped to only that query. That way you can make queries that try out some changes to see if they lead up to a certain resulting value. Anyways, I don't have any use case for that now. This is slightly off-topic also 😇

**Comment by alanctkc** [comment]
I don't think I even thought about `editor.command()` and `editor.query()` already existing like that! This is most likely what I would do in my own code, as long as chaining worked as expected.

**Comment by ianstormtaylor** [comment]
> @ianstormtaylor , I've npm'linked your branch into our codebase, and again, much to refactor, but the end looks very promising! I like it!
> 
> Seems like we can get rid of a lot of code/cruft with this simpler API. It's also much easier to follow what's actually is going now as editor.value is now the only place to read the value, and changes are more atomic. Just made things a lot clearer and to the point which again is inspiring for finding better ways to solve problems.

@skogsmaskin that's really good to hear! It is nice how the API continues to feel better and better as we figure out what we're really trying to achieve 😄 

> I had an idea btw: when doing `editor.command('something')` - what about the possibility to register a callback function that will be called when the command has actually become processed (like manifested in the value)?

What's your use case for this? I'm not opposed, just curious. Right now the command is immediately manifest in `editor.value`, if that's what you mean.

> (sorry for editing your comment btw, I couldn't resist clicking on the checkboxes and didn't know I was actually performing edits in realtime :D )

Haha no worries! Checking the boxes is great.

**Comment by ianstormtaylor** [comment]
@skogsmaskin I think in most cases the rendering was async before and after this change due to the `value` probably being stored using `setState` at a level above the editor, so this won’t effect that. 

That’s said, feel free to open a new issue if you’d like and we can discuss it and people can weigh in.

**Comment by skogsmaskin** [comment]
> I think in most cases the rendering was async before

That is true. I'll open an own issue. Great to se the PR already merged! :+1:

**Comment by Dundercover** [comment]
Sorry for coming in with a side note but from a purely usability point of view I think both dynamic methods and methods identified by strings are bad since they are too implicit and won't let you follow the execution flow on the highest abstraction level.

Instead of `editor.insertBlock` or `editor.command('myCustomCommand')` I would much rather use

```
import { insertBlock } from 'slate/commands';
import myCustomCommand from './my-custom-command';

...

editor.command(insertBlock);
editor.command(myCustomCommand);
```

I think this is much easier to follow and any editor is able to jump to these references out of the box.

**Comment by ianstormtaylor** [comment]
Hey @Dundercover that's a great point, and a good potential solution. The good news is that that is an option for people to use in the current API, since `editor.command` accepts a function argument.

And then in the future we can decide to settle towards any one of these three as the "one true" approach and potentially deprecate the others. The reason I don't want to make the call yet is (a) because I'm not 100% in any direction, and (b) because the migration path is easier for now if we don't restrict it. So to me it seems like we might as well defer the decision to when we have more information.

But I'll open an issue now to make a note of your suggestion, since I think it's a good one, for down the line.
