### ISSUE TITLE
Deleting selection across nested blocks results in an error (`Node.assertNode` could not find node with path or key)

### ISSUE THREAD

**Issue by karelskopek** [ianstormtaylor/slate#2336]
#### Do you want to request a _feature_ or report a _bug_?

Bug. 🐛 

#### What's the current behavior?

When you select a list branch with more then three levels of nesting and try to delete it, it will result in an error. For example:

> `Node.assertNode` could not find node with path or key: `List [ 0, 1, 0, 0, 0, 0 ]`

This behavior, however, won't happen when you select multiple branches (see the recording).

##### CodeSandbox reproduction
[https://codesandbox.io/s/6ykzw473wz](https://codesandbox.io/s/6ykzw473wz)

##### GIF
![GIF](http://g.recordit.co/oUxJCiHHQj.gif)

##### Environment

- macOS High Sierra
- Chrome 70
- `slate@0.42.6`
- `slate-react@0.19.8`

#### What's the expected behavior?

Expected behavior is to delete the selected content.

**Comment by skogsmaskin** [comment]
It's happening here [packages/slate/src/utils/path-utils.js#L323](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/utils/path-utils.js#L323)

The operation:
```
{
  "object": "operation",
  "type": "merge_node",
  "path": [
    0,
    1,
    0,
    1
  ],
  "position": 0,
  "properties": {
    "data": {}
  },
  "target": null
}
```

The result is ``List [ 0, 1, 0, 0, 0, 0 ]``

**Comment by skogsmaskin** [comment]
Heh, seems like it was just a matter of making it the oppoiste order:

```
      path = increment(path, position, pIndex + 1)
      path = decrement(path, 1, pIndex)
```

**Comment by Airkro** [comment]
same error in `Microsoft Edge 12` when I dragging text.

**Comment by juliankrispel** [comment]
a failing test with this would be nice :+1:

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
