### ISSUE TITLE
Can I use slate as a mention-box in Angular 6?

### ISSUE THREAD

**Issue by silentsnooc** [ianstormtaylor/slate#2339]
I'm sorry, this is not an issue but a question - but maybe it's also just an idea: *slate*'s upcoming "mention-box mode". I have tried (and failed) a few times to build a simple "mention-box" for myself which has only one job: Allow user to mention something and further serialize it into some markup for me to POST it to my backend.

Here is my [mention-box](https://stackblitz.com/edit/mention-box) experiment on stackblitz but well.. it's just not working as it should. 

So here's the question: Will I be able to use/modify *slate* such that:

- Users can use `#` to mention items
- Filtering items is customizable by just providing a `myFilter` method
- The dropdown menu is custimizable (e.g. display location & elements can be both clicked and selected with <kbd>Enter</kbd>)
- I am able to serialize something like `<span id="person:1337" class="person-ref">Mary</span> has a lamb` to `<person id="1337"/> has a lamb`. Obviously I'll have to do the serialization myself but maybe *slate* delivers some support to make things easier.

There is *slate*'s [mention demo](https://www.slatejs.org/#/mentions) but there are some things missing:
- Dropdown shows only up if user has typed something
- One cannot use the keyboard to select items

Also: I am not sure how much effort it is to use *slate* in Angular 6. I couldn't see any instructions on the main page. 

If somebody could shed me some light on whether I should consider *slate* that would be great.

At this point I took a look at quite a few editors and I had to turn away from all of them - everytime for another reason. Just to sum up my experience with rich text editors:

<img src="https://imgs.xkcd.com/comics/standards.png">

(source [xkcd](https://xkcd.com/927/))

**Comment by ianstormtaylor** [comment]
Hey @silentsnooc, Slate isn't built for Angular. But you can always embed React inside Angular if needed. As for the mention UX, all of that is customizable and a lot of it is outside the scope of something Slate would do for you—not that's it's not possible (it is definitely possible) but it's more of a "your code" thing than a "Slate's code" thing. For future questions, the best place to ask is our Slack channel.

**Comment by silentsnooc** [comment]
@ianstormtaylor Alright, got it. Thanks for the quick response :)
