### ISSUE TITLE
Single node inline void in a block prevent edition of text

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#234]
When a block (for example a `paragraph`) contains a single inline void node, it's not possible to insert text before or after.
It's working as expected, if some text nodes are already existing.

JSFiddle to reproduce the issue: https://jsfiddle.net/rhmkxsd5/

**Comment by ianstormtaylor** [comment]
Ah, interesting case! Basically we need to either:

- Normalize the document to always wrap single `isVoid: true` inline nodes in a text node on either side, to preserve the ability to move the selection there and insert text.
- Or to render fake "leaves" on either side of the inline void node if it's the only child, also allowing the selection to be placed there.

I'm not actually sure which solution is best, but if you get either working I'd accept a PR! Let me know if that makes sense, or I can explain my thoughts more.

**Comment by SamyPesse** [comment]
> Normalize the document to always wrap single isVoid: true inline nodes in a text node on either side, to preserve the ability to move the selection there and insert text.

From my understanding, it looks like the best solution. Rendering fake"leaves" may result in a lot of conditions to test if a leave is a normal one or not; when normalization is just a transformation of state.

Concerning normalization, there might be a few other thing that should be normalized in the Slate core, for example ensuring that an inline node doesn't contain block nodes.

**Comment by SamyPesse** [comment]
I can try to work on a PR for the `Normalize the document to always wrap single isVoid: true inline nodes in a text node on either side, to preserve the ability to move the selection there and insert text.`.

**Comment by stefan1968** [comment]
Unfortunately this is a big deal for me as i need to get inline images working. Any temporary workaround?

**Comment by bkniffler** [comment]
@ianstormtaylor I guess the fake leaf option would be the more elegant way, but harder to implement for people who do not yet fully understand the ins and outs of slate. I've tried manipulating `renderElement` in `components/node` using something like the fake leaf renderer in `components/void`, but no success yet. I wonder how I could go and create a real leaf as soon as text is inserted in the fake leaf.

**Comment by ianstormtaylor** [comment]
@bkniffler I think @SamyPesse is right that going the normalize route would be best, since the fake leaf I think will make for some weird `.transform` or `.get` operations. Basically we just need to edit `Node.normalize()` to handle this case properly
