### ISSUE TITLE
slate-md-serializer with Next.js

### ISSUE THREAD

**Issue by markolofsen** [ianstormtaylor/slate#2340]
Got an error... when trying serializer/deserialize slate-tree into/back Markdown (NEXT.JS)

```
import MdSerializer from 'slate-md-serializer'
console.log(MdSerializer.deserialize(''))
```

**Error:**
`TypeError: slate_md_serializer__WEBPACK_IMPORTED_MODULE_6___default.a.deserialize is not a function`

**Comment by ianstormtaylor** [comment]
Hey @markolofsen this repo doesn't have the `slate-md-serializer`, but feel free to open this up on that one!
