### ISSUE TITLE
Command callback functions?

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#2341]
#### Do you want to request a _feature_ or report a _bug_?
*Maybe* request a feature / discussion
_
#### What's the expected behavior?

The possibility to add a callback function to the editor commands that gets called when the editor has finished executing the command, and is emitting it to onChange. As commands can be async, we really don't know when they (potentially) will manifest themselves in DOM changes through an onChange.

Illustrated by an example:

You have a toolbar with a button that inserts a special void block. The command grabs stuff from the net first to populate the block, so you don't know how long it will take. The block has an non-slate-managed editing interface that is inside a popover. You would like to open up this popup when the block is inserted into the editor, pehaps position it near the renderend block. Normally you would click an edit button on the block, but when it is first inserted you would like to show it to allow the user to immediately edit it through the popup .

```
      const showPopupCallbackFn = editor => {
        // A small timeout to make sure React has applied new State value from onChange.
        setTimeout(() => {
          const domNode = findDOMNode(editor.value.focusBlock)
           // Open popup etc
           ....
        }, 10)
      }
      editor.command('insertBlockThatGrabsSomethingFromTheNetFirst', {..someOptions}, showPopupCallbackFn)
```
 
The idea is to be able to write code in the vicinity of where you call the command, and know that the command is applied through onChange when that code runs.

The question is, *is it useful*? Or does it just add complexity with minor benefits, and incite anti patterns? 

Thoughts?

**Comment by ianstormtaylor** [comment]
@skogsmaskin thanks for the example, that's helpful. It sounds like it might be something that is best handled in React itself. You could toggle a value, and then handle this in `componentWillUpdate`?

**Comment by skogsmaskin** [comment]
@ianstormtaylor , yes as for the concrete example there are probably many ways to solve it better, and I agree it sounds like something that should be solved in React. But it explains the problem pretty well, where you have something somewhere executing a command and you would like to do stuff after the command is executed and propagated to the the visual editor (whatever it is).

I think a callbackFn can facilitate this without the need of passing  props,  or manipulate editor values themselves with non-relevant data. I'm sure there are other use-cases too, and that's mainly what I want to check with the issue.

**Comment by dselman** [comment]
I _think_ I have a use case for this. We are building a code-style editor using Slate. When the text is modified it needs to be parsed on the server (via an HTTP call). When the server returns the text should be updated with the details of any parser errors.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
