### ISSUE TITLE
Link nodes behavior mismatches across browsers

### ISSUE THREAD

**Issue by juangl** [ianstormtaylor/slate#2348]
#### Do you want to request a _feature_ or report a _bug_?

Bug report

#### What's the current behavior?

Currently typing something at the end of a link node works different across both browsers. On Safari, characters are appended to the link, on Chrome, characters are inserted after the link.

#### Browser versions:
- Safari: Version 12.0 (14606.1.36.1.9)
- Chrome: Version 70.0.3538.77
- This is happening on iOS too (I can confirm version 12 and 11.4), both Chrome and Safari since they use the same engine.

Happy to working on this if someone could point me out some piece of code to look at.

http://g.recordit.co/TbPB0wP34G.gif

![screen recording](http://g.recordit.co/TbPB0wP34G.gif)

#### What's the expected behavior?

Links should behave the same on both browsers.

**Comment by Slapbox** [comment]
I can't easily test in Safari, but this does appear to be an issue. @juangl, can you provide the browser version numbers too?

**Comment by yangguoquan** [comment]
Does anyone solve this problem?

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3151
