### ISSUE TITLE
Select a text input, input method automatically disappear

### ISSUE THREAD

**Issue by zjfjiayou** [ianstormtaylor/slate#2350]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Environment：
- Windows 7 64
- Chrome 49
- slate 0.43.0
- slate-react 0.20.1

Select a piece of text and type in Chinese. The input method will automatically disappear and cannot get the correct input result, as shown in the picture below

![qq20181030-144717](https://user-images.githubusercontent.com/7593789/47702392-bd3da780-dc57-11e8-8df0-f9a46600c98f.gif)

#### What's the expected behavior?
Input Chinese correctly

**Comment by ericedem** [comment]
@zjfjiayou Do you have a Fiddle or example for this? It's unclear from the gif whether this is a Slate bug or possibly something else going on.

**Comment by Slapbox** [comment]
@zhujinxuan this is new as of `Slate@0.43`, right? Probably related to async changes affecting the focus/blur methods of the editor.

**Comment by zjfjiayou** [comment]
@ericedem Thank you very much for your reply, I created an example here https://github.com/zjfjiayou/slate-test/tree/master
You can activate him with the following command
`npm i && npm start `
Before that, you'll need to prepare for Windows 7 and chrome 49, which you can download here
https://www.slimjet.com/chrome/download-chrome.php?file=win%2Fchrome64_49.0.2623.75.exe

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
