### ISSUE TITLE
Focus is lost when tabbing into a Slate editor

### ISSUE THREAD

**Issue by steobrien** [ianstormtaylor/slate#2352]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Pressing tab from either a plain input or another Slate editor, to focus a Slate editor, results in a cursor very briefly showing (~100ms) in the editor, which then disappears and focus is lost.

Example gif from https://www.slatejs.org/#/syncing-operations:

![gifable-01df4f01-365f-406a-988a-ea451425ceee](https://user-images.githubusercontent.com/1694410/47733990-d6d2f500-dc3f-11e8-921e-8d079cbdb07e.gif)

(This is a little hard to make out: I'm clicking into the first editor and pressing tab on my keyboard. You can see a flash of cursor in the second editor a few times.)

#### What's the expected behavior?

A tabbed-to editor should obtain and maintain focus

<hr />

Some background in a related issue: https://github.com/ianstormtaylor/slate/issues/2147#issuecomment-434334329

**Comment by steobrien** [comment]
For now, we’re working around this using the approach outlined in https://github.com/ianstormtaylor/slate/issues/2147#issuecomment-417965381.

**Comment by Slapbox** [comment]
This is likely related to changes becoming async in `slate@0.43` - I've also had to implement some workarounds.

**Comment by steobrien** [comment]
@Slapbox I think the problem may predate `0.43` – we saw this issue appear in our app when upgrading from `0.13` to `0.41`.

**Comment by Slapbox** [comment]
Wow that's one big upgrade, and you're right. Here's a link where you can use Slate as it was with PR #2100 
https://deploy-preview-2100--slatejs.netlify.com/#/syncing-operations. #2100 wasn't committed, but that corresponds roughly with Slate `0.37`:

By #2112 the issue appears: https://deploy-preview-2112--slatejs.netlify.com/#/syncing-operations, which corresponds roughly with Slate `0.38` or `0.39`

Some change in that time period seems to be responsible.

You can view the times that all versions were published with the command `npm info slate time`
