### ISSUE TITLE
Input text behind a link width IME the editor would render the link error when composing

### ISSUE THREAD

**Issue by cainiao222** [ianstormtaylor/slate#2358]
In the demo website of slate, when input some content width IME in the end of a link, the link would be rendered error when composing, when delete the link the editor would throw an error.

![qq20181101-165158](https://user-images.githubusercontent.com/22426345/47842136-cd3fbd80-ddf6-11e8-952e-5c43c61b49f4.gif)

 OS: mac, browser: safari and chrome ,  the slate version : 0.43.3,

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368.
