### ISSUE TITLE
white-space and justify align

### ISSUE THREAD

**Issue by j-san** [ianstormtaylor/slate#2359]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

When using css `text-align: justify;` in the editor, text is not justified.

#### What's the expected behavior?

The text is justified as expected.

On the editor node there is an inline `white-space: pre-wrap` and this looks like prevent `justify` to works correctly. using `white-space: pre-line` looks to solve the issue.

**Comment by isubasti** [comment]
@j-san white-space style is overwritable by giving `style={{whiteSpace: "pre-line"}}` as the editor props. Although, if I remember correctly there are some problems with `white-space: pre-line` on some browsers as well, so I remove justify content option on the project that I'm working on.

**Comment by j-san** [comment]
Yes, it's also what i figured out. My solution is to keep slate behaviour (with `white-space: pre-wrap`) and add  `white-space: pre-line` on justified text only.

**Comment by darshanshah** [comment]
but you cannot add spaces to the justified white-space: pre-wrap conent.
can only add one space max in firefox
