### ISSUE TITLE
Allow running custom normalizers before default normalizers

### ISSUE THREAD

**Issue by timobetina** [ianstormtaylor/slate#2361]
#### Do you want to request a _feature_ or report a _bug_?
feature

#### What's the current behavior?
Currently core schema rules take precedence over custom rules.
Example situation: A not valid html (such as text and blocks are siblings) is copied into editor. Then slate's defaultNormalize removes the blocks and only preserves the text.

#### What's the expected behavior?
It would be nice to be able to specify custom schema rules which would run before core schema rules.

**Comment by CameronAckermanSEL** [comment]
Do we have any ideas for what this interface could look like?

**Comment by Malgalad** [comment]
What adding `enforce` property to a rule, similar to [webpack](https://webpack.js.org/configuration/module/#rule-enforce)? So you can add rules that run before or after other ones.

**Comment by CameronAckermanSEL** [comment]
I really like that idea :)

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
