### ISSUE TITLE
IE11:  Doesn't allow cursor to focus or edit text on editor input 

### ISSUE THREAD

**Issue by lranches-sfdo** [ianstormtaylor/slate#2364]
#### Do you want to request a _feature_ or report a _bug_?

Bug 🐛 

#### What's the current behavior?'
![ie-rteditor](https://user-images.githubusercontent.com/43382367/47881688-176b7380-dde4-11e8-8fc3-bf72f6d53cb6.gif)

Using Internet Explorer 11, if the editor input already contains text. It won't allow on click to focus on the Editor Input and edit. Also upgraded to the latest Slate versions and still has the same issue but posted the versions being used below. It also is working perfectly fine in Chrome.

Any help would be much appreciated! 

```    
    "slate": "^0.33.4",
    "slate-react": "^0.12.4",
```

#### What's the expected behavior?

Working on Chrome!

![chrome-rteditor](https://user-images.githubusercontent.com/43382367/47881702-1f2b1800-dde4-11e8-8d86-36f2dc0def76.gif)

**Comment by isubasti** [comment]
@lranches-sfdo 	do you have polyfill for IE, I think it might be due to IE 11 doesn't have `Element.closest` and slate relies on that and it's not included hence you need to include your own.

**Comment by lranches-sfdo** [comment]
@isubasti Thank you for your response. We actually have the closest polyfill for IE and still no luck :(. Any other ideas?

**Comment by lranches-sfdo** [comment]
Any updates? :)

**Comment by dannyiacono** [comment]
The same issue applies to your provided examples, for instance with your link demo: https://www.slatejs.org/#/links

**Comment by afrankel-sfdo** [comment]
I can't even get the site to load in IE11 on Windows 10 or 8.1...

![screen shot 2018-11-21 at 12 02 00 pm](https://user-images.githubusercontent.com/31106469/48863110-81dd5700-ed85-11e8-9973-21261e997332.png)

**Comment by ericedem** [comment]
@afrankel-sfdo Tracked here: https://github.com/ianstormtaylor/slate/issues/2385.

**Comment by afrankel-sfdo** [comment]
@eramdam thanks, that was just a sidebar while attempting to reproduce the editor issue in IE11 above.

**Comment by isubasti** [comment]
Kinda find out what the issue is but don't know how to fix it. It's due to Edge and IE behaviour on `contentEditable`. If the `Editor` does not have focus then native selection`s rangeCount is always 0(https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/after.js#L687). To verify this behaviour, make the `Editor` have `autoFocus` and go straight on clicking around the editor and it should works but once you clicked outside the editor and try to get back to it then you won't be able to select anything.

**Comment by epotockiy** [comment]
Fixed this by running ``editor.focus()`` without ``deselect()`` inside ``onFocus`` event in MS Edge, problem definitely are in new range selection, but i don't know how to fix it without removing function

**Comment by statianzo** [comment]
I've create a PR that removes `deselect` for IE in #2535. It solved the issue for me. Can others check it out?
