### ISSUE TITLE
refactor `Leaf` and `Text` logic

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2371]
#### Do you want to request a _feature_ or report a _bug_?

Debt.

#### What's the current behavior?

The `Leaf` and `Text` model logic has lots of code quality issues. Off the top of my head there are many things wrong...

- Methods that are `static` that don't need to be.
- Methods that shouldn't be exposed in the first place.
- Mismatches in how leaves of zero length are treated. (They shouldn't be allowed.)
- Redundancies in the code where things are calculated twice.
- Poor quality comments and formatting.
- And probably undiagnosed performance issues.

#### What's the expected behavior?

All of these things should be cleaned up, in a single PR or in many smaller ones over time.

**Comment by zhujinxuan** [comment]
Hi, @ianstormtaylor . Do you think it is a good idea to move `splitLeaves` and `createLeaves` from static function to utils/LeafUtils.js?

**Comment by zhujinxuan** [comment]
The zero length leaves are to support the marked empty paragraph like the Google Docs.  In Google Docs, if we mark a region as bold, the empty paragraph inside is also bolded (like the following gif):

![Bolded gif](http://g.recordit.co/9ZFXjeLR1l.gif)

I am not sure whether we shall still support this.  But if we still want to support that feature, without zero wide leaves, then perhaps we need to add mark property to Block or Text.

**Comment by ianstormtaylor** [comment]
I think keeping zero-width leaves is reasonable, and allowing marks on those zero-width leaves makes Slate more flexible. (Eg. for commenting on a void block.)

**Comment by ianstormtaylor** [comment]
This is done now that leaves were removed.
