### ISSUE TITLE
consider xstate

### ISSUE THREAD

**Issue by matt-erhart** [ianstormtaylor/slate#2372]
https://youtu.be/VSKuS2XkkZU
https://xstate.js.org/docs/guides/start/

Basically a way to model state that's easy to visualize and easier to test endless permutations of state transitions. See especially around the 17 min mark for an interesting testing example.

**Comment by brendancarney** [comment]
xstate does look cool, but I'm not sure it's a good fit for slate, and I don't think a low level library like slate should depend on a state abstraction. I don't exactly see how the data model would fit into something like x state, so if you could provide some example, that would be great.
