### ISSUE TITLE
"Versions" example is broken

### ISSUE THREAD

**Issue by Dundercover** [ianstormtaylor/slate#2375]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

In the "Versions" example when choosing a version from the dropdown nothing happens and you get an exception in the console (`Uncaught TypeError: e.invert is not a function`).

#### What's the expected behavior?

When choosing a version from the dropdown the editor should change its content to whatever selected version contains.

**Comment by ericedem** [comment]
@bryanph any thoughts on how to fix this one? I think we had some changes in the way operations work recently.
