### ISSUE TITLE
Demo page doesn't work on Safari

### ISSUE THREAD

**Issue by burlesona** [ianstormtaylor/slate#238]
Was just browsing and stumbled across Slate, but when I opened the demo in Safari 9.1.1, page load fails with error:

```
SyntaxError: unexpected keyword 'const'. Const declarations are not supported in strict mode.

build.prod.js:62056
```

Just thought I'd let you guys know.

**Comment by ianstormtaylor** [comment]
Shoot, fix incoming! cc @vleletko

**Comment by vleletko** [comment]
should be fixed in #239

**Comment by ianstormtaylor** [comment]
Thanks @vleletko!

**Comment by ianstormtaylor** [comment]
Hey @vleletko it looks like the `./dist` folder of the package hasn't been updated, so `0.0.4` still has the `const` in it when downloading from npm.

**Comment by vleletko** [comment]
@ianstormtaylor right,, my bad. #242 with updated 0.0.5 version

**Comment by ianstormtaylor** [comment]
Fixed now. Thanks again @burlesona for letting us now!

**Comment by burlesona** [comment]
No prob :)






On Sat, Aug 13, 2016 at 7:24 PM -0400, "Ian Storm Taylor" <notifications@github.com> wrote:












Fixed now. Thanks again @burlesona for letting us now!
