### ISSUE TITLE
Serializers returns an invalid document state - empty nodes do not get text nodes

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2381]
### Do you want to request a _feature_ or report a _bug_?

BUG

### What's the current behavior?

Deserializing HTML with the HTML Serializer leads to an invalid state - Empty nodes do not get `text` nodes inserted into them. This causes quite a few issues. This is related to https://github.com/ianstormtaylor/slate/issues/2260 

#### Example deserializing `<p></p>`

**Here's the values before and after focusing the editor with my mouse:**

![image](https://user-images.githubusercontent.com/6835891/48031325-c9c37380-e121-11e8-98de-0613faa1daa1.png)

### What's the expected behavior?

The value returned should pass at least Slate's internal normalization I think. I know about the change in `0.42` which says values can't be normalized on creation, but shouldn't they pass through a normalization based on at least Slate's internal rules about all blocks requiring at least one node?

@ianstormtaylor - Is this a fixable issue within the current architecture, or is this by design?

**Comment by ianstormtaylor** [comment]
This is correct, serializers themselves are schema-unaware and thus aren't "normalized". But if we're going to try to change this, first we need examples of the issue, because this is not something I want to change.

**Comment by CameronAckermanSEL** [comment]
My recommendation would be to think about a more elegant way to get a value normalized on creation. It's not hard, really, to stand up a new editor instance and use that to extract a normalized value as part of deserialization, but its a step that people probably wouldn't always think to do. 

I wonder if there's an appropriate place in the examples we can provide this step?  Maybe this document seems like a good place to throw in a note about passing the raw deserialized value through an editor. 

https://docs.slatejs.org/walkthroughs/saving-and-loading-html-content

**Comment by ruanyl** [comment]
The `normalize` isn't performing well on a large document, there are already several issues about it, I'd like to turn off `normalize` on the initial render of slate editor, otherwise, the UI is frozen because of normalizing. 

But if `normalize` is turned off, the document is not rendered correctly, those empty paragraphs will not be rendered.

Is there a function exposed at somewhere that I can do normalize manually myself? @ianstormtaylor

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
