### ISSUE TITLE
IE11 slatejs.org breaks due to `includes()`

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2385]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

Looks like a use of includes in [`slate-dev-environment`](https://github.com/ianstormtaylor/slate/blob/fa343c07f4d9bb8840c5a85ecd8efc617dbabde1/packages/slate-dev-environment/src/index.js#L112) is not getting transpiled for IE11. And is blowing up on https://www.slatejs.org/.

![ie11_includes_broken](https://user-images.githubusercontent.com/1060669/48080471-9bd24380-e1a2-11e8-8d93-31675d893e7f.PNG)

#### What's the expected behavior?

It looks like this module is missing in transpilation. IE11 is in the browserlist, so maybe some other configuration is interfering?

**Comment by ericedem** [comment]
Found trying to verify https://github.com/ianstormtaylor/slate/issues/1015

**Comment by CameronAckermanSEL** [comment]
Is this something that needs to be solved with an IE11 polyfill?

**Comment by dmitrizzle** [comment]
I think it would be good to document somewhere a list of correct polyfills required to run older browsers. Perhaps `babel-polyfill` is enough.

**Comment by isubasti** [comment]
hm... this is weird as `Array.prototypes.includes` should be included by polyfill.io

**Comment by dannsam** [comment]
It fails in https://github.com/ianstormtaylor/slate/blob/44e47d7ffe0a821b744c431a7557bf72c9cdf291/packages/slate-dev-environment/src/index.js#L112-L113

Maybe `slate-dev-environment` is missing `babel-polyfill` ?
