### ISSUE TITLE
Create a draft of next changelog entry

### ISSUE THREAD

**Issue by Dundercover** [ianstormtaylor/slate#2386]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Two problems:

- The person creating a release might miss something when he/she writes the changlog entry.
- Contributors usually work on the latest commit on master which may contain changes they don't know about. 

#### What's the expected behavior?

Idea:

Keep a draft of the next changelog entry (either in `Changelog.md` or a separate file) which contributors can help write. When it's time for release, the person doing the release can just commit that draft.

**Comment by ianstormtaylor** [comment]
Gonna close this because although I agree that it's a nice idea, it's not something that is easy to manage or enforce while maintaining. And will end up just adding friction if we do force people to use it.
