### ISSUE TITLE
Merging blocks from inside Inline node deletes extra character

### ISSUE THREAD

**Issue by Malgalad** [ianstormtaylor/slate#2391]
Reproducible with [links example](https://www.slatejs.org/#/links).

**Steps**:
1. Place selection inside hyperlink, for example after "hype".
2. Press <kbd>Enter</kbd>.
3. Press <kbd>Backspace</kbd>.

**Expected**
- I get visually the same content as what I had at step one, that is hyperlink with "hyperlinks" text.

**Actual**
- Previous character is removed after merging blocks, e.g. "hyprlinks".

This does **not** happen if you move the selection outside of Inline block, for example by pressing <kbd>←</kbd> once after pressing <kbd>Enter</kbd>.

Edit:
![ice_video_20181107-145712](https://user-images.githubusercontent.com/1475852/48133043-2c417e80-e29e-11e8-9f0b-7c98b09ddbd8.gif)

**Comment by Malgalad** [comment]
I can try my hand at fixing it, but I need help with starting point. I couldn't even find where are the default event handlers, if there is such concept.

**Comment by CameronAckermanSEL** [comment]
I'd guess that this is a logical error in https://docs.slatejs.org/slate-core/commands#mergenodebykey-path
