### ISSUE TITLE
Placeholader was accidentally added

### ISSUE THREAD

**Issue by yunwuxin** [ianstormtaylor/slate#2397]
https://github.com/ianstormtaylor/slate/blob/f2f97e502e5fd648666960e823872d829be1ef99/packages/slate-react/src/plugins/react.js#L116-L124

```
{
  "document": {
    "nodes": [
      {
        "object": "block",
        "type": "paragraph",
        "nodes": [
          {
            "object": "inline",
            "type":"image",
            "data":{...}
            ]
          }
        ]
      }
    ]
  }
}
```

when `value` is like this ,  `placeholader` should not be added, but actually added.

**Comment by ianstormtaylor** [comment]
@yunwuxin wouldn't that get normalized to have text nodes on either side of the inline?

**Comment by yunwuxin** [comment]
@ianstormtaylor The place judged above is not

**Comment by ianstormtaylor** [comment]
@yunwuxin ah! I see what you mean, it doesn't take that into account. Sounds like we might need to tweak the check to only happen when there is a single text node too? `node.getTexts().size === 1`?

**Comment by yunwuxin** [comment]
It should be ok
