### ISSUE TITLE
Allow the user to specify what block type is "default" in the schema

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#2406]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

In userland, there is what I would estimate to be a nearly universal need to have some concept of a "default" block type. Some use cases for where the concept of the default block is important are:

* Preventing states where the editor is empty (this is probably handled manually by the vast majority of slate editors)
* Knowing what kind of block type to create when a block is split (this is not a core behavior but is sometimes overridden when splitBlock should not copy type)
* Knowing what kind of block type to return to when "toggling" block types from a toolbar (IE Paragraph -> H1, H1 -> Paragraph)
* Knowing what kind of block type to insert to provide padding between some void blocks, or blocks that need to be padded by at least one "simple" block (IE, I place a paragraph between two tables to keep them separated)
* Many plugins I have written or use require knowledge of the default block type, so this has to be passed in via props. It would be nice to for plugins to be able to query the editor for what the default block is instead of having to have it be specified by the user everytime the plugin is contructed

There's some others.

#### What's the expected behavior?

It would be useful for the editor to have some awareness of what the default block type is. This would afford several advantages:

1. Most importantly, we could have a core schema rule that prevents the editor from ever being empty, which is a source of many bugs and has to be implemented manually by most users.
2. Commands such as 'insertBlock' could have a good guess on what kind of block type should be inserted when its invoked.
3. We could prevent cases where a block type is somehow missing due to user error by falling back to the default type (debatable).

My recommendation is to provide a top level schema property called `default` which is

```
{
  default: String | Object | Fn
}
```
Where default is either the type string of the block, an object containing the properties of the default block, or a function that generates the default block.

**Comment by CameronAckermanSEL** [comment]
Added another use case for plugins being able to be aware of the default block type as opposed to forcing the user to specify it every time.

**Comment by brendancarney** [comment]
I like this idea. Most feature plugins I've written (lists, code editing,  quotes) have required the concept of a default block. I think this would improve developer experience.

**Comment by isubasti** [comment]
@brendancarney you can have a plugin that expose `getDefaultBlock` query

**Comment by brendancarney** [comment]
Yep, you could, but I think the developer experience would be better if it were in core. That being said, I'm sure there are some reasons it shouldn't be also, and I'd be interested in hearing those.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
