### ISSUE TITLE
Rich text sample seems to be broken

### ISSUE THREAD

**Issue by ufef** [ianstormtaylor/slate#2407]
I think rich text sample has got broken after recent changes. 
Try the following scenario:

https://www.slatejs.org/#/rich-text

Open the page, click outside of the editor area so focus gets lost, and then click again inside the editor.
It throws this exception:

`
TypeError: Cannot read property 'key' of undefined
    at a.n.renderBlockButton (https://www.slatejs.org/main-21d3cb05a6e56c129e06.js:42:22776)
...
`

The error is due to `value.blocks.first()` being null in this line of `renderBlockButton` method:
`
      const parent = value.document.getParent(value.blocks.first().key);
`

I am using Chrome 70.

**Comment by DouglasLivingstone** [comment]
This is also broken on iOS, so not browser specific.
