### ISSUE TITLE
When a large piece of text is pasted, it is very slow.

### ISSUE THREAD

**Issue by yunwuxin** [ianstormtaylor/slate#2414]
https://github.com/ianstormtaylor/slate/blob/b78f6546cd804b10f8c1b3060d45f7c2ecffe567/packages/slate/src/controllers/editor.js#L102-L108

paste a large text will call `insertFragementAtRange`, in this mehtod will loop call `insertNodeByKey`
however every time insert a `node`, you need to recalculate the previous `dirty`, which is very time-consuming

**Comment by yunwuxin** [comment]
https://www.slatejs.org/#/huge-document

You can test through the following steps

1. `Ctrl+A`  select All
2. `Ctrl+C` Copy
3. `Delete` Delete All
4. `Ctrl+V` Paste

Steps 3 and 4 are very slow, especially 4.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
