### ISSUE TITLE
Update documentation (or changelog) to reflect lack of Change

### ISSUE THREAD

**Issue by beaugunderson** [ianstormtaylor/slate#2421]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

There are conflicting statements in the changelog and the documentation, e.g. in the changelog:

> All places that used to receive change now receive editor, which is API equivalent.

And in the slate-react documentation:

![screenshot](https://i.imgur.com/VYnD99D.png)

And in the slate documentation:

![screenshot](https://i.imgur.com/PcZPIoN.png)

#### What's the expected behavior?

The way the changelog is written I expect `onChange` to receive an `Editor`, not a `Change`. Is that correct?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
