### ISSUE TITLE
Perceivable delay at sync

### ISSUE THREAD

**Issue by viztor** [ianstormtaylor/slate#2431]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
when you type really fast, i.e. keep pressing alternate keys, the sync is stuck until you finished typing.

**Comment by zhujinxuan** [comment]
Can you make a gif?  I cannot reproduce it.

**Comment by viztor** [comment]
![2018-11-16 05 54 23](https://user-images.githubusercontent.com/3511050/48584244-27e32880-e964-11e8-9383-6f51592a9632.gif)

**Comment by viztor** [comment]
so at the first few keys they were fine, then it began to appear in batch, as it seems that operations are blocked while syncing.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
