### ISSUE TITLE
Focus breaks when calling setState in onFocus / onBlur

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2434]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

When you call `setState()` from within an `onFocus()` or `onBlur()` handler the editor can no longer receive / release focus. Here is a JSFiddle illustrating the problem: https://jsfiddle.net/fj9dvhom/2611/. Just try to focus or unfocus the editor.

Chrome: Version 70.0.3538.102 (Official Build) (64-bit)
Mac OS: 10.14.1

#### What's the expected behavior?

Focusing should work correctly.

I have a suspicion that the `setState()` call is causing a render event before the editor can finish handling the original focus / blur event. Wrapping the `setState()` in a `setTimeout()` seems to alleviate the issue.

**Comment by isubasti** [comment]
@ericedem it's because `onChange`, `onBlur` and `onFocus` can go to a race condition?. one way to get around this is to do something like

```js
onFocus = (event, editor, next) => {
	this.setState({hasFocus: true, value: editor.value});
	next();
}
```

**Comment by rjbergerud** [comment]
@isubasti that doesn't seem to fix it for me, though I don't understand how the race condition affects the editor taking focus.

**Comment by isubasti** [comment]
@rjbergerud are you talking about this problem or a different one that you posted on https://github.com/ianstormtaylor/slate/issues/2451?

**Comment by rjbergerud** [comment]
Sorry, the one I posted in #2451

**Comment by klis87** [comment]
#2451 is a different issue, this bug occurs even with one editor. For some reason this fixes blurring:  
```js
onBlur = (event, editor, next) => {
    next();
    setTimeout(() => this.setState({ hasFocus: false }), 0);
  }; 
```
which imho this is a proof that it is a race condition issue.

See online demo: https://jsfiddle.net/fj9dvhom/2734/

**Comment by tomspeak** [comment]
@klis87 — I am facing this issue as, due to styling reasons, I need the outer wrapper to know when the editor is in focus so it can apply a `className`.

I am still seeing this on the latest version, do you know what could be causing this? The `setTimeout` work around isn't the end of the world, but is curious!

**Comment by johnw86** [comment]
I was experiencing this exact same issue, took me a good while to come to that conclusion also. I have settled on:

`this.setState({ hasFocus: true }, next);`

**Comment by klis87** [comment]
@johnw86 interesting idea, much cleaner that timeout trick :+1:

**Comment by ericedem** [comment]
That trick means that you will block `onBlur()` event handling for all other plugins until the next react render cycle, which could result in some pretty unexpected behavior. Especially since slate is expecting to call all the event handlers synchronously.

**Comment by johnw86** [comment]
@ericedem Thanks Eric, I'm pretty new to both slate and React, so thanks for the advice. Will go with the setTimeout workaround for now.

**Comment by thatmarvin** [comment]
I'm quite surprised to find that `setState()` on a _parent_'s `onBlur/Focus` handler also prevents the editor from gaining/losing focus. I'd expect `Editor`'s inner workings to be immune from external state changes like this?

I've forked @ericedem's fiddle, and simply moved the `onFocus/Blur` handler to a `<div>` wrapper to demonstrate the problem here: https://jsfiddle.net/thatmarvin/sLkq06yt/

Wrapping `setTimeout` also fixes the problem: https://jsfiddle.net/thatmarvin/fa0encyd/

**Comment by rahul1995** [comment]
> I'm quite surprised to find that `setState()` on a _parent_'s `onBlur/Focus` handler also prevents the editor from gaining/losing focus. I'd expect `Editor`'s inner workings to be immune from external state changes like this?
> 
> I've forked @ericedem's fiddle, and simply moved the `onFocus/Blur` handler to a `<div>` wrapper to demonstrate the problem here: https://jsfiddle.net/thatmarvin/sLkq06yt/
> 
> Wrapping `setTimeout` also fixes the problem: https://jsfiddle.net/thatmarvin/fa0encyd/

Yes, this one needs to be fixed on priority as it's totally a blocker. It took my 2 days to figure out why my editor was not working, as it doesn't even throw any error.

**Comment by steida** [comment]
The better workaround is to track selection.isFocused changes imho.

**Comment by ctrlplusb** [comment]
@steida - do you have any examples of this?

**Comment by ctrlplusb** [comment]
Ok, never mind, figured it out. It needs to be against the `ònChange` callback, which contains `value.selection.isFocused`.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by lcswillems** [comment]
@ianstormtaylor No, it is not solved. I have this issue when I set a state into a focus. The editor loses focus.

**Comment by lcswillems** [comment]
I finally figure out how to avoid editor losing focus. My solution is based on @steida recommandation of tracking `isFocused`. Here is what I did:

1. Add this hook somewhere into your code:

```tsx
const useFocusBlurCallback = (onFocus: () => void, onBlur: () => void) => {
  const focusedRef = useRef(false);

  return (focused: boolean) => {
    if (!focusedRef.current && focused) {
      onFocus();
    } else if (focusedRef.current && !focused) {
      onBlur();
    }
    focusedRef.current = focused;
  };
};
```

2. In your component, call this hook:

```tsx
const setEditorFocused = useFocusBlurCallback(
    () => {
        // onFocus
    },
    () => {
        // onBlur
    }
);
```

3. When editor changes:

```tsx
onChange={value => {
    setEditorFocused(ReactEditor.isFocused(editor));
}}
```

**Comment by vsirakova** [comment]
Thank you, @lcswillems, I just solved my problem using this approach and it works!
