### ISSUE TITLE
Potentially extraneous React peer dependency in Slate core

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#2439]
#### Do you want to request a _feature_ or report a _bug_?
Bug?
#### What's the current behavior?

The slate core library has a peer dependency of React

#### What's the expected behavior?

The model library probably does not need to have any react dependency

Probably? Willing to file a PR just wanted to double check first :)

**Comment by ianstormtaylor** [comment]
Yup, that's definitely an old dep. Thanks @CameronAckermanSEL!
