### ISSUE TITLE
merge commands in normalize to the previous command?

### ISSUE THREAD

**Issue by yunwuxin** [ianstormtaylor/slate#2440]
#### Do you want to request a _feature_ or report a _bug_?

_feature_

#### What's the current behavior?

when run a command, after it will call some normalize, in these normalize will call some commands,

then run redo , not all  commands  redo

#### What's the expected behavior?

redo all commands from the first command

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
