### ISSUE TITLE
Cannot easily click and drag to select text on IE11 or Edge

### ISSUE THREAD

**Issue by dannyiacono** [ianstormtaylor/slate#2442]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
We are unable to click and drag to select text when the text contains links or marks, like in the demo provided here: https://www.slatejs.org/#/rich-text. Sometimes, if we click and drag fast enough the selection will be successful, but otherwise, text is only partially selected or not selected at all.

MacOS Mojave 10.14.1, IE11/Edge, latest SlateJS at the time of filing this issue

http://recordit.co/xOYYQ0sZ8n

#### What's the expected behavior?
We expect to be able to select text via click and drag in order to copy and paste content.

**Comment by omackaj** [comment]
I'm facing the same problem. it all works fine until I try to move between 2 paragraphs for example.
I found a difference between Edge and Chrome here:
https://github.com/ianstormtaylor/slate/blob/8dd919dc3457c62ea2aa72f31b83faf42cbaba72/packages/slate/src/commands/on-selection.js#L590
Edge will call select twice with the same focus property and then stops selecting the text. I don't know if that's the problem but might be a hint.

**Comment by taseenb** [comment]
Selection is broken on MS Edge regardless the element (making the library unusable on most projects atm). I don't know how Slate deals with user selections, but it looks like Slate controls it and probably there's a bug with the update of the selection state on MS Edge.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
