### ISSUE TITLE
What happened to slate-simulator ?

### ISSUE THREAD

**Issue by enzoferey** [ianstormtaylor/slate#2449]
Hello everybody !

I was wondering if any of you know what happened to the `slate-simulator` package. It used to be in this repo (I wrote some docs for it on August or something like that) but now it's just not here it seems.

Should we just use an Editor instance instead or what is the way plugins developers should test their code ?

Thanks 😄

**Comment by CameronAckermanSEL** [comment]
Slate Simulator was deprecated because of the addition of the editor controller in 0.42, it wasn't really necessary. The editor controller can be used to simulate user interaction events easily so it didn't make a lot of sense to keep the simulator around.

**Comment by enzoferey** [comment]
Thank you very much ! I will look at the controller then :)

Have a nice day !
