### ISSUE TITLE
make `isVoid` determined by schema

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#245]
Now that we have the concept of a schema, we no longer need to make `isVoid` a property of each node, and we can instead have it determined by the schema.

**Comment by cobbweb** [comment]
I wonder if this should be defined by the Block itself? Is there a use-case for a single block type that can operate as both void node _or_ having children?

Or if for some reason you did have a node that could be either, you could make a getter function for `block.isVoid`?

```
function ImageBlock({ node }) {
  return <img src={node.data.src} />;
}

MyBlock.isVoid = true;

const schema = {
  nodes: {
    image: ImageBlock
  }
};
```

If people were to start distributing blocks for others to use, this style would make them easier to consume?

**Comment by ianstormtaylor** [comment]
I think the issue with putting it purely in the component land is that transforms need to know about whether it's void or not so they can know to use different deleting/etc. behavior.

I think the simplest for now would actually be to keep it the way it is, but allow for an easy way for the schema to ensure that certain nodes are always void. So that you wouldn't have to care about it anymore.

**Comment by cobbweb** [comment]
Can the transform not pull it off the Component through the schema though?
I guess in my example `MyBlock.isVoid` is a static prop, so my getter idea wouldn't work as cleanly as I originally thought (if someone needed such functionality). 

Assuming it can be access from the Component, that still feels like the right place to me. 
Renderers are written with a specific `isVoid` value in mind, but don't really have a way to enforce this. This leads to edge-cases like if you call `Transform.setBlock('paragraph')` when the current selection is a void block, you end up with a [void paragraph](https://jsfiddle.net/f6L257bs/3/) (which cannot be edited). 

I suppose having `isVoid` in the schema might fix that, but you've still got an implicit dependency in the renderer that the Node's `isVoid` is a particular value that it cannot enforce.

**Comment by ianstormtaylor** [comment]
Yeah definitely tricky. I think it needs to either be in the schema or in the state itself though, and not in the renderer, because you shouldn't need to be rendering something to be able to transform it properly (eg. imagine runnning transforms server-side).

**Comment by cobbweb** [comment]
Ah yep, gotcha. Schema it is!

**Comment by ianstormtaylor** [comment]
Closing since this is a userland schema choice after our decision. There could probably be a bit better docs for this use case (or adding to images example) if someone wants to PR!
