### ISSUE TITLE
Unexpected behaviour depending on whether `Point` has `path` or not.

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2458]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

I'm trying to insert a block at the end of the last node and it inserts it before or after the last block, depending on whether my target range's start point has a path set or not.
This looks like unwanted behaviour.

In this [fiddle](https://jsfiddle.net/mkv74rhu/), we have a void block as a last block.
After 1000 ms, we try to insert a new block at the end.
The place where we could optionally add in a `path` for changed behaviour is documented.

The block however gets inserted before, not after the void block.
The reason is that the `start` `Point` of the `Range` has no path set and therefore is declared `isUnset = true`. If we created a range point with a path however, the new block would be added after the void block.

The offending line is [here](https://github.com/ianstormtaylor/slate/blob/6d8df18f016df75da0d49d6b753cecb333dca078/packages/slate/src/models/point.js#L222)

#### What's the expected behavior?

Assuming that the offending line was added to avoid ill-defined range points, then if we need `path`, a check requiring it could be added to Point.create or Range.create.
If not, the `Range.isSet` property could be relaxed to tolerate either `path` or `key`.
Removing the offending line would also work, I don't know why it was added there.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
