### ISSUE TITLE
Cannot use slate-react-placeholder twice

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2459]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

If `slate-react-placeholder` is instantiated twice for different placeholders, the instances will interfere as they use the same mark, and the same placeholder will be displayed for both `when` queries.

Solution: Either an auto-counter for the mark name, or option for the user to submit a custom mark name.
I'll make a PR for auto-counter as that's the simplest solution.

Example plugins:

    [
      placeholder({ type: 'title', placeholder: titlePlaceholder }),
      placeholder({ type: 'text', placeholder: textPlaceholder })
    ]

and `slate-react-placeholder` like this:

    export default ({ type, placeholder }) => {
      if (type !== 'title' && type !== 'text') {
        throw new Error('type needs to be \'title\' or \'text\'')
      }
      return PlaceholderPlugin({
        placeholder,
        when: whens[type]
      })
    }

#### What's the expected behavior?

Two instances of placeholder should stay independent.

**Comment by cmcnamara87** [comment]
I'm having this same problem, what can I do to help?

**Comment by bebbi** [comment]
@cmcnamara87, I think if you find someone on the slatejs slack to review PR #2460, that would certainly help move this forward.
