### ISSUE TITLE
deleteAtRange should not force selection snapshotting

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#2463]
#### Do you want to request a _feature_ or report a _bug_?

Request a feature.

#### What's the current behavior?

Right now, most "delete" commands will eventually delegate to deleteAtRange, which will always snapshot the selection before taking action. This makes it impossible to group multiple deletes into a single undo step without using the low-level `removeTextByKey`, etc. This behavior should be something that a user / plugin can control.

#### What's the expected behavior?

A user / plugin should be able to have deletes in various ranges of a document group into a single undo step -- imagine, for example, deleting all matching words in a document. You can _do_ it if you use the lower-level methods, but it would be much easier to iterate over a bunch of ranges and call `deleteAtRange` on each.

**Comment by Calyhre** [comment]
A **very ugly** workaround is to override the `snapshotSelection` method around the operations you'd like to group:

```js
snapshotSelection = editor.snapshotSelection
editor.snapshotSelection = () => editor
// [...] Perform all .deleteAtRange() operations
editor.snapshotSelection = snapshotSelection
```

This could be implemented in a plugin command, and used like this:
```js
editor.withoutSnapshots(() => {
  // [...] Perform all .deleteAtRange() operations 
})
```

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
