### ISSUE TITLE
Cannot enter Chinese on IOS

### ISSUE THREAD

**Issue by zjfjiayou** [ianstormtaylor/slate#2468]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

Thank you for looking at my problems in your spare time. My problem is that I cannot input text using Chinese input method in ios 12。
![ezgif-4-519ee7f4c273](https://user-images.githubusercontent.com/7593789/49372247-fecce100-f734-11e8-9b4a-c039671238a4.gif)

#### What's the expected behavior?
Normal input Chinese

**Comment by hecor** [comment]
Have the same problem, please help.

**Comment by ianstormtaylor** [comment]
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!
