### ISSUE TITLE
[Slate-React]: Allow customisation of placeholder style

### ISSUE THREAD

**Issue by sgreav** [ianstormtaylor/slate#2470]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
Currently, the placeholder text for a slate editor automatically has [certain styles applied to it](https://github.com/ianstormtaylor/slate/blob/a09c3c2fdfe87605988a13e968643f81b4936978/packages/slate-react-placeholder/src/index.js#L62) inline. This can be quite tricky to override, particularly opacity, where even passing your own custom placeholder child component will inherit this attribute.

#### What's the expected behavior?
Rather than having these styles inline, it would be nice if they were associated with a class, so that they could be easily targeted and overridden by the end user, e.g. by adding
`.slatePlaceholder { opacity: 1 }` to their own stylesheet

**Comment by brendancarney** [comment]
Maybe we could support a `style` or `className` option here: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react-placeholder/src/index.js#L17-L24

**Comment by brendancarney** [comment]
If @ianstormtaylor approves of this, it would be a good PR for someone new to contribute.

**Comment by sgreav** [comment]
Happy to work on the PR if approved : )

**Comment by brendancarney** [comment]
Hi @sgreav, I'm confident that we'd be ok to go ahead and add a `style` option that we merge with the default styles if you want to create a PR for that and I can review/merge it. Thanks!
