### ISSUE TITLE
HTML Serializer is Incompatible with React-Native

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2472]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

~~Trying to import the `html-serializer` into a `react-native` project causes the error:~~

~~`document is not defined` - I assume this occurs because the `html-serializer` relies on the built in `DOMParser`~~

The above is inaccurate and seems to be caused by my `schema` somehow, although I believe the issue itself is still relevant as React-Native is missing DOMParser as far as I can tell.

#### What's the expected behavior?

It's probably not reasonable to expect this to work out of the box, but it would be great to:

1. Find a way to throw a friendlier error message thrown before React-Native can throw its own - Right now we have that, but React-Native beats it to the punch.
2. Determine an alternative to `DOMParser` and `jsdom` that can be passed to the `html-serializer`

#### Potentially interesting avenues to explore:
- https://www.npmjs.com/package/react-native-dom-parser
- [Find a way to use `jsdom` without reliance on NodeJS built-ins](https://github.com/jsdom/jsdom/issues/1284#issuecomment-371074497)

@ianstormtaylor do you have any ideas that might be less cumbersome than the above?

**Comment by brendancarney** [comment]
So are you saying an error gets thrown before this one? https://github.com/ianstormtaylor/slate/blob/master/packages/slate-html-serializer/src/index.js#L75

**Comment by Slapbox** [comment]
@brendancarney it's been a while now and I was wrong about the initial cause of my issue. I believe that that error will be thrown as would be expected. I haven't been able to find any substitute parser to drop in in place of Slate though. I think `parse5` should work, but I didn't get it working and went another route.

It would still be a big help to have this working with any other parser in a React-Native environment. I'm sure it's not terribly difficult to find one, but I've already burned a lot of time on this between toying with `jsdom` and `parse5`.

**Comment by brendancarney** [comment]
I had an issue with `parse5` where `node.nodeValue` is null in parse5, but `node.value` isn't:

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-html-serializer/src/index.js#L47

I haven't looked into what is right.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
