### ISSUE TITLE
Blur and refocus breaks cursor position after new line

### ISSUE THREAD

**Issue by emaciel10** [ianstormtaylor/slate#2474]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

If the current block is an ordered list or a numbered list then blurring the editor (focusing on another window) and returning to the editor causes the cursor position to be incorrect after pressing 'Enter'

This issue can be reproduced on the rich text example at https://www.slatejs.org/#/rich-text

I am on macOS Mojave v10.14, Chrome Version 70.0.3538.110

Here is a gif of the issue:

![slate-blur-bug](https://user-images.githubusercontent.com/11020939/49404320-21530000-f71d-11e8-88d9-ba58c8daf1c0.gif)

#### What's the expected behavior?

The expected behavior is that after pressing enter, the cursor is moved to the next line along with the new block element that has been inserted.

**Comment by alexfi** [comment]
Any progress on this one?

**Comment by gdehmlow** [comment]
I've encountered the same issue with programmatically inserting text after blurring / focusing. You can also reproduce it on the home page by just blurring then focusing then hitting enter on any kind of text.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
