### ISSUE TITLE
race condition async `onChange` (0.44.6)

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2477]
Race condition - bug or documentation

Using slate `0.44.6`, I store the editor controller in the parent react component of the editor.

For an attachment component, I add a placeholder block, and whenever the file is done uploading to the server I update the slate state accordingly (the relevant void block is assigned a final file url). I then synchronously issue a `publishSuccessMessage` to the user.

But since the `publishSuccessMessage` changes react's context, the editor immediately re-renders, thereby overwriting the updated editor controller with the previous unfinished one before slate gets a chance to trigger `onChange`.

I've worked around that issue with `setTimout(publishSuccessMessage, 0)`, but that behaviour might be worth mentioning or documenting somewhere.

Some potentially relevant draftjs discussions:
https://draftjs.org/docs/advanced-topics-editorstate-race-conditions.html
https://github.com/facebook/draft-js/issues/1577

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
