### ISSUE TITLE
"Flatten" an array of normalizeNode hooks provided by a plugin

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#2479]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Currently if a plugin has to export multiple normalizeNode rules for validation features it provides, it can only provide one such handler. This means that developers have to
1. Export their normalizeNode plugins as separate plugin exports from their main plugin
2. Jump through weird hoops to try to get the one normalizeNode function to run multiple normalization routines, thereby causing performance problems by bypassing slate's normalization memoization.

#### What's the expected behavior?

The expected behavior is that if a plugin really needs to, it should be able to easily hook up multiple normalizeNode functions.

A naive idea to solve this problem would be to allow the normalizeNode hooks to detect that it's received an array and flatten it into the existing normalizeNode stack via destructuring. 

But I suspect that there's some other better way to do this, though

**Comment by ianstormtaylor** [comment]
@CameronAckermanSEL as of `0.42` or `0.43` (can't remember) individually plugins and arrays of plugins are used interchangeably. So you should be able to return an array of plugin objects instead of just a single one.

**Comment by CameronAckermanSEL** [comment]
Thanks for the quick response! That's good to hear. :)

I'll double check the docs to see if we need an update there, but this can likely be closed.

**Comment by CameronAckermanSEL** [comment]
(For my reference later https://docs.slatejs.org/slate-core/plugins#normalizenode)
