### ISSUE TITLE
Examples stop working in MS Edge when changing focus

### ISSUE THREAD

**Issue by n1ghtmare** [ianstormtaylor/slate#2487]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?
Changing focus breaks the examples in MS Edge.

![slatejs-bug](https://user-images.githubusercontent.com/3255810/49604135-92591880-f9a6-11e8-892d-ff3035b6f1be.gif)

Version: Microsoft Edge **42.17134.1.0**

#### What's the expected behavior?
Should be able to refocus.

Let me know if I can provide any additional info.

**Comment by steida** [comment]
Thank god Microsoft Edge will die soon.

**Comment by pjshy** [comment]
I have the same problem **Version: Microsoft Edge 42.17134.1.0**

**Comment by alizeaiter** [comment]
Still having the same problem, editor focus 30% of the time on Edge

**Comment by alizeaiter** [comment]
A temporary fix would be focusing the editor manually on click events.
```
setTimeout(() => {
	editor.focus();
}, 0);
```

**Comment by alizeaiter** [comment]
Scratch that, just found out that even selecting doesn't work on edge.

**Comment by pjshy** [comment]
find a issue in react-dom about this, but i am not sure https://github.com/facebook/react/issues/13212

**Comment by davegw** [comment]
Believe this was fixed in #2535. However, while focus can be given back to the editor now, the initial position of the cursor on refocus goes back to the previous position before the editor was blurred.

**Comment by brendancarney** [comment]
It does look like this is fixed in latest. @davegw if there's not an issue for what you mentioned, we should create that.
