### ISSUE TITLE
Cursor exception and Deletion key failure

### ISSUE THREAD

**Issue by bs32g1038** [ianstormtaylor/slate#2489]
## the questions

- when I input, the cursor will  jump the end.

- the deletion key is failure

- when I input too fast, the letter can replace the current letter.

## environmental information

- window10 

- Google Chrome
Version 71.0.3578.80 (Official Build) (64-bit)
demo: [https://www.slatejs.org/#/rich-text](https://www.slatejs.org/#/rich-text)

## screenshot

![bug](https://user-images.githubusercontent.com/16550983/49687341-79d82380-fab6-11e8-8c6c-4df7f0ca7dae.gif)

**Comment by alizeaiter** [comment]
I can`t reproduce the issue. Is there a specific pattern for it to happen?

**Comment by bs32g1038** [comment]
@alizeaiter  This error occurs when I use the Chinese input。

**Comment by ianstormtaylor** [comment]
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!
