### ISSUE TITLE
Editor not focusing on Microsoft edge

### ISSUE THREAD

**Issue by alizeaiter** [ianstormtaylor/slate#2490]
#### Do you want to request a _feature_ or report a _bug_?
A bug

#### What's the current behavior?
The editor doesn`t focus at all on microsoft Edge making it unusable.

https://jsfiddle.net/fj9dvhom/1/
The bug is on Windows 10, Microsoft Edge browser, slate@0.44.8
#### What's the expected behavior?
To focus like any other browser

**Comment by digitalbase** [comment]
Duplicate of https://github.com/ianstormtaylor/slate/issues/2487

**Comment by alizeaiter** [comment]
Closing this issue as the problem is solved by using the `babel-polyfill` plugin.

**Comment by n1ghtmare** [comment]
@alizeaiter Can you give us some more details on this? I tried using `babel-polyfill` but had no luck. Can you perhaps give an example? I'm probably doing something wrong.
