### ISSUE TITLE
Focus causing double text insertion and shifting selection to the beginning of the editor

### ISSUE THREAD

**Issue by alizeaiter** [ianstormtaylor/slate#2501]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
The `focus()` method causes text to be inserted twice, one at the selection and one at the beginning of the editor. Asyncing the focus with a timeout seems to prevent the double insertion but still shifts the focus to the start of the editor.

https://jsfiddle.net/fj9dvhom/2706/
http://recordit.co/8wX9n9df5n
#### What's the expected behavior?
Focus should just focus and not shift to the start of the editor

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
