### ISSUE TITLE
Triple click incompatible with nested blocks

### ISSUE THREAD

**Issue by caifara** [ianstormtaylor/slate#2503]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

Upon using triple-click + backspace to delete the first of two adjacent custom blocks A and B (A itself containing a paragraph), the second block (block B) becomes nested in block A.

These tickets/PR's are related: https://github.com/ianstormtaylor/slate/pull/1605, https://github.com/ianstormtaylor/slate/pull/950, https://github.com/ianstormtaylor/slate/pull/863#issuecomment-307659171

The gif start with a triple-click + delete having an expected result (everything else stays the same) and continues with two unexpected ones (the adjacent block becomes nested in the first block).

![](http://g.recordit.co/8ApNZpGTsJ.gif)

https://jsfiddle.net/caifara/62e3bxgL/5/

Mac OS 10.14, Chrome 71.0.3578.98, Slate 0.44.9, Slate-react 0.21.15

#### What's the expected behavior?

The selected line gets deleted, everything else stays the same.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
