### ISSUE TITLE
The difference between change and this.editor

### ISSUE THREAD

**Issue by 136170746** [ianstormtaylor/slate#2509]
Sorry, the following is a translation software translation, I hope you can understand:
I want to know how the change variable in onChange(change) differs from the editor instance in Ediotr ref.
If I add the addBoldMark method under the commands in the plugin, should I use this.editor.addBoldMark or can I use change.addBoldMark or both?

I did not find the difference between the two descriptions in docs.slatejs.org, I am confused about this, I hope to answer it, thank you!

**Comment by bebbi** [comment]
You should read the `packages/slate/Changelog.md` file

```

###### BREAKING

**The `Change` object has been removed.** The `Change` object as we know it previously has been removed, and all of its behaviors have been folded into the `Editor` controller. This includes the top-level commands and queries methods, as well as methods like `applyOperation` and `normalize`. _All places that used to receive `change` now receive `editor`, which is API equivalent._

```
