### ISSUE TITLE
Uncaught TypeError: state.transform is not a function

### ISSUE THREAD

**Issue by kulakowka** [ianstormtaylor/slate#251]
I'm trying to go through the steps of documentation: [Adding Event Handlers](https://github.com/ianstormtaylor/slate/blob/master/docs/walkthroughs/adding-event-handlers.md)

I did everything according to the instructions. But I got the error:

```
Uncaught TypeError: state.transform is not a function
```

I was able to reproduce the error: https://jsfiddle.net/kulakowka/Lrxptwtv/

Maybe I made a mistake somewhere? or indeed an error there?

Maybe documentation is outdated?

**Comment by kulakowka** [comment]
I got another error when trying to execute the next step: [Defining Custom Block Nodes](https://github.com/ianstormtaylor/slate/blob/master/docs/walkthroughs/defining-custom-block-nodes.md)

```
Uncaught TypeError: Cannot read property 'some' of undefined
```

I think this is for the same reason.

**Comment by kulakowka** [comment]
Problem solved. But I think we should update the documentation.

> **aunsuwijak:** According to plugin documentation onKeyDown pass 3 parameters and `state` is the last one like this `onKeyDown(event, data, state)`

**Comment by Slapbox** [comment]
What was the resolution to this?

**Comment by Slapbox** [comment]
In my case I somehow changed my state tag to `state={this.state}` instead of `state={this.state.state}`
