### ISSUE TITLE
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by 136170746** [ianstormtaylor/slate#2518]
```
 onDragStart = event => {
        const element = ReactDom.findDOMNode(this)
        const { node } = this.props
        setEventTransfer(event,'node',node)
        event.dataTransfer.setDragImage(element.parentNode,10,10)
    }
```

**Comment by 136170746** [comment]
`onDrop = event => {
        
        const transfer = getEventTransfer(event) // This is error
        console.log(transfer)
        if(transfer && transfer.node){
            event.preventDefault()
            event.stopPropagation()
            const { document } = editor.value
            const index = document.nodes.findIndex(item => item.key === node.key)
            editor.moveNodeByKey(transfer.node.key,document.key,index + 1)
        }
    }`

**Comment by brendancarney** [comment]
Hi @136170746, I'm going to close this issue as we don't have enough info. Please provide a CodeSandbox or JSFiddle that we can look at, and comment here or create a new issue. Thanks!
