### ISSUE TITLE
throw error when pressing the Enter key or the Backspace key

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2520]
I want to develop based on the official demo, the link is [https://www.slatejs.org/#/code-highlighting](https://www.slatejs.org/#/code-highlighting) 

However, when the mouse cursor was at the end of the first line, I pressed the `Enter` key, it thrown error.
Anyone can reproduce the result in the demo.

Similarly, in my local demo, when I deleted the whole second line of the `code` by pressing the `Backspace` key, it also reported an error.

The `value.json` file I am using is as follows:
```
{
    "document": {
        "nodes": [
            {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                    {
                        "object": "text",
                        "leaves": [
                            {
                                "text": "There are certain behaviors that require rendering dynamic marks on string of text, like rendering code highlighting. For example:"
                            }
                        ]
                    }
                ]
            },
            {
                "object": "block",
                "type": "code",
                "data": {
                    "language": "js"
                },
                "nodes": [
                    {
                        "object": "block",
                        "type": "code_line",
                        "nodes": [
                            {
                                "object": "text",
                                "leaves": [
                                    {
                                        "text": "function mainx(){ "
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "object": "block",
                        "type": "code_line",
                        "nodes": [
                            {
                                "object": "text",
                                "leaves": [
                                    {
                                        "text": "     "
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "object": "block",
                        "type": "code_line",
                        "nodes": [
                            {
                                "object": "text",
                                "leaves": [
                                    {
                                        "text": "}"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
}
```

The error is as follows:
![local error](https://user-images.githubusercontent.com/3793502/50640295-6332c880-0f9f-11e9-8bca-212e541af10a.png)

**Comment by bebbi** [comment]
Looks like the issue is caused by this chain:

`examples/code-highlighting/index.js:220`: Decorations `{ anchor, focus, mark }` are assigned with a `key` but no `path` property.

`slate/src/models/decoration.js:118`: The `{ anchor, focus, mark }` all do not have a path object

`slate/src/models/point.js:97`: The point is created with a `null` path.

`slate-react/src/components/text.js:122`: The `start.path` is null which is a bad input for `PathUtils.compare`.


This looks like a similar type of problem like issue #2458 which also results in unexpected behaviour when no `path` arg is submitted to `Point` or `Range` constructors.

**Comment by CodePlayer** [comment]
This problem is rather bad and affects my use of it in a production environment.
@bebbi  @ianstormtaylor  Could you give me a convenient solution?
Many thanks!

**Comment by wuxiandiejia** [comment]
Change
 `while (available < remaining && texts.length > 0)` to 
`while ((available < remaining || available <= 0) && texts.length > 0)`
I think it will work.
