### ISSUE TITLE
@types/slate-react missing "id" property in BasicEditorProps

### ISSUE THREAD

**Issue by wizzard0** [ianstormtaylor/slate#2523]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
using slate & slate-react from typescript and specifying id results in type error;
editing typings package manually fixes the problem

OS: all, browser: all, typescript: 3.2, slate-react: 0.21

#### What's the expected behavior?

i'd happily create the pull request myself, but can't find where the typings are in the slate repositories :(

just add the line `id?: string;` to BasicEditorProps interface in @types/slate-react. Thanks.

**Comment by CameronAckermanSEL** [comment]
I don't believe we have any types in this repository due to the volatility of the API at this time. I certainly wouldnt imagine a donation would be unwelcome though :)

**Comment by ianstormtaylor** [comment]
The types are managed outside of this repository, so please open the issues/PRs to the types themselves instead of here.
