### ISSUE TITLE
bug: `normalizeNode` is called on non-existent path and throws an error.

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2528]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

When merging nodes, the `getDirtyPaths` function collects an illegal path, leading `normalizeNodeByPath` function to throw on its `assertNode` call.

##### Repro

1. Open https://jsfiddle.net/y5q9120p/2/
2. Open the dev console
3. Click into the first line, drag down to anywhere in the middle of the last line to create a selection.
4. Press Delete
5. See "Uncaught Error: `Node.assertNode` could not find node with path or key: List [ 0, 0, 0, 11 ]"

The path appears to refer to the right side adjacent text node that gets merged with its neighbor [here](https://github.com/ianstormtaylor/slate/blob/09db2c93b6f69b2c1c733bca8fd1bcf71d7688a3/packages/slate/src/plugins/core.js#L165)

#### What's the expected behavior?

This should just work without an error.

**Comment by bebbi** [comment]
Possibly related, while above works for a simple node: https://jsfiddle.net/x96ja1fv/ it fails with an `assertNode` error on undo.
Should that be a separate issue?

**Comment by bebbi** [comment]
@CameronAckermanSEL I've tried it and no, the issue is independent of https://github.com/ianstormtaylor/slate/pull/2505.

While in that PR dirty handling appears key based instead of path based, the dirty calculation code path seems to be the same.

The reason that PR appears to work is because its early exit on missing nodes in `normalizeNodeByPath` instead of the original assertNode(path).

While I am not familiar with the details of dirty path calculation, I did notice that the offending path is added to the `editor.tmp.dirty` array before the call to [merging adjacent text nodes](https://github.com/ianstormtaylor/slate/blob/09db2c93b6f69b2c1c733bca8fd1bcf71d7688a3/packages/slate/src/plugins/core.js#L165).

During that merge, the (offending) node gets deleted but the path never gets removed from the dirty paths array. It looks like that is the actual issue to me.

Example:

before merging the adjacent nodes:

tree structure:

```
14 (document)
| 15 container
| | 16 paragraph
| | | 17 text "This is abo" 
| | | 28 text "e content" 
| | 21 container
...
```

and

    editor.tmp.dirty = ["14", "15", "14", "15", "21", "22", "14", "15", "16", "17", "14", "15", "21", "22", "26", "27", "28", "14", "15", "27", "28", "14", "15"]

Then 28 gets removed by the merge.

Then more paths get added by that operation but none gets removed and the 28 path is still there but doesn't exist anymore:

    editor.tmp.dirty = ["14", "15", "14", "15", "21", "22", "14", "15", "16", "17", "14", "15", "21", "22", "26", "27", "28", "14", "15", "27", "28", "14", "15", "14", "15", "16", "17"]

**Comment by Calyhre** [comment]
Just encountered this one. I added a few tests on my fork that triggers it -> https://github.com/Calyhre/slate/commit/6bac5ceaf7cb5378e7b85c1e3c0da88b8623e40a
