### ISSUE TITLE
the schema's validation of slate conflicted with multi-step operation in editor.

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2531]
#### Do you want to request a _feature_ or report a _bug_?

**bug**

#### What's the current behavior?

Consider the following scenario:
**The schema's definition of editor as follows**:
```json
{
"blocks": {    
    "bulleted-list": {
      "nodes": [ { "match": { "type": "list-item" }, "min": 1 } ]
    },
    "numbered-list": {
       "nodes": [ { "match": { "type": "list-item" }, "min": 1 } ]
    },
    "list-item": {
      "parent": [ { "type": "numbered-list" }, { "type": "bulleted-list" } ]
    },
}
```
There are three regular paragraphs in the editor.
I want to convert all the paragraphs into a numbered-list block which also known as `ol-li`.

Refer to the official example [https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js](https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js).

The core code is as follows:
```js
editor.setBlocks('list-item').wrapBlock("numbered-list");
```

Two editor methods will be called.
However, when the first step is executed, it will trigger schema's validation and schema's `normalize` method.
Then, it will trigger an unexpected error or behavior.

#### What's the expected behavior?

I think there should be a mechanism to ensure that the schema's validation is not triggered midway in a continuous multi-step operation in the editor.
For example, consider adding a `editor.flush()` method, or a `editor.batch( multi-operations )` method.

**Comment by CameronAckermanSEL** [comment]
`editor.withoutNormalizing(e => e.setBlocks('list-item').wrapBlock('numbered-list'))` suppresses the normalization until the end of the function enclosure, at which point it normalizes dirty nodes.

**Comment by CodePlayer** [comment]
Thank you very much for telling me this good news! @CameronAckermanSEL
