### ISSUE TITLE
Spellcheck Behaving Incorrectly on Safari and Firefox

### ISSUE THREAD

**Issue by milkman4** [ianstormtaylor/slate#2540]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

[JSFiddle](https://jsfiddle.net/hysn87kt/)

Recorded on SlateJS.org
Firefox 62.0 : 
![Firefox](http://g.recordit.co/QOOnCgKVPl.gif)

Safari 12.0.2 : 
![Safari](http://g.recordit.co/gLhAwNtG1b.gif)

Recorded in JSFiddle:

Firefox 62.0:
![Firefox](http://g.recordit.co/bHgSbjTWTy.gif)

Safari 12.0.2:
![Safari](http://g.recordit.co/N9tuOQGjQb.gif)

In all examples, focus changes are required to enable spellcheck. In both, I'm doing a combination of clicking inside and clicking outside of the Slate editor component and clicking on the words themselves. The issue behaves a bit differently in each browser, but it's a very similar issue that requires changes in focus to get the red underline to appear.

#### What's the expected behavior?

Something more like how Chrome works, ignoring the flashing decorations of course.

Example:

Chrome 71.0.3

![Chrome](http://g.recordit.co/VtCJt4Xl5a.gif)

Any help is appreciated! :) Thank you so much!

**Comment by ryanhyslop** [comment]
We're experiencing the same issue and having to look into this, don't suppose anyone would have any pointers or suggestions?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by lmariscal** [comment]
I am still experiencing this issue in Firefox 72.0.2.
