### ISSUE TITLE
Slate rendering read only

### ISSUE THREAD

**Issue by stevez86** [ianstormtaylor/slate#2541]
I’m considering building a CMS editor that uses slate to create web pages with custom react components. 

I was wondering if there was a lighterweight or an alternative to just rendering the slate value on the client using the editor?

Ideally I could just take my renderNode function and a lightweight rendered would spit out the react. Thoughts?

**Comment by dmitrizzle** [comment]
Yes, check out https://github.com/roast-cms/french-press-editor/blob/develop/src/components/vignettes/Reader.js - feel free to implement code or use the entire lib as an install, too. Cheers.

**Comment by thesunny** [comment]
Nice. Looks like this issue is closed. I'm going to create a new issue to maybe add this to the documentation and perhaps even as a separate lib. Looks useful!
