### ISSUE TITLE
Proposal to add onSplit and onSpace events to plugins

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2543]
This is a proposal is for a feature that enables mobile devices to provide special handling when pressing Enter or Space in the editor which is currently not possible.

Normally, this is done by handling the `onKeyDown` event; however, due to the way Android implements events, this is not possible because:

1. It's difficult in some cases and impossible in others to determine if Enter or Space was pressed by looking at the event. Android events don't provide this data.
2. Even in some of the cases where it is possible, it is sometimes impossible or too late to cancel the native event in order to handle it ourselves.

The `onKeyDown` event in Slate plugins is used to handle keyboard shortcuts and smart replacements (e.g. convert a URL into a link). This is a solution to the smart replacements issue. Instead of the user registering `onKeyDown` in a plugin, the user registers `onEnter` and `onSpace` events.

When `onEnter` or `onSpace` is called, we know the user is requesting an enter or a space. We then can handle it and prevent it from continuing with its original intent or we can let it pass through and do it's usual thing.

To be clear, this is not an attempt to improve the semantics of how you might register handlers for hitting Enter and Space. The keydown event works fine enough from a semantic perspective. This is a proposal for making handling Enter and Space possible on certain devices. I provide this proposal here for discussion and it is related to my current work on Android support which you can view here: https://github.com/ianstormtaylor/slate/issues/2062

**Comment by ianstormtaylor** [comment]
Hey @thesunny, I think this relates to the discussion in https://github.com/ianstormtaylor/slate/issues/2342. We probably wouldn't add specific handlers like `onSplit` without considering the full case. I'm going to close this in favor of that discussion.
