### ISSUE TITLE
Paste on line with void an no text deletes void node

### ISSUE THREAD

**Issue by ldavidpace** [ianstormtaylor/slate#2544]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?

When Pasting on a line that only contains a void with no additional text it deletes the void. 

[JSFIDDLE](https://jsfiddle.net/paceld/74c8dvep/)
![inlinedeleteonpaste](https://user-images.githubusercontent.com/25068382/51335931-8437f680-1a40-11e9-9e25-edbe0a07c855.gif)
Mac Os High Sierra,  Chrome: 71.0.3578.98  slate version: ^0.44.8

#### What's the expected behavior?

It should not paste the text next to the void.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
