### ISSUE TITLE
Proposal for Combo object for event handling

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2547]
#### Do you want to request a _feature_ or report a _bug_?

Proposal for feature

#### What's the current behavior?

There are composite groups of events that fire in Android. By looking at one event, we cannot tell what the intended action of the user is. For example, an `Enter` after a `Backspace` in the middle of a word fires multiple `input`, `keydown`, `beforeinput`, `compositionStart` and `select` events which include events identified as `delete` and `enter`.

We cannot act on each event individually as it breaks Android usually resulting in Android's DOM going out of sync with React's virtual DOM. This ends in a crash.

To continue with this example, we know the fingerprint of an `Enter` is a set of events all fired one after the other which includes the `Enter` event. The `Delete` event somewhere in there is just a side-effect of how Android is manipulating the DOM as part of its way to handle `Enter`.

#### What's the expected behavior?

What we want is a special object (the Combo) that we instantiate. It has a bunch of signatures in it. As the events fire, we want the combo to determine the right signature. Was this a `delete`? Was this an `enter`? At the end of period of time, we then want the correct event to fire or no event to fire if the signature indicates not to do anything at this time. This could happen, for example, if a user hits a key in the middle of a composition. We don't want that to fire unless a `compositionEnd` is at the right position in the combo.

We also want to have a way to refresh the timeout in the Combo. Some combos have enough events in that that the `requestAnimationFrame` has a chance to fire before the combination of events has actually finished. To combat this, we restart the timer whenever we send an event to the Combo.

The Combo also needs to include snapshots of previous DOM and selection states. This is because some Combos need to revert the DOM back to a safe state so that it doesn't cause React to crash. When Android manipulates the DOM without letting React know, we usually end up with a fatal error. The moment in time that the snapshot needs to revert to may be different depending on the final event. For this reason, the Combo should be able to take a snapshot when events are being sent to the Combo. The Combo can then select which Snapshot to revert to.

Related to https://github.com/ianstormtaylor/slate/issues/2062

**Comment by thesunny** [comment]
**Matching and Rejecting**

When a combo is finished, we need to match against several signatures. These signatures need to these features:

* The ability to match a number of events in a specific order. For example, an `onBeforeInput:enter` followed by an `input:delete`.
* The ability to reject if we encounter an event that fails the signature. For example, perhaps the above is invalid if called after a `compositionEnd`.

The syntax for matching could be like this:

```js
[
  {type: 'onBeforeInput:enter'},
  {type: 'onBeforeInput:delete'}
]
```

Two possible syntaxes for rejection.

The first is to make it part of the definition:

```js
[
  {type: 'onBeforeInput:enter', notType: 'onCompositionEnd'},
  {type: 'onBeforeInput:delete'}
]
```

The second is to include it linearly:

```js
[
  {notType: 'onCompositionEnd'},
  {type: 'onBeforeInput:enter'},
  {type: 'onBeforeInput:delete'}
]
```

They both indicated that a `compositionEnd` event cannot precede the `onBeforeInput:enter` event.

The benefit of the former is that we only need to look at one matcher at a time. The benefit of the second is a more readable format.

One way the former method could be implemented is that these matchers can simply be functions. The functions can return `true` (match), `false` (reject) or `null` skip this event for now.

**Comment by thesunny** [comment]
Made some improvements to Combo specification. Thanks @ianstormtaylor for the link to https://twitter.com/threepointone/status/1099018973595779072. Gave me some good ideas.

A combo object is defined like this:

```js
const combo = new Combo()
```

combos are defined like this:

```js
combo.register(
  "enter",
  [
    e => e.type === "compositionEnd",
    e => e.type === "input" && e.inputType === "deleteContentBackwards",
    e => e.type === "keyDown" && e.key === "Enter",
  ],
  (editor) => {
    compositionEndSnapshot.apply()
    editor.splitBlock()
  }
)
```

The preceding defines a combo that captures a possible `enter` event that we might want to capture.

The first argument `enter` gives the combo a name. Not strictly necessary but useful for debugging so we can tell which combo was triggered.

The second argument is an array of event matcher functions. The combo above will only match if we get a `compositionEnd` event, followed by an `input` event where the `inputType` is `deleteContentBackwards` followed by a `keyDown` event where the `key` is `Enter`. All of these events must fire within a single tick. It's not strictly speaking a `requestAnimationFrame` or a `setTimeout` tick but you can think of it like that for purpose of understanding the example.

If nothing matches, it goes on to the next combo that is registered so the order of registration matters.

If the combo matches, the third argument which is a function is fired with the `editor` as the first argument.

The Combo object reacts to events that are triggered on it. An example of writing a trigger might be something like this in a plugin:

```js
function onKeyDown(e) {
  combo.trigger({type: 'onKeyDown', key: e.key})
}
```

Note that we don't simply do:
```js
// DON'T DO THIS
function onKeyDown(e) {
  combo.trigger(e)
}
```

This is because `e` gets re-used for performance reasons. We need to explicitly pull out the things we want to look at. One nice thing is it makes `Combo` pretty generic. We don't even need to trigger off of browser events. It can be editor events for example. All we have to do is trigger with an Object.

**Comment by thesunny** [comment]
A basic design for the Combo class. Note: I haven't run any of this code so there may be errors.

```js
class Combo {
  /**
   * An array of Combos
   */
  combos = []

  /**
   * The constructor sets the Combo state to the `reset` state.
   */
  constructor() {
    this.reset()
  }

  /**
   * Combos track a set of events from the time the first event is fired until
   * the events stop firing in rapid succession (i.e. when there is enough
   * time for a `setTimeout` callback to be called). Then the state is reset.
   */
  reset() {
    this.events = [] // events called in this set of events
    this.match = null // has a combo matched yet
    this.deferredCallback = null // If a combo has matched, its deferred callback
    this.timeoutId = null // The currently waiting `setTimeout` id
  }

  /**
   * Register a Combo for matching against.
   *
   * @param {String} name
   * @param {[Function]} matchers
   * @param {Function} callback
   */
  register(name, matchers, callback) {
    is.string(name)
    is.array(matchers, is.func)
    is.func(callback)
    events.push({ name, matchers, callback })
  }

  /**
   * Whenever an event is triggered, we want to reset the timer on the
   * `setTimeout`. This is because a `setTimeout` can trigger in the middle
   * of a sequence of events if that sequence is long enough. By resetting
   * the timer, we reduce (hopefully eliminate) the chance of this happening.
   */
  pushTimeout() {
    if (this.timeoutId) clearTimeout(this.timeoutId)
    this.timeoutId = setTimeout(this.done)
  }

  /**
   * Called when the set of events has completed. If there is a
   * `deferredCallback` we call it now. We then also reset the state.
   */
  done = () => {
    if (this.deferredCallback) this.deferredCallback()
    this.reset()
  }

  /**
   * Whenever we receive an event, we push it onto an array of events and
   * reset the timeout.
   *
   * If there hasn't been a match to a Combo, we try and match it. If there is
   * a match, we call its callback and set the `deferredCallback` if there is
   * one.
   *
   * @param {Object} event
   */
  trigger(event) {
    this.events.push(event)
    this.pushTimeout()
    // there already is a match so we don't need to look for more.
    if (this.match) return
    const match = matches(this.combos, this.events)
    if (match) {
      this.match = match
      this.deferredCallback = this.match.callback() || null
    }
  }
}

/**
 * Returns the first combo that matches the array of Events.
 * Note: Not super-performant to call this for every event added but done this
 * way for now.
 *
 * @param {[Combo]} combos
 * @param {[Event]} events
 */
function matches(combos, events) {
  const match = combos.find(combo => {
    let i = 0
    return combo.matchers.every(matcher => {
      for (; /* <- no reset on purpose */ i < events.length; i++) {
        const event = events[i]
        if (matcher(event)) {
          i++
          return true
        }
      }
      return false
    })
  })
  return match ? match : null
}
```

**Comment by adjourn** [comment]
Rethinking events might also be a great opportunity to get rid of synthetic events.. I think that this is pretty much the only thing that prevents using Slate with Preact.

**Comment by adjourn** [comment]
Rethinking events might also be a great opportunity to get rid of synthetic events (mainly `onBeforeInput`).. I think this is pretty much the only thing that prevents using Slate with Preact.

**Comment by ianstormtaylor** [comment]
I'd love to get rid of synthetic events, but it seems like something we need the React team to finally do themselves first. Otherwise we'll have bad compatibility with other React components sadly.

**Comment by adjourn** [comment]
@ianstormtaylor I can see your point.

By the way, I tried to make `slate-react` compatible with Preact but current dependency on React's `onBeforeInput` synthetic event (which uses `textInput` under the hood) makes it nearly impossible, at least for me, Slate is still largely a black box for me.

Every other event I came across seems to work fine though.

**Comment by thesunny** [comment]
FYI, I've moved this along forward and have switched to an `ActionManager` object which handles the same use cases in less code, with more flexibility and better ease of use. I also reduced the requirement for needing multiple snapshots.

The `ActionManager`'s main feature is that it can detect and react to an `action`.

I define an `action` as when the user does one thing. An action is not an event. One action often fires a large number of `events`. For example, pressing a key down might fire `beforeinput`, `textinput`, `keydown`, etc. That's one action.

In `ActionManager` you define `handler`s. Each handler can define an `onTrigger` or `onFinish` or both.

An `onTrigger` is fired for each event and has a signature of `onTrigger(event, options, events)`. If the function returns true, the action is handled and no further `onTrigger` or `onFinish` functions are called.

An `onFinish` is fired at the end of each action if no earlier `onTrigger` functions returned true. It has a signature of `onFinish(events, options)`. If any of the `onFinish` functions return true, the action is handled and no further `onFinish` functions are called.

Furthermore, each handler can define an `onSetup` and `onTeardown` function that are called at the beginning and end of each action. These can be used, for example, to take a snapshot at the beginning of an action and clear it at the end.

The `options` argument in the function callbacks is just an argument which is an Object that can be passed in when the `ActionManager` is first created. This allows us to pass in arbitrary values like the `editor`, `reconciler` and `snapshots` that can be used within the callback functions. Technically, we can get away with not having these because we can access them in the function context in which `ActionManager` is defined but this allows us to move the handler definitions into separate files to keep things cleaner.

**Comment by thesunny** [comment]
The `ActionManager` above is created the way it is in order to handle three use cases with respect to mapping a user action to a `handler`:

1. The action can be identified by a single event and can be handled immediately: In this use case, we use the `onTrigger` function and if there is a match, we `event.preventDefault()`, run the code that we need to run to handle the action, and then return `true` so that further `onTrigger` and `onFinish` functions aren't called.

2. The action can be identified by a single event and must be handled at the end of the action: In this use case, we can also use `onTrigger` but we don't `preventDefault`. Instead, we return a `function` instead of `true` and that `function` will be called at the end of the action (note: not in the spec above as I missed that use case earlier).

3. The action is identified through a composite of events and or DOM analysis (e.g. we know that `enter` was pressed because the DOM is split): In this case, we use `onFinish` and we have access to the manipulated DOM and an array of all events.
