### ISSUE TITLE
Link example is broken

### ISSUE THREAD

**Issue by zacksiri** [ianstormtaylor/slate#255]
For example try editting the link, it would show up errors. 

![image](http://g.recordit.co/PvAYNB4E1P.gif)

**Comment by kulakowka** [comment]
+1 paste from clipboard do not work for me too...

**Comment by ianstormtaylor** [comment]
Thanks for reporting this, sorry for the delay @zacksiri ! I was on vacation the past ten days. I've isolated why this is happening, and working on a fix.

**Comment by ianstormtaylor** [comment]
Hey @zacksiri sorry for the long wait. The typing behavior in the video is now fixed! (The ability to "edit" an existing link by clicking the link icon button actually isn't part of the example's functionality, so that part isn't available still.)
