### ISSUE TITLE
Proposal for rendering read-only Slate

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2554]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

There is no way to render a lite read-only version of a Slate editor

#### What's the expected behavior?

The desired behavior is to have something like this:

https://github.com/roast-cms/french-press-editor/blob/develop/src/components/vignettes/Reader.js

Either add to Editor or Docs.

**Comment by RyanBertrand** [comment]
Isn’t this read-only?

https://www.slatejs.org/#/read-only

**Comment by thesunny** [comment]
@RyanBertrand 

This was a proposal from somebody in the Slack channel I believe. I posted on somebody's behalf.

The proposal is for a **lite** read-only version. That is, without, all the other Editor related code. The idea was for the use case where a user publishes pages and they still need the renderer but they don't want all the Slate editing code to have to load in.

**Comment by dmitrizzle** [comment]
Hey Ryan, it does the same thing but only takes up 3.35 KB of uncompressed, unformatted code - much less if you optimize it.

**Comment by ianstormtaylor** [comment]
Now that Slate's data model is pure JSON, this should be easier for folks to reason about. They can render the JSON to React components however they'd like, using a recursive rendering technique.
