### ISSUE TITLE
Consider adding versions of slate-edit-table, slate-edit-list, slate-prism, slate-edit-code into packages?

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2556]
#### Do you want to request a _feature_ or report a _bug_?

Requesting a feature

#### What's the current behavior?

Gitbook which provides many of the plugins that make Slate valuable have forked for stability and performance. This means that over time their plugins will become, or have already become, incompatible with this version of Slate.

#### What's the expected behavior?

We should consider having official or sanctioned versions of these plugins that iterate along with the current version of Slate.

If we put them into the Lerna packages in this repo it will be easier to keep them updated in sync with each other.

I am aware that this may not align with @ianstormtaylor usage but I think for a big part of the community, these plugins are what make Slate valuable. Certainly when I was starting, spending hours just trying to get lists, or code editing or tables working would be painful and I think for others, it may mean that they skip adopting Slate in favour of an editor that includes more of the features they need.

This also reduces re-inventing the wheel for common use cases.

**Comment by ianstormtaylor** [comment]
Hey, thanks for opening this @thesunny. You're correct that this doesn't mesh with my vision for Slate. I understand that those packages are valuable to a lot of people, but they aren't something that I want to be part of "core". If people find them valuable enough, someone should take it upon themselves to maintain them. But I don't use them myself, so it's not going to be me.
