### ISSUE TITLE
Can't replace or remove text when selected using triple click, next to void nodes.

### ISSUE THREAD

**Issue by getnashty** [ianstormtaylor/slate#2561]
#### What's the current behavior?

I have a custom node block that takes some extra data and sets them as props on the custom node - with the intent that they are void (i.e. like a date).

When I triple click the text to select all, if I hit delete, or any other character in attempt to remove or replace the selected text, the initial word or character I clicked on is removed/replaced, rather than the selection:

![selection-replace](https://user-images.githubusercontent.com/113112/51873174-25b92500-232a-11e9-946b-f487db2650e7.gif)

Reproduceable:
https://jsfiddle.net/getnashty/zuvqpL63/6/

#### What's the expected behavior?

For the selected text to be replaced / removed

**Comment by rogovdm** [comment]
Experiencing same issue.

Adding custom checkbox, selecting all text. When trying to delete only one char goes away.

![image](https://user-images.githubusercontent.com/1548235/52405823-e383a680-2ad4-11e9-9db2-7af7c84aaebc.png)

![image](https://user-images.githubusercontent.com/1548235/52405835-ebdbe180-2ad4-11e9-98aa-04bca9f64ae1.png)

**Comment by rogovdm** [comment]
oh, yeah. This what helped me:

![image](https://user-images.githubusercontent.com/1548235/52405968-4117f300-2ad5-11e9-8fc4-9d655c308b2e.png)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
