### ISSUE TITLE
Schema invalidations/fixes added to slate history

### ISSUE THREAD

**Issue by jas7457** [ianstormtaylor/slate#2571]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?
When there is something that does not pass a schema validation, both the invalid state and the fixed state are added to slate history.

Windows 10, Chrome 71.0.3578.98, Slate 0.44.10

#### What's the expected behavior?
If there is an invalid state that gets fixed by normalizing, this should not be an entry in the history

#### Example fiddle:
https://jsfiddle.net/bm8zrh97/
This is a character limit schema that makes sure the user does not type more than 50 characters. For each character typed past the 50, the user has to ctrl+z two times that amount before they actually start undoing typed characters.

For example, if the user types 60 characters, they have to undo 21 times until text is actually removed ((60 - 50 cap) * 2) + 1 = 21.

#### Example video
http://recordit.co/j1xIiAVC9A
I typed 10 characters past the 50 cap and had to Undo 21 times until something was undone.

**Comment by ericedem** [comment]
I played around with the fiddle a bit, and adding `editor.withoutSaving()` at least prevents the double undo problem: https://jsfiddle.net/9grw713m/.

It does seem like changes shouldn't be saved to undo unless they pass normalization. I haven't dug super deep, but one thing that may be happening is that the value is getting saved after normalization, even though the state is exactly the same as it was before the normalization.

**Comment by jas7457** [comment]
Yeah I noticed wrapping it in that call only adds 1 bad state to the history, but the original one still occurs. @ianstormtaylor is this by design? If so, what's the correct way to more or less replace the state with what happens in the normalize?

**Comment by ianstormtaylor** [comment]
This is by design, the normalization adds extra operations to the history to return the editor from an invalid state to a valid one. It's currently not possible to "overwrite" the invalid state in the first place. But since history is managed in batches, it shouldn't ever return to an invalid state on undo/redo.
