### ISSUE TITLE
Current Version（0.21.15）has issue when enter chinese in UC browser

### ISSUE THREAD

**Issue by xigongdaEricyang** [ianstormtaylor/slate#2573]

**Comment by xigongdaEricyang** [comment]
https://www.slatejs.org/#/rich-text, this demo in uc browser can't enter chinese

**Comment by ianstormtaylor** [comment]
Hey, thanks for reporting this. I think this is actually a duplicate of #https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!
