### ISSUE TITLE
bug: `normalizeNodeByPath` throws on delete.

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2574]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

If deleting nodes, slate `normalizeNodeByPath` encounters an illegal path and throws.
This is similar to #2528 and using the same fiddle, but looks like not a regression of #2536.

1. Open https://jsfiddle.net/y5q9120p/2/
2. Open the dev console
3. Select all (e.g. Cmd+A)
4. Press Delete
5. See "Uncaught Error: Node.assertNode could not find node with path or key: List [ 0, 0, 0, 0 ]"

I checked whether it's a regression [here](https://jsfiddle.net/dx54Lcve/2/), this is 0.44.9 but fails too:
cc @Calyhre 

I additionally get that error a lot on undo after a working delete (also like in #2528), but that may be the same issue.

#### What's the expected behavior?

It should just work fine.

**Comment by isubasti** [comment]
i believe this is fixed on #2593

**Comment by bebbi** [comment]
fixed by #2593
