### ISSUE TITLE
On simple inline copy-then-paste, `insertFragmentAtRange` inserts as a nested block instead of inline.

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2575]
#### Do you want to request a _feature_ or report a _bug_?

bug
#### What's the current behavior?

A simple inline copy-then-paste gets pasted as separate blocks.

![copy_paste](https://user-images.githubusercontent.com/2752391/52136941-996c7200-2649-11e9-8aa0-f843b0d85a57.gif)

1. open fiddle: https://jsfiddle.net/kj2vspaq/
(1a. for verifying, a more nested fiddle: https://jsfiddle.net/mat306x4/1/)
2. in the second paragraph, select any letter in the middle, press copy (Cmd-C), then paste (Cmd-V)
3. See the paragraph fall apart into multiple blocks.

Two issues:
- The fragment isn't inserted inline
- The selection jumps to the end.

#### What's the expected behavior?

Step 3 should result in no visual difference from before, including the selection endpoint.

**Comment by bebbi** [comment]
So this is related to the functionality introduced in https://github.com/ianstormtaylor/slate/pull/2273.

@steobrien thanks for the great explanation over there. I'd like to relax your check

    hasSingleNode(documentInner)

[here](https://github.com/ianstormtaylor/slate/blob/8e659dbd28cf88ca7659460417b31e0e558c2488/packages/slate/src/commands/at-range.js#L827)

because I think, instead of allowing the melding only in the subset of cases where `documentInner` has a single node, when we have multiple nodes there we can instead check if we *find a path* that matches the fragment's path and if found, return that as the insertion node.

I'm going to see if I can PR this but would love your quick feedback.

**Comment by steobrien** [comment]
Hey @bebbi, that sounds like a good idea. Good luck with the PR!

**Comment by bebbi** [comment]
#### On this PR

I'm going to propose a PR that changes the `findInsertionNode` logic (only).
Originally, I just wanted to allow melding pastes when the document has a non-trivial structure per above. Then I understood that this doesn't address many deeply nested paste issues, so I ended up with a larger change proposal to start addressing nested pastes more generally. Here's the reasoning behind the change:

In relatively 'flat' lists of blocks, the current paste approach works fine, but in deeply nested scenarios (nodes are mostly part of other nodes) and very different block depths throughout the document, it works less well.

The main limitation seems to be that we're currently anchoring the melding calculation at the document's root, which still allows a lot of impedance mismatch between document and fragment structure leaf-side where it gets important.

The proposed implementation addresses that with an approach that establishes a document-to-fragment correspondence starting at leaf-side blocks instead of root-side. This seems to generalize better and solves this issue's fiddle while working for the current tests as well, and all pastes in all examples that I've tried.

#### Beyond this PR

I propose that if there is agreement with the approach, this PR can be merged as it stands, however, beyond that, I'd like to solve copying from deep trees into shallow trees, and this requires a bit more elaboration.

The point here is that to solve all nested-copy cases, we ultimately need the ability to accept a developer-side decision of exactly how deeply to drive the fragment into the "document surface" (see PR for explanation).

If I have some deeply nested content that I paste into a shallow document (and while our use-case has some generic nested structure, let me make a made-up example with tables to illustrate), as an example, say I paste a cell from a table inside a table:

    table
     ..
      table
        row
          cell
            <cursor around a single letter>

then I may not be interested in transferring over the whole tree structure, but have the ability to decide on an app- or blocktype-specific cut-off for just how much structure to paste as a developer. While there could be good defaults for many standard cases, I know our use-case needs a custom decision.

And actually the same is even true when copying from shallow to deep; I may only be interested in a fragment-to-doc match between ancestors to a certain degree: e.g., as a developer I should be able to decide that I want to paste a single word from a table inside a list:

    list
      list item
        table
          row
            cell
              <cursor around word>

into a table inside a table:

    table
      row
        cell
          table
            row
              cell
                <cursor around word>

and just paste that word inline into an existing cell, instead of creating a deeply nested table-inside-list structure inside that cell.

The advantage with the proposed PR is that we can define that cut-off simply by removing root nodes from our paste fragment before letting slate follow through on the paste.
