### ISSUE TITLE
How to complete the list and start a new line?

### ISSUE THREAD

**Issue by kulakowka** [ianstormtaylor/slate#258]
See for example:

![](http://recordit.co/kEALSqSO58.gif)

I think that the list should end, after entering the second blank line. 

I have not understood very well editor API, so I could not fix it myself. But I will be grateful for any advice.

**Comment by ianstormtaylor** [comment]
Hey @kulakowka! I'd be glad to accept a small PR implementing that logic (as long as it keeps the example simple still). As for how to do it, it depends on your own situation. You could choose to implement it with a hotkey like <kbd>cmd-enter</kbd> or via pressing <kbd>enter</kbd> twice like you mentioned. The example is just a very simple thing to show how to use Slate, so it's not exhaustive.

**Comment by sergiulucaci** [comment]
Hei, @ianstormtaylor,  is there any update on this? Or are you still opened for a PR on this?
