### ISSUE TITLE
Adding information about document key

### ISSUE THREAD

**Issue by RohovDmytro** [ianstormtaylor/slate#2581]
Spent an hour figuring out how to get document id after creating a `Value`. Could not find it yet. Is it somewhere? I am very new to the library, so I might missing something.

![image](https://user-images.githubusercontent.com/1548235/52210907-f9088e80-2890-11e9-8efd-6c037128ee79.png)

**Comment by CameronAckermanSEL** [comment]
Hi,

There's a slack channel where you can get some support https://slate-js.slack.com/

Using the issue tracker here makes it too difficult to track help requests. 

Thanks!
