### ISSUE TITLE
No way to forcibly merge operations into a batch in the undo history

### ISSUE THREAD

**Issue by gdehmlow** [ianstormtaylor/slate#2583]
#### Do you want to request a _feature_ or report a _bug_?

Mostly a feature, but IMO it's unexpected behavior

#### What's the current behavior?

`editor.withoutMerging` allows you to force the editor to create save points. It does this by setting `editor.tmp.merge = false`, then performing a set of operations, then setting it back to its previous value.

But setting manually setting `editor.tmp.merge = true` does not keep `editor.tmp.merge = true`.. there are certain operations like `deleteAtRange` that call `editor.snapshotSelection()`:

https://github.com/ianstormtaylor/slate/blob/1ce7c7cc8937dba80c6b75f154a6e3dab2855aa5/packages/slate/src/commands/at-range.js#L94

Which in turn calls `editor.select` with `snapshot: true`, which sets `editor.tmp.merge` back to false.

#### What's the expected behavior?

In my editor I am trying to batch together as many programmatic changes so that the undo history is as coherent as possible to the end user. For example, I may insert a fragment as a result of user action, but then I apply some automatic transformations to that fragment in order to present it to the user. When the user hits undo, I don't want them to see any of the intermediate steps.. I want the transformations and the fragment insertion undone in one swoop.

There should be a way to set an override value to `merge` that cannot be modified by the internal operations of the editor.. such as, for example, a `editor.forceMerge = true`. If this is set, then in `editor.save()`:

https://github.com/ianstormtaylor/slate/blob/73b4cb423e967a1f1f86a152206562755510d3cd/packages/slate/src/commands/on-history.js#L19-L37

 `merge` will always be considered `true` regardless of the value of `editor.tmp.merge`, until the user of `editor` sets `forceMerge` back to `null`.

We could then provide a helper that is kind of the opposite of `withoutMerging` (maybe `withMergingAll`)

**Comment by ericedem** [comment]
@gdehmlow I'm not completely sure I understand the issue you are facing, but a paired down fiddle of the issue could be helpful.

Have you looked at inverting the behavior and saving everything except the parts where you want to merge and calling [`withoutSaving()`](https://docs.slatejs.org/slate-core/commands#withoutsaving)?

**Comment by gdehmlow** [comment]
> For example, I may insert a fragment as a result of user action, but then I apply some automatic transformations to that fragment in order to present it to the user. When the user hits undo, I don't want them to see any of the intermediate steps.. I want the transformations and the fragment insertion undone in one swoop.

Let's say a user hits a button. I want to insert a fragment, and then iteratively replace a bunch of text within the fragment after it's inserted. If the user then hits undo, I want the fragment to disappear (I don't want them to undo each text replacement individually.. they should not see the intermediate steps!). 

Then if they hit redo, I want them to see the fragment with the text all replaced. 

In effect, I want the fragment insertion + text replacement to look kind of like one operation in the undo history.

If I use `withoutSaving` around the text replacement steps, when they hit undo and then redo, the text will _not_ be replaced (since those changes were not saved to the history). Hence why I want to be able to force merging.

Maybe I'm misinterpreting how `withoutSaving` works?

**Comment by ericedem** [comment]
I was thinking is that you use `withoutSaving()` so that you don't keep track of any of that intermediate state, and then you either pull the last operation out of `withoutSaving()` or manually save the state after you are done. So if you had to do `n` operations it would be:

```
// initial state

editor.withoutSaving(() => {
  operations.forEach(child => {
   // do something
  })
})

// manually save
```

I don't recall whether there is a specific manual save, it isn't [listed here](https://docs.slatejs.org/slate-core/commands#miscellaneous-commands) if so.

**Comment by brendancarney** [comment]
I believe this could be addressed with https://github.com/ianstormtaylor/slate/issues/2658

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
