### ISSUE TITLE
Pass (reactive) props to nodes

### ISSUE THREAD

**Issue by preciselywilliam** [ianstormtaylor/slate#2585]
I've read a few threads on the subject (see below). The conclusion seems to be that you can pass props to nodes but that they will not update inside the node, even though an updated value of the prop is sent through the slate editor.

https://github.com/ianstormtaylor/slate/issues/715
https://github.com/ianstormtaylor/slate/issues/763

I have a pretty specific use case for which I've thought of a few possible solutions, none of which I like in particular. I'm wondering if I'm missing something, or if I will have to use a another lib to solve the problem I've got.

I have two pages which both render a editor. Both editors use the same plugins, but they get their data from different slices of the redux store. The following is an example:

Page A: Todo list editor page
Page B: Shopping list editor page

Both editors use the ListItem plugin which renders a ListItem node with the required prop listItemId.

The app state looks as follows:
```
{
  ...store,
  todoListItems: [{ id: 'listItemId', name }, ...todoListItems],
  shoppingListITems: [{ id: 'listItemId', name }, ...shoppingListItems],
}
```

In my real app, the todo items and shopping items are different domains which I don't want to mix (ducks structure).

Right now, my selector connects to redux-router and based on if I'm on url ""*/todo/*" or not, I'll select different parts of the state. If I introduce a third domain which can be used to render the ListItem nodes, I'd have to introduce changes to the selector.

Another option I've thought about is to normalize the state so that each ListItem can be accessed straight by its id. In this case I would be able to use the same selector regardless of the domain/itemtype (i.e. state.items[itemId]). The problem with that is that I have to mix state from different domains.

Is there a cleaner way of doing this? Maybe a solution that involves react context? 

Appreciate if someone who has more experience with slate can advise.

Thank you!

**Comment by ericedem** [comment]
@preciselywilliam you will likely get quicker feedback if you ask questions in the [slack channel](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md#asking-questions).

That being said I'm having trouble getting a full picture of what's going on in your app. A paired down example of the problem you are facing in a [fiddle](https://jsfiddle.net/fj9dvhom/1/) would be really helpful. Thanks!

**Comment by brendancarney** [comment]
@preciselywilliam Like @ericedem mentioned, I'd recommend asking for help in the slack channel. If you feel there is a bug, or you'd like to request a feature, please feel free to open another issue. Thanks!
