### ISSUE TITLE
Text goes in revers on Android

### ISSUE THREAD

**Issue by sinisavukovic** [ianstormtaylor/slate#2586]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
Text goes in reverse when typing on Android on official slate example

Browser: Chrome 72
OS: Android 8.0

#### What's the expected behavior?
Text should be shown in normal order

**Comment by thesunny** [comment]
Hi @sinisavukovic 

This is addressed in this PR https://github.com/ianstormtaylor/slate/pull/2565 and there are details in this issue https://github.com/ianstormtaylor/slate/issues/2062

Closing this issue in favor of the others.
