### ISSUE TITLE
Document issue for Plugin Hook

### ISSUE THREAD

**Issue by sunjingwu** [ianstormtaylor/slate#2596]
"onCommand" 后面的说明和 “onQuery” 是一样的，这不对吧？

![image](https://user-images.githubusercontent.com/7359030/52692593-45458400-2f9f-11e9-9c88-92bf4a5d8e78.png)

**Comment by ericedem** [comment]
Thanks, yea that looks like a copy paste error. That should all read for commands instead, the usage is basically the same.
