### ISSUE TITLE
Unable to get previous state in onChange plugin

### ISSUE THREAD

**Issue by damien-monni** [ianstormtaylor/slate#2601]
I would like to create a plugin to save the editor content when onChange is fired. Following documentation, I would like to check previous document value before saving to database with:

```javascript
if (prevValue.document !== newValue.document) {
  // Save to database
}
``` 

But I can't find a way to get my previous value from the onChange plugin handler:

```javascript
const SavePlugin = () => ({
  onChange: ({ value: newValue }, next) => {
    // How can I get previousValue ??
    if (prevValue.document !== newValue.document) {
      const content = JSON.stringify(newValue.toJSON());
      localStorage.setItem('content', content);
    }

    next();
  },
});
```

Is there a way to get the previous state value from the onChange plugin event handler?

**Comment by adjourn** [comment]
Slate has undo/redo functionality so there probably is a way to rebuild old value, maybe someone else can give you that answer but the following doesn't work for you? 

Variable _should_ be nicely isolated and accessible in your plugin.

```js  
let previousValue = null;

const SavePlugin = () => ({
  onChange: ({ value: newValue }, next) => {
    if (previousValue !== null) {
      // has previous value
      // do your thing..
    } else {
      // first time running
    }

    // don't forget to update
    // it for the next round
    previousValue = newValue;

    next();
  },
});
```

**Comment by gdehmlow** [comment]
I think this is a question better suited for the Slack channel (https://slate-slack.herokuapp.com/).

But you could use the closure of the `SavePlugin` like so:

```
const SavePlugin = () => {
  let previousValue = null;
  return {
    onChange: ({ value: newValue }, next) => {
      // How can I get previousValue ??
      if (prevValue.document !== newValue.document) {
        const content = JSON.stringify(newValue.toJSON());
        localStorage.setItem('content', content);
     }
     previousValue = newValue;
      next();
    },
  };
};
```

**Comment by ericedem** [comment]
@damien-monni Did that answer your question?

**Comment by damien-monni** [comment]
Yes it is!
Thank you @gdehmlow ;)

**Comment by ericedem** [comment]
@damien-monni Great! Mind closing the issue as well? Thanks!

**Comment by damien-monni** [comment]
You can close the issue (y)
