### ISSUE TITLE
More tests that show pasting fragments into "deep" editor trees.

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2604]
These additional tests demonstrate how the "general pasting" PR #2589 improves pasting sections into a deep tree. See issue #2575 for more in-depth discussion.
Above tests just throw before PR #2593 which fixes a *lot* of move_node issues.
They've mainly been added to fix the throwing in slate, but will also only work post #2589.
So they need PRs #2589 *and* #2593.

After a slack discussion, I'm posting this issue to link to a PR with tests that will succeed once both "general pasting" #2589 and "move_node bug fix" #2593 are merged.
These tests throw errors pre-#2593.

The relevant commit here is 94e4f77.
As discussed in slack, I'm pushing that commit together with the commits belonging to #2589 because of the chance of conflicts. I can rebase later if needed.

**Comment by ericedem** [comment]
@bebbi Can you change the title and description to reflect what the issue actually is? Like "Add tests for X, Y, Z use cases". Right now this issue is just a chain of references to other places and doesn't really indicate what the problem is.

**Comment by bebbi** [comment]
@ericedem does that improve things? You can see there's some complication that evolved over the time of two PRs being open to fix a partially overlapping set of issues.

**Comment by ericedem** [comment]
@bebbi Yep, that helps a lot!

**Comment by bebbi** [comment]
Now that newest master has #2593, we can close this in favor of #2589.
