### ISSUE TITLE
discussion: add keyboard control to the mentions example and / or make it a plugin

### ISSUE THREAD

**Issue by ericedem** [ianstormtaylor/slate#2609]
#### _idea_

When I implemented the mentions example, the goal was to highlight how to interact with Slate around capturing mentions, inserting void nodes, and displaying the suggestions as a floating menu. An additional goal was to try and do this in as simple a fashion as possible, which means putting all the logic in the parent component instead of using a Slate plugin.

This is not how we have it implemented in production at [cake.co](https://www.cake.co). Because there is so much additional logic, in large part due to keyboard control, we have it implemented as a plugin. Implementing as a plugin also adds quite a bit of complexity and conceptual overhead, which is something I wanted to avoid in the slate plugin.

I have received some requests to either add support for keyboard support in the plugin, which will add quite a bit of complexity, or to open source the plugin itself. I'd love to open source it, but I don't know if I have the time or energy to maintain such a project right now, so I'm worried that it will become defunct like the plethora of other plugins (this is why I added it as an example in the first place).

I'm open to updating the example to be a bit more fully featured, and converting the example to a plugin. Here are the pros and cons I see:

### Pros
1. **Drop in solution** This is probably the most compelling solution. While it would be hard to understand, it would be very easy to just copy paste and use as is, even in an already complicated application.
2. **It's already pretty complex** It's already a pretty complicated solution, so maybe it would be more worthwhile just to go all the way so the people have the right framework to work from.

### Cons
1. **Ease of understanding** Right now the example is already fairly complicated, but it is easy enough to understand. If we make it a plugin, now users will need to understand what a plugin is (which are already somewhat complex) before they can even begin to understand how to implement mentions.
2. **Maintainability** There are a lot of edge cases to consider with plugins, and I'm worried that it will become pretty difficult to maintain by the community. This is probably my biggest concern.

Anyways, this will take a little bit of work for me to do, so I'd like some feedback from the community about whether this is the right thing to do before jumping into it.

**Comment by oyeanuj** [comment]
@ericedem Firstly, thank you for contributing that mentions example, and for starting this discussion. I think mentions is one functionality that there isn't a solid plugin developed in user-space - hence the pressure on you :)

I imagine outside of fleshing out the examples to include the plugin logic, a couple of other options that might work are:

1. Create a plugin but put a notice for co-maintainers who can keep it running so that you don't have to commit all of your energy.

2. Create a repo for the example, for mentions and we can link it from the examples here. With an example repo, there is no pressure on maintaining it as it exists solely for demonstration purposes.

I think the lessons you've learnt around building it into a production use-case are the most valuable, so an example that illustrates that will atleast prevent people from making the same mistakes (without hopefully adding much burden on you).

Thoughts?

**Comment by ericedem** [comment]
> Create a repo for the example, for mentions and we can link it from the examples here. With an example repo, there is no pressure on maintaining it as it exists solely for demonstration purposes.

I think the trouble with this is what we've seen in the past. There are at least 3 different mention example repos floating around that I can think of where the examples themselves no longer work with the current version of slate, which made them effectively useless when I was trying to do my own implementation. I think given my best intentions the same might happen with any repo that I started, especially considering it would only be maintained by me, and maybe a couple other people.

This is the primary reason I decided to contribute it as an example in the core repo, since it would be treated as a first class citizen for maintenance and could easily receive bug fixes along with the evolution of Slate. This has already proven to be useful as there have been a few issues that have been found and quickly fixed, and not just by me! 😄

> I think the lessons you've learnt around building it into a production use-case are the most valuable, so an example that illustrates that will atleast prevent people from making the same mistakes

I think this is the most compelling reason to pluginify the example, so good to hear that feedback.

After thinking about this today, and hearing your feedback, I'm sold on fleshing out the example some more. It is already, by nature, pretty complicated, and I think it would be best to lay that out for people so that they don't approach it thinking things will be easy.

One thing that I think could be a benefit too is that I had to do some non-obvious things that I feel were a bit hacky to get this working. Hopefully with more eyes on it we might find a better approach, or possibly even inform future evolutions of the Slate plugin architecture.

**Comment by oyeanuj** [comment]
I think all of that makes a lot of sense!

> Hopefully with more eyes on it we might find a better approach, or possibly even inform future evolutions of the Slate plugin architecture.

Both of these are excellent reasons, especially as Slate is still finessing the APIs!

**Comment by scottluptowski** [comment]
Hi @ericedem, really eager to see this plugin! I am currently working on the same feature now and ran into similar issues. At a certain point it became much easier to write my code as a plugin than to follow the example.

I'm also really interested in any issues you ran into while testing. I am currently testing the plugin unit-test style, but it involves stubbing out more values than I would like!

The heart of my logic lives in `onKeyDown`, so I have to e.g. stub out fake events, call the handler directly, etc:
```js
function MentionsPlugin(options) {
  return {
    onKeyDown(event, editor, next) {
      switch (event.key) {
        case 'Tab':
        // ...
        case 'Enter':
        // ...
      }
    }
  }
}
```

**Comment by ericedem** [comment]
@scottluptowski I submitted a PR at #2610 That's awaiting review if you wanted to check out the plugin implementation.

**Comment by scottluptowski** [comment]
@ericedem Thanks so much!

**Comment by ianstormtaylor** [comment]
See https://github.com/ianstormtaylor/slate/pull/2610#issuecomment-490719600.
