### ISSUE TITLE
insertFragment run inconsistency for large fragment

### ISSUE THREAD

**Issue by joehua87** [ianstormtaylor/slate#261]
These 2 output run by 1 code:
https://github.com/joehua87/slate/blob/master/test/transforms/fixtures/insert-fragment/large-block/output.json
and
https://github.com/joehua87/slate/blob/master/test/transforms/fixtures/insert-fragment/large-block/output-1.json

**Comment by ianstormtaylor** [comment]
Hey @joehua87 can you explain the issue you're running into here more? It would go a long way towards making it easier to resolve. Thanks

**Comment by joehua87** [comment]
Hey @ianstormtaylor this is the step to reproduce the error:
* Open http://slatejs.org/#/paste-html in Chrome
* Copy a long html (for example, in this page) & paste into that page
You will see the inconsistence pasted result
First, I thought it was caused by html serializer but finally find out that it was caused by insertFragment function.
So I've created the test fixture for insertFragment (see here https://github.com/joehua87/slate/tree/master/test/transforms/fixtures/insert-fragment/large-block),
And it result difference output each time (For example, you can see output.json & output-1.json)

**Comment by ianstormtaylor** [comment]
@joehua87 thanks for the info! That's perfect. I'll check this out

**Comment by ianstormtaylor** [comment]
@joehua87 or @cobbweb could one of you make a PR with a test case that fails inconsistently (but sometimes succeeds if that's the case) and I can check it out? Thanks!

**Comment by joehua87** [comment]
@ianstormtaylor I've created the new test for the error case at https://github.com/joehua87/slate
* `npm run test-large-block` to run the error case. 
* It will run the same code 10 times & output 10 difference results. 
* You can see the difference result in test/large-block-error/output folder

Please tell me if something is not clear. :)

**Comment by ianstormtaylor** [comment]
Woot, happy to report that @somus's pull request https://github.com/ianstormtaylor/slate/pull/322 fixed this issue!
