### ISSUE TITLE
Delete text from the menu causes crash

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#2617]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Slate crashes when Undo-ing 

1. Go to https://www.slatejs.org/#/rich-text
2. Select all the text in the rich text editor
3. Right click on the selection and press the `Delete` menu entry
4. Undo

My system:
> Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
> Name: Firefox
> Version: 65.0.1
> Identifiant de compilation: 20190211233335
> Release Channel: release
> User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0
> Operating system: Darwin 17.7.0

It also happen with Chrome
> Version 72.0.3626.109 (Official build) (64 bits)

Gif:
![gif](http://g.recordit.co/qzb7SxbouU.gif)

#### What's the expected behavior?

Delete the text correctly and undo the delete operation correctly.

#### Additional Notes

The editor text becomes corrupted when deleting from the menu when there is multiple styling in the seleted text.

**Comment by brendancarney** [comment]
I haven't looked into this much yet, but my guess is that no event is fired/handled by clicking delete in the context menu. I wonder how we would handle this. Maybe watching for changes with MutationObserver?

It's not exactly related, but maybe @thesunny has some ideas since I know they have experience dealing with potentially related input issues for android support.

**Comment by ntgussoni** [comment]
@brendancarney  same happens if you press backspace.

This is the stacktrace

`Error: Decorations must be created with a `type`, but you passed: {"anchor":{"key":"1984","offset":0,"path":[0,0]},"focus":{"key":"1984","offset":0,"path":[0,0]},"mark":{"type":"placeholder","data":{"key":0}}}
    at Function.value (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:1:17185)
    at value (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:1:16170)
    at Array.map (<anonymous>)
    at Function.value (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:1:16439)
    at a.value (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:1:133334)
    at a.e.(anonymous function) (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:1:124238)
    at a.value (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:1:172175)
    at Mi (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:22:63126)
    at ji (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:22:62921)
    at Ti (https://www.slatejs.org/main-3ef18fc13ba8bf31a2e8.js:22:66768)

    in a
    in div
    in a
    in a
    in div
    in a
    in div
    in be
    in xe
    in div
    in a
    in a
    in div
    in a
    in a
    in a
    in a`

**Comment by ntgussoni** [comment]
#2750

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
