### ISSUE TITLE
Deleting Inline at beginning of editor causes error.

### ISSUE THREAD

**Issue by bnowlin** [ianstormtaylor/slate#2621]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

1. Go to https://www.slatejs.org/#/links
2. Highlight the beginning text "In"
3. Enter any text for link
4. Move cursor to end of "In"
5. Press backspace - deletes n
6. Press backspace - deletes I
7. Press backspace - Causes error

#### What's the expected behavior?

The inline (void false) Object is deleted on step 6. 

Edit: My use case involves small pieces of text so I see this more often than an edge case. Triggering this bug in my React app causes the UI to freeze ~15.

**Comment by dons20** [comment]
Is this the error you're getting as well?
![image](https://user-images.githubusercontent.com/3958349/53690825-e1adab80-3d3f-11e9-8909-97adf20b424f.png)

**Comment by bnowlin** [comment]
Yes.

**Comment by ShanSenanayake** [comment]
Is there any plan to merge https://github.com/ianstormtaylor/slate/pull/2850? 

We are having this issue in our platform as well. Would be nice to have it merged for next release.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
