### ISSUE TITLE
Editor Validation Breaks after removing parent nodes

### ISSUE THREAD

**Issue by ldavidpace** [ianstormtaylor/slate#2623]
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?

When parents of nodes are removed the editor tries to validate a node that does not exist this throws an error and causes all other validation to stop working.

[jsfiddle](https://jsfiddle.net/paceld/hg8mf6by/33/)
![slate-error](https://user-images.githubusercontent.com/25068382/53522997-db49d600-3a98-11e9-89fd-29a2512c5ecc.gif)

Slate version 0.44.8
Slate-React 0.21.16
Chrome 72.0.3626.119
Mac Os 10.13.6

#### What's the expected behavior?

The editor should always keep validating nodes and normalizing any that are invalid.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
