### ISSUE TITLE
When focusing the editor in firefox, the selection does not match the click position

### ISSUE THREAD

**Issue by darkyshiny** [ianstormtaylor/slate#2631]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
In Firefox when the editor is focused the selection is set to the beginning of the document rather than the position that was clicked.
This is likely the same problem as #2095 
This is reproducible in both the template jsfiddle and the Slate examples

##### Steps to reproduce
1. Place the cursor anywhere other than the start of the document
2. Click outside the editor
3. Click inside the editor again

Jsfiddle:
https://jsfiddle.net/fj9dvhom/1/

Gif:
![xvnxktpsrv](https://user-images.githubusercontent.com/16773900/53800417-f6a35e00-3f3c-11e9-8688-e153a0bc03d4.gif)

OS: Windows
Browser: Firefox 65.0.2
slate version: 44.10
slate-react version: 21.16

#### What's the expected behavior?
Selection is set to where the user clicked.

**Comment by brendancarney** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2095
