### ISSUE TITLE
Decorations should not be mutable

### ISSUE THREAD

**Issue by gdehmlow** [ianstormtaylor/slate#2634]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Take the [search highlighting example](https://www.slatejs.org/#/search-highlighting). Enter a search term. Select the end of the highlighted word and type.. the highlight continues as the decoration is appended to:

![decorationbug](https://user-images.githubusercontent.com/850025/53936154-c3a4bb80-405d-11e9-8478-5e412b4d4387.gif)

Likewise, if you hit enter, both lines become highlighted:

![decorationbug2](https://user-images.githubusercontent.com/850025/53936207-efc03c80-405d-11e9-8bef-94f4631598b3.gif)

#### What's the expected behavior?

Modifying decorated text should re-evaluate the decorations and ensure that they are valid.

**Comment by gdehmlow** [comment]
As an amendment to this issue, it seems that sometimes decorations can come back from the grave. See this fiddle: https://jsfiddle.net/710djobp/8/

![weird decorate issue](https://user-images.githubusercontent.com/850025/53997070-ae786d00-40ef-11e9-9772-455125437650.gif)

The idea is that roughly 50% of the time, when a character is entered, the text of the current node should turn red. As we can see, `decorateNode` is only ever firing for the current block being typed in (as we expect).

But the text for _other_ nodes will sometimes turn red.. even though they aren't having their respective `decorateNode` methods called!

**Comment by isubasti** [comment]
@gdehmlow not sure about how we can fix the original issue but the amendment is actually a non issue. it looks like it come back from the grave because it's decorating `document` which is not a `block` but a `node` as well. if you do:
```
if (node.object !== 'block') return [];
```
at the very start of `decorateNode` function then you won't get that issue

**Comment by imaGuru** [comment]
> What's the expected behavior?
> Modifying decorated text should re-evaluate the decorations and ensure that they are valid.
IMHO that is your job. You should reevaluate decorations in onChange hook

Decorations should mutate it's focus and anchor points when edited (like they do now). This is actually very desirable and I am using this functionality to mark sections of my document. So when a user modifies a section of the document I still maintain the correct start and end points of the section. The same applies to collaborative cursors - e.g. if you edit inside someone's selection

Also the bug described doesn't seem to exist anymore in the recent annotation update

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
