### ISSUE TITLE
decorateNode does not get called after shouldNodeComponentUpdate returns true for non-current nodes 

### ISSUE THREAD

**Issue by gdehmlow** [ianstormtaylor/slate#2636]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When `shouldNodeComponentUpdate` returns true, when the node is re-rendered, `decorateNode` does _not_ get called for that node.

See this fiddle: https://jsfiddle.net/710djobp/9/
And this gif: 
![another weird decorate issue](https://user-images.githubusercontent.com/850025/53997265-60179e00-40f0-11e9-8c79-2c7ff6484822.gif)

Notice how `decorateNode` is only ever called for the current node being operated on, even though we return `true` for many other nodes' `shouldNodeComponentUpdate`.

#### What's the expected behavior?

If `shouldNodeComponentUpdate` returns `true` for a node, it should call `decorateNode` for that node.

I _think_ the bug may be a combination of these two lines:

https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate-react/src/components/node.js#L135
https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate/src/interfaces/element.js#L2007

We _do_ in fact re-render the other nodes thanks to `shouldNodeComponentUpdate` returning `true`, but the `getDecorations` call is memoized, so it returns the same thing it returned last time instead of calling `decorateNode` on the editor as it should here: https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate/src/interfaces/element.js#L446

I think this may be because `getDecorations` takes just `node`, `editor` as an argument, and `editor` never changes identity + the non-current nodes probably haven't changed.

## Solutions

The easiest solution I can think of is simply not memoizing `getDecorations`. Whether the component is re-rendered at all is already memoized (with our escape hatch being `shouldNodeComponentUpdate`), and `getDecorations` is a part of the `Node` render method, so it seems redundant to me. Or maybe we should create a special non-memoized `forceGetDecorations` that `Node.render()` can use?

Another option would be to temporarily save the result of `shouldNodeComponentUpdate`... if it is true when we call `node.getDecorations()`, pass an additional unique third argument like `performance.now()` in order to blow through `memoize`.

Or perhaps we do a hybrid approach where we preserve the result of `shouldNodeComponentUpdate` and only if `true` do we call the `forceGetDecorations` method?

I think I could work around this by, maybe in `onChange`, detecting that `shouldNodeComponentUpdate` will be true for a certain set of nodes, and then setting some unique data on those nodes via `setNodeByKey`.

**Comment by isubasti** [comment]
it is running `shouldNodeComponent` update because it is indeed need to be updated since you're decorating `document` node as mentioned [here](https://github.com/ianstormtaylor/slate/issues/2634#issuecomment-470761142)

**Comment by isubasti** [comment]
@gdehmlow does that makes sense and fixed the issue that you're having. if so can this issue be closed?

**Comment by gdehmlow** [comment]
I think the issue I raised is still valid - even if I don't provide decorations to the `document`, it still doesn't call `decorateNode` for nodes _other_ than the one that has actually changed because of the memoization issue: https://jsfiddle.net/rwhz27to/

**Comment by gdehmlow** [comment]
I figured out a workaround, but I still don't think the current behavior is desired. If I want to force the re-rendering of a node, it's probably for a good reason and thus should try to use the freshest data possible.

Conceptually, my implementation of `decorateNode` can depend on things besides just the `node` itself.. and there's currently no way for me to tell Slate that this is the case.

**Comment by isubasti** [comment]
decorations are actually one of the performance bottleneck in slate ATM. even with memoizing, once you have certain number of decorations in a node the fps drops significantly.

**Comment by cmhchoi** [comment]
Hi @gabrielrtakeda - do you mind sharing some tips on what you did for your workaround please?

**Comment by cmhchoi** [comment]
Hi @isubasti - appreciate that it is a bottleneck for performance, but I think having an option as @gdehmlow proposed would be more flexible 🙏

**Comment by isubasti** [comment]
@cmhchoi not memoizing is not really solving the problem since the issue itself is not the memoize. the `getDecorations` function is only called on `renderNode`, without any change to the node `renderNode` won't get called. it might require a lot bigger changes than just simply removing the memoization.

**Comment by gdehmlow** [comment]
@cmhchoi my workaround was to set data on the block like this:

```jsx
            editor.setNodeByKey(block.key, {
              data: block.data.set('misspelledBlock', misspelledBlock),
            });
```

to force the block to re-render completely

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
