### ISSUE TITLE
Add documentation for gh-pages:fork

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2637]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

There is no documentation on how to publish a fork to github pages.

#### What's the expected behavior?

With the Android PR, I've included a script in `package.json` to allow forks to publish to github pages. Need to add documentation on how to use it.

**Comment by ianstormtaylor** [comment]
No longer using `gh-pages` so I think we can close this.
