### ISSUE TITLE
Add docs to clarify how to `setState` during `onFocus`

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2640]
#### Do you want to request a _feature_ or report a _bug_?

Documentation Improvement

#### What's the current behavior?

Currently, according to these two issues, when you `setState` during an `onFocus` event, the focus will fail.

https://github.com/ianstormtaylor/slate/issues/2097
https://github.com/ianstormtaylor/slate/issues/2434

#### What's the expected behavior?

Since this feels like a common way to use `setFocus` (for example, to change the styling of an editor when it has the focus or to start an editing session) we should explain that there is a race condition and there is a simple workaround which is to use `setTimeout` as per @klis87 recommendation:

```js
onBlur = (event, editor, next) => {
    next();
    setTimeout(() => this.setState({ hasFocus: false }), 0);
}; 
```

We can remove the documentation if this ever gets fixed but it's been a bug since August so could benefit from documentation in the mean time.

**Comment by brendancarney** [comment]
Might be fixed by: https://github.com/ianstormtaylor/slate/pull/2660

**Comment by ianstormtaylor** [comment]
I think the biggest issue here is that `onFocus/onBlur` are browser-level events. Really people should be using `onChange` for this kind of state management instead of the low-level events. (Although I see why it's confusing.)

**Comment by IanVS** [comment]
I'm still trying to learn slate, and this is a good tip, but I can't quite figure out how to determine whether a `Change` contains a focus or blur event. The [glossary](https://docs.slatejs.org/general/glossary#change) is empty, so I'm not sure what's available on the `Change` that's provided to `onChange` handlers.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
