### ISSUE TITLE
`slate-html-serializer` not deserializing nested elements in test environment

### ISSUE THREAD

**Issue by zyqxd** [ianstormtaylor/slate#2641]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

Version:
`slate@0.44.12`
`slate-html-serializer@0.7.36`
`mocha@2.3.4`
`

Hard to produce JSFiddle since regular behaviour is fine:

Serializer Rules:
~~~js
const test = new Html({ 
  rules: [
    serialize(node: Object, children: any) {
      if (node.object === 'inline' && node.type === 'link') {
        const href = node.data.get('href');
    
        return (
          <a href={href} target="_blank" rel="nofollow noopener noreferrer">
            {children}
          </a>
        );
      }
      if (node.object === 'block' && node.type === 'line') {
        return <div>{children}</div>;
      }
    },
    deserialize(el: HTMLElement, next: Function) {
      if (el.tagName === 'A' && !el.hasAttribute('data-type')) {
        return {
          object: 'inline',
          type: 'link',
          data: { href: el.getAttribute('href') },
          nodes: next(el.childNodes),
        };
      }
      if (el.tagName === 'DIV' && !el.hasAttributes()) {
        return {
          object: 'block',
          type: 'line',
          data: {},
          nodes: next(el.childNodes),
        };
      }
    }
  ],  
  parseHtml: (html) => {
    const doc = document.implementation.createHTMLDocument('');
    doc.body.innerHTML = html;
    return doc.body;
  },
  defaultBlock: 'line',
});
~~~

Live testing
~~~js
const html = '<div><a href="href" target="_blank" rel="nofollow noopener noreferrer">test</a></div>'
test.serialize(test.deserialize(html));
=> "<div><a href="href" target="_blank" rel="nofollow noopener noreferrer">test</a></div>"
~~~

Running in test environment
```
const obj = converter.deserialize('<div><a href="href" target="_blank" rel="nofollow noopener noreferrer">test</a></div>');
console.log(converter.serialize(obj))
=> <div></div>
```

I notice this happening to a bunch of different rules, everything only deserializes one level deep, so for example
```
serialize(deserialize("<img />")) => "<img />"
```

but 
```
serialize(deserialize("<div>test</div>")) => "<div></div>"
serialize(deserialize("<div><img /></div>")) => "<div></div>"
```
(Note, this is also only in the test environment)

#### What's the expected behavior?

Test works properly

**Comment by isubasti** [comment]
@zyqxd you might want to compare the lowercase tagname like so:
`el.tagName.toLowerCase() === 'div'` instead of `el.tagName === 'DIV'`. my gut feeling says that this is the actual problem as `nodes: next(el.childNodes)` should handle nesting

**Comment by zyqxd** [comment]
@isubasti 
Yeah i have the same suspicion about next(...) in mocha. I thought it was the dom tree passed in test was different from other environments but through inspection, I couldn't find a difference.

Also, for `tagName`s, for now there is no case for parsing XML.

**Comment by isubasti** [comment]
@zyqxd it seems that you misunderstood what i mean. can you check with console.log or something during test whether it actually reach any of your deserialise or is it just deserializing `#text` from the core `HTMLSerializer`.

**Comment by zyqxd** [comment]
@isubasti yes during testing, the serializer is reached and gets within the `if` block. Afterwards, its called again with `tagName` of undefined, which I'm assuming is the reason why my test is failing (it should be a nested element).

**Comment by isubasti** [comment]
@zyqxd alright, that's a good information. the problem seems to be that `DOMParser` inside mocha behaves differently. need to find out how to use the same `DOMParser` either through mocha's config or pass a `parseHTML` function to https://github.com/ianstormtaylor/slate/blob/master/packages/slate-html-serializer/src/index.js#L104

**Comment by zyqxd** [comment]
@isubasti Yes that was my initial attempt of plugging 
```
(html) => {
    const doc = document.implementation.createHTMLDocument('');
    doc.body.innerHTML = html;
    return doc.body;
  },
```

which is take from the [mozilla DOMParser extension](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#DOMParser_HTML_extension_for_other_browsers)

**Comment by isubasti** [comment]
@zyqxd https://stackoverflow.com/questions/42649700/using-domparser-in-javascript-testing-with-mocha-and-jsdom have you tried something like this?

**Comment by zyqxd** [comment]
It was a problem with the dom parser in mocha. Wrote my own. Thanks
