### ISSUE TITLE
inline node and block node can not be siblings

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2642]
#### Do you want to request a _feature_ or report a _bug_?

**both**

#### What's the current behavior?

 `inline` node (  or `text` node ) and `block` node  can not be siblings.

e.g.

```
<div>
<div><span>some text (inline node)</span><p>paragraph( block node )</p><div>
</div>
```

Once this happens, only the first node is retained.

#### What's the expected behavior?

In the real world , It should be acceptable.
Therefore, I hope to be able to lift this low-level restriction.
Or, at least, it should also be made configurable.

In addition, consider the following scenario:
```
<a href="link"><div><h3>Title</h3><img src="a logo" /><div class="body">Content</div></div></a>
```
In the code above, ` a` tag is an `inline` node, `div` and `h3` tag both are `block` node. This scene is reasonably present in the real world, but not supported by Slate.

**Comment by CameronAckermanSEL** [comment]
I disagree with the assertion that it is not supported by slate. You can achieve this if you have these inserted into the document as inline nodes, which nothing about Slate prevents you from doing.

**Comment by travigd** [comment]
Treating an `h3` and `div` as an inline is probably less than ideal, IMO. The "better" solution might be to wrap the `<a />` in a `<p />` tag (or similar), but there are still issues with that, especially since blocks and inlines don't have equivalent behavior (I just opened an issue, #2644, that talks about that and is related to this issue).

**Comment by CodePlayer** [comment]
@CameronAckermanSEL  I think this kind of consideration is not rational enough. Because in the real world, it’s not just such a scene that exists in isolation.

E.g.  in an online shopping mall, `a` tag can wrap a series of information about a commercial product, such as name、price、vendor、image、summary...etc.
In such a scenario, `a` tag should be a `block` node in Slate. However,  in most other scenarios, `a` tag should be considered as a `inline` node.  There are many similar scenarios and they may be more complicated in the real world.

Even if you think your scene doesn't need it, you shouldn't ignore the real needs of others.

I think, at least, should make it configurable, in other words, should allow overwrite the default schema.

**Comment by CameronAckermanSEL** [comment]
In contrast, is it more rational to redo the model for problems that are solvable as is, or problems that are solvable with a plugin or a cheaper PR? 

I honestly think your hang up is based on terminology,

**Comment by CodePlayer** [comment]
In fact, `a` tag can really play the three roles of `block` node, `inline` node, and even `text` node at the same time.

However, the key issue is that performing the same operations on `block` node, `inline` node and even `text` node will result in some different results that are not as expected.  Because many of the behaviors of `block` node, `inline` node and `text` node are different in Slate.

For example, if you press the `Enter` key in `block` node and `inline` node, the default behavior they bring is different.

I have disguised `block` node as `inline` node or disguised `inline` node as `block` node according to your suggestion. However, the results are not ideal, even quirky.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2653. I’m open to this potentially, but it’s not an easy change and will require someone putting in the effort to make it happen nicely.
