### ISSUE TITLE
Overwrite default schema

### ISSUE THREAD

**Issue by travigd** [ianstormtaylor/slate#2644]
#### Do you want to request a _feature_ or report a _bug_?
Feature(?)

We have a use case where we want to be able to have text and blocks within the same block. The actual reason is kind of a hack; we want block-style selection mechanics (where you have to manually cursor-over to move from one node into the next), so if there's a better way to do that I'm all ears.

But is it possible (and it seems like it's not - hence the issue) to override Slate's default schema to allow blocks and inlines to appear within the same Slate block?

**Comment by CameronAckermanSEL** [comment]
https://docs.slatejs.org/guides/data-model#documents-and-nodes

> The actual reason is kind of a hack; we want block-style selection mechanics (where you have to manually cursor-over to move from one node into the next), so if there's a better way to do that I'm all ears.

So, rephrasing to make sure I have this correct: you'd like to be able to have a clear division on whether the inline or the text is selected, right? 
If that's the case there's a plugin called `slate-sticky-inlines` that would do this for you, except its out of date and needs to be updated. There's a PR to update it to work with latest slate, and that might be enough to get you going.

That said, I don't find this to be a compelling justification to complicate the model by blurring the division between blocks and inline nodes. This guide might help illuminate the purpose for these nodes in the model and why they exist. The selection semantics, I feel, are a transient and overcome-able issue that doesn't justify a dramatic change.

https://docs.slatejs.org/guides/data-model#documents-and-nodes

**Comment by travigd** [comment]
> Blocks can only contain either other block nodes, or inlines and text nodes. This is another "sane" restriction that allows you to avoid lots of boilerplate if statements in your code. Blocks either wrap other blocks, or contain actual content.

What kind of boilerplate does this actually reduce? One would still need to know if the block contains other blocks or text/inlines if that kind of thing matters to the consuming code. Also, it's the kind of thing that could definitely be a default but overrideable fairly easy (I do think it's somewhat of a sane _default_).

**Comment by CameronAckermanSEL** [comment]
Whether a node is a block or an inline has considerations when it's split, merged, or with how selection behaves (as you observed). Don't have a lot of specific information unfortunately, this is probably a question that Ian will have to answer
