### ISSUE TITLE
Paste HTML example doesn't support images

### ISSUE THREAD

**Issue by gnestor** [ianstormtaylor/slate#2645]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

When pasting HTML that includes an image into the paste HTML example editor, everything pastes correctly except for images.

To reproduce, copy this into the [paste HTML example](https://www.slatejs.org/#/paste-html):

<p align="center">
  <a href="#"><img src="/ianstormtaylor/slate/raw/master/docs/images/banner.png" style="max-width:100%;"></a>
</p>
<p align="center">
  A <em>completely</em> customizable framework <br>
  for building rich text editors.
</p>
<br>
<p align="center">
  <a href="#why"><strong>Why?</strong></a> ·
  <a href="#principles"><strong>Principles</strong></a> ·
  <a href="http://slatejs.org" rel="nofollow"><strong>Demo</strong></a> ·
  <a href="#examples"><strong>Examples</strong></a> ·
  <a href="/ianstormtaylor/slate/blob/master/docs/general/plugins.md"><strong>Plugins</strong></a> ·
  <a href="http://docs.slatejs.org" rel="nofollow"><strong>Documentation</strong></a> ·
  <a href="/ianstormtaylor/slate/blob/master/Contributing.md"><strong>Contributing!</strong></a>
</p>
<br>
<p align="center">
  <a href="http://slatejs.org" rel="nofollow"><img src="/ianstormtaylor/slate/raw/master/docs/images/preview.png" style="max-width:100%;"></a>
</p>
<p align="center">
  <a href="https://unpkg.com/slate/dist/slate.min.js" rel="nofollow">
    <img src="https://camo.githubusercontent.com/ef0d60eaec5bd27f719512dd8365b1e32118975c/687474703a2f2f696d672e626164676573697a652e696f2f68747470733a2f2f756e706b672e636f6d2f736c6174652f646973742f736c6174652e6d696e2e6a733f636f6d7072657373696f6e3d677a6970266c6162656c3d73697a65" data-canonical-src="http://img.badgesize.io/https://unpkg.com/slate/dist/slate.min.js?compression=gzip&amp;label=size" style="max-width:100%;">
  </a>
  <a href="https://slate-slack.herokuapp.com" rel="nofollow">
    <img src="https://camo.githubusercontent.com/27c7f6d9d83da7d417163a6ef87827dfcd792b4a/68747470733a2f2f736c6174652d736c61636b2e6865726f6b756170702e636f6d2f62616467652e737667" data-canonical-src="https://slate-slack.herokuapp.com/badge.svg" style="max-width:100%;">
  </a>
  <a href="/ianstormtaylor/slate/blob/master/packages/slate/package.json">
    <img src="https://camo.githubusercontent.com/704a8d560849845ed1212cdebff23da2a7992190/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f736c6174652e7376673f6d61784167653d33363030266c6162656c3d76657273696f6e26636f6c6f72423d303037656336" data-canonical-src="https://img.shields.io/npm/v/slate.svg?maxAge=3600&amp;label=version&amp;colorB=007ec6" style="max-width:100%;">
  </a>
</p>

#### What's the expected behavior?

It should paste everything including the image.

You can reproduce at https://www.slatejs.org/#/paste-html or play with it at https://codesandbox.io/s/j4k03k1579.

**Comment by dmitrizzle** [comment]
For working with images you will need https://github.com/ianstormtaylor/slate-plugins/tree/master/packages/slate-drop-or-paste-images

**Comment by gnestor** [comment]
The project I'm working on uses that plugin and pasting HTML that contains images still doesn't work. I've created a Code Sandbox to reproduce: https://codesandbox.io/s/j4k03k1579?fontsize=14

**Comment by CameronAckermanSEL** [comment]
Hey @gnestor, thanks for the report. 

I think the disjoint here may be that the image support is modeled in a different example. The rich text example is the most featured, but it's not meant to be a "complete" "all-in-one" example (as far as I understand).

The behavior you are looking for is supported in the image example: https://github.com/ianstormtaylor/slate/blob/master/examples/images/index.js

Is this sufficient for your needs?

**Comment by gnestor** [comment]
Hey @CameronAckermanSEL. 

The rich text example doesn't work either (because it doesn't have a _paste HTML_ plugin). 

The images example works when copying an image (not HTML, just right-click on an image) and pasting. I'm specifically referring to copying HTML (copying text and images on a webpage, e.g. the example in the description of this issue), and the paste HTML example pastes everything but images. If you inspect the result, it looks like:

```html
<div data-key="2086" style="position: relative;">
    <span data-key="2085">
        <span data-slate-leaf="true" data-offset-key="2085:0">
            <span data-slate-content="true"></span>
        </span>
    </span>
</div>
```

**Comment by CameronAckermanSEL** [comment]
Sorry misread the issue. The paste html example should support pasting, so this might be related to it receiving a html element structure that its not equipped to deal with for some reason. I can take a look in a bit

**Comment by CameronAckermanSEL** [comment]
@gnestor I'm pretty sure whats happening is that the `html-deserializer` will make these anchors inline nodes, and then the image nodes are then deserialized into blocks

This then causes the normalizer to toss the image blocks because you cant have blocks as children of inlines.

To fix this, we would need to have this model start treating the images as inlines, which is probably fine, but then there'd need to be some context of where in the html tree this image is being pasted from relative to the "root". Alternatively, you could look for an `a` tagged element, then check its descendant for an `img` tag, and then insert this as an image block, if that's how your image blocks are rendered.

I don't believe we need this paste html example to be this sophisticated. It's not meant to be fully featured and bullet proof for pasting, and the amount of use cases in the wild for pasting become unwieldy over time. A lot of these sorts of problems are going to wind up being domain specific in userland.

What are your thoughts?

**Comment by wmertens** [comment]
That sounds like the best solution, then you can just put images in links as well. The CSS can just show images as block elements.

**Comment by CameronAckermanSEL** [comment]
@gnestor is this a satisfactory resolution for this issue?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
