### ISSUE TITLE
Text nodes can't be adjacent to other text nodes

### ISSUE THREAD

**Issue by nego25** [ianstormtaylor/slate#2649]
Hello! I need a help.
In my project, the document can have  adjacent two and more text nodes. If they will be automated merged, then will be broken structure of document.  This is not good for me. I have try to convert my text node to inline object. After that in the document automatic  adds new text nodes. So structure of my documents is changed.  This is not good again ((. 
How I can resolve this problem? I can't resolve this via plugin, because core plugin with self rules started before my plugin. If I will try to delete empty text node in my plugin then will be loop with core plugin.
Can I switch off some rule in core plugin or may be have some way to resolve my problem?

**Comment by CameronAckermanSEL** [comment]
Hi,

Text nodes can be adjacent to other text nodes, so long as they have a different set of mark decorations.

Normally it's considered sort of an implementation detail for how the text nodes are modeled relative to one another. I suspect this detail is not actually your problem.

What is it that you're expecting or trying to achieve? Why is it important for you to have adjacent text nodes? What are you expecting this to mean?

**Comment by ianstormtaylor** [comment]
Please ask questions in the Slack channel.

**Comment by nego25** [comment]
> What is it that you're expecting or trying to achieve? Why is it important for you to have adjacent text nodes? What are you expecting this to mean?

Cameron Ackerman,  thank you  for response!
I need to have adjacent text nodes, because in our system, this nodes can have some system links by it's key (uid). So if text nodes will be merged to one text node, then we losing this links.
