### ISSUE TITLE
Invalid condition in get-event-transfer.js

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#2650]
While refactoring our slate fork to use Typescript, tslint warned us about the use of bitwise operators in [`slate-react/src/utils/get-event-transfer.js`](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/get-event-transfer.js):

I'm opening this issue because from my understanding this condition is always false:

```js
if (!fragment && html && ~html.indexOf(' data-slate-fragment="')) {
```

You can test it:

```js
> ~('hello'.indexOf('h'))
-1
> ~('hello'.indexOf('5'))
0
> ~('hello'.indexOf('2'))
0
> ~('hello'.indexOf('e'))
-2
```

It probably has no effect since no one noticed before, but I thought it'd good to signal it even we are no longer using this package.

**Comment by brendancarney** [comment]
Thanks @SamyPesse! 

Here's the other side of this if anyone knows what's going on: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/clone-fragment.js#L92

This may be an attempt to support older browsers? More info starting from this PR: https://github.com/ianstormtaylor/slate/pull/1815

**Comment by CameronAckermanSEL** [comment]
I suspect we can just remove the `~` character.

The non-zero values still are considered to be `true` when used in a boolean context, so this explains why this hasn't been noticed before. And judging from the comment, it looks like it's looking for the presence of the `data-fragment` attribute. 

!!(-2)
true
!!(~('hello'.indexOf('e')))
true
!!(~('hello'.indexOf('d')))
false
```

It should be equivalent behavior to just remove the ~

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
