### ISSUE TITLE
Mentions example:  Add z-index to suggestion menus.

### ISSUE THREAD

**Issue by white112** [ianstormtaylor/slate#2651]
#### Do you want to request a _feature_ or report a _bug_?
Bug.

#### What's the current behavior?
https://www.slatejs.org/#/mentions
When I try to add mention in the first line of editor, this issue comes.

![e42c0ca32a39af6f71284dc2b99a3458](https://user-images.githubusercontent.com/22128210/54457753-860bf680-471f-11e9-9c7a-79a410ba3d93.gif)

#### What's the expected behavior?
![Screenshot 2019-03-15 12 40 58](https://user-images.githubusercontent.com/22128210/54457822-adfb5a00-471f-11e9-8939-91dddbed3391.png)
We should add z-index attribute to SuggestionList styled component.

**Comment by CameronAckermanSEL** [comment]
I can't reproduce this on Chrome or Firefox. What browser did you see this on?

**Comment by white112** [comment]
Chrome browser.

**Comment by adjourn** [comment]
Im seeing it too on [slatejs.org](https://www.slatejs.org/#/mentions) but not locally, seems to be a browser quirk (Linux, Chromium). 

I was about to write a PR but then I remembered [this](https://github.com/ianstormtaylor/slate/pull/2610). I say we wait until it gets merged and revisit the issue.

**Comment by MatthewHerbst** [comment]
This is not reproducible for me on Chrome 75 as of the current code version (`slate@0.47.4`). Is this stil an issue @white112 ?

**Comment by white112** [comment]
It seems solved now,
