### ISSUE TITLE
editor.command is not a function

### ISSUE THREAD

**Issue by karanmittal60** [ianstormtaylor/slate#2654]
I am using slate editor 
 "slate": "^0.41.2",
 "slate-html-serializer": "^0.7.7",
 "slate-plain-serializer": "^0.6.7",
 "slate-react": "^0.18.5",

i am using links and on function 
`onClickLink = (event) => {
        event.preventDefault()

        const { editor } = this
        const { value } = editor
        const hasLinks = this.hasLinks()

        if (hasLinks) {
            editor.command(unwrapLink)
        } else if (value.selection.isExpanded) {
            const href = window.prompt('Enter the URL of the link:')

            if (href == null) {
                return
            }

            editor.command(wrapLink, href)
        } else {
            const href = window.prompt('Enter the URL of the link:')

            if (href === null) {
                return
            }

            const text = window.prompt('Enter the text for the link:')

            if (text === null) {
                return
            }

            editor
                .insertText(text)
                .moveFocusBackward(text.length)
                .command(wrapLink, href)
        }
    }
`

Getting error with editor.command command is not a function
![commandError](https://user-images.githubusercontent.com/31075642/54511764-f319c900-4977-11e9-99b8-0a42518d75f3.png)

**Comment by CameronAckermanSEL** [comment]
`"slate": "^0.41.2",`

https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#0420--october-9-2018

Editor controller wasn't introduced until 0.42.
