### ISSUE TITLE
Adding a character with 2 empty lines selected doesn't behave correctly

### ISSUE THREAD

**Issue by damien-monni** [ianstormtaylor/slate#2659]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
When pressing a key after selecting two empty lines, both lines are deleted and the character is inserted at the end of previous line.

You can reproduce it on the official demos: [https://www.slatejs.org/#/rich-text](https://www.slatejs.org/#/rich-text)

![slate issue gif](https://i.ibb.co/z7gTP03/issue-slate.gif)

#### What's the expected behavior?
The new character should be placed at the beginning of the first selected line and only the second selected line should be deleted, not both.

**Comment by rikkit** [comment]
The direction you drag seems to matter here. Selecting the first then the second empty line will get the behaviour you're expecting.

**Comment by damien-monni** [comment]
> The direction you drag seems to matter here. Selecting the first then the second empty line will get the behaviour you're expecting.

Yes but it should behave the same regardless of the direction.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
