### ISSUE TITLE
Schema rules question: Validation against a node's parents

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#266]
Hello again, now with a real question.

I am implementing a validation rule for lists with a classic structure, a parent `list-block` that can contains only a list of `item-block`:

```
list-block
    [
        item-block
    ]    
```

I can easily validate a `list-block` node's children to be `item-blocks`. But I am not sure **how to validate that any `item-blocks` is a descendant of a `list-block`**.

I could make a global rule that looks for orphan `item-block` across the whole document, like this:
```js
const ITEM_BLOCK_RULE = {
    // Apply rule to all blocks
    match: function matchAllBlock () ...,

    validate: function (block) {
        // If the block is not a list-block,
        // but has an orphan item-block as child,
        // invalidate.
    },

    normalize: ... // remove orphan item-blocks
}
```

But I instinctively would like to implement a rule like this:
```js
const ITEM_BLOCK_RULE = {
    match: function matchItemBlock () ...,

    // Extra <document> parameter
    validate: function (node, document) {
        // Use the document reference to check that node's parent
        // is a list-block
    },

    normalize: ... // remove the item-block if it is orphan
}
```
Do you think it would make sense to pass a reference to the document as parameter to `validate` ? This would help to implement these kind of context sensitive rules.

Thanks for the awesome work.

**Comment by Soreine** [comment]
Thinking about it now, passing the `document` as reference would prevent some cool optimizations like memoizing the `validate` functions (to only execute the validation on nodes that have changed).

**Comment by ianstormtaylor** [comment]
Ah yup, the memoization is the reason I opted not to do that. Sadly I think it's something we have to constrain since validation will be called so often that without being able to lock it down a lot for performance things will get slow.

Same goes for the `decorate` method too if I remember correctly.

So yeah, it would need to be implemented with the "all blocks" technique instead. But that'll give us better performance.

Let me know if you have any more questions!

**Comment by Soreine** [comment]
Definitely. Thanks!
I went for the "all blocks" technique. And it even made the code cleaner. Since we can split the normalization rules for a type of block into several rules (`{match, validate, normalize}`), I was able to just move that bit of logic into its own rule at the "all blocks" level. The other rules can stay at their relevant level.
