### ISSUE TITLE
Placeholder crashes on mobile when pressing backspace

### ISSUE THREAD

**Issue by lapico** [ianstormtaylor/slate#2666]
#### Do you want to request a _feature_ or report a _bug_?

Bug (I think) !

#### What's the current behavior?

- Reproducible with this example : https://www.slatejs.org/#/rich-text
- Gif :
![ezgif-4-8fa85c4f0cc9](https://user-images.githubusercontent.com/5967573/55008227-fd277180-4fe0-11e9-92ec-0085721ee630.gif)
- Tested on IOS Safari latest version

#### What's the expected behavior?

First of all, thanks for the great library, I'm using it for first time and love the API.

On mobile, the editor crashes when we write, then erase all content, then press backspace as the placeholder is displayed. Then it's impossible to write something again.

I checked here if I could see something to fix by PR but did not see anything

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react-placeholder/src/index.js

Thanks !

**Comment by pokonski** [comment]
Same issue, also holding backspace skips over some characters and throws an exception (probably why it skips them):

Chrome 73,
Android 9
SwiftKey keyboard 

Exception is: `Cannot read property 'resume' of null` from this line https://github.com/ianstormtaylor/slate/blob/89adf63e1f47afa5149d27239631f1612dfe8a28/packages/slate-react/src/plugins/android.js#L240

**Comment by gracicot** [comment]
I tested and the problem seem gone on iOS. I had other issues with the placeholder on android and I've not been able to test properly yet.

**Comment by derrxb** [comment]
I'm experiencing this as well. I'm not familiar with the internals of Slate but the error seems to be coming from here:

https://github.com/ianstormtaylor/slate/blob/cf4bf38aca4565c88dfc36efc81d5858cc992a81/packages/slate-react/src/plugins/react/commands.js#L22-L29

`block` resolves to `null` and so when you try to access `block.nodes` you get `Cannot read property 'nodes' of null` error.

I attempted to handle the case of block being null. But then that didn't work and led to an error another error here: https://github.com/ianstormtaylor/slate/blob/cf4bf38aca4565c88dfc36efc81d5858cc992a81/packages/slate-react/src/plugins/react/commands.js#L46

`reconcileDOMNode` was introduced in https://github.com/ianstormtaylor/slate/pull/2801. So perhaps @thesunny might have an idea about what's causing this.

Sorry I couldn't be of more help.

**Comment by brianathere** [comment]
I'm hitting this as well, looking for work arounds.

**Comment by ntgussoni** [comment]
This is happening to me on some android devices, on chrome.

> Same issue, also holding backspace skips over some characters and throws an exception (probably why it skips them):
> 
> Chrome 73,
> Android 9
> SwiftKey keyboard
> 
> Exception is: `Cannot read property 'resume' of null` from this line
> 
> https://github.com/ianstormtaylor/slate/blob/89adf63e1f47afa5149d27239631f1612dfe8a28/packages/slate-react/src/plugins/android.js#L240

This is happening to me on some android devices, on chrome.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
