### ISSUE TITLE
Cannot find module "../maps/decode.json"

### ISSUE THREAD

**Issue by MatthewKosloski** [ianstormtaylor/slate#267]
After searching for a framework to replace the popular Draftjs, I stumbled upon Slate.  I started reading the docs, and tried to create a basic Slate example.  I copied the basic example from [this](http://docs.slatejs.org/walkthroughs/installing-slate.html) page of the docs.  After creating a new React component in my local environment and pasting in that code, I was presented with the following error:

`Cannot find module "../maps/decode.json"`

I have no idea what this means.  I don't know if the issue is with Webpack or Slate; however, I'm leaning more towards the former.

I think the best way for you to understand what's going on is to try it yourself.  I created a temporary Github repo with my attempt to create the simple Slate example.  It's really small, just a simple React boilerplate.  

To recreate this error:

- Download or clone my [repo's directory](https://github.com/MatthewKosloski/slate) to your computer.
- Install the dependencies with `npm install` 
- Run the Express server with `npm start`
- Navigate to `localhost:3000`

I appreciate your time and look forward to a response.  Can't wait to use this awesome framework, appreciate you open sourcing it.

**Comment by ianstormtaylor** [comment]
Hey @MatthewKosloski, thanks for the report. From the error, I don't think it's an issue with the core Slate library code, since that file path doesn't exist. But it might be in one of the dependencies.

Can you try reinstalling the dependencies? And if it still doesn't work try grep'ing for that path to see where it's coming from? 

Also it could be a Webpack thing I'm not sure. 

I'm still on vacation for a bit longer so if you haven't solved it by then I can check out your example in a few days when I'm back. Good luck!

**Comment by cobbweb** [comment]
I think you need to add [json-loader](https://github.com/webpack/json-loader) into your Webpack config.

**Comment by arekkas** [comment]
Yup, like this:

```
  module: {
    loaders: [ /* ... */ {
      test: /\.json$/,
      loader: 'json'
    }]
  },
```

**Comment by MatthewKosloski** [comment]
It works!  Thanks, guys.  I can't wait to start making my editor :)

**Comment by ianstormtaylor** [comment]
Thanks for reporting back with the fix @MatthewKosloski! Glad it's solved

**Comment by oyeanuj** [comment]
I ran into this issue as well, with an additional complication of having the `initialState.json` for the editor in the `src` folder. Here is the solution that worked for me (enhancement to the one mentioned above), incase anyone else encounters it. 

```js
{
    test: /\.json$/,
    include: [
       /node_modules/,
      path.resolve(__dirname, '..')
    ],
    loader: 'json-loader'
}
```
In my case, the initial problem was being created via cheerio, so hopefully, it will completely disappear with #55 or upgrade to webpack 2.0.
