### ISSUE TITLE
Remark

### ISSUE THREAD

**Issue by comerc** [ianstormtaylor/slate#2670]
#### Do you want to request a _feature_ or report a _bug_?

Feature

## Idea

I think we probably want [this parser](https://github.com/remarkjs/remark/tree/master/packages/remark-parse), which is part of the [remark](https://remark.js.org/) library and is used in [Gatsby](https://www.gatsbyjs.org/) and others. The whole remark ecosystem (including mdx which is just amazing) is awesome.

([copy-paste](https://github.com/sstur/draft-js-utils/issues/162))

**Comment by ianstormtaylor** [comment]
@comerc I don't think this directly relates to Slate's core. Although people are free to write their own Markdown serializers for Slate if they need one.
