### ISSUE TITLE
Operation.toJSON does not save selection's value - Saving history

### ISSUE THREAD

**Issue by callingmybluff** [ianstormtaylor/slate#2672]
#### Do you want to request a _feature_ or report a _bug_?

A _bug_

#### What's the current behavior?

https://jsfiddle.net/Ismaeel/xvgoqLn2/

1. Place the cursor anywhere inside the text
1. Click on `Click To Do Nothing` (it will reset the history by using the history itself, but each operations is re sat to its value after to/from JSON: `op = Operation.fromJSON(op.toJSON())`
1. Click on the redo button, which calls the *native* `this.editor.undo`.
1. An error appears in the console: `Uncaught TypeError: Cannot read property 'merge' of undefined`

Slate 0.44.12, Chrome latest (73.0.3683.86 64bit), and Windows7

#### What's the expected behavior?

I would like to save the history in a JSON and load from a JSON too (replay what the user did step per step). I can use something like `deep-diff`, but using them would be much faster (although maybe not memory-friendly).

If you think this is a valid bug and you would accept a pull request for it, I will happily do that. Please let me know if you want me to create an example for it, too (or extend the versioning example as it only saves in memory for now).

**Comment by isubasti** [comment]
@callingmybluff there's an option to `preserveSelection`on `toJSON`

**Comment by callingmybluff** [comment]
> @callingmybluff there's an option to `preserveSelection`on `toJSON`

Did you try the example? It does nothing, or I am using it wrong? According to the documentation, it reserves JSON for the data as a whole, not to `Operation`.

https://jsfiddle.net/Ismaeel/xvgoqLn2/35/

**Comment by callingmybluff** [comment]
Possible solution would probably be by adding (as in: https://jsfiddle.net/Ismaeel/xvgoqLn2/40/) :
```
if (options.preseveSelection && op.selection)
    json.selection = op.selection.toJSON();
```

I will create a pull request for it

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
