### ISSUE TITLE
Add documentation for `setData` command

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2673]
#### Do you want to request a _feature_ or report a _bug_?

Improve documentation

#### What's the current behavior?

The `setData` method is mentioned here

https://docs.slatejs.org/guides/commands-and-queries#on-the-top-level-value

But is not in the reference. There are some other methods here as well that should be probably be transferred over like `setDecorations`

#### What's the expected behavior?

`setData` should be in the commands reference here:

https://docs.slatejs.org/slate-core/commands

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
