### ISSUE TITLE
Value.fromJSON does not cast data properly (undos and redos list)

### ISSUE THREAD

**Issue by callingmybluff** [ianstormtaylor/slate#2678]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Value.fromJSON(jsonvalue) parses the `JSON` into a `Value`, but it keeps data.undos and data.redos as a js `Array` instead of the expected `List`.

It was discovered during implementing example for #2672 

#### What's the expected behavior?

Value.JSON parses JSON array of undos and redos into a `List`.

**Comment by becwatson** [comment]
I worked around this issue in my code by doing the folowing:

`
var value_json = value.toJSON(
        {
            preserveSelection: true, 
            preserveAnnotations: true, 
            preserveData: false // WTF why doesn't this work ok?!
        });
// update the json document of the value in other ways

// put the data into the value using Data.fromJSON which seems to work fine with Value.fromJSON
value_json.data = Data.fromJSON(value.data);

var new_value = Value.fromJSON(value_json);


`

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
