### ISSUE TITLE
Uncaught TypeError: previous.getMarksAtIndex is not a function

### ISSUE THREAD

**Issue by lapico** [ianstormtaylor/slate#2679]
https://github.com/ianstormtaylor/slate/blob/bb5d6beffa393176c55392b07ccbb0de63bd2138/packages/slate/src/interfaces/element.js#L970-L977

Maybe replace `return previous` by `return previousText` ?

**Comment by jtadmor** [comment]
My apologies, looks like I broke that. Agreed that the fix should just be calling `return previousText`, seems like we also don't have any tests for that method so I'll take a look at those.
