### ISSUE TITLE
wrapInline command of type link with target _blank

### ISSUE THREAD

**Issue by ayyouboulidi** [ianstormtaylor/slate#2681]
the data object should give the opportunity to add other attributes for a node.

I was trying to add `target: "_blank"` to my link but it is not taking it into account.

```
editor.wrapInline({
          type: 'link',
          data: {
            href: this.state.linkHref,
            target: '_blank'
          },
});
```

Has someone tried to do something like that before ?

**Comment by rikkit** [comment]
The `data` object you're passing in is available in your `renderNode` method - you'll need to handle it there.

**Comment by ayyouboulidi** [comment]
Thanks 🙏  I am closing the issue.
