### ISSUE TITLE
Unable to focus and navigate caret on empty inline node.

### ISSUE THREAD

**Issue by jerkly** [ianstormtaylor/slate#2685]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?

- Unable to focus non-void inline without text.
![2019-04-12_20-29-29](https://user-images.githubusercontent.com/8193821/56055550-61c52900-5d62-11e9-9272-960d5e62a77e.gif)

- Unable to move backward with arrows through empty non-void inline.
![2019-04-12_20-37-56](https://user-images.githubusercontent.com/8193821/56055756-0fd0d300-5d63-11e9-9dc9-0b3ac2a1b630.gif)

- Unable to move backward with arrows through non-void inline which contains a void inline.
![2019-04-12_20-45-38](https://user-images.githubusercontent.com/8193821/56056193-23c90480-5d64-11e9-8ad3-d315241b79a6.gif)

#### Reproduce this:
https://codesandbox.io/s/1rw6klw0o7

#### What's the expected behavior?
Normal behaviour expected with caret movement through inline and ability to focus inline and edit it. 

#### Possible solution
First of all I started to reproduce this bug with vanilla html div contenteditable tags and without slate to exclude browser bugs. With vanilla contenteditable tags all movement works well, without any unexpected behaviour.

Debugging after I found that the main problem is located here.
https://github.com/ianstormtaylor/slate/blob/b6a59c69a42aed08e08f48ee5245b09d77ff799f/packages/slate-react/src/utils/get-selection-from-dom.js#L46-L67

For some reason additional move added when caret is located at the end of inline. Could someone explain why is this permanently need?

There are several issues, which are stuck in this code block
#1610, #1492, #2652, #2600, #2148

If you commented these lines `(get-selection-from-dom.js#L46-L67)` you can found this bug in Chromium-based browsers (Firefox works well): Caret is rendering in non-focused element, but insert symbols in focused.

Chrome
![2019-04-12_21-57-26](https://user-images.githubusercontent.com/8193821/56060039-57109100-5d6e-11e9-8a0b-c4667ef42e58.gif)

Firefox
![2019-04-12_22-14-56](https://user-images.githubusercontent.com/8193821/56060834-9cce5900-5d70-11e9-87c1-eabdbd3ba869.gif)

The crucial part is that native dom selection api produces identical parameters (anchor, offset...) in both browsers, but the caret rendering is different.

I suppose that Chromium-based browser has a bug with caret rendering position, because Firefox caret rendering for me looks more natural.

Looking back to the code `(get-selection-from-dom.js#L46-L67)`. For me it seems that this code is trying to fix caret position rendering, which is directly not the slate bug.

I think we need to discuss about bypassing this problem with different solution, not hardcoded in slate code.

**Comment by jerkly** [comment]
In additional to this I found, that the caret rendering is depending on `display` css property and behaviour is variating. 

But in one case behaviour is identical in all browsers.

```
(get-selection-from-dom.js#L46-L67) - assuming that this code is commented / deleted

.inline-node {
    display: -webkit-inline-flex;
    display: -ms-inline-flexbox;
    display: inline-flex;
}
```

![2019-04-12_22-43-01](https://user-images.githubusercontent.com/8193821/56062652-d05fb200-5d75-11e9-9ba5-eaae3423b3d5.gif)

**Comment by jerkly** [comment]
I've just reported bug to Chrome about this behaviour. The main point: it's impossible to reach anchorOffset and focusOffset equals to 0 at internal tag only via keyboard arrow keys in Chrome browser.
https://bugs.chromium.org/p/chromium/issues/detail?id=952628

I expect when it is fixed we will give up this code block (get-selection-from-dom.js#L46-L67)

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3148
