### ISSUE TITLE
Comparison with MobileDoc

### ISSUE THREAD

**Issue by martinklepsch** [ianstormtaylor/slate#269]
I'd love to see a comparison with [MobileDoc(-kit)](https://github.com/bustlelabs/mobiledoc-kit). 👍

**Comment by ianstormtaylor** [comment]
Sure thing! I had looked at it previously but had never written anything up since I didn't dive that deeply. But here's my take after reading through the docs and examples:

> [**Mobiledoc Kit**](https://github.com/bustlelabs/mobiledoc-kit) — I added Mobiledoc Kit to this list after creating Slate as well, so the issues with it are solely from reading their documentation. In terms of the goal of customizability, Slate and Mobiledoc Kit are similar in striving to give the developer control over the rendering and serialization methods. The issues I found with Mobiledoc Kit are: that the JSON representation of content is complex to wrap your head around, that the naming terminology chosen doesn't build on prior art to make it easier to pick up, that the event handler architecture makes assumptions about use cases which leads to complexity, that the flat document model makes certain complex experiences difficult to build, and that core library makes assumptions about the behavior of specific types of nodes in the content.

Let me know if you have any other questions!
