### ISSUE TITLE
Void blocks render markup with divs inside

### ISSUE THREAD

**Issue by DominikSerafin** [ianstormtaylor/slate#2690]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### Context

In my use case I have a void block "image"  `<img>`. That image can be either standalone block or wrapped into "paragraph" `<p>` block.

(I've read in Slate docs, that blocks can contain other blocks, so I think that's alright?)

#### What's the current behavior?

Slate renders void blocks with additional markup that has some divs in it. Which is not valid when wrapped in `<p>`. E.g.:

```
<p data-key="16">

  <div data-slate-void="true" data-key="17">
    <div data-slate-spacer="true" style="height: 0px; color: transparent; outline: none; position: absolute;">
      <span data-key="34">
        <span data-slate-leaf="true" data-offset-key="34:0">
          <span data-slate-zero-width="z" data-slate-length="0">&#65279;</span>
        </span>
      </span>
    </div>
    <div contenteditable="false">
      <img src="https://unsplash.it/500/500" title="https://unsplash.it/500/500" data-key="17">
    </div>
  </div>

</p>
```

#### What's the expected behavior?

Maybe all of the elements in void blocks should be rendered using spans instead?

---

It's not that important for me though. I just wanted to let you know guys about potential issue. Which seems that it can't be fixed with plugins or user workarounds.

**Comment by ianstormtaylor** [comment]
Sounds like a good solution to me. Frustrating that it’s not possible.

**Comment by ianstormtaylor** [comment]
This would be solved by https://github.com/ianstormtaylor/slate/issues/1884, so I'm going to close in favor of it.
