### ISSUE TITLE
Customizable wrappers for Void nodes

### ISSUE THREAD

**Issue by Reklino** [ianstormtaylor/slate#2699]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What I'm trying to do:
I'm trying to implement layout control in a way that only works if every top level element has a specific updatable dynamic style. Void nodes have wrapper elements that can't be customized, and throw a wrench in this type of concept. See below:
``` html
 <div style={{  display: 'grid', gridTemplateColumns: '50% 50%' }}>
  <div style={{ gridColumn: '1/3' }}>
    This is a 2 column item
  </div>
  <div style={{ gridColumn: '1/2' }}>
    This is a 1 column item
  </div>
  <div style={{ gridColumn: '1/3' }}>
    I want a control in the UI that allows the user to change the layout by updating that style.
  </div>
  <div data-slate-void="true">
    ...
    <div style={{ gridColumn: '1/3' }}>
    This breaks the layout if it's nested in wrappers that I can't control. It has to be on that parent container for it to work with css grid.
  </div>
  </div>
</div>
```

#### What's the current behavior?

``` html
<div data-slate-void="true" data-key="...">
    <div data-slate-spacer="true" ...>...</div>
    <div style={{ gridColumn: '1/3' }}>
          <img src="..." />
    </div>
</div>
```

#### What's the expected behavior?

Here's the behavior I would expect to see

Basically, I would expect the content of the void block/node to reflect the intended dom structure as much as possible.
``` html
<div style={{ gridColumn: '1/3' }} data-slate-void="true" data-key="...">
    <div data-slate-spacer="true" ...>...</div>
    <img src="..." />
</div>
```

#### Potential proposals?
- Allow a way to pass a custom void component.
- Change the way the rendering works in [the void component](https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate-react/src/components/void.js) to work as described above.

I am happy to explore solutions and make a PR, but I thought it'd be best to get some thoughts from people who have more history around why the void component renders the way it does before I dive too much further.

Thanks y'all 😄

**Comment by ianstormtaylor** [comment]
Hey @Reklino, thanks for the super well presented issue. I totally agree that it would be good if this was possible. This might be solveable by https://github.com/ianstormtaylor/slate/issues/1884?

**Comment by ianstormtaylor** [comment]
Closing in favor of that existing issue.
