### ISSUE TITLE
Add reserved custom commands for `enter` to override default handling

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2700]
#### Do you want to request a _feature_ or report a _bug_?

Add reserved custom command for `enter` to normalize behavior between desktop and mobile

#### What's the current behavior?

Currently there is no way to intercept `enter` behavior in Android because `enter` is usually implemented by looking at `keydown` and checking for the `enter` key then overriding it. In Android, we cannot intercept and prevent default on the `enter` key.

Note that by default Slate calls `splitBlock` (I believe) when handling an `enter`.

#### What's the expected behavior?

In Android, there is no interruptible `keydown` event that we can cancel and replace behavior with but we still want a way to do special handling of `enter`. For example, in a table or a list, we want to handle it differently.

The way we can do it is to reserve a special command like `enter`. By default, we can have hitting `enter` do a `splitBlock` like it currently does; however, if an `enter` command is available (because the developer added it), we use that instead. Something like this pseudo code.

```
if (commandExists('enter') {
  editor.enter()
} else {
  editor.splitBlock()
}
```

Note that this approach means that we can't easily build plugins with `enter` handling in it because we can only have one `enter` command. Another approach I suggested was creating a special event like `onEnter` that would go through the normal event handling chain; however, there was some push back on that and the thought that perhaps we should use commands instead.

I don't feel like this solution I have here is a better solution than creating a custom event but I agree that that approach is heavy. If anyone has any better ideas, I'd be grateful to hear them.

Either way, with an `enter` command, we can get Android working even though it may require a very big custom `enter` command with branching. This is better than having no solution to the problem.

If a solution cannot be found that is acceptable at this time, I will probably make a custom command like `enterOnAndroid` that would only be called in Android so that at last we can have the ability to make Android work until we can come to a consensus on a cross-platform method.

**Comment by ianstormtaylor** [comment]
Why not use `splitBlock` for this purpose instead?

**Comment by thesunny** [comment]
@ianstormtaylor I may be misunderstanding your comment but to clarify, this is to allow a developer to override the default splitBlock behavior when enter is pressed. The default behavior would continue to be splitBlock on Android.

One real world example:

I have a task list and my cursor is in a task that is checked. If I hit enter at the end of the checked task, our users expect a new task to be created on the next line and that the task is unchecked. SplitBlock will not uncheck the task so we have to do it ourself.

So in non-Android we’d probably intercept keyDown, preventDefault, and call splitBlock then uncheck the task. In Android, we can’t intercept the keyDown because it breaks Android. I think keyDown might not even fire in a way you can identify that it is enter but even if it did you can’t prevent default and intercept the default action because it breaks the DOM for React.

But the Android plugin knows when enter was pressed and when it’s safe to issue commands. I’m looking for a solution for letting the user handle the enter in a cross browser compatible way.

**Comment by ianstormtaylor** [comment]
@thesunny check out the `onCommand` middleware handler, it would let you do this by using the `splitBlock` command as your target. In normal execution you'd let it through, but when inside a check list item you'd uncheck afterwards as you mention.

It would be good to update our examples for this new capability since it seems like something people would need a lot, and should be the default way to do things instead of using `keydown` handlers going forward.

**Comment by thesunny** [comment]
Had no idea this existed!

The documentation doesn't tell us how to call an actual `splitBlock` inside an `onCommand` hook.

I can create an issue to update the docs if you can tell me if this fake code would work:

```js
{
  onCommand(command, editor, next) {
    const { type, args } = command

    if (type === 'splitBlock' && editor.isInTask()) {
      next() // presumable to call the actual `splitBlock`
      editor.checkTask()
    } else {
      next()
    }
  }
}
```

And if that doesn't work, (a) what would or (b) do we need to create a way to do this.

Finally, I notice the examples on that page all return `next()`. From my understanding, we don't need to return `next()` anymore right? I can create an issue for that as well if that's the case.

**Comment by ianstormtaylor** [comment]
@thesunny you’re right on both counts there! An update to the docs would be awesome. 

I added that capability in a while ago with Android in mind, but haven’t updated the examples to use it yet. But really `onKeyDown` should be fairly rare going forward, reserved for platform-specific logic or hotkeys.

**Comment by thesunny** [comment]
@ianstormtaylor This mechanism is great.

I do have two issues that I haven't figure out and perhaps you have a solution for already:

1. Using `next()` may cause more than one `onCommand` middleware to respond when you only want one. For example, let's say you had special handling for `splitBlock` in a task (resets the checked state on split) but you also had special handling for `splitBlock` at the beginning of a line (capitalizes the first word). But let's say if you were at the beginning of a task and hit enter and you want to reset the checked state but you don't want the capitalization. There doesn't seem like there is a way to handle the `task` `splitBlock` and uncheck and then not doing the capitalization since they both match and they both call `next`.

2. Once there is a middleware handler, it is difficult to access the underlying command (i.e. the original `splitBlock` command without the handlers on it). For example, let's say I had a special command to split a task such that each word in the task turned into its own task. So the code calls `splitBlock` for each word but I want to use the `splitBlock` for the underlying command, not the one with the middleware attached that will reset the task and capitalize. How would I call it?

I wonder if the solution is to use the middleware to add special handling but still define an explicit command for the `enter` to disambiguate from the actual `splitBlock` (i.e. without handlers).

Then we can add middleware to the `enter` without modifying `splitBlock` and it should solve 1 and 2 above. Also, this solution would work well with a `space` command that by default would call `insertText(" ")` and that would give us the ability to handle things like markdown headings with `# ` and convert it to a heading on mobile.

For me, the `enter` handling and the `space` handling would be enough to get a great mobile experience. There could be other punctuation like `.` and `,` that might work too, but frankly I don't see a lot of auto-conversion being done with them in the wild.

**Comment by ianstormtaylor** [comment]
Interesting points. For (1) I'm not sure there's a good solution, but that's kind of inherent to middleware/composition. For (2) I think you could use `splitBlockAtRange` for that potentially?

For other thoughts, check out https://github.com/ianstormtaylor/slate/issues/2342. It would be great if you add your thoughts there too for the future!

**Comment by thesunny** [comment]
I feel like this bridge can be crossed later and it's adding to the issues so I'm going to close for now.
