### ISSUE TITLE
consider replacing Text and Leaf with just Text

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2704]
#### Do you want to request a _feature_ or report a _bug_?

Idea.

#### What's the current behavior?

Right now we have the concept of `Text` nodes and `Leaf` objects inside of them. This works, but it also just happened to be the way things evolved. We combine adjacent text nodes into one another, and leaves get combined too if they share marks.

But this could be simplified, and it might be nice to do so. Instead of...

```js
[{
  object: 'text',
  leaves: [
    {
      object: 'leaf',
      text: 'A bit of ',
      marks: [],
    },
    {
      object: 'leaf',
      text: 'rich',
      marks: [
        {
          object: 'mark',
          type: 'bold',
          data: {},
      ],
    },
    {
      object: 'leaf',
      text: ' text.',
      marks: [],
    },
  ]
}]
```

We'd have:

```js
[{
  object: 'text',
  text: 'A bit of ',
  marks: [],
}, 
{
  object: 'text',
  text: 'rich',
  marks: [
    {
      object: 'mark',
      type: 'bold',
      data: {},
  ],
},
{
  object: 'text',
  text: ' text.',
  marks: [],
}]
```

Essentially we just promote the `leaf` objects to being `text` objects instead. It would reduce the nesting in the data model quite a bit, saving on bytes. And generally make things easier to reason about.

The only real difference becomes that text nodes can now be adjacent if they contain different marks. There probably would need to be a bit of logic updating in helpers like `getOffset` or similar. But it would be pretty straightforward I'd think.

**Comment by thesunny** [comment]
Yes, I like this.

I serialize to JSON that looks something like this already and haven't had any issues with it.

**Comment by justinweiss** [comment]
Considering text nodes get merged together already, I think this is a natural next step.

I wonder if we should consider versioning the model JSON? We would have to migrate our existing data to the new (leaf-free) format before passing it into the editor, unless the editor was backwards-compatible. A version number would let us more easily know when we would need to do the migration.
