### ISSUE TITLE
Value.activeMarks returns incorrect set of marks for overlapping marks in selection

### ISSUE THREAD

**Issue by ferdaber** [ianstormtaylor/slate#2705]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
The site's example rich text editor reproduces this behavior: https://www.slatejs.org/#/rich-text.

![image](https://media.giphy.com/media/chyZTg3JBJhnRhZQQw/giphy.gif)

In the gif above, I overlapped an underline mark and a bold mark. Selecting the text from the start of the bold mark produces correct behavior of having the bold mark button be rendered as active, but as the selection grows to also encompass the underlined text, the bold mark button is still rendered as active. This appears to be behaving as expected when there are no overlapping marks (just bold text where the selection grows larger than the bolded text range)

#### What's the expected behavior?

The `Value.activeMarks` function only returns the subset of marks where *every* character in the selection possesses that mark. In the above case, I expected the bold mark button to be deactivated when the selection grows beyond the bolded text.

I am more than happy to help fix this, if someone could point me in the direction of how `Value.activeMarks` is actually populated (seems to be a getter in `Selection.marks` but that's where I got lost).

**Comment by ferdaber** [comment]
From some debugging it looks like it's failing at `Text.getActiveMarksBetweenOffsets`, where the `forEach` loop is breaking early on the first intersection it finds: https://github.com/ianstormtaylor/slate/blob/bb5d6beffa393176c55392b07ccbb0de63bd2138/packages/slate/src/models/text.js#L314

Removing that last `return false` line makes it work as expected. I can create a PR if the maintainers agree that this is the solution.

**Comment by isubasti** [comment]
@ferdaber check the doc https://docs.slatejs.org/slate-core/value#activemarks, https://docs.slatejs.org/slate-core/value#marks. what you want is `value.marks` not `value.activeMarks`

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
