### ISSUE TITLE
Document how to handle future breaking changes

### ISSUE THREAD

**Issue by quicksnap** [ianstormtaylor/slate#2707]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Related: #1992 

Many tickets are open that are flagged as breaking changes, such as combining "Text/leaf" nodes into "text". When fundamental changes like this happen, how will users migrate existing serialized content?

Documenting this would be a great add. If it's not currently supported, it may be worth calling that out in the documentation as well.

Thoughts?

**Comment by CameronAckermanSEL** [comment]
This makes sense. 

Is this something that is not already addressed by the [changelog](https://docs.slatejs.org/general/changelog)? 

https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md

**Comment by quicksnap** [comment]
Whoops--forgot to reply: I didn't see the changelog at the time of this question, so that's good! However, it could be useful still to document how to generally handle core schema changes listed in the changelog.

I'm about to upgrade Slate and deal with the changes, so if I have anything valuable I'll try to open a documentation PR.

**Comment by ianstormtaylor** [comment]
@quicksnap I'm unsure of what we'd document there. It would be the up to the user to figure out how they want to deal with the transition, just like when migrating any other piece of data that lives in your database. You could write a shim, you could run the migration, etc.

**Comment by dmitrizzle** [comment]
Hey @quicksnap there's a doc in the repo that I use whenever I migrate to next breaking version: https://github.com/ianstormtaylor/slate/blob/master/Changelog.md - hope this helps.
