### ISSUE TITLE
Un/redoing state causes renderer to miss updates

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#271]
I am using redux-undo to undo changes to the state. However, it looks like slate is missing some of the event changes.

![gif](http://g.recordit.co/Wn3QWKlrOF.gif)

The state transforms look fine.

<img width="1869" alt="bildschirmfoto 2016-08-29 um 16 10 10" src="https://cloud.githubusercontent.com/assets/3372410/18054326/ae542088-6e03-11e6-9992-0f46aadcd2cd.png">

<img width="1868" alt="bildschirmfoto 2016-08-29 um 16 10 20" src="https://cloud.githubusercontent.com/assets/3372410/18054325/ae53cfd4-6e03-11e6-8eac-90d943f2aedf.png">

<img width="1871" alt="bildschirmfoto 2016-08-29 um 16 10 32" src="https://cloud.githubusercontent.com/assets/3372410/18054327/ae55d95a-6e03-11e6-9a22-1613aa1a1dd1.png">

I am quite confident that this has to do with a flag called `isNative` which is preventing rendering of the editor. I think that undo/redo is not modifying that value which causes the renderer to ignore the state update.

**Comment by arekkas** [comment]
I think I understand the issue better now. What's happening is that redux-undo is simply catching each state change and when re- or undoing, that the current state will be replaced with the one from the past (undo) or future (redo). However, as I'm typing stuff, slate sets `isNative=false` to save performance. But when redo uses that state, `isNative` is still false which causes the editor to ignore the update.

This is a tricky one. One option would be to remove isNative, the other would be for me to manually set isNative to false when undoing or redoing

**Comment by ianstormtaylor** [comment]
Ah yup. For now I'd recommend manually setting it to `false`. I believe I've got this fixed on the `add-operations` branch, so soon you won't have to!

**Comment by arekkas** [comment]
Awesome! :)

Gesendet mit meinem HTC

----- Reply message -----
Von: "Ian Storm Taylor" <notifications@github.com>
An: "ianstormtaylor/slate" <slate@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Author" <author@noreply.github.com>
Betreff: [ianstormtaylor/slate] Un/redoing state causes renderer to miss updates (#271)
Datum: So., Sep. 4, 2016 02:39

Ah yup. For now I'd recommend manually setting it to `false`. I believe I've got this fixed on the `add-operations` branch, so soon you won't have to!

**Comment by ianstormtaylor** [comment]
@arekkas with `0.14.0` out, can you let me know if this is still an issue?

**Comment by Soreine** [comment]
Hello @ianstormtaylor @arekkas,

Because of the current bugs with undo/redo (`0.14.14`), I have been implementing a very simple undo/redo on top of Slate, without the complexity of reverse operations. In the end, it comes down to swapping an editor `State` with an older one. And I ran into the same issue described above. Setting the `isNative` flag to `false` whenever I store a state in my history did the trick for me.

@ianstormtaylor what should have changed in `0.14.0` ?

**Comment by arekkas** [comment]
Sorry for my delayed response, I didn't have time to check yet. I will take a look tomorrow.

**Comment by arekkas** [comment]
@ianstormtaylor unfortunately no, this is still an issue. It would be great if you can reopen this issue. Is there any way I can help you with this?

**Comment by arekkas** [comment]
I tried to resolve this by setting the `isNative` flag always to false. The undo/redo works fine then, but I get the same behaviour that was reported in #402

**Comment by arekkas** [comment]
Ok, so I was able to fix this by setting the isNative flag to false when an undo/redo action is triggered. Whoever is interested how I did it, the jsfiddle is here: https://jsfiddle.net/uvg4cdfa/1/

Since I don't believe that remove the isNative flag is feasable, I will close the issue as it is possible to fix this as you can see in the jsfiddle.

**Comment by wootencl** [comment]
Apologies for dredging up an old thread, but @arekkas I would assume this isn't an issue anymore with the changes introduced in [0.23.0](https://github.com/ianstormtaylor/slate/blob/ff598bc5a18ebe05db009be4bb09e9334edfe73c/packages/slate/Changelog.md#0230--september-10-2017)? Looks like `ory` is still using your workaround so maybe a potential area of change.
