### ISSUE TITLE
Add documentation for `onCommand` middleware to trigger underlying command

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2713]
#### Do you want to request a _feature_ or report a _bug_?

Improve documentation

#### What's the current behavior?

The documentation for the `onCommand` middleware doesn't describe how to access the original command.

#### What's the expected behavior?

The documentation should describe how to access the original command. Here's a code sample:

```js
{
  onCommand(command, editor, next) {
    const { type, args } = command

    if (type === 'splitBlock' && editor.isInTask()) {
      next() // calls the actual `splitBlock`
      editor.checkTask()
    } else {
      next()
    }
  }
}
```

**Comment by saidnader** [comment]
https://www.facebook.com/sttati.hassan

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
