### ISSUE TITLE
operations' size check in SchemaPlugin's defaultNormalization decision

### ISSUE THREAD

**Issue by akovantsev** [ianstormtaylor/slate#2719]
```
      const { size } = editor.operations
      ...
      if (editor.operations.size === size) {
```
should probably be
```
      const { size } = editor.operations.size
      ...
      if (editor.operations.size === size) {
```

https://github.com/ianstormtaylor/slate/blob/62ca8703045f29f57f0636ed4c2dadbe7fed0910/packages/slate/src/plugins/schema.js#L101
https://github.com/ianstormtaylor/slate/blob/62ca8703045f29f57f0636ed4c2dadbe7fed0910/packages/slate/src/plugins/schema.js#L110

**Comment by CameronAckermanSEL** [comment]
No, this assignment is correct. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by akovantsev** [comment]
@CameronAckermanSEL you are right, still not used to it. Thanks
