### ISSUE TITLE
wrapNodeByKey does not trigger validation when used in normalizeNode plugin

### ISSUE THREAD

**Issue by Bonnevie** [ianstormtaylor/slate#2721]
#### Do you want to request a _feature_ or report a _bug_?
bug (maybe?)

#### What's the current behavior?
If you implement a custom normalizeNode function in a plugin then normalization steps that only use wrapNodeByKey send the normalizer into an infinite loop. Performing a similar operation using a sequence of replace-/insert-/removeNodeByKey works as expected.
User "brendan" on the Slack channel (I think he's @brendancarney here) had run into similar issues previously and was under the impression that wrapNode does not register as changing the value, and is thus perceived as a no-op by the normalization check (paraphrased). 

Replicated in this Sandbox:
https://codesandbox.io/embed/1ymzy53zk4
Problematically, it crashes the whole tab - I have put the crashComputer flag in place in the code to ensure that you can open the link and inspect the code. If `crashComputer === true` the normalizeNode will run as described and crash the tab.

#### What's the expected behavior?
WrapNodeByKey should be a valid normalization step by itself. 

P.S. what are the rules for the insertion of empty Text elements between inlines? Does this mean that previous/next schema rules will always retrieve a text element?

**Comment by CameronAckermanSEL** [comment]
This issue is "resolved" by changing the normalizer to run the correction command as opposed to returning a delegate that does it. 

```
console.log("wrapping");
editor.wrapNodeByKey(node.key, Inline.create("wrapper"));
return; 
```

**Comment by Bonnevie** [comment]
@ianstormtaylor does this really count as resolved? Shouldn't `wrapNodeByKey` behave on par with other normalization steps?
I also found an issue with the solution, although the issue might be more universal: if you write fast, a race condition can occur where the normalization step does not have time to take place and since the normalization step always responds with the "all clear" value of `undefined` the node doesn't get rechecked before it is modified again.

**Comment by ianstormtaylor** [comment]
I don't think it has to do with `wrapNodeByKey`. Text nodes are always placed adjacent to inline nodes, so if you wrap all text nodes in inline nodes you'll end up with an infinite loop I'd think.

**Comment by Bonnevie** [comment]
but to avoid that issue the demo has always taken steps to wrap non-empty text nodes only (via `if(node.getText().length)`), so I cannot see how that is how the loop gets triggered?
