### ISSUE TITLE
Changes not applied properly when nesting editors with contexts

### ISSUE THREAD

**Issue by philipstolpe** [ianstormtaylor/slate#2723]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

**Setup:**

I have created an editor wrapper (SlateEditor) with a context provider (EditorDataProvider) around the editor. A custom block type (NestedEditor) has been defined which contains a context consumer (EditorDataConsumer). This block also renders another instance of SlateEditor.

Another custom block type has been defined (ColoredBlock). When mounting this component, the setNodeByKey command is triggered to update the data of the node, which will trigger the rendering and turn the background blue.

So basically, the the DOM nesting looks like this:

```
Context Provider
    Editor
        Colored Block
        Context Consumer
            Context Provider
                Editor
                    Colored Block
```

**What's happening:**

1. ColoredBlock (C1) gets rendered
2. ColoredBlock (C2) in NestedEditor gets rendered
3. C1 mounts, updates data  (through setNodeByKey)
4. C2 mounts, updates data (through setNodeByKey)
5. Editor gets updated with new state
6. C1 renders (with updated data - becomes blue)
7. Nested Editor gets updates, with no state changes

I've added logs, which shows that C2 calls setNodeByKey. The NestedEditors picks up the command, but doesn't update the node data properly. I have tested with other commands as well (like setting marks) but I get the same result.

**Screenshot:**
![image](https://user-images.githubusercontent.com/9337846/56946025-54ad8580-6b29-11e9-98d9-a9f60f9b92d0.png)

**Specifications:**
MacOS: 10.14.4
Google Chrome: 73.0.3683.103
slate 0.45.1
slate-react 0.21.21
react: 16.8.4

**Sandbox reproduction:**
https://codesandbox.io/s/qvvy88xqqw

#### What's the expected behavior?

1. ColoredBlock (C1) renders
2. ColoredBlock (C2) in NestedEditor renderes
3. C1 mounts, updates data
4. C2 mounts, updates data
5. Editor gets updated with new state 
6. Nested Editor gets updated with new state
7. C1 renders (with updated data - becomes blue)
8. C2 renders (with updated data - becomes blue)

The problem is much easier to see in action (through the Sandbox link). If more information needs to be provided, let me know!

**Comment by CameronAckermanSEL** [comment]
In the browser console, I'm seeing these errors every time the nested editor is updated:
```
Uncaught TypeError: Cannot read property 'equals' of null
    at Point.moveTo (qvvy88xqqw.codesandbox.io/node_modules/slate/lib/slate.js:3169)
    at eval (qvvy88xqqw.codesandbox.io/node_modules/slate/lib/slate.js:15222)
    at Selection.updatePoints (qvvy88xqqw.codesandbox.io/node_modules/slate/lib/slate.js:15415)
    at Selection.moveTo (qvvy88xqqw.codesandbox.io/node_modules/slate/lib/slate.js:15221)
```

Is the nested editor strictly necessary? It should be avoidable because slate has hierarchical blocks.

**Comment by preciselyphilip** [comment]
@CameronAckermanSEL Where do you see those errors? To me, everything seems to look fine (no errors). What browser are you using?

**Comment by philipstolpe** [comment]
@CameronAckermanSEL Where do you see those errors? To me, everything seems to look fine (no errors). What browser are you using?

**Comment by bryanph** [comment]
I think this might have to do with https://github.com/ianstormtaylor/slate/issues/2477. It seems there is some internal logic that queues updates. If it just so happens that after you apply changes to the slate editor that something causes a rerender up the tree with an old `value` then the "new" value is discarded. This is my thesis anyway.

**Comment by olabala** [comment]
@CameronAckermanSEL I am stuck here, have you found a solution?

**Comment by CameronAckermanSEL** [comment]
To be frank with you @olabala, I believe the best solution is to not nest editors. I'm not sure what use case drives people to want to do that, but this editor can deal with hierarchical block structures, so it's mostly unnecessary to even attempt. I suspect a lot of people are used to other editors like Draft that can't deal with nested block structures (like tables) without nesting editors.

**Comment by olabala** [comment]
@CameronAckermanSEL I just found the recurring case.
The error is because I executed `editor.moveToRangeOfDocument().delete()` twice.

**Comment by CameronAckermanSEL** [comment]
That sounds like it's a separate problem and deserves a different issue.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
