### ISSUE TITLE
Issues with focus/cursor on custom block nodes

### ISSUE THREAD

**Issue by edin-purkovic** [ianstormtaylor/slate#2732]
#### What's the current behavior?

First, a big thank you for this badass editor!

I am using text inputs in my custom block nodes and can't figure how to solve this issue - here is the simplified version on codesandbox using the slates Check List example, changed only from checkbox to text inpux: https://codesandbox.io/s/yqj378j5wv

Focus behaves fine on input boxes until I change the focus to CheckListItem text, and then changing the focus back to the input box - input box loses focus as soon as I enter anything and the cursor moves back to the last position in CheckListItem text - gif:

![losing_focus](https://user-images.githubusercontent.com/12642134/57148233-74fb6f80-6dc9-11e9-8d65-476091823244.gif)

Same behavior for controlled and uncontrolled. 

Tested on Firefox 66.0.3 / Chrome 74.0.3729.131 / Slate 0.46.1

Thanks!

**Comment by unludo** [comment]
hi, did you find something on this? I have a similar issue.

**Comment by edin-purkovic** [comment]
Couldn't find time so unfortunately no, had to go with using uncontrolled inputs on custom nodes as an workaround

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
