### ISSUE TITLE
Native Range.isCollapsed is always undefined in slate-react/utils/findRange

### ISSUE THREAD

**Issue by akovantsev** [ianstormtaylor/slate#2737]
Probably a bug:

`findRange` function accepts native either Range or Selection, and, if gets Range – "coerces" it to Selection.
The issue is: it assumes both `Range` and `Selection` have `.isCollapsed`, and does not "coerce" this attribute. However, Range's attribute is called `.collapsed`, not `.isCollapsed`.

So in `findRange(range, editor)` isCollapsed is always undefined (I think). 

https://developer.mozilla.org/en-US/docs/Web/API/Range/collapsed
https://developer.mozilla.org/en-US/docs/Web/API/Selection/isCollapsed

https://github.com/ianstormtaylor/slate/blob/7855783b2d35f9334880983f4e7ee862157ce799/packages/slate-react/src/utils/find-range.js#L32-L37

https://github.com/ianstormtaylor/slate/blob/7855783b2d35f9334880983f4e7ee862157ce799/packages/slate-react/src/utils/find-range.js#L40-L46

**Comment by akovantsev** [comment]
the fix is just 1 line:
```
 native = { 
   anchorNode: native.startContainer, 
   anchorOffset: native.startOffset, 
   focusNode: native.endContainer, 
   focusOffset: native.endOffset, 
   isCollapsed: native.collapsed // <--  this one
 } 
```
However I have no clue about implications in the code depending on this, and have no experience with js infra setup to even test the change.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
