### ISSUE TITLE
ReplaceNodeByPath is not saving a snapshotSelection

### ISSUE THREAD

**Issue by FedeLochbaum** [ianstormtaylor/slate#2739]
#### Do you want to request a _feature_ or report a _bug_?
 Currently the ` replaceNodeByPath ` and  ` replaceNodeByKey ` are not using [snapshotSelection](https://docs.slatejs.org/slate-core/commands#snapshotselection).

[Current replaceNodeByPath implementation](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/commands/by-path.js#L368)

#### What's the current behavior?
If you call to `replaceNodeByPath` or ` replaceNodeByKey ` and you after press `cmd+z` the cursor pass to the block above or down if is the update block is the first.

#### What's the expected behavior?
I would like that, when i call to ` replaceNodeByPath ` the block transformation only be a replace. If i press (cmd+z) i would like that cursor pass to old position (the position that the cursor has before call to ` replaceNodeByPath `)

**Comment by ianstormtaylor** [comment]
Hey @FedeLochbaum, those commands don't have anything to do with the current selection, so they shouldn't be snapshotting it or reverting it on undo. Feel free to ask in our Slack to narrow down the issue, and maybe there's some other root cause.
