### ISSUE TITLE
setValue in controllers/editor.js causes race conditions

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2742]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
`setValue` is called in two places in the controller:
1. Reacting to a prop change (https://github.com/ianstormtaylor/slate/blob/5b8a6bb3b49faef7d955632506a69dce1ebd597a/packages/slate/src/controllers/editor.js#L378)
2. Reacting to an internal state change (https://github.com/ianstormtaylor/slate/blob/5b8a6bb3b49faef7d955632506a69dce1ebd597a/packages/slate/src/controllers/editor.js#L98)

Because of the asynchronous nature of the two, it is possible that a rerender occurs whilst slate is applying operations locally. This has as a result that `onChange` wll be called with an inconsistent value.

#### What's the expected behavior?
`value` should be set either internally or through props only so that updates can correctly be queued in some way and race conditions do not occur.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
