### ISSUE TITLE
Remove mark is not working like part of a transaction

### ISSUE THREAD

**Issue by FedeLochbaum** [ianstormtaylor/slate#2744]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
If a call to `removeMarkByPath`/`removeMark`/`removeMarkAtRange`, i call to any action like `deleteCharBackward` and a press `cmd+z` the undo functionality first is reverting the `deleteCharBackward` and if a press again `cmd+z` the removeMark is reverted.

#### What's the expected behavior?
Should can revert both changes at the same moment, if those changes are managed as a group, pressing only one time cmd+z should revert the  `deleteCharBackward ` and the `removeMark` 
Here a screenshot of history when i do:
```
removeMark(...)
deleteCharBackward()
```
<img width="732" alt="Screen Shot 2019-05-07 at 1 13 40 PM" src="https://user-images.githubusercontent.com/16744248/57328649-5f978580-70e8-11e9-9bea-e57f11527e18.png">
The image show more changes because is an example more complex ( but is doing the same)

BUT if i do:
```
deleteCharBackward()
removeMark(...)
```
The history is:
<img width="698" alt="Screen Shot 2019-05-07 at 1 16 15 PM" src="https://user-images.githubusercontent.com/16744248/57328712-848bf880-70e8-11e9-8f27-6fd19693a180.png">
Clearly there something that is working bad. I think that the history is not managing the removeMark as a change within a transaction/group

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
