### ISSUE TITLE
'Select All' + 'Delete' results to Error in rich text example

### ISSUE THREAD

**Issue by rkboyz124** [ianstormtaylor/slate#2750]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
In rich text example, selecting all the text inside the editor and then deleting it results in an error.

![Screenshot from 2019-05-09 19-34-32](https://user-images.githubusercontent.com/12042986/57450668-b1c7da80-7291-11e9-966d-d21cf79570de.png)

#### What's the expected behavior?
Should work properly without any errors.

**Comment by calspre** [comment]
Just started using this library and encountered the very same issue. 🤔

**Comment by rg4real** [comment]
Very sad. :( 

Something wrong with a placeholder.

**Comment by rg4real** [comment]
https://www.slatejs.org/#/placeholders

**Comment by Jarred-Sumner** [comment]
I think it's the recent change where `mark.type` is now `.type` for decorations

Might be worth making it backwards compatible for now and adding a warning

**Comment by ianstormtaylor** [comment]
Sorry about that folks, just released a fix to the `slate-react-placeholder` to prevent this. And I've added a backwards compatible deprecation warning as @Jarred-Sumner suggested as well, so it will work with the old format but log a warning.

**Comment by rg4real** [comment]
@ianstormtaylor , awesome! Thank you very much for such a quick reaction.

Any change that [this issue](https://github.com/ianstormtaylor/slate/issues/2755) is related to this problem?..
