### ISSUE TITLE
Plugin setting a selection to editor.value.selection to cancel selection change cause slate to not update the DOM correctly

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#2752]
#### Do you want to request a _feature_ or report a _bug_?
A bug.

#### What's the current behavior?

The browser selection is not the same as the selection reported by slate when caneling a selection change with a plugin.

Let me explain. I have a plugin that whenever the use click on the selected text in slate, I catch the `select` command and select the previous selection, so the selection don't change.

When I do this, slate thinks the selection hasn't changed and won't update the DOM. But in reality, it has changed to the same selection before any event. The DOM has a collapsed selection due to the click, while slate thinks the selection hasn't changed at all.

Here a capture:

![Capture](http://g.recordit.co/dhGcFHTTI5.gif)

To see the issue reproduced, 

 1. go to this online example: [https://codesandbox.io/embed/v0wrvy7mll](https://codesandbox.io/embed/v0wrvy7mll)
 2. Select a part of the text
 3. Click inside the selection
 4. Notice the plugin displaying "selection cancel"
 5. Type a letter, notice the text previously selected disappearing.

This bug does not occur if a send a different selection to the command. For example, `editor.value.selection.moveFocusForward()`

#### What's the expected behavior?

The expected behaviour of my plugin would be for the user to click on the selection and see the selection stay.

Also, I would expect slate to update the DOM correctly when changing the selection to the same it was before.

**Comment by gracicot** [comment]
The live example on codesandbox will work if we reverse the anchor and focus: https://codesandbox.io/embed/n7owo2j6vj

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
