### ISSUE TITLE
Mark nesting causes the outer mark to be broken as unexpected

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2753]
#### Do you want to request a _feature_ or report a _bug_?

***bug***

#### What's the current behavior?

Consider the following code snipet:
```
<p>Hello world <i>java <strong>or</strong> javascript</i></p>
```
Tag `strong`  is the symbol of mark `bold`;  tag `i` is the symbol of mark 'italic'.
However, the latest Slate can't really reproduce the scene.
Using Slate can ***only*** output the following code snipet:
```
<p>Hello world <i>java <i/><i><strong>or</strong></i><i> javascript</i></p>
```

#### What's the expected behavior?
```
<p>Hello world <i>java <strong>or</strong> javascript</i></p>
```

**Comment by tkirda** [comment]
This is by design. Read about it here: 

https://docs.slatejs.org/guides/data-model#marks

**Comment by ianstormtaylor** [comment]
Hey @CodePlayer this used to be possible with `slate-hyperscript`, but with the recent changes to text nodes, I removed that possibility because it was incongruous with how Slate actually renders the elements, and it made making guarantees about what gets returns from a mark tag harder.

**Comment by CodePlayer** [comment]
I was attracted by Slate's powerful and flexible customization, but now I feel that it is a weird partial student...
