### ISSUE TITLE
Error while mounting with focus from Value.fromJSON

### ISSUE THREAD

**Issue by rg4real** [ianstormtaylor/slate#2755]
Use case: I need to set focus from Value.fromJSON function.

Link to replicate an issue:
https://codesandbox.io/embed/o58z9o0kyz?fontsize=14

**Comment by rg4real** [comment]
@ianstormtaylor, can you estimate how hard / easy it is to fix? It's really blocking my project so I am interested in but I have little understanding of the library.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
