### ISSUE TITLE
Editor component's placeholder prop is broken

### ISSUE THREAD

**Issue by franjohn21** [ianstormtaylor/slate#2760]
#### Do you want to request a _feature_ or report a _bug_?
🐛 

#### What's the current behavior?
When the `Editor` component from `slate-react` has the `placeholder` prop specified, the expected behavior is that the placeholder text will be rendered when there is no text entered. The current behavior is that the placeholder text is not being rendered in the latest slate-react.

This bug is verifiable in Slate's own examples, e.g. https://www.slatejs.org/#/rich-text where [the source code](https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js#L102) specifies a `placeholder` prop, the empty state for the editor does not render the placeholder.

![Screen Shot 2019-05-10 at 2 18 44 PM](https://user-images.githubusercontent.com/7452924/57557833-5ef13000-7330-11e9-8e86-87c284b0d986.png)

#### What's the expected behavior?
The expected behavior is that the placeholder text is visible in the empty state. I am completely new to slate though so it's possible I'm misunderstanding what this is supposed to do.

**Comment by franjohn21** [comment]
👋 @ianstormtaylor think we could get some eyes on https://github.com/ianstormtaylor/slate/pull/2765 when you gets a chance? IMO the `placeholder` is fairly critical to maintain feature parity with native text inputs

**Comment by ianstormtaylor** [comment]
Thanks @franjohn21, I totally missed that one!
