### ISSUE TITLE
Error on selecting text from the end of block

### ISSUE THREAD

**Issue by MunifTanjim** [ianstormtaylor/slate#2763]
#### What's the current behavior?

**Steps to reproduce**:

- Go to: https://www.slatejs.org/#/rich-text
- Open browser's devtools
- Put the cursor after `like this:` on the second block.
- Hold <kbd>Shift</kbd> and tap <kbd>Left Arrow</kbd> a couple times.
- You should see the error in the console:

```
element.js:2583 Uncaught Error: `Node.assertNode` could not find node with path or key: List [ a { "key": "1985", "marks": Set { a { "data": Map {}, "type": "bold" } }, "text": "bold" }, List [ 1, 1 ] ]
```

This affects the latest versions:
- slate-react@0.22.2
- slate@0.47.2
- Browser: Chrome@latest

**Comment by adjourn** [comment]
Duplicate of #2761?

**Comment by MunifTanjim** [comment]
Seems like it... :thinking:
