### ISSUE TITLE
Search Highlight example is broken

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#2767]
Annotations seem to mess up the document structure.
https://www.slatejs.org/#/search-highlighting
![search-highlight-broken](https://user-images.githubusercontent.com/8127927/57582208-3e58df80-74c2-11e9-9381-788a1ea4e10d.gif)

**Comment by adjourn** [comment]
I submitted a PR earlier today #2766. [Test it out](https://deploy-preview-2766--slatejs.netlify.com/#/search-highlighting).

**Comment by dselman** [comment]
I'd love to see this in a release - it's blocking for me.
