### ISSUE TITLE
remove props.state from node components

### ISSUE THREAD

**Issue by cobbweb** [ianstormtaylor/slate#277]
That `state` prop passed into a Block instance is often stale or behind the real state, and `props.editor.getState()` is the preferred method for transforming state from within a block. Having  `state` as its own prop seems overkill and a trap for the unsuspecting, I think the best way to fix this is just remove the prop!

Is there a use case for having `state` as it's own prop?

**Steps to reproduce:**
1. Go to http://slatejs.org/#/embeds
2. Add a new paragraph at the very end, type ‘Testing’ into it
3. Click into the YouTube node <input>, type ‘c’
4. ‘Testing’ paragraph is gone

<div align="center"><img src="http://g.recordit.co/zsVn6Ige8Z.gif"></div>

**Comment by ianstormtaylor** [comment]
@cobbweb I'm down for this change. Can you write up a PR with it?
