### ISSUE TITLE
Spellcheck not working correctly on Windows/Chrome latest

### ISSUE THREAD

**Issue by jmoyers** [ianstormtaylor/slate#2775]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Windows 10
Chrome Version 74.0.3729.131 (Official Build) (64-bit)
Current Behavior (on https://www.slatejs.org/#/rich-text):
[Recorded Gif](http://recordit.co/os0WSULnos)

If you replace a misspelled word, the cursor location doesn't update properly, your arrow keys no longer function with the portion of the word that was inserted. If its a long line, you can no longer use arrow keys to go all the way to the end of the line. I also noticed that if the word that is replaced is the same length, there is some very odd behavior when you try to delete the word or manipulate it with cut and paste.

#### What's the expected behavior?

Cursor state should update to the end of the word, you should be able to use arrow keys to navigate normally.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
