### ISSUE TITLE
[Android] Command middleware don't get called on android

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#2776]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

Not a lot of middleware function get called properly. For example, the `insertText` and 
`select` commands almost never gets called on a android keyboard. The `deleteAtRange` get called sometimes but not always depending on the keyboard.

[Here a demo that log commands](https://codesandbox.io/embed/0mmpl18jww)

On android, almost all commands are not logged. Any editor that rely on command middleware will not work properly.

Android: 9
Keyboard: Google keyboard, Samsung keyboard.

[Capture](https://imgur.com/a/kxw4Fdq)

#### What's the expected behavior?

The expected behavior is commands would be called on soft keyboard just like on desktop.

In the demo linked above, the insertText, delete and select command would be called properly in the middleware.

**Comment by thesunny** [comment]
@gracicot I'm working on Android but it may take a while before the middleware is working. Right now the focus is just getting it to work and be stable which it isn't yet.

**Comment by gracicot** [comment]
@thesunny good, thank you, and thanks for your hard work on this. I suspected it was the case. I just wanted to make sure this item is tracked and not forgotten.

**Comment by gracicot** [comment]
@thesunny We tried the Slate version with the new Android support made with Mutation Observer. From what I see, the plugin middlewares are now called correctly. If you don't see this bug anymore on your side too, I would be willing to close the issue.
