### ISSUE TITLE
Master appears to be broken

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2777]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

I start the dev server with the latest on `master` using `yarn start` and I get the following error message on Chrome on OSX. Fails to load also on Safari. I assume the rest have the same error.

![image](https://user-images.githubusercontent.com/469587/57738858-186c4000-7666-11e9-895f-f1dcf1053752.png)

#### What's the expected behavior?

We shouldn't see an error.

**Comment by thesunny** [comment]
Must remember to install packages when upgrading!

**Comment by steida** [comment]
This should be some yarn command I guess:

```
"deps": "rimraf 'yarn.lock' 'node_modules' '**/node_modules' && yarn"
```
