### ISSUE TITLE
Enter is broken in master before a decoration introduced by "remove leaves (#2715)"

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2778]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Bug can be observed on examples here: https://www.slatejs.org/#/rich-text

Just hit `enter` immediately before the bold word `rich`.

![image](https://user-images.githubusercontent.com/469587/57739493-a34e3a00-7668-11e9-9f21-c29879104c4b.png)

The cursor remains where it is instead of going to the next line.

Happens on Chrome and Safari on OSX. Doesn't happen on Firefox on OSX.

#### What's the expected behavior?

The cursor should move to the next line after hitting `enter`.

**Comment by thesunny** [comment]
Checked and the last good publish commit where this was working was this one: 
https://github.com/ianstormtaylor/slate/commit/a431576e732f1240a27159cecca9bd61a9f0e5f3

Appears to have broken in `remove leaves` PR: https://github.com/ianstormtaylor/slate/pull/2715

**Comment by thesunny** [comment]
@ianstormtaylor FYI, this also presents at the end of a decoration (e.g. bold). If you hit enter, it will split the block but the cursor will not move into the next line in both cases.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
