### ISSUE TITLE
Slate-Schema-Violations doesn't seem to include CHILD_MIN_INVALID & CHILD_MAX_INVALID

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2784]
The latest version I see is 0.1.39 and last published 9 months ago. The page for the package on NPM links to the Slate repo, but I don't see it anywhere in the repo anymore. I'm a bit confused. Is this still maintained? https://www.npmjs.com/package/slate-schema-violations

**Comment by benjiro** [comment]
That package was deprecated a while back to reduce file size, and complexity of the project. The commit that it was removed can be found here https://github.com/ianstormtaylor/slate/commit/36ed4397d880bf75126e9f8f890e999fc69c3b9a#diff-9b8fab691c00b9e5380b19ce882f3271.

You can read up about schema errors in the doco https://docs.slatejs.org/slate-core/schema#errors

An example
https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate/test/schema/custom/child-min-invalid-at-end-custom.js

**Comment by Slapbox** [comment]
Thanks so much @benjiro, that helps a ton!
