### ISSUE TITLE
Support webpack tree-shaking

### ISSUE THREAD

**Issue by klis87** [ianstormtaylor/slate#2787]
#### Do you want to request a _feature_ or report a _bug_?
Optimization

#### What's the current behavior?
Currently slate is not tree-shaking friendly, at least not with Webpack

#### What's the expected behavior?
Slate should be tree-shaking friendly, especially it is so big library.

There are several things to consider to make it work:
- `sideEffects: false` should be added to all package.jsons, unless there are side effects, then it should get array of modules with side effects
- why even bothering with using rollup for providing es build? In my opinion it does not give any advantage, because bundling is done on app level anyway. Prebundling though doesn't allow webpack to make its optimizations, especially tree-shaking. Bundling with rollup/webpack is great for UMD though

Why do I need that? Because I code-split my app, and I wanna display WYSIWIG only in certain cases. However, I need access to { Value } to deserialize json from db to display generated documents, and right now whole slate is bundled just to get this one object. I cannot even pick this object from `slate/models/value`, because simply slate is prebundled by rollup.

Problem is related to blog post https://www.danielberndt.net/blog/2018/you-might-not-need-rollup-for-libraries/

Also, one of libraries optimized for webpack tree-shaking is `material-ui`, giving just for reference.

**Comment by dmitrizzle** [comment]
In the mean time, if you are looking for a smaller package to just display data, consider approach taken here: https://github.com/roast-cms/french-press-editor/blob/develop/src/components/vignettes/Reader.js - it's a single component file that consumes serialization rules and prints HTML in React. Note that I haven't updated this library to handle the new data structure introduced in recent Slate release (the one that removes leaves from text).

**Comment by ianstormtaylor** [comment]
Hey, this is a good thing to fix. But I think we can fix it by https://github.com/ianstormtaylor/slate/issues/2495 instead of any restructuring now. But already I’d assume that `Slate` and `slate-react` are separate bundles.

**Comment by klis87** [comment]
@dmitrizzle thx, I will try it perhaps but I have one idea first I need to investigate mitigating tree-shaking issue

@ianstormtaylor 
1) I am not sure how 2495 is related? the only thing I can see is that immutable wont be needed anymore which takes quite a few a kbs
2) Indeed I managed to use `slate-react` inside dedicated bundle only needed for WIZARD rendering, I am addressing `slate` in this issue, as I need ONLY `Value` in bigger part of the app, while I need to have whole slate because of that
3) what do you mean by any restructuring? `slate` is structured already fine now, it has `index.js` with reexports, which is just what webpack needs, the only 2 things need to be done are:
a) adding `sideEffects: false` to `package.json`
b) giving up rollup for es build - babel is totally enough
I tested this locally and it did work

The biggest question of all is, is `slate` safe to apply `sideEffects: false`?

**Comment by ianstormtaylor** [comment]
@klis87 Immutable.js would no longer be used, and the functions that are all methods right now would be exported as individual functions instead, so you'd theoretically be able to have it tree shake down to just a few functions.

When you say right now that, "you only need `Value`". I assume what you mean is that you only need the models code? (Eg. not the editor controller code which includes commands, operations, ...?) Because the way things are structured right now `Value` itself depends on pretty much all of the other code in `src/models`.

I have no idea about `sideEffects: false`, I haven't read up on Webpack-specific stuff much too be honest, if someone wants to research and do a detailed pull request I'd be happy to help get it merged in!

I also don't know if the ES build is being used by people right now in cases where they want ES outputs. (Eg. does Parcel use this?) Someone would need to do research to see how to either preserve it, or eliminate it without affecting that.

**Comment by klis87** [comment]
@ianstormtaylor I just need `Value` to be able to transform json into slate object, which then is deserialized by html serializer. I don't remember exactly but I believe that splitting Value from the rest actually saved big amounts of kbs. Once I have some time, I will do this test once again to give exact values.

`sideEffects` just tells Webpack, that importing a package won't cause any side effect, or to rephrase it, there is no initialization logic, especially with some private module variables. Or to put it in another way, importing a package should be idempotent, no matter how many times you import it, it won't break stuff. For example:
```js
const x = 0;

const init = () => {
  x++;
};

init();

export const helper = () => console.log('helper');
```

Above module has side effects, because importing it increases `x` every time. So this knowledge is enough to anwer this question. If Slate just exports functions and doesnt call anything by itself, then it should be safe.

Webpack need this information, as it is not safe to tree-shake modules with sideEffects, so it does require this flag to mark a package as safe to do it.

Regarding es build, I guarantee you, most webpackers use it by default, because of this https://github.com/ianstormtaylor/slate/blob/master/packages/slate/package.json#L8 , which tells Webpack that this is es bundle and it will prefer this by default to make its optimizations. However, because for `Slate` `Rollup` is used, unfortunately this doesnt work due to how Rollup bundles. Webpack tree-shaking is based on unused reexports.

So, the question is, what are reasons to bundle library by Rollup. Of course it is nice to provide UMD target, so that people could use it directly within browser without things like Webpack or Browserify. But I cannot see even single benefit of bundling for es target, only disadvantages:
- if no advantages, why to even do it, just takes time and build process is more complicated
- hurts tree-shaking, at least for Webpack
- people cannot just pick specific module if they want, like `import Value from 'slate/modals/value'`

Maybe there are some advantages, I would love to see other people opinion cause I might miss some pros.

**Comment by ianstormtaylor** [comment]
FWIW, that other issue I linked to about JSON would save you the need to do any of this because you wouldn’t have to deserialize the value in the first place.

I don’t think all of Slate’s packages are without side effects.

**Comment by klis87** [comment]
Good news regarding serialization. 

However, I still thing it is worth considering giving up rollup for es/cjs build. Correct me if I wrong, but as stated above, I cannot see any advantage.

Regarding sideeffects, it is still possible to provide array of files with sideeffects instead of false.

In my free time I will try to hunt down those files, @ianstormtaylor do we have any branch which assembles stuff which will go to the next version? if not, I could do it then, as I guess that removing immutableJS is a complete slate rewrite
