### ISSUE TITLE
{action}MarkByKey/Path does nothing if length is 0.

### ISSUE THREAD

**Issue by nz-chris** [ianstormtaylor/slate#2805]
{action} being one of `add`, `remove`, `set`.

https://jsfiddle.net/chris_wte/gbkrcveo/58/

You can place your caret inside a bold word (make sure the selection is collapsed)

Pressing the button labelled `this.editor.removeMark('bold')` does nothing, but I think this bug is already known...

However pressing the button labelled `this.editor.removeMarkByKey(..., 'bold')` also does nothing. I don't see why this is.

Similarly, pressing the button labelled `this.editor.addMarkByKey(..., 'italic')` does nothing. If the regular functions such as `editor.addMark` are meant to work without a selection, then these functions should too!

**Comment by nz-chris** [comment]
I'm fairly sure that on slate 0.45, this was not an issue.

**Comment by nz-chris** [comment]
Still an issue in Slate v0.47.6.

**Comment by nz-chris** [comment]
@ianstormtaylor Am I correct in thinking this is an issue?

**Comment by ianstormtaylor** [comment]
Not sure, I don’t necessarily think it is. There’s a question of what’s more useful. Either operating on the whole node or being able to operate on a slice. But I could see your argument for making `ByRange` take over in this respect. 

But I’m looking to deprecate these key-based methods in the next breaking version either way.

**Comment by nz-chris** [comment]
> But I’m looking to deprecate these key-based methods in the next breaking version either way.

The similar {action}MarkByPath functions also don't work with length: 0, but I now see that this is perhaps not a bug. {action}MarkAtRange can be used instead, and it makes more sense.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
