### ISSUE TITLE
moveNodeByKey adds undefined node on move

### ISSUE THREAD

**Issue by Jam42** [ianstormtaylor/slate#2806]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When you `moveNodeByKey` first node undefined node is added to nodes array

[Example link](https://codesandbox.io/s/slate-movenodebykey-first-element-undefined-3f4qo)

![slate-undefined](https://user-images.githubusercontent.com/14905381/58079969-0f362280-7bd4-11e9-8d37-29bba8b33db6.gif)

#### What's the expected behavior?

There shouldn't be undefined node :)

**Comment by galfaroth** [comment]
Bump!

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
