### ISSUE TITLE
Editor without white-space pre-wrap

### ISSUE THREAD

**Issue by steida** [ianstormtaylor/slate#2828]
Maybe I overlooked something but is it theoretically possible to use Slate without white-space pre-wrap?

**Comment by ianstormtaylor** [comment]
Not sure, would require someone doing research to see if it works as far as browser editing goes.

**Comment by isubasti** [comment]
Theoretically it is possible indeed. I used to do it to support justified alignment but it has some unintended behaviours on some browsers((have had to remove support due to this). Not sure about now as I haven't tried it again
