### ISSUE TITLE
Html-serializer: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by coltontravers** [ianstormtaylor/slate#2829]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

When trying to serialize a Slate value, it gives me a "Cannot read property 'reduce' of undefined" error. 

The error happens here: 
![image](https://user-images.githubusercontent.com/6713494/58280365-6839be00-7d6e-11e9-902b-16491fb2a89b.png)

**Comment by brendancarney** [comment]
Could you provide a CodeSandbox or JSFiddle demonstrating the issue?

**Comment by coltontravers** [comment]
@brendancarney Well, I created a codesandbox here (https://codesandbox.io/s/stupefied-lake-855zy), but it works in that. I have my repo up here that has the error: https://github.com/coltontravers/Slyde

**Comment by davidgolden** [comment]
I was seeing this same error and upgrading to the latest versions of slate and slate-react along with updating some code to match those versions seems to have resolved it.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
