### ISSUE TITLE
core onDrop handlers is missing type node

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#283]
I have been messing with `onDrop` today. I must say, implementing it was actually really straight forward. So thank you!

One immediate problem I ran into was that some items I dropped had a type of `node`. The core `onDrop` handler doesn't have a way to deal with this type so I was forced to handle it myself. I feel like my solution is fairly generic enough so I thought I'd get your feedback. I am also more than willing to open a pull request, although you may have a way you want to implement this.

``` js
function onDrop(e, data, state) {
  if (data.type !== "node") return;

  let {target,isInternal,node} = data;
  let {selection} = state;

  if (isInternal) {
    data.type = "fragment";
    data.isInternal = true;
    data.fragment = state.document.getFragmentAtRange(selection);
  } else {
    selection = selection.moveToRangeOf(state.document.getChild(node.key));

    if (
      selection.endKey == target.endKey &&
      selection.endOffset < target.endOffset
    ) {
      target = target.moveBackward(selection.startKey == selection.endKey
        ? selection.endOffset - selection.startOffset
        : selection.endOffset);
    }

    let transform = state.transform()
      .removeNodeByKey(node.key)
      .moveTo(target);

    if (node.kind === "block") transform = transform.insertBlock(node);
    else if (node.kind === "inline") transform = transform.insertInline(node);
    else return;

    return transform.apply();
  }
}
```

I just want to point out that manipulating the data object when it has been marked internal was a bit of a hack to allow the core plugin to take over as if it were a fragment. A built-in implementation would not do this.

**Comment by ianstormtaylor** [comment]
Hey @tyler-johnson, good call! In the back of my mind I felt like there was a reason I omitted it, but I honestly can't remember, so we're probably safe to add it 😄 

If you're down, I'd help merge a PR!

**Comment by ianstormtaylor** [comment]
Fixed in newer versions of Slate!
