### ISSUE TITLE
Toggling a mark stops when selection started at block's end

### ISSUE THREAD

**Issue by FerrielMelarpis** [ianstormtaylor/slate#2830]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?

When selecting a text from end to any point at its left except the start of the block,
and toggling a mark, it stops the toggling state and moves the cursor to the leftmost of the adjacent text node.
It can be seen in Slate examples as well: https://www.slatejs.org/#/rich-text 

Here is a screen record:
![slate](https://user-images.githubusercontent.com/8219804/58302192-66c6cf00-7e1c-11e9-9a0e-149d254d720b.gif)

#### What's the expected behavior?

The expected behavior is to not lose focus and toggling state shouldn't stop.

**Comment by mkoskim** [comment]
This same behaviour can be experienced in Rich Text example: https://www.slatejs.org/#/rich-text

Go at the end of any line or make one. Press Ctrl-B and write. Text is bold. Now, try to toggle bolding off by pressing Ctrl-B again. When you write something, it is "automatically" toggled bold again. If you select some text at the end of line and press Ctrl-B to toggle bolding off, cursor is taken to the beginning of line.

**Comment by FerrielMelarpis** [comment]
@mkoskim I think this is a different issue but it is also a bug on toggling a mark. 
`toggleMark` uses `addMark` and `removeMark` commands internally and those commands change marks of the current selection. I tried debugging what happens when I am toggling a mark and it seems like `marks` becomes `null` when you remove them. It's not consistent though as I see some text nodes that have `marks: []` when the text doesn't have any mark.
```js
{
  anchor: {
    object: "point",
    offset: 6,
    path: [0, 1]
  },
  focus: {
    object: "point",
    offset: 6,
    path: [0, 1]
  }
  isFocused: true,
  marks: null, // I think this is right since we removed the mark on toggling again
  object: "selection"
}
```

The problem I see is not in the selection but rather in the nature of Slate that it merges text nodes. My theory is that the bug lies in the failure of creating another text node. In an example text like this:

"a **b** c" =>
```js
      { object: 'text', text: 'a', marks: [] },
      { object: 'text', text: 'b', marks: ['bold'] },
      { object: 'text', text: 'c', marks: [] },
```
but what happens is `text: 'c'` is concatenated to `text: 'b'` even if `text: 'b'` has marks and selection starting from `text: 'c'` has `marks: null`.

@ianstormtaylor sorry for tagging you but if you can point me to the right direction on fixing this, I am willing to submit a PR 😄 
Kudos to this awesome framework btw.

**Comment by ellinokon** [comment]
Looks like there is work being done here @FerrielMelarpis #2818

**Comment by FerrielMelarpis** [comment]
@ellinokon Thanks for referencing the PR. Looks like it will already solve this issue as well but I'll test it for this scenario as this might be a corner case that is not yet caught on the test cases.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
