### ISSUE TITLE
Add `componentDidMount` and `componentDidUpdate` event to plugins

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2832]
#### Do you want to request a _feature_ or report a _bug_?

Request a feature.

Note: Also looking for input on this feature request in case there is a better way to handle this without having to add this feature or to implement a feature that can provide the same benefits in a better way.

#### What's the current behavior?

There is no way to know when the Editor component has mounted or updated.

I have these scenarios where this is important in the Android implementation:

1. I need to set up a `MutationObserver` on the Editor's root element. Currently, in the plugin, I use a `requestAnimationFrame` during the plugin's initialization to add the mutation observer to the Editor's root element; however, this is hacky because (a) changes in implementation may mean that the root element might not exist after the `requestAnimationFrame` (possibly created later) (b) there may be a period of time between the component mounting and the `requestAnimationFrame` during which a mutation could come in and be missed.

2. When I call `editor.restoreDOM`, the root element of the Editor is discarded and rebuilt from scratch. Because it is built from scratch, the existing `MutationObserver` would be on an `Element` that is no longer in the DOM because it has been replaced by a newly created one. We could use `componentDidUpdate` to check then add the `MutationObserver` on the new object.

3. I need to ignore mutations that React is performing while paying attention to mutations that the user is doing. I can do this by setting a local variable `updating = true` before I call Editor commands (which modify the React DOM). All mutations that come in while `updating === true` are ignored so we don't react to React mutations. On the `componentDidUpdate` method, we set `updating = false` and we can pay attention to mutations again.

Note: The Android implementation is sensitive to timing issues and we need to make everything synchronous with respect to updates.

#### What's the expected behavior?

Create two or more additional events that hook into React's component life-cycle.

```js
const myPlugin = {
  componentDidMount(event, editor, next) {
    console.log(`Hey, the Editor's "Content" just mounted!`)
    next()
  },
  componentDidUpdate(event, editor, next) {
    console.log(`Hey, the component just updated!`)
    next()
  }
}
```

These could be valuable generally for when the developer needs to add some initialization to the Editor's root element. This would provide an easy way to hook into them synchronously during a mount or update. It could be argued that these are too low level for a common use case in which case we could remain them `unstable_componentDidMount` and `unstable_componentDidUpdate` in the style of React methods that are available but generally shouldn't be relied on.

**Comment by thesunny** [comment]
@ianstormtaylor this provide more details as per the message I sent to you through Slack.

**Comment by ianstormtaylor** [comment]
The use case makes sense to me. The only thing that makes me hesitate is that we’ll likely move to use hooks in the future (or at least that’s the goal) at which point these methods won’t exist. 

I’m personally fine with introducing them for now and then making breaking changes to remove them in favor of hooks later.

**Comment by brendancarney** [comment]
Regarding `componentDidMount`: Is it not enough to know that the component containing the editor mounted? 

On keeping track of the DOM element, can this be accomplished with a ref? 

If this is added, I'm definitely on the side of not making them a public API, and keeping it `unstable`, but I really think we can find a better way.

**Comment by thesunny** [comment]
@ianstormtaylor it should be easy enough to refactor to useEffect later so that works for me.

@brendancarney I can already get access to the root element and component but I can’t tell when the mount/update has happened.

I’m open to alternatives. Some alternatives I considered were:

- wait for ‘renderNode’ and then do a ‘requestAnimationFrame’ which is probably pretty close but is not synchronous.
- create a new Component for ‘document’ object during ‘renderNode’ and put the callbacks on that component but it seemed like a roundabout way that adds unnecessary components in the render pipeline

**Comment by steida** [comment]
RequestAnimationFrame can be tricky as hell. I prefer leveraging React API. I suppose your suggestion is right. Remember, make it work, make it right, make it fast.
