### ISSUE TITLE
Fix all showstopper bugs in Slate on Android 8, 8.1, and 9 (Help us by reporting and testing bugs)

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2839]
The purpose of this issue is to consolidate and fix all Android 9 bugs, especially those that are showstoppers (i.e. bugs that if we don't fix we can't claim to have Android support).

Started a new issue for these bugs instead of here https://github.com/ianstormtaylor/slate/issues/2726 because this is a completely new rewrite using mutations instead of events.

If you want Android support, you can help make it happen by testing and providing good bug reports. Note: If you can't recreate the bug, please do not submit it (e.g. needs to e more specific than "sometimes backspace doesn't work").

Thank you to the many that have asked what they can do to help with Android. This is the best way to do it. Once I'm off on the next project, it may be a while before I get back here.

## Supported Android Versions 8, 8.1 and 9 (API 28)

Currently supporting Android 8, 8.1 and 9 only (8 and 8.1 recently added)

## Known Issues

- Holding down `backspace` (i.e. repeating backspace) has unpredictable behavior. It should not crash the editor but will result in erratic behavior.

## Where to test Android support

Use my Slate examples site (not the official Slate examples). The official repo does not have my latest Android updates:

https://thesunny.github.io/slate/#/composition/split-join

## What to submit in a bug report

@Slapbox has put together a way to do a screencast and also put together a template for submitting bugs which you can use:

Courtesy of @slapbox:

(If someone has a better way to do anything mentioned, I will update this comment)

## Easiest way to create screen recordings
1. [Download DU Recorder from the Play Store](https://play.google.com/store/apps/details?id=com.duapps.recorder&hl=en_US) (Play store seems to be having issues currently)
2. Create your screen recording.
3. Upload your created file at https://imgur.com/upload to get a shareable link - I use [Join](https://play.google.com/store/apps/details?id=com.joaomgcd.join) to send the file to my PC and upload it to Imgur from there.
4. Share your recording and ensure that you explain the steps to recreate the bug AND that the recording is not too fast for someone to decipher what's going on. It's likely it will take a few tries to get a solid recording for some bugs and you might be feeling impatient. Take the extra 10 seconds to ensure a quality recording for your bug report.

## Finding the API version for your version of Android: 

Check the version of Android on your phone, then visit this link: https://source.android.com/setup/start/build-numbers

## Template

```
## Android Version
Get it from https://source.android.com/setup/start/build-numbers

## Description of Bug
- Start from a clean example (make sure to reload page)
- Describe steps
- Provide screencast where helpful
```

**Comment by thesunny** [comment]
For those interested, the code for Android support is here https://github.com/thesunny/slate/tree/mutations-android

Most of the changes exist here https://github.com/thesunny/slate/tree/mutations-android/packages/slate-react/src/plugins/android

- `mutation.js` is the plugin
- Most of the actual work is in `composition-manager.js`

**Comment by HGZwebdesign** [comment]
## Android Version
version: 9,
Samsung S9,
browser: Chrome

## Description of Bug
The button 'bold' doesn't work.

**Steps:**
- type: "it should be "
- press button "B"
- type: "bold, but it is"
- select word "isn't" from suggestions
- type: ". "
- press "B" again
- cursor moves before "."
