### ISSUE TITLE
Placeholder not working inside a custom node

### ISSUE THREAD

**Issue by malihs** [ianstormtaylor/slate#2842]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?

The placeholder using `slate-react-placeholder` does not seem to work correctly when using a custom node. Here is a CodeSandbox demonstrating the issue: https://codesandbox.io/s/zw5dm

#### What's the expected behavior?

When completely deleting the content of the custom node, the placeholder should show.

**Comment by loopla-eric-owens** [comment]
I'm experiencing the same.

**Comment by pvanliefland** [comment]
For me it looks like updating to slate 0.47.4 / slate-react 0.22.4 fixes the issue

**Comment by malihs** [comment]
@pvanliefland yes it does. Thank you!
