### ISSUE TITLE
Focus change after backward selection and toggleMark

### ISSUE THREAD

**Issue by ggustilo** [ianstormtaylor/slate#2846]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

When I backward select content via keyboard or mouse and toggle a mark (bold, italic), it correctly renders the mark but sends the focus to the beginning of the line.

The bug is present in https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js

![slate_selection_focus_bug](https://user-images.githubusercontent.com/8061922/58718089-5cfc1900-8392-11e9-82a5-d86eeebd483e.gif)

Present in Chrome, Firefox and Safari.  Slate version 0.46.1.

Note: This does not occur with forward selection and does not happen when a second mark is applied.

#### What's the expected behavior?

Expected behavior is for focus to stay blurred after mark render, with selection still active, waiting for the user to change focus to before/after selection.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
