### ISSUE TITLE
Toggle mark bug : toggle, at the start of writting - untoggles

### ISSUE THREAD

**Issue by minbraz** [ianstormtaylor/slate#2848]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

The bug is present in https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js

type: 'aa'
type: ctrl+b
type: 'bb'
type: ctrl+b
type: 'cc' <-- also has 'bold' mark

![bug-1](https://user-images.githubusercontent.com/144001/58747239-0b768b80-8471-11e9-9b0a-989c674e55b2.gif)

OS: Ubuntu 18.04.2 LTS
browser: Firefox 67.0 
slate version: 0.47.3
slate-react version: 0.22.3

#### What's the expected behavior?

type: 'aa'
type: ctrl+b
type: 'bb'
type: ctrl+b
type: 'cc' <-- normal text

**Comment by samuelcolvin** [comment]
Should be fixed by #2818.
