### ISSUE TITLE
How to get a Marks path or key.

### ISSUE THREAD

**Issue by North101** [ianstormtaylor/slate#2852]
#### Do you want to request a _feature_ or report a _bug_?

Request a feature

#### What's the current behavior?

I'm trying to replace all marks like this:
```
editor.value.document.getMarksByType(type).forEach((value) => {
  editor.setMarkByPath(path, 0, undefined, value, {
    type: type,
    data: newData
  });
});
```

But how do I get the path of the mark? (Maybe I'm just missing something)

#### What's the expected behavior?

A way to get the path or key of the mark.

**Comment by minbraz** [comment]
Marks, themselves, do not have keys, but text nodes have them. 

See https://docs.slatejs.org/slate-core/mark, https://docs.slatejs.org/slate-core/text ,

**Comment by North101** [comment]
Thanks. Seems like an indirect way to do it but it worked.
