### ISSUE TITLE
[bug] Using non-English input methods in code blocks results in repeated input

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2854]
### Do you want to request a _feature_ or report a _bug_?

**bug**, very serious.

The following demo uses the official example [https://www.slatejs.org/#/code-highlighting](https://www.slatejs.org/#/code-highlighting)

### What's the current behavior?
I just want to enter Chinese: "搜索搜索"。

I use the Chinese input method, press the "**s**" key 4 times per line, and then press the "**space**" key.

However, input in the code block, the result is not in line with expectations.
It produces duplicated characters, and the second half cannot get the focus and cannot be selected.

In Chrome v74 browser, as below :

![slate-chinese-repeated-error](https://user-images.githubusercontent.com/3793502/58934096-10eb1300-879c-11e9-8648-1e7b7dceed80.gif)

In Firefox v67 browser, as below :

![slate-chinese-repeated-error-in-firefox](https://user-images.githubusercontent.com/3793502/58934113-1a747b00-879c-11e9-887a-8bcc34c87889.gif)

### What's the expected behavior?

Below, I am using the Quill Rich Text Editor for the demo.

![quilljs-chinese-input-demo](https://user-images.githubusercontent.com/3793502/58934657-b18e0280-879d-11e9-980b-1e98f57f1df7.gif)

**Comment by Coderhypo** [comment]
This bug existed in 2018.

Reference：
- https://github.com/ianstormtaylor/slate/issues/2457
- https://github.com/ianstormtaylor/slate/issues/2458

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
