### ISSUE TITLE
Undoing change to atomic annotations throws

### ISSUE THREAD

**Issue by fraziermork** [ianstormtaylor/slate#2856]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
![annotation-undo-bug](https://user-images.githubusercontent.com/16546625/59055030-c9bb5b80-8849-11e9-8e79-8b791d2543eb.gif)

Not including a jsfiddle because the search highlighting example is sufficient to repro the bug. In the gif, I delete a character in an atomic annotation so that slate cleans it up, then undo that edit. It throws an error somewhere in applyOperation/removeAnnotation.

Not sure if this is related to the whole `editor.withoutSaving` thing

#### What's the expected behavior?
not to throw

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
