### ISSUE TITLE
remove the `*ByKey` commands

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2858]
As part of https://github.com/ianstormtaylor/slate/issues/2495 we'll want to get rid of the `*ByKey` commands (with a deprecation stage first).

**Comment by nz-chris** [comment]
Have schema normalize functions been considered? I think these rely heavily on keys at the moment, as there is no obvious way to get the path of the 'error node'. Perhaps the error object should include a path?

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
