### ISSUE TITLE
Backspace on selection has issues while chrome inspector is open.

### ISSUE THREAD

**Issue by wtr7** [ianstormtaylor/slate#2866]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

When I make a selection of some text and I press "backspace", it will only delete the last character and not the whole text. This ONLY happens when my inspect console is open.

http://recordit.co/Bds6GRHe0M

#### What's the expected behavior?

It should remove the selected text which works correctly when my console is closed.
http://recordit.co/vRFipDkzwq

```
"react": "^16.8.6",
"slate": "^0.47.4",
 "slate-react": "^0.22.4"
```

This happens in Chrome Version 73.0.3683.103. With safari I don't have this issue.
Did anyone had an issue like this or knows something about it?

Thanks!

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
