### ISSUE TITLE
Undoing adding/removing marks no longer takes the length of the mark into account

### ISSUE THREAD

**Issue by jas7457** [ianstormtaylor/slate#2870]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
Inverse operations are not added correctly for (presumably) remove_mark

Codesandbox: https://codesandbox.io/s/eager-architecture-feupo
Recordit: http://recordit.co/AdqywQRyo3
#### What's the expected behavior?
Toggling a mark and clicking Undo would correctly put the document in the correct state.

*Note:* This seems to have been broken at the 0.46.0 release. Prior to that upgrade, this worked, but something (presumably the refactor for removing leaves) broke this behavior in that release.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
