### ISSUE TITLE
Pasting HTML results in four erroneous trailing blank lines.

### ISSUE THREAD

**Issue by nz-chris** [ianstormtaylor/slate#2875]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Pasting HTML into a slate editor supporting html paste (https://www.slatejs.org/#/paste-html) will result in four blank lines appearing after the pasted text.
In this example video, I use the official paste-html live example, and I use MacOS Notes as the paste source (text from Notes is considered HTML). My browser is Chrome.
![Jun-12-2019 10-57-38](https://user-images.githubusercontent.com/37297133/59312356-f9aea700-8d00-11e9-802d-84a0f7d95012.gif)

#### What's the expected behavior?
No erroneous blank lines.

___

From my experimentation, it is not possible to catch these blank lines in the deserialization stage.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
