### ISSUE TITLE
Discussion on command and plugin adapter

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#2879]
I have not working on the SlateJS for some time.  Please forgive me when I got something wrong.

This post is trying to discuss on the dependency between plugins, and some naive ideas to use Lens as a solution.

# Current State on Plugin Dependency

Currently, all plugins are in same level, and each plugin register their commands and queries to `editor`, and every plugins potentially can call all commands and queries from all
plugins.

All commands are just a side effect on the whole editor, and it can access every node under document. Then in the development, we always have some unhappy boilerplate of re-get the ancestor after calling a command. 

# A Root transformation

Suppose we have two editors, editor P and editor Q, and editor Q's root Document is equal to editor P's one descendant block.

```
Editor P
  Void
   |
   A
  / \
 B   C
    / \
   D   E

Editot Q:
    Void
     |
     C
    / \
   D   E

```

Then for any operations on editor Q, we can correspondingly find an operations on editor P

```javascript
const Poperation = {
  ...Qoperation,
  path: [1, ...Qoperations[Q]],
  selection: selection.mapPath(...)// selection transformaed by path
}
```

More generally, we can have a statement like this:
> For any two root block P and Q, if there exists a path transformation from Q to P that 
> maps all block in Q to block in P.  Then all operations in an Editor of Q are equivalent
> of an operation in an Editor based on P.

## Effect interface
We can introduce an interface named `Effect`, which shall handle all editor operations except
`undo`.  The `Effect` is alike a just initialized Editor with all side effects just under a descendant/subgraph

```javascript
  const pathQ2P = {
    forward: (path) => [0, 1, ...path[1:end]]
    backward: n => n.getChild(1)
  }
  
  const effectQ = effect(n => {
    n.removeDescendent(E.key)
  })

  const effectP = pullback(pathQ2P, effectQ)
  
  editor.apply(effectP)
```

This will remove node E.  Suppose we replace `E.key` with `A.key` here.  This shall throw an error that A is not found in Q.

In the sense of subgraph, we can also have some teleconnection logic in this way:
```
Editor P
  Void
   |
   A
  / \
 B   C
    / \
   D   E

Editot Q:
    Void
    / \
   B   D
```

```javascript
const pathQ2P = {
  forward : path => path[0] = 0 ? [0,0, path[1:end]] : path[0,1,0, path[1:end]]
  backward: node => new Root([node.getNode([0]), node.getNode[1,0]])
}

const effectQ = ....;

const effectP = pullback(pathQ2P, effectQ)
  
editor.apply(effectP) 
```
To enable this feature, we need a root, named Void here, which is ancestor of all nodes in all graphs.

## Composite of path transformation and Effect, and Error Handling

Obviously, Effect on the same node/graph is composable.
> Suppose `EffectP1` and `EffectP2` are effect on P, then we can have an accumulated effect by sequentially apply them.
```
class Effect {
  run(n : Node) => (Node, [Operations])
}

compose(eff1, eff2) = (node) => {
  const (n1, op1) = eff1.run(node)
  const (n2, op2) = eff2.run(n1)
  return (n2, [...op1, ...op2])
}
```

The Error Handling comes almost freely if we replace the Tuple above with a promise-like interface.  We can leave it to future discussion.

For the path transformation, we can have it composable freely: 
```
interface PathT = {
  forward : Path -> Path
  backward : Node -> Node
}
```

We only need to concat them just like `a->a`.  Similarly, we can have error torenlance with replacing `a->a` with `(MonadFail m) => a -> m a`.
We can still leave it to feature discussion because it will not change the designed interface.

# On Plugins, how to composite commands.

Insofar, we have discussed about how to describe operations and effects without introducing editor.  
Therefore, we do not need to include editor everywhere.  Instead, we can implement something like 
`implicit parameter`, or shared parameter:

``` pluginA.ts
import {Implicit} from `slate`
export const SymEffectA = Symbol('EffA')
export default mkPlugin(implicit : Implicit) : Plugin {
  implicit[SymEffectA] = effA;
  return ...;
}
```

```pluginB.ts
import {Implicit} from 'slate'
import {SymEffectA} from './pluginA'
export default mkPlugin(implicit : Implicit) : Plugin {
  const effA = implicit[SymEffectA]
  const effB = mkEffect(effA, ...)
  ...
  
  return  {
     onKeyDown () { ....; editor.apply(effB)}
  }
}
```

```
type implicit = {[_: Symbol] : Effect|Query|SlateOthers}
```

Instead of `[Plugin]`, we will use `[Implicit -> Plugin]` or `[Implicit -> (Implicit, Plugin)]` as the `plugins`.  They are also composable.

Because we are using `Symbol` here, there will be no overwritten between plugins.

In these way, we can move commands, queries out of plugin instance, and then plugins can include only normalization, events and rendering.

**Comment by ianstormtaylor** [comment]
Hey @zhujinxuan, thank you so much for writing this up! This is really interesting. I don't fully understand all of it I think, but that's okay.

I've been thinking about a similar use case of nested sub-editors, and having operations apply relative to a root like this. But it wasn't to decouple commands/plugins, but just to allow nesting.

How would this work with command overriding—allowing commands in a plugin to override a native editor command for example, like `splitBlock`, and tweak its behavior in certain circumstances.

**Comment by zhujinxuan** [comment]
Hi @ianstormtaylor , if you are asking about how to make a command/effect have different behavior on different node (polymorphism, in a fancy/PL way).  I am thinking a idea like Haskell's type class:

```
type Effect = Node -> (Node, [Operations]) | null

interface Implicit {
  [Symbol] : [Effect]
}
```

Then we can register or get an effect by symbol as 
```typescript
register(s : Symbol, im : Implicit, eff : Effect) : void {
  if (im[s]) im[s].push(eff);
  else im[s] = [eff]
}

get(s: Symbol, im : Implicit) : Effect {
  if (!im[s]) return (_) => null
  retutn n => {
      for (const eff of im[s]) {
            const y = eff(n)
            if (y) return y;
      }
      return null
  }
}
```

**Comment by steida** [comment]
@zhujinxuan I started with React editor from scratch https://github.com/steida/slad

Can you help me to define the better command API probably made with https://github.com/gcanti/fp-ts?

**Comment by zhujinxuan** [comment]
@steida I would like to help.  However I may be not very helpful because I do not have enough time in recent half year.

Please feel free to mention me at any issue of your editor.  I will help if I can.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
