### ISSUE TITLE
state.transform().blur().apply() does not remove selection / caret

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#288]
I have an `onBlur` handler who is triggered programatically. My onBlur handler (has nothing to do with slate) runs:

```
  onBlur = (props: Props) => {
    props.onChange({
      editorState: props.state.editorState
        .transform()
        .blur()
        .apply()
    })
  }
```

However, the changes do not seem to propagate to slate.

![](http://g.recordit.co/tZdKaci5qk.gif)

In the redux state this looks as follows. Before changing focus:

<img width="1874" alt="bildschirmfoto 2016-09-01 um 16 37 22" src="https://cloud.githubusercontent.com/assets/3372410/18171502/8f2fa860-7062-11e6-87dc-83c78189b34d.png">

After changing focus:

<img width="1876" alt="bildschirmfoto 2016-09-01 um 16 37 29" src="https://cloud.githubusercontent.com/assets/3372410/18171499/8eec8814-7062-11e6-9780-b73c05dc4d94.png">

I did not set the `onBlur` property in slate, only `onFocus={() => false}`

**Comment by arekkas** [comment]
I am not doing anything different than slate:

```
  blur = () => {
    const state = this.state.state
      .transform()
      .blur()
      .apply()

    this.onChange(state)
  }
```

https://github.com/ianstormtaylor/slate/blob/0755e6b226dd854a0d49789f5142b3eaec5760eb/lib/components/editor.js#L134

**Comment by cobbweb** [comment]
Are you passing the new blurred state back into Slate?

**Comment by arekkas** [comment]
@cobbweb most definitely, otherwise other changes would not propagate.

**Comment by arekkas** [comment]
superseded by #297
