### ISSUE TITLE
removeMark behavior changed slightly since 0.45.x - By design, or accident?

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2880]
#### Do you want to request a _feature_ or report a _bug_?

Bug(?)

#### What's the current behavior?

`removeMark` no longer removes marks from a collapsed selection.

#### What's the expected behavior?

Previously calling `removeMark` would remove marks from a collapsed selection.

**Comment by isubasti** [comment]
duplicate of https://github.com/ianstormtaylor/slate/issues/2848, https://github.com/ianstormtaylor/slate/issues/2830, https://github.com/ianstormtaylor/slate/issues/2736, maybe https://github.com/ianstormtaylor/slate/issues/2736. fixes PR seems to be on the way https://github.com/ianstormtaylor/slate/pull/2818

**Comment by Slapbox** [comment]
Nice work @isubasti, it's indeed a duplicate of #2848
