### ISSUE TITLE
Merge and simplify input handling for desktop, mobile, compositions, IME, single input, Android, etc.

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2882]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Currently, there are multiple techniques for handling input and the code for these techniques are in several different places in Slate.

Some input handling techniques are and forgive me if I make a mistake when describing the technique used but this should give you a general idea:

* Keydown handling: We intercept an event, cancel it, modify the Slate Value and then render the result to the browser DOM
* Spellcheck handling: I believe this happens on an `input` that isn't handled by anything else. We look at the browser DOM, see what's changed, then modify the Slate Value and then render the result to the browser DOM (which should basically be like a noop)
* Composition handling: On composition end we do some handling to update the Slate Value
* Android handling using mutations: Because of the limitations of what Android communicates by events, we use a combination of mutations and compositionEnd events to update the Slate Value which we then use to update Slate Value

#### What's the expected behavior?

Ideally, there should be one way of handling input in one place. This will reduces the total amount of code and the complexity of needing overlapping methods of handling input depending on whether it is composition, non-composition or Android (which as of now uses a completely separate input handling method).

The unifying solution IMO at this point of my understanding of all the issues is this:

* Use mutations to identify when simple text changes have occured like inserting text in a node or removing text in a node. Use this to update Slate Value instead of events.
* Where these mutations happen within a composition (e.g. after a `compositionStart`), we do not update the Slate Value but only track changes until one of these things happens at which point we update the Slate Value with the tracked changes which causes a render:
  * a `compositionEnd` event
  * the mutation happens in a node different than the previously mutated node at which point we commit the value change to Slate
  * We get an `enter` at which point we commit the value change to Slate and then execute a `spliteNode`.
  * We get a `backspace` or `delete` that removes a node (e.g. all the characters in a bold span are deleted)
  * We get a `backspace` at the beginning of a block and need to merge two block nodes.

##### Enter

* We can identify `enter` by looking at mutations. In this case, we have to make sure to revert DOM using `DOMSnapshot` (preferred) or using `editor.restoreDOM()` (slower because the entire Editor Content DOM has to be rebuilt).

##### Backspace and Delete

* If `backspace` or `delete` removes text within a DOM node while we are in a composition, we just track the changes. We only need to specially handle when a node gets removed or we backspace over the beginning of a block and have to merge into the previous node.
* If we get a `backspace` or `delete` that removes an inline node like in `bold` text, we update the Slate value and render. We have use `DOMSnapshot` or `editore.restoreDOM()` to fix DOM
* If we get a `backspace` or `delete` that merges two blocks, we update the Slate value and render. We use `DOMSnapshot` or `editor.restoreDOM()` to fix DOM.

#### Benefits

By doing this, we should be able to use a single code base for

* single character inputs
* compositions
* spell check fixes
* IME
* autosuggest
* gesture writing
* Android

**Comment by mpkelly** [comment]
Hi @thesunny, can you confirm how I should be consuming slate if I want @sgurenkov's [PR](https://github.com/docusign/slate/tree/fix-marks-bugs) and you Android improvements? Looking at the commit history I should be getting your changes with Stan's but when testing on Android the [editor](https://rawcdn.githack.com/mpkelly/react-text-editor/4deebfa06b53ac5162b58385e1297dca31c0dcec/example/index.html) is unusable: cursors jumps to start of line; can't enter to new line and text prediction dumps meaningless text into editor.

**Comment by thesunny** [comment]
@mpkelly I'm sorry but I don't have the bandwidth to figure out how sgurenkov's PR is impacting Android support. It's hard enough keeping it working on mainline. ;)

**Comment by ianstormtaylor** [comment]
Hey, there are lots of open Android-related issues that are out of date with the latest `0.50` release because the codebase was completely rearchitected. We'll need to figure out how to have proper support for Android going forward based on `beforeinput` events somehow. I'm tracking this in https://github.com/ianstormtaylor/slate/issues/3112, so I'm going to close this in favor of that one. 

If it cannot be implemented simply in core with `beforeinput` we'll likely need to have a separate plugin for android support be created, because it's too much of a departure from all of the other simpler logic in core and very hard for me to test or respond to issues. Using a separate plugin should be possible now as the newest version simplifies a lot of the internals.

Thank you for understanding.
