### ISSUE TITLE
Plugins as react components

### ISSUE THREAD

**Issue by marcuslindfeldt** [ianstormtaylor/slate#2884]
#### Do you want to request a _feature_ or report a _bug_?
feature request

#### What's the current behavior?
Slate plugins is not react components which makes it awkward to hold state.

#### What's the expected behavior?
One rough idea with hooks could look something like this:

```jsx
import React from 'react';
import { useOnKeyDown } from 'slate';

const SlatePlugin = ({ editor, children }) => {
  const  [pluginState, setPluginState] = useState({ showLinkModal: false });

  useOnKeyDown(editor, () => {
    // handle editor keydown events...
  })

  return (
    <>
      {children}

      {pluginState.showLinkModal && (
        <MyLinkModal />
      )}
    </>
  );
};

export default SlatePlugin;
```

**Comment by kierson** [comment]
That would we awesome.

Currently it is hard to mainain state and react to changes in the state of upper level components or changes in redux state tree.

**Comment by thovden** [comment]
I'm also struggling finding a way to implement a plugin that manages a modal popup. The plugin will detect words or react to hotkeys, and pop up a menu. It would be great to be able to do this with standard React state mechanisms.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
