### ISSUE TITLE
shouldNodeComponentUpdate is not deprecated in slate-react plugins documentation

### ISSUE THREAD

**Issue by qrew** [ianstormtaylor/slate#2885]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

Currently slate-react plugins documentation doesn't say that `shouldNodeComponentUpdate` is deprecated. However, console shows warning:

> As of slate-react@0.22 the 'shouldNodeComponentUpdate' middleware is deprecated. You can pass specific values down the tree using React's built-in "context" construct instead.

#### What's the expected behavior?

Documentation should say that `shouldNodeComponentUpdate` is deprecated and explain what should be used instead.

**Comment by dmitryplatonov** [comment]
Yes, I'm having the same problem.
Force refresh plugin no longer works because of this change. Would be nice to have at least working example.

**Comment by winrey** [comment]
Met error when tried two different ways to use a context API in Plugin.

I finally endup with using a `editor.setNodeByKey()` to reset all nodes which need to refresh.

Here is an example to refresh all the node.

```javascript
commands: {
        refreshAllNodes: (editor) => {
          editor.value.document.getTexts().forEach(
              node => editor.replaceNodeByKey(node.key, node)
          )
          return editor
        }
}
```

**Comment by qrew** [comment]
Here's an example how we use React build-in "context". If 'value' has been changed CustomContext.Consumer will be re-rendered. 

``` 
  import React from 'react'
  const CustomContext = React.createContext({})
  
  function CustomBlock({children, ...props}) {
    return (
      <CustomContext.Consumer>
      {value => {
        return <div className={value}>{children}</div>
      }}
      </CustomContext.Consumer>
    )
  }

  const renderBlock = (props, editor, next) => {
    const children = next()
    return <CustomBlock {...props}>{children}</CustomBlock>
  }

  const renderEditor = (props, editor, next) => {
    const children = next()
    const customClassName = 'block'
    return (
      <CustomContext.Provider value={customClassName}>
        {children}
      </CustomContext.Provider>
    )
  }
```

**Comment by winrey** [comment]
@qrew Thanks for the example, but how if we need to update a value which is a state in plugin in a plugin's commend or a plugin's?

It cannot be managed by a react built-in state system(It means we cannot update it by a `setState()`), and will raise an error if using a `useContext()` hock.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
