### ISSUE TITLE
Node index doesn't update after being moved

### ISSUE THREAD

**Issue by schabluk** [ianstormtaylor/slate#2886]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

When getting the current index of a node with `parent.nodes.indexOf(node)`, it doesn't update, after a node is moved.

Reproduced issue: https://codesandbox.io/s/floral-cloud-v8udh - click "Move Down" button - the `index` variable keeps its value.

It changes only, when editable field is focused.

![](http://g.recordit.co/nA9vGJSFHm.gif)

OS: Windows, OSX
Browser: Chrome, latest
Slate version: 0.47.4
Slate react version: 0.22.4

#### What's the expected behavior?

All node indexes should be updated after the node was moved to a different position.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.

**Comment by schabluk** [comment]
Confirmed, in 0.50 it is working correctly. Sandbox for reference: https://codesandbox.io/s/ianstormtaylorslateissues2886-2ywcx
