### ISSUE TITLE
Is it possible to avoid XSS attacks?

### ISSUE THREAD

**Issue by lcswillems** [ianstormtaylor/slate#2887]
Hi,

Does Slate prevent the insertion of `<script></script>` or unwanted markup?

**Comment by dmitrizzle** [comment]
Check out Slack channel for quick answers, this repo's issues are usually limited to bug reports and feature requests. Other than that, yes, you define what tags are allowed explicitly in Slate.

**Comment by lcswillems** [comment]
Okay, great!
