### ISSUE TITLE
Hyperlinks are not clickable 

### ISSUE THREAD

**Issue by laufeyrut** [ianstormtaylor/slate#2888]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Hyperlinks are not clickable. 

Reproduction of the issue: 
https://jsfiddle.net/laufey/9ac1d3t2/9/

This is also an issue in the example 
https://www.slatejs.org/#/links 

![hyperlinkBug](https://user-images.githubusercontent.com/15036127/59672973-070bdb80-91b0-11e9-8d06-69aea64b567b.gif)

Chrome Version 74.0.3729.169
Safari Version 12.1.1 (14607.2.6.1.1)
MacOs 10.14.5 (18F132)

#### What's the expected behavior?
You should be able to click the hyperlink

**Comment by adjourn** [comment]
You mean navigate on click?

It should work just fine if you set editor to `readOnly` mode: [updated fiddle](https://jsfiddle.net/t0d7rung/). If link was clickable in edit mode, user wouldn't be able to place cursor inside the link, etc. If you want clickable links in edit mode, I suggest to display a hover menu with clickable link if selection is inside the link.

**Comment by laufeyrut** [comment]
@adjorn Thank you did not know that was the case! 
Will close this issue 🙃

**Comment by fourcolors** [comment]
@adjourn There is a real use case where you want to be able to click on the link while editing. For instance, Notion or Dropbox Paper style menu's allow you to click on the link to navigate away from the page. If you want to edit the link, you just need to select the entire link. 

I'm current working on getting this working. I'm hoping this is straight forward.

**Comment by yleflour** [comment]
@fourcolors Have you found a way to manage this use case? I'm interested in the solution.

**Comment by rocket-squirrel** [comment]
You can add a custom onClick handler to link element e.g.

`onClick={(e) => { if (e.metaKey) { window.open(element.url, '_blank') } }}`

In this case link remains editable, but can be opened in a separate tab via Cmd+Click.

**Comment by dsvgit** [comment]
works for me
```javascript
import React from "react";
import {
  createLinkPlugin as _createLinkPlugin,
  ELEMENT_LINK,
} from "@udecode/slate-plugins";

export const createLinkPlugin = (options) => {
  const plugin = _createLinkPlugin(options);

  return {
    ...plugin,
    renderElement: (editor) => {
      const renderElement = plugin.renderElement(editor);
      return (props) => {
        if (props.element.type === ELEMENT_LINK) {
          return (
            <span
              onClick={(e) => {
                const linkElement = e.currentTarget.querySelector("a");
                if (linkElement && e.metaKey) {
                  const href = linkElement.href;
                  window.open(href, "_blank");
                }
              }}
            >
              {renderElement(props)}
            </span>
          );
        }
      };
    },
  };
};

```

**Comment by inithink** [comment]
This makes it work like a regular mouse click.

```typescript
onClick={(e) => {
  e.currentTarget.contentEditable = "false";
  setTimeout(() => (e.currentTarget.contentEditable = "true"), 200);
}}
```
