### ISSUE TITLE
Examples - Search highlighting no longer works across marks

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2889]
#### Do you want to request a _feature_ or report a _bug_?

Feature, of sorts

#### What's the current behavior?

0.47.x changes the decoration logic and I'm no longer sure what an easy, performant way to highlight over marks would be.

#### What's the expected behavior?

Pre 0.47.x search highlighting code worked across/over marks.

The example itself does not include marks, but the code worked for that purpose previously. It's not really bona fide search highlighting if words or phrases are left out because there's a mark boundary within them.

**Comment by Slapbox** [comment]
I really like the new changes, but they do make a small subset of tasks about 50 times harder than they used to be, even if they make 95% of use cases much easier.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
