### ISSUE TITLE
Select-all/delete not working in document with trailing void node

### ISSUE THREAD

**Issue by erquhart** [ianstormtaylor/slate#2890]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?
If the last top level block in a document is a void node, <kbd>cmd</kbd>+<kbd>a</kbd> (or <kbd>ctrl</kbd>+<kbd>a</kbd> for Windows) moves the cursor to the beginning of the document to the beginning of the document without selecting anything.

If you manually select all document content, or select via `editor` command, and then press backspace, everything is deleted except the trailing void node. Pressing backspace a second time deletes the void node.

This is reproduced in the Embeds demo:

1. Hit the link: https://www.slatejs.org/#/embeds
2. Delete the final paragraph so the last selectable thing in the document is the embed
3. Hit <kbd>cmd</kbd>+<kbd>a</kbd> (or <kbd>ctrl</kbd>+<kbd>a</kbd> for Windows)

#### What's the expected behavior?
Select-all keyboard shortcut should work with a trailing void node, as should deletion with everything selected.

**Comment by ruandao** [comment]
I get a similar problem

when i select all, and delete: it raise:
Uncaught TypeError: Cannot read property 'anchor' of null

I delete all plugins, this error still throw

```
slate-react.es.js:3156 Uncaught TypeError: Cannot read property 'anchor' of null
    at slate-react.es.js:3156
(anonymous) | @ | slate-react.es.js:3156
-- | -- | --
  | requestAnimationFrame (async) |   |  
  | onSelect | @ | slate-react.es.js:3149
  | onSelect | @ | slate-react.es.js:3262
  | next | @ | slate.es.js:10637
  | run | @ | slate.es.js:10666
  | run | @ | slate-react.es.js:5634
  | onEvent | @ | slate-react.es.js:5524
  | (anonymous) | @ | slate-react.es.js:1485
  | invokeFunc | @ | debounce.js:97
  | leadingEdge | @ | debounce.js:107
  | debounced | @ | debounce.js:171

```

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
