### ISSUE TITLE
Copy pasting text with different marks messes up cursor position

### ISSUE THREAD

**Issue by mengusfungus** [ianstormtaylor/slate#2894]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

The bug can be seen in the rich text example https://www.slatejs.org/#/rich-text

A gif is attached that should be pretty self explanatory. Basically copying text with a certain mark and pasting it into text with a different mark will mess up the cursor position.

![slatejsbug](https://user-images.githubusercontent.com/17165883/59960352-2c346e80-947c-11e9-8e13-0ba12da012d9.gif)

#### What's the expected behavior?

The paste itself works correctly, I would expect the cursor to be positioned immediately after the end of the newly pasted text.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
