### ISSUE TITLE
Unexpected behavior on list item

### ISSUE THREAD

**Issue by filipsvensson** [ianstormtaylor/slate#2896]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

http://recordit.co/6GoFju0RTh

Reproducible in the slate rich-text demo. 

- create empty list item
- press enter
- toggle list
- write some text
- move to beginning of paragraph
- press backspace

#### What's the expected behavior?

Paragraph should be part of last list item

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
