### ISSUE TITLE
Update npm with latest fixes

### ISSUE THREAD

**Issue by LouisMelo** [ianstormtaylor/slate#2897]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

`setAnnotations` is not a function, it's added in a latest fix, but 0.47.4 didn't contain it~

Could you please update npm version to fix this problem?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
