### ISSUE TITLE
Plugin handlers are passed an incomplete instance of editor object

### ISSUE THREAD

**Issue by kilrain** [ianstormtaylor/slate#2900]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

I'm not sure this is the behavior for all Plugin callbacks, but... for onCopy, at least, the second argument (editor) doesn't seem like it has all the expected functionality.

When I try to call `editor.setValue()`, I get an error saying it isn't a function. When I reference the plugins property, it's undefined.

[Here is a JSFiddle](https://jsfiddle.net/vyswf8ma/4/) which exhibits the problem (open your dev console to see the logs)

Apologies - I tried to get the recordit app working for a gif... but it's a bit buggy. You can see the behavior (And the code) in the JSFiddle.

MacOS 10.14.5
Chrome 75
Slate 0.45
Slate-React 0.22.4

#### What's the expected behavior?

All methods and properties for [the slate editor](https://docs.slatejs.org/slate-core/editor) are available in plugin callbacks such as onCopy.

**Comment by kilrain** [comment]
I've realized that the docs may be out of date with regard to the `plugins` property. But `setValue` should still be defined

**Comment by kilrain** [comment]
Some discussion on the Slack channel: https://slate-js.slack.com/archives/C1RH7AXSS/p1561809462190400

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
