### ISSUE TITLE
Wrong or misleading validation error when trying to normalize on a schema expecting exactly three consecutive nodes.

### ISSUE THREAD

**Issue by lukasbuenger** [ianstormtaylor/slate#2904]
#### Do you want to request a _feature_ or report a _bug_?

I think it's a _bug_ or at least very unintuitive behavior.

#### What's the current behavior?

https://jsfiddle.net/1nev2pw7/7/
![](http://g.recordit.co/DKghmTWiFq.gif)

slate: 0.47.4
slate-react: 0.22.4
Chrome: 75.0.3770.100
OSX: 10.14.5
react and react-dom: 16.8.6

Given a document that gets controlled by a schema that expects exactly three consecutive nodes:
```
{ match: { type: 'main' }, min: 1, max: 1},
{ match: { type: 'sidebar' }, min: 1, max: 1},
{ match: { type: 'footer' }, min: 1, max: 1}
```

After an operation, that causes a merge of nodes `main` and `sidebar` (see GIF for example) into a single node `main`, a validation error `child_min_invalid` is thrown for `index: 0`.

#### What's the expected behavior?

After an operation, that causes a merge of nodes `main` and `sidebar` into a single node `main`: 
- a validation error `child_min_invalid` is thrown for `index: 1`.
- a validation error `child_type_invalid` is thrown for `index: 1`.

**Comment by wleroux** [comment]
I am also experiencing this issue. It is causing the browser to crash (as I try to insert the node for the wrong index, thus causing a perpetual child_max_invalid child_min_invalid cycle).

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
