### ISSUE TITLE
Chrome is not firing onBeforeInput when editor is blurred during IME

### ISSUE THREAD

**Issue by bengotow** [ianstormtaylor/slate#2906]
#### Do you want to request a _feature_ or report a _bug_?
Bug report specific to Chrome (testing on Chrome 75)

#### What's the current behavior?
- Open https://www.slatejs.org/#/syncing-operations in Chrome.
- Type "korewa" with the Japanese input enabled on MacOS
- Without pressing Enter to confirm the IME dropdown, click out of the Slate editor (anywhere else on the page is fine).

![Jul-01-2019 12-16-45](https://user-images.githubusercontent.com/1037212/60454703-2831ea80-9bfa-11e9-9cb4-0541a8f9ef4b.gif)

#### What's the expected behavior?
The text remains in place and the underline disappears (expected behavior), but no onBeforeInput event is emitted so Slate does not fire an onChange event and the text you typed is not added to the value. You can tell it is broken because the typed text does not appear in the second editor on the page.

**In Firefox, this works as expected. The text you typed is committed to the document and appears in both editors when you click away from the field.**

**Comment by bengotow** [comment]
Interesting, looks like the Chrome team has an open issue acknowledging their tests for this are flaky 😅 https://bugs.chromium.org/p/chromium/issues/detail?id=457007&q=IME%20blur&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified. 


If anyone else runs in to this, I assembled a small patch that manually emits the textInput event into the DOM when Chrome ends composition without firing it, and it's resolved the immediate issue in Mailspring: github.com/foundry376/mailspring/commit/134a0e55b80d5a77dbacc4b68c042a36c5fbf3e0.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
