### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by MatthewKosloski** [ianstormtaylor/slate#291]
There appears to be typos in the docs on [this](http://docs.slatejs.org/walkthroughs/applying-custom-formatting.html) page.

**I think the other one is supposed to be for the schema ;)**

![screen shot 2016-09-03 at 11 13 48 pm](https://cloud.githubusercontent.com/assets/1219553/18229005/1c3e3ad0-722c-11e6-8607-8830a7c776c9.png)

![screen shot 2016-09-03 at 11 19 28 pm](https://cloud.githubusercontent.com/assets/1219553/18229018/f1de5e22-722c-11e6-906e-29188a27fd65.png)

**Comment by arekkas** [comment]
You can easily create a PR for the docs, they are located here: https://github.com/ianstormtaylor/slate/tree/master/docs

**Comment by MatthewKosloski** [comment]
Didn't think of doing that, thanks!  [Here](https://github.com/ianstormtaylor/slate/pull/293) it is.

**Comment by ianstormtaylor** [comment]
Thanks!
