### ISSUE TITLE
InsertText with AddMark bug.

### ISSUE THREAD

**Issue by jad-eljerdy** [ianstormtaylor/slate#2913]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

No Marks are being rendered with autoreplace. Text is showing up but not with BOLD mark. No marks are rendered at all.

If you type BEFORE the text manually, the text is bold.

#### What's the expected behavior?

Marks should render.

```javascript
const plugins = [
            AutoReplace({
                trigger: '*',
                before: /(\*{1}(.+?))$/,
                change: (change, e, matches) => {
                    var match = [...matches.before].pop()

                    return change
                        .addMark('bold')
                        .insertText(match)

                }
            }),

        ]
```

Doing this should insert BOLD text. That's not the current behavior. Anyone else experiencing this ?

**Comment by mpkelly** [comment]
It sounds like a bug I was experiencing. See here

https://github.com/ianstormtaylor/slate/pull/2818#issuecomment-516925387

There is a fix in another user's repo which you can build yourself and then install as a local npm package.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
