### ISSUE TITLE
Feature request: Insertion Point size change with 'size' mark

### ISSUE THREAD

**Issue by DrakkenWulf** [ianstormtaylor/slate#2917]
#### Do you want to request a _feature_ or report a _bug_?

Feature request.

#### What's the current behavior?

When changing the size, the Insertion point doesn't change. (The size is recorded in the Selection object, but the insertion drawing piece doesn't consult that.)

#### What's the expected behavior?

More like Google doc's insertion point, as displayed in this video.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12256528/60823607-836d5b00-a16d-11e9-98a5-7fe30d7b37fe.gif)

Note that we would have to 'standardize' that 'size' mark to make this work, or at least flag one of the marks as the 'size' mark somehow.

**Comment by ianstormtaylor** [comment]
The drawing of the cursor is outside our control, so if you need this I think you'd need to ensure that the mark is immediately reflected in the document to get it to change size.
