### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by AlesJiranek** [ianstormtaylor/slate#2919]
Hello,

is there any date when you are going to do new release? We are using slate in our app but we have some problems with editing on android devices. 
Master branch already includes https://github.com/ianstormtaylor/slate/pull/2853 so we hope it could fix at least some of those bugs.

Is there any plan to release it please?

Thank you

**Comment by linonetwo** [comment]
How to install from git if slate is a mono repo? It seems hard to install the latest code if the maintainers don't release the code.
