### ISSUE TITLE
renderAnnotation and renderDecoration not in Plugin type

### ISSUE THREAD

**Issue by linonetwo** [ianstormtaylor/slate#2921]
#### What's the current behavior?

On typescript interface `Plugin`, there is only old `renderMark`, no latest `renderAnnotation` and `renderDecoration`.

#### What's the expected behavior?

Add them to `slate-react`'s index.d.ts.

**Comment by linonetwo** [comment]
And there is no doc about Annotation in `Slate Core` section.

**Comment by brendancarney** [comment]
SlateJS does not maintain the typescript types. They are in a separate project.
