### ISSUE TITLE
Placeholder with long text overflows block width

### ISSUE THREAD

**Issue by danieltorrer** [ianstormtaylor/slate#2922]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
If you add a placeholder with a large string of text, it will go beyond the block width. The width of it should be tied to the block properties. By the way its built it not possible to edit the size via CSS styles.

Fiddle: https://jsfiddle.net/76pukr98/5/
I set the editor to a fixed width. You can type text to see where the line breaks and compare it to the placeholder width.

#### What's the expected behavior?

Placeholder text breaks to match block size

**Comment by ihd-dev** [comment]
You could try style it as follows, i.e. add the style:

> PlaceholderPlugin({
      placeholder:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti assumenda exercitationem saepe iste et? Asperiores facere amet distinctio assumenda eius error, recusandae ut vel atque optio qui ducimus praesentium animi.',
      when: 'isEmpty',
      style: {
      	display: 'inline',
        whiteSpace: 'normal'
      }
    })

**Comment by danieltorrer** [comment]
@ihd-dev  Thanks for your response. I already tried that, you can see it here: https://jsfiddle.net/zLpx4cn8/1/
The issue with this solution is that the cursor is positioned at the end of the dom node.

I think one solution can be to play around with absolute position and adding on top of it the actual input field with a higer z-index. But the current structure of the plugin doesn't allow that AFAIK.

**Comment by johannesbraeunig** [comment]
What about removing the placeholder if the block is selected? I think having `with: 0px` is exactly the "hack" for not displaying the cursor at the end of the line, which is  an issue for longer placeholders.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by Glazy** [comment]
This issue isn't fixed as of v0.59.0, opened a new issue @ #4018
