### ISSUE TITLE
Document about setAnnotation and addAnnotation

### ISSUE THREAD

**Issue by linonetwo** [ianstormtaylor/slate#2924]
#### What's the current behavior?

I `console.log(editor)`, found there is `setAnnotation` `addAnnotation`.

#### What's the expected behavior?

Document what they are, since they are in the example, and many people will try to use them.

**Comment by mrwnmonm** [comment]
Yes, we need some docs about annotations. Also, want to report that the serializer doesn't recognize annotations.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
