### ISSUE TITLE
A renderInline hook isn't triggered when slate is bootstrapped

### ISSUE THREAD

**Issue by aboutlo** [ianstormtaylor/slate#2930]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behaviour?

A `renderInline` hook inside a plugin isn't triggered at the bootstrap. After the bootstrap phase occurs  any Slate change triggers the hook correctly

Here an example that reproduces the issue: 
https://codesandbox.io/s/slate-renderinline-plugin-not-triggered-the-first-time-z0ybv

OS: iOS
browser: Chrome 75
Slate: `0.47.4`
Slate-React: `0.22.4` 

![slate_render_inline_not_triggered_the_first_time](https://user-images.githubusercontent.com/1236268/61289931-7cc09280-a7c2-11e9-89f8-a83d384e6704.gif)

#### What's the expected behaviour?
The `renderInline` hook should be triggered at the bootstrap too. I forced an update via a `useEffect` in the `TestEditor.js`

```js
// WORKAROUND uncomment useEffect to show the correct use case
   useEffect(() => {
     setTimeout(() => {
       setValue(Value.fromJSON(value.toJSON()));
     }, 0);
     // we want to use the effect only once so value isn't a dependency
     // eslint-disable-next-line
   }, [template, data]);

  // "I'm the valid text" doesn't show up because
  // RenderInlinePlugin isn't triggered the first time
```

**Comment by kayandra** [comment]
I can also confirm this. I have temporarily resolve to using marks for now.

**Comment by kayandra** [comment]
I later figured out why links weren't rendering, you should check the schema allows for inline renderings.

**Comment by ianstormtaylor** [comment]
I believe this is due to not setting the inline-ness of a node in the schema, and not a bug per se. It might need better documentation though if someone wants to contribute some. Feel free to ask in our Slack for more help!
