### ISSUE TITLE
Skip null / undefined plugin methods in the editor stack

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#2932]
#### Do you want to request a _feature_ or report a _bug_?

Probably a feature.

#### What's the current behavior?

In `editor.run`, an entry in the plugin stack that’s `undefined` will terminate the middleware stack: https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/controllers/editor.js#L298

This means that if you are passing through props like `onBlur` from a parent component to the editor component, if you don't remove null / undefined props, it will prevent default behavior from happening.

#### What's the expected behavior?

If you pass null / undefined for a plugin method, it should be skipped when going through the plugin stack.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
