### ISSUE TITLE
html deserializer behave unintuitively

### ISSUE THREAD

**Issue by nareshbhatia** [ianstormtaylor/slate#2935]
#### Do you want to request a _feature_ or report a _bug_?

Document/clarify html deserializer's behavior

#### What's the current behavior?

Consider the markup below containing two paragraphs:

```
const htmlContent = `
<p>
  Paragraph 1
  Hello World
</p>

<p>Paragraph 2</p>
`;

const initialValue = html.deserialize(htmlContent);
```

1. When this markup is deserialized, the rules are triggered in the following sequence (console output from the provided example):

```
---> el.tagName: P, block: paragraph
---> el.tagName: , block: undefined
---> el.tagName: , block: undefined
---> el.tagName: P, block: paragraph
---> el.tagName: , block: undefined
```  

The two calls with `el.tagName: P` are understandable, but I cannot explain the three calls with no `tagName`. I suspect they are fired because of line breaks in the markup, but that's not very intuitive. If these are intentional, how should they be handled?

2. The paragraphs are rendered as nested `<p>` and `<span>` tags (following the Slate data model), but that creates an issue with rendering of the first paragraph which has a line break inside the `<p>` tag.

Here's the rendered markup:

![image](https://user-images.githubusercontent.com/1220198/61465703-98ed3c80-a946-11e9-9f20-2c7c4aaeb51c.png)

And here's how it is rendered on screen:

![image](https://user-images.githubusercontent.com/1220198/61465950-0b5e1c80-a947-11e9-977f-969e89e5f0b5.png)

As you can see, paragraph 1 has extra space in the beginning and is broken into two lines. Based on the markup it should be all in one line - white space should be ignored. What is the recommended way to solve this issue?

3. Three paragraphs are rendered instead of two - see the large gap between paragraph 1 and paragraph 2 above. I suspect this is coming from the line break between the two paragraphs in the markup. What is the recommended way to work around this?

Supporting material:

- CodeSandbox reproducing the issue: https://codesandbox.io/s/slate-editor-issue-rktwj
- Slate: 0.47.4, Slate React: 0.22.4, Slate HTML Serializer: 0.8.6, latest Chrome, MacOS

#### What's the expected behavior?

The deserializer should

- not trigger rules with undefined tag names (in the example above, only two rules should be fired with tagName = P)
- render paragraphs with line breaks correctly - leading whitespace and line breaks should be ignored
- line breaks between tags should be ignored

**Comment by brendancarney** [comment]
The serializer uses DOMParser, which sees them as separate nodes. The difference is that the browser follows some rules at _render_ time that doesn't display those. See https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33. 

We may want to consider making the slate HTML serializer follow those rules. (we do something similar for our editor)

**Comment by FarbrorGarbo** [comment]
@brendancarney, would you consider adding a sanitizer flag to the serializier that strips out any characters outside of html <> to fix this issue?

**Comment by nareshbhatia** [comment]
@brendancarney, thanks for the detailed explanation. Are there any libraries that will strip the right amount of whitespace to mimic the browser behavior? You said you do something similar - did you write your own? How difficult is this?

**Comment by brendancarney** [comment]
@FarbrorGarbo I believe it's a little more complicated than that, but open to PRs that address the issue. 

@nareshbhatia I haven't been able to find any libraries, and I'm still researching the best ways. Right now, all we're doing is trimming the white space on block level elements, removing consecutive spaces, and removing empty text nodes.

**Comment by minimaluminium** [comment]
@nareshbhatia Have you made any progress on this issue?

**Comment by nareshbhatia** [comment]
@minimaluminium, I have not made any progress on this. I am currently focused on other aspects of creating an off-the-shelf Slate editor. Here's [my work](https://github.com/nareshbhatia/slate-editor) so far.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
