### ISSUE TITLE
Document Editor handler memoizing

### ISSUE THREAD

**Issue by dminkovsky** [ianstormtaylor/slate#2939]
#### Do you want to request a _feature_ or report a _bug_?

Bug (documentation)

#### What's the current behavior?

I'm very new to Slate, and wrote some code like this:

```js
export default function Test() {
    const [value, setValue] = useState(
        Value.fromJSON(blankEditor),
    );
    const [count, setCount] = useState(0);
    return (
        <div>
            <div onClick={() => setCount(count + 1)}>Add</div>
            <SlateEditor
                value={value}
                onChange={({value}) => {
                    setValue(value);
                    console.log(count);
                }}
                onFocus={(event, editor, next) => {
                    console.log(count);
                    next();
                }}
            />
        </div>
    );
}
```

in the `onFocus` handler, `count` did not update. I spent a lot of time trying to figure out what was wrong, not considering that the handler was being memoized. After isolating the behavior in the above test, I was surprised this was, indeed, the case. I had not seen this mentioned anywhere in the docs. During the course of my debug, as I suspected the handler was being cached, I searched "cache" and "memoize" on [Adding Event Listeners](https://docs.slatejs.org/walkthroughs/adding-event-handlers) and [Editor](https://docs.slatejs.org/slate-react/editor) but didn't find anything.

#### What's the expected behavior?

Would it make sense to document this behavior on pages like [Adding Event Listeners](https://docs.slatejs.org/walkthroughs/adding-event-handlers) and [Editor](https://docs.slatejs.org/slate-react/editor)? I am sorry if I missed something.

**Comment by steida** [comment]
I had the same problem. Handlers are just memoized. Related to https://github.com/ianstormtaylor/slate/issues/2927

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
