### ISSUE TITLE
Select a word without the space after it

### ISSUE THREAD

**Issue by mrwnmonm** [ianstormtaylor/slate#2940]
I think this should have been asked before, but I couldn't find it.

#### What's the current behavior?
When you select a word, the selection automatically includes the space after it. So if you added marks dynamically on the beginning for example, then the user tried to select that word to edit the mark, he won't see it, because the selection will be different.

#### What's the expected behavior?
Select only the word, without the space after it.

**Comment by CameronAckermanSEL** [comment]
To my knowledge, most RTE fields on the web include the space when the word is double clicked. 
Slack:
![image](https://user-images.githubusercontent.com/14242948/63974446-bf33eb00-ca61-11e9-9145-7a08d87c0a48.png)

Github:
![image](https://user-images.githubusercontent.com/14242948/63974462-c6f38f80-ca61-11e9-9b37-b2d2fa9eccbc.png)

Google docs:
![image](https://user-images.githubusercontent.com/14242948/63974505-decb1380-ca61-11e9-976c-87890672edc7.png)

I'd recommend you explore a custom plugin that modifies the onDoubleClick event to change the selection behavior for your editor.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
