### ISSUE TITLE
TypeError: Cannot read property 'equals' of null

### ISSUE THREAD

**Issue by MatthewHerbst** [ianstormtaylor/slate#2942]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

We don't know the exact circumstances, but a user on our website trigged the following error:

```
TypeError: Cannot read property 'equals' of null
```

The entire stacktrace is:

```
TypeError: Cannot read property 'equals' of null
1 File "webpack:///./~/slate-react/lib/slate-react.js" line 4716 col 1 in AfterPlugin
      if (isDraggingInternally && selection.end.offset < target.end.offset && selection.end.path.eq...
2 File "webpack:///./~/slate/lib/slate.js" line 11028 col 1 in value
      var ret = fn.apply(undefined, toConsumableArray(args).concat([controller, next]));
3 File "webpack:///./~/slate-react/lib/slate-react.js" line 5445 col 1 in BeforePlugin
      next();
4 File "webpack:///./~/slate/lib/slate.js" line 11028 col 1 in value
      var ret = fn.apply(undefined, toConsumableArray(args).concat([controller, next]));
5 File "webpack:///./~/slate/lib/slate.js" line 11062 col 1 in value
      return next();
6 File "webpack:///./~/slate-react/lib/slate-react.js" line 6169 col 1 in value
      return (_controller9 = this.controller).run.apply(_controller9, arguments);
7 File "webpack:///./~/slate-react/lib/slate-react.js" line 6056 col 1 in value
      return _this2.run(handler, event);
8 File "webpack:///./~/slate-react/lib/slate-react.js" line 1710 col 1 in value
      this.props.onEvent(handler, event);
9 File "webpack:///./~/slate-react/lib/slate-react.js" line 1384 col 1 in Content
      return _this.onEvent(handler, event);
10 File "webpack:///./~/react-dom/cjs/react-dom.production.min.js" line 14 col 426 in Object.i
      function x(a){for(var b=arguments.length-1,c="https://reactjs.org/docs/error-decoder.html?invaria...
```

Apologies that a reproducing fiddle is not given: we do not know what the user did to cause this, only that it was caused. Happy to provide any information about our schema, etc.

#### What's the expected behavior?

There should be no error.

The specific issue is that [this line](https://github.com/ianstormtaylor/slate/blob/79a2d215713ee55f4f758eaecaa1a8189f804a26/packages/slate-react/src/plugins/dom/after.js#L320) assumes `path` will exist, when clearly there is a scenario where it does not. If it's ok for `path` to not exist I'm happy to submit a PR to check its value first. However, if it's not ok for `path` to not exist then I'm not sure where to start looking to fix this.

**Comment by jmsansan** [comment]
I can reproduce this on chrome by opening dev tools and set "Toggle device toolbar" to on (mobile mode), then I refresh the page containing the editor and write on it.

**Comment by zbeyens** [comment]
```
TypeError: Cannot read property 'equals' of null
    at Point.moveTo
    ...
../../node_modules/slate/lib/slate.es.js.Commands$1.insertBlockAtRange
    ...
../../node_modules/slate/lib/slate.es.js.Commands$6.insertBlock
```

Steps to reproduce:
- Click on an image block with `isVoid=true`
- `editor.insertBlock(obj)`

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
