### ISSUE TITLE
Slate overwriting the default behavior of browser on undo/redo 

### ISSUE THREAD

**Issue by vamshi9** [ianstormtaylor/slate#2943]
#### Do you want to request a _feature_ or report a _bug_?

I would like to report a bug.

#### What's the current behavior?
 When I change something inside the slate editor which is wrapped with form component, and focus out of the editor and execute `undo/redo`, it is doing nothing. However, all the other input boxes, text areas, and content editable divs are working fine. 

Please refer to this sandbox
https://codesandbox.io/s/gallant-mcclintock-qxog3
![code sandbox gif](https://user-images.githubusercontent.com/11611776/61767979-92a60700-ae03-11e9-9e29-a62102c9393d.gif)

#### What's the expected behavior?
How can I make slate editor change along with other inputs in the form component

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
