### ISSUE TITLE
Allow disabling certain parts of core Slate schema

### ISSUE THREAD

**Issue by rkoval** [ianstormtaylor/slate#2949]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

[This normalization rule](https://github.com/ianstormtaylor/slate/blob/dbf6237caf5852215d1c35276f68399adac44093/packages/slate/src/plugins/core.js#L172-L191) is currently preventing certain desired functionality of our editor. We're currently processing markdown syntax characters by removing them and adding appropriate marks to the underlying `text` node (e.g., typing `*hello*` would output "hello" in italics by applying an italic `mark` to a `text` node with content "hello"). However, because of the previously linked rule, the user will continue typing in italicized format because the current selection after adding the closing `*` will still be in the `text` node with the italic `mark`. The solution seems like it would be to just add an empty `text` node at the selection after the closing `*`, but therein lies the clash with the normalization rule. This seems like our issue could be solved by just disabling it, *although I'm unsure of other issues that could have throughout Slate. Please advise if it could cause other issues*.

#### What's the expected behavior?

Allow the ability to customize the underlying core schema by adding some sort of initialization function.

---

If you have specific thoughts on how this should be implemented, I would be more than happy to create a PR; alternatively, I can just wing it and submit a PR for review also. It would need to be supported on the 0.46.x branch though, as we're currently on an older React version that doesn't have everything supported in 0.47.x.

**Comment by rkoval** [comment]
Also, FWIW, this was not an issue on Slate 0.44.x because of the fact that `text` nodes had `leaves`, and I don't think this sort of normalization was enforced at that level. We had the proper behavior whereby empty `text` `leaves` could exist next to other `text` `leaves` with any number of marks.

**Comment by rkoval** [comment]
In looking at this a bit further, I may not need to disable the normalization altogether. I just need to make it so it looks to the `text` node `marks` additionally instead of just looking at the raw contents?

**Comment by CameronAckermanSEL** [comment]
The core schema rules are in slate to enforce the model that it needs in order for all of the core operations to function. Allowing users to arbitrarily disable rules would cause an influx of undesired behavior for them to deal with, and greatly complicate testing and development on the library. I am strongly opposed to this idea.

I will say though that this issue is similar to a defect that was fixed recently where marks cannot be removed if the removal was done at the end of a text line. It was resolved here: https://github.com/ianstormtaylor/slate/pull/2936#issuecomment-514722570

Are you still experiencing this problem?

**Comment by rkoval** [comment]
Ahh yes, this PR may fix it, although we are locked on 0.44.x for the foreseeable future unfortunately. I'll close this issue, as we may just maintain a fork to achieve the desired functionality on 0.44.x.
