### ISSUE TITLE
Inline nodes without text children

### ISSUE THREAD

**Issue by inyono** [ianstormtaylor/slate#295]
First things first: thanks for the great project.

I'm trying to get inline math formulas to work. They are similar to links in the sense that they also have some internal state, namely the LaTeX source. They don't have any underlying text, though. `innerHtml` will be generated by some JavaScript library, [KaTeX](https://github.com/Khan/KaTeX) in my example. Optimally, the inline node should behave as a single character, e. g. when my cursor is right before the formula, pressing right arrow should move the cursor directly after the formula. Instead, the cursor disappears. Furthermore, there is an error thrown when forward deleting before the formula:
```
Could not find a descendant node with key "4ojg"
```
Do you have any idea what the problem might be? I published a [minimal example of the code](https://github.com/inyono/slate-katex), `npm install`, `npm start` should be enough to test things out.

Thanks in advance for any pointers.

**Comment by mull** [comment]
I've implemented this with MathJax. I had the same error as well, I solved it by properly passing down the attributes in my schema.

```js
const SCHEMA = {
  nodes: {
    [CONSTANTS.TYPE_MATHJAX_INLINE]:  props => <Mathjax {...props} />,
  }
}
```

I believe `props` contains a `key` attribute which has to be set on whatever component is rendering your math. Hope that helps!

**Comment by mull** [comment]
On second look I'm not sure if this is any different from what you're doing.

**Comment by inyono** [comment]
Thanks for your answer. Does Mathjax also set `innerHtml`? Or how does MathJax rendering work in your case?

**Comment by mull** [comment]
Yeah MathJax is even worse than Katex :) It reads the formula from innerHTML and then replaces it with SVGs. Horrible horrible framework to work with but we need its features unfortunately

**Comment by inyono** [comment]
Okay, thanks! Maybe I try MathJax, too and try to find the underlying issue with my approach.

**Comment by mull** [comment]
If you don't need features beyond KateX then go with that. MathJax needs a DOM to work.
