### ISSUE TITLE
Firefox Android: All keypresses at start of line are treated as Enter

### ISSUE THREAD

**Issue by Macil** [ianstormtaylor/slate#2951]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

In Firefox Android, at the Slate JS front page rich text demo (https://www.slatejs.org/#/rich-text)
* When you position the cursor at the start of a line, all keypresses (including backspace) are treated as Enter presses that add a newline.
* After a newline is added anywhere, inserting (non-newline) text stops working entirely.

Mobile Chrome doesn't have this specific issue for me.

**Comment by jonathannen** [comment]
This bug is appearing in Firefox desktop too - Confirmed with:
Firefox 68.0.1 (64-bit) OSX

**Comment by jonathannen** [comment]
Just as an addendum - I've been getting this error when using slate-react. Reverting to slate-react 0.22.4 (and the appropriate slate version) fixes this. I'll log over at slate-react too.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
