### ISSUE TITLE
undo: only works with `onMouseDown` and not `onClick`

### ISSUE THREAD

**Issue by montezume** [ianstormtaylor/slate#2954]
#### Summary

When using `editor.undo()`, it doesn't work properly when called through `onClick`. However, it works with `onMouseDown`.

I made a reproduction repo [here](https://github.com/montezume/slate-undo)

Any ideas why this is? 

#### GIFs

With `onClick`

![with onCLick](https://user-images.githubusercontent.com/2425013/62290353-7d635500-b461-11e9-82fd-3b4342ba79c7.gif)

With `onMouseDown`

![with mouse down](https://user-images.githubusercontent.com/2425013/62290363-82c09f80-b461-11e9-9d4d-2b8d086761fa.gif)

I also tried adding `event.preventDefault`, and it had the same behaviour.

**Comment by isubasti** [comment]
`onMouseDown` is called before `onClick`and is the one that move the focus to the button therefore `preventDefault` on `onClick` doesn't really help as the focus is already taken by the button

**Comment by montezume** [comment]
Thanks for the explanation, I'll close this 😄
