### ISSUE TITLE
IE11: Focusing across multiple editors is broken

### ISSUE THREAD

**Issue by jas7457** [ianstormtaylor/slate#2955]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
In IE11, if you are focused in one Editor and try to click to another, the original Editor is blurred three times and the Editor that you click into never gets selected/focused. Other browsers seem to behave differently.

I have attached a video, as jsfiddle does not work with IE11. I clicked in a paragraph in the first editor, and then clicked a paragraph in the second. Both editors lost focus instead of focus being transferred to the second editor.
https://recordit.co/zm9Jssyzvp

#### What's the expected behavior?
Clicking a new editor will focus that editor in IE11 as it does with other browsers.

#### Notes
I have tried to look into this myself and have found the following. There was a commit (https://github.com/ianstormtaylor/slate/commit/e493905f29c19191a836caf6698101af9d54f553#diff-021b2a72cf52cd5e8214d0a035b3ebc9R162) which is the culprit. I've linked the line number which calls blur on the element.

IE11 seems to be the only browser which gets into this if statement, and without calling blur, things seems to work in IE11. I don't know enough about the repercussions of removing/changing this, so I did not want to file a PR myself.

Another thing to note, IE11 seems to be the only browser which still has reference to the Editor for the window.document.activeElement at this point in code, all other tested browsers have the body as the activeElement.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
