### ISSUE TITLE
Trying to recreate Slate

### ISSUE THREAD

**Issue by steida** [ianstormtaylor/slate#2956]
I decided to try to recreate Slate from scratch to learn how it works and how it should work. I started with an empty repository with the best practices I want to leverage. Yarn workspace, TypeScript, React Hooks, properly configured Eslint, etc.

I would like to use https://github.com/steida/slad for discussions about various strategies. For example, the first issue I run over was the React key issue for value object. Should we require a model with unique ids, or can we use WeakMap for object identity-based keys? Also note the value model type, which is fully configurable.

I love Slate. It's the best WYSIWYG editor I know, mainly because of its configurable model. But it's a little bit outdated and this little experiment can move it forward. Let's play.

https://github.com/steida/slad

**Comment by steida** [comment]
@rememberlenny Can you help me to understand what's wrong with this issue? Thank you.

**Comment by sgurenkov** [comment]
+ 100 for using typescript, would be awesome to convert existing slateJS to TS eventually.
One think that comes to my mind on how slateJS can be improved performance wise is converting critical computational parts to WASM.

**Comment by steida** [comment]
@sgurenkov Converting exiting Slate code to fully leverage TypeScript is IMHO impossible without a full rewrite. For example, note how I am using TypeScript generics to describe custom props.

As for performance, I am not aware of any CPU intensive Slate blocker, maybe except modifying the plain JSON model, which is the only advantage of immutablejs as far as I know, but I suppose that would be relevant only for really huge documents. For what I know about WASM, it would not bring measurable performance benefits. But let's see.

**Comment by sgurenkov** [comment]
@steida are you planning on using immutable js as well?

and how are you going to approach building your new project, are you going to mimic the same API that slate provides or the main ones, like render hooks and major editor commands?

**Comment by steida** [comment]
@sgurenkov Check the [repo](https://github.com/steida/slad/blob/master/packages/slad/SladEditor.tsx), I am using plain typed JSON. Immutablejs is all and nice, but it has its own issues.

As for API, I would like to use it as an inspiration. There are many planned changes to Slate itself well described by Ian. There is already renderElement and renderText functions. Check two examples. In first, I am using default implementation and in the second, I delegate CSS rendering to styled-jsx. As for editor commands, I believe in functional transformations, but there are probably some drawback which I need to understand, that's why I started with Slad experiment.

**Comment by steida** [comment]
@ianstormtaylor If you feel uncomfortable with this issue, just tell me and I will move the discussion elsewhere. I just want to help the community and Slate itself of course.

**Comment by schabluk** [comment]
@steida yo, check this out: https://github.com/juliankrispel/zettel

**Comment by steida** [comment]
Probably not interesting for the community.
