### ISSUE TITLE
Cannot read property 'text' of null when deleting an element

### ISSUE THREAD

**Issue by JinJieTan** [ianstormtaylor/slate#2962]
BUG：
### When I delete this unique image
![image](https://user-images.githubusercontent.com/47209029/62606986-dc2c4100-b92f-11e9-9f95-bbe2f78f0d09.png)
DOM： 
![image](https://user-images.githubusercontent.com/47209029/62607041-f5cd8880-b92f-11e9-89e1-bafebf6a49a3.png)

code:
const initialValue = Value.fromJSON({

    document: {
        nodes: [
            {
                object: 'block',
                type: 'paragraph',
                nodes: [
                    {
                        object: 'text',
                        text: '',
                    },
                ],
            },
        ],
    },
})

```
 handleEmoji = (_, code) => {
        this.editor
            .insertInline({ type: 'emoji', data: { code } })
            .moveToStartOfNextText()
            .focus()
    }

    //渲染行内元素
    renderInline = (props, editor, next) => {
        const { attributes, node, isFocused } = props

        switch (node.type) {
            case 'emoji':
                return (
                    <img src={require(`../../../../assets/emoji/emotion/${node.data.get('code')}.png`)}
                        className="emoji" alt={node.data.get('code')}
                        onDrop={e => e.preventDefault()}
                    />
                )
            case 'text':
                return (<span
                    {...attributes}
                    onDrop={e => e.preventDefault()}

                //         className={css`
                //   outline: ${isFocused ? '2px solid blue' : 'none'};
                // `}
                >{node.data.get('code')}</span>
                )
            default:
                return next()
        }
    }
 render() {
        return <Editor
            value={this.state.value}
            onChange={this.onChange}
            onKeyDown={this.keyDown}
            ref={this.ref}
            className="input-message"
            autoFocus={true}
            renderInline={this.renderInline}
            onCopy={this.handleCopy}
            onCut={this.handleCut}
            onPaste={this.handlePaste}
        />
    }
```

**Comment by ldavidpace** [comment]
Do you have a schema to let slate know your emoji is a void. I don't see it in your example. Something like 
```
schema={
  inlines: {
    emoji: {
      isVoid:true
    }
  }
}
```

**Comment by JinJieTan** [comment]
Thank you, although I have found a solution to this problem, your open source project works very well. Thank you very much for being so responsible





------------------ 原始邮件 ------------------
发件人: "ldavidpace"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 凌晨1:21
收件人: "ianstormtaylor/slate"<slate@noreply.github.com>;
抄送: "Peter"<453089136@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ianstormtaylor/slate] Cannot read property 'text' of null whendeleting an element (#2962)




Do you have a schema to let slate know your emoji is a void. I don't see it in your example. Something like
 schema={   inlines: {     emoji: {       isVoid:true     }   } }
