### ISSUE TITLE
incorrect direction of movement cursor in RTL mode

### ISSUE THREAD

**Issue by masihjahangiri** [ianstormtaylor/slate#2963]
When try to move cursor by arrow keyboard key in RTL markdown ("https://www.slatejs.org/#/markdown-preview" address )  it don't move correctly.
For example when press right arrow key, editor cursor move the left (instead of right)!

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by SophiaSaiada** [comment]
@ianstormtaylor 
It still happens, even in the last version, so I've submitted a PR which fixing that :)

**Comment by kode-ninja** [comment]
Still an issue in 0.59.0 - please reopen
