### ISSUE TITLE
Upgrade memoize-one dependency

### ISSUE THREAD

**Issue by feimosi** [ianstormtaylor/slate#2968]
#### Do you want to request a _feature_ or report a _bug_?
Potential bug

#### What's the current behavior?

Installing / Upgrading `slate-react` prints the following warning:
> warning slate-react > memoize-one@4.1.0: New custom equality api does not play well with all equality helpers. Please use v5.x 

#### What's the expected behavior?
Upgrading to `memoize-one@5`

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
