### ISSUE TITLE
Provide a `getInsertionPoint` query

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#2973]
#### Do you want to request a _feature_ or report a _bug_?

Request a feature. (See https://github.com/ianstormtaylor/slate/issues/2865)

#### What's the expected behavior?

At the boundary between two text nodes, or a text and an inline node, we have points that are ambiguous. Should the point be at the end of the preceding node? Or at the beginning of the next node?

Different browsers have different behaviors for their native selections. To avoid edge cases and make things easier for plugin devs and slate-react itself, that point should be normalized consistently. I think the default today is always "end of the preceding node."

Plugins like `slate-sticky-inlines` would like more control over that normalization, so you can edit the edges of nodes. So this should also be customizable.

To solve both these problems, Slate should use and provide a `getInsertionPoint` query. This query would take a point and return a normalized point. Slate would use it internally when normalizing points, so plugins could customize it with their own behavior.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3151
