### ISSUE TITLE
Firefox regressions

### ISSUE THREAD

**Issue by mehdikazi** [ianstormtaylor/slate#2978]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
This was initially reported on this [PR](https://github.com/ianstormtaylor/slate/pull/2236#issuecomment-523004658), but thought it might be helpful to make a new issue for it. 

You can see the following behavior on all the slate examples using Firefox:
1. Pressing arrow left or right does not move the selection.
2. Typing a character makes the selection jump somewhere else in the editor.

Video from PR - https://drive.google.com/file/d/1YcPlKy8PCiHnWIrpKx-3ttxmdGdGw2X-/view

**Comment by jonathannen** [comment]
Confirm this is occurring for me too (GIF below). My workaround at the moment is to use slate-react `0.22.4` which is using slate `0.47.4`.

![Lc6UyRAuP5](https://user-images.githubusercontent.com/49863/63630991-7399cf80-c664-11e9-9fef-b1d7f93dd928.gif)

**Comment by macrozone** [comment]
can also confirm this happens on @react-page: https://github.com/react-page/react-page/issues/720

**Comment by devxom** [comment]
I can also confirm encountered a similar problem. 

System info: MacOS 10.14.6 Firefox 69.0b14

1. The problem appeared after updating:
- **slate-react** from `0.22.7` to `0.22.8` 
- **slate** from `0.47.7` to `0.47.8`

2. The symbolic deletion also broke when selecting a word. After the delete operation, a jump to the beginning of the section occurs. Also, a carriage change occurs when entering characters.

![2019-08-30 12 50 31](https://user-images.githubusercontent.com/2714216/64011773-0cc55c00-cb25-11e9-9822-34e2f36dddec.gif)

![2019-08-30 12 58 03](https://user-images.githubusercontent.com/2714216/64012308-17342580-cb26-11e9-9c6c-ff7a0330533c.gif)

**Comment by kaydelaney** [comment]
Made a PR reverting the changes that introduced the regressions, and (hopefully) also fixing the original issue without causing other problems. Would love some reviews if anyone has the time!
https://github.com/ianstormtaylor/slate/pull/2995
@ianstormtaylor

**Comment by projectLewis** [comment]
Can confirm what jonathannen said in that 0.22.4 which is using slate 0.47.4 are the last working versions in Firefox for me. slate-react - 0.22.7 and slate -0.47.7 as someone else mentioned did not work for me.

**Comment by ruanyl** [comment]
Can confirm the same issue on Firefox after upgrade slate to latest version
