### ISSUE TITLE
Programmatic changes remove the composition visual cue on macos

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#2979]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

A programmatic change to the editor remove the visual cue we usually see on macos when starting a composition.

For example, when typing 'ê', you start with '^' then 'e'. When composition starts, you see the '^' character underlined then the composed letter appear when typing 'e'.

Here's a gif demonstrating the problem:

![http://g.recordit.co/3RxpemJZj6.gif](gif)

[Code Sandbox](https://codesandbox.io/s/slatejs-playground-xmokw)

The problem happens with both firefox and chrome.

#### What's the expected behavior?
The composition visual cue is not really a character. It should not be removed before composition ends. It should only be removed when the selection effectively move or when the composition has finished.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
