### ISSUE TITLE
Determining the block type of the current selection

### ISSUE THREAD

**Issue by katiewoolston** [ianstormtaylor/slate#2981]
I'm adding buttons to allow a user to resize the images they insert, but I need to be able to hide the buttons when an image is not selected.

Is it possible to determine when the current selection is an image block?

**Comment by montezume** [comment]
Have you tried doing something like this?

```js
  const activeBlock =
    (editor.value.blocks.first() && editor.value.blocks.first().type) || '';
```

**Comment by katiewoolston** [comment]
That worked perfectly! Thanks.
I ended up changing the images to be inlines (instead of blocks), but `editor.value.inlines.first()` also works.
