### ISSUE TITLE
HTML content being pasted twice

### ISSUE THREAD

**Issue by moinism** [ianstormtaylor/slate#2988]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?
![twice](https://user-images.githubusercontent.com/2242528/63936985-cd423580-ca7a-11e9-9c1d-e4faaeabaac9.gif)

When HTML content is pasted, it is pasting it twice.

1. Copy some content from a webpage, even a line.
2. https://www.slatejs.org/#/paste-html
3. Paste.

#### What's the expected behavior?

Paste only once.

**Comment by CameronAckermanSEL** [comment]
As far as I can tell, the defect is that the onPaste handler is firing a second time with a plain text paste as if `return next()` was being called to resume the plugin stack after the html is deserialized and inserted
https://jsfiddle.net/1nzto9vd/1/

**Comment by larrywu13535** [comment]
Pasting also doesn't respect line breaks

**Comment by CameronAckermanSEL** [comment]
That's probably related to how insert fragment works

**Comment by eshavrov** [comment]
Hello
Need to change the `onPaste`
```js
  onPaste = (event, editor, next) => {
    event.preventDefault()  // <---- add me

    const transfer = getEventTransfer(event)
    if (transfer.type !== 'html') return next()
    const { document } = serializer.deserialize(transfer.html)
    editor.insertFragment(document)
  }
```

[link](https://github.com/ianstormtaylor/slate/issues/2972)
