### ISSUE TITLE
Feature request: state.document.getNode

### ISSUE THREAD

**Issue by mull** [ianstormtaylor/slate#299]
There's already `state.document.getParent(childKey)`. I see no reason why there shouldn't be a `getNode` as well.

Happy to work on this, but I want to check with you first. I'm thinking you might have omitted this from the current API for a reason. I'm reluctant to pass around `Blocks` myself for some reason, and would rather just pass around the keys. Maybe that's silly?

**Comment by Soreine** [comment]
According to the doc, [`Document` implements the methods from `Node`](http://docs.slatejs.org/reference/models/document.html#node-methods). So you can use [`getDescendant`](http://docs.slatejs.org/reference/models/node.html#getdescendant).

```
state.document.getDescendant(key)
```

**Comment by mull** [comment]
Ouch, my bad!

**Comment by ianstormtaylor** [comment]
Although I do think in the future calling it `getNode` might be nice for terseness.
