### ISSUE TITLE
Selection not committed to the dom when a mark is added when the editor is blurred by clicking outside

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#2997]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Happens on both Firefox and chrome, MacOS

Here's the setup:

- An editor with a plugin that applies a mark when the editor goes out of focus
- Any element that listen on mousedown outside the editor, a button will do nicely
- A button outside the editor that applies the focus back to the editor
- A span outside the editor

[You can find the setup here](https://codesandbox.io/embed/slatejs-playground-q5k99).

How to reproduce:

 - Select some text that cross a mark or a paragraph
 - Press the no-op button 

The selection is moved in the dom.

 - Click on the button that focus the editor

The selection is applied where it has been before it has moved, since in the slate model, the selection was always in the right place (as opposed to the dom)

Clicking on the span element don't show such issues

Here's the gif showing the behaviour when clicking on the span. The grey background is added with the mark:
![A gif showing that cliking on the span work as intended](http://g.recordit.co/NADje1Tu1K.gif)

Here's a gif showing the problematic behaviour when clicking on the button. The grey background is also added using a mark:
![A gif showing the problem with the button](http://g.recordit.co/Q4EqJ4Lzg9.gif)

You can also see that when the focus is regained and the no-op button is clicked again, the selection stays the same as expected, but that's only when loosing the focus the second time.

#### What's the expected behavior?

The expected behaviour is that the selection don't move in the dom while loosing focus.

I would also expect the editor to either have an active selection while being blur. Or at least, don't expose the selection as blurred when in fact there is a selection in the browser.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
