### ISSUE TITLE
On a MAC, a right mouse click selects text

### ISSUE THREAD

**Issue by JinJieTan** [ianstormtaylor/slate#2998]
![image](https://user-images.githubusercontent.com/47209029/64327746-cbd6b700-cffe-11e9-8fc7-926a596df3c5.png)

It made my experience worse

**Comment by Calyhre** [comment]
This is a standard mac os behavior, would you expect something else to happen?

**Comment by JinJieTan** [comment]
Thank you. Then I have no more questions


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Charley DAVID"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月10日(星期二) 下午4:40
收件人:&nbsp;"ianstormtaylor/slate"<slate@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ianstormtaylor/slate] On a MAC, a right mouse click selects text (#2998)




This is a standard mac os behavior, would you expect something else to happen?
