### ISSUE TITLE
Docs do not describe the actual model.

### ISSUE THREAD

**Issue by FabianHertwig** [ianstormtaylor/slate#2999]
Hi there, awesome project first of all!

I found that the docs do not describe the actual model for `Value` and `Decoration`.

# Value
See: https://github.com/ianstormtaylor/slate/blob/master/docs/reference/slate/value.md and https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/value.js

The docs says the properties are:
```javascript
Value({
  document: Document,
  selection: Selection,
  data: Data,
  decorations: List<Decoration>,
})
```
but the default properties are
```javascript
const DEFAULTS = {
  annotations: undefined,
  data: undefined,
  document: undefined,
  selection: undefined,
}
```

# Decoration
See https://github.com/ianstormtaylor/slate/blob/master/docs/reference/slate/decoration.md and https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/decoration.js

The docs says the properties are:
```javascript
Decoration({
  anchor: Point,
  focus: Point,
  mark: Mark,
})
```
but the default properties are
```javascript
const DEFAULTS = {
  type: undefined,
  data: undefined,
  anchor: undefined,
  focus: undefined,
}
```

**Comment by eselkin** [comment]
I think Decoration became Annotation and that's why it has the data and type.

**Comment by Slapbox** [comment]
Decoration and annotation co-exist, though I'm not clear on the purpose/distinction. Unless I'm mistaken, annotations do everything decorations do and then some.

@ianstormtaylor will annotations replace decorations? If not, can you illuminate the purpose of keeping decorations? The changelog seems to imply decorations are on the way out in the long run. 

> Introducing the Annotation model. This is very similar to what _used to be_ stored in value.decorations,

**Comment by ianstormtaylor** [comment]
Annotations are for formatting that span across nodes, like comments. Whereas decorations are for formatting that is dynamically generated based on the content of a node, like syntax highlighting.

**Comment by Slapbox** [comment]
Makes sense! Thanks for the clarification. 

Sorry, I don't want to ask you to explain the whole damn thing, I know you get bombarded, but I'll get the docs on this updated once I'm clear, and I plan to dive into the internals of decorations/annotations regarding #2807 too.

Why is `annotations` a default prop and `decorations` is not. What's the purpose of setting it explicitly as `undefined` explicitly. I assumed for clarity, but in that case I'm not sure why we don't also need, `decorations: undefined`

I also noticed that `annotation.js` has an additional method that `decoration.js` does not called `createMap` which it seems like should be addressed as well. It doesn't seem to be used in the examples and I'm not clear on its usage; maybe very obvious.

----

Would it be best to create a `Annotation.md` that largely duplicates `Decoration.md` or would it make sense to have an `Annotation.md` doc that mentions the few additional concepts that don't apply to Decorations and then links to `Decoration.md` for discussion of the data model? Something like:

> Annotations are for formatting that span across nodes, like comments. Whereas decorations are for formatting that is dynamically generated based on the content of a node, like syntax highlighting.

> Annotation.createMap - Some explanation

> The underlying data model and methods match those used by [Decoration](https://docs.slatejs.org/slate-core/decoration).

**Comment by ianstormtaylor** [comment]
@Slapbox that sounds good to me! 

The differences are mostly due to decorations being a render-time concept. They don't really "exist" in the document, they are generated at render time based on the content of the document. So it wouldn't really make sense to "set" them as a prop. They don't really live in the data model, they are part of the view layer.

Whereas annotations actually part of the data model. They're extremely similar to marks, except that instead of being attached to the individual text nodes, they live at the top level and specify a range that they apply to. This makes more sense for things like comments, where they often span across entire ranges of the text. (But most things that use annotations could be implemented as the low-level marks as a fallback, just slightly less ideally.)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
