### ISSUE TITLE
copied html content inserting extra linebreaks when pasted into rich text sample

### ISSUE THREAD

**Issue by iceskel** [ianstormtaylor/slate#3002]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?
Copy html content found here (bottom right screen)
https://jsfiddle.net/rb3hop6z/
paste into the slatejs rich text editor here https://www.slatejs.org/#/rich-text
it then inserts extra linebreaks
recording here: https://recordit.co/3Nc5MWAkV0

#### What's the expected behavior?

It should not insert any extra linebreaks. Dropbox paper doesn't seem to insert any linebreaks from the copied html content, for example https://recordit.co/GNira6abpD

**Comment by iceskel** [comment]
Apologies, using the onPaste prop from the paste html example does resolve this.

**Comment by nomadus** [comment]
I did not find onPaste property in the paste html example, was it removed? What is the suggested workaround to remove extra line breaks?

**Comment by nomadus** [comment]
onPaste is not available with the paste HTML example, but the issue is still there. Is there a workaround to remove the extra lines when pasting content?
