### ISSUE TITLE
Add mark in loop at absolute position in text

### ISSUE THREAD

**Issue by boehm-e** [ianstormtaylor/slate#3006]
Hi, 
I can add mark :
```javascript
this.editor
.focus()
.moveToRangeOfDocument()
.moveTo(10)
.moveFocusForward(4)
.addMark('bold')
```

but I can't add more than one mark : 
this is not working

```javascript
this.editor
.focus()
.moveToRangeOfDocument()
.moveTo(10)
.moveFocusForward(4)
.addMark('bold')
.moveTo(20)
.moveFocusForward(5)
.addMark('bold')
```

and this is not working too:
```javascript
data.forEach(word => {
  this.editor
  .focus()
  .moveAnchorTo(word.begin)
  .moveFocusTo(word.end)
  .addMark('bold')
})
```

So is there a way to add multiple marks at the same time, or one by one by looping over some data ?
What I would like to do is to add mark at Absolute position in the document.
Thank you :)

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
