### ISSUE TITLE
add `editor.create*` commands

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3008]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Once we are using JSON objects for models, and allowing top-level metadata from #3007 we will need to ensure that when creating or splitting nodes we preserve the right properties, and allow userland to add new properties. 

I think an easy way to do this is to have `editor.create*` commands that are always invoked whenever a new node, annotation, mark, etc. are created.

For example, in core:

```js
const createElement = editor => props => {
  return {
    nodes: [],
    ...props,
  }
}
```

That would create an element. But userland could also override it and define an `id` property for all elements:

```js
const createElement = (editor, fn) => props => {
  return {
    ...fn(props),
    id: uuid.v4(),
  }
}
```

**Comment by thesunny** [comment]
I like this.

Right now, I add timestamps and user_id stamps to track who contributed content and when. I find that once in a while, Slate creates an empty text node that bypasses `insertText` and so I end up with a stamp-less text node that I have to add special handling for. Having access to `create*` would make it easier to ensure that nodes of any type get their required attributes without searching for all the insertion points.

**Comment by ianstormtaylor** [comment]
I think this is actually not how it will work. Realizing that it's very hard to make a guarantee that Slate calls these kinds of methods every time it creates something. Instead, people should override the `editor.apply` logic for operations, where they can edit the operations to include any extra properties they want for each type of object being added—whether it's nodes, marks, etc.
