### ISSUE TITLE
Embeds example reverts text changes when editing the video url after changing text

### ISSUE THREAD

**Issue by kommen** [ianstormtaylor/slate#301]
The Embeds example reverts text changes when editing the video url after changing text.
To reproduce:

1. go to http://slatejs.org/#/embeds?_k=fj5rfy
2. select a word in the text and change it to something else
3. focus the video url text field and type a character

This reverts the change to the text from step 2.

**Comment by ianstormtaylor** [comment]
Thanks for reporting @kommen !
