### ISSUE TITLE
App freezes after upgrade to the latest version

### ISSUE THREAD

**Issue by DanSallau** [ianstormtaylor/slate#3010]
Hi,

First of all i would like to apologise because i know this might be an issue from my end not a bug. But i am confused and desperate, i asked on the slack group yet no reply.

My editor is a replica of the example here https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js and was working fine few months back. I then upgraded all my slate to the latest . Then suddenly,My app freezes when i click the block type keys. Example, when i try to insert ```h1``` tag, it froze at line 291 of the ```onClickBlocks``` function from the link above. The whole app froze, can't close, reload . I have to restart my PC. This happen on all block controls with the exception of ```paragraph```. Pragraph is the only control that works.

However, i noticed that when i insert a paragraph block and going to the second row or line in the editor, The app works fine. The remaining blocks too works, it just doesn't on the first line or row in the editor and clicking one freeze the whole browser tab. Please what am i doing wrong ? Any help would be appreciated.

**Comment by CameronAckermanSEL** [comment]
Hi,

In order to exercise this issue we need a minimum reproduction of it in a jsfiddle or a code sandbox.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
