### ISSUE TITLE
Referencing propTypes at runtime causes inconsistent behavior when using babel-plugin-transform-react-remove-prop-types plugin

### ISSUE THREAD

**Issue by tylerdavis** [ianstormtaylor/slate#3020]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?
In a recent pull request #2855, a change was introduced that references `Content.propTypes` at runtime.

The default babel configuration for rails uses a plugin that strips the definition of propTypes out of all files for production compilation. Referencing propTypes at runtime feels like an anti-pattern which should probably be avoided, since in most cases prop-types is generally considered a dev tool and configured as a dev dependency.

The offending line is https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L542

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
