### ISSUE TITLE
There is an issue when I use Chinese input method to input Chinese characters after underlined characters.

### ISSUE THREAD

**Issue by qhwc2009** [ianstormtaylor/slate#3026]
Steps to reproduce:
1. Select the underline format and enter some underlined content.
2. Open the Pinyin input method, and cancel the underline format, enter some Chinese characters, click Enter

Then you will find that both pinyin and Chinese characters appear, and the pinyin is underlined, the Chinese characters are not underlined, and the pinyin cannot be selected.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
