### ISSUE TITLE
There is a document mistake about the type of the marks

### ISSUE THREAD

**Issue by winrey** [ianstormtaylor/slate#3029]
It says the property of a `Text` named `marks` in [document](https://docs.slatejs.org/slate-core/text) is a `Immutable.List<Mark>,`, while it's actually a `Immutable.Set<Mark>,`.

It cause an error and takes me half an hour to find it.  T^T

Would you please correct it?

**Comment by CameronAckermanSEL** [comment]
Thank you for identifying a problem in the documentation. It would however probably be faster for you to submit a PR to correct the mistake since you have a great deal of insight into it.

Thanks!

**Comment by winrey** [comment]
> Thank you for identifying a problem in the documentation. It would however probably be faster for you to submit a PR to correct the mistake since you have a great deal of insight into it.
> 
> Thanks!

Sorry for unfamiliar with the open-source cooperation and thanks for your encourage!

**Comment by thesunny** [comment]
Thanks @winrey 

Merged the PR

**Comment by winrey** [comment]
@thesunny Thanks for review. Have a good day!
