### ISSUE TITLE
Cursor position is incorrect in Firefox

### ISSUE THREAD

**Issue by tgfischer** [ianstormtaylor/slate#3037]
### What's the current behavior?
Using any of the examples with Firefox (e.g. https://www.slatejs.org/#/rich-text), the cursor position is incorrect as you type. After you type the first character, it moves the cursor back to the beginning of the line, and all proceeding characters are added behind the first. The cursor stays at the beginning of the line.

This happens in Firefox 69.0.1, but not Chrome 77.0.3865.90

#### Firefox 69.0.1 (64-bit)
https://i.imgur.com/zkeH6lv.mp4

#### Chrome 77.0.3865.90 (64-bit)
https://i.imgur.com/DStBSIk.mp4

### What's the expected behavior?
The cursor position should not change, and have the same behaviour across supported browsers

### Update
I can't seem to reproduce on the main website anymore (not sure if it got updated?), but I can still reproduce the exact same issue with an editor I made in React

**Comment by dmitru** [comment]
Experiencing the same issue here. 🤔

**Comment by klehmann** [comment]
Seems to be fixed in slate-react 0.22.9 with this fix: 6d637f37a23714634a72a3989f5cf4855573c28e

**Comment by DanielHara** [comment]
> Seems to be fixed in slate-react 0.22.9 with this change: [6d637f3](https://github.com/ianstormtaylor/slate/commit/6d637f37a23714634a72a3989f5cf4855573c28e)

Upgrading to slate-react 0.22.9 solved this issue for me.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
