### ISSUE TITLE
Firefox spell checker mark disappears (is not consistent).

### ISSUE THREAD

**Issue by Azlbert** [ianstormtaylor/slate#3039]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?

The spell checker mark disappears. It might appear latter, but I could not figure out how exactly. It was not happening before the new release "slate-react@0.22.9 ".

- Ubuntu 18.04.3 LTS
- Firefox 69.0.1
- slate@0.47.8
- slate-react@0.22.9

![Slatejs bug firefox 69](https://media.giphy.com/media/hTgg9y0hQjIJ3jYSjA/giphy.gif)

#### What's the expected behavior?

Spell checker mark should not disappears.

Chromium 77.0.3865.90 does not have the issue, the spell checker is 'glitching' as always but never disappears.

**Comment by macrozone** [comment]
@Azlbert yes, this has been fixed: https://github.com/ianstormtaylor/slate/pull/2995

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
