### ISSUE TITLE
Erronous text duplication in examples when breaking the paragraph with cursor within formatted part.

### ISSUE THREAD

**Issue by rafalp** [ianstormtaylor/slate#304]
Steps to reproduce:
1. Go to http://slatejs.org/
2. Place cursor before end of any of inline-styled bits of text, eg. `|rich` or `mu|ch`
3. Break paragraph with enter key.
4. Enter new character. This will result in inline-styled bit after cursor being duplicated in addition to your character, ergo if "a" was pressed, this will produce `arich` or `ach` respectively.

I'm using Chrome 53, but I've confirmed the issue on two other machines and for all examples.

**Comment by ianstormtaylor** [comment]
Shoot, thanks for reporting @rafalp ! I think this is related to the latest transforms refactor. Looking into it!

**Comment by ianstormtaylor** [comment]
Fixed in `0.15.0`!
