### ISSUE TITLE
move{Point}Forward and move{Point}Backward behave unexpectedly when moving across Text nodes.

### ISSUE THREAD

**Issue by nz-chris** [ianstormtaylor/slate#3042]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug.
#### What’s the current behavior?
When using these two commands...
- https://docs.slatejs.org/slate-core/commands#move-point-backward
- https://docs.slatejs.org/slate-core/commands#move-point-forward

...you will see unexpected behaviour if the argument `n` has a value such that `{Point}` will be expected to move from one `Text` to another.
In this example video, I am on a fork of the latest master branch, and the only change I have made is adding a button to the toolbar in the rich text example that does `this.editor.moveForward(3)` on click. I use this button twice. The first time is unexpected behaviour (the cursor mover more than 3 characters) because the selection movement crosses a border between two `Text` nodes, and the second time is expected behaviour because the selection movement stays within a single `Text`.
![slate bug](https://user-images.githubusercontent.com/37297133/65842889-1d1e6000-e38b-11e9-97af-0757bdbfcdbd.gif)
#### What’s the expected behavior?
The result of the command moves {Point} a distance of `n` characters in the appropriate direction.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
