### ISSUE TITLE
What is the appropriate way to set a new value? and how to trigger a rerender after doing so?

### ISSUE THREAD

**Issue by mrwnmonm** [ianstormtaylor/slate#3045]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
Setting a new value using `setState({value})` doesn't trigger a render for the custom blocks.  
And `editor.setValue()` is not definded in slate 0.47.3

#### What's the expected behavior?
```js
ParagraphNode = (props) => {
    return (
      <p {...props.attributes} className={this.state.hoveredParagraph.toString() == props.attributes["data-key"].toString() ? "paragraph" : "paragraph dim"} onMouseDown={()=>{this.setState({"hoveredParagraph": props.attributes["data-key"].toString()})}}>
        {props.children}
      </p>
    )
}

renderBlock = (props, editor, next) => {
    switch (props.node.type) {
      case 'paragraph':
        return <this.ParagraphNode {...props} />
      default:
        return next()
   }
}

render(){
  return(
   <Slate.Editor
     ref={this.ref}
     value={this.state.value}
     onChange={this.onChange}
     renderEditor={this.renderEditor}
     renderBlock={this.renderBlock}
     renderMark={this.renderMark}
     spellCheck={true}
    />  
  )
}
```
With the code above, if I did the following anywhere I expect that the first paragraph to not have the `dim` class.
```js
this.setState({hoveredParagraph: this.ref.current.value.document.nodes.get(0).get("key").toString(), value: newValue})
```
But all paragraphs stay dimmed. Also using `editor.setValue()` doesn't work, because it is undefined.

**Comment by ryanmitts** [comment]
Do you have a solution for this?

**Comment by hitochan777** [comment]
@ryanmitts You can take a look at the discussion on Slack (https://slate-js.slack.com/archives/C1RH7AXSS/p1570067154369600?thread_ts=1570060638.365800&cid=C1RH7AXSS).
