### ISSUE TITLE
Can't backspace a list if it's the only element in the editor

### ISSUE THREAD

**Issue by 11** [ianstormtaylor/slate#3048]
#### Do you want to request a _feature_ or report a _bug_?
<b>Bug</b>

#### What's the current behavior?

List elements cannot be removed with backspacing when they're the only element in the editor. This list elements can only be removed when by clicking the numbered list icon

The error is currently active in the `rich text` demo: https://www.slatejs.org/#/rich-text

![backspace-broken](https://user-images.githubusercontent.com/6809522/66238672-06974200-e6c6-11e9-8272-88c33e49adfd.gif)

macOS Mojave 10.14.6 - Google Chrome 
Google Chrome | 77.0.3865.90 (Official Build) (64-bit)

#### What's the expected behavior?
Expected behavior is for backspacing to also remove the list

**Comment by CameronAckermanSEL** [comment]
The more precise description of the desired behavior is "backspace converts a list item to the default block type when the list item is empty or the cursor is at the start of the list item"

The absence of this behavior is not a defect. This is a custom behavior that must be implemented by the developer.

**Comment by 11** [comment]
Hi @CameronAckermanSEL. I appreciate the response. Personally, I feel like this is a somewhat expected behavior and it would be nice to have in the demo (as well as have this question answered for future searches). I'm more than happy to create a PR with the change, but I don't think the documentation does a great job explaining how to catch this error. 

From what I was able to gather before I posted this question, it seems like adding a `normalize` function in the editor's schema to account for this `error` will do the trick, but it's not entirely obvious which error to check for - or if that is at all the correct approach. If I had to guess, I would check for `parent_object_invalid` and then  correct it by adding an empty paragraph node when this occurs? 

Would you mind going into a little more detail about detecting this error and how to correct it?

**Comment by CameronAckermanSEL** [comment]
Hey @11, this rich text editor example is not meant to be fully featured and usable as a RTE out of the box. It is meant to provide enough of the basics for how to interact with slate for you to be successful in implementing your own editor with your own custom behaviors.

One could also make the argument that this example should do things like handle pasting, or list item merging, or anything of that nature that are also idiomatic with modern RTEs. The problem then is that the examples become harder to maintain, more subject to bugs, and also conversations like this where people disagree with the behaviors of the example.

On those grounds, I would disagree with a PR that adds this clean up functionality. 

To your specific question on how you would detect this condition yourself, my recommendation would be to boil this down to the interactions you're having with the editor and what you expect it to do.

The preconditions are: 

1. You are hitting the backspace key while
2. Your selection is collapsed at the start of
3. A list item

And your output is:

You want the list item to become a paragraph block

This sounds like an onKeyDown event to me that runs `editor.setBlock('paragraph')` when the above conditions are true.

You might also look for a [plugin ](https://docs.slatejs.org/general/plugins) that provides list editing behaviors.

**Comment by jonocairns** [comment]
As an example for the idea above by @cameracker 

```
  const handleBackspace: React.KeyboardEventHandler<HTMLDivElement> = (event) => {
    if (event.key === 'Backspace') {
      const {selection} = editor;
      if (
        selection &&
        selection?.focus.offset === 0 &&
        selection?.anchor.offset === 0 &&
        Range.isCollapsed(selection)
      ) {
        const node = editor.children[selection.anchor.path[0]];
        if ((node as CustomElement)?.type === 'list') {
          toggleBlock(editor, 'list');
        }
      }
    }
  };
```

```

<Editable
      ...otherProps
      onKeyDown={handleBackspace}
/>

```

**Comment by jonocairns** [comment]
I also wrote a plugin to do the same thing.

```
import {CustomElement, SlateEditor} from './Slate';
import {Range} from 'slate';
import {toggleBlock} from './helpers/blockHelpers';

export const withDeleteEmptyBlock = (editor: SlateEditor) => {
  const {deleteBackward} = editor;

  editor.deleteBackward = (unit) => {
    const {selection} = editor;
    if (selection && selection.focus.offset === 0 && selection.anchor.offset === 0 && Range.isCollapsed(selection)) {
      const node = editor.children[selection.anchor.path[0]];
      if ((node as CustomElement)?.type === 'list') {
        toggleBlock(editor, 'list');
      }
    } else {
      deleteBackward(unit);
    }
  };

  return editor;
};
```

usage
```
  const [editor] = useState(withDeleteEmptyBlock(withHistory(withReact(createEditor()))));
```
