### ISSUE TITLE
In Safari, text input at the end of an inline is placed inside the inline

### ISSUE THREAD

**Issue by dminkovsky** [ianstormtaylor/slate#3052]
#### Do you want to request a _feature_ or report a _bug_?

Bug (inconsistent behavior)

#### What's the current behavior?

In Safari (desktop and mobile), if the cursor is positioned at the end of an inline, and you type some text, that text is inserted into the inline.

In Chrome and Firefox, the text in inserted after the inline.

#### What's the expected behavior?

I think the current Chrome/Firefox behavior is correct: users expect that if the cursor is at the end of an inline (say, a link), text they type should be inserted after the inline. 

It appears that some form of this inconsistency has existed since #1492.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3151.
