### ISSUE TITLE
Use `range.getClientRects()` on iOS to scroll into view

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3053]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Currently, on iOS we do not scroll into view because `range.getBoundingClientRect()` returned incorrect values on iOS.

We short-circuit return here to skip the scrollIntoView https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate-react/src/utils/scroll-to-selection.js

#### What's the expected behavior?

We should scroll into view on iOS. Nicolas Torres offered an alternative.

```js
  myBoundingClientRect = range => {
    const rects = range.getClientRects();
    let rect = { top: 0, right: 0, bottom: 0, left: 0 };

    if (rects.length) {
      const { top, right, bottom, left } = rects[0];

      rects.forEach(rect => {
        if (rect.height !== 0 || rect.width !== 0) {
          rect = {
            top: Math.min(top, rect.top),
            right: Math.max(right, rect.right),
            bottom: Math.max(bottom, rect.bottom),
            left: Math.min(left, rect.left)
          };
        }
      });
    }
    return {
      ...rect,
      width: rect.right - rect.left,
      height: rect.bottom - rect.top
    };
  };
```

We should test this including on older versions of Safari on iOS to ensure that it works. If it does, replace with this new code.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
