### ISSUE TITLE
Firefox does not show blinking cursor without content

### ISSUE THREAD

**Issue by comatory** [ianstormtaylor/slate#3054]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

When using latest Firefox browser, I will not get blinking cursor in the editor until I start typing (or when there is already some content present).

(JSFiddle template is "broken' for me so posting codesandbox link instead)

- https://codesandbox.io/s/slatejs-firefox-cursor-problem-ofb7t
- ![](https://i.imgur.com/IrGP4Jv.gif)
- MacOS 10.14.5, Firefox 69.0.1, `slate@0.45.1`, `slate-react@0.21.24`, `react@15.4.2`, `react-dom@15.4.2`

#### What's the expected behavior?

The editor should show blinking cursor even when not having any content, like Chrome and Safari does (tested). **If I upgrade only react & react-dom to at least version 16 it works**. However for my use case, I can't really upgrade any of the listed dependencies.

*NOTE*: If anyone could point me to relevant issue or MR, it'd be very helpful. I don't mind creating a patch for my usage as long as it works with my dependencies. Since this is tied to React my suspicion is it'd have to do maybe with `slate-react` library?

**Comment by comatory** [comment]
Bumping this. I can't figure this one out and I'm not sure if it is happening to me locally or not. Seems like something a lot of ppl will experience on Firefox browsers.

Could someone point me maybe to some PR or part of code where I could try and figure it out? Thanks.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
