### ISSUE TITLE
Loosing focus after changes to DOM in `renderEditor`

### ISSUE THREAD

**Issue by Knorrke** [ianstormtaylor/slate#3057]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
When `renderEditor` changes the DOM structure, slate looses the current selection.

E.g. the following linter example would break after typing `/` somewhere
```js
  renderEditor(props, editor, next) {
    const children = next();
    const { text } = editor.value.document;

    if (text.includes("/")) {
      return <div style={{ backgroundColor: "red" }}>{children}</div>;
    }
    return children;
  }
```
- CodeSandbox:  https://codesandbox.io/s/slatejs-cursor-rendereditor-oi8nh Type `/` somewhere in the text to trigger the linter plugin
- Recording: ![slate-issue](https://user-images.githubusercontent.com/11499926/66560130-03cd9e80-eb57-11e9-9d94-31ffe554e096.gif)
- OS: recorded on Ubuntu 18.04, additionally tested on Win10
- Browser: recording on Firefox v69, additionally tested on Chrome v77 (on Chrome, selection jumps to the beginning)
- Slate version: v47.8.
#### What's the expected behavior?
Courser position should still be the same after DOM change in `renderEditor`.

**Comment by Knorrke** [comment]
Interestingly this works with the versions:
```
    "slate": "0.46.1",
    "slate-react": "0.21.24"
```
https://codesandbox.io/s/slatejs-cursor-rendereditor-c4ol3

**Comment by v4dkou** [comment]
Tested on Firefox Developer Edition 71.0, same problem.

 @Knorrke Thanks a lot for the workaround!

**Comment by Jay0328** [comment]
same problem on
```
"slate": "0.47.9",
"slate-react": "0.22.10"
```

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by Knorrke** [comment]
Thanks, that PR is amazing! Will check out 0.50 soon and let you know if the issue persists :-)
