### ISSUE TITLE
Markdown example - Lists - Could not find a descendant node ..

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#306]
What a fantastic editor you got here @ianstormtaylor, congrats and thanks!
I found a bug in the markdown example. Try adding a list by starting lines with '-'. Then try to remove the list.

<img width="703" alt="screen" src="https://cloud.githubusercontent.com/assets/4349324/18479366/fa812a0a-79d4-11e6-8a2b-7ea157d933f6.png">

**Comment by ianstormtaylor** [comment]
Hey @bkniffler, really glad you like it 😄 

Sorry about that, looks like a regression from the latest big refactoring of transforms in `0.14` on the road to collaborative editing! Just releasing a patch fix for it now!
