### ISSUE TITLE
slate-react assumes PlaceholderPlugin exists

### ISSUE THREAD

**Issue by marianoguerra** [ianstormtaylor/slate#3061]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

slate-react 0.22.9 fails to load because it assumes PlaceholderPlugin is loaded

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/react/index.js#L4

Reproduction: https://marianoguerra.github.io/bugs/slate-placeholder-plugin/index.html 

Following instructions from https://github.com/ianstormtaylor/slate/blob/1aa1783c9c4f7d56a4836c3060194df9e6ac895f/docs/walkthroughs/using-the-bundled-source.md

Trying to load slate-react-placeholder fails too because in the compiled version it exports SlateReactPlaceholder and not PlaceholderPlugin: https://unpkg.com/slate-react-placeholder@0.2.8/dist/slate-react-placeholder.js

Fails on Chrome 77.0.3865.120 on Linux and Firefox Nightly on Linux but it's not a browser issue.

Versions:

* slate 0.47.8
* slate-react 0.22.9

#### What's the expected behavior?

The example loads and renders the editor, instead if fails with an error "TypeError: PlaceholderPlugin is not a function"

**Comment by marianoguerra** [comment]
Forgot to mention, the example works if slate-react is 0.22.8 instead of 0.22.9

here's the same example that loads with 0.22.8: https://marianoguerra.github.io/bugs/slate-placeholder-plugin/works.html

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
