### ISSUE TITLE
`set_annotation` does not works correctly

### ISSUE THREAD

**Issue by cudr** [ianstormtaylor/slate#3063]
#### Do you want to request a _feature_ or report a _bug_?
Bug?

#### What's the current behavior?
Looks like `set_annotation` operation does not applies correctly

@ianstormtaylor, this is a bug?

repro: https://codesandbox.io/s/divine-lake-l77re?fontsize=14

#### What's the expected behavior?
`set_annotation` operation does change annotation when applied to editor

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
