### ISSUE TITLE
Consider adding composition state to `Value`

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3065]
#### Do you want to request a _feature_ or report a _bug_?

Change the implementation of composition such that:

- Whether we are in a composition is stored in `Value`
- If we are in a composition, any changes to the `Value.document` are not rendered to the DOM
- If we are in a composition, any changes to the `Value.selection` do not modify the selection in the DOM

#### What's the current behavior?

Currently, there is no way to commit a change into Slate's Value without also causing it to render to the DOM and/or affecting the selection

#### What's the expected behavior?

The idea is that we add something like `isComposing` to Value and use that with `shouldComponentUpdate` to prevent rendering to the DOM or affecting the selection during a composition.

Ultimately, what this allows us to do is to continually update the current state of Value such that it accurately reflects what's in the DOM. Currently, we handle this by delaying a change to the Value until we are ready to update the DOM. But this causes a bunch of issues of having to track the DOM state.

For example, consider in Android that a user is in a composition to type "world" after "Hello".

So he types, "Hello world". At the point where he finishes typing world, Slate's Value only reflect "Hello ". Then, let's say the user decides to hit enter. We have a bunch of problems to worry about now. The first is that we need to reconcile the "world" from the DOM. Then we have to determine the position of the cursor from the DOM. We then have to set the Slate's value to reflect the change so that we get "Hello world". Then we need to call `splitBlock`.

This back-tracing of history to pull in the "world" and then calling `splitBlock` with the appropriate selection means we are handling multiple issues at once and adds unnecessary complexity. We also can't confirm that things are going well until we hit `enter`. But what if we hit `space` or punctuation which causes the composition to end? What if the user moves the selection to another world which does NOT end the composition in all cases. These all might have different flows where we have to reconcile from the DOM and then do something.

By adding an `isComposing` value, the issue breaks down into more manageable units of action. So when they start composing "world", we type "w". Slate's value now reflects "Hello w" but because `isComposing=true` this doesn't get rendered to the DOM so it doesn't break the composition. Then user types "o" and we get "Hello wo" and all the way until we end up with "Hello world". Now when the user hits enter, it's easy to know by looking at the Slate value that we've got everything right. We now just handle the `splitBlock` with `isComposing` set to false and everything renders.

**Comment by gracicot** [comment]
I was trying part of this concept in my fork: preventing re-render of the DOM while compositing. The small test was successful in the sense that it fixed the two issue I had introduced in #3023.

I don't think we can apply a position to the cursor without breaking composition in some corner cases. Having the value `isComposing` (either in the slate value or as a query) to prevent applying things to the DOM might be required if we want to keep the value up to date on android.

**Comment by ianstormtaylor** [comment]
In the latest version of Slate this is solved by allowing plugins to augment the editor how they please, so one could add an `editor.isComposing` flag if it needed. But I think in core we don't need this flag so it should be left to plugins instead if they really need it.
