### ISSUE TITLE
Crash upon initial click if Shift+RightArrow held down

### ISSUE THREAD

**Issue by jankurianski** [ianstormtaylor/slate#3066]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

![image](https://i.imgur.com/DqPXBF3.gif)

1. Open https://www.slatejs.org/#/plain-text
2. Click on the grey area of the document to blur the text editor.
3. Hold down `Shift` and `Right Arrow` keys.
4. While continuing to hold down the keys, click on any part of the text in the text editor.
5. A crash occurs at this line because `startText` is null:
https://github.com/ianstormtaylor/slate/blob/6269fcaa7168d6a7b79a62b286fd0d0316819c8f/packages/slate-react/src/plugins/dom/after.js#L570

This crash occurs in Chrome 77 and Firefox 69.  I'm using Windows 10.  The crash does not occur on Edge 18 or Safari 12.1. 

#### What's the expected behavior?

Selection starts at the click position and then continues expanding right while `Shift` and `Right Arrow` is held.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by jankurianski** [comment]
I can confirm this bug is fixed by #3093 - no longer reproduces in Chrome or Firefox.  Thanks Ian.
