### ISSUE TITLE
Drag and drop a fragment: Cannot read property 'size' of null (path)

### ISSUE THREAD

**Issue by zbeyens** [ianstormtaylor/slate#3068]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

```
"slate": "0.47.8",
"slate-react": "0.22.8",
```

When you drag and drop a void block at the same position, `path` is null and the block moves to at the start of the document

![1UCdn6GFTN](https://user-images.githubusercontent.com/19695832/66859524-cc625600-ef8b-11e9-8d3b-057c23e98515.gif)

Error:

![image](https://user-images.githubusercontent.com/19695832/66860262-26175000-ef8d-11e9-9952-55fb0d8b35ba.png)

#### What's the expected behavior?

The block should stay at the same place

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
