### ISSUE TITLE
An option to turn on/off mark sticky edges.

### ISSUE THREAD

**Issue by crow1796** [ianstormtaylor/slate#3069]
#### Do you want to request a _feature_ or report a _bug_?
_Feature_

#### What's the current behavior?
It automatically includes the characters at the end of marks
![](https://media.giphy.com/media/ghTHjlrfaf6OYuZrqj/giphy.gif)

#### What's the expected behavior?
Should have an option to turn on/off sticky edges on marks, particularly at the end of marks.

**Comment by ianstormtaylor** [comment]
This is something that should be handled in a plugin instead of in Slate's core. In core we'll be aiming for https://github.com/ianstormtaylor/slate/issues/3151
