### ISSUE TITLE
Suggestion: rename 'lib' to 'src', 'dist' to 'lib'

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#307]
Hey, 
Its been a convention with a lot of react projects to have a 'src' dir for uncompiled es6/7 jsx code and 'lib' for the compiled counterpart, and maybe a 'dist' for bundled js files. This is a problem when I maintain a fork of this project that I integrate into my existing gulp/babel workflow, maybe this might be a problem for others too?

This is just a suggestion and I would totally understand if you prefer your own style in this matter. Is this something you'd accept as a PR?

**Comment by ianstormtaylor** [comment]
Hey, yeah it does seem like the convention for transpiled stuff is `src` more often than `lib`. I think I've just kept my pre-babel naming scheme so far. But I'd be down to accept a PR that fixes this!

Do you think `dist/*` should be un-gitignored in that case? For easier grabbing of files.

**Comment by bkniffler** [comment]
I created a PR https://github.com/ianstormtaylor/slate/pull/314/files
I'd suggest to keep lib and dist ignored for now. It might be handy to grab dist files directly, but since most people will use the npm package directly, I don't see too much need.

We can always reconsider as soon as actual dist package bundling is happening, and/or also consider using cdnjs (like https://cdnjs.com/libraries/react-router).

**Comment by ianstormtaylor** [comment]
Done, thanks @bkniffler !
