### ISSUE TITLE
Mentions functionality errors.

### ISSUE THREAD

**Issue by blindibrasil** [ianstormtaylor/slate#3071]
#### Do you want to request a _feature_ or report a _bug_?
_error_

Text editor code:
[https://gist.github.com/blindibrasil/0823834ba65b87d89239ab2497592355](https://gist.github.com/blindibrasil/0823834ba65b87d89239ab2497592355
)

#### What is the current behavior?
I am trying to implement the mentions option in my editor, but I am experiencing some issues with this functionality.

**Problems:**

**1 -** When using the code that is in the documentation, I come across the following problem;
```html
Unhandled Rejection (TypeError): Cannot read property 'getBoundingClientRect' of null;
```

![Captura de tela de 2019-10-16 15-56-50](https://user-images.githubusercontent.com/47512798/66951330-7f848b00-f030-11e9-92f0-82603a3f3f0d.png)

**2 -** Trying to get around the problem I commented the line in question that was giving error, leaving as follows:
```html
// const anchorRect = anchorSelector.getBoundingClientRect ();

      setPosition ({
        top: window.pageYOffset,
        left: window.pageXOffset,
      });
```
That way I was able to access my editor correctly, but other problems arose. When you type @ and type another letter to appear the mentions suggestions, these two errors happen:

![Captura de tela de 2019-10-16 16-01-14](https://user-images.githubusercontent.com/47512798/66951495-e1dd8b80-f030-11e9-9c7e-51b6b727e2ca.png)

**2.1 -** The suggestions screen is in the corner of the screen.
**2.2 -** And the second mistake is this: I have tried to correct in several ways but I still can not.
 Warning: State updates from useState () and useReducer () Hooks don't support the second callback argument. To perform a side effect after rendering, declare it in the body component with useEffect ().
I believe it may be coming from the onChange function;

**3 -** Once in the suggestion popup nothing happens, if I double click it mentions the text correctly, but gives another error in the console identical to the one mentioned in point 2.2, and does not close the suggestion popup. 
![Captura de tela de 2019-10-16 16-07-30](https://user-images.githubusercontent.com/47512798/66951615-2e28cb80-f031-11e9-8550-13bd0fdbf1f2.png)

And if you click on the popup again a new error appears.
```html
TypeError: Cannot read property 'length' of null
```

![Captura de tela de 2019-10-16 16-09-25](https://user-images.githubusercontent.com/47512798/66951556-0174b400-f031-11e9-88c9-da44e4dffdc1.png)

- Info System
Ubuntu
Chromium Version 77.0.3865.90 (Official Version) snap 64-bit
Slate 0.47.8

#### What is the expected behavior?

The expected behavior is when typing @ and writing, pop up the suggestions popup to be inserted into the text and after clicking once the popup disappears.

Thank you very much to everyone on the Slate team.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
