### ISSUE TITLE
Deleting using holding backspace in editor's last block leads to invalid key/path error

### ISSUE THREAD

**Issue by david-sabata** [ianstormtaylor/slate#3073]
#### Do you want to request a _feature_ or report a _bug_?
Bug :bug: 

#### What's the current behavior?
Reproducible in the example editor, e.g. https://www.slatejs.org/#/rich-text (currently 0.47.8)

1. Put the cursor anywhere to the last block of editor (the phrase "Try it out yourself!")
2. Press and hold backspace
3. The content gets deleted, but when the cursor reaches the beginning of the block, it jumps to the beginning of the whole editor

Other observations:
- When running locally, there's a console warning ``A point's `path` or `key` invalid and was reset!``
- It seems to only be happening on the last block of the editor
- If there's an inline node within the block, the cursor jumps right after deleting that node, leaving beginning of the block intact

Video :arrow_down: (I selected some text, but it doesn't seem to be relevant)
https://www.loom.com/share/ef0775aea2ea4f31a7fafc72b16c496c

#### What's the expected behavior?
The cursor continues deleting current block and then continues to the block above, as it would in a regular text editor

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
