### ISSUE TITLE
annotation.focus.path and annotation.anchor.path  from props in renderAnnotation is empty

### ISSUE THREAD

**Issue by cudr** [ianstormtaylor/slate#3074]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Looks like paths  from props.annotation in renderAnnotation is
inconsistent with annotation, which selected directly from editor value

Repro: https://codesandbox.io/s/async-hooks-xqm6e?fontsize=14

If annotation is taken from editor value, correct path is obtained.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
