### ISSUE TITLE
How to make the inserted image cursor stay at the bottom

### ISSUE THREAD

**Issue by JinJieTan** [ianstormtaylor/slate#3078]
怎样让插入的图片光标停留在最下面

How to make the inserted image cursor stay at the bottom

The default is now to insert at the top of the image  When there is no text behind me

现在默认是插入在图片后面的最上方 当我后面没有文字的时候

**Comment by JinJieTan** [comment]
Or how to change the style of the cursor?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by JinJieTan** [comment]
thank you , slate is a very good library&nbsp;


If there's another chance&nbsp;, i will still use slate in my production !&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ian Storm Taylor"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 中午11:29
收件人:&nbsp;"ianstormtaylor/slate"<slate@noreply.github.com&gt;;
抄送： &nbsp;“ Peter” <453089136@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题： &nbsp;Re：[ianstormtaylor / slate]如何使插入的图像光标停留在底部（＃3078）




我相信这可以通过＃3093来解决，它已经改变了Slate中的许多逻辑，slate-react尤其是。我将结束这一问题，但与往常一样，如果您仍然遇到新问题，请随时打开。感谢您的理解。
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
