### ISSUE TITLE
Cursor absolute position

### ISSUE THREAD

**Issue by podviaznikov** [ianstormtaylor/slate#308]
What would be the best way to get cursor/caret absolute position in the viewport?

Basically to implement something like Medium when you select new line you will see toolbox popup on the left (to insert image, video etc)

**Comment by ianstormtaylor** [comment]
Hey @podviaznikov!

Depending on what exactly you're looking for there are two cases:

1. Positioning something relative to the cursor itself. For a good example of this, check out the built-in [hovering menu example](https://github.com/ianstormtaylor/slate/blob/master/examples/hovering-menu/index.js).

2. Positioning something relative to the block the cursor is currently in. This sounds like what you're talking about with the Medium editor. In this case, you'd probably want to add a component in your React tree at the same level as the Slate editor, and pass in the same `state={state}` object. And then inside that component, you'd look for the currently selected block and use the `Slate.findDOMNode` util function to get a reference to it, and find the coordinates of it the regular DOM way.

I've actually been meaning to open-source a component I built that makes it super easy, but haven't gotten to it yet. Here's a quick gist of it copy-pasted to give you a start: https://gist.github.com/ianstormtaylor/7924e6abc71c1efa40411a4553afe4dc

Hope that helps!

**Comment by podviaznikov** [comment]
Thank you @ianstormtaylor! That is exactly what I need.

**Comment by linguafranka** [comment]
@podviaznikov how did you go about implementing this?

@ianstormtaylor Thanks for sharing your SlateNodePortal in a gist. Very helpful. What's the best way to find the currently selected block? Docs don't mention this. SlateNodePortal takes node prop but if i'm not mistaken I'll need pass the currently selected block node to it for it work. What's the best way to get that given current editor state?

Thanks in advance!
