### ISSUE TITLE
Select one image and all of them will be selected

### ISSUE THREAD

**Issue by JinJieTan** [ianstormtaylor/slate#3084]
当我拖动鼠标的时候，选中一张图片，所有的都会有选中效果。

When I drag the mouse, I select one image, and all of them will be selected.

![image](https://user-images.githubusercontent.com/47209029/67732232-9fa34980-fa35-11e9-9d46-110069a7098d.png)

my code :

 
![image](https://user-images.githubusercontent.com/47209029/67732362-032d7700-fa36-11e9-9d0e-8f27379764cf.png)

```
 renderInline = (props, editor, next) => {
    const { attributes, node, isFocused } = props;
    switch (node.type) {
      case 'emoji':
        return (
          <span className="emoji-container">
            <img
              {...attributes}
              style={{ boxShadow: isFocused ? '0 0 0 1px #2FBE68' : 'none' }}
              src={require(`../../../../assets/emoji/emotion/${node.data.get('code')}.png`)}
              className="emoji"
              alt={node.data.get('code')}
            />
          </span>
        );
      case 'image':
        return (
          <span className="image-container">
            <img
              src={`${node.data.get('src')}`}
              className="image"
              {...attributes}
              style={{ boxShadow: isFocused ? '0 0 0 1px #2FBE68' : 'none' }}
              onMouseDown={(e) => {
                e.preventDefault();
              }}
             
            /> </span>
        );
      default:
        return next();
    }
  };
```

**Comment by JinJieTan** [comment]
@kommen @tslocke @justinweiss @rgrove  , Sorry to bother you, but could you help me check if there is something wrong with my code?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
