### ISSUE TITLE
Inline blocks are not erased correctly

### ISSUE THREAD

**Issue by cvlmtg** [ianstormtaylor/slate#3086]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

1) the user selects a word with a double click
2) an inline block is created for the current selection using `editor.insertInline()`. as you can see in the gif below the block is highlighted yellow and a new element is added to the page that shows the block plus some of its metadata
3) the user selects again the word with a double click
4) the user press backspace to delete the word
5) the inline block is *not* erased, it is still present as a zero width block. in the gif below you can see that the UI element for that block is still present

deleting the space before `bar` erases the inline block, but that's quite annoying for our users...

![ezgif-1-d3775ce8498d](https://user-images.githubusercontent.com/6401008/67843347-1571e880-fafc-11e9-88bc-e455f2b8fe18.gif)

```
"slate-plain-serializer": "^0.7.10",
"slate-react": "^0.22.9",
"slate": "^0.47.8",
```

OS: macOS and Windows
Browser: chrome

#### What's the expected behavior?

The inline block should be erased completely since the text deleted is the whole block.

BTW no idea if this bug is the same described here https://github.com/ianstormtaylor/slate/issues/2868, however since it seems this problem is not perceived as urgent, I really need to find some workaround in the meanwhile. Any help would be appreciated in case someone has some good / performant solution at hand. Thanks!

**Comment by Klaney** [comment]
You could possibly create a custom keyDownHandler for backspace/delete, where you have some logic where if the selected text is the same as the entire text of the inline block, use the `removeNodeByKey` method available on the editor object, to remove the node manually. I'm pretty sure that should produce the desired result.

**Comment by cvlmtg** [comment]
just a little update: I just discovered that this bug happens only on chrome. on firefox the inline block is erased correctly

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
