### ISSUE TITLE
Support React Concurrent Blocking Mode

### ISSUE THREAD

**Issue by newtack** [ianstormtaylor/slate#3090]
We want to move as soon as possible to React Concurrent mode and are using Slate. 

As per React's documentation there is migration approach that gives most of the benefits without going all the way, see

https://reactjs.org/docs/concurrent-mode-adoption.html#migration-step-blocking-mode

It'd be great if Slate could support this soon.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
