### ISSUE TITLE
weird Invalid regular expression error when minified with webpack

### ISSUE THREAD

**Issue by arxii** [ianstormtaylor/slate#3094]
compiled empty file and required slate... 
error only appears when i minify the code for production, any ideas?
![Screen Shot 2019-11-06 at 5 00 23 PM](https://user-images.githubusercontent.com/3401121/68345503-189a4500-00b7-11ea-88f3-7d692a13d06f.png)
![Screen Shot 2019-11-06 at 5 00 04 PM](https://user-images.githubusercontent.com/3401121/68345508-1b953580-00b7-11ea-9c2b-1f92554a6872.png)
<img width="616" alt="Screen Shot 2019-11-06 at 4 58 03 PM" src="https://user-images.githubusercontent.com/3401121/68345517-1fc15300-00b7-11ea-8152-60d15dca288c.png">

**Comment by arxii** [comment]
something to do with that dependency and parsing that character code string and webpack...not sure but i replaced it with 
![Screen Shot 2019-11-06 at 5 37 43 PM](https://user-images.githubusercontent.com/3401121/68347328-2900ee80-00bc-11ea-9ab5-409cd151a996.png)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
