### ISSUE TITLE
Undo weirdness

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#310]
Hello, we've been having some issues with undos around list items. It seems that slate likes to bundle list item edits together resulting in a ⌘Z that undoes a lot more than expected. See my two examples:

![slate-undo-1](https://cloud.githubusercontent.com/assets/310038/18488165/7e6e3224-79b5-11e6-835e-9df2e2645d0d.gif)

![slate-undo-2](https://cloud.githubusercontent.com/assets/310038/18488164/7e6db696-79b5-11e6-9b22-56687fe314d8.gif)

Additionally, typing into a line, pausing, typing some more and then undoing removes the entire line. It seems like maybe slate is batching edits that happen? This makes sense, although I would expect the batch to be timer based (i.e. record new history every 15ms) to avoid massive undos as that is rarely what the person editing wants.

**Comment by ianstormtaylor** [comment]
Hey @tyler-johnson thanks for reporting this! I totally agree. And that weird "delete whole line" behavior is totally a bug. Question, could you re-open this as three separate issues:

1. weird undo whole line bug
2. new undo save point for typing in different places
3. idea to create new save point after certain amount of time

Thanks man!

**Comment by tyler-johnson** [comment]
Done. Thanks!
