### ISSUE TITLE
Cursor Pointer not working when editor value is set from props.

### ISSUE THREAD

**Issue by edwinbbu** [ianstormtaylor/slate#3108]
#### What's the current behavior?

Text is not getting highlighted when editor value is set from props.

 ```
 onChange = ({ value }) => {
    const data = html.deserialize(this.props.value);
    if (value.document !== data.document) {
      const string = html.serialize(value);
      this.props.onChange(string);
    }    
    // this.setState({ value });
  }
```
Instead of setting the state. I am serializing and deserializing the editor value.

**Not able to highlight the text in the slate editor.**

Same issue was reported in https://stackoverflow.com/questions/53309983/slate-js-set-the-prop-as-the-editors-value

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
