### ISSUE TITLE
cursor lost when editor have sibling element and type in chinese character

### ISSUE THREAD

**Issue by cheerful-li** [ianstormtaylor/slate#3116]
when editor have a sibling element, you type in a chinese character, you lost your cursor

the bug can be reproduce in [https://www.slatejs.org/#/syncing-operations](https://www.slatejs.org/#/syncing-operations)

here is the gif: 
![cursorLost](https://user-images.githubusercontent.com/5164195/68832449-eb1f4e00-06eb-11ea-8d8c-3dd85bb808c0.gif)

the version is: 
    "slate": "0.47.9",
    "slate-react": "0.22.10"

below is a simple code to prove it
```jsx

import React from 'react'
import { Editor } from 'slate-react'
import { Value } from 'slate'

const initialValue = Value.fromJSON({
  document: {
    nodes: [
      {
        object: 'block',
        type: 'paragraph',
        nodes: [
          {
            object: 'text',
            text: '',
          },
        ],
      },
    ],
  },
})

// Define our app...
class NewEditor2 extends React.Component {
  // Set the initial value when the app is first constructed.
  state = {
    value: initialValue,
  }

  // On change, update the app's React state with the new editor value.
  onChange = ({ value }) => {
    this.setState({ value })
  }

  // Render the editor.
  render() {
    return (
      <div style={{ border: '1px solid #ddd', padding: 20 }}>
        <Editor
          value={this.state.value}
          onChange={this.onChange}
          placeholder="请输入"
        />
      </div>
    )
  }
}

const Other = props => {
  // return null
  return <div>123</div>
}

export default function() {
  return (
    <div>
      <NewEditor2 />
      <Other />
    </div>
  )
}


```

thanks for help

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
