### ISSUE TITLE
character overlapping placeholder and can't modify after lost focus

### ISSUE THREAD

**Issue by mongris** [ianstormtaylor/slate#3117]
#### What's the current behavior?

1. type with Chinese IME, character overlapping placeholder
2. click out of  editable area (let it lost focus), the character stuck

It can be repo in https://www.slatejs.org/#/rich-text

here is the gif

![Kapture 2019-11-15 at 16 59 45](https://user-images.githubusercontent.com/259816/68916379-91da1c00-07ca-11ea-9b83-51935477a2e8.gif)

#### What's the expected behavior?

1. hide placeholder when isComposing = true
2. update text node with composing character string when lost focus

**Comment by mongris** [comment]
I tried to change Placeholder plugin's `when()` to compare isComposing but it never be called when isComposing is true.

Help please

**Comment by Jokcy** [comment]
Have got the exact same problem.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
