### ISSUE TITLE
decorated text cannot be selected anymore

### ISSUE THREAD

**Issue by jege31** [ianstormtaylor/slate#3118]
This behaviour of SlateJs looks like a bug : after rendering a decoration (that looks ok in the browser) the text cannot be selected anymore. The cursor automatically moves to the end of the text.
The browser is Firefox and slate is 0.47.9

[Here is the index.js file](https://github.com/ianstormtaylor/slate/files/3860421/index.txt) giving this result (renamed index.txt because github does not accept .js)

![Salte_Decoration_Selection](https://user-images.githubusercontent.com/47570838/69084711-1b951e00-0a45-11ea-8f8e-39dd0b12d7d3.gif)

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
