### ISSUE TITLE
Move {Point} To {Edge} Of Fragment

### ISSUE THREAD

**Issue by rafegoldberg** [ianstormtaylor/slate#3119]
This works beautifully:

```javascript
editor
  .moveStartToStartOfBlock()
  .moveEndToEndOfBlock()
```

How would I similarly adjust the selection based on the `editor.value.fragment`? What I'd love to be able to do is like this:

```javascript
editor
  .moveStartToStartOfFragment()
  .moveEndToEndOfFragment()
```

And so on!

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by rafegoldberg** [comment]
@ianstormtaylor will definitely check out #3093
