### ISSUE TITLE
Incorrect text insertion behavior

### ISSUE THREAD

**Issue by eshavrov** [ianstormtaylor/slate#3122]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
The problem occurs if the selected fragment starts from the beginning of one of the leaves in the block of text with marks.
```js
/** @jsx h */

import h from '../../../helpers/h'

export default function(editor) {
  editor.insertText('insert')
}

export const input = (
  <value>
    <document>
      <paragraph>hello</paragraph>
      <paragraph>
        <anchor />wo<focus />
        <b>r</b>d
      </paragraph>
    </document>
  </value>
)

export const output = (
  <value>
    <document>
      <paragraph>
        helloinsert<cursor />
      </paragraph>
      <paragraph>
        <b>r</b>d
      </paragraph>
    </document>
  </value>
)
```
- Slate version: v0.47.6

#### What's the expected behavior?
```js
export const output = (
  <value>
    <document>
      <paragraph>hello</paragraph>
      <paragraph>
        insert<cursor />
        <b>r</b>d
      </paragraph>
    </document>
  </value>
)
```

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
