### ISSUE TITLE
onPaste no longer prevents default event

### ISSUE THREAD

**Issue by KrisBraun** [ianstormtaylor/slate#3123]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

https://www.slatejs.org/#/links

With a link in the paste buffer, select text and paste. The selected text is linked and the text of the link is also inserted. Adding `event.preventDefault()` in `onPaste` prevents the link text from being pasted.

#### What's the expected behavior?

Previously (0.44.x) this would only link the selected text.

The [onPaste docs](https://docs.slatejs.org/slate-react/plugins#onpaste) also state "The event is already prevented by default".

**Comment by KrisBraun** [comment]
Is this is a desired change, I'm up for putting up a PR that changes the example and docs. If it's a regression, I'm not sure if I'm set up to build and test a fix.

**Comment by DamareYoh** [comment]
I'm pretty sure the documentation and example are out of date. This bug was already found in the paste example and fixed by adding an `event.preventDefault()` call

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
