### ISSUE TITLE
setBlock merge data option

### ISSUE THREAD

**Issue by timothyarmes** [ianstormtaylor/slate#3125]
_feature_

`Editor.setBlocks({ data: { ... } -})` replaces the existing data with the new map.

This makes is awkward for plugins to add/remove their own data without affecting other plugins. For example, I have in image plugin that sets the _src_, and an alignment plugin  that sets the block's alignment.

When the alignment plugin tries to add its data using:

 `Editor.setBlocks({ data: { alignment: 'left'  } })`

the image src is lost.

**Comment by ihd-dev** [comment]
You could get the existing data and use that when setting the new, so as: Editor.setBlocks({ data: { ...existingData, alignment: 'left' } })

**Comment by timothyarmes** [comment]
No I can't, that assumes that all the selected blocks have the same data.

**Comment by DamareYoh** [comment]
Hi @timothyarmes, 
Slate is in flight on deprecating it's immutable js dependency in favor of immer, so long term this won't be an issue.

However, the first snippet you provided is the way consumers have been advised to handle data; you need to use the `editor.setNodeByKey(block.key, { data: block.data.merge(alignmentData) })` form to preserve the existing data.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
