### ISSUE TITLE
Upload Image to s3 plugin?

### ISSUE THREAD

**Issue by bonbonio** [ianstormtaylor/slate#3129]
Hello,

Is it possible to use this editor for the following;

h1-h6 styles, bold, italic and links buttons (Appears so)
Allowing images to be added, and aligned but the image should be uploaded to an s3 bucket as part of the saving process
If not, is there any other editors that work with ReactJS and could do this? My stack is NextJS + Material-UI + Hapi.

Many thanks... I did look through the past questions about local image upload, but there was no definitive answer or code example of this.

Many thanks

**Comment by CameronAckermanSEL** [comment]
Hi, thanks for your interest in the library. Please note that the issue  submission template included this:

```
<!-- 
If you have a question, ask it in our Slack channel instead:

https://slate-slack.herokuapp.com/
-->
```

We'll see you on the slack channel.

**Comment by tony** [comment]
@ianstormtaylor @camersonackermansel Hi there!

While I respect this policy, I wanted to offer an idea for cases like this.

When I looked this up via Google, I arrived on this page.

![image](https://user-images.githubusercontent.com/26336/109205229-ec9f4900-776b-11eb-8bb1-a2888a21f455.png)

This is what users see:

![image](https://user-images.githubusercontent.com/26336/109205454-39831f80-776c-11eb-9868-c543431a593b.png)

Idea:

It may be worth adding GitHub discussions. If you enable discussions, issues like this can be migrated to the Discussion forum. That way questions could be visible on Google.

**Comment by ianstormtaylor** [comment]
@Tony very fair point. I've enabled Discussions for this repo now, so we can opt to convert future issues into discussions which hopefully will help.

As far as this specific issue since there wasn't a description at all it seems pretty low quality and not likely to spark any useful discussion, so I'm opting not to convert it, and I'll delete it in a bit if I remember.

**Comment by tony** [comment]
@ianstormtaylor We can see what happens.  Maybe we can try to migrate this issue there? (I think you can do it via the bottom right)
