### ISSUE TITLE
idea to create new save point after certain amount of time

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#313]
See #310

**Comment by ianstormtaylor** [comment]
Closing, but if someone wants to come up with a way to make this happen feel free! Otherwise, I think it can belong in user-land.

**Comment by dmitrizzle** [comment]
I have a plugin that uses Lodash throttle. Happy to publish and share. However `onDicumentChange` isn't available for plugins; is there a way to get it to work there, or is `onChange` the only option?

**Comment by dmitrizzle** [comment]
```javascript
// tools
import { Raw } from "slate"
import throttle from "lodash/throttle"

// return
export function Save(options) {
	let throttledSave = throttle((state, prevState) => {
		if(prevState && state.document !== prevState.document){
			const composerState = JSON.stringify(Raw.serialize(state))
			localStorage.setItem("composer-state", composerState)
		}
	}, 5000);
  return {
  	onChange(state, prevState) {
  		throttledSave(state, prevState)
		}
  }
}
```

This works fairly well as a plugin. However, document changes state every time the cursor or focus changes. If there's a way to ignore those, the above would work better.
