### ISSUE TITLE
ime input on markdown-preview example add placeholder text

### ISSUE THREAD

**Issue by Jokcy** [ianstormtaylor/slate#3130]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

https://codesandbox.io/s/damp-wildflower-rux31
![Nov-27-2019 16-47-50](https://user-images.githubusercontent.com/2088642/69707970-b83a7880-1135-11ea-959f-cc0c99e061b6.gif)

#### What's the expected behavior?

just input the choosed text.

It seems releated to `decorateNode`, we can seem when I input `z`, it looks like the decoration before it. Also, if i use ime after input a space, then it works fine.

**Comment by Jokcy** [comment]
I also noticed that when I input `onChange` event never fire, I guess the characters added to decoration node directly.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.

**Comment by Jokcy** [comment]
@ianstormtaylor How to fix this in my project? Released in any version?

**Comment by Jokcy** [comment]
oh, I see, such a big release. I need to learn again I guess...
