### ISSUE TITLE
Backwards keyboard selection expansion breaks when moving through an "empty" block

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#3131]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

On the rich text example, holding shift and using the arrow keys to expand selection backwards 

Up arrow: 
https://recordit.co/dyndP7b3M0

Right arrow:

https://recordit.co/PFHAl2raHy

This behavior works as expected when expanding selection forwards. 

#### What's the expected behavior?

Selection continues to expand across empty blocks when using shift + arrow keys

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
