### ISSUE TITLE
[ Firefox ] Editor default behaviors not registering correctly

### ISSUE THREAD

**Issue by NomNomChompsky** [ianstormtaylor/slate#3134]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug.

OS: Windows 10
Browser: Firefox (Chrome is unaffected by this).
Slate Version: Latest one as of 11/28/2019 @ 11:54 PM PST

#### What's the current behavior?
As aforementioned, in Firefox:
![currentB](https://user-images.githubusercontent.com/51143383/69788211-02e6df80-118c-11ea-8449-79ae1844b6bb.gif)

- Previous state keeps "interfering" current state
- "Enter" key to next line does not work by default.

#### What's the expected behavior?
In Chrome:
![expectedB](https://user-images.githubusercontent.com/51143383/69788203-fe222b80-118b-11ea-964e-e841011b9903.gif)

With the defaults, working in Firefox seems to have gotten worse in the latest update. In the broad scheme of things I guess this isn't really a major issue considering Firefox's smaller user base to Chrome's.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3141
