### ISSUE TITLE
Images are now duplicated instead of being draggable

### ISSUE THREAD

**Issue by laufeyrut** [ianstormtaylor/slate#3137]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

From the examples https://www.slatejs.org/examples/images 

Now images are duplicated instead of being moved around in the text when dragging them.

Chrome Version 78.0.3904.108
MacOs Catalina 10.15.1
Slate version 0.50.0

![Kapture 2019-11-28 at 13 01 08](https://user-images.githubusercontent.com/15036127/69808345-2d15bd00-11df-11ea-82c6-45c0034c46b7.gif)

#### What's the expected behavior?

In the last version Images were draggable

**Comment by ejoebstl** [comment]
@ianstormtaylor Any leads on how to tackle this issue?
Is this a problem with the example or will it require digging deeper?

**Comment by kamilmielnik** [comment]
I'd like to point out one more issue here: dragging an image does not work if image is not selected. Instead its' URL is dragged.

![Peek 2020-09-25 15-10](https://user-images.githubusercontent.com/6830683/94243258-59a27e80-ff41-11ea-9358-f80d81be4dc1.gif)

**Comment by alexanderisora** [comment]
Thanks for opening this issue, @laufeyrut 
I have subscribed to follow any updates.

**Comment by clauderic** [comment]
Solved by #4238

**Comment by nikita-neganov** [comment]
@clauderic still duplicates at demo https://www.slatejs.org/examples/images

**Comment by clauderic** [comment]
@nikita-neganov there are issues with the auto-deploy of the https://www.slatejs.org website when changes are merged onto the main branch, I've informed @ianstormtaylor of this issue.

Locally when you clone the project, the problem is fixed.

**Comment by tjuandev** [comment]
For some reason the problem is still persisting in Firefox...
