### ISSUE TITLE
add "selection marks" back in

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3144]
#### Do you want to request a _feature_ or report a _bug_?

Feature.

#### What's the current behavior?

In the newest version of Slate, there is no longer an `isFocused` or `marks` property on the selection. However, the "adding a mark to the selection" is still a common rich-text behavior that should be supported.

#### What's the expected behavior?

If the selection is collapsed and someone does `add_mark` (or `remove_mark`), the marks should be added to an interim set which will be applied the next time a character is inserted. (This is how Google Docs, Dropbox Paper, etc. work.)

To do this, I think `withReact` should... 

1. Override the `add_mark` and `remove_mark` commands, and when the selection is collapsed it should update an `editor.marks` property. (Or even use a `WeakMap` and not have the data live in the editor object at all.)

2. Override the `insert_text` command to mark the text afterwards if there are currently any "selection marks" present.

3. Override the `apply` function for `set_selection` commands to remove any selection marks that are present, since that's what Google Docs seems to do—when the user's selection changes, the selection marks are ignored.

If anyone could help with this that would be awesome!

**Comment by dmarkow** [comment]
I might be interested in tackling this. However, `add_mark` etc. are gone now, in lieu of just using `Editor.setNodes(...)` to add formatting. So I'm not exactly sure where `withReact` should intercept/override the formatting?

**Comment by ianstormtaylor** [comment]
@dmarkow good question. I'm not exactly sure, but I think it could make sense to introduce a new `format_text` command for this purpose. And it might have options of:

```ts
interface FormatTextCommand {
  type: 'format_text'
  properties: Record<string, any>
}
```

Which we could then use for this purpose instead?

**Comment by dmarkow** [comment]
I was able to get something working in my app using this (though I haven't tested it much so far)

```js
const withRichText = (editor: Editor) => {
  const { exec, isVoid } = editor;

  editor.pendingFormats = null;

  editor.exec = command => {
    if (command.type === "insert_text" && editor.pendingFormats) {
      Editor.insertNodes(editor, {
        ...editor.pendingFormats,
        text: command.text
      });
      editor.pendingFormats = null;
    } else if (command.type === "toggle_format") {
      const { format } = command;
      const isActive = isFormatActive(editor, format);

      // Only apply the format if text is selected, otherwise save it for later
      if (editor.selection && Range.isExpanded(editor.selection)) {
        Editor.setNodes(
          editor,
          { [format]: isActive ? undefined : true },
          { match: "text", split: true }
        );
      } else {
        editor.pendingFormats = {
          ...(editor.pendingFormats || {}),
          [format]: isActive ? undefined : true
        };
      }
    } else {
      exec(command);
    }
  }
}
```

**Comment by ianstormtaylor** [comment]
Nice! That's awesome how small it is.

I think we might want to go with `add_format` and `remove_format` actually for the core behavior, so that we don't have to have core deciding what "active" is for people?
