### ISSUE TITLE
Backward selection from the start of a block is broken

### ISSUE THREAD

**Issue by zbeyens** [ianstormtaylor/slate#3147]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

![PwJGRRmom2](https://user-images.githubusercontent.com/19695832/69829358-ed22fa00-121f-11ea-939c-075c4d790d60.gif)

https://www.slatejs.org/examples/plain-text

Backward selection from the start of a block is not working correctly.

It looks that the cursor is moving when selecting

Chrome 78.0.3904.108
Windows 10
Slate v0.50.0

#### What's the expected behavior?

The cursor should not change its position when selecting with the mouse

**Comment by ianstormtaylor** [comment]
Is it just when using the mouse?

**Comment by zbeyens** [comment]
Using only Shift+Left, the backward selection breaks when traversing an empty block:

![KXr5Z6FTwa](https://user-images.githubusercontent.com/19695832/69833354-87d90400-1233-11ea-9b0e-40749012e061.gif)

Using Ctrl+Shift+Left: breaks only when starting from an empty block:

![R737cQhobJ](https://user-images.githubusercontent.com/19695832/69833403-e605e700-1233-11ea-95a2-1bfa1f23ba8a.gif)

**Comment by ianstormtaylor** [comment]
I think the original thing is a mouse-only behavior that is related to the zero-width spaces. I'm going to close in favor of #1971.
