### ISSUE TITLE
Obtaining an element's data object for deserialization

### ISSUE THREAD

**Issue by MatthewKosloski** [ianstormtaylor/slate#315]
In the [documentation](https://docs.slatejs.org/reference/serializers/html.html) it describes the structure of the returned deserialized object like so:

	{
	  kind: 'block',
	  type: String,
	  data: Object,
	  nodes: next(...)
	}

But I want to know how you would get the `data` Object?  This was my attempt:

	deserialize(el, next) {
	  const type = BLOCK_TAGS[el.tagName];
	  if (!type) return;
	  return {
		kind: 'block',
		type: type,
		data: el.data,
		nodes: next(el.children)
	  }
	}

I attempted to retrieve the data via the element's `data` property, but got nothing.  Really liking Slate so far, thanks!

**Comment by ianstormtaylor** [comment]
Hey @MatthewKosloski! Glad to hear it 😄 

I'm not sure if I understand you fully, but in that example the `el` there is a [`cheerio`](https://github.com/cheeriojs/cheerio) element object, and not a Slate element. 

In a `serialize` method you'd be passed a Slate `node` in this case which would have a `node.data` property. But in `deserialize` you're creating the Slate node object instead.

Let me know if that makes sense, I think I'm missing something, happy to help more with more info

**Comment by MatthewKosloski** [comment]
Hey @ianstormtaylor, thanks for the response.

It turns out this was a bit of a misunderstanding—I had it all backwards!  All this time I just wanted to get the `data` from the serialized object like so:

    serialize(object, children) {
        if (object.kind !== 'block') return;
        if(object.type === IMAGE) {
            return <img src={object.data.get('src')} alt="caption_goes_here"/>;
        }
    }

**Comment by FoxyWolfy** [comment]
Thanks!  This is the only place getting the image src is documented?
return <img src={object.data.get('src')} alt="caption_goes_here"/>;
