### ISSUE TITLE
Add super simple autocomplete to mentions example

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3152]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

Right now the `mentions` example uses a `window.prompt` for simplicity.

#### What's the expected behavior?

I think we could use the `<datalist>` approach from [this tweet](https://twitter.com/TejasKumar_/status/1194689434656088065) to end up with a proper autocomplete-like behavior but while still keeping it very simple. 

![image](https://user-images.githubusercontent.com/311752/69832957-06677e80-11ff-11ea-85a2-ab44d2e2cd10.png)

It would: 

- Borrow the hovering menu from `hovering-menu` to position the autocompleting `<input>` in the right spot when `@` is pressed, and insert on <kbd>enter</kbd>.

- Remove the mention button, and only use `@` autocompletion instead.

**Comment by timothyarmes** [comment]
Could this example please add a tiny bit of very useful complexity...

Rather than reusing the hover code, fo which we already have an example, it would be really useful if the dropdown could be pinned to the trigger character. It's not obvious how to do this, so the example add value.

We used to do this with an annotation.

**Comment by ianstormtaylor** [comment]
Sure! It would be very similar, just without updating on selection changes.

**Comment by timothyarmes** [comment]
Would that follow in scroll?

**Comment by objectlegal** [comment]
To my understanding, omitting to updating on changes makes it a bit weird in cases of line breaks and possibly even scrolling. E.g. we need the dropdown to follow even when we start @typing far to the right and it line-breaks in the middle of the suggestion. Therefore, its a bit more overhead and logic than anticipated, but it should be working calculatingand creating a custom dom range for the trigger and get the position from there. 

See: https://codesandbox.io/s/slate-reproductions-cdw83

Mewle
