### ISSUE TITLE
All Examples and Migrating show 404 Not found

### ISSUE THREAD

**Issue by flppv** [ianstormtaylor/slate#3157]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Example pages show 404 after last few commits

![image](https://user-images.githubusercontent.com/6984143/69834444-7a2f7880-124b-11ea-8acf-dc20a670bff0.png)

![image](https://user-images.githubusercontent.com/6984143/69834477-b2cf5200-124b-11ea-946e-4856768df316.png)

#### What's the expected behavior?

Those pages should load content.

**Comment by knownasilya** [comment]
Basically this makes the site not usable, since it auto redirects to examples page.
