### ISSUE TITLE
markdown-preview.js example isn't rendering properly

### ISSUE THREAD

**Issue by cassidoo** [ianstormtaylor/slate#3161]
#### Do you want to request a _feature_ or report a _bug_?

This is a bug.

#### What's the current behavior?

`markdown-preview.js` isn't rendering properly. It is just rendering as plaintext. I discovered this while trying to implement it in my own personal experiment with Slate, and wasn't sure what I was doing wrong, when I realized the example might be wrong.

https://github.com/ianstormtaylor/slate/blob/master/site/examples/markdown-preview.js

![image](https://user-images.githubusercontent.com/1454517/69848351-bd2f2300-122e-11ea-8d7d-3ac322ac50bb.png)

#### What's the expected behavior?

Markdown gets rendered properly in the example. I noticed that `markdown-shortcuts.js` renders properly, even though the two examples are very similar.

#### My personal guess

I'm not sure if this is right, but I think maybe `withHistory` and `withReact` have to be swapped? I saw that it was in a different order in the `markdown-shortcuts.js` file. I'm unable to set up the project currently myself, otherwise I would try a PR.

**Comment by ianstormtaylor** [comment]
My bad there @cassidoo I just broke it in a recent commit. Fixed with e1458c8c1b9c25c9cb5161fc38bfb56e2272fb2b thanks for reporting!

**Comment by hassenc** [comment]
@ianstormtaylor it looks this is broken again.

![image](https://user-images.githubusercontent.com/3796547/91659985-8b0b6400-ead3-11ea-9e68-afa627ca9e67.png)
