### ISSUE TITLE
`Editor.marks` seems to be truthy for all mark types if any mark is active

### ISSUE THREAD

**Issue by krishnagopinath** [ianstormtaylor/slate#3178]
#### Do you want to request a _feature_ or report a _bug_?
Bug

Looks like `Editor.marks` is returning truthy, if any mark is active. This is the function I use:

```
const isMarkActive = (editor, type) => {
  const [mark] = Editor.marks(editor, { match: { type }, mode: 'universal' })
  return !!mark
};
```

#### What's the current behavior?

![screen-capture](https://user-images.githubusercontent.com/4935809/69910158-ade9da00-13d4-11ea-93ea-cbabd51f67a5.gif)

Slate: 0.50.4
Browser: Chrome
OS: Linux

#### What's the expected behavior?

Returning the right mark status would be beneficial.

**Comment by arnaudDerbey** [comment]
`const isMarkActive = (editor, type) => {
  const [mark] = Editor.marks(editor, { match: { type }, mode: 'all' })
  return !!mark
};`
this did the trick for me.

**Comment by krishnagopinath** [comment]
Ah, makes sense. This may be a good time to add some docs about the `mode` property. 😅

**Comment by ianstormtaylor** [comment]
This sounds like a big. The universal snippet above looks like it should work. The universal mode sounds like it’s not weeding out the non-matches.

**Comment by krishnagopinath** [comment]
@ianstormtaylor could I give this a try?

**Comment by ianstormtaylor** [comment]
Absolutely!
