### ISSUE TITLE
Using currying in withSchema

### ISSUE THREAD

**Issue by timothyarmes** [ianstormtaylor/slate#3181]
_feature_

Currently the `withSchema` function takes the schema as the last argument: `withSchema(editor, schema)`. This is unfortunate since it doesn't allow functional composition:

```
const editor = compose(
  withInlineStyles,
  withBlockStyles,
  withAlignment,
  withLinks,
  withImages,
  withVideos,
  withHistory,
  withReact,
)(createEditor());

// This isn't nice ->
this.editor = withSchema(editor, schema);
```

If we allowed withSchema to be curried, we could do this, which is much nicer and fits better with the very functional approach taken throughout the codebase:

```
const editor = compose(
  withInlineStyles,
  withBlockStyles,
  withAlignment,
  withLinks,
  withImages,
  withVideos,
  withHistory,
  withSchema(schema),
  withReact,
)(createEditor());
```

**Comment by ianstormtaylor** [comment]
Sounds great to me, thanks @timothyarmes!
