### ISSUE TITLE
Firefox does not fire `beforeinput` events

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3185]
Firefox does not currently support the `beforeinput` event, which Slate uses under the covers to be notified whenever the user triggers an input into the editor (inserts, deletes, cuts, pastes, drops, etc.). These `beforeinput` events are cancellable and we use them to then do the Slate-equivalent of whatever the event was.

Right now we hack around this for Firefox and handle some of the common input cases. However, there's only so much we can do. And input events like `formatBold`, or `insertFromComposition` are hard to polyfill. (There might be ways to improve our existing ones, if you see them please PR!)

This is also the reason we disable `autoCorrect` and `spellCheck` in Firefox on the `contenteditable` element, since we have no easy way of determining when those changes occur.

Here are the bug reports… (please vote for and follow them!)

- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=970802
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1305387
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1449831

Once these are supported Firefox will get improved editing support (autocorrect, spellcheck, IME composition, B/U/I toolbars, etc.). And we'll be able to reduce bundle size for everyone by removing the current Firefox-specific hacks.

**Comment by minwe** [comment]
Duplicated text inserted when using IME in Firefox:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0
```

![ime-firefox70](https://user-images.githubusercontent.com/4370770/69947766-4f824000-1529-11ea-845d-2b978dbd8146.gif)

It seems text inserted both `onCompositionEnd` and `onBeforeInput`:

![image](https://user-images.githubusercontent.com/4370770/69947815-69bc1e00-1529-11ea-80a6-6bfcbedd9f8b.png)

![image](https://user-images.githubusercontent.com/4370770/69947862-80627500-1529-11ea-9ea2-bc03968984f5.png)

It's better to use **feature detection** but not **UA detection**.

**Comment by fletcher91** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=970802 and https://bugzilla.mozilla.org/show_bug.cgi?id=1449831 have been marked as fixed :+1:

**Comment by ClubicTech** [comment]
+1 I force "true" here https://github.com/ianstormtaylor/slate/blob/f4ee75d13d219214fd12c1b10448098f4c070b77/packages/slate-react/src/components/editable.tsx#L41 and spellcheck work perfectily on firefox 76.

**Comment by Doss** [comment]
Hello, 

When do you think you fixed this issue?

**Comment by hysie** [comment]
> 
> 
> +1 I force "true" here
> 
> https://github.com/ianstormtaylor/slate/blob/f4ee75d13d219214fd12c1b10448098f4c070b77/packages/slate-react/src/components/editable.tsx#L41
> and spellcheck work perfectily on firefox 76.

Doesn't work on Firefox 80.

It actually disables the fallback and ends up not firing any events when you spellcheck, this makes it look like it works but instead what you get is the real DOM not synchronizing with slate internal representation (doesn't `event.preventDefault`) and causing all kind of bugs.

What I did instead was to add a special fallback mechanism using the `input` event (only spellcheck), I'll make a PR if someone wants it.

**Comment by ClubicTech** [comment]
> I'll make a PR if someone wants it.

Yes, I want plz ;)

**Comment by asamuzaK** [comment]
You shouldn't detect by UA, instead detect feature like below.

```
const HAS_BEFORE_INPUT_SUPPORT = typeof InputEvent.prototype.getTargetRanges === 'function';
```
