### ISSUE TITLE
Slate docs say to use useMemo, should be useRef

### ISSUE THREAD

**Issue by jas7457** [ianstormtaylor/slate#3198]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
In the docs, it says to use useMemo for the editor instance passed to the `<Slate>` component so it is "stable across renders". useMemo does not guarantee identity between renders (https://reactjs.org/docs/hooks-reference.html#usememo) and talking with @ianstormtaylor, it sounds like identity is needed. between renders.

Slate: 0.50.7

#### What's the expected behavior?
The docs should be updated to use a ref (or some other stable memo besides useMemo/useCallback/etc). Slate itself could memoize the value passed to it if identity is necessary, or inversion of control could be maintained for the user of Slate to pass a memoized version.

#### Note:
A simple hook that I wrote can help to initialize a ref if it's expensive to compute. It works similar to useState's lazy initialization, but there wasn't a way to lazily set a ref.

import {useRef, MutableRefObject} from 'react';

```javascript
// using an object here instead of something like "null" or "undefined" or "Infinity"
// that way we truly know if we need to call the init function or not because the user of this can never pass something that === initialValue
const initialValue = {};

/**
 * Allows for lazy refs that only call the callback once
 * This also helps guarantee values between renders, unlike useMemo or useCallback which makes no such guarantee
 */
export default function useLazyRef<T>( init:() => T ):MutableRefObject<T> {
	const ref = useRef<T | typeof initialValue>( initialValue );

	if ( ref.current === initialValue ) {
		ref.current = init();
	}

	return ref as MutableRefObject<T>;
}

```

**Comment by ianstormtaylor** [comment]
Seems like we can use https://github.com/alexreardon/use-memo-one and maybe expose it as a `useStable` hook for people. Since it does seem to be asking a lot if people have to figure out the stability for themselves.
