### ISSUE TITLE
unwrapNodes destroys the parent block even when it is not empty

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#3199]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

unwrapNodes will destroy the parent block when unwrapping the target node(s) out of it. This has the side effect of displacing the nodes' previous siblings out of their parent container. This may result in confusing behaviors such as 
* blocks spontaneously disappearing due to schema rules
* list items becoming orphaned when converting one list item into a non list item block

Reproducible in the rich text example:
Before:
![image](https://user-images.githubusercontent.com/14242948/70002701-b5fd6300-1515-11ea-8ef5-f5eb6e36cb62.png)

After:
![image](https://user-images.githubusercontent.com/14242948/70002713-c44b7f00-1515-11ea-9312-d0e92df770ce.png)

Slate: 0.50

#### What's the expected behavior?
unwrapNodes preserves the parent block as long as it has children. It should also split the parent block if the node is in the middle of its child nodes collection

**Comment by ianstormtaylor** [comment]
Thanks for reporting this @CameronAckermanSEL!

The `unwrapNodes` transform actually supports a `split: true` option, but I forgot to add it for unwrapping those list blocks in the rich-text example. Just added!

**Comment by PeterKottas** [comment]
Thanks for reporting this @CameronAckermanSEL and big thanks for clarification @ianstormtaylor. I hope you wouldn't mind, I have some followup questions. 

How would one go around:
a) If I have a list of 3 items, select the middle, unwrap, then wrap again. My expectation would be that the list "joins" again. Now it creates 3 separate lists.
b) If I hold shift + enter, I would expect a new line to be inserted without a new li. How should you achieve something like this in 0.50? Should I intercept the onKeyDown handler? Not sure what way to go.

Cheers.

**Comment by ianstormtaylor** [comment]
Both of those would be solved the same as in earlier versions: (a) using a schema rule, and (b) by adding a hotkey.

**Comment by PeterKottas** [comment]
Hmm ok, I'll try to read about the schema rules. Any suggestions where some documentation about this might be? I don't think it's mentioned anywhere in the new docs.

**Comment by CameronAckermanSEL** [comment]
I have a schema for merging lists that probably doesn't work directly with `0.50` but could probably get you started:
```
      [BlockTypes.UnorderedList]: {
        next: { type: type => type !== BlockTypes.UnorderedList },
        normalize: (editor, {
          code, child, node, next,
        }) => {
          switch (code) {
            case 'next_sibling_type_invalid': {
              editor.withoutNormalizing((e) => {
                next.nodes.forEach((n, index) => {
                  e.moveNodeByKey(
                    n.key,
                    child.key,
                    child.nodes.size + index,
                  );
                });
                e.removeNodeByKey(next.key);
              });
              break;
            }
            default:
          }
        },
      },
```

And here's an old plugin that does soft break https://github.com/ianstormtaylor/slate-plugins/tree/master/packages/slate-soft-break

But it might just be easier to do a basic hotkey instead these days

**Comment by PeterKottas** [comment]
Thanks man, I'll try to figure where and how should this go in 0.50
