### ISSUE TITLE
Matching modes

### ISSUE THREAD

**Issue by objectlegal** [ianstormtaylor/slate#3208]
Many generator methods such as Editor.nodes take a mode argument, which is great. 

However, two discussion points from my side: 

1) As far as I understand, the only modes at the moment are 'highest' and 'all'. Wouldn't it make sense to also add a 'lowest' ? [**EDIT: I recalled Ian having mentioned this and found the issue where he addressed this. Nevermind. **] 
**Edit2: the Editor.match should also be able to take highest/lowest.**

2) The Editor.unwrapNodes method (and certain others) matches nodes using the mode 'highest'. This is perhaps a good default in many cases, although it should be possible to override this (for instance setting the mode 'lowest'). A use case would be that you have a set of nested lists and unwrapping the lowest/most nested list-items should - at least in my opinion - be made at the lowest level (not unwrapping the entire list from the top which mode 'highest' seems to result in)

**Comment by ianstormtaylor** [comment]
As for (1) there's already an issue for it here: https://github.com/ianstormtaylor/slate/issues/3184

And for (2) that sounds like a great idea to me, feel free to open another issue for it describing the feature request.
