### ISSUE TITLE
Images example: document.getBlocks doesn't work as expected

### ISSUE THREAD

**Issue by kommen** [ianstormtaylor/slate#321]
In the Images example [document.getBlocks is used](https://github.com/ianstormtaylor/slate/blob/b7f317a/examples/images/index.js#L117-L119), but as far as I can see [getBlocks](https://github.com/ianstormtaylor/slate/blob/88f6ee5e12aa76b95a329ae075358f0e48b0e836/lib/models/node.js#L159) doesn't give ordering guarantees, so checking for the last returned value won't always work.

We're working around this like this:

```javascript
const lastText = document.getTexts().last()
const lastBlock = document.getClosestBlock(lastText)
```

Is that sensible? Thanks!

**Comment by ianstormtaylor** [comment]
Ah, good catch! We'd want that to guarantee order I think, which I guess would just be replacing `.toSet()` with `.toOrderedSet()`?

If you want to whip up a PR I'd be happy to merge! Should be just a find/replace I think. If you do, could you replace the other spots where we do `.toSet().toList()` as well? Thanks!

**Comment by kommen** [comment]
Thanks @ianstormtaylor! And thanks @somus for the quick PR :)
