### ISSUE TITLE
newLine at the end of line

### ISSUE THREAD

**Issue by PeterKottas** [ianstormtaylor/slate#3213]
#### What's the current behavior?
If you do
```
editor.exec({
  type: 'insert_text',
  text: '\n',
});
```
when the selection is at the end of the line, it won't immediately jump to the next line. You need to do it twice.
https://codesandbox.io/s/slate-reproductions-m94x1
use shift + enter to trigger the command to insert \n. Notice that if you first use normal enter, then backspace then shift + enter, it actually works.

Slate: 0.50.8
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?
It should work on the first try.

**Comment by ianstormtaylor** [comment]
I believe this is fixed now.
