### ISSUE TITLE
Transforms are now mutable

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#323]
I think it should be added to `History.md` because it was a breaking change in `v0.14.0`.

```diff
-- **Transforms are no longer exposed on `State` or `Node`.** ...
+- **Transforms are no longer exposed on `State` or `Node` and are now mutable.** ... 
```

[We already have talked about this change](https://github.com/ianstormtaylor/slate/issues/274), so now I am kind of late to the party. But I still wonder how much in performance improvement this brings. Have you had any performance issue with Transforms so far ? Or have you measured the benefits somehow ?

**Comment by ianstormtaylor** [comment]
Ah shoot you're right. Honestly I'm not sure that it brings performance enhancements, and I'd be down to revert that to keep everything immutable... Wasn't sure where to go there, since they're use case is pretty mutable, but it is an outlier.
