### ISSUE TITLE
How to limit Editor to single line

### ISSUE THREAD

**Issue by thunderousNinja** [ianstormtaylor/slate#3238]
I am trying to figure out how to limit the Slate Editor to just be a single line, so it can be used as an input box.  I am struggling to figure out how this can be done, especially with the recent 0.5x changes.

I tried looking at the forced layout example to see if there is something I can do with the schema, but I wasn’t able to find any good documentation on the slate-schema stuff.

Any ideas on how this can be done?

Thanks!

**Comment by SilverDY** [comment]
Questions like this would be better to ask in the Slack channel. Probably someone has already asked this one.

**Comment by Gab1988** [comment]
If you are still checking this one out have a look at this example 

https://codesandbox.io/s/slate-single-line-2190g?file=/src/PlaceholderInput.tsx
