### ISSUE TITLE
slate-react@0.50.11 has old TS typings

### ISSUE THREAD

**Issue by eddyw** [ianstormtaylor/slate#3247]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

I'm implementing the examples in the repo in TypeScript and it's displaying a bunch of error in pretty much every component. For example:
```typescript
    <Slate
      editor={editor}
      value={value} // <<< Property 'value' does not exist on type ...
      selection={selection}
      onChange={(value, selection) => {
        setValue(value)
        setSelection(selection) // << Type 'Operation[]' is missing the following properties from type 'Range'
      }}
    >
```

I checked the installed types against a cloned & built version from Github and the typings in 0.50.11 seem to be .. old.

This is from current installed `index.d.ts`:
```typescript
export * from './components/editable';
export { DefaultElement } from './components/element';
export { DefaultMark, DefaultDecoration } from './components/leaf';
export * from './hooks/use-editor';
export * from './hooks/use-focused';
export * from './hooks/use-read-only';
export * from './hooks/use-selected';
export * from './hooks/use-slate';
export * from './react-command';
export * from './react-editor';
export * from './with-react';
//# sourceMappingURL=index.d.ts.map
```

Slate: 0.50.11
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?

The one that works that I built from the repo (0.50.11):
```typescript
export { RenderElementProps, RenderLeafProps, Editable, } from './components/editable';
export { DefaultElement } from './components/element';
export { DefaultLeaf } from './components/leaf';
export { Slate } from './components/slate';
export { useEditor } from './hooks/use-editor';
export { useFocused } from './hooks/use-focused';
export { useReadOnly } from './hooks/use-read-only';
export { useSelected } from './hooks/use-selected';
export { useSlate } from './hooks/use-slate';
export { InsertDataCommand, ReactCommand } from './plugin/react-command';
export { ReactEditor } from './plugin/react-editor';
export { withReact } from './plugin/with-react';
//# sourceMappingURL=index.d.ts.map
```

**Comment by ianstormtaylor** [comment]
Sounds like something in the build scripts that doesn't properly rebuild the typings when releasing? Not sure. If someone who's good with TypeScript tooling can investigate that would be amazing.

**Comment by eddyw** [comment]
It seems ok on recently released `0.51` 👍

**Comment by ianstormtaylor** [comment]
Sounds even more likely then that it's a transient error in the build/release process

**Comment by gyh9457** [comment]
encountered a similar error, can not recognize `renderLeaf` and some other props

![image](https://user-images.githubusercontent.com/13557235/70312248-31c91980-184e-11ea-9360-14c480fb3d99.png)

**Comment by ianstormtaylor** [comment]
I believe this is fixed with https://github.com/ianstormtaylor/slate/commit/e1918a7cf4400d23e45d10f8b8256c2600085fe0 because it was some caching issue with the `rollup-plugin-typescript2`. Which probably makes rebuilds a lot slower sadly.
