### ISSUE TITLE
add `'universal'` matching mode to `Editor.nodes`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3248]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the expected behavior?

It's a common use case to want to match "only nodes that appear in every branch of the selection". This essentially answers the questions "do all nodes I have selected match this?".

This is useful for determining the "active" state of text marks, and for some block nodes as well.

For example:

```jsx
<paragraph>
  <text bold>on<anchor />e</text>
  <text>t<focus />wo</text>
</paragraph>
```

With that selection, using the `'all'` mode returns a match. But if you're determining the active state of a <kbd>Bold</kbd> toolbar button then you likely only want it active if **every** text node in the selection is bold—not just one.

So instead of `'all'`, you'd use the `mode: 'universal'` which only makes nodes eligible to be matched that are in every "branch" (eg. all the levels of a single path) in the tree.

That example has two branches:

```js
[[], [0], [0,0]]
[[], [0], [0,1]]
```

But the same works for blocks, for example:

```jsx
<paragraph>o<anchor />ne</paragraph>
<quote>tw<focus />o</quote>
```

Matching `{ type: 'paragraph' }` with the branches:

```js
[[], [0], [0,0]]
[[], [1], [1,0]]
```

Would also return no matches in universal mode.

**Comment by objectlegal** [comment]
Great idea! What comes to mind is the array methods `every` and `some` which method names could perhaps be used here as well?
