### ISSUE TITLE
Links example: text added after link gets included in link

### ISSUE THREAD

**Issue by dmarkow** [ianstormtaylor/slate#3253]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

In the Links example, when the last word is a link, it becomes impossible to add non-link text after it without hitting Enter and starting a new paragraph first.

![ScreenFlow](https://user-images.githubusercontent.com/8009/70268015-382f9680-1765-11ea-98f4-62975c73cded.gif)

Slate: 0.51.0
Browser: Chrome 
OS: Mac

#### What's the expected behavior?

Placing the cursor immediately after the last character in a link and typing should result in non-link text (this is how most rich editors handle it)

**Comment by ianstormtaylor** [comment]
This is a known bug right now, but solvable by: https://github.com/ianstormtaylor/slate/issues/3151

**Comment by dmarkow** [comment]
Fixed in #3260
