### ISSUE TITLE
transform deleteBackward is not deleting enough

### ISSUE THREAD

**Issue by massanishi** [ianstormtaylor/slate#326]
Hi, I was looking for a way to implement cmd and alt delete. This improvement [thread](https://github.com/ianstormtaylor/slate/issues/80) says the feature is implemented already. 

But running the http://slatejs.org example, the cmd/alt delete pushes the cursor back as expected, but it only deletes the first character. Diving more into the core plugin, word/char offset count is returning the right number, but it looks like state.transform().deleteBackward(n).apply() is not behaving properly. Any thought?

**Comment by ianstormtaylor** [comment]
It looks like this is a regression from `0.14`, thanks for reporting this!
