### ISSUE TITLE
Delete forward is not well supported (Ctrl+D)

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#327]
To reproduce on the base JSFiddle https://jsfiddle.net/2zokvrvt/7/ 

1. Move cursor in the middle of the text.
2. Delete forward (<kbd>Ctrl+D</kbd> on OSX)
3. The cursor is not at the right offset.

**Comment by Soreine** [comment]
There are also issues with other native editing shortcuts:
- <kbd>Cmd+K</kbd> which should delete the rest of the line
- <kbd>Alt+Delete</kbd> which should delete the previous word

I can open separate issues for these.

**Comment by ianstormtaylor** [comment]
Fixed the multiple-word/line issue: https://github.com/ianstormtaylor/slate/commit/f27ccd5140345507827c3e57645488d04ef04a4a

**Comment by ianstormtaylor** [comment]
Hey @Soreine for the <kbd>Cmd+D</kbd> key combination, where are you seeing that? Every browser I have overrides that to be "add to favorites".

**Comment by Soreine** [comment]
Oops, I meant <kbd>Control+D</kbd> and <kbd>Control+K</kbd> (Edited)

**Comment by ianstormtaylor** [comment]
moved to a new issue for anyone to tackle!
