### ISSUE TITLE
What Minimum Version of Chrome Does Slate Support

### ISSUE THREAD

**Issue by scottfr** [ianstormtaylor/slate#3274]
What is the lowest version of Chrome Slate should support?

In our continuous integration pipeline we are seeing Slate 0.5+ failing on Chrome 75 and earlier (76 and onwards works fine). Is that to be expected or should Slate support these earlier versions?

**Comment by ianstormtaylor** [comment]
Honestly, no idea. But I'm down to have it support the latest two versions. Which right now seems like 78 and 77. If people have specific issues with a recent version they can open issues for whatever the bug is.
