### ISSUE TITLE
Programmatically set `text` for text node

### ISSUE THREAD

**Issue by objectlegal** [ianstormtaylor/slate#3278]
#### Do you want to request a _feature_ or report a _bug_?

_Improvement_

#### What's the current behavior?

AFAIK, there is no obvious way to set the `text` of a text/leaf node. There was a recent update which disallowed the usage of the `set_node` operation to set the `text`.

I'm sure that there are reasons for not allowing the replacement of text this way. One issue was that selection errors could arise if the selection covered offsets which following text replacement no longer existed (i.e. if the replaced text was shorter in length). This could however be solved so that - if the selection following replacement would be out of bounds - the selection is adjusted in connection with the replacement. 

Is there any other known issues or reasons not to have a method/operation to set or replace text in text nodes? If not, I'd be happy to look into making a PR. 

Slate: 0.52.X

#### What's the expected behavior?

A user should be able to programmatically set the text of a text node.

**Comment by ianstormtaylor** [comment]
If you have the path of the text node you can do it with `Editor.insertText`. Because paths are converted to ranges, deleted, and then inserted at the collapsed point. 

Similarly you can replace the full text of an element with the same approach.
