### ISSUE TITLE
v0.52.6 Slate doesn't auto-normalize

### ISSUE THREAD

**Issue by eddyw** [ianstormtaylor/slate#3285]
#### Do you want to request a _feature_ or report a _bug_?

Bug?

#### What's the current behavior?

It doesn't seem to auto-normalize when the editor is created. I have wrote a `withSchema` plugin that wants to enforce a specific layout. However, this doesn't happen when the editor is created and only when start typing on it.

```typescript
export const withSchema = (nodes: Element[]) => (editor: Editor): Editor => {
  const { normalizeNode } = editor

  editor.normalizeNode = entry => {
    const [, path] = entry

    if (path.length === 0) {
      /**
       * Ensure it has exactly the same number of nodes
       * specified in `nodes` argument
       */
      if (editor.children.length < nodes.length) {
        const insertLength = nodes.length - editor.children.length
        const start = nodes.length - insertLength

        for (let i = start; i < nodes.length; i++) {
          Editor.insertNodes(editor, nodes[i])
        }
      }
      /**
       * Remove extra nodes and set each node
       * to the specified type in `nodes`
       */
      if (editor.children.length > nodes.length) {
        for (const [child, childPath] of Node.children(editor, path)) {
          const index = childPath[0]

          if (index >= nodes.length) {
            Editor.removeNodes(editor, { at: childPath })
          } else if (child.type !== nodes[index]) {
            Editor.setNodes(editor, { type: nodes[index].type }, { at: childPath })
          }
        }
      }
    }

    return normalizeNode(entry)
  }

  return editor
}
...
  const editor = useMemo(
    () => withReact(withSchema(createEditor())),
    []
  )
```

I don't know if this is the expected behavior or not. The way I'm going around this issue is like this:
```javascript
  React.useLayoutEffect(() => {
    Editor.normalize(editor, { force: true })
  }, [editor])
```

If I try to do `Editor.normalize` within the `withSchema` plugin after overwriting `normalizeNode`, it doesn't do anything because `Editor.isNormalizing` returns `true` (??)

Slate: 0.52.6
Browser: -
OS: -

#### What's the expected behavior?

If it's not the expected behavior, then it should normalize nodes when editor is created.

**Comment by ianstormtaylor** [comment]
Not normalizing everything on create is the new expected behavior, yup. It's an expensive operation, and the old way made it hard to opt-out of. In the majority of cases the data will have be saved from a previously normalized state, so it's wasted effort.

The way you're doing it sounds right. Another approach is to call `Editor.normalize` right after wherever you are calling `createEditor()` (after mixing in your plugins).

If you want to open another issue to discuss the `Editor.normalize` and `isNormalizing` interaction, that sounds good. I'm not sure what to do there.

**Comment by eddyw** [comment]
> The way you're doing it sounds right. Another approach is to call Editor.normalize right after wherever you are calling createEditor() (after mixing in your plugins).

Actually, I have tried this:
```typescript
  const editor = useMemo(
    () => {
      const e = withReact(withSchema(createEditor()))
      Editor.normalize(e, { force: true })
      return e
    },
    []
  )
```

And it doesn't work and it made sense because the editor hasn't gotten a `value` just yet. I'm guessing `useLayoutEffect` would be the only way to go?

**Comment by ianstormtaylor** [comment]
@eddyw ah yeah good point. I guess `useLayoutEffect` is the way then.
