### ISSUE TITLE
Site examples fail on Ubuntu+Chrome

### ISSUE THREAD

**Issue by Bonnevie** [ianstormtaylor/slate#3286]
#### What's the current behavior?
Using Ubuntu 16.04 and an updated Chrome browser, all of the examples at [www.slatejs.org/examples](www.slatejs.org/examples) fail. The issue was reproduced in a Chrome browser running without extensions, as well as using a local clone of the repo, and also when running basic examples in a fresh `react-app`. The examples run as expected on my Windows system.

The issue manifests as wrong handling of inputs, where each key results in two new characters and the cursor being moved, as seen in the GIF below where I only press the character `a` on the keyboard.  

![slate-crash](https://user-images.githubusercontent.com/5861991/70553564-a4523600-1b7b-11ea-9929-02d5d216f21d.gif)

The crashes seem to occur when text is attempted added to an empty node, such as when writing in a blank document or at the rightmost edge of the document.

Using a `console.log` in the `onChange` function of the `Slate` component, it appears that the text reproduced on the screen does not reflect the internal state passed to `SetValue` --- the latter does not contain duplicate characters after one keypress.

Possibly related to issues of missing `beforeInput` events?

**Comment by eddyw** [comment]
@Bonnevie what is the browser version you're using?
`chrome://version/`

**Comment by Bonnevie** [comment]
I am on a different Ubuntu+Chrome setup now  where the problem does not persist (specifically Ubuntu version 18.04.3 LTS/Chrome version 79.0.3945.79 (Official Build) (64-bit)), so it's clear now that it is not due to the combination alone. 
I cannot check the version of the browser before I get home I am afraid...

**Comment by Bonnevie** [comment]
@eddyw okay, finally got to check the version, it is version 75.0.3770.90 (Official Build) (64-bit). Since this is lower than the version on my other system, I did a reinstall, and the newer version actually fixes the issue.  I'll close the issue unless you want to pursue it further.
