### ISSUE TITLE
IME input bug in richtext demo

### ISSUE THREAD

**Issue by icarusysuper** [ianstormtaylor/slate#3292]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
![demo](https://user-images.githubusercontent.com/3395277/70581749-3c3f3680-1bf3-11ea-8f65-226ff1573b5f.gif)

Slate: 0.53.X
Browser: Chrome
OS: Windows

#### Reproduce steps

1. visit https://www.slatejs.org/examples/richtext
2. switch to IME input (Chinese pinyin)
3. select multiple lines
4. input something (IME input)

#### What's the expected behavior?

IME input work correctly in situation above

**Comment by tianpanpan66** [comment]
https://user-images.githubusercontent.com/28037665/111422707-0fe56480-872a-11eb-801b-c4406f750a11.mp4

type chinese, crash
