### ISSUE TITLE
Building a custom layout engine for Slate

### ISSUE THREAD

**Issue by aglundahl** [ianstormtaylor/slate#3296]
We are working on a Slate-based word processor similar to Google Docs. To create a word processor, we have to implement a lot of features that aren't typical of Slate or of most editors, really: pagination, headers and footers, footnotes, tab stops, etc.

Our research suggests that many of these features would be difficult, if not impossible, to implement with a contenteditable. For example, to do pagination we need to split the content at every page break, and there will be headers and footers between the editing surfaces of every page. Even though we have been able to implement very rudimentary pagination by doing custom line wrapping in Slate, we are suspecting that we will reach a point where we want to implement a feature that is impossible to implement using contenteditable.

To circumvent this, we are building our own layout engine for Slate. The idea is to render Slate's value similarly to slate-react, but orthogonally to the input method and not inside a contenteditable. We would then process input and user events in a separate, hidden, and always focused contenteditable (this is how Google Docs does it), and translate them to commands that we send to Slate.

By doing this, we hope to fight less contenteditable quirks and not worry as much about browser compatibility. Intuitively, we think that it might also facilitate virtualization when rendering large documents.

What we are wondering is if anyone else in the Slate community is working on anything similar to this, or for some other reason has valuable insights in relation to what we are trying to do. It would also be highly appreciated if anyone has feedback or thoughts on our plan on how to implement this.

Thanks!

**Comment by seanders** [comment]
This may have been brought up, but I was wondering if there's any lessons we could derive from how `@react-pdf` handles layout and pagination using yoga. The reason this jumped to mind is that I know `react-pdf` handles pushing content over into new pages:

https://github.com/react-pdf/textkit

**Comment by t3db0t** [comment]
For whatever it's worth I'm highly interested in this feature set. Happy to help where possible.

**Comment by dimitriadamou** [comment]
I'm definitely happy to work on something like this, is there an open repo or a point of collaboration?

**Comment by gintautassulskus** [comment]
@aglundahl did you get anywhere with this? 

Is it possible to replace the layout engine in Slate through standard and intended means or do you have to rewrite the internals?

**Comment by BrentFarese** [comment]
Closing this issue.  We have made some significant progress on this, but we had to scrap `slate-react` entirely and re-write a bunch of things ourselves.  Taleweaver is an interesting project too!

**Comment by BrentFarese** [comment]
> I've been thinking of trying to see if I can fork `react-slate` to add some extension points to make pagination in the presentation layer possible, and try to get those improvements merged back in the upstream so they can benefit everyone.

We re-wrote `slate-react` and manage the selection differently, built our own rendering engine for pages.  It was no small feat.  It's not open source but maybe 1 day it will be.

**Comment by mattiaz9** [comment]
@BrentFarese so is it possible to paginate the editor now or is it still a closed solution? in that case are you willing to share your code with the community?
