### ISSUE TITLE
Allow for more complicated `matches` handling on Text & Element nodes

### ISSUE THREAD

**Issue by timbuckley** [ianstormtaylor/slate#3299]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

`Text.matches` and `Element.matches` cannot handle matches where the values for props are objects.

For example:
```js
const textNode = {text: 'hiii', bold: {active: true}}
const searchProps = {bold: {active:true}}

 // Does not consider this a match because of JavaScript's !== is a reference check, eg: {} !== {}
Text.matches(textNode, searchProps) === false
```

#### What's the expected behavior?

Since the concept of the `marks` array is gone, properties on `Text` and `Element` nodes may become more complex, and so we should allow for more robust searching of properties on these Nodes.

Expected behavior:
```js
const textNode = {text: 'hiii', bold: {active: true}}
const searchProps = {bold: {active:true}}


Text.matches(textNode, searchProps) === true
```

More complicated expected matching behavior:
```js
const textNode = {text: 'hiii', bold: {active: true, inherited: false}}
const searchProps = {bold: {active:true}}

// Nested objects should also allow for partial matches.
Text.matches(textNode, searchProps) === true
```

I'll have a PR for this change shortly.

**Comment by ianstormtaylor** [comment]
What use case are you needing the nested objects for?

And can you give a code snippet of where are you using the `Node/Text.matches` function?

**Comment by timbuckley** [comment]
@ianstormtaylor Since the concept of Marks is removed in favor of attributes on nodes, more robust searching on those properties is useful.

```js
import { Text } from 'slate'

const exampleTextNode: Text = {
  text: 'Some bold text.',
  bold: {
    active: true,
    origin: 'INHERITED',
  }
};

// Now I want to find bolded Text nodes, regardless of their `origin`.
Text.matches(exampleTextNode, {bold: {active: true}})
// But ^ this returns false, not the desired behavior
```

**Comment by ianstormtaylor** [comment]
What's your use case? Explain the domain-specific behaviors you're looking for.

I'm not likely to expand this contract in the API easily. No other parts of the API work that way to my knowledge, and it's generally common for things to not be loosely matched? Not to mention if you really need this you can always write one-off logic to test nested structures.

I'm not opposed, but I want to see strong merit.

**Comment by timbuckley** [comment]
In our use case, we need to know two things about any given text property (bold, italics, etc):

1) Whether it was caused by the user directly (`origin: 'USER_APPLIED'`) vs inherited (`origin: 'INHERITED'`) from the text's style-type, eg `Normal`, `Title` or `Heading 3`.
![Screen Shot 2019-12-13 at 10 26 03 AM](https://user-images.githubusercontent.com/4212194/70811127-fe791400-1d92-11ea-8b1f-61afaac5e253.png)
2) Whether that attribute is on or off (`active: bool;`). If it's not a binary, it would need something else like `size: number;`. Either way, this is necessary to know what to render.

We need both of those bits of data because, when the default style attributes of a given style change (eg, maybe `Normal` style changes to have `bold.active = true`), we need to know whether the given text node should just have its attribute just use whatever value was inherited, or keep the style the user has previously applied to it.

The most straightforward way to model this is
```ts
const exampleTextNode: Text = {
  text: 'Some bold, non-italicized text.',
  style: 'normal',
  bold: {
    active: true,
    origin: 'USER_APPLIED'
  },
  italics: {
    active: false,
    origin: 'INHERITED'
  },
};
```

Though it is also possible to model it in the following way, it's a bit uglier:
```ts
const exampleTextNode2: Text = {
  text: 'Some bold, non-italicized text.',
  style: 'normal',
  boldActive: true,
  boldOrigin: 'USER_APPLIED',
  italicsActive: false,
  italicsOrigin: 'INHERITED',
  // ...
};
```

That said, even if you don't agree with our modeling, the current behavior makes attributes of objects and arrays never match, due to JS reference equality (`{} !== {}`). In that case the underlying check should at least be `deepEquals(text[key], prop[key])` instead of just `===`.

**Comment by ianstormtaylor** [comment]
Why not model that as:

```ts
interface Text {
  text: string
  style: ‘normal’ | ‘heading’ | ...
  bold: boolean 
  italic: boolean 
  ...
}
```

**Comment by timbuckley** [comment]
Closing in favor of the merged and released behavior in https://github.com/ianstormtaylor/slate/pull/3327, which completely covers my use case. Thanks Ian!
