### ISSUE TITLE
What is the purpose of onDOMBeforeInput?

### ISSUE THREAD

**Issue by zbeyens** [ianstormtaylor/slate#3302]
The only example using it is:

https://github.com/ianstormtaylor/slate/blob/bad6472e130723d33830439e8a09d09130e63754/site/examples/hovering-toolbar.js#L32-L43

By removing it, I don't see any change. 

Can you explain its purpose? Thanks!

**Comment by ianstormtaylor** [comment]
It's an event handler for the native DOM `beforeinput` event, because sadly React's synthetic events don't properly expose it. In this case it's listening for specific `inputType`s that browsers fire for context menus, etc.

**Comment by Prottoy2938** [comment]
I can't use `onDOMBeforeInput` in my **Slate React TypeScript** project. I'm following this code example: 
https://github.com/ianstormtaylor/slate/blob/master/site/examples/hovering-toolbar.js

And I'm trying to convert the code into typescript. But I'm stuck in the `onDomeBeforeInput` props, it says: `Property 'inputType' does not exist on type 'Event'.`

Any idea?

Is there any example TypeScript version for this [project](https://www.slatejs.org/examples/hovering-toolbar)?

**Comment by victor-ca** [comment]
> I can't use `onDOMBeforeInput` in my **Slate React TypeScript** project. I'm following this code example:
> https://github.com/ianstormtaylor/slate/blob/master/site/examples/hovering-toolbar.js
> 
> And I'm trying to convert the code into typescript. But I'm stuck in the `onDomeBeforeInput` props, it says: `Property 'inputType' does not exist on type 'Event'.`
> 
> Any idea?
> 
> Is there any example TypeScript version for this [project](https://www.slatejs.org/examples/hovering-toolbar)?
```ts
  onDOMBeforeInput={(e: Event) => {
          const event = e as InputEvent;
          event.preventDefault();
          //...
````

**Comment by Bartlett-Will** [comment]
> > I can't use `onDOMBeforeInput` in my **Slate React TypeScript** project. I'm following this code example:
> > https://github.com/ianstormtaylor/slate/blob/master/site/examples/hovering-toolbar.js
> > And I'm trying to convert the code into typescript. But I'm stuck in the `onDomeBeforeInput` props, it says: `Property 'inputType' does not exist on type 'Event'.`
> > Any idea?
> > Is there any example TypeScript version for this [project](https://www.slatejs.org/examples/hovering-toolbar)?
> 
> ```ts
>   onDOMBeforeInput={(e: Event) => {
>           const event = e as InputEvent;
>           event.preventDefault();
>           //...
> ```

Preventing the default for the onDomBeforeInput will disable the ability to type into the editor
