### ISSUE TITLE
Add warning to docs that Android is currently not supported after 0.47

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3314]
#### Do you want to request a _feature_ or report a _bug_?

Improve documentation

#### What's the current behavior?

It's not clear that Android is not supported in the current version of Slate

#### What's the expected behavior?

Provide a warning in the documentation that if Android support is required to use version 0.47 of Slate.

**Comment by SilverDY** [comment]
@thesunny, do you have plans to add support for the current version? I hope so :)

**Comment by SilverDY** [comment]
@thesunny do you have progress in adding this support?

**Comment by thesunny** [comment]
Sorry, I do not have a timeline; however, I can share that it realistically won't be for a while.
