### ISSUE TITLE
documentation is lacking

### ISSUE THREAD

**Issue by cvlmtg** [ianstormtaylor/slate#3318]
Hi, are there any plans in improving the documentation, describing commands and helpers?

I'm currently trying to upgrade out app from slate 0.4x to slate 0.5x and it seems all I can do is just copy-paste code from the examples without understanding how the new slate works...

Just an example: our editor has a button to remove all styles from the current block or selected text. I could achieve it with this code:

```
editor
   .moveStartToStartOfBlock()
   .moveEndToEndOfBlock()
   .setBlocks({ type: 'paragraph' })
   .removeMark('underline')
   .removeMark('italic')
   .removeMark('bold');
```

I have no idea how to do the same with slate 0.5x, because available helpers and commands are basically undocumented...

I know this release has been a big change, things are still getting ironed out etc... but trying to upgrade has currently been quite frustrating :(
Any help would be greatly appreciated!

BTW at the beginning of the project I tried draft.js and I was basically copy-pasting code that manipulated nodes, splitting here, wrapping there etc... Then I tried slate and I really appreciated how its interface made my code really simple and expressive. now it seems I'm back at copying code I don't understand... I think it would really be a huge improvement trying to have again something similar to the old methods, or at least standardize arguments and such (e.g. why in the rich-text example the `format_text` has a properties key while `format_block` doesn't?)

Thanks in advance!

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3319

If you want to help investigate auto-generated the reference docs from the source code that would be extremely appreciated!
