### ISSUE TITLE
"past-html" not working as expected if you paste HTML starting with a Heading

### ISSUE THREAD

**Issue by lazharichir** [ianstormtaylor/slate#3320]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

See – https://codesandbox.io/s/slate-reproductions-uyh7j?fontsize=14&hidenavigation=1&theme=dark (toggle the "project view" to see it in the browser)

I added some dummy HTML-formatted text under Slate.

If you copy and paste a paragraph and any heading at the same time, all seems well.

If you copy and paste a heading and its below paragraph, the heading (h1/h2/..) is not deserialized to its `heading-*` Slate Node. It becomes a paragraph.

![Screen Recording 2019-12-13 at 20 43 37](https://user-images.githubusercontent.com/12215372/70831117-999cd880-1de9-11ea-82f7-46208f6ba6ea.gif)

Slate: 0.54.2
Browser: Latest Chrome
OS: Mac

#### What's the expected behavior?

It should convert the heading being copied to the appropriate `heading-*`.

I've added a `console.log` to show the H1 is indeed copied (see the console on paste).

**Comment by thallada** [comment]
This also happens if the first line of the pasted html is a `<pre><code>...</code></pre>` block. The first line the the editor after pasting will be a `paragraph` instead of a `code` block.

**Comment by aykutkardas** [comment]
Is there a study on this? Or have you found a way to overcome it temporarily? @thallada @lazharichir @ianstormtaylor

**Comment by rohmanhm** [comment]
> This also happens if the first line of the pasted html is a `<pre><code>...</code></pre>` block. The first line the the editor after pasting will be a `paragraph` instead of a `code` block.

I also have the same bug as @thallada .
https://www.loom.com/share/e81143828c00451eb84ea4268194234b

**Comment by irmerk** [comment]
Ran into this issue as well, demonstrated in the Slate examples:

## Selection begins with a heading, heading does not persist:

![Apr-13-2020 13-40-55](https://user-images.githubusercontent.com/36460856/79144229-9e1fd080-7d8c-11ea-902d-a1a399285aa9.gif)

## Selection _contains_ a heading, heading does persist:

![Apr-13-2020 13-44-56](https://user-images.githubusercontent.com/36460856/79144473-0373c180-7d8d-11ea-9da9-72d3f0c5cb8e.gif)

**Comment by gaKoltai** [comment]
I am still having the issue in in v. 0.59. Anyone managed to find a workaround? It seems to copy everything properly except the first line in all cases.

**Comment by dylans** [comment]
This is repeatable whenever the start of the selection is not a paragraph. You lose the start of the selection prior to the first paragraph. This is true with headings, links, as well as nearly everything in slate-plugins (lists, tables, etc.).

**Comment by bobywoodwarrior** [comment]
Also have this issue, any news on this bug ?

**Comment by hugoobauer** [comment]
The bug is still there. Does anyone know if there is a workaround ?

**Comment by phronaeus** [comment]
Also looking for a workaround if anyone has found one.

**Comment by DougReeder** [comment]
This issue still exists as of v 0.65.3. It's not confined to pasting HTML - on any call to `Transforms.insertFragment(editor, slateNodes)` where `slateNodes` starts with `{type: 'heading...', ...}` the type will be ignored.

I'd be happy to create a test case for `insertFragment`, if someone can point me to the right file.

**Comment by dylans** [comment]
Fixed in #4489 0.66.0 release will include it.
