### ISSUE TITLE
add support for ctrl-k on mac

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#333]
It should delete forward to the end of the current line. It should be a super simple change in `./plugins/core.js` if anyone wants to make it! Check out the regular delete handling to see how "delete forward line" works.

**Comment by edencore** [comment]
Hi @ianstormtaylor!
I found that 
```
return state
      .transform()
      .deleteForward(startBlock.text.length - startOffset)
      .apply()
```
does the trick - removes all text till the end of the line (or better to say - to the end of the block). Can I use that code? I feel like I forgot something 🤔

**Comment by ianstormtaylor** [comment]
Yup that sounds about right! If you check out the existing delete handler for <kbd>delete+option</kbd> on the Mac it would be the same as that.
