### ISSUE TITLE
`Editor.*` docblock comments aren't preserved in TypeScript?

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3330]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

The `Editor.*` helpers don't preserve their docblock comments in the TypeScript `.d.ts` files, which means the docs don't show up in VS Code's IntelliSense. 

I'm not sure why this is happening. I think it has to do with the spreading into a new object here:

https://github.com/ianstormtaylor/slate/blob/63a94a23c7f811d1b4be248f35fbd3251af4858c/packages/slate/src/interfaces/editor/index.ts#L31-L40

You can actually see this in `./dist`:

- `./dist/interfaces/editor/index.d.ts` does NOT have comments.
- `./dist/interfaces/editor/queries/*.d.ts` does have comments.

If someone who's more familiar with TypeScript compilation could figure this one out that would be **very** appreciated!

We might have to not spread anymore, and make things in a big file? That would be unfortunate.

**Comment by lazharichir** [comment]
Related to this typescript's issue https://github.com/microsoft/TypeScript/issues/14619 – still opened and unresolved! A pain point for many... Will do some research to see if there's something to solve this.

**Comment by ianstormtaylor** [comment]
Don't think we want to go with auto-generated docs in the end—never seems to work well—so closing this.
