### ISSUE TITLE
Really strange bug when React takes a long time to update DOM.

### ISSUE THREAD

**Issue by marcandrews** [ianstormtaylor/slate#3332]
## Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

First things first, this React app is very complex. It has a complex form that is connected to Redux and when the user changes a form field, a lot of other elements on the page update as well (think of an online page builder with live preview) ... so the app is a bit laggy ... plus, this is in development mode (CRA) with React and Redux Dev Tools enabled, making things lag even more. The production build is much more performant, but I have not tried to recreate this bug in a production build.

I am using Slate like a _controlled component_.

Adding or deleting characters is working fine, but when I attempt to insert a new line into the editor, I am encountering a really strange bug. It looks like the internal State updates, but when Slate tries to reconcile the internal state with that of the DOM, and the DOM hasn't updated due to low performance/lag, Slate encounters the error `Cannot find a descendant at path [x,y] in node: { ... }`. Anyway, this is just speculation on my part.

I was able to reproduce the error in Codesandbox by wrapping the Redux `dispatch` in a `setTimeout` to simulate a laggy app. 

![output](https://user-images.githubusercontent.com/3518829/70966574-b93e3600-2061-11ea-8a21-f9c88524630a.gif)

Codesandbox: https://codesandbox.io/s/vigorous-leftpad-6q3xv

Stack trace:
```
Uncaught Error: Cannot find a descendant at path [1,0] in node: {"children":[{"type":"paragraph","children":[{"text":"This is editable plain text, just like a <textarea>!"}]}],"operations":[{"type":"split_node","path":[0,0],"position":13,"target":null,"properties":{}},{"type":"split_node","path":[0],"position":1,"target":13,"properties":{"type":"paragraph"}}],"selection":{"anchor":{"path":[1,0],"offset":0},"focus":{"path":[1,0],"offset":0}},"marks":null}
    at Object.get (VM464 index.js:6199)
    at Object.node (VM464 index.js:2751)
    at Object.toDOMPoint (VM468 index.js:1616)
    at Object.toDOMRange (VM468 index.js:1675)
```
Slate: 0.55.2 (also 0.53.0)
Slate React: 0.55.3 (also (0.53.0)
Browser: Chrome (maybe others)
OS: Mac (maybe others)

#### What's the expected behavior?

Inserting a new line in a laggy app should not break the editor.

This seems to be a really weird problem even though Redux is synchronous. The solution seems very complex, involving some kind of wait mechanism to ensure that DOM has been updated. I would love to submit a PR provided I receive some direction on potential solutions.

**Comment by marcandrews** [comment]
One potential workaround is to bypass the Redux lifecycle by copying the value into into internal state:
https://codesandbox.io/s/blissful-monad-juddz

**Comment by marcandrews** [comment]
I am unable to reproduce this bug in `0.57.1`.

Thanks ❤️

**Comment by arpit016** [comment]
@marcandrews I am still getting the same issues in 0.57.1, if there is some lag from redux side, the editor crashes. Can you share some codesandbox snippet where you are actually updating from the redux and not bypassing it?

**Comment by arpit016** [comment]
@ianstormtaylor @thesunny

**Comment by marcandrews** [comment]
I am still bypassing redux by copying the value into internal component state and only dispatching my update action if the value changes.

**Comment by nomadus** [comment]
I have the same issue "Error: Cannot find a descendant at path [0,0] in node: {"children":[{"text":"[object Object]"}],"operations":[],"selection":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}},"marks":null,"history":{"undos":[[{"type":"set_selection","properties":null,"newProperties":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}}}]],"redos":[]},"id":"description","spellCheck":true}", my environment is:
    
"slate": "^0.58.1",
"slate-history": "^0.58.1",
"slate-hyperscript": "^0.58.1",
"slate-react": "^0.58.1",

**Comment by nomadus** [comment]
I reverted to 0.57.1, unfortunately, the issue is still there.  I can't share the code, but redux is being used.

**Comment by ebasic** [comment]
Maybe this would work.....add this code in your Slate editor component (root component that accepts editor `value`):

```
  useEffect(() => {
    if (!value) {
      Transforms.deselect(editor);
    }
  }, [value]);
```

You are getting error because value becomes blank  and selection remains whatever it is, so you should reset editor selection in case of blank value.
