### ISSUE TITLE
In selection, anchor is always left of the focus

### ISSUE THREAD

**Issue by sirgru** [ianstormtaylor/slate#3333]
Bug (probably)

When a selection is made, even from right to left, anchor is always left of the focus. So isForward always returns true. 

#### What's the current behavior?
https://codesandbox.io/s/slate-reproductions-qm103
![http://g.recordit.co/WRwnEkbDQF.gif](http://g.recordit.co/WRwnEkbDQF.gif)
Slate: 0.55
Browser: Chrome
OS: Windows

#### What's the expected behavior?
Anchor should stay where selection begins, and focus should be where it ends.

**Comment by kilrain** [comment]
I think the issue lies in these lines...  

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugin/react-editor.ts#L467-#L470

**Comment by jerkly** [comment]
Workaround at this time:
```typescript
const selection = window.getSelection();
const range = ReactEditor.toSlateRange(editor, selection);
const isBackward = Range.isBackward(selection);
```

Main problem is located in `onDOMSelectionChange:359` method. 
For some reason DOMSelection is "converted" to DOMRange, which is not store any information about direction of selection. As a result `Editor.selection` always has forward direction.
https://github.com/ianstormtaylor/slate/blob/1d7ab974292a3e831908a2ba0aab9fdd8a66fe10/packages/slate-react/src/components/editable.tsx#L353-L384
