### ISSUE TITLE
Firefox: wrong selection with double click on a text node

### ISSUE THREAD

**Issue by cvlmtg** [ianstormtaylor/slate#3336]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

double click on a word in an unformatted paragraph (i.e. made of just one `text` node) and apply some formatting. then deselect and select it again. even if the browser shows the word as selected, slate has selected the whole paragraph. you can see it because the next style is applied to the whole line and not just the word. on Chrome it seems to work correctly.

![Registrazione schermo 2019-12-17 alle 22 24 42](https://user-images.githubusercontent.com/6401008/71035749-71301980-211c-11ea-98f6-b38fd8c60184.gif)

Slate: 0.55.2
Browser: Firefox
OS: Mac

#### What's the expected behavior?

slate should select the word, not the whole paragraph

**Comment by sirgru** [comment]
Just discovered this issue myself. In Firefox, anchor and cursor do not always return the path of the inner node when double clicking. Instead the paths seems to bleed into the previous/next node, What I've found is sometimes the selection works properly with manual drag.

**Comment by cvlmtg** [comment]
@sirgru yes, that should be fixed by #3374

**Comment by dylans** [comment]
This has a potential fix in #3374, but it was never finished. If someone wants to revisit I suggest starting there. Thanks.
