### ISSUE TITLE
remove redundant method Editor.unsetNodes

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3343]
#### Do you want to request a _feature_ or report a _bug_?

remove unnecessary method

#### What's the current behavior?

Currently we can use `setNodes` with `null` property values or `unsetNodes` with an array to remove properties from nodes.

Slate: 0.50+

#### What's the expected behavior?

As per Slack discussion with Ian, we can remove the `unsetNodes` method since it's now unnecessary.

**Comment by dylans** [comment]
Given the feedback in https://github.com/ianstormtaylor/slate/pull/3353#issuecomment-894975949 , it seems like keeping the `unsetNodes` method may be convenient enough to not remove. Let me know if we should close this out or proceed with removing.

**Comment by thesunny** [comment]
I'm okay with keeping it as a convenience feature. If we are doing a bigger cleanup of the API removing unnecessary methods, maybe we could reconsider it then.
