### ISSUE TITLE
consider reducing verbosity of commands

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3344]
In the newest version of Slate, there is now a separation between **Commands** and **Transforms**...

- **Commands** are user-level actions that are taken on the editor. They correspond directly to user input, and always operate on the current selection. They are _overridable_ because this allows plugins to define complex behaviors (eg. auto-markdown).

- **Transforms** are slightly lower level (but not as low as **Operations**), and are designed to make it easy to perform many types of changes to a Slate editor's content. They're not overridable, they're just functional helpers. And they do not always act directly on the current selection, they can act on any location. They're what you'd build commands from.

This distinction is very helpful.

But... the downside is that implementing every type of action a user can perform as commands is very verbose. You end up having to thread every custom command through the `exec` function. 

It feels like using Redux, and that's not a compliment IMO.

---

I think there's a good argument for trying to simplify this.

And it comes down to the question of whether **userland** commands need to be overridable by plugins. I'm not sure there are great use cases for this. This "requirement" is a vestige of the old Slate architecture.

The only ones that come to mind for me are Redux-like use cases like a global logger, but those are honestly pretty weak. (Even the examples Redux gives in its documentation for what you'd use middleware for are very contrived.) And we already have operations for global undo/redo.

If we need non-core commands to be overridable we've got to stick with the current state of things. But if we don't...

---

Instead of modeling commands as objects that pass through `exec`, we could promote the core commands to live directly on the `Editor` object. For example:

```js
editor.insertText('string')
editor.deleteForward({ unit: 'word' })
editor.undo()
```

And these are still available to be overridden by plugins, the same way that `exec` or `isVoid` are already overridden.

Combine that with moving the existing transforms to a separate object to make it clear these are not user-level actions:

```js
Transforms.insertText(editor, 'string', { at: range })
Transforms.unwrapNodes(editor, { match: ... })
```

And then finally, (this one will confuse you if you're still thinking in the current terms), create default helpers for the core commands on the `Editor`:

```js
Editor.insertText(editor, 'string')
Editor.deleteForward(editor, { unit: 'word' })
Editor.undo(editor)
```

I know that last step _sounds_ confusing given the current API. But what it actually does it is allows the `Editor` helper namespace to be properly customized by end-users the way they'd expect it to be. **Instead of having to thread commands objects through `exec` like you're building a Redux app.**

For example, you can now define your own helpers which blend in:

```js
Editor.insertParagraph(editor)
Editor.formatLink(editor, 'https://example.com')
```

All depending on your schema.

---

I'm fairly sure this is a good idea.

If you have use cases where you **need** userland commands to be overridden by a plugin, please let me know! That's the only real tradeoff that this makes.

**Comment by thesunny** [comment]
I'm trying to clarify this for myself. Could you tell me if this understanding is accurate?

### `editor` instance methods

Use it to execute an action on the current selection

```js
editor.insertText('string')
editor.deleteForward({ unit: 'word' })
editor.undo()
```

### `Transform` static methods

Use it to execute an action at an arbitrary location (point, range, etc)

```js
Transforms.insertText(editor, 'string', { at: range })
Transforms.unwrapNodes(editor, { match: ... })
```

### `Editor` static methods

```js
Editor.insertText(editor, 'string')
Editor.deleteForward(editor, { unit: 'word' })
Editor.undo(editor)
```

Still trying to understand this properly. From what you've written, it sounds like `editor.insertText('hello')` calls `Editor.insertText(editor, 'hello')`.

You can override the `editor.insertText` instance method by replacing it on the `editor` instance object with your own and calling out to the old one if necessary (same way that's being done in 0.50+). You should not replace core static methods on `Editor` but you are allowed to add new static methods to `Editor` which become helper methods.

What I'm finding challenging about this is the following (if I'm understanding this correctly):

- To extend core methods, you modify the `editor` instance but must **not** touch the core `Editor` static methods.
- To add helpers, you must **not** modify the `editor` instance but you should add `Editor` as static methods.

I'm probably missing something but why not add helpers to the `editor` instance if you are okay with modifying the `editor` object to override (i.e. `editor` isn't sacred/can't be touched)? These helpers could also be overridable in the same way that core `editor` instance methods are (plus a check to see if a parent method exists in some cases).

This protects the `Editor` namespace (which is shared across editor instances). e.g. different instances of the Slate Editor using different plugins may end up with name collision in `Editor`.

**Comment by mms-uret** [comment]
I think this would simplify writing plugins as well.

To explain: At the moment, if you want to have an imge plugin which supports say `{type: 'image'}` elements, you write the new command `insert_image` in the editor interface (as stated in the plugin docs) but you also need to have a renderElement function for the `<Editable>` which knows how to render the elements with type 'image'. And you probably have other plugins which know how to render its type. So you kind of have to 'compose' the renderElement function.

For the command part the way of composing it is given by overriding the exec function.  For the renderElement (and renderLeaf) function this is completely up to the plugin author. Given the overriding for the command part, doing the same for the render functions seems encouraged. Which leads to some boilerplate code and this "reduxy" way of doing things, imho.

As I understand this change would encourage a more "functional" approach for plugins, like extending the `Editor`, so I like it :) But just my 2 cents....

**Comment by BrentFarese** [comment]
We are using Typescript to implement our editor and we have entirely moved away from using `editor.exec` to using our own custom Transforms.  The reason for this is that we could not figure out a viable way for us to get type-safety with overriding `editor.exec`.  For instance, we wanted our overrides of `editor.exec` to only accept Commands of the type that we have in our implementation, but could not land on a viable way to do that in the current pattern that is supported in Slate (as `editor.exec` expects a Command of the type specified in Slate core).  So, we moved entirely to our own custom Transforms where we can explicitly define the type for arguments that are passed to that Transform.

This has worked very well for us and I think is 1 of your suggested options above.  We actually did not find much utility in using the `editor.exec` pattern and felt it was similar to a middleware stack where your Command must be passed through each exec function until it hits the right function.

In any case, for people using Typescript in their projects, the above way gives good type-safety in userland and didn't really sacrifice any flexibility in the implementation.

**Comment by rikkit** [comment]
> (as editor.exec expects a Command of the type specified in Slate core).
As an aside, there might be a way to improve the typing to work around this. Something like `const exec = <T extends Command>(command: T) => {}`

**Comment by ianstormtaylor** [comment]
> @thesunny: I'm trying to clarify this for myself. Could you tell me if this understanding is accurate?

More like:

```js
// Use it to make arbitrary changes, usually many of these are
// built up to create the effect of a single user action.
Transforms.unwrapNodes(editor, ...)
Transforms.setNodes(editor, ...)
...

// Use them, and define your own, to take action from user input.
Editor.insertText(editor, 'text')
Editor.addMark(editor, 'bold', true)
...

// You don't ever call these, but they can be overridden by plugins
// that wish to alter the default behaviors for built-in actions.
editor.insertText('text')
editor.deleteForward('character')
...
```

> @mms-uret: Given the overriding for the command part, doing the same for the render functions seems encouraged.

Actually this has no impact on the `render*` functions. I'd still personally recommend not conflating them with editor behaviors, and keeping rendering as a separate concern. But of course anyone can define their own editors however they'd like.

> @BrentFarese: This has worked very well for us and I think is 1 of your suggested options above.

Yup! The idea is to basically move to doing exactly what you're doing out of the box.

Technically, you could easily define an `Editor.exec(editor: MyEditor, command: MyCommand)` function already which would give you type safety. But getting the unwrapped `editor.exec` function to be type-safe out of the box was something I tried to do implicitly but couldn't really get TypeScript to give us.

Either way, this should simply things in TypeScript a lot I think.

I'd even love to potentially make the `editor.*` functions protected or private or something so that people are encouraged to always use the `Editor.*` helpers instead. I might need a more advanced TypeScript-er to figure that out though.

> @rikkit: As an aside, there might be a way to improve the typing to work around this. Something like const `exec = <T extends Command>(command: T) => {}`

I think you are right. If you define your own `MyEditor` you should be able to narrow that interface and get type checking by default.

What I couldn't get working was un-narrowing the interface if the core `Editor` used `CoreCommand` instead of the abstract `Command`. Which is around when I gave up 😄

**Comment by gracicot** [comment]
> If you have use cases where you **need** userland commands to be overridden by a plugin, please let me know! That's the only real tradeoff that this makes.

Unless I'm mistaken, you ask if plugins should be able to override built-in commands from Slate?

If so, yes we use that a lot. For example, we piggyback on commands to exact information on what editing actions has been done. We also change how some commands act, the soft break plugin is a great example of this. We even override how selection should act in some case and how much character should the backspace delete.

**Comment by ianstormtaylor** [comment]
@gracicot not for the built-in commands, but for userland commands.

**Comment by ianstormtaylor** [comment]
(And actually, you can still override them. You just have to be aware of the specific type of the `Editor` you are dealing with. Which actually seems like a net positive.)

**Comment by thesunny** [comment]
Hi Ian, thanks for the clarification.
