### ISSUE TITLE
OnSelect sometimes returns the old value

### ISSUE THREAD

**Issue by sirgru** [ianstormtaylor/slate#3348]
#### Do you want to request a _feature_ or report a _bug_?
Report a _bug_.

#### What's the current behavior?
I have noticed the onSelect event sometimes runs with the old selection value, sometimes with the new selection. 
If you select text multiple times, in combinations of range select and click especially, every once in a while it will report the old value. 
This makes certain other kinds of bugs hard to catch for developers, because the behavior is erratic.

https://codesandbox.io/s/slate-reproductions-8n7q5
https://recordit.co/j053446P1S
![http://g.recordit.co/j053446P1S.gif](http://g.recordit.co/j053446P1S.gif)

Slate: 0.56.0
Browser: Chrome
OS: Windows

#### What's the expected behavior?
onSelect should fire consistently, with the value of the new selection made.

**Comment by sirgru** [comment]
Another thing I've noticed: setting any kind of value via hooks in `onSelect` sometimes returns the cursor to the previous position. This seems related.

**Comment by ianstormtaylor** [comment]
The `onSelect` handler is a synthetic React polyfill that isn't really triggered when the selection changes (it's trigger on click, on keydown, etc.). Unfortunately the React events started out as proper spec-compliant polyfills, but that was years ago and they haven't kept pace, so these days there are many gaps that aren't properly covered and it doesn't seem like they're going to fix the synthetic events at all. Here's an issue specifically tracking `selectionchange`: https://github.com/facebook/react/issues/5785

If you're looking to do things when the editor's selection changes you should likely use `onChange` instead. I'd be open to adding an `onDOMSelectionChange` if someone wants to PR to get the real DOM event which would actually be accurate.
