### ISSUE TITLE
0.14 regressions!

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#335]
Hey all,

Just wanted to give a quick update. I released `0.14` which was a huge refactor of how transforms work internally to be able to get one step closer to being able to use OT/CRDT with the editor for collaborative editing. The release didn't significantly change the API at all, but there were several regressions to behavior that was working fine before. (This is beta software after all!)

I'm working to get these regressions fixed. (And if you want to help with pull requests that would be super amazing!) But if you don't want to bother with them right now, feel free to use `0.13` for a bit while they are ironed out. The migration path from `0.13 -> 0.14` is super simple, so it won't be hard when you want to upgrade later.

Just a heads up! Thanks

---

A list of the regressions:
- [x] https://github.com/ianstormtaylor/slate/issues/326
- [x] https://github.com/ianstormtaylor/slate/issues/327
- [x] https://github.com/ianstormtaylor/slate/issues/325
- [x] https://github.com/ianstormtaylor/slate/issues/312
- [x] https://github.com/ianstormtaylor/slate/issues/311
- [x] https://github.com/ianstormtaylor/slate/issues/306
- [x] https://github.com/ianstormtaylor/slate/issues/318
- [x] https://github.com/ianstormtaylor/slate/issues/341
- [x] https://github.com/ianstormtaylor/slate/issues/348
- [x] https://github.com/ianstormtaylor/slate/issues/346
- [x] https://github.com/ianstormtaylor/slate/issues/304
- [x] https://github.com/ianstormtaylor/slate/issues/330
- [ ] https://github.com/ianstormtaylor/slate/issues/331
- [x] https://github.com/ianstormtaylor/slate/issues/347
- [ ] https://github.com/ianstormtaylor/slate/issues/350

**Comment by SamyPesse** [comment]
Hi @ianstormtaylor I'm starting a PR to fix #318

I'll publish it in the next 24hours.

**Comment by ianstormtaylor** [comment]
Making progress!

For anyone who wants to help speed things up, the most helpful thing you can do after reporting issues (which is great!) is to submit a pull request with a failing test case for the specific transformation behavior you're seeing. This helps speed things up in the debugging process for me a lot 😉  thanks!

**Comment by ianstormtaylor** [comment]
Closing this group issue since most of them are fixed now with `0.15`.
