### ISSUE TITLE
can't programmatically focus the editor anymore...

### ISSUE THREAD

**Issue by cvlmtg** [ianstormtaylor/slate#3360]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

There's no longer a way to give programmatically focus to the content-editable element.
In slate 0.4x it was possibile to attach a ref to the `<Editor>` component. This is no longer the case because `<Editable>` is a stateless component

Slate: 0.57.0
Browser: all
OS: all

#### What's the expected behavior?

It should be possible to give focus programmatically to the editor

**Comment by Killavus** [comment]
Isn't `ReactEditor.focus` function does what you want to achieve?

**Comment by cvlmtg** [comment]
@Killavus no idea because it's basically undocumented and I didn't know it existet. I'll try it.

**Comment by cvlmtg** [comment]
@Killavus yap it works, thanks!

**Comment by MarkPare** [comment]
Is this documented anywhere?

**Comment by paullaffitte** [comment]
@MarkPare I found that you can import ReactEditor from slate-react and it has a [focus](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugin/react-editor.ts#L116) method. Here is how you can use it.

```js
import { ReactEditor } from 'slate-react';
ReactEditor.focus(editor);
```

With `editor` being an instance of your editor. You can get it from `createEditor()` or `useSlate()` depending on where do you need it.

**Comment by dons20** [comment]
This really needs to be documented...
