### ISSUE TITLE
Expose constants for keyboard events

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#337]
⚠️ This is **not** an important issue.

In all the plugins we are working on at GitBook (`slate-edit-code`, `slate-edit-list`, `slate-edit-blockquote`, etc), we are adding [these lines](https://github.com/GitbookIO/slate-edit-code/blob/master/lib/index.js#L6):

``` js
const KEY_ENTER     = 'enter';
const KEY_TAB          = 'tab';
const KEY_BACKSPACE = 'backspace';
```

It might be great if slate can expose these constants:

``` js
const Slate = require('slate');

Slate.KEY_ENTER, ...
```

**Comment by thesunny** [comment]
Since it's an easy one, decided to make a pull request for it.

Will add documentation if PR accepted.

**Comment by ianstormtaylor** [comment]
Hey sorry for the delay here. I'm not yet sure I want to do this, because I'm not yet sure how useful it would be compared to people who want more control using something like Flow or Typescripts. Since I'm unsure, I'm currently defaulting to not adding it, just because it adds API scope.

**Comment by ianstormtaylor** [comment]
I'm going to close this for now, since I'd rather not do this I think for bloat reasons. But if someone wants to implement this as another library that works! And if it gets popular we can consider merging it into core.
