### ISSUE TITLE
Click on the picture scroll distance problem

### ISSUE THREAD

**Issue by undeadfrost** [ianstormtaylor/slate#3391]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

Slate: 0.53.0
Browser: Chrome
OS: [Windows]

Click on the picture scroll distance problem, can I disable scroll events after clicking an image?

#### What's the expected behavior?

Disable scroll events after clicking an image

**Comment by thesunny** [comment]
Sorry, can you elaborate?

What does "Click on the picture scroll distance problem" mean?
