### ISSUE TITLE
Transform to move Node as last child for a given path

### ISSUE THREAD

**Issue by macrozone** [ianstormtaylor/slate#3417]
#### Do you want to request a _feature_ or report a _bug_?

feature request. i asked in slack if there is  api for that, but it seems its not possible.

Slate: 0.57.0
Browser: Chrom
OS: Mac 

It should be possible to move a node as a child of another node. E.g. moving a node as child of the previous sibling:

```


 const previous Editor.previous(editor, {
    match: elem => elem.type === sometype,
  });

Transforms.moveNodes(editor, {
      match: elem => elem.type === someothertype
      to: previous[1] // what to do here???
    });


```

the above example moves the item before the previous instead as a child. I also tried:

```
Transforms.moveNodes(editor, {
      match: elem => elem.type === someothertype
      to: previous[1].concat(0)
    });
```

which unexpectedly replaces the previous sibiling with the current node and

```
Transforms.moveNodes(editor, {
      match: elem => elem.type === someothertype
      to: previous[1].concat(1)
    });
```

just removes the current node

**Comment by macrozone** [comment]
I figured out my particular problem, but it took me incredibly long to understand what can go wrong with this new api:

- `Transforms.moveNodes` will just silenty remove nodes if they are text nodes and will be placed next to non-text nodes
- `Editor.previous` is still a riddle to me, luckely i could avoid using it.
- working with Paths and Editor.node(editor, path) was more intuitive and lead me to success (after 10 hours of try&error

I am sure that a lot of thought has been put into this new api and its probably very powerful, but the lack of documentation and a lack of help in the slack channel makes it currently a huge challenge to use. 

I think we need a `needs documentation` label for some common api problems / recipes

**Comment by gavriguy** [comment]
Hi @macrozone can you share how you were able to do what you did? I'm struggling on the same thing
10x

**Comment by macrozone** [comment]
@gavriguy can't really explain, but here is our code in @react-page: https://github.com/react-page/react-page/blob/master/packages/plugins/content/slate/src/pluginFactories/utils/listUtils.ts

**Comment by mukeshsoni** [comment]
Here's a codesandbox for what @macrozone was talking about - https://github.com/ianstormtaylor/slate/issues/3417

`Transforms.moveNodes` eats up the node to be moved.
