### ISSUE TITLE
operation to replace document entirely?

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#342]
My editor is partially-collaborative, in the sense that multiple people can edit documents at the same time, but they can't see what the other people are doing. This mostly works in practice since we have a limited number of people working in the same document and even fewer working in the same Slate editor.

When changes happen, the new complete document (stored in HTML) is distributed to other clients and the other clients silently swap it out with the old state. The issue I am facing now is that the undo/redo history is removed since it is a brand new state. In the pre-0.14 transform I could simply save a new version of the document into the history, however with this new operation-based transform that is not so easy.

So is it possible to get an operation that totally overwrites the state's document with a new document?

**Comment by ianstormtaylor** [comment]
I don't think this is something that will become an operation, since the operations are intended to be small for OT/CRDT use. However, it could become a transform if it proves useful to enough people.

Although for now what you could do is manually make the same thing happen, by looping the document and removing all the top-level nodes. And then looping the new document and inserting all of its top-level nodes. Hope that helps!

**Comment by ianstormtaylor** [comment]
PS. Of course you could also migrate to an operation-based update schema, where you just send each set of operations over the wire instead, and apply them in the other persons editor (without performing OT) and then I think the history would work like normal.

**Comment by tyler-johnson** [comment]
@ianstormtaylor thanks for the suggestion!

The transform goes through fine, but the editor gets into a state where further edits throw these errors:

```
Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".
```

```
Error: Could not find a descendant node with key "a5ok".
```

Here is the transform I am using. I am doing something incorrectly? or perhaps this is related to #353?

```js
let transform = state.transform();

state.document.nodes.forEach(n => {
  transform = transform.removeNodeByKey(n.key);
});

newstate.document.nodes.forEach((n, index) => {
  transform = transform.insertNodeByKey(state.document.key, index, n);
});

state = transform.apply();
```

**Comment by ianstormtaylor** [comment]
Hmm that first error is particularly strange, do you happen to have a stack trace to know why `null` is passed as a key somewhere? Not sure what would be causing that.

**Comment by chilijung** [comment]
I've also get the error

```
Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".
```

when using `removeNodeByKey` API. I've tried to find out why, but still can't find what cause the error.

**Comment by sdemontfort** [comment]
I can run `removeNodeByKey` without an error, but  as soon as I type into the editor afterwards, I get the error:
`Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: null`

My editor is also shown as empty, with no elements inside it whatsoever.

Is this still a known problem?

**Comment by Java-Jonas** [comment]
Same problem as @sdemontfort . Can't find a way to work around it.
