### ISSUE TITLE
Path.previous should not throw if there is no previous path 

### ISSUE THREAD

**Issue by macrozone** [ianstormtaylor/slate#3422]
#### Do you want to request a _feature_ or report a _bug_?

feature request (or flaw)

#### What's the current behavior?

`Path.previous(path)` throws an error when path is first path (e.g. ends with 0):

"Cannot get the previous path of a first child path ... because it would result in a negative index."

#### What's the expected behavior?

It should not throw and instead return null. This is much easier to work with, in particular with typescript as you would mark the result type as optional.

This is in particular critical because:

- there is no method Path.hasPrevious to guard this situation
- Path objects should be opaque i guess (e.g. its internal representation as array should not be any concern to devs), thats why a manual check `if(path[path.length - 1] > 0)` is not recommended.

Similarly, other Path functions should not throw.

**Comment by LiuJi-Jim** [comment]
I agree. I think it would be better if `prevous/next/above` etc. return `null/undefined`.
