### ISSUE TITLE
dynamic placeholder isn't supported

### ISSUE THREAD

**Issue by mongris** [ianstormtaylor/slate#3423]
#### What's the current behavior?

1. Keep slate editor empty
2. Change placeholder value at short interval 
3. placeholder never changed after slate be initialized

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

Show correct placeholder as expected.

**Comment by lostpebble** [comment]
Yea, have this issue too - would like to dynamically change it according to an earlier form input. To say something like: `Add a description for ${name}`

Probably related to #3432
