### ISSUE TITLE
Slate value is of type Node[]

### ISSUE THREAD

**Issue by lcswillems** [ianstormtaylor/slate#3448]
#### What's the expected behavior?

I would like Slate value type to be equal to the type of the value I give it.

Making Slate generic would help I think.

**Comment by timbuckley** [comment]
Related to (duplicate of?) #3416

**Comment by lcswillems** [comment]
I am not sure

**Comment by martonlanga** [comment]
Just in case: are you importing the Node type from slate? I've had conflicts like this before because there is also a built-in Node type. But importing it like this works for me: `import { Node } from 'slate'`

If you're trying to use a custom type, then ignore this.

**Comment by BrentFarese** [comment]
Closing this as it's somewhat broad and not specific.  There are other issues too for making Slate's types more generic.  It is on the long-term roadmap.
