### ISSUE TITLE
Selecting entire block and then calling wrapNodes wraps the next block as well as the current block

### ISSUE THREAD

**Issue by mpkelly** [ianstormtaylor/slate#3454]
I figured this has already been reported but I couldn't find it. I ran into this issue when working with links and have reproduced it using the Links example. Here is a video

https://drive.google.com/file/d/1z3M7SkyRFQyDzeuf1LqzYrX5HACz-UcC/view

The problem is that when you select the entire block and then call:

```
 Transforms.wrapNodes(editor, link, {
        at: selection as Range,
        split: true
      });
```

Slate is wrapping the following block as well. Hopefully that's enough info and sorry if this is a dupe.

**Comment by cvlmtg** [comment]
on which browser? because there's a known bug on firefox with selection (https://github.com/ianstormtaylor/slate/pull/3374)

**Comment by mpkelly** [comment]
@cvlmtg Apologies for not including that. This is happening on Google chrome: `Version 79.0.3945.117 (Official Build) (64-bit)`

**Comment by pauliusef** [comment]
I'm experiencing the same issue, only with applying list styles. I found, that this issue has been solved in previous versions but either it re-surfaced or hasn't been solved fully (See for example #2503)

Issue can be reproduced in http://slatejs.org/#/rich-text. Triple click to select the first paragraph. Click ordered/unordered list button. See, that the previous block gets added inside the list element.

**Comment by czechdave** [comment]
This case seems to be fixed with `{ hanging: false }`

```js
Transforms.wrapNodes(editor, link, {
    at: selection as Range,
    split: true,
    { hanging: false }
});
```

**Comment by mpkelly** [comment]
Hi @czechdave , thanks for posting. I don't see hanging as an option in the 0.57.1 API for `wrapNodes`. Are you referring to a patch? 

I don't have time to jump into the Slate source right now but the type definition file shows this:

```TypeScript
    wrapNodes(editor: import("..").Editor, element: import("..").Element, options?: {
        at?: import("..").Path | import("..").Point | import("..").Range | undefined;
        match?: ((node: import("..").Node) => boolean) | undefined;
        mode?: "highest" | "lowest" | "all" | undefined;
        split?: boolean | undefined;
        voids?: boolean | undefined;
    }): void;
```

**Comment by czechdave** [comment]
@mpkelly you are absolutely right. Looks like that options is missing specifically from `wrapNodes` but is available on most of the other Node methods.

Here's an example of what that option does: https://github.com/ianstormtaylor/slate/blob/0bbe121d76c5c2313d939de8a7ebed3bfd37f62d/packages/slate/src/transforms/node.ts#L465-L467

So for now it should be fairly simple to workaround by doing:
```js
Transforms.wrapNodes(editor, link, {
    at: Editor.unhangRange(editor, editor.selection),
    split: true,
});
```

**Comment by mpkelly** [comment]
Thanks for the update, @czechdave. It looks like [0.57.2 was about to be released](https://github.com/ianstormtaylor/slate/commits/master) but was then backed out. I guess it wont be too far away, so I will probably just update whenever that lands rather than build from master. 

Closing.

**Comment by htulipe** [comment]
I'm facing this issue, the workaround works great. Is there a plan of adding "hanging" to wrapNodes @czechdave ?

**Comment by czechdave** [comment]
@htulipe I don't know of any plan. You could def submit a PR for it 😉

**Comment by htulipe** [comment]
I'm clearly not confident enough with the codebase 😅
