### ISSUE TITLE
Inline void elements cannot be deleted when selected

### ISSUE THREAD

**Issue by laverdet** [ianstormtaylor/slate#3456]
#### Do you want to request a _feature_ or report a _bug_?
This is a bug report

#### What's the current behavior?
You can reproduce this easily on the Slate mentions example. Go here: https://www.slatejs.org/examples/mentions

*Click* one of the mentions so that it's highlighted with the custom rounded blue border. Now press backspace or delete. You can't delete it when it is selected. If you press right arrow and then backspace it will work fine.

![image](https://thumbs.gfycat.com/ColossalDisguisedKawala-size_restricted.gif)

It seems that block voids work, since `examples/images` works fine.

Slate: 0.57.1
Browser: Version 79.0.3945.117 (Official Build) (64-bit)
OS: macOS 10.15.1 (19B88)

#### What's the expected behavior?
I would expect that pressing delete would delete the mention.

**Comment by laverdet** [comment]
Another issue with void elements, again reproducible in the examples. To reproduce:

* Visit the image example: https://www.slatejs.org/examples/images
* Click the image icon and paste an image URL (try https://source.unsplash.com/kFrdX5IeQzI)
* Cmd+A
* Delete

This will delete all text up to the first image, leaving the rest untouched. It seems to only happen when an image is the last element in the editor.

![image](https://thumbs.gfycat.com/CompletePopularCod-size_restricted.gif)

**Comment by skogsmaskin** [comment]
> This will delete all text up to the first image, leaving the rest untouched. It seems to only happen when an image is the last element in the editor.

This also happens if there is an empty paragraph as last block.

**Comment by abhishekbhardwaj** [comment]
I think it happens whenever a void element is at the start or end of the document.

if you put a checkbox at the top of the doc, it does the same to the actual checkbox.

**Comment by abhishekbhardwaj** [comment]
@laverdet @skogsmaskin I was able to fix this last image issue by doing the following in my `withImages` plugin:

```
editor.deleteFragment = () => {
    const { selection } = editor;

    if (selection && Range.isExpanded(selection)) {
      const images = Array.from(
        Editor.nodes(editor, {
          match: n => n.type === TYPES.IMAGE
        })
      );

      if (!!images.length) {
        // We're only deleting the last image as that's what is always left behind.
        // Slate is handling the rest easily.
        const [, cellPath] = images[images.length - 1];
        Transforms.delete(editor, {
          at: cellPath,
          voids: true
        });
      }
    }

    deleteFragment();
  };
```

We just delete the last image in the selection and leave the rest to Slate

**Comment by calvinwyoung** [comment]
Has anyone figured out a workaround for the first issue (i.e., unable to delete selected inline void elements)? I'm running into the same issue right now.

**Comment by idevelop** [comment]
I'd also be interested in a solid solution to this. 

Here's my current approach, trying to add delete support in the [mentions example](https://www.slatejs.org/examples/mentions) when you click on a specific inline mention. 

```
if (event.key === Keys.BACKSPACE) {
  const { selection } = editor;
  if (selection && Range.isCollapsed(selection)) {
    const currentNode = (value[selection.anchor.path[0]].children as Node[])[selection.anchor.path[1]];
    if (Element.isElement(currentNode)) {
      if (editor.isVoid(currentNode as Element)) {
        event.preventDefault();
        editor.deleteBackward('block');
      }
    }
  }
}
```

It works but feels a bit messy (I've only been developing on Slate for a day). 
Problems I see with this:
- getting the current element is hardcoded and will fail for deeply nested elements. I tried using `Node.get(value, selection.anchor.path)` but when the void element is selected the path actually points to its text leaf, whereas I actually need that leaf's parent.
- `deleteBackward('block')` seems to work and only deletes the mention element, but I'm unsure if it's the right thing to call

**Comment by vujevits** [comment]
seems to be a browser specific issue, it's working in Firefox for Mac.

**Comment by zbeyens** [comment]
So we have 3 cases: 

- All browsers – select all and delete where the last element is void, or a void element followed by one (it's working with two) element with empty text – it's deleting everything except these last elements. Note that without using the history (undo), it's working. [Sandbox](https://codesandbox.io/s/bug-deletefragment-with-history-last-element-is-void-kfwc1). Refresh the sandbox and delete to see it working, undo and delete to see the bug.
- Chrome – select a specific void element and delete – it's not deleting. [Sandbox](https://codesandbox.io/s/bug-deletefragment-first-element-is-void-mtlrn).
- Chrome – select all and delete where the first element is void – it's not deleting anything. [Sandbox](https://codesandbox.io/s/bug-deletefragment-first-element-is-void-mtlrn).

**Comment by camjosen** [comment]
I think I have a fix for case #1. The problem is that `Editor.unhangRange()` is too aggressively trimming the end of selections that contain inline voids.

Initially, my solution was to overwrite `Editor.unhangRange()` to handle inline voids. However, I discovered that `unhangRange()` caused other small UX problems, and I couldn't find of a single situation in which it actually improved UX. So, I decided to overwrite `Editor.unhangRange()` like this:

```typescript
Editor.unhangRange(
  editor: Editor,
  range: Range,
  options: {
    voids?: boolean
  } = {}
): Range => {
  return range;
}
```

It simply returns the range unmodified. All of the bugs and other UX issues seem to have gone away, and I have yet to discover any negative consequence of this change.

What was the original purpose of `Editor.unhangRange()` anyway? Is it meant to fix a bug? Improve UX in some way?

**Comment by pch** [comment]
Also experiencing the issue with images (Chrome, macOS - current demo). Apart from the problem mentioned by @laverdet, when an image is the only element in the editor, nothing can be inserted after it. So basically, when an image is inserted first, it's impossible to add any text. Also, adding an image element keeps placeholder text in place...

**Comment by calliday** [comment]
@pch This issue can be overcome by normalizing your editor after every Transform, appending an empty paragraph below the last node if it is a void type. Maybe there is a better solution though.

Here is a possibly related void deletion issue:

![image](https://user-images.githubusercontent.com/43559869/86624829-3fc84f80-bf81-11ea-805d-16125bc7a16f.png)

It is not possible to delete the empty paragraph in between these two images. I'm experiencing this with any two void blocks with a non-void between them. I have been trying to override `deleteForward` and `deleteBackward` for editable nodes without success.

**Comment by bryanph** [comment]
@calliday I made an issue for what you describe: https://github.com/ianstormtaylor/slate/issues/3991

**Comment by calliday** [comment]
Thank you!

**Comment by clauderic** [comment]
Opened a PR to fix this issue here https://github.com/ianstormtaylor/slate/pull/4307
