### ISSUE TITLE
Pasted HTML content from Google Docs in wrong order and cursor is not at end

### ISSUE THREAD

**Issue by thallada** [ianstormtaylor/slate#3457]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

I have a very basic Google doc: https://docs.google.com/document/d/161uHSpY9kLytIf_izWSeTvVQ5xL5zAZo9D5HbQAxehY/edit?usp=sharing

<img width="227" alt="Screen Shot 2020-01-22 at 1 56 00 PM" src="https://user-images.githubusercontent.com/1505923/72924470-f95a9d80-3d1e-11ea-8557-1485bb180706.png">

When I select the text in the google doc there is a little bit of selectable whitespace at the end of the last sentence:

<img width="258" alt="Screen Shot 2020-01-22 at 1 22 08 PM" src="https://user-images.githubusercontent.com/1505923/72922161-8f3ff980-3d1a-11ea-9290-428bf550f944.png">

If I copy that and then paste it into the slate paste HTML example (https://www.slatejs.org/examples/paste-html), this is the result:

<img width="752" alt="Screen Shot 2020-01-22 at 1 22 43 PM" src="https://user-images.githubusercontent.com/1505923/72922180-97983480-3d1a-11ea-8264-65f3ae536e2e.png">

Note the extra space after the first paragraph and how the cursor ends up after the first paragraph after pasting instead of at the end of the entire pasted content.

If I exclude the extra whitespace at the end of the Google doc:

<img width="199" alt="Screen Shot 2020-01-22 at 1 22 23 PM" src="https://user-images.githubusercontent.com/1505923/72922196-9cf57f00-3d1a-11ea-824e-4ca9e0a00a6e.png">

And paste that in the example, even stranger things happen:

<img width="747" alt="Screen Shot 2020-01-22 at 1 23 05 PM" src="https://user-images.githubusercontent.com/1505923/72922211-a4b52380-3d1a-11ea-9c8a-f75fae878820.png">

The document was pasted out of order. Now the last paragraph is above the ordered list.

For that last example, the link seems to be an important. If I remove the link, pasting with or without the the extra whitespace leaves the paragraphs in the correct order but with the extra newlines and the cursor in the wrong place:

<img width="746" alt="Screen Shot 2020-01-22 at 1 48 18 PM" src="https://user-images.githubusercontent.com/1505923/72923883-e1cee500-3d1d-11ea-827e-e110c5a2f23b.png">

I found this code sandbox of Slate 0.44.9 with copy-and-paste html implemented with the old slate-html-serializer plugin: https://codesandbox.io/s/j4k03k1579

If I paste with or without the extra whitespace, the document is not re-ordered and the cursor always ends up at the end of the pasted content. So, it seems like this issue only started happening in the 0.5X.X rewrite.

### Debug Info

To try to debug this, I made a minimal code sandbox for Slate 0.57.1 with just the `PasteHtmlExample` component: https://codesandbox.io/s/slate-minimal-paste-html-example-gojyi

I added some `console.logs` to get the HTML content of the paste and the resulting fragment that is passed to `Transforms.insertFragment`. Here are the results for pasting the two cases I mentioned above.

This is the HTML content of the paste with the extra whitespace at the end: 
<details><summary>whitespace.html</summary>
<p>

```html
<meta charset="utf-8" /><meta charset="utf-8" /><b
  style="font-weight:normal;"
  id="docs-internal-guid-d1a1747d-7fff-f3f1-4e2c-6a97f2f0102c"
  ><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;">
    <span
      style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
      >Paragraph 1</span
    >
  </p>
  <br />
  <ol style="margin-top:0;margin-bottom:0;">
    <li
      dir="ltr"
      style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;"
    >
      <p
        dir="ltr"
        style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"
        role="presentation"
      >
        <span
          style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
          >One</span
        >
      </p>
    </li>
    <li
      dir="ltr"
      style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;"
    >
      <p
        dir="ltr"
        style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"
        role="presentation"
      >
        <span
          style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
          >Two</span
        >
      </p>
    </li>
  </ol>
  <br />
  <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;">
    <span
      style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
      >Paragraph 2. </span
    ><a href="https://www.google.com/" style="text-decoration:none;"
      ><span
        style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
        >Link</span
      ></a
    ><span
      style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
      >.</span
    >
  </p></b
><br class="Apple-interchange-newline" />
```
</p>
</details>

And, this is the HTML without the extra whitespace:
<details><summary>no_whitespace.html</summary>
<p>

```html
<meta charset="utf-8" /><meta charset="utf-8" /><b
  style="font-weight:normal;"
  id="docs-internal-guid-d045a6c5-7fff-0621-9d25-64383cd41038"
  ><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;">
    <span
      style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
      >Paragraph 1</span
    >
  </p>
  <br />
  <ol style="margin-top:0;margin-bottom:0;">
    <li
      dir="ltr"
      style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;"
    >
      <p
        dir="ltr"
        style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"
        role="presentation"
      >
        <span
          style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
          >One</span
        >
      </p>
    </li>
    <li
      dir="ltr"
      style="list-style-type:decimal;font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;"
    >
      <p
        dir="ltr"
        style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"
        role="presentation"
      >
        <span
          style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
          >Two</span
        >
      </p>
    </li>
  </ol>
  <br /><span
    style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
    >Paragraph 2. </span
  ><a href="https://www.google.com/" style="text-decoration:none;"
    ><span
      style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
      >Link</span
    ></a
  ><span
    style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"
    >.</span
  ></b
>
```
</p>
</details>

This is the diff between the two: http://www.mergely.com/Hy4rKwpT/

The fragment passed to `insertFragment` with the extra whitespace:
<details><summary>whitespace.json</summary>
<p>

```json
[
  {
    "type": "paragraph",
    "children": [
      {
        "text": "Paragraph 1"
      }
    ]
  },
  {
    "text": "\n"
  },
  {
    "type": "numbered-list",
    "children": [
      {
        "type": "list-item",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "One"
              }
            ]
          }
        ]
      },
      {
        "type": "list-item",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "Two"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "text": "\n"
  },
  {
    "type": "paragraph",
    "children": [
      {
        "text": "Paragraph 2. "
      },
      {
        "type": "link",
        "url": "https://www.google.com/",
        "children": [
          {
            "text": "Link"
          }
        ]
      },
      {
        "text": "."
      }
    ]
  },
  {
    "text": "\n"
  }
]
```
</p>
</details>

The fragment passed to `insertFragment` with no extra whitespace:
<details><summary>no_whitespace.json</summary>
<p>

```json
[
  {
    "type": "paragraph",
    "children": [
      {
        "text": "Paragraph 1"
      }
    ]
  },
  {
    "text": "\n"
  },
  {
    "type": "numbered-list",
    "children": [
      {
        "type": "list-item",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "One"
              }
            ]
          }
        ]
      },
      {
        "type": "list-item",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "Two"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "text": "\nParagraph 2. "
  },
  {
    "type": "link",
    "url": "https://www.google.com/",
    "children": [
      {
        "text": "Link"
      }
    ]
  },
  {
    "text": "."
  }
]
```
</p>
</details>

And, diff between the two: http://www.mergely.com/mbMQgV4P/

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

I expect the pasted content to look like it did in the old version of Slate, and that the cursor is at the end of the content after pasting:

<img width="554" alt="Screen Shot 2020-01-22 at 2 03 15 PM" src="https://user-images.githubusercontent.com/1505923/72925012-fad89580-3d1f-11ea-89e0-0f15742ef5b4.png">

**Comment by thallada** [comment]
I tried to reproduce the structure of the Google doc completely within the Slate editor and then printed out `editor.children`:

<details><summary>editor.children</summary>
<p>

```json
[
  {
    "type": "paragraph",
    "children": [
      {
        "text": "Paragraph 1"
      }
    ]
  },
  {
    "type": "paragraph",
    "children": [
      {
        "text": ""
      }
    ]
  },
  {
    "type": "numbered-list",
    "children": [
      {
        "type": "list-item",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "One"
              }
            ]
          }
        ]
      },
      {
        "type": "list-item",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "Two"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "type": "paragraph",
    "children": [
      {
        "text": ""
      }
    ]
  },
  {
    "type": "paragraph",
     "children": [
       {
          "text": "Paragraph 2. "
       },
       {
         "type": "link",
         "url": "https://www.google.com/",
         "children": [
           {
             "text": "Link"
           }
         ]
       },
       {
         "text": "."
       }
     ]
  }
]
```
</p>
</details>

I notice 3 things about this structure that was different from what is pasted:

1. There is no `\n` in the `text` values.
2. Where there is a `{ "text": "\n" }` in the pasted fragment, Slate instead has an empty paragraph: `{ "type": "paragraph", "children": [{ "text": "" }] }`.
3. Top-level text and link nodes in the pasted fragment are wrapped in a top-level paragraph node in Slate.

It seems like Slate does not like to have inline-type nodes in the top-level `editor.children` array.

It looks like `deserializer` was outputting `\n`s because that's how it deserializes the `<br>` tag:

https://github.com/ianstormtaylor/slate/blob/8cd9b793528eb76a4a76940e022854cf33419bc4/site/examples/paste-html.js#L47-L49

To fix that, I deleted that else block and changed it to deserialize into an empty paragraph instead:

```
if (el.nodeName === 'BR') {
  return jsx('element', { type: 'paragraph' }, [{ text: '' }])
}
```

**This fixed the extra whitespace and the cursor positioning after paste.**

I also wrote a small band-aid patch in the [`withHtml` `editor.insertData` override](https://github.com/ianstormtaylor/slate/blob/8cd9b793528eb76a4a76940e022854cf33419bc4/site/examples/paste-html.js#L113-L124) that attempts to wrap any top-level text or inline nodes in paragraphs:

```javascript
const wrapTopLevelInlineNodesInParagraphs = (editor, fragment) => {
  let inlineNodes = []
  const newFragments = []

  const maybePushInlineNodeParagraph = () => {
    if (inlineNodes.length > 0) {
      newFragments.push(jsx("element", { type: "paragraph" }, inlineNodes))
      inlineNodes = []
    }
  }

  fragment.forEach(node => {
    if (Text.isText(node) || Editor.isInline(editor, node)) {
      inlineNodes.push(node)
    } else {
      maybePushInlineNodeParagraph()
      newFragments.push(node)
    }
  })
  maybePushInlineNodeParagraph()

  return newFragments
}
```

Which I use in the `withHtml` plugin like this:

```javascript
editor.insertData = data => {
  const html = data.getData("text/html")

  if (html) {
    const parsed = new DOMParser().parseFromString(html, "text/html")
    const fragment = deserialize(parsed.body)
    let fragmentWithOnlyBlocks = fragment
    if (Array.isArray(fragment)) {
      fragmentWithOnlyBlocks = wrapTopLevelInlineNodesInParagraphs(
        editor,
        fragment
      )
    }
    Transforms.insertFragment(editor, fragmentWithOnlyBlocks)
    return
  }

  insertData(data)
}

return editor
```

**This fixed the paragraphs out of order issue.**

Not sure how to integrate these fixes into Slate as a proper PR. I'm also not confident that this patch will corrupt other valid paste cases that I'm not thinking of.

**Comment by iammorganparry** [comment]
> I tried to reproduce the structure of the Google doc completely within the Slate editor and then printed out `editor.children`:
> 
> editor.children
> I notice 3 things about this structure that was different from what is pasted:
> 
> 1. There is no `\n` in the `text` values.
> 2. Where there is a `{ "text": "\n" }` in the pasted fragment, Slate instead has an empty paragraph: `{ "type": "paragraph", "children": [{ "text": "" }] }`.
> 3. Top-level text and link nodes in the pasted fragment are wrapped in a top-level paragraph node in Slate.
> 
> It seems like Slate does not like to have inline-type nodes in the top-level `editor.children` array.
> 
> It looks like `deserializer` was outputting `\n`s because that's how it deserializes the `<br>` tag:
> 
> https://github.com/ianstormtaylor/slate/blob/8cd9b793528eb76a4a76940e022854cf33419bc4/site/examples/paste-html.js#L47-L49
> 
> To fix that, I deleted that else block and changed it to deserialize into an empty paragraph instead:
> 
> ```
> if (el.nodeName === 'BR') {
>   return jsx('element', { type: 'paragraph' }, [{ text: '' }])
> }
> ```
> 
> **This fixed the extra whitespace and the cursor positioning after paste.**
> 
> I also wrote a small band-aid patch in the [`withHtml` `editor.insertData` override](https://github.com/ianstormtaylor/slate/blob/8cd9b793528eb76a4a76940e022854cf33419bc4/site/examples/paste-html.js#L113-L124) that attempts to wrap any top-level text or inline nodes in paragraphs:
> 
> ```js
> const wrapTopLevelInlineNodesInParagraphs = (editor, fragment) => {
>   let inlineNodes = []
>   const newFragments = []
> 
>   const maybePushInlineNodeParagraph = () => {
>     if (inlineNodes.length > 0) {
>       newFragments.push(jsx("element", { type: "paragraph" }, inlineNodes))
>       inlineNodes = []
>     }
>   }
> 
>   fragment.forEach(node => {
>     if (Text.isText(node) || Editor.isInline(editor, node)) {
>       inlineNodes.push(node)
>     } else {
>       maybePushInlineNodeParagraph()
>       newFragments.push(node)
>     }
>   })
>   maybePushInlineNodeParagraph()
> 
>   return newFragments
> }
> ```
> 
> Which I use in the `withHtml` plugin like this:
> 
> ```js
> editor.insertData = data => {
>   const html = data.getData("text/html")
> 
>   if (html) {
>     const parsed = new DOMParser().parseFromString(html, "text/html")
>     const fragment = deserialize(parsed.body)
>     let fragmentWithOnlyBlocks = fragment
>     if (Array.isArray(fragment)) {
>       fragmentWithOnlyBlocks = wrapTopLevelInlineNodesInParagraphs(
>         editor,
>         fragment
>       )
>     }
>     Transforms.insertFragment(editor, fragmentWithOnlyBlocks)
>     return
>   }
> 
>   insertData(data)
> }
> 
> return editor
> ```
> 
> **This fixed the paragraphs out of order issue.**
> 
> Not sure how to integrate these fixes into Slate as a proper PR. I'm also not confident that this patch will not corrupt other valid paste cases that I'm not thinking of.
> 
> Here's a code sandbox of the minimal `PasteHTMLExample` with these fixes: https://codesandbox.io/s/slate-minimal-paste-html-example-with-fixes-p3nxd

You absolute beautiful human being. This was driving me crazy
