### ISSUE TITLE
<input /> elements do not work within renderElement function

### ISSUE THREAD

**Issue by flavordaaave** [ianstormtaylor/slate#3468]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

I more or less copied the code from the image example but instead of an image I'd like to render an `<input />` element.
I managed to get the node's text and pass it as a value to the `<input />` element but the `onChange` handler of the `<input />` element never get's called.

[Sandbox](https://codesandbox.io/s/slate-05x-normalizing-bug-wkrop?fontsize=14&hidenavigation=1&theme=dark)

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

The `onChange` handler of the `<input />` element or event of all elements within a `void` element should not be blocked/interfered.

**Comment by daldoy** [comment]
Has anyone found a workaround?

**Comment by darrensiegel** [comment]
Running into this issue as well.  Slate 0.57.1, Chrome, Mac

**Comment by alfechner** [comment]
Have a look at #3426.

**Comment by CameronAckermanSEL** [comment]
Closing, I think this is fixed in https://github.com/ianstormtaylor/slate/pull/3436
