### ISSUE TITLE
backspacing to the start of an inline node errors

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#347]
From #317:

> Inserting a link at the start of a line, and then backspacing from the end of the link to its beginning: as the first character is deleted it throws Uncaught Error: Could not find a descendant node with key "xinw".

**Comment by joelburget** [comment]
I'd like this fixed and could take a look, but would prefer guidance on how you'd tackle it first.

**Comment by arekkas** [comment]
This is resolved in the 0.15 branch!

**Comment by ianstormtaylor** [comment]
Woot!
