### ISSUE TITLE
`onChange` is not called when using Cypress's `type` command

### ISSUE THREAD

**Issue by achou11** [ianstormtaylor/slate#3476]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

Using [Cypress's](https://www.cypress.io) [`type`](https://docs.cypress.io/api/commands/type.html)  command to insert some text in a Slate editor. The `Slate` `onChange` handler doesn't seem to be called while typing (note how the placeholder is never removed):

![cypress-slate-issue](https://user-images.githubusercontent.com/18542095/73491049-c39b6180-437b-11ea-981f-08310c98d226.gif)

Here's some console output for the `onChange` handler for the duration of this interaction:

![onchange-console-slate-issue](https://user-images.githubusercontent.com/18542095/73491709-33f6b280-437d-11ea-9057-35e5b68989e3.png)

This was only logged once (presumably when the editor mounted). Instead, this should've been logged several times and the leaf should've ended up with a `text` value equivalent to what was typed.

Slate: 0.57.1
Browser: Chrome (_in a Cypress environment_)
OS: Mac

#### What's the expected behavior?

`onChange` should be called as the value changes when typing. There's some documentation about how events are handled for Cypress's `type` command [here](https://docs.cypress.io/api/commands/type.html#Events).

**Comment by achou11** [comment]
Update: looks like the type command is inserting the text into an unexpected element i.e. the element that accompanies the placeholder and contains zero width character:

![text-insert-dom](https://user-images.githubusercontent.com/18542095/73496074-c9964000-4385-11ea-902d-294d2cabe3d2.png)

Not sure if this is a Slate issue or a Cypress issue at this point.

**Comment by mattapperson** [comment]
@achou11 do you by any chance have a small test-case of this issue?

**Comment by Jmaharman** [comment]
There is an ongoing thread of users finding their appropriate hacks to get it working. Some may lead to a solution of how to support it natively.

https://slate-js.slack.com/archives/C1RH7AXSS/p1579110773288500

**Comment by CameronAckermanSEL** [comment]
Slate is relying more heavily on the `beforeInput` event to deal with user interaction.

I havent had the time to dive into this problem, but reading the documentation on cypress I noticed:

https://docs.cypress.io/api/commands/type.html#Events-that-fire

`beforeinput is not fired even though it is in the spec because no browser has adopted it.`

And this is probably because firefox still does not declare they support `beforeInput` 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event

Cypress does not yet have an issue for this on their backlog as far as I could tell.

https://github.com/cypress-io/cypress

I'm uncertain I have enough information to make a report.

**Comment by reydelo** [comment]
The Cypress input commands (e.g. `cy.type()` and `cy.clear()`) work by dispatching `input` and `change` events - in the case of `cy.type()`, one per character. This mimics the behavior of a real browser as a user types on their keyboard and is enough to trigger the behavior of most application JavaScript.

However, Slate relies almost exclusively on the `beforeinput` event (see here https://docs.slatejs.org/concepts/xx-migrating#beforeinput) which is a new browser technology and an event which the Cypress input commands don’t simulate. Hopefully the Cypress team will update their input commands to dispatch the `beforeinput` event, but until they do I’ve created a couple of simple custom commands which will trigger Slate’s input event listeners and make it respond.

```
// commands.js
Cypress.Commands.add('getEditor', (selector) => {
  return cy.get(selector)
    .click()
    .wait(50); // Need to wait temporarily to make sure the selection is made by Slate
});

Cypress.Commands.add('typeInSlate', { prevSubject: true }, (subject, text) => {
  return cy.wrap(subject)
    .then(subject => {
      subject[0].dispatchEvent(new InputEvent('beforeinput', { inputType: 'insertText', data: text }));
      return subject;
    })
});
 
Cypress.Commands.add('clearInSlate', { prevSubject: true }, (subject) => {
  return cy.wrap(subject)
    .then(subject => {
      subject[0].dispatchEvent(new InputEvent('beforeinput', { inputType: 'deleteHardLineBackward' }))
      return subject;
    })
});

// slateEditor.spec.js
cy.getEditor('[data-testid=slateEditor1] [contenteditable]')
    .typeInSlate('Some input text ');

cy.getEditor('[data-testid=slateEditor2] [contenteditable]')
    .clearInSlate()
    .typeInSlate('http://httpbin.org/status/409');
```

If you need to support other inputTypes, all of the inputTypes supported by Slate are listed [here](https://github.com/ianstormtaylor/slate/blob/16ff44d0566889a843a346215d3fb7621fc0ed8c/packages/slate-react/src/components/editable.tsx#L249)

**Comment by alexmonteirocastro** [comment]
@reydelo Tried that approach but it didn't work.

**Comment by mwood23** [comment]
@alexmonteirocastro I couldn't get it to work for me either and chased it down into the source. The solution posted works and goes through all the code paths you'd want as long as your `Editable` component has `autoFocus` on it.

Here's a [snippet from the examples](https://github.com/ianstormtaylor/slate/blob/67c4b3b330c3a62d626c4994d26f4526d18a4a1e/site/examples/richtext.js#L37) on usage.

**Comment by BrentFarese** [comment]
Closing this since, as noted above, it really is a Cypress issue with Cypress not firing `beforeinput` and there are listed workarounds above for folks that need to test using Cypress.

**Comment by lavaldi** [comment]
Someone was able to test the editor with CyPress without the `autoFocus` property?

**Comment by appsgodfather** [comment]
Is someone knows how to simulate the enter button click in the slate input? For example, the comment input field which posts a comment after click Enter
