### ISSUE TITLE
setValue(blankSlateValue) would cause focus error

### ISSUE THREAD

**Issue by hanselke** [ianstormtaylor/slate#3477]
#### Do you want to request a _feature_ or report a _bug_?

bug
#### What's the current behavior?

if you have multiline content in the editor, and you use setValue(blankSlateValue), it causes 

`
Cannot find a descendant at path [1,0] in node: {"children":[{"type":"paragraph","children":[{"text":""}]}],"operations":[],"selection":{"anchor":{"path":[1,0],"offset":6},"focus":{"path":[1,0],"offset":6}},"marks":null,"history":{"undos":[[{"type":"set_selection","properties":null,"newProperties":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}}}],[{"type":"insert_text","path":[0,0],"offset":0,"text":"e"},{"type":"insert_text","path":[0,0],"offset":1,"text":"a"},{"type":"insert_text","path":[0,0],"offset":2,"text":"f"},{"type":"insert_text","path":[0,0],"offset":3,"text":"e"},{"type":"insert_text","path":[0,0],"offset":4,"text":"a"},{"type":"insert_text","path":[0,0],"offset":5,"text":"f"},{"type":"insert_text","path":[0,0],"offset":6,"text":"e"},{"type":"insert_text","path":[0,0],"offset":7,"text":"a"}],[{"type":"split_node","path":[0,0],"position":8,"target":null,"properties":{}},{"type":"split_node","path":[0],"position":1,"target":8,"properties":{"type":"paragraph"}}],[{"type":"insert_text","path":[1,0],"offset":0,"text":"f"},{"type":"insert_text","path":[1,0],"offset":1,"text":"e"},{"type":"insert_text","path":[1,0],"offset":2,"text":"a"},{"type":"insert_text","path":[1,0],"offset":3,"text":"f"},{"type":"insert_text","path":[1,0],"offset":4,"text":"a"},{"type":"insert_text","path":[1,0],"offset":5,"text":"e"}]],"redos":[]}}
`
Slate: 0.57.1
Browser: Chrome 
OS: Mac 

#### What's the expected behavior?

focus should be set automatically and not cause this error.

i have a quick hack that does

`
            editor.selection = {
              anchor: {
                path: [0,0],
                offset:0
              },
              focus: {
                path: [0,0],
                offset: 0
              }
            }
`
before i setValue(blankSlateValue) and it works as expected

**Comment by multiplegeorges** [comment]
Just confirming this bug, I hit it and resetting the anchor and path avoids the error when resetting to a simple state like:
```typescript
const initialValue = [
  {
    type: 'paragraph',
    children: [{ text: '' }],
  }
] as Node[]
```

**Comment by FoxyWolfy** [comment]
FYI - I just hit this issue.  Resetting the anchor and focus didn't have any effect.

Tracking the exception led me to my toolbar buttons where I set the active color for "Bold", "Italic", etc.  I removed the functionality (below) and the exception just went away.  
It was throwing on the Editor.nodes(editor, { match: { bold: true },  mode: 'universal', }) check.  
 
`return ToolbarButtons.isBoldMarkActive(editor) ? "primary" : "default"`

```
const ToolbarButtons = {
    isBoldMarkActive(editor) {
        **const [match] = Editor.nodes(editor, {
            match: { bold: true },
            mode: 'universal',
        })**

        return !!match
    },

    isItalicMarkActive(editor) {
        const [match] = Editor.nodes(editor, {
            match: { italic: true },
            mode: 'universal',
        })

        return !!match
    },
etc...
}
```

**Comment by CameronAckermanSEL** [comment]
Hi @hanselke , incidentally the "hack" you mentioned is the solution to this behavior. The selection state for slate is controlled separately from the value state, and if you pass it a value and the selection state is no longer valid, it will throw an exception. Setting the selection to a neutral state is necessary before resetting the value.

**Comment by pnfcre** [comment]
Hi there, could anyone show an example of this in context of a simple example? I'm trying to figure out how to set the selection to a neutral state before setting the state in a `useEffect` hook with no dependencies, to make it run on first render, but it doesn't seem to work. Any ideas? Thanks.

**Comment by Pr1ncek** [comment]
> Just confirming this bug, I hit it and resetting the anchor and focus avoids the error when resetting to a simple state like:
> 
> ```ts
> const initialValue = [
>   {
>     type: 'paragraph',
>     children: [{ text: '' }],
>   }
> ] as Node[]
> ```

can you show how to do it?

**Comment by martonlanga** [comment]
For people still getting this error:

I had an `initialValue` const that I was using to init slate's value. Slate doesn't like this, do it like this instead:
```
const [value, setValue] = useState<Node[]>([
    {
      type: 'paragraph',
      children: [{ text: '' }],
    },
  ])
```

**Comment by mdegrees** [comment]
This is caused by react Fast Refresh. I got rid of the crash by adding ``// @refresh reset`` to the top of the file according to https://reactnative.dev/docs/fast-refresh#tips

**Comment by jacob-lcs** [comment]
> This is caused by react Fast Refresh. I got rid of the crash by adding `// @refresh reset` to the top of the file according to https://reactnative.dev/docs/fast-refresh#tips

Thank you, this is very useful to me

**Comment by DavidJones418** [comment]
I was seeing this with [react-refresh](https://www.npmjs.com/package/react-refresh) after following the [installation guide](https://docs.slatejs.org/walkthroughs/01-installing-slate), I fixed it by replacing `const editor = useMemo(...)` with

```js
const [editor] = useState(() => withReact(createEditor()))
const [value, setValue] = useState(initialValue)
```

to tie the editor lifetime to that of the parent component and persist it across hot module reloads (`React.useMemo` is re-evaluated each time.)

**Comment by sebastijandumancic** [comment]
Can confirm, resetting anchor and focus fixes the error.

**Comment by mdegrees** [comment]
@DavidJones418 one caveat to this approach is changes not being reflected when doing plugin development. If you're writing code for a withX plugin, there is no way you can get the updated editor value on a re-render.

**Comment by lollichilli** [comment]
I applied your method and it worked for me, however, the text cursor is always set to the first row. What do you think caused the problem?

> #### Do you want to request a _feature_ or report a _bug_?
> bug
> 
> #### What's the current behavior?
> if you have multiline content in the editor, and you use setValue(blankSlateValue), it causes
> 
> `Cannot find a descendant at path [1,0] in node: {"children":[{"type":"paragraph","children":[{"text":""}]}],"operations":[],"selection":{"anchor":{"path":[1,0],"offset":6},"focus":{"path":[1,0],"offset":6}},"marks":null,"history":{"undos":[[{"type":"set_selection","properties":null,"newProperties":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}}}],[{"type":"insert_text","path":[0,0],"offset":0,"text":"e"},{"type":"insert_text","path":[0,0],"offset":1,"text":"a"},{"type":"insert_text","path":[0,0],"offset":2,"text":"f"},{"type":"insert_text","path":[0,0],"offset":3,"text":"e"},{"type":"insert_text","path":[0,0],"offset":4,"text":"a"},{"type":"insert_text","path":[0,0],"offset":5,"text":"f"},{"type":"insert_text","path":[0,0],"offset":6,"text":"e"},{"type":"insert_text","path":[0,0],"offset":7,"text":"a"}],[{"type":"split_node","path":[0,0],"position":8,"target":null,"properties":{}},{"type":"split_node","path":[0],"position":1,"target":8,"properties":{"type":"paragraph"}}],[{"type":"insert_text","path":[1,0],"offset":0,"text":"f"},{"type":"insert_text","path":[1,0],"offset":1,"text":"e"},{"type":"insert_text","path":[1,0],"offset":2,"text":"a"},{"type":"insert_text","path":[1,0],"offset":3,"text":"f"},{"type":"insert_text","path":[1,0],"offset":4,"text":"a"},{"type":"insert_text","path":[1,0],"offset":5,"text":"e"}]],"redos":[]}}` Slate: 0.57.1 Browser: Chrome OS: Mac
> 
> #### What's the expected behavior?
> focus should be set automatically and not cause this error.
> 
> i have a quick hack that does
> 
> `editor.selection = { anchor: { path: [0,0], offset:0 }, focus: { path: [0,0], offset: 0 } }` before i setValue(blankSlateValue) and it works as expected
