### ISSUE TITLE
Add API Reference for 0.5x+

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3480]
The lack of API Reference for 0.5x+ is a critical hole in Slate.

There is conversation about using inline comments to generate documentation; however, I think as an interim step, it would be a benefit to the community if somebody manually created the documentation.

I am posting this (a) to put the request out to the community for help and (b) perhaps through reactions gauge how important this is to others.

**Comment by nikparo** [comment]
I was hoping to migrate a project over, but I'm new to Slate and I'm finding the lack of API References to be quite a big road block. Would love to see this.

**Comment by hadrysmateusz** [comment]
I also agree, I would help myself but I'm also new to Slate. I'm having a hard time understanding the API without a reference. I'm spending more time in Slate's than in my own, just trying to figure out how to accomplish basic stuff.

**Comment by sherwinyu** [comment]
Agreed! I've just found myself reading the Slate source (and looking at the examples), and took about a month of migrating from 0.47 to become familiar with the different parts of the source

**Comment by CameronAckermanSEL** [comment]
Merged in a generous PR that adds manually written API documentation. Long term, I think it's still a goal to have auto generated documentation, but this has been more challenging than originally anticipated.

Closing this issue. If you guys find any issues with the documentation, please submit a PR to fix mistakes.
