### ISSUE TITLE
Get Current Location 

### ISSUE THREAD

**Issue by zerobytes** [ianstormtaylor/slate#3485]
#### What's the current behavior?
Get the current Location, Block, Node, Leaf.

So far i couldn't find at the documents on examples how to get the current Localtion in the editor, where the user is placing it's cursor at.
I would expect something like:
```js
let location = Editor.getCurrentLocation()
/// returns a Location that i could use to get the Node/Block/Leaf, 
/// as the methods to get them require a Location, as so many others do.
let currentLeaf = Editor.leaf(editor,location)
let currentNode = Editor.node(editor,location)
....
```

**Comment by ramlez** [comment]
@zerobytes Have you tried to use `editor.selection`? It looks like it's something that you're looking for. [Here is some example.](https://github.com/ianstormtaylor/slate/blob/master/site/examples/links.js)

**Comment by CameronAckermanSEL** [comment]
I'm pretty sure this is satisfied by the `editor.selection` property that @ramlez . If this isn't the case, please let me know and I can reopen the issue.
