### ISSUE TITLE
addRange(): The given range isn't in document.

### ISSUE THREAD

**Issue by xinghul** [ianstormtaylor/slate#3488]
#### Do you want to request a _feature_ or report a _bug_?
Bug

This happens randomly, see the attachment for details.
![Screen Shot 2020-02-08 at 3 37 52 PM](https://user-images.githubusercontent.com/6555861/74093609-1e723e80-4a89-11ea-8103-ee667d09888e.png)

**Comment by marcandrews** [comment]
This seem related to #3380.

I am in the process of migrating to my codebase to TypeScript and also updating a few dependencies. Even with #3380, my code was working with my proposed workaround, but now I am encountering this issue.

I am looking into the issue further, but removing the second instance resolves it.

😭

**Comment by xinghul** [comment]
thank you!
