### ISSUE TITLE
Cannot input chinese directly after the mention in mention demo

### ISSUE THREAD

**Issue by zhaoyao91** [ianstormtaylor/slate#3490]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

![Kapture 2020-02-10 at 12 41 17](https://user-images.githubusercontent.com/3808838/74121701-982e3780-4c03-11ea-9521-7cbc3328c6a9.gif)

https://www.slatejs.org/examples/mentions

Slate: I don't know
Mac OS: 10.15.3
Chrome: 80.0.3987.87

#### What's the expected behavior?

When typing Chinese after the mention (void node), it could work fine, but it seems breaking the slate structure and the following typing is buggy.

**Comment by tangzijun** [comment]
在safari中使用，输入中文后，光标始终在段落的最前面，这个问题十分困扰，不知道现在解决的进展如何了，我使用的是0.57.1的最新版本。

**Comment by tangzijun** [comment]
It is used in safari. After entering Chinese, the cursor is always at the front of the paragraph. This problem is very disturbing. I don't know how the problem is solved. I use the latest version of 0.57.1.

**Comment by pedily** [comment]
I can confirm similar issues with Microsoft IME whenever using IME input at offset 0 behind another element.

The IME widget will modify the wrong dom element.

My workaround is to insert a character without IME first, then use IME input, then deleting the character again

**Comment by pedily** [comment]
I can confirm similar issues with Microsoft IME whenever using IME input at offset 0 behind another element.

The IME widget will modify the wrong dom element.

My workaround is to insert a character without IME first, then use IME input, then deleting the character again

**Comment by pedily** [comment]
I can confirm similar issues with Microsoft IME whenever using IME input at offset 0 behind another element.

The IME widget will modify the wrong dom element.

My workaround is to insert a character without IME first, then use IME input, then deleting the character again

**Comment by scil** [comment]
it's about IME. Chinsese can not be used well on slate right now. because IME related DOM event damage React Reconciliation.

#3824

**Comment by hardywu** [comment]
confirm that it still appears on safari right now

**Comment by xxxxxccc** [comment]
version 0.65 still has this problem, input chinese after a void node; use macos ，when u 'ArrowLeft' or 'ArrowRight' choose a chinese word ,the cursor incorrect

**Comment by jim-kk-hc** [comment]
+1

**Comment by dylans** [comment]
I believe what needs to be done is to add an empty whitespace character after the mention gets inserted. At least I think that's what we did for the implementation in Plate.

**Comment by pubuzhixing8** [comment]
In the earlier slate-angular fixed this problem, mention example: [http://slate-angular.ngnice.com/mentions](http://slate-angular.ngnice.com/mentions), probably the problem is that the tag containing the **\[data-slate-spacer="true"\]** will interrupt the IME input, so slate-angular move all **\[data-slate-spacer="true"\]** tag to the front of \[Void text\] to avoid IME input being interrupted, it has been working fine in Prod environment for a while without any additional issues, I plan to submit a PR with such changes.

slate-react DOM：

![](https://user-images.githubusercontent.com/18631804/170693103-775d124a-7745-42d7-8ea5-4a9d0a1dba8e.png)

slate-angular DOM：

![](https://user-images.githubusercontent.com/18631804/170693136-3b0dd614-53cb-4cad-8eaf-a78a4b343270.png)

**Comment by jim-kk-hc** [comment]
> d

I asked you this question in Zhihu last week. It bothered me for a long time. Thank you

**Comment by HUYIFU** [comment]
![image](https://github.com/user-attachments/assets/72e60ebe-0efe-40c5-aa9a-2c7f80d530fc)
Changing it like I did fixed the topmost problem, but it introduced a new bug that triggered the whole editor to crash when moving the cursor left in Chinese input to the inline-block element itself, and then I couldn't stop cursor movement by disabling the call to event.preventDefault in the slate's onKeyDown event. 
![20240720230246_rec_](https://github.com/user-attachments/assets/1b3bfbf8-79be-483c-9322-0583ff69959e)
help
