### ISSUE TITLE
Issue clearing input on key press

### ISSUE THREAD

**Issue by KieranVieira** [ianstormtaylor/slate#3492]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When clearing input on key press enter I get a slate error. Example in this [sandbox](https://codesandbox.io/s/restless-hill-bp2l8?fontsize=14&hidenavigation=1&theme=dark)

![slate error](https://user-images.githubusercontent.com/43533103/74270054-97b3a080-4cd8-11ea-83e0-557fc0dfbc62.gif)

Slate: 0.57.1
Browser: Chrome
OS: Windows

I have tried the suggestions in #713 and #300

#### What's the expected behavior?

Should remove the input content, the same as the behavior of the button in the sandbox.

**Comment by aykutkardas** [comment]
This is because the cursor is still looking for a block after the action.

You won't have this problem when you click on a button. Because the editor loses focus.

Import ReactEditor value from slate-react.
```js
import { Editable, withReact, Slate, ReactEditor } from "slate-react";
```
Use the `ReactEditor.blur` method to lose focus before saving the new value.

```jsx
  <Editable
    placeholder="Write text and press enter to see error."
    onKeyDown={e => {
      if (e.key === "Enter") {
        e.preventDefault();
        ReactEditor.blur(editor);

        setValue([
          {
            type: "paragraph",
            children: [{ text: "" }]
          }
        ]);
      }
    }}
  />
```

**Comment by aykutkardas** [comment]
Or it can import `Transforms` and `Editor` values.

```js
import { createEditor, Transforms, Editor } from "slate";
```
With the `Transforms.select` method, you can move the cursor to the beginning of the editor.

```jsx
  <Editable
    placeholder="Write text and press enter to see error."
    onKeyDown={e => {
      if (e.key === "Enter") {
        e.preventDefault();
        Transforms.select(editor, Editor.start(editor, []));
        setValue([
          {
            type: "paragraph",
            children: [{ text: "" }]
          }
        ]);
      }
    }}
  />
```

**Comment by KieranVieira** [comment]
Ah right that makes sense, thanks for the quick help and detailed explanation.
