### ISSUE TITLE
Can't control how data is inserted with ctrl+shift+v

### ISSUE THREAD

**Issue by lcswillems** [ianstormtaylor/slate#3496]
I have override the default `insertData` method of `ReactEditor` but I can't control data pasted with `ctrl+shift+v`. How could I do? It doesn't seem there is a way to do it.

----

Slate: 0.57.0
Browser: Chrome
OS: Linux

**Comment by tuttieee** [comment]
#3414

**Comment by mindplay-dk** [comment]
#3415 was merged, so I think this issue can be closed?

**Comment by lcswillems** [comment]
Yes, it can be closed now. Great PR!
