### ISSUE TITLE
<input /> onChange is not triggered in Firefox

### ISSUE THREAD

**Issue by daldoy** [ianstormtaylor/slate#3500]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
input elements rendered in renderElement don't work in Firefox: onChange is not triggered.

https://codesandbox.io/s/slate-reproductions-b5363

Slate: 0.57.1
Browser: Firefox

**Comment by CameronAckermanSEL** [comment]
I believe this is fixed from merging https://github.com/ianstormtaylor/slate/pull/3436
