### ISSUE TITLE
Cannot focus inline void elements

### ISSUE THREAD

**Issue by knpwrs** [ianstormtaylor/slate#3518]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

When arrowing through the text in the mentions example, as soon as a mention is highlighted, focus is lost and user can no longer use arrow keys.

![2020-02-26 19-54-03 2020-02-26 19_55_56](https://user-images.githubusercontent.com/174864/75402168-2aa42b80-58d2-11ea-8206-15497aceda5a.gif)

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

The mentions should become highlighted and arrow keys should continue to work.

**Comment by CameronAckermanSEL** [comment]
I think this is related to one of the PRs I merged in that was attempting to fix inputs in void nodes.

**Comment by dalevy** [comment]
Is this related to Issue [#2685 ](https://github.com/ianstormtaylor/slate/issues/2685) and [#2019](https://github.com/ianstormtaylor/slate/issues/2019) ?

**Comment by cj1128** [comment]
Examples with input, `editable-voids` and `embeds`  are all broken now, You just can't type anything in this input element.

Slate version: 0.57.1

**Comment by CameronAckermanSEL** [comment]
Hi @cj1128 , the examples that are currently hosted should have functional input voids. Please double check and let me know if that's not the case. The live examples work for me in FF and Chrome.

**Comment by dalevy** [comment]
> Hi @cj1128 , the examples that are currently hosted should have functional input voids. Please double check and let me know if that's not the case. The live examples work for me in FF and Chrome.
> 
> A version of slate that fixes the problem with the input voids has not yet been released.

By any chance, do you have a timeline for the release of the fix @CameronAckermanSEL ?

**Comment by CameronAckermanSEL** [comment]
Hey @kilrain, the version of the library that has this bug should not have been released yet, it should only impact the live examples right now. Are you able to reproduce this on the latest release in npm?

**Comment by kilrain** [comment]
Ah - that's good news. I'm in the middle of upgrading from .47 and haven't yet migrated the inline-void parts of my codebase. Thanks for the quick response @CameronAckermanSEL !

**Comment by cj1128** [comment]
> Hi @cj1128 , the examples that are currently hosted should have functional input voids. Please double check and let me know if that's not the case. The live examples work for me in FF and Chrome.
> 
> A version of slate that fixes the problem with the input voids has not yet been released.

Hi @CameronAckermanSEL, this is my bad. I used the release version (0.57.1) to test the master examples. All the examples work well except `editable-voids` and `embeds`. I retest them using the master version and they work as expected.

Thanks for all the hard work.

**Comment by nahumzs** [comment]
@cj1128 I'm using 0.57.1 version on my local development and input on void element don't work, the onchange don't fire and left and right arrows don't work. 

You mention you fixed this with the master version, what version is that?
Can you help me on this, I have been stuck with this for days now :(. 

Thank you for this awesome library btw.

**Comment by CameronAckermanSEL** [comment]
I think I fixed this problem here. https://github.com/ianstormtaylor/slate/pull/3572 

There's a preview deployment under the automated PR checks. Would appreciate a (careful!) second glance
