### ISSUE TITLE
Microsoft Edge Legacy doesn't support 'beforeinput' event

### ISSUE THREAD

**Issue by pavlyna** [ianstormtaylor/slate#3536]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

Children and selection don't get synced in Microsoft Edge Legacy.
Microsoft Edge Legacy doesn't support 'beforeinput' event https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event
Apparently, no workaround has been introduced.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/7562331/76009763-66667300-5f1a-11ea-932e-cac171a6e047.gif)

Slate: 0.57.1
Browser: Edge <79
OS: Windows

#### What's the expected behavior?

Whereas Microsoft Edge Legacy is not the newest, but is the latest of its kind, I would suggest consider providing support for it, in the same way as Firefox is handled since it has the same issue.

In addition, would like to mention the next issue https://github.com/ianstormtaylor/slate/issues/2060

Created PR just in case, #3537

**Comment by p0lax** [comment]
That's would be great to fix it, because currently new version of Edge is not installing automatically, so majority of users which are used Edge will proceed using version ~44

**Comment by eivindw** [comment]
We have finished upgrading slate - but will probably have to revert to old version if Edge issues are not fixed. Would be good if support for Edge could be kept until most Windows users are on the new version. Cutting old IE versions is fine - but Edge is still used by some of our users unfortunately.
