### ISSUE TITLE
some weird behavior in Safari when i input chinese

### ISSUE THREAD

**Issue by baijiahei** [ianstormtaylor/slate#3538]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
in Safari， focus will lose and with some errors when i input chinese
![Mar-06-2020 11-42-20](https://user-images.githubusercontent.com/16861647/76048113-cbb07780-5f9f-11ea-9732-b61ac9a33ecd.gif)

Slate: 0.57.X
Browser: Safari 
OS: Mac

**Comment by YacheLee** [comment]
Hi, @baijiahei could you review to see the bug is fixed or nor?
https://github.com/YacheLee/slate/tree/hotfix-3538-safari-with-chinese

**Comment by baijiahei** [comment]
> Hi, @baijiahei could you review to see the bug is fixed or nor?
> https://github.com/YacheLee/slate/tree/hotfix-3538-safari-with-chinese
> The demo is here https://slate-3538.now.sh

perfect,thx!!!
