### ISSUE TITLE
onChange handler is triggered after unmount

### ISSUE THREAD

**Issue by jdimond** [ianstormtaylor/slate#3550]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Minimal repro: https://codesandbox.io/s/serene-hooks-4dzks.

![repro](https://user-images.githubusercontent.com/1628592/76885775-0090ba00-683d-11ea-9f82-db1e878621ba.gif)

The onChange handler is triggered *after* the component is unmounted. As far as I can see this happens because

- the [onDOMSelectionChange](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx#L354) callback is run asynchronously due to the call to throttle.
- However, that callback still has a reference to the editor, which in turn avoids deallocating the callback stored in the weak reference map [here](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/slate.tsx#L35).
- The callback runs a Transforms.(de)select which then causes the onChange callback to be run (after the component has already been unmounted).

Note that this is not reproducible if the toggle switch is replaced with an actual button rather than a normal element with an onClick handler.

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

onChange should stop triggering immediately after an unmount.

**Comment by qin9smile** [comment]
@jdimond 
use ref instead.
https://codesandbox.io/s/stupefied-pine-ynedd

**Comment by jdimond** [comment]
@qin9smile using ref (and that examples) still repros with the error for me.

**Comment by qin9smile** [comment]
> @qin9smile using ref (and that examples) still repros with the error for me.

you are right.
