### ISSUE TITLE
 Unable to find the path for Slate node:

### ISSUE THREAD

**Issue by johnpaul89** [ianstormtaylor/slate#3556]
Hey Guys?

I'm trying to serialize this HTML as defined [here in the docs](https://docs.slatejs.org/concepts/09-serializing) but I keep getting this error

This error occurs when I have this component defined

``` 
             <Editable
                    renderElement={renderElement}
                    renderLeaf={renderLeaf}
                    placeholder="Enter some rich text…"
                    spellCheck
                    autoFocus
                    onKeyDown={event => {
                        for (const hotkey in HOTKEYS) {
                            if (isHotkey(hotkey, event)) {
                                event.preventDefault()
                                const mark = HOTKEYS[hotkey]
                                toggleMark(editor, mark)
                            }
                        }
                    }}
                />
```

Uncaught Error: Unable to find the path for Slate node: {"children":{"children":[{"type":"paragraph","children":[{"text":"This is editable "},{"text":"rich","bold":true},{"text":" text, "},{"text":"much","italic":true},{"text":" better than a "},{"text":"<textarea>","code":true},{"text":"!"}]},{"type":"paragraph","children":[{"text":"Since it's rich text, you can do things like turn a selection of text "},{"text":"bold","bold":true},{"text":", or add a semantically rendered block quote in the middle of the page, like this:"}]},{"type":"block-quote","children":[{"text":"A wise quote."}]},{"type":"paragraph","children":[{"text":"Try it out for yourself!"}]}]}}

Anyone knowing how to fix this?

**Comment by johnpaul89** [comment]
I figured it out guys, on your initial value you should use 

```
    [
        {
            children: [{ text: '' }],
        }
    ]
```

Instead of the one provided in the [Docs](https://docs.slatejs.org/concepts/09-serializing) because that one in the docs is the one causing the error above.

**Comment by fosterer** [comment]
Does not work for me...

**Comment by cormacncheese** [comment]
@johnpaul89 is a temporary fix but I'm still unable to add an image from url. Same error as before

**Comment by isachivka** [comment]
Opened a PR that fixes the `beforeinput` slice of this: https://github.com/ianstormtaylor/slate/pull/6080

Two `toSlateRange` call sites in `Editable.onDOMBeforeInput` (the `getTargetRanges()` branch and the WebKit ShadowRoot branch) still hard-code `suppressThrow: false`, so when the browser's target range points at a DOM node that no longer resolves to a Slate node (stale NODE_MAP entry after a re-render, IME composition, clicking between editors), the `Unable to find the path for Slate node` throw escapes the DOM event handler and crashes the app. Every other `toSlateRange` call site in the same file already passes `suppressThrow: true` + null-checks — the PR aligns the last two and degrades gracefully (falls back to slate's synthetic handling at the current selection).

Context: in our production editor (slate-react 0.124.2) this exact stack — `findPath ← toSlatePoint ← toSlateRange ← beforeinput handler` — is a steady session-killing crash for ~8 users/day.
