### ISSUE TITLE
Uploading image using URL.createObjectURL, when I hit enter adds more images

### ISSUE THREAD

**Issue by MontoyaAndres** [ianstormtaylor/slate#3559]
When I hit enter under the image, for some reason it adds again the image... I'm using this code to add a new image:

This is the button:

```
const ImageButton = () => {
  const editor = useSlate();

  function uploadImage(event) {
    event.preventDefault();
    let file;

    if (event.target.files) {
      file = event.target.files[0];

      if (file && file.size < 1.2e7) {
        file = Object.assign(file, {
          preview: URL.createObjectURL(file)
        });

        insertImage(editor, file.preview);
      }
    }
  }

  return <input type="file" accept="image/*" onChange={uploadImage} />;
};
```

it executes the method `insertImage`. Which is this:

```
const insertImage = (editor: Editor, image: string) => {
  const text = { text: "" };
  const content = { type: "image", image, children: [text], isVoid: true };

  Transforms.insertNodes(editor, content);
};
```

It adds the image right, but when I hit enter, to add a new paragraph or something, it adds a new image... Here's the complete [code](https://codesandbox.io/s/stoic-monad-fmi6u):

![ezgif-3-90df3320bfde](https://user-images.githubusercontent.com/15065852/77472144-7bc81200-6de1-11ea-886f-eb6414795194.gif)

```
"slate": "^0.57.1"
"slate-history": "^0.57.1"
"slate-react": "^0.57.1"
OS: Windows 10
Browser: Google chrome
```

#### What's the expected behavior?

The behavior expected is, do not add a new image when I hit enter...

**Comment by CameronAckermanSEL** [comment]
This behavior is a deliberate part of splitBlock, which clones block and their properties. This is done because slate does not have a concept of a "default block type" and generally when a user hits "enter" they expect the new block to have the same marks and the same type as the original. 

You can overcome this by overriding the behavior of the splitBlock command, or overriding the onKeyDown event handler to clear out the properties of the new block after its split.

**Comment by MontoyaAndres** [comment]
Hey @CameronAckermanSEL ! Thanks! I  tried this:

```
    <Editable
        style={{
          backgroundColor: "#fafafa",
          minHeight: 150,
          border: "rgba(0, 0, 0, 0.54) solid",
          marginTop: "1em",
        }}
        onKeyDown={(event: React.KeyboardEvent<HTMLElement>) => {
          if (event.key === "Enter") {
            event.preventDefault();

            const newLine = {
              type: "paragraph",
              children: [
                {
                  text: "",
                  marks: [],
                },
              ],
            };
            
            Transforms.insertNodes(editor, newLine);
          }
        }}
        renderElement={renderElement}
        renderLeaf={renderLeaf}
        placeholder="Enter some rich text…"
        spellCheck
      />
```

Is this a good practice? Or maybe I should do something else? :) Thanks!
