### ISSUE TITLE
Possibility of creating `@next` tag on npm?

### ISSUE THREAD

**Issue by jeffkhull** [ianstormtaylor/slate#3561]
First off, thanks for the awesome text editor.

I am wondering if it is possible to install the latest code off of master (or some accelerated release tag), maybe by creating a new @next tag on npm?

My specific need is to get code which includes this fix: https://github.com/ianstormtaylor/slate/pull/3388/files

But I imagine many users could benefit from a @next tag in order to get more recent fixes.

**Comment by rohmanhm** [comment]
@jeffkhull Do you have any workaround fix until @ianstormtaylor creates the @next tag on npm?

**Comment by jeffkhull** [comment]
Hey @rohmanhm, no workaround, just not using the readonly flag - until I can get an updated version.

**Comment by CameronAckermanSEL** [comment]
0.57.2 is out.
