### ISSUE TITLE
onChange doesn't fire in android webview

### ISSUE THREAD

**Issue by littlehome-eugene** [ianstormtaylor/slate#3563]
#### What's the current behavior?

In android webview, mention example doesn't work because `onChange` doesn't fire for alphabet characters (onchange fires for `#`) 

I used https://github.com/react-native-community/react-native-webview (9.0.1)
slate 0.57.1
slate-react 0.57.1

![dd](https://user-images.githubusercontent.com/24217396/77603011-50186980-6f52-11ea-95f8-327df4daf08f.gif)

Slate: 0.XX.X
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

**Comment by johnpaul89** [comment]
#3470 
This issue is referenced here.

**Comment by CameronAckermanSEL** [comment]
Thanks for the report @littlehome-eugene ! I'm going to close this as a duplicate so we can keep track of our android support problems better.

**Comment by baljeet-aulakh** [comment]
I am using slate 47 and it's working perfectly on desktop and iOS devices but onChange is not triggering on Android devices. I would greatly appreciate any suggestion. Thanks.
