### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by johnpaul89** [ianstormtaylor/slate#3564]
Hey guys, When will this new version of **Slate 0.57+** get Android Support.

@ianstormtaylor @thesunny @gracicot  The plugin that you were [talking about of Android ](https://github.com/ianstormtaylor/slate/pull/3023#issue-318533006)will it be available soon enough?
I would like to use it on production where most of my users might be using Android.

**Comment by lightninglu10** [comment]
@johnpaul89 why did you close this issue, does it exist?

**Comment by wceolin** [comment]
@thesunny launched a [Kickstarter campaign to make it open-source](https://www.kickstarter.com/projects/sunnyhirai/add-android-support-for-the-slate-wysiwyg-editor) - as he explained on #3786. It would be awesome to have your support to make this happen, @lightninglu10 @johnpaul89
