### ISSUE TITLE
Cannot find a descendant at path when setting initialValue

### ISSUE THREAD

**Issue by ramsy-leftclick** [ianstormtaylor/slate#3565]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?
When I start with an empty state, add some text and make NO changes to it, f. If I then programmatically reset the state via a button it results in a crash.

Slate: 0.XX.X
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

**Comment by CameronAckermanSEL** [comment]
Hey @ramsy-leftclick, this happens if you don't also reset the selection state which is stored separately from the value. Also, your empty state must have at least one text node in it. 

In the future, some code to show a minimum reproduction of the error would be helpful as well :)

**Comment by ramsy-leftclick** [comment]
Hi @CameronAckermanSEL.

Thanks for the response. I made a Sandbox containing the code, which I've submitted with the bug.

https://codesandbox.io/s/jovial-browser-43pzl

**Comment by CameronAckermanSEL** [comment]
Hi @ramsy-leftclick , this is still not a bug. You need to reset selection when you reset the editor value, because selection is not packed in with the value. The crash is because when you rip out the value under the editor, it will still hold onto its current selection state and then have nothing to retrieve at that area.

**Comment by elios264** [comment]
> Hi @ramsy-leftclick , this is not a bug. You need to reset selection when you reset the editor value, because selection is not packed in with the value. The crash is because when you rip out the value under the editor, it will still hold onto its current selection state and then have nothing to retrieve at that area.
> 
> You probably need to call something like `Transforms.select(editor, [0])` before `setValue`

select din't work for me, I had to use: `Transforms.deselect(editor);`

**Comment by sebastijandumancic** [comment]
`
  /** Resets the value of the editor when triggered. Use instead of undefined or "".  */
  function clearEditor() {
    editor.selection = {
      anchor: { path: [0, 0], offset: 0 },
      focus: { path: [0, 0], offset: 0 },
    };

    setValue([
      {
        type: 'paragraph',
        children: [{ text: '' }],
      },
    ]);
  }`
  
  Here is an example of clearing editor, for example when sending a message. Notice resetting anchor and focus before setting null value.

**Comment by letzbrush** [comment]
struggled with this error with our editor allowing for setting its value from parent components (in React)
so we implemented some Path validation after each value update like so:
```
const onValueChange = () => {
  const { selection } = editor
  if (
    selection
    && selection.anchor
    && !Editor.hasPath(editor, selection.anchor.path)
  ) {
    Transforms.deselect(editor)
  }
}
```
maybe that helps someone stumbling on this thread :)
