### ISSUE TITLE
onChange gets fired even no change is made (i.e. if I put it out of focus without any changes made)

### ISSUE THREAD

**Issue by ebasic** [ianstormtaylor/slate#3567]
#### Do you want to request a _feature_ or report a _bug_?

*Bug*

#### What's the current behavior?

`onChange` gets fired even if I don't make any changes on editable text. For example, if I put focus on editable text, make no changes and immediately click out of it,  'onChange' callback is triggered. How can I prevent this behavior? 
It's problem because every `onChange` re-renders my component where editable text is located and I don't want this additional re-render.

#### What's the expected behavior?

Slate version (npm packages):
 _"slate": "*",_
_"slate-history": "*",_
_"slate-react": "*",_

Browser: Chrome / Safari / Firefox / Edge
OS: Mac

**Comment by ebasic** [comment]
@ianstormtaylor

**Comment by CameronAckermanSEL** [comment]
onChange is fired as part of selection change. This is an unavoidable behavior and is required for slate to work. Instead, I'd focus on making your `onChange` loop as tight as possible.

**Comment by ebasic** [comment]
Solved and shared code by **@piyushpatel** on Slack:

`const handleChange = useCallback(val => {
    const ops = editor.operations.filter(o => {
      if (o) {
        return o.type !== 'set_selection';
      }
      return false;
    });

    if (ops && Array.isArray(ops) && ops.length > 0) {
      onChange(val);
    }
  }, []);`
