### ISSUE TITLE
Apply block level formatting (like text alignment) on node

### ISSUE THREAD

**Issue by ebasic** [ianstormtaylor/slate#3569]
#### Do you want to request a _feature_ or report a _bug_?

Request for feature.

I want to apply block level formatting on text (like textAlign: 'center'). I said block level because we can't apply it only on subset text (i.e. only on selected text) but on whole text container. 

I started with:

  `const [match] = Editor.nodes(editor, {`
    `at: selection,`
    `match: n => Editor.isBlock(editor, n),`
   ` mode: 'lowest',`
  `});`

'const path = match[0];'

To match lowest block arrount selection and then apply formatting:

`Transforms.setNodes(editor, { data: { align: 'left' } }, { at: path});`

But it doesn't work. 
*Problem 1: * It matches first block node arround my text, which is`span element - leaf node` and whose width is equal to text width. But there is one more container arround  them which is `div element - element node` whose width is full container width and actually it is node where textAlign should be applied. How can I match this node and how to point to it inside setNodes function?

**Comment by CameronAckermanSEL** [comment]
Hi @ebasic , this feature should already exist. `setNodes` is capable of applying arbitrary properties to nodes and various match constraints and depth (via mode). This is verified in a few [tests ](https://github.com/ianstormtaylor/slate/tree/master/packages/slate/test/transforms/setNodes) as well, if you're looking for some examples.

That said, it's a little unclear what problem you're actually running into. At this point, I think we need you to provide a minimum reproduction of the issue you're running into in a code sandbox so we can observe what you're running into.

Thanks

**Comment by CameronAckermanSEL** [comment]
Further chat in slack has indicated that you've figured out how to solve this. I'm going to close this as this feature exists already.
