### ISSUE TITLE
Backspace the image in first line failed 

### ISSUE THREAD

**Issue by kiliwalk** [ianstormtaylor/slate#357]
Assume an image in the first line of document, focus it, then tap `Backspace` or `Delete` key, image is not removed but an error occurs: `node.js:107 Uncaught Error: Could not find a descendant node with key "759l".`

After debug this, I found a solution to fix the backspace problem.
Replace the [line in at-current-range.js#L109](https://github.com/ianstormtaylor/slate/blob/master/src/transforms/at-current-range.js#L109): 

```
    after = selection
```

with 

```
    let parentNode = document.getClosestBlock(startNode)
    if(parentNode && parentNode.isVoid) { // first node is like image etc
      after = selection.collapseToStartOf(document.getNextBlock(startNode))
    } else {
      after = selection
    }
```

I'd like to see a more accurate method to fix these problems.
Thanks for this great framework!

**Comment by arekkas** [comment]
This yields now the following warning: `Warning: Selection was invalid and reset to start of the document`

**Comment by ianstormtaylor** [comment]
This should be fixed now!
