### ISSUE TITLE
Partially hidden blocks/images don't scroll into view from the top

### ISSUE THREAD

**Issue by borgar** [ianstormtaylor/slate#3576]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Clicking a partially hidden "block" element scrolls it into view if it at the bottom of the viewport, but not if it is at the top of the viewport.

![slate-scroll-issue](https://user-images.githubusercontent.com/21862/78274713-22a65f80-7500-11ea-8150-f3a1d6e69aad.gif)

The issue is demonstrable with the https://www.slatejs.org/examples/images example if extra text is added to create a scrolling document.

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

Block/Image should behave the same way in both up and down directions.

#### Further notes

I've taken a look at the code and the issue seems to be that the [element passed into the scrollIntoView mechanism](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx#L166-L167) is a placeholder below the element, and not the element itself. The scroll never happens as the placeholder is "in view" the entire time.

**Comment by borgar** [comment]
I would be happy to submit a patch but would I would need guidance where to start. This is being done every keypress so it seems vital that detecting if the scroll-target is within a block and using the block the scroll target is done in the fastest way possible.

**Comment by dylans** [comment]
Fixed in  #3746
