### ISSUE TITLE
Faster decorators using Web workers

### ISSUE THREAD

**Issue by oguzgelal** [ianstormtaylor/slate#3578]
Hi, I'm developing a [text editor library](https://github.com/marketmuse/editor) for my company on top of Slate (v0.57.1).

One of our requirements is to be able to use decorators on long contents, however the built-in `decorate` function causes too much lag that makes the editor unusable. For example if you try pasting this [massive article](https://neilpatel.com/what-is-growth-hacking) in the [search highlighting](https://www.slatejs.org/examples/search-highlighting) example you can observe the lag. But if you paste the same article in the [rich text](https://www.slatejs.org/examples/richtext) example it works pretty smoothly.

As a solution I tried using web workers to do the heavy lifting, so it won't block the UI and won't cause lag (in [here](https://github.com/marketmuse/editor/blob/master/src/editor/decorators/decorator.js) and [here](https://github.com/marketmuse/editor/blob/master/src/editor/decorators/decorateWorker.js)). There are still some small issues but the results I've got is very promising, it eliminated the lag. What I'm doing is computing the range array in a worker asynchronously, and applying them manually once the worker is done. 

I'm not however completely happy with [the way](https://github.com/marketmuse/editor/blob/master/src/editor/decorators/decorator.js#L95) I'm applying the range array using `Transforms.setNodes` by removing and reapplying the decorations on every loop. This is also causing problems with history. 

My question is, is there a way to apply a range list as decorations without using the `decorate` function ? Thank you!

**Comment by gentle-noah** [comment]
+1

**Comment by oguzgelal** [comment]
I've ended up making use of the built-in `decorate` function and just passing pre-calculated ranges list. Here's the [code](https://github.com/marketmuse/editor/blob/master/src/editor/decorators/decorator.js#L128). Seems like working pretty well

**Comment by IamStephan** [comment]
Hi @oguzgelal 
I quite like your implementation.
There is one thing I wanted to point out, though. I looked through your code before implementing it myself and after I did that, I noticed that this is good for forward typing but the decorators seem to jump when making edits before another decorator. Then I looked at your example and it seems to do the same thing. (I know it's because the ranges are pre calculated and new characters are just shifted into the decorator)

Otherwise, nice solution.

**Comment by oguzgelal** [comment]
Thanks @IamStephan! Yeah we do have that issue, but given the benefit of being able to handle extremely long contents that's been our tradeoff ¯\_(ツ)_/¯ I'm thinking of a solution where I'd selectively use the web workers vs. the native decorate function based on the content.
