### ISSUE TITLE
Unexpected cursor behavior on ENTER key after mark

### ISSUE THREAD

**Issue by pzhine** [ianstormtaylor/slate#3600]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

1. Go to the [rich text example](https://www.slatejs.org/examples/richtext)
2. Place your cursor after a mark range, e.g. after the italicized word "_much_"
3. Press ENTER key
4. Cursor remains in place even though line break is added

![bug](https://user-images.githubusercontent.com/2692844/78891916-ac0de280-7a68-11ea-868e-bdc53dee015b.gif)

#### What's the expected behavior?

Expected behavior is shown in the video above: when ENTER is pressed after non-marked text, the cursor follows the line break to the next line.

**Comment by dylans** [comment]
I don't recall the exact PR, but I believe this has been fixed and I'm no longer able to reproduce. Feel free to reopen if I missed a scenario where this is still an issue.
