### ISSUE TITLE
Error when typing Chinese character to replace all the content

### ISSUE THREAD

**Issue by YacheLee** [ianstormtaylor/slate#3607]
#### Do you want to request a _feature_ or report a _bug_?
It's a bug

#### What's the current behavior?
- A GIF showing the issue in action.
![](http://g.recordit.co/TJdJMsqsSN.gif)
- A sandbox that minimally reproduces the issue.
https://www.slatejs.org/examples/richtext
- Information about your OS, browser, Slate version, etc.
Chrome 80.0.3987.163 , Mac OS, Slate 0.57.1

Slate: 0.57.1
Browser: Chrome / Safari / Firefox / Edge
OS: Mac

#### What's the expected behavior?
Like https://quilljs.com/
![](http://g.recordit.co/HcD9X5mvC5.gif)

**Comment by mano233** [comment]
+1

**Comment by caffeine-cn** [comment]
same as #3292

**Comment by dimitriadamou** [comment]
PR #3342 fixes the issue
