### ISSUE TITLE
Handling multiple editors at once (bug)

### ISSUE THREAD

**Issue by Obiwarn** [ianstormtaylor/slate#3619]
#### BUG:

1. open Editable Voids example
2. add Node (press plus button)
3. try to edit the rich text editor field in the first node (below 'Tell us about you:')
4. BUG: focus jumps to the second node's editor

**Comment by Obiwarn** [comment]
![BUg](https://user-images.githubusercontent.com/9539797/79561333-7b9df800-80a9-11ea-8dcc-30b336f42c38.gif)

**Comment by CameronAckermanSEL** [comment]
See https://github.com/ianstormtaylor/slate/issues/3380#issuecomment-612432934

**Comment by Obiwarn** [comment]
Thank you.

I suggest to consider to update the example correspondingly.
