### ISSUE TITLE
Slate crashes when loaded on Microsoft Edge

### ISSUE THREAD

**Issue by TedChenNZ** [ianstormtaylor/slate#3622]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?

After importing slate, it crashes when opened in Microsoft Edge.
The default codesandbox shows this error: https://codesandbox.io/s/slate-reproductions-k0tpx

It also fails with the current latest versions of slate and react: https://codesandbox.io/s/slate-reproductions-m7s6y

I don't have a gif but hopefully an image of this example is good enough considering animations are not required to showcase this.

https://i.imgur.com/xCTyLIA.png

Slate: 0.57.1
Browser: Edge
OS: Windows

#### What's the expected behavior?

Slate not crashing when imported and used in Microsoft Edge.

**Comment by CameronAckermanSEL** [comment]
Hi @TedChenNZ , this is fixed on latest master, and pending release. Not sure when release will be, but if you're really in a pinch, you can deploy latest to your own npm registry for the time being.

I'm going to close this issue though as this is fixed.

Thanks!
