### ISSUE TITLE
List Items with Paragraph Blocks

### ISSUE THREAD

**Issue by irmerk** [ianstormtaylor/slate#3624]
#### Do you want to request a _feature_ or report a _bug_?

Bug 🐛

#### What's the current behavior?

List items containing paragraph blocks do not behave as expected.

##### GIF of issue in action
![Apr-20-2020 14-28-34](https://user-images.githubusercontent.com/36460856/79786334-44328400-8313-11ea-9e61-3efb6ffccef8.gif)

##### Sandbox of issue reproduction
https://codesandbox.io/s/slate-repo-irmerk-20-04-2020-s784c

##### Information about your OS, browser, Slate version, etc.
Slate: **0.57.1**
Browser: **Chrome**
OS: **Mac**

#### What's the expected behavior?

Support `list_item` blocks having rich text capability, allowing for `onKeyDown` to easily interpret splitting both the `list_item` and `paragraph` children.

**Comment by CameronAckermanSEL** [comment]
Hi! Saw this was closed. Was this perhaps related to the mode argument on split nodes?

**Comment by irmerk** [comment]
No, not sure what that is. We implemented changes to `editor.insertBreak` in a wrapper function on the editor. ([AP#370](https://github.com/accordproject/markdown-editor/pull/370))
