### ISSUE TITLE
Determining the current position of node

### ISSUE THREAD

**Issue by mateuszs** [ianstormtaylor/slate#3627]
Hi. 
I have an image with a delete icon. I want to delete image by clicking an icon. So the algorithm is to determine the current image position (it can be different than initial one) and run 

`Transform.removeNodes(editor, { at: currentImagePosition})`

The problem is I do not see any API in Slate which would help me to find some node by its, for example ID or key and get its position. I think my use case should be very common and many of you had similar. 

Regards

**Comment by joergjaeckel** [comment]
Did you solved that? Struggling myself with the concept of finding the path/position of a void image to transform related data.

**Comment by calvinwyoung** [comment]
If you're using `slate-react`, then you can use something like this when you render your image:

```typescript
import { ReactEditor, useEditor } from 'slate-react';

const ImageElement: React.FC<RenderElementProps> = ({
  attributes,
  children,
  element,
}) => {
  const editor = useEditor();

  // This will be the path to the image element.
  const path = ReactEditor.findPath(editor, element);
};
```

**Comment by eleventy** [comment]
Just getting started with slate, so I might be wrong, but Node.descendants gives you a list of your nodes, along with the path:

```javascript
for (const e of Node.descendants(editor, [] )) {
      console.log({e})
}
````
with specifying the path and a bit of filtering, you can find your element, and next to it is its path

**Comment by imdbsd** [comment]
solution from @calvinwyoung work for me, thanks man!

**Comment by dsimon-dev** [comment]
We are using `useSlateSelector` to avoid excessive re-renders:

```typescript
import { useCallback } from 'react';
import type { Editor, Element, Path } from 'slate';
import { ReactEditor, useSlateSelector } from 'slate-react';

/**
 * Returns the path of the given Slate element.
 * Re-renders when the path changes.
 */
export function useElementPath(element: Element): Path {
  return useSlateSelector(
    useCallback(
      (editor: Editor) => ReactEditor.findPath(editor, element),
      [element],
    ),
    pathEqualityFn,
    {
      // this is required to ensure that the returned path is not outdated
      deferred: true,
    },
  );
}

function pathEqualityFn(a: Path | null, b: Path): boolean {
  if (a == null) {
    return false;
  }
  if (a.length !== b.length) {
    return false;
  }
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) {
      return false;
    }
  }
  return true;
}
```

**Comment by 12joan** [comment]
@dsimon-dev Nice hook! I think it would fit well in `packages/slate-react/src/hooks`.

Although I would use this logic for `pathEqualityFn`:

```ts
const pathEqualityFn = (path: Path | null, another: Path): boolean =>
  path !== null && Path.equals(path, another)
```
