### ISSUE TITLE
select multiple row, and type Chinese, the editor will crash

### ISSUE THREAD

**Issue by ximenyue** [ianstormtaylor/slate#3628]
the behavior:
when you select multiple row, and type chinese, it crashed
gif:
![bug](https://user-images.githubusercontent.com/63843636/79844794-bd52d980-83ee-11ea-8e1a-7655897b9289.gif)
my system:
Version 80.0.3987.163 (Official Build) (64-bit)
computer:
<img width="346" alt="Screen Shot 2020-04-21 at 4 41 33 PM" src="https://user-images.githubusercontent.com/63843636/79844996-0571fc00-83ef-11ea-96f5-e46dcf48fefb.png">

**Comment by cevio** [comment]
The same as my project, i also have no idea how to resolve it. 

Do anyone can help?

**Comment by knubie** [comment]
Happens with Japanese and Korean as well. Seems to happen on `compositionEnd` event.

**Comment by knubie** [comment]
@ianstormtaylor Looks like this was closed by #3342

**Comment by ianstormtaylor** [comment]
Thank you @knubie!
