### ISSUE TITLE
Name Editor State and the Editor Namespace Differently

### ISSUE THREAD

**Issue by mwood23** [ianstormtaylor/slate#3629]
#### Do you want to request a _feature_ or report a _bug_?

Bug (type issue)

#### What's the current behavior?

Right now the type for the editor's state is the same as the helper methods namespace which causes problems when extending. The term `interface` is also conflated between referring to the [editor state in the source](https://github.com/ianstormtaylor/slate/blob/f6bfe034d707693488c38da77537fd36cb8856cf/packages/slate/src/interfaces/editor.ts#L31), but in [the docs](https://docs.slatejs.org/concepts/04-commands) it refers to the helper methods namespace

```ts
import { Editor, Editor } from 'slate' // Not valid!

export const MyEditor = {
  ...Editor, // This is an object of helper methods
  toggleMark(editor: Editor, format: string) { // This is the type of the editor state
    console.log(editor, format)
    // run stuff here
  },
}
```

Instead, you need to alias to make everything compile as expected:

```ts
import { Editor as SlateEditor, Editor as EditorState } from 'slate'

export const MyEditor = {
  ...SlateEditor,
  toggleMark(editor: EditorState, format: string) {
    // run stuff here
  },
}
```

I know that seems like a trivial matter, but it's confusing because in [the docs](https://docs.slatejs.org/concepts/04-commands) the namespaced helper properties is referred to as an `interface`, but the actual `Editor` interface in the [source](https://github.com/ianstormtaylor/slate/blob/f6bfe034d707693488c38da77537fd36cb8856cf/packages/slate/src/interfaces/editor.ts#L31) is actually the editor state.

Slate: 0.57.1

#### What's the expected behavior?

A more semantic name would be to refer to the editor state as `EditorState` instead of `Editor` since that's used as a namespace for helper methods. The descriptions could also be updated as well so the caller knows that they're creating an editor state object, not just an editor object. It also solves knowing what you're getting out of a callback on hover since it'll say `EditorState` in the screenshot below.

<img width="701" alt="2020-04-21_15-00-06" src="https://user-images.githubusercontent.com/13633613/79903381-f7b57a00-83e0-11ea-92e8-afc550ec0c3f.png">

Really enjoying working with the Slate, that just tripped me up for a while so wanted to file the issue. If this is something you think would be good to update I can take a stab at putting in the fix!

**Comment by jerkly** [comment]
Import `Editor` once to fix compilation error.

```typescript
import { Editor } from 'slate';

export const MyEditor = {
  ...Editor,
  toggleMark(editor: Editor, format: string) {
    console.log(editor, format)
    // run stuff here
  },
}
```


The second case of editor creation
```typescript
interface MyEditor extends Editor {
    //some declaration stuff here
}

const MyEditor = {
  ...Editor,
  toggleMark(editor: Editor, format: string) {
    console.log(editor, format)
    // run stuff here
  },
}

const withMyEditor = <T extends Editor>(editor: T): T & MyEditor => {
    const result = editor as T & MyEditor;
    // Initialization of MyEditor state
    return result;
};

function ReactCoolComponent() {
    const editor = useMemo(() => withReact(withMyEditor(createEditor())), []);
    
    //...
}

```

About renaming `Editor` interface to `EditorState`. 
I'll give you two examples of declaration of same things. Maybe this will help you understand what's going on.

First written in style come from strong typed language, i.e. Java or C#
```typescript
class Editor {
    public static method1(editor: Editor) {
        //run some stuff
    }

    public property1: number;
    public property2: number;

    constructor() {
        this.property1 = 99;
        this.property2 = 99;
    }

    public method2() {
        //run some stuff
    }
}

const editor = new Editor();  //editor is object (instance) of class Editor
Editor.method1(editor);
```

Second written in more js-like style
```typescript
interface Editor {
    property1: number;
    property2: number;

    method2: () => void;
}
const Editor = {
    method1: (editor: Editor) => {
        //run some stuff
    },
};

function createEditor(): Editor {
    return {
        property1: 99,
        property2: 99,
        method2: () => {
            //run some stuff
        },
    };
}

const editor = createEditor(); //editor is object corresponding to Editor interface
Editor.method1(editor);
```

**Comment by mwood23** [comment]
Thanks for putting together some examples, but the issue is the Editor helper function object and Editor state are not the same thing. Based on the docs, there's [helper functions namespaced](https://docs.slatejs.org/concepts/01-interfaces#helper-functions) to particular parts of the app, like the editor namespace. Then, there's the concept of plugins which allow you to [write higher order functions](https://docs.slatejs.org/concepts/06-editor#overriding-behaviors) to augment the editor state. 

The [Editor helper interface](https://github.com/ianstormtaylor/slate/blob/f6bfe034d707693488c38da77537fd36cb8856cf/packages/slate/src/interfaces/editor.ts#L62) and the [Editor state](https://github.com/ianstormtaylor/slate/blob/f6bfe034d707693488c38da77537fd36cb8856cf/packages/slate/src/interfaces/editor.ts#L36) do not contain the same properties and that's why I filed the ticket originally. If you look at the source for one of the examples you'll see that even though they have access to the [return value of createEditor](https://github.com/ianstormtaylor/slate/blob/217b84ff1f2039646ff30b11949e53417d70b824/site/examples/mentions.js#L22) they still import the helper `Editor` namespace because it [contains methods](https://github.com/ianstormtaylor/slate/blob/217b84ff1f2039646ff30b11949e53417d70b824/site/examples/mentions.js#L82) that the editor state does not.

**Comment by ianstormtaylor** [comment]
@mwood23 having an object be both a type and a value is possible in TypeScript. I'm not exactly sure what the issue you're running into is that isn't fixed by what @jerkly mentioned.

**Comment by ianstormtaylor** [comment]
I don't think we're going to change this. The `Editor` type represents the `editor` object, and the `Editor` namespace contains all the functions that take an `editor` object, and you'll often want both of them at once, and TypeScript is designed to make those things co-exist.
