### ISSUE TITLE
Make ReactEditor.findPath work with Leafs

### ISSUE THREAD

**Issue by daniel-civicore** [ianstormtaylor/slate#3633]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

Currently ReactEditor.findPath only works with Element nodes. It doesn't currently work with Leaf nodes. It appears this is because leafs are not being added to the WeakMaps NODE_TO_INDEX and NODE_TO_PARENT. For Elements these are added in the children component. For leafs this would need to be added in the text component.

I think the change that needs to happen is the following but I don't know enough yet about slate if this will cause any other issues.

slate-react/src/components/text.tsx
Add after Line 43

    NODE_TO_INDEX.set(leaf, i)
    NODE_TO_PARENT.set(leaf, parent)

Thanks,
Daniel

**Comment by mfranzs** [comment]
Resolved in this conversation  https://slate-js.slack.com/archives/C1RH7AXSS/p1591640944442600 with @BrentFarese :

Text  nodes are in the data structure, not leafs.  leafs are what is generated as a result of decorations.  A Text node can have multiple leafs if you use the decorate function of Slate.

 I would suggest you get the path to the Text node using ReactEditor.findPath.  You have access to the Text node too via `text` in the props to renderLeaf.

If you’re not using decorations, you don’t really need to worry about it.  Just target the Text node using ReactEditor.findPath inside your renderLeaf function and you might be alright.

**Comment by pirtlj** [comment]
Thanks for this, I was having the same issue

**Comment by nawartamawi** [comment]
@mfranzs how to differentiate between two leafs that happens to have the same text?
