### ISSUE TITLE
Backward selection doesn't work with custom blocks

### ISSUE THREAD

**Issue by DTX-92** [ianstormtaylor/slate#3647]
It presentеd in the official image example: https://www.slatejs.org/examples/images

Sandbox:
https://codesandbox.io/s/magical-monad-2icnm?file=/src/App.js

Gif:
https://i.imgur.com/QIvClnz.mp4 (or https://imgur.com/a/pTLfknS)

Chrome 81.0.4044.122 (Official Build) (64-bit), MacOs 10.14.6

**Comment by jerkly** [comment]
Workaround, relative to your sandbox.

`lines:82-84`

```jsx
<div contentEditable={false} style={{ userSelect: 'none' }}>
    <img src={element.url} alt="img" />
</div>
```
