### ISSUE TITLE
Selection via mouse across void nodes not worked

### ISSUE THREAD

**Issue by jerkly** [ianstormtaylor/slate#3648]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

Selection with mouse are collapsed, when hitting void node's edge.

Mention example: 
https://www.slatejs.org/examples/mentions
![screencast-www slatejs org-2020 05 04-05_35_00](https://user-images.githubusercontent.com/8193821/80932811-c8800f00-8dc9-11ea-9ecb-d147a5a2285f.gif)

Image example:
https://www.slatejs.org/examples/images
![screencast-www slatejs org-2020 05 04-05_43_31](https://user-images.githubusercontent.com/8193821/80932968-6a076080-8dca-11ea-8f56-60b76467ff80.gif)

Slate: 0.XX.X
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?
Selection is not collapsed, when selecting via mouse across void nodes

**Comment by jerkly** [comment]
Selection with keyboard arrows works as expected.

**Comment by knubie** [comment]
Was this fixed in #3594? (Potential duplicate of #1969)

**Comment by jerkly** [comment]
@knubie, #3594 is not fixed selection in all cases (only selection via keyboard). Bug are still present in Slate 0.57.2.
Look at the mention and image example https://www.slatejs.org/examples/mentions and try to select across voids via mouse.

**Comment by knubie** [comment]
> Bug are still present in Slate 0.57.2.

#3594 Is not included in 57.2. Could you try `master`?

**Comment by jerkly** [comment]
> > Bug are still present in Slate 0.57.2.
> 
> #3594 Is not included in 57.2. Could you try `master`?
Master checked again. Voids with extra content (i.e mention or embed) selectable only via keyboard.
With mouse selection there are two cases:
- selection via `Shift + mouse_click` working
- selection via `mouse_move` not working

**Comment by jerkly** [comment]
fixed in #3649
