### ISSUE TITLE
How can I modify the code background block

### ISSUE THREAD

**Issue by jaddoescad** [ianstormtaylor/slate#3653]
Hey,
I'm trying to implement a code block that is similar to this wi

<img width="649" alt="Screen Shot 2020-05-04 at 8 40 26 PM" src="https://user-images.githubusercontent.com/12466304/81026273-84335400-8e47-11ea-9c86-4dd58e9d56a2.png">

How can I style the background and make sure that each line is attached to the next?

**Comment by CameronAckermanSEL** [comment]
Hi @jaddoescad  thanks for your interest in the library! We're currently using the github to keep track of bugs and feature requests, and instead have a slack channel for people to ask questions. 

We'll see you at https://slate-js.slack.com!
