### ISSUE TITLE
Replacing words with LanguageTool does not work (Drafts.js works)

### ISSUE THREAD

**Issue by Obiwarn** [ianstormtaylor/slate#3655]
I am not sure if this is a bug or feature request:

When I use Language-Tool (https://languagetool.org/) to check spelling with Slate, it inserts the suggestion at the current cursor position (instead of replacing the wrong word). 

With Draft.js this works. Any idea why this happens? Or how I can avoid it?

![Insert](https://user-images.githubusercontent.com/9539797/81078852-0aef3c00-8eef-11ea-828a-5e86b928c86f.gif)

**Comment by dimitriadamou** [comment]
Just for clarification - What browser are you using? I tried this on Chrome on Mac and ran into no issues

![May-06-2020 19-12-50](https://user-images.githubusercontent.com/3094239/81160625-a6ef7500-8fcd-11ea-8254-568878930288.gif)

**Comment by Obiwarn** [comment]
Indeed. The new LT version 3.1.5 just fixed this. Thank you!
