### ISSUE TITLE
Selection bug

### ISSUE THREAD

**Issue by hector-esv** [ianstormtaylor/slate#366]
1. Insert a node somewhere
2. Put the selection inside the node
3. Undo the insertion (with Ctrl-Z)
4. If state.blocks or state.marks is accessed, throws with
   Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".

Interpretation: the selection references nodes that no longer exist.

**Comment by chilijung** [comment]
https://github.com/ianstormtaylor/slate/pull/365

I think this PR should fix the issue?

**Comment by ianstormtaylor** [comment]
This might be fixed in `0.15`. If you run into it again feel free to re-open though.

**Comment by Slapbox** [comment]
I get this error whenever I try to open the state tree on the Editor element in React Devtools.

I am using Redux to store the state of everything in my app, for better or worse, so I can see the state in Redux always. This also prevents me from testing though if this is a bug in Devtools or in the editor/my integration of it with Redux.
