### ISSUE TITLE
editor.insertData() is not triggered on Safari when pasting an image

### ISSUE THREAD

**Issue by heymanhn** [ianstormtaylor/slate#3664]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
1. Load the Slate Images example: https://www.slatejs.org/examples/images
2. Copy an image from another webpage
3. Use Command + V to paste it into the demo editor.
4. Nothing happens; editor.insertData() isn't even triggered.

Video: https://share.getcloudapp.com/v1uDQnj4 (you can't see me hitting cmd + v, but trust me I'm doing it).

Browser: Safari - Version 13.1 (15609.1.20.111.8)
OS: Mac

#### What's the expected behavior?
editor.insertData() should be triggered and the pasted image available for any custom code to execute.

**Comment by mfranzs** [comment]
@heymanhn Did you ever find a workaround for this issue?

I'm unsure what the core problem is here. I notice this odd line that changes behavior on Safari, but don't understand the motivation for this check:
https://github.com/ianstormtaylor/slate/blob/97dbab13a88cbeb7b9d41287fc7e6a2086211f1e/packages/slate-react/src/components/editable.tsx#L701

**Comment by dylans** [comment]
Likely the same issue as #4465. Closing as duplicate.
