### ISSUE TITLE
Slow backspace performance

### ISSUE THREAD

**Issue by hector-esv** [ianstormtaylor/slate#367]
Deleting text is much slower than insertion. To see this make sure the document has a lot of nodes in it. I think insertion doesn't always cause re-renders, but every backspace always results in a re-render of the whole document.

**Comment by SamyPesse** [comment]
This is related to #353, #364 and #354.

We are also concerned about this for our editor application, current performances make Slate unusable for production applications (the examples are unusable once you inserted more than 20/30 lines). But it can be improved (#354).

Backspace performance can also be improved separately by enabling the native mode for it (the native mode is what slate uses when you type to avoid re-rendering when the state has been transformed natively).

**Comment by hector-esv** [comment]
How do I enable the native mode for backspace?

**Comment by hector-esv** [comment]
I tried to use shouldComponentUpdate on node classes to reduce re-rendering, but it seems that any change will change the node objects so its impossible to use equality tests to see if they've changed or not.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/479
