### ISSUE TITLE
2x pressing space key, inserts dot / "." when in text.

### ISSUE THREAD

**Issue by kledk** [ianstormtaylor/slate#3674]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
2x press space key inserts a "." in the middle of words when caret is in text.

This happens in my local project and in the slate.js examples, eg: 
https://www.slatejs.org/examples/richtext

![spaces-dots](https://user-images.githubusercontent.com/3142986/81556484-a7e82400-938a-11ea-92d0-907b66e4fd6e.gif)

Slate: 0.58.0
Browser: Chrome 0.80
OS: Mac 10.15.4

#### What's the expected behavior?
No dot when 2x press space key.

**Comment by jerkly** [comment]
This is relate to Mac OS, not to slate.

`System Preferences` → `Keyboard` → `Text`, then check "Add full stop with double-space" option.

**Comment by kledk** [comment]
Oh, ah okay my bad!
Closing issue...
