### ISSUE TITLE
 Support TypeScript declaration merging

### ISSUE THREAD

**Issue by ccorcos** [ianstormtaylor/slate#3680]
Slate: 0.58.1

I'd really like to refine the internal editor types. Typescript supposedly has support for this:

https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

But I think its not working currently, because for example text.d.ts exports a interface Text and a const Text so I think Typescript is having trouble with that. 

Ideally, I can just write this code:

```ts
declare module "slate" {
	interface Text {
		bold?: string
	}
}
```

And now the text type everywhere in my codebase has a bold property.

**Comment by ccorcos** [comment]
I can confirm that renaming `interface Text` → `interface IText` solves this problem.

**Comment by ccorcos** [comment]
Just to give you a better sense of what I'm going after, this code is typesafe and lets me modularlize features.

```ts
declare module "slate" {
	interface IText {
		bold?: string
	}
	interface IEditor {
		bold: ReturnType<typeof createBoldInterface>
	}
}

function createBoldInterface(editor: IEditor) {
	return {
		isActive() {
			const [match] = Editor.nodes(editor, {
				match: (n) => n.bold === true,
				universal: true,
			})
			return !!match
		},
		toggle() {
			const isActive = editor.bold.isActive()
			Transforms.setNodes(
				editor,
				{ bold: isActive ? null : true },
				{ match: (n) => Text.isText(n), split: true }
			)
		},
	}
}

function withBold(editor: IEditor) {
	editor.bold = createBoldInterface(editor)
	return editor
}
```

That said, something I'm not super clear about yet -- what's the point of having methods on the editor instance and separating out all the static Editor helper functions that accept the editor as the first argument?

**Comment by CameronAckermanSEL** [comment]
This would seem like a good improvement to me, personally

**Comment by ccorcos** [comment]
I'll make a PR

**Comment by ccorcos** [comment]
Hmm. It won't let me make a PR... 
![image](https://user-images.githubusercontent.com/1794527/81845517-8495b400-9505-11ea-8807-094de8249fe1.png)

Here's what I did though: https://github.com/ianstormtaylor/slate/compare/master...ccorcos:master

I've tried to only make a minimal change (hence the last two reverts). But I think in general, it's a bad pattern to shadow variable names with types.

**Comment by TheSpyder** [comment]
Side note
>  it's a bad pattern to shadow variable names with types

I find this very useful, although yes it does hinder extending types. However instead of extending the built-in types, Slate methods could just support `<T extends Text>` etc as discussed in #3416

**Comment by ccorcos** [comment]
Yeah, I think generics would be a better solution. But it’s going to
require significantly more refactoring. Happy to help if you’d like.

**Comment by kxalex** [comment]
> I can confirm that renaming `interface Text` → `interface IText` solves this problem.

The prefix `I` may be confusing and the whole idea of an interface of hiding implementation + not telling anyone that you are using an interface. The practice of having `I` in front of interfaces leads that you describe parameters, data structures with `I` which is wrong. It's a data structure, not `interface`.

https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript

I, personally, like that slate does not use `I` prefix. 

PS: Microsoft and Facebook do not use it for a reason.

**Comment by ccorcos** [comment]
Yeah, I don't like that pattern either (and don't do it myself). I was just
trying to come up with a small and pragmatic solution for you all.

**Comment by ccorcos** [comment]
> Something I'm not super clear about yet -- what's the point of having methods on the editor instance and separating out all the static Editor helper functions that accept the editor as the first argument?

Any thoughts on this? @CameronAckermanSEL @ianstormtaylor 

Looking through the [`slate-history` package](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-history/src/history-editor.ts) and I'm not sure I understand why `undo()` and `redo()` are editor prototype methods while `isSaving(editor)` is not...

**Comment by TheSpyder** [comment]
v0.50 moved towards a more compositional architecture, having less _things_ on the editor by default.

I'm not sure in general why some methods were left on the editor directly, but in the case of `undo/redo` it's probably so the React editor doesn't explicitly depend on `slate-history` but can make use of it if it's available.
https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx#L739-L746

Even then, though, the implementation could still be in the static method and the instance method just calls it (instead of the other way around as happens today).

**Comment by thesunny** [comment]
Declaration merging requires an interface; however, an interface doesn't support union types.

Because of this, I wonder if we should close this issue in favour of a generic `type`. An example is a block that can be a paragraph, heading or list. With a `type`, we can define it as:

```ts
type MyElement = Element &
  (
    | { type: "paragraph" }
    | { type: "heading"; level: number }
    | { type: "list-item"; depth: number }
  )
```

The benefit is that we get type narrowing:

```ts
if (element.type === 'heading') {
  const level = element.level // works!
  // the following would give a useful TypeScript error
  // const depth = element.depth
}
```

**Comment by ccorcos** [comment]
@thesunny I agree -- is there another issue ticket for generic types or should I just modify this one? At the end of the day, I just want better types...

**Comment by thesunny** [comment]
I figured out a way that solves extensibility (only available in interface) and type discrimination (only available in types).

I think it warrants a separate Issue. Will post it today.

**Comment by thesunny** [comment]
Here's the proposal that supports declaration merging and type unions with type discrimination:

https://github.com/ianstormtaylor/slate/issues/3725

**Comment by mikestopcontinues** [comment]
I'd also like to add that the current form of declaration merging is messing up typescript's ability to differentiate the merged `Element` type from the `Element` export. When you merge, TS seems to become blind to the shadowed value.

Example:

```ts
import {Element as SlateElement} from 'slate';

declare module 'slate' {
  interface Element {
    type: 'p' | 'blockquote' | 'h1' | 'h2' | 'h3' | 'ol' | 'ul' | 'li';
  }
}

SlateElement.isElement(null); // 'SlateElement' only refers to a type, but is being used as a value here. ts(2693)
```

I suspect this problem might go away if you could export `Element` without renaming it, but of course, then typescript thinks you're referring to DOM `Element`:

```ts
import {Element} from 'slate';

Element.isElement(null); // Property 'isElement' does not exist on type '{ new (): Element; prototype: Element; }'. ts(2339)
```

**Comment by thesunny** [comment]
@mikestopcontinues Can you make sure your TypeScript version is the most recent? I have code that uses `Element.isElement` and it seems to work.

Unfortunately, because we are using a lot of cutting edge TypeScript, these new types are pretty sensitive to having to be used with recent versions. Ran across a number of situations which were solved by upgrading.

Let me know either way (if it works or if it continues to fail).

**Comment by mikestopcontinues** [comment]
@thesunny Sorry for the delay. I was finally able to get back to my slate code. It seems using the CustomX interface got things working for me. Thanks!

**Comment by ianstormtaylor** [comment]
I believe this was solved by @thesunny? But feel free to comment and we can re-open if not.
