### ISSUE TITLE
slate-hyperscript still use .flat. It crashed IE

### ISSUE THREAD

**Issue by PrimeObjects** [ianstormtaylor/slate#3681]
I applied a fix manually in index.es.js and it works very well, if you think it is good enough, feel free to apply to the source code. 

function deepFlatten(array)
{
  var result = []; 
  
  array.forEach(function (elem) {
    if (Array.isArray(elem)) {
        result = result.concat(deepFlatten(elem)); 
    } else {
        result.push(elem);
    }
  });
  
  return result;
};

Then you can use it like the code below 
children = deepFlatten(children.filter(child => Boolean(child)));

**Comment by CameronAckermanSEL** [comment]
Hi @PrimeObjects , slate does not support IE11 out of the box. You may address this by using a polyfill, but IE11 is missing too many modern js features for this library to support it, and microsoft doesn't even consider it to be a browser to be used for common consumption of modern web applications.

**Comment by PrimeObjects** [comment]
FYI, it also failed on IE Edge.

**Comment by PrimeObjects** [comment]
but my code above fixes it, you can apply the code and it will solve the issue,

**Comment by CameronAckermanSEL** [comment]
It will probably fail on legacy edge, but the chromium based edge should work fine.
