### ISSUE TITLE
Doc: What does `hanging` mean?

### ISSUE THREAD

**Issue by lcswillems** [ianstormtaylor/slate#3683]
#### Question

From the source code and the documentation, I can't understand what "hanging" means. Could somebody explain?

I think it would be nice to explain it somewhere in the documentation.

**Comment by majelbstoat** [comment]
Hey @lcswillems, from the issue template:

```
If you have a question, ask it in our Slack channel instead:

https://slate-slack.herokuapp.com/
```

(Or, you could restructure this as a documentation request!)

**Comment by lcswillems** [comment]
I have updated the issue. Why not allowing Github Discussions on this repo? The big advantage is that they will be indexed by Google.

**Comment by majelbstoat** [comment]
That is a good suggestion. @CameronAckermanSEL, thoughts?

**Comment by CameronAckermanSEL** [comment]
Its a fair point, however this has been a long standing request by Ian and it's really up to him to change it. 

That said, the request for documentation on what hanging means is a perfectly reasonable enhancement request for the documentation

**Comment by majelbstoat** [comment]
Perhaps you know this, but I think @lcswillems means the relatively new Discussions feature, like for example, https://github.com/zeit/next.js/discussions. The concept didn't exist in Github until recently. 

They don't count as issues, and can be answered by anyone. Might help with some of the recurring questions we get in Slack about DOM selection, last focused position, how to match/nodes effectively etc.

(I definitely agree we shouldn't have questions as issues here.)

**Comment by CameronAckermanSEL** [comment]
Oh! I didn't know that feature was a thing!

**Comment by cymoo** [comment]
@lcswillems Maybe you can guess the meaning of `hanging` by reading some test cases [](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/test/transforms/setNodes/block/block-hanging.js)

**Comment by lcswillems** [comment]
I don't get it either... Is somebody able to explain this concept with a sentence?

**Comment by Wulf** [comment]
From my experience, hanging means that the selection is on a node but hasn't really selected anything in the node. For example:

Given this slate document:
```
[{text: 'one '}, {text: 'two', bold: true}, {text: ' three'}]
```
It would render like so:
> one **two** three

Now if we selected the "two":
> one |**two**| three

We don't really have a guarantee of the selection's path and offset for the anchor and focus points.

So let's go over the possible scenarios for `editor.selection`:

```
// 1 -- no hanging
{
  anchor: { path: [1], offset: 0 },
  focus: { path: [1], offset: 3 }
}

// 2 -- anchor hanging
{
  anchor: { path: [0], offset: 4 },
  focus: { path: [1], offset: 3 }
}

// 3 -- focus hanging
{
  anchor: { path: [1], offset: 0 },
  focus: { path: [2], offset: 0 }
}

// 4 -- both hanging
{
  anchor: { path: [0], offset: 4 },
  focus: { path: [2], offset: 0 }
}
```

so if you use `Editor.unhangRange(editor, editor.selection)`, it will always return the first scenario (no hanging).

**Comment by lcswillems** [comment]
Thank you for your answer! Now, I get it!

A simple sentence would be: *a range is hanging if it starts at the end of a node or ends at the start of a node*.

**Comment by beorn** [comment]
Perhaps include a note about when/why this happens, why it matters, and when/why/how to fix it?

**Comment by tmikeschu** [comment]
> From my experience, hanging means that the selection is on a node but hasn't really selected anything in the node. For example:
> 
> Given this slate document:
> 
> ```
> [{text: 'one '}, {text: 'two', bold: true}, {text: ' three'}]
> ```
> 
> It would render like so:
> 
> > one **two** three
> 
> Now if we selected the "two":
> 
> > one |**two**| three
> 
> We don't really have a guarantee of the selection's path and offset for the anchor and focus points.
> 
> Let's go over the possible scenarios for `editor.selection`:
> 
> ```
> // 1 -- no hanging
> {
>   anchor: { path: [1], offset: 0 },
>   focus: { path: [1], offset: 3 }
> }
> 
> // 2 -- anchor hanging
> {
>   anchor: { path: [0], offset: 4 },
>   focus: { path: [1], offset: 3 }
> }
> 
> // 3 -- focus hanging
> {
>   anchor: { path: [1], offset: 0 },
>   focus: { path: [2], offset: 0 }
> }
> 
> // 4 -- both hanging
> {
>   anchor: { path: [0], offset: 4 },
>   focus: { path: [2], offset: 0 }
> }
> ```
> 
> If you use `Editor.unhangRange(editor, editor.selection)`, it will always return the first scenario (no hanging).
> 
> Hehe, I came here looking for whether there was a bug with hanging selection and I ended up finding that someone has already created an [issue](https://github.com/ianstormtaylor/slate/issues/3336) and [PR](https://github.com/ianstormtaylor/slate/pull/3374). Hope it gets merged soon!

Hello! Wanted to point out that based on the [implementation](https://github.com/ianstormtaylor/slate/blob/60b56651b2e1e6f58bcf29a1a876612720a4fe2c/packages/slate/src/interfaces/editor.ts#L1260), neither offset can be non-zero. I think that means

> A range is hanging if it starts at the end of a node AND ends at the start of a node.

?

If it _should_ be an _or_, I think the the code has a bug and should be

```tsx
    if ((start.offset !== 0 && end.offset !== 0) || Range.isCollapsed(range)) {
```

**Comment by techird** [comment]
Also intrested here, does partially hanging (scenario 2 and 3) can defined as hanging?
