### ISSUE TITLE
cursor

### ISSUE THREAD

**Issue by 596121109** [ianstormtaylor/slate#3684]
Re rendering the editor content will cause the cursor to disappear. You need to click the cursor again to get out. That is to say, you need to click the editor again to get the cursor out every time you input a character

**Comment by lcswillems** [comment]
I think it will be hard to understand what you mean with such elliptic title + description.

Adding a more accurate text + description is not making you waste time. On the contrary, it makes you win time because it is much more likely others will understand you and be able to help you.

What do you mean by "re-rendering"? I don't have the issue you describe on my side. Which version are you using? This is asked in the template...

**Comment by 596121109** [comment]
Thank you for your reply. I mean: there is a personnel list on the left side of my page. On the right side is the description of the personnel list. When I click the list on the left, the corresponding personnel information will appear on the right side. Obviously, my personnel information display is the slate editor, When I click the list on the left, the right side is updated, but after the update, the content of slate editor changes, but the cursor disappears, so I need to click the editor again to call him up.

**Comment by lcswillems** [comment]
I think it is intended because Slate loses focus.

Have you tried to use `ReactEditor.focus(editor)` to focus editor again?

What is your Slate version please?

**Comment by 596121109** [comment]
0.13 version ， What do you mean “ReactEditor.focus(editor)”, please

**Comment by 596121109** [comment]
Every time I input a word, the cursor disappears. I need to click the area again to wake up the cursor

**Comment by 596121109** [comment]
![image](https://user-images.githubusercontent.com/16631844/81907530-7d9c9d80-95fa-11ea-87bf-14e8d070ff3e.png)
![image](https://user-images.githubusercontent.com/16631844/81907553-85f4d880-95fa-11ea-8ff9-96eb4002548f.png)
![Uploading image.png…]()

**Comment by lcswillems** [comment]
0.13 is a very very old version that I don't know. I can't help you and encourage you to upgrade since it will surely help you solve your issue.

**Comment by 596121109** [comment]
think you !

**Comment by BrentFarese** [comment]
Closing this issue as it seems resolved or outdated.  Thanks!
