### ISSUE TITLE
Unable to copy and paste last node if void-node

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#370]
If you have a void-node as the last node in the document. Selecting it and copying it will result in the error: 

`Uncaught Error: Invalid 'key' argument! It must be either a block, an inline, a text, or a string. You passed: "undefined".`

If there is a paragraph (non-void) node below, copying and pasting works as expected.

Steps to reproduce:

Go to http://slatejs.org/#/embeds?_k=11ykkh
Delete last paragraph.
Select the video node. Copy and paste it.

EDIT: seems like it also happens when there is an empty paragraph in the end.

**Comment by skogsmaskin** [comment]
Maybe related to https://github.com/ianstormtaylor/slate/pull/360#issuecomment-252268762

**Comment by ianstormtaylor** [comment]
I can't reproduce this in `0.15`, but it might still be an issue. If you see the same error happening, please re-open.
