### ISSUE TITLE
Is anyone doing any work or has extensions for Slate that are non-react?

### ISSUE THREAD

**Issue by adamreisnz** [ianstormtaylor/slate#3707]
From reading the docs of this project I was under the assumption it was a front-end framework agnostic editor, but by reading the installation walkthrough it seems it is built for React and requires React as a peer dependency. Is there any progress on non-react version, e.g. framework agnostic, or Vue based?

**Comment by marsprince** [comment]
I wrote a vue based [slate-vue](https://github.com/marsprince/slate-vue). And you can find the package slate-vue in npm

**Comment by adamreisnz** [comment]
@CameronAckermanSEL not all questions fit inside a template

**Comment by CameronAckermanSEL** [comment]
@adamreisnz you're right. That's why the template says to ask in slack instead.

```

<!--
If you have a question, ask it in our Slack channel instead:

https://slate-slack.herokuapp.com/
-->
```

And

https://github.com/ianstormtaylor/slate/issues/3599

**Comment by adamreisnz** [comment]
Because we all want to join yet another slack / gitter channel when we have
a simple question...
