### ISSUE TITLE
 the cursor can not be maintained after deleteFragment when typing ime

### ISSUE THREAD

**Issue by Manwzy** [ianstormtaylor/slate#3709]
#### Do you want to request a _feature_ or report a _bug_?

maybe a bug

#### What's the current behavior?

Here is the Repo: https://codesandbox.io/s/tender-water-5nk3o?file=/src/App.js

when i select multi line and  type ime directly, the editor will crash after I type blank space. The main reason I figure out is  the browser will remove the dom when typing ime, which means the inner data cannot match with the dom structure any more so that react cannot render correctly. 

To solve this problem, I try to delete selected fragment at the moment of onCompositionStart, and it works. However, it leads to another problem，that the cursor cannot be maintained. Actually, the data inserting action is correct, but cursor is at wrong place.

Here is my code: 
```js
<Editable
    onCompositionStart={() => {
      if (editor.selection && !Range.isCollapsed(editor.selection)) {
        editor.deleteFragment();
      }
    }}
/>
```

Here is the behaviour: 
![Untitled_ May 31, 2020 2_28 PM](https://user-images.githubusercontent.com/28730927/83346727-9e325a80-a351-11ea-9882-49e6eb0bc013.gif)

Slate: 0.58.1
Browser: Chrome
OS: Mac / Windows 

#### What's the expected behavior?

 the cursor can still be maintained after deleteFragment when typing ime

**Comment by laobeijing0806** [comment]
this PR [https://github.com/ianstormtaylor/slate/pull/3342](url), it solved your problem
