### ISSUE TITLE
Backspace does not delete an inline void node when it is selected

### ISSUE THREAD

**Issue by lcswillems** [ianstormtaylor/slate#3711]
#### What's the current behavior?

On the [mentions example](https://www.slatejs.org/examples/mentions), if I click on a mention and I hit "backspace", the mention is not deleted. It would be nice to allow to delete them.

If somebody has a hint to implement this, I can do a PR.

Slate: 0.58.2
Browser: Chrome
OS: Linux

**Comment by CameronAckermanSEL** [comment]
This is a bug, and I think it's related to this: https://github.com/ianstormtaylor/slate/issues/3665

**Comment by CameronAckermanSEL** [comment]
(I edited your post, I hope you dont mind)

**Comment by idevelop** [comment]
Duplicate of #3456

**Comment by CameronAckermanSEL** [comment]
Thanks, I knew I had seen it elsewhere!
