### ISSUE TITLE
Convert examples to typescript

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#3713]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

All of the current slate examples are in javascript. While this does make the examples a little easier to maintain in the long run, it makes it harder to discover type issues while making changes to the library, and there's less guidance for users who are trying to use slate with typescript and are less experienced.

Slate: 0.58.2
Browser: NA
OS: NA

#### What's the expected behavior?
The examples should be in typescript like the library.

**Comment by wendellhu95** [comment]
I am working on it, it there's nobody had started his/her work.

**Comment by machineghost** [comment]
Please do not remove the Javascript examples: Typescript is great, but it's *not* Javascript 2.0!

All Javascript libraries should provide *Javascript* examples. Please don't forget that the significant majority (by any dev survey that I've seen at least) of all devs continue to use Javascript, not Typescript.

**Comment by CameronAckermanSEL** [comment]
Hi @machineghost , I think you're overestimating the difference between typescript and javascript. In the style that's used in slate, typescript is mostly limited to adding type descriptors to variables and function signatures. The code is not written in C# style like you would see in some typescript libraries. 

As such, moving the examples to typescript will help us catch type problems on the API a little bit better without _doubling our support burden by having duplicate examples that have no value to the example site_. Thanks for your feedback, but we should move the examples to typescript.

**Comment by machineghost** [comment]
Fair enough, but IMHO you should really start calling yourself a Typescript library and not a Javascript library if all your examples will be in Typescript.

**Comment by CameronAckermanSEL** [comment]
Given that you can use typescript and javascript easily in the same project with minimal configuration, I don't see how this distinction is meaningful to users at large.

**Comment by machineghost** [comment]
IF you know Typescript.  If you don't it's literally invalid Javascript code in your examples.

**Comment by CameronAckermanSEL** [comment]
I find it highly unlikely that a developer with the engineering savvy required to consume a library of this complexity is going to have trouble distinguishing between typescript and javascript.

**Comment by machineghost** [comment]
Yup, no new JS learners will ever use Slate ...

**Comment by CameronAckermanSEL** [comment]
@machineghost  Enough.
