### ISSUE TITLE
Your connection is not private - NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by kode-ninja** [ianstormtaylor/slate#3719]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

https://docs.slatejs.org has cert issues and cannot be accessed

![image](https://user-images.githubusercontent.com/7857611/83756020-18771d80-a677-11ea-8525-15b704ddbbd1.png)

Slate: 0.XX.X
Browser: Chrome
OS: Windows

**Comment by CameronAckermanSEL** [comment]
https://github.com/ianstormtaylor/slate/issues/3720
