### ISSUE TITLE
Should './utils/normalize' be exported?

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#372]
`./utils/normalize` is not exported from slate. Maybe it should?

`Normalize.block` seems like a very handy function to have in plugins for creating new blocks.

**Comment by ianstormtaylor** [comment]
I could be convinced for sure. I think I'd ideally like to make `Block.create` a lot better at handling some of the edge cases itself, and get rid of the need for some of the normalizing helpers. But regardless, I agree with your goal of making it easier for plugins/users to create nodes!
