### ISSUE TITLE
Documentation page is not responding

### ISSUE THREAD

**Issue by kvvojciechowski** [ianstormtaylor/slate#3720]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?
Page docs.slatejs.org (documentation link from README) throws `ERR_NAME_NOT_RESOLVED`

Slate: n/a
Browser: Chrome 83.0.4103.61, Safari 13.1 (15609.1.20.111.8)
OS: Mac, Windows

#### What's the expected behavior?
`docs.slatejs.org` should respond with proper documentation page.

**Comment by CameronAckermanSEL** [comment]
It looks like this is loading now, is this still an issue?

**Comment by CameronAckermanSEL** [comment]
I'm going to close this because it looks like it's functioning now. Please let me know if you're still running into problems!

**Comment by kvvojciechowski** [comment]
Thanks. It's working correctly now.
