### ISSUE TITLE
Cursor vertical position after large inline void element.

### ISSUE THREAD

**Issue by jakehamilton** [ianstormtaylor/slate#3728]
#### Do you want to request a _feature_ or report a _bug_?

A bug.

#### What's the current behavior?

When moving the cursor immediately after the image, the cursor will no longer be vertically aligned with the other text. This issue **only** happens on Chrome as far as I can tell. The cursor positions correctly on Firefox. (A separate issue occurs on Safari where the cursor is made too large.)

Reproduction: https://codepen.io/short/pen/8087e3633304a8a19027555cc1cde0ab?editors=0011

<img width="771" alt="image" src="https://user-images.githubusercontent.com/7005773/84067503-52e50100-a97c-11ea-8ea6-c3e765b81439.png">

Slate: 0.57.1
Browser: Chrome
OS: Mac

Note: I'm unable to record a GIF of the problem due to permissions on my work computer. However, the linked Codepen should suffice.

#### What's the expected behavior?

The cursor should respect the existing vertical alignment of the document. This behavior is already working in Firefox:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/7005773/84067934-14037b00-a97d-11ea-800a-e7352520a6bb.png">

**Comment by jerkly** [comment]
This bug relate to css. Duplicate #3390 
Note this discussion: https://stackoverflow.com/questions/61332798/caret-position-and-selection-height-for-inline-elements-in-chrome

**Comment by jakehamilton** [comment]
Ah, thank you @jerkly. I looked around quite a bit before making this issue, wish I found that thread. Will try this out tomorrow.

**Comment by jakehamilton** [comment]
To follow up on this issue, I wasn't able to solve the problem. After playing with `flexbox`, `vertical-align`, `float`, etc., we decided that this wasn't something worth investing more time in. If anyone finds a CSS hack that can fix this please do let me know! 🙏

As things are right now, I'll close this issue as there isn't really anything else to do for it. Thanks to everyone working on Slate ❤
