### ISSUE TITLE
Add Examples and/or Documentation for Syntax Highlighting in Slate

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3733]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Currently, there are no examples or documentation related to getting syntax highlighting working with Slate 0.5x. Earlier versions of Slate had syntax highlighting examples.

Based on searching Slate's Slack, nobody has successfully implemented Syntax Highlighting with the current version of Slate.

#### What's the expected behavior?

There should be an example and/or documentation on how to get syntax highlighting working with the current version of Slate.

**Comment by fsanal** [comment]
This would be very useful!

**Comment by mdmjg** [comment]
working on this!

**Comment by thesunny** [comment]
@mdmjg Thank you so much! Can't wait to see this land.
