### ISSUE TITLE
  types error in 0.58.3 when i use typescript

### ISSUE THREAD

**Issue by find456789** [ianstormtaylor/slate#3734]
#### Do you want to request a _feature_ or report a _bug_?
 bug 

#### What's the current behavior?
i got error:
```
Argument of type 'Node[]' is not assignable to parameter of type 'SetStateAction<{ type: string; children: { text: string; }[]; }[]>'.
  Type 'Node[]' is not assignable to type '{ type: string; children: { text: string; }[]; }[]'.
    Type 'Node' is not assignable to type '{ type: string; children: { text: string; }[]; }'.
      Property 'type' is missing in type 'Editor' but required in type '{ type: string; children: { text: string; }[]; }'.  TS2345
```

Slate: 0.58.3
Browser: Chrome  
OS: Mac  

#### What's the expected behavior?
no error

## this is my code:
```
// code from https://docs.slatejs.org/walkthroughs/01-installing-slate
// Import React dependencies.
import React, { useEffect, useMemo, useState } from "react";
// Import the Slate editor factory.
import { createEditor } from 'slate'

// Import the Slate components and React plugin.
import { Slate, Editable, withReact } from 'slate-react'


export const Editor = () => {
    const editor = useMemo(() => withReact(createEditor()), [])
    // Add the initial value when setting up our state.
    const [value, setValue] = useState([
      {
        type: 'paragraph',
        children: [{ text: 'A line of text in a paragraph.' }],
      },
    ])
  
    return (
      <Slate editor={editor} value={value} onChange={newValue => setValue(newValue)}>
        <Editable />
      </Slate>
    )
  }
```
# this is my way , can fix the error:
change the code: 
1.add `import { Node } from 'slate';`
2. change   
```
const [value, setValue] = useState([
      {
        type: 'paragraph',
        children: [{ text: 'A line of text in a paragraph.' }],
      },
    ])
```

to
```
const [value, setValue] = useState<Node[]>([
      {
        type: 'paragraph',
        children: [{ text: 'A line of text in a paragraph.' }],
      },
    ])

```

its work!!!

the point is `useState<Node[]>`

**Comment by kanweiwei** [comment]
这个不算bug吧

**Comment by alexander-zolotykh** [comment]
Why did you change interfaces from:

```
[key: string]: any;
```

```
[key: string]: unknown;
```
?

Please put back previous variant.

**Comment by bmingles** [comment]
@stfenjobs  The proposed change is appropriate for TypeScript, but the walkthroughs are currently written in plain .js. I don't think this will work unless the examples also include TypeScript version. This would be awesome, but it does change the scope of this request to something bigger.

**Comment by idonov** [comment]
Just used Slate for the first time and with TS, i still get this issue in 0.60.11

code:
`const [value, setValue] = useState<Node[]>([
    {
      type: "paragraph",
      children: [{ text: "A line of text in a paragraph." }],
    },
  ]);`

error:
Type '{ type: string; children: { text: string; }[]; }' is not assignable to type 'Node'.
  Object literal may only specify known properties, and 'type' does not exist in type 'Node'.

**Comment by codercodingthecode** [comment]
This is how I solved it.

```typescript 
 import { Descendant } from 'slate'
 const [value, setValue] = useState<Descendant[]>([{ type: 'paragraph', children: [{ text: '' }] }])
```

The documentation doesn't show this part, but you also have to add slate history and empty children.
Basically, the whole sample app looks like this:
```typescript
import React, { useMemo, useState } from 'react'
import { createEditor, BaseEditor, Descendant } from 'slate'
import { Slate, Editable, withReact, ReactEditor } from 'slate-react'
import { HistoryEditor } from 'slate-history'

type CustomText = { text: string }
type CustomElement = { type: 'paragraph'; children: CustomText[] }

declare module 'slate' {
    interface CustomTypes {
        Editor: BaseEditor & ReactEditor & HistoryEditor
        Element: CustomElement
        Text: CustomText
    }
}

export const Note = () => {
    const editor = useMemo(() => withReact(createEditor()), [])
    const [value, setValue] = useState<Descendant[]>([{ type: 'paragraph', children: [{ text: '' }] }])
    return (
        <Slate
            editor={editor}
            value={value}
            onChange={(newValue) => setValue(newValue)}
        >
            <Editable />
        </Slate>
    )
}

**Comment by pukingrainbows** [comment]
Typescript is complaining about BaseEditor is not exported, I tried the solution from @codercodingthecode compiled buts doesn't show anything, 
For my case I ended just declaring the state as  `useState<Descendant[]>()` and did the trick.

```
import React from "react"
import { createEditor, Descendant } from "slate"
import { Slate, withReact, Editable } from "slate-react"

export default function Editor() {
  const editor = React.useMemo(() => withReact(createEditor()), [])
  const [value, setValue] = React.useState<Descendant[]>([{ children: [{ text: "hi" }] }])

  return (
    <Slate editor={editor} value={value} onChange={(newValue) => setValue(newValue)}>
      <Editable />
    </Slate>
  )
}
```
🤷

**Comment by idonov** [comment]
> Typescript is complaining about BaseEditor is not exported, I tried the solution from @codercodingthecode compiled buts doesn't show anything,
> For my case I ended just declaring the state as `useState<Descendant[]>()` and did the trick.
> 
> ```
> import React from "react"
> import { createEditor, Descendant } from "slate"
> import { Slate, withReact, Editable } from "slate-react"
> 
> export default function Editor() {
>   const editor = React.useMemo(() => withReact(createEditor()), [])
>   const [value, setValue] = React.useState<Descendant[]>([{ children: [{ text: "hi" }] }])
> 
>   return (
>     <Slate editor={editor} value={value} onChange={(newValue) => setValue(newValue)}>
>       <Editable />
>     </Slate>
>   )
> }
> ```
> 
> 🤷

I did something similar, I used CustomElement[] instead of Descendant[]. I needed to not import anything 'slate' because of loadable-components separation

**Comment by EKOLX** [comment]
Same thing:
`const initialValue = [
  {
    type: "paragraph",
    children: [{ text: "Enter your post here." }],
  },
];
`
`
const [value, setValue] = useState<Node[]>(initialValue);`

With initial value there are no issue, but
` useEffect(() => {
    if (existingBody) {
      setValue([
        {
          type: "paragraph",
          text: existingBody,
        },
      ]);
    }
  }, []);`
here it complains
`Object literal may only specify known properties, and 'type' does not exist in type 'Node'`

**Comment by idonov** [comment]
> Same thing:
> `const initialValue = [ { type: "paragraph", children: [{ text: "Enter your post here." }], }, ]; `
> ` const [value, setValue] = useState<Node[]>(initialValue);`
> 
> With initial value there are no issue, but
> ` useEffect(() => { if (existingBody) { setValue([ { type: "paragraph", text: existingBody, }, ]); } }, []);`
> here it complains
> `Object literal may only specify known properties, and 'type' does not exist in type 'Node'`

use this:
const [value, setValue] = React.useState<Descendant[]>([{ children: [{ text: "hi" }] }])

and some where in code define yout CustomElement as CustomElement = YourParagraphElement | YourImageElement etc...

**Comment by jsoneaday** [comment]
> This is how I solved it.
> 
> ```ts
>  import { Descendant } from 'slate'
>  const [value, setValue] = useState<Descendant[]>([{ type: 'paragraph', children: [{ text: '' }] }])
> ```
> 
> The documentation doesn't show this part, but you also have to add slate history and empty children.
> Basically, the whole sample app looks like this:
> 
> ```ts
> import React, { useMemo, useState } from 'react'
> import { createEditor, BaseEditor, Descendant } from 'slate'
> import { Slate, Editable, withReact, ReactEditor } from 'slate-react'
> import { HistoryEditor } from 'slate-history'
> 
> type CustomText = { text: string }
> type CustomElement = { type: 'paragraph'; children: CustomText[] }
> 
> declare module 'slate' {
>     interface CustomTypes {
>         Editor: BaseEditor & ReactEditor & HistoryEditor
>         Element: CustomElement
>         Text: CustomText
>     }
> }
> 
> export const Note = () => {
>     const editor = useMemo(() => withReact(createEditor()), [])
>     const [value, setValue] = useState<Descendant[]>([{ type: 'paragraph', children: [{ text: '' }] }])
>     return (
>         <Slate
>             editor={editor}
>             value={value}
>             onChange={(newValue) => setValue(newValue)}
>         >
>             <Editable />
>         </Slate>
>     )
> }
> ```

This works great thanks, but can you tell me now what would the type for marks be? Specifically I have a function called isMarkActive what is the type for the key? Type any does not work.

```
const isMarkActive = (editor: Editor, format: any) => {
  const marks = Editor.marks(editor);
  return marks ? marks[format] === true : false;
};
```

**Comment by connorjacobsen** [comment]
> 
> This works great thanks, but can you tell me now what would the type for marks key be? Specifically I have a function called isMarkActive what is the type for the key? Type any does not work. The type for marks is shown as Omit<Text, "text">. So far I've tried giving format a type of any, string, string | number, "text", and CustomText. None has worked.
> 
> ```
> const isMarkActive = (editor: Editor, format: any) => {
>   const marks = Editor.marks(editor);
>   return marks ? marks[format] === true : false;
> };
> ```

There is probably a better way to do this (which I would love to hear about), but I have done:

```typescript
export interface CustomText extends BaseText {
  bold?: boolean;
  code?: boolean;
  italic?: boolean;
  underlined?: boolean;
}

export const isFormatActive = (editor: Editor, format: string): boolean => {
  const marks = Editor.marks(editor);

  switch (format) {
    case 'bold':
      return marks?.bold || false;
    case 'code':
      return marks?.code || false;
    case 'italic':
      return marks?.italic || false;
    case 'underlined':
      return marks?.underlined || false;
    default:
      return false;
  }
};
```

**Comment by codercodingthecode** [comment]
@jsoneaday and @connorjacobsen or anyone else. If you guys can share a sandbox I can take a look at it.
