### ISSUE TITLE
Path.transform doesn't handle move_node properly (p=onp, op<onp, op and onp are siblings)

### ISSUE THREAD

**Issue by wleroux** [ianstormtaylor/slate#3737]
https://github.com/ianstormtaylor/slate/blob/32e120af191930433490093f44f022570bc2ea72/packages/slate/src/interfaces/path.ts#L394-L401

By moving the node at [2, 1], to [2, 5], the node at [2, 5] actually remains at [2, 5]... Since moving the node at [2, 1] causes the post-operation path [2, 5] to actually be [2, 4]. Hence, a node at [2, 5] remains at [2, 5] post-operation.

Test case:

Path to Transform: [2, 5]
Operation: Move Node at [2, 1] to [2,5]

Expected Result: [2, 5]
Actual Result: [2, 4]

**Comment by wleroux** [comment]
I think the code should just be:

```
   if (!Path.endsBefore(op, p)) { 
     p[op.length - 1] += 1 
   } 
```

**Comment by jason-krypton** [comment]
I think you are considering this a bit incorrectly. And pretty easy to show. If you execute the the moveNode transform on an editor you will see that the node at position [2,5] is no longer at the same index. 

Consider the following example:

Starting state `0 1 2 3 4 5 6 7 8 9` (Where each number is a node)
Moving 1 -> 5
First remove 1 --> `0 2 3 4 5 6 7 8 9` (Causes all nodes after the path index to shift forward)
Insert node at index 5 --> `0 2 3 4 5 1 6 7 8 9`

Node that was at index 5 is now at index 4

**Comment by wleroux** [comment]
I believe that my original understanding is correct as per the way that the move_node operation is executed:

https://github.com/ianstormtaylor/slate/blob/32e120af191930433490093f44f022570bc2ea72/packages/slate/src/interfaces/editor.ts#L1327-L1336

That is to say... The path in move_node operation operates on path locations before the operation is performed... so a move from nodes 1 to 5 means... Move the node at index 1 to where the index 5 currently is... However, by removing the node at index 1, the index 5 will be now at index 4.

**Comment by wleroux** [comment]
Turns out you were correct! The comments made me think the movement was based on the 'snapshot' index (i.e.: you specified where you wanted the node to go using indexes. `abcdef` would have possible positions `0a1b2c3d4e5f6`)... That is not the case.
