### ISSUE TITLE
Path.transform doesn't handle move_node properly (p=op, op<onp)

### ISSUE THREAD

**Issue by wleroux** [ianstormtaylor/slate#3738]
https://github.com/ianstormtaylor/slate/blob/32e120af191930433490093f44f022570bc2ea72/packages/slate/src/interfaces/path.ts#L385-L392

By moving the node at [2, 1], to [2, 5], the node at [2,1] actually becomes node [2, 4].

Test case:

Path to Transform: [2,1]
Operation: Move Node at [2, 1] to [2,5]

Expected Result: [2,4]
Actual Result: [2,5]

I believe the code should actually read:

```javascript
          if (Path.isAncestor(op, p) || Path.equals(op, p)) {
            const copy = onp.slice()

            if (Path.endsBefore(op, onp)) {
              copy[op.length - 1] -= 1
            }

            return copy.concat(p.slice(op.length))
```

**Comment by jason-krypton** [comment]
You can run the Transform.moveNode code on an editor to show this isn't true. The ending index of the node at `[2,1]` will end at `[2,5]`.

**Comment by wleroux** [comment]
You're right, the comment made me believe that the approach taken was different than the actual behavior. I believed the index was determined before the the move. For instance `abcdef` would have positions `0a1b2c3d4e5f6` So moving node 1, `b`, to index 5 meant the intention was for the change to become `acdebf`.
