### ISSUE TITLE
Inverted move_node operation does not reference newPath

### ISSUE THREAD

**Issue by wleroux** [ianstormtaylor/slate#3739]
https://github.com/ianstormtaylor/slate/blob/32e120af191930433490093f44f022570bc2ea72/packages/slate/src/interfaces/operation.ts#L237-L246

The inverse operation for move_node should capture the new location of both the path and newPath, however it doesn't.

I believe the code should be:

```javascript
   const inversePath = Path.transform(newPath, op)! 
   const inverseNewPath = Path.transform(path, op)! 
   return { ...op, path: inversePath, newPath: inverseNewPath } 
```

**Comment by wleroux** [comment]
It should be noted that by inverting this operation, the resultant operation is a no-op... (moving a node from n to n+1 results in no movement). This would cause future inverted operations that assume the inversion was done property to fail.

**Comment by jason-krypton** [comment]
Can you provide a specific example that you think does not invert correctly?

Also moving from n -> n+1 does result in movement, which you can check by calling `Transform.moveNodes` on an editor.

**Comment by wleroux** [comment]
Alright, I understand it better, the `Path.transform(path, op)` becomes `newPath` because that's what the operation does... And Path.next(path) is the node that ends up where `path` was... My brain got tripped up because it didn't refer to `newPath` at all... Please disregard!
