### ISSUE TITLE
Error: Invalid key argument in getInlinesAtRange (stale selection state?)

### ISSUE THREAD

**Issue by roadscape** [ianstormtaylor/slate#376]
To reproduce: go to http://slatejs.org/#/links and try to remove the link.

`Invalid``key``argument! It must be either a block, an inline, a text, or a string. You passed: "null".`

![image](https://cloud.githubusercontent.com/assets/5168676/19282326/e110ad96-8fbb-11e6-9ead-004a3d4c4e37.png)

**Comment by roadscape** [comment]
Minimal jsfiddle case: https://jsfiddle.net/6jy8a5bk/1/

After the new state is applied, the component re-renders, but hasLinks causes an exception.

I think this may be due to `selection` being stale immediately after setState, during the 2nd rendering.

**Comment by arekkas** [comment]
This also happens if a link is the first element in a node:

![slate](https://cloud.githubusercontent.com/assets/3372410/19961243/cf0f6eb8-a1b1-11e6-82f2-bb6b72c85cc7.gif)

**Comment by arekkas** [comment]
This is resolved with slate 0.15
