### ISSUE TITLE
Some Slate components cannot seem to handle whitespace.

### ISSUE THREAD

**Issue by calthejuggler** [ianstormtaylor/slate#3761]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behaviour?
I have a Slate editable, allowing users to add topics or comments to my forum. The problem is, when they add a new topic or comment that includes any whitespace (A line with no text on it), upon clicking send, React throws the following error:
```
Error: Cannot find a descendant at path [2,0] in node: {"children":[{"type":"paragraph","children":[{"text":""}]}],"operations":[],"selection":{"anchor":{"path":[2,0],"offset":0},"focus":{"path":[2,0],"offset":0}},"marks":null}
```
What's strange is that, even though this error gets thrown, the comment or topic is added to my database anyway. And what's even stranger - I have a similar component for editing a topic or comment that has already been posted. When you edit an existing post, this error doesn't happen at all!

In the following video, I make a post with no bug and then I cause the bug to happen by posting again, but adding an empty line. (The line could be anywhere, not just at the end).

![Broken whitespace Slate issue GIF](https://user-images.githubusercontent.com/30095183/86369921-5d46a200-bc7f-11ea-84cb-bca33dcbb945.gif)

And here is the state before I clicked send (Approximately):
![Form state before the error comes](https://user-images.githubusercontent.com/30095183/86375413-eb258b80-bc85-11ea-89e1-1176964cfa6d.png)

The error in the console seems to point towards `leaf`s in some way:
![image](https://user-images.githubusercontent.com/30095183/86377944-4e64ed00-bc89-11ea-89ac-fba16da9f8ac.png)

Slate: 0.57.3
Browser: Chrome / Safari (And maybe others)
OS: Mac / Windows (And maybe others)

#### What's the expected behaviour?
I expect it to upload the posts without throwing an error! I guess it is because the `"text"` key in the `Node[]` is empty as `""`, but I can't see why that wouldn't register as an empty string.

Pleases and thank yous in advance!

**Comment by CameronAckermanSEL** [comment]
Hey @calthejuggler , it's hard to tell what's going on without some code to look at. We might be able to get away with the snippet you're using to insert your text and how it's being called, but a minimum reproduction would be the best.

Thanks!

**Comment by calthejuggler** [comment]
Hey @CameronAckermanSEL ! Thanks. It's a bit complicated, but I'll try...

So, I have a TextAreaInput component, which looks like this (I have removed anything that I'm pretty sure is unimportant:
```
// ... React and Slate imports

import MarkButton from './components/MarkButton';
import Toolbar from './components/Toolbar';
import BlockButton from './components/BlockButton';

const Element = ({ attributes, children, element }: RenderElementProps) => {
	switch (element.type) {
		case 'block-quote':
			return <blockquote {...attributes}>{children}</blockquote>;
// ... More switch cases...
		default:
			return <p {...attributes}>{children}</p>;
	}
};

const Leaf = ({ attributes, children, leaf }: RenderLeafProps) => {
	if (leaf.bold) {
		children = <strong>{children}</strong>;
	}
// ... More if (leaf.foo) {}
	return <span {...attributes}>{children}</span>;
};

const TextAreaInput: FC<TextAreaInterface> = ({
	state,
	setState,
	placeholder,
}) => {
	const editor: ReactEditor = useMemo(() => withReact(createEditor()), []);

// ...Hotkey codes

	const toggleMark = (editor: ReactEditor, format: string) => {
		const isActive = isMarkActive(editor, format);

		if (isActive) {
			Editor.removeMark(editor, format);
		} else {
			Editor.addMark(editor, format, true);
		}
	};

	const isMarkActive = (editor: ReactEditor, format: string) => {
		const marks = Editor.marks(editor);
		return marks && format ? marks[format] === true : false;
	};

	const renderElement = useCallback(
		(props: RenderElementProps) => <Element {...props} />,
		[]
	);
	const renderLeaf = useCallback(
		(props: RenderLeafProps) => <Leaf {...props} />,
		[]
	);

	return (
		<Slate
			editor={editor}
			value={state}
			onChange={(value: Node[]) => setState(value)}
			onKeyDown={
// ... which hotkey and toggleMark
                        }
		>
			<Toolbar>
				<MarkButton format='bold' icon='fas fa-bold' />
				<BlockButton format='link' icon='fas fa-link' />
// ...More buttons
			</Toolbar>
			<Editable
				renderElement={renderElement}
				renderLeaf={renderLeaf}
				placeholder={placeholder}
				autoFocus
				spellCheck
			/>
		</Slate>
	);
};
export default TextAreaInput;
```
Although, I think the problem could also be coming from my parent component, where I am setting an initialState like so:
```
const initialNode = [
    {
	type: 'paragraph',
	children: [{ text: '' }],
    },
] as Node[];

// ...

// ... My Post request is here
.then(() => {
    if (user) {
	firebase.incrementForumPosts(user?.uid);
	setError(null);
	setTitle('');
	setContent(initialNode);
        $('#addTopicModal').modal('hide');
}
```

I'm sorry that this is so much code 🔢. I just really don't know where the issue lies!

**Comment by TheSpyder** [comment]
It has to be your submit code. The error shows an editor with the cursor in the second paragraph, but the editor only has one empty paragraph (much like your `initialNode` value).

So wait, is this happening on submit? You're clearing the editor contents?
```
	setContent(initialNode);
        $('#addTopicModal').modal('hide');
```

That would cause this. Judging by the error, at some point after the editor contents are set to empty:
* the page re-renders the toolbar
* `MarkButton` checks `isMarkActive` 
* this calls `Editor.marks(editor)`
* this searches `editor.selection` for leaf nodes
* node `[0,1]` is selected but the content is `initialNode` which does not have a second paragraph

 Set `editor.selection = null` if you are resetting the editor state.

**Comment by calthejuggler** [comment]
@TheSpyder `editor.selection = null` is exactly what I needed! Thank you so much :)
