### ISSUE TITLE
docs.slatejs.org is offline

### ISSUE THREAD

**Issue by roadscape** [ianstormtaylor/slate#377]
https://docs.slatejs.org/reference/models/state.html

```
This site can’t be reached

docs.slatejs.org took too long to respond.
```

----

P.S. Thank you for Slate and its excellent docs!

**Comment by SamyPesse** [comment]
Our US CDN edge had a minor issue and was down 4 hours ago for a small interval of time (EU and Asia were not affected).

It's working fine now.
