### ISSUE TITLE
Rename Master branch to Main

### ISSUE THREAD

**Issue by uipoptart** [ianstormtaylor/slate#3770]
#### Do you want to request a _feature_ or report a _bug_?
Neither?

Github has announced that they will be renaming the primary branch from "Master" to "Main". Opening this for Slate to do the same. This link does a better job that I can of explaining the why:
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

My 2 cents:
It takes a few moments to run the terminal command and change the repository setting. We can what-if over the actual origins or if everyone decides later it doesn’t matter but the time spent over the hand wringing is less than the two terminal commands it would take to just change it and move on. 

The Slack thread:
https://slate-js.slack.com/archives/C1RH7AXSS/p1594073983171300

Thanks!

**Comment by tograd** [comment]
First they came for my master branch, and I said nothing..

**Comment by ianstormtaylor** [comment]
Hey @uipoptart thanks for opening this. I've been busy and hadn't checked any Slate-related notifications for many months, so I totally missed this issue. 

I agree that this is a great change to make. Not only does it eliminate a word that can bring up unnecessary stress for some people, it's also unambiguously clearer in terms of DX for people just getting into coding. I remember being confused as to what "master branch" meant when I first started using Git—"main branch" would have been one less piece of jargon to learn. Fits well with the Slate mindset of not being shy to make breaking changes for even minor improvements in DX.

**Comment by ianstormtaylor** [comment]
I've just run the commands and switched the setting on GitHub, so we should be good to go. Thanks!

**Comment by TheSpyder** [comment]
I appreciate the enthusiasm, but github hasn't yet released their tooling to make this seamless. All open PRs still target `master`. I recommend reversing this until github makes it easy to change by retargeting PRs (and may even offer seamless updates for `git fetch`).
https://github.com/github/renaming/#later-this-year-seamless-move-for-existing-repositories-
