### ISSUE TITLE
Node.normalize creates new `node.nodes` instance

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#378]
`Node.normalize` creates a new `node.nodes` list, even when the values are unchanged: https://github.com/ianstormtaylor/slate/blob/master/src/models/node.js#L1130

More details on this PR. https://github.com/ianstormtaylor/slate/pull/373

**Comment by skogsmaskin** [comment]
I think this is related to the troubles I have here? https://github.com/skogsmaskin/slate-insert-block-on-enter/issues/1

**Comment by ianstormtaylor** [comment]
Shouldn't be an issue anymore in `0.15`!
