### ISSUE TITLE
ordered lists and unordered list in RTL mode

### ISSUE THREAD

**Issue by slivinn** [ianstormtaylor/slate#3788]
When applying lists, in RTL mode, the <li> tags are getting automatically the 'direction':'rtl' but the ul/ol tags dosen't.

![image](https://user-images.githubusercontent.com/31238766/87566424-b117a900-c6cb-11ea-9b0e-59c78ae87861.png)

**Comment by ahmedosama7450** [comment]
@slivinn Why did you close this issue ? Did you find a solution ?
