### ISSUE TITLE
Calling wrapInline on an inline isVoid: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by roadscape** [ianstormtaylor/slate#380]
I'm trying to implement linkable images, but running into this error.

![image](https://cloud.githubusercontent.com/assets/5168676/19327851/fcaa5a5a-909e-11e6-9e95-3ca75849d2c6.png)

To reproduce: https://jsfiddle.net/2c5po0m4/4/

However, if you add text after the image, and then attempt to link the entire line, it works.

i.e. one can `wrapInline` an inline/isVoid node, but not if it's alone.

**Comment by arekkas** [comment]
This is no longer the case in 0.15
