### ISSUE TITLE
Bug when pressing enter and typing in a mark

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#381]
I noticed a weird bug on the Slate rich text example.
### How to reproduce it?
1. Put the cursor in the code at the first lien (`<text[cursor]area>`)
2. Press enter
3. Press `f`

it inserts `farea>` instead of just `f`.
### Video

![2016-10-12 23_48_07](https://cloud.githubusercontent.com/assets/845425/19328941/7f116bbe-90d6-11e6-880b-2f7b27e43042.gif)

**Comment by rafalp** [comment]
Seems like same animal as mine #304

**Comment by ianstormtaylor** [comment]
Fixed in `0.15.0`!
