### ISSUE TITLE
Crash slate when delete mention

### ISSUE THREAD

**Issue by rust96** [ianstormtaylor/slate#3814]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### Information about your OS, browser, Slate version, etc.

Slate: 0.58.4
Browser: Chrome 84.0.4147.105 (Official Build) (64-bit)
OS: macOS Catalina 10.15.5

#### What's the current behavior?

![screencast 2020-08-05 11-25-02](https://user-images.githubusercontent.com/41750125/89390153-01a08600-d70f-11ea-9442-67b2267ba729.gif)
Link to sandobox: [https://codesandbox.io/s/slate-multiple-editors-one-toolbar-zt0qg?file=/src/index.js]()

#### Steps to reproduce:
1. Go to [https://codesandbox.io/s/slate-multiple-editors-one-toolbar-zt0qg?file=/src/index.js]()
2. Click on "TAP TO CLOSE" on first created mention.
3. Click on "TAP TO CLOSE" on second created mention.

#### What's the expected behavior?
Deleting of the mention and no errors in console
#### Actual result:
First mention deleted ok, but when you delete second mention - slate crashed

I use `Transforms.removeNodes(editor, { match: n => n.type === "mention" });` to remove the mention. I also tried to find path from `ReactEditor.findPath` by function and the use it  just like this `Transforms.removeNodes(editor, { at: path });`, but no changes.

**Comment by markogresak** [comment]
This is not a bug with Slate, but it's a gotcha with the `onClick` handler.

The `onClick` event will trigger the `close` function, but it will also propagate to Slate, which will try to select the node
https://github.com/ianstormtaylor/slate/blob/1cf63f0a19a45c3b35ea3f8682e57a28cacfb4d1/packages/slate-react/src/components/editable.tsx#L582
But the `close` code just removed the node at that location, so Slate will fail.

A solution to this is to stop the `onClick` event propagation in the `close` function:
```diff
- const close = () => {
+ const close = (event) => {
+  event.stopPropagation();
   Transforms.removeNodes(editor, { match: n => n.type === "mention" });
 };
```

**Comment by rust96** [comment]
Yeah, u r right! Thank you so much for your help!
