### ISSUE TITLE
Support React as AMD module

### ISSUE THREAD

**Issue by nazar-pc** [ianstormtaylor/slate#382]
I'm wondering why `window.React` is used in NPM package instead of consuming it (at least, as fallback) as AMD module?

I'm not using React otherwise and I don't really want to mess around with it, just want to consume everything like usual AMD dependencies.

Looks like Slate is currently enforcing build system and/or the whole React ecosystem on those who want to use it as one of many tools on the projects.

Is this something that can be supported?

**Comment by nazar-pc** [comment]
And `slate` itself I guess too, otherwise I'm getting:
```
Uncaught ReferenceError: exports is not defined
```

**Comment by SamyPesse** [comment]
Are you importing the `dist/slate.js` or `lib/index.js` ?

**Comment by nazar-pc** [comment]
`dist/slate.min.js`.
`lib` is all CommonJS which is not browser-compatible (at least if you don't have a bunch of stuff for build process, which I don't want to add just for this library).

**Comment by ianstormtaylor** [comment]
Hey @nazar-pc, I'm not sure exactly what you're asking for. 

There's a bundled version in `dist/slate.js`, which has all of Slate packaged up (except for React which you need to bring yourself). And then there's the default method of requiring it like a regular node module. For now those are the only two supported out-of-the-box ways to use Slate. If you'd like to use it in a different way, you're free to clone and build from the source yourself, but I can't support a bunch of other build outputs right now I think.

**Comment by nazar-pc** [comment]
I thought Slate is designed to run in browser. If this is correct, then why the default way of loading it is like regular node module? It simply doesn't work in browser, there is AMD designed for browsers. Not supporting it out-of-the-box (especially considering that UMD is trivial to implement) and forcing people to manually include React on the page doesn't make any sense to me. It simply doesn't work in browser and forcing people to use certain build tools, which is even worse.

I hope to see UMD build where React is loaded as dependency rather than from global scope.
