### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by machineghost** [ianstormtaylor/slate#3830]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

The page https://docs.slatejs.org/walkthroughs/xx-using-the-bundled-source has a link ("Installing Slate") to: https://github.com/ianstormtaylor/slate/tree/f6bfe034d707693488c38da77537fd36cb8856cf/docs/walkthroughs/installing-slate.md

... but that's a 404 page.

#### What's the expected behavior?

One would expect a page to be at that link (Ie. one would expect a valid link).

**Comment by CameronAckermanSEL** [comment]
Thanks for the report! This seems to be fixed now

**Comment by machineghost** [comment]
NP.  Also, apologies for offending you in that other thread.  I just work with new JS learners, so I know for a fact that many of them don't understand TS and do try using libraries like Slate.  I was trying to advocate *not* for you to avoid TS, but just to understand that, and try and be transparent to help such "juniors". 

But again, I truly didn't mean to offend, and I apologize if my "advocacy" for them came across as an attack.
