### ISSUE TITLE
Bug: In Firefox bold mark don't work properly after double click on a word

### ISSUE THREAD

**Issue by grabowskimr** [ianstormtaylor/slate#3840]
#### What's the current behavior?
In Firefox, there is a bug with the selector. 

Steps to reproduce: 
1) Select a word and mark it as bold.
2) Click somewhere in the editor to remove the selector from the word.
3) Double click on the bolded word to select it again.

After these steps bold mark isn't detected and a user isn't able to remove bold from the selected word.

![bug](https://user-images.githubusercontent.com/30661564/91293362-2f21a200-e798-11ea-97a1-168d1af9374f.gif)

Slate: 0.58.4
Browser: Firefox
OS: Mac

#### What's the expected behavior?

After double click on a word user should be able to remove the bold mark.

**Comment by Yidaotus** [comment]
Additionally you get all kinds of weird behaviour when double clicking in firefox. This makes it pretty much unusable right now.

![slate](https://user-images.githubusercontent.com/2761350/94573288-3a259180-0272-11eb-9a34-91bec6e02cbe.gif)

Slate: v0.59.0 
Browser: Firefox 81.0 (64-Bit)
OS: Windows 10
