### ISSUE TITLE
Docs: misleading label/link in the Contributing guide for issues needing help

### ISSUE THREAD

**Issue by udayanshevade** [ianstormtaylor/slate#3865]
#### Do you want to request a _feature_ or report a _bug_?
Typo / misleading link in the docs

#### What's the current behavior?
The current link filters issues by the label `♥ help please` which shows zero results. 

#### What's the expected behavior?
Need to filter by the correct label of `♥ help` instead.

Small fix in a PR here: #3860

**Comment by BrentFarese** [comment]
Fixed in #3860.
