### ISSUE TITLE
Inverted cursor movements in RTL texts

### ISSUE THREAD

**Issue by going-confetti** [ianstormtaylor/slate#3879]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
In an RTL text, the cursor movements are inverted. Surprisingly, selection with holding `shift` + arrow keys seem to work properly.

![RTL](https://user-images.githubusercontent.com/3773351/93476877-94c9ff80-f8fa-11ea-99ea-ad2f27761ac7.gif)

Steps to reproduce
1. Insert some RTL text into Slate - for example, `البطاطس` (Potato in Arabic).
1. Put the cursor in the middle of the text string.
1. Press the **right** arrow key - the cursor will move **left**.
1. Press the **left** arrow key - the cursor will move **right**.
1. Check the `option` + arrow keys shortcut (`ctrl` + arrow keys on Windows) - it's also inverted.

You can try it out here: https://codesandbox.io/s/slate-reproductions-forked-wm4qt 

Slate: 0.58.4
Browser: Chrome 85.0.4183.102 / Safari 13.1 / Firefox 79.0 (64-bit)
OS: Mac

#### What's the expected behavior?

Similarly to how selection with `shift` currently works – using the right arrow key should move the cursor to the right, using the left arrow key should move it to the left. (When there's an LTR word)
I checked the behavior of a few web and desktop editors. Google Docs, Draft.js, Quill, native `<textarea>`, Pages on Mac, and TextEdit on Mac work as expected, while ProseMirror doesn't seem to support RTL at all.

#### Possible solution
The fix proposed by @SophiaSaiada in https://github.com/ianstormtaylor/slate/pull/3727 seems to be working really well.

**Comment by Navid61** [comment]
I did check by demo version it worked without any problem, However I don't know what version it is
![slate](https://user-images.githubusercontent.com/4729469/108824840-723dc000-75d7-11eb-8b09-4043011d8c77.png)
it seems this issue fixed
