### ISSUE TITLE
Focusing issue when there are multiple editors and state is managed by a parent component

### ISSUE THREAD

**Issue by jasonmng** [ianstormtaylor/slate#3880]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When there are multiple editors and state is managed by a parent component, it takes two clicks to focus on the second editor

https://codesandbox.io/s/slate-reproductions-forked-py658?file=/Container.tsx

Slate: 0.58.4
Browser: Chrome / Safari / Firefox /
OS: Mac

#### What's the expected behavior?

The second editor is focused on the first click

**Comment by hack0001** [comment]
Did you manage to resolve this as I have this issue also

**Comment by JanJakes** [comment]
Same problem on 0.60.1.

**Comment by vpontis** [comment]
Can you try doing `_.deepClone(value)` for the other editors? 

The way that Slate handles node referencing, there will be issues if the same node is rendered twice.

**Comment by JanJakes** [comment]
Actually, I found the problem – in my case it was related to https://github.com/ianstormtaylor/slate/issues/3696, specifically a multi render issue described in https://github.com/ianstormtaylor/slate/issues/3696#issuecomment-723497830. Similar problem described also in https://github.com/ianstormtaylor/slate/issues/3634, specifically https://github.com/ianstormtaylor/slate/issues/3634#issuecomment-723498466.

There are many possibilities how one can cause redundant renders, in my case it was due to state managed from higher above in the tree plus some inline callbacks. Solved with proper `useCallback` & `useMemo` usages plus wrapped my editor component with `React.memo()`.

**Comment by justspamjustin** [comment]
Is there a solution to this issue? I'm seeing the same thing in version 0.63.0.

**Comment by justspamjustin** [comment]
> Actually, I found the problem – in my case it was related to #3696, specifically a multi-render issue described in [#3696 (comment)](https://github.com/ianstormtaylor/slate/issues/3696#issuecomment-723497830). Similar problem is described also in #3634, specifically [#3634 (comment)](https://github.com/ianstormtaylor/slate/issues/3634#issuecomment-723498466).
> 
> There are many ways one can cause redundant renders, in my case it was due to state managed from higher above in the tree plus some inlined callbacks. Solved with proper `useCallback` & `useMemo` usages plus wrapped my editor component with `React.memo()`.

Yes I was able to do a deep compare to ensure I don't update state when there isn't a real change. Here's a link to my fix for the original poster's codesandbox: https://codesandbox.io/s/slate-reproductions-forked-d7tyf

**Comment by jasonmng** [comment]
> Actually, I found the problem – in my case it was related to #3696, specifically a multi-render issue described in [#3696 (comment)](https://github.com/ianstormtaylor/slate/issues/3696#issuecomment-723497830). Similar problem is described also in #3634, specifically [#3634 (comment)](https://github.com/ianstormtaylor/slate/issues/3634#issuecomment-723498466).
> 
> There are many ways one can cause redundant renders, in my case it was due to state managed from higher above in the tree plus some inlined callbacks. Solved with proper `useCallback` & `useMemo` usages plus wrapped my editor component with `React.memo()`.

likewise, The issue I was seeing was solved by changing the Component to a PureComponent
