### ISSUE TITLE
Runtime change of editor causes a crash

### ISSUE THREAD

**Issue by MCMrARM** [ianstormtaylor/slate#3886]
#### Do you want to request a _feature_ or report a _bug_?

I am reporting a bug.

#### What's the current behavior?

https://codesandbox.io/s/slate-reproductions-forked-er268?file=/index.tsx

To reproduce the issue click on Add Editor twice. The first editor is recreated when clicking on the button.
Slate: 0.58.0
Browser: This issue is not browser specific and is reproducible at least in Chromium Version 85.0.4183.102 (Official Build) Arch Linux (64-bit) and Firefox 80.0.1 (64-bit) for Arch Linux.
OS: Arch Linux

#### What's the expected behavior?

I expect changing the editor to work and not crash the app since React docs explicitly mention at https://reactjs.org/docs/hooks-reference.html#usememo that applications should work even if the memoized var is cleared:
> **You may rely on useMemo as a performance optimization, not as a semantic guarantee.** In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

The issue seems to be caused by not including [editor] as a dependency in plenty of places.

**Comment by Enva2712** [comment]
The editor object stores the editor state, and needs to be persisted for the editor's lifetime. `useMemo` doesn't guarantee that it's value will be persisted, and the slate docs should probably be updated to use a different hook.
Here's a fork of your codesandbox that uses `useRef` and a lazy initializor to store the editor object for the entire editor lifetime: https://codesandbox.io/s/slate-reproductions-forked-1m9cv?file=/index.tsx

The react docs go into more depth on persisting values using hooks: https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily

@ianstormtaylor I can open a PR to update the docs if you want. Below are alternatives to `useMemo` that will persist the editor object without dropping it:
```tsx
// Using useState
const [editor] = useState(() => withReact(createEditor()));

// Using useRef with an initializor function
const editor = useRef<ReactEditor | null>(null);
const getEditor = useCallback((): ReactEditor => {
    if(editor.current === null) editor.current = withReact(createEditor());
    return editor.current;
}, [])
```

Side node: the same bug occurs when using NextJS fast refresh.

**Comment by Enva2712** [comment]
Another alternative is to write a `useEditor` hook that takes an editor creator function and does the above for you like so:

```tsx
function useEditor<T extends Editor>(createEditor: () => T): T {
    const editor = useRef<T | null>(null);
    if(editor.current === null)
        editor.current = createEditor()
    return editor.current
}

function MySlateEditor() {
    const editor = useEditor(() => withReact(createEditor()))

    return <Slate editor={editor}>
        ...
    </Slate>
}
```

**Comment by jaked** [comment]
I don't quite understand the original repro sandbox, but here is a simpler one that illustrates the issue:

https://codesandbox.io/s/slate-reproductions-1wwuj?file=/index.tsx

As @MCMrARM points out,

> The issue seems to be caused by not including [editor] as a dependency in plenty of places."

There are a bunch of memoized handlers in the `Slate` and `Editable` components that close over `editor` but don't list `editor` in the memo keys, so if you pass a different editor to the same component instances many things break.

You can work around it by forcing the components to remount (explicitly setting a `key` property on the `Slate` component that changes when the editor changes). But it seems like Slate should properly handle a change of editor, right?
