### ISSUE TITLE
Request: Documentation should have a user option to display either TypeScript or JavaScript

### ISSUE THREAD

**Issue by timbuckley** [ianstormtaylor/slate#3895]
#### Do you want to request a _feature_ or report a _bug_?

Request

#### What's the current behavior?

Currently there is no way to toggle between JS and TS examples on the documentation ([example](https://docs.slatejs.org/concepts/01-interfaces)), it only shows TS examples.

#### What's the expected behavior?

User should see a toggle above each example (or at the top of all pages) to see a TS or JS version of example usage.

**Comment by Walsker** [comment]
I'd like to tackle this, however I'd like to clarify something. Some snippets only include things like [interfaces](https://docs.slatejs.org/concepts/06-editor) or [types](https://docs.slatejs.org/concepts/03-locations#path), which don't directly translate back to JS. How should that be represented when toggled to JS, or should that not be an option for these kinds of snippets?

**Comment by thesunny** [comment]
@Walsker @timbuckley I wonder if the right approach is to use the TypeScript to generate the JavaScript. I don't know if the JavaScript will appear natural, but I feel like it's worth a try. Then we don't have to keep two separate code bases (one in TS and one in JS) in sync.

With respect to `interface`s and `type`s, I don't think those have a JS equivalent anyways so they should be ignored.

**Comment by RavenColEvol** [comment]
@thesunny @ianstormtaylor is it still a good first issue? I would like to hop in and take this issue.

**Comment by thesunny** [comment]
@RavenColEvol feels like a good first issue to me!

Since it affects documentation and not Slate itself, it is simultaneously easy to confirm that it works (does the code look right) and also shouldn't introduce any issues into Slate.
