### ISSUE TITLE
TODO: Convert all remaining JavaScript files to TypeScript

### ISSUE THREAD

**Issue by timbuckley** [ianstormtaylor/slate#3896]
#### Do you want to request a _feature_ or report a _bug_?

Request

#### What's the current behavior?

Currently 1.9% of the codebase is written in JavaScript, with almost all of the rest in TypeScript.

#### What's the expected behavior?

We'd like to transform as much of the remaining project to TypeScript as possible. Mainly this will involve transforming the `slate-hyperscript` tests.

**Comment by vanya829** [comment]
Hi. I'd like to work on this issue and convert `slate-hyperscript` tests to typescript. May I?
