### ISSUE TITLE
Error: Cannot resolve a Slate point from DOM point

### ISSUE THREAD

**Issue by shhlkien** [ianstormtaylor/slate#3903]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### Reproduce

![Screencast-2020-10-06-173928](https://user-images.githubusercontent.com/23404165/95191619-2f7f7500-07fb-11eb-9c05-d96eb5b3f32f.gif)

See sandbox: https://codesandbox.io/s/youthful-boyd-z3l36

#### What's the current behavior?
Tested on Firefox and Chrome, the error only appears in Firefox
From getting started guide, I set up as the docs. 
When typed something, some characters of the text was missing
When pressed `enter` or `backspace`, nothing happened
The browser console logged this: 
```
Error: Cannot resolve a Slate point from DOM point
...
```

Slate: 0.59.0
Browser: Firefox 80
OS: Ubuntu 20.04

#### What's the expected behavior?
Works as Chrome

**Comment by karlshea** [comment]
I'm running into this too—this isn't a great entry into this project. I'd like to replace react-quill with Slate and the most simple example from the installation guide immediately crashes.

**Comment by karlshea** [comment]
I think I figured this out: `SlateDocument` **cannot** be empty.

If I initialize it with this it works:

```
[
  {
    children: [
      {
        type: 'paragraph',
        children: [{ text: '' }],
      },
    ],
  },
]
```

**Comment by shhlkien** [comment]
It's because of `onBeforeInput` event is not implemented (see https://github.com/preactjs/preact/issues/1422). I haven't found any solution for this

**Comment by BrentFarese** [comment]
I cannot reproduce this and am not sure there is any bug.  Can you provide a minimal reproduction?  As mentioned, make sure the Slate value is set.  Thanks.

**Comment by shhlkien** [comment]
> I cannot reproduce this and am not sure there is any bug. Can you provide a minimal reproduction? As mentioned, make sure the Slate value is set. Thanks.

I did provide a code sandbox. The last time I tested on Firefox 86, Chrome 85 and Edge Chromium 90, it worked on Firefox and Chrome. I also checked your examples, they worked all, that very weird!
This is a browser problem, as I said in the previous comment (and it also has one [issue](https://github.com/ianstormtaylor/slate/issues/2060) here). So far I haven't found any polyfill of `onBeforeInput` event to support old browser versions

**Comment by BrentFarese** [comment]
Thank you. Yes I tried the code sandbox and couldn't reproduce any error.  It seemed to work just fine.  Will close for now but glad to re-open if you can provide a minimal reproduction.

**Comment by karlshea** [comment]
In the provided sandbox if I change the value hook to

```
const [value, setValue] = useState([]);
```

And click into where the editor is, I get the exception in Chrome 88.

**Comment by souljuse** [comment]
I have the same issue, and I can reproduce on @karlshea's sandbox

It happens randomly when I type a special character, or a list of special characters, both on Firefox 90.0 (64-bit) and Chrome Version 91.0.4472.164 (Official Build) (x86_64)

![2021-07-27 16 43 47](https://user-images.githubusercontent.com/13051823/127175280-553f470a-19ae-47b5-9fff-934f6761dd4f.gif)
