### ISSUE TITLE
Chinese text being doubled (duplicated inserted into the wrong node)

### ISSUE THREAD

**Issue by gt2345** [ianstormtaylor/slate#3914]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?

Slate: 0.50.0
Browser: Chrome
OS: Mac

![Screen Shot 2020-10-09 at 4 34 28 PM](https://user-images.githubusercontent.com/40620519/95561783-d5c2b900-0a4d-11eb-8d2b-e1412256e804.png)

When typing in Chinese for the second time (if the editor has just rendered and not been touched, this won't happen. It only happens when I type in something and clear it), text somehow got inserted into both < p data-slate-node="element"> and < span data-slate-string="true"> nodes, which results in text being doubled on screen. At this time, if I press enter to switch to the next line, then everything comes back to normal.
P.S. I already change some code in toSlatePoint function to normally render at this situation, otherwise is will through an error.
Could anyone provide some work around to eliminate text being inserted into < p data-slate-node="element">, or auto trigger pressing enter?

#### What's the expected behavior?
Text should only appear in < span data-slate-string="true">, but not in < p data-slate-node="element">

**Comment by ls19930101** [comment]
不要使用placeholder,单独自己维护一个placeholder可以规避slate对中文输入法的不支持.

**Comment by emmkong** [comment]
@ls19930101 你有具体的实现方式吗？你怎样替代原有的placeholder？

**Comment by Q-Qplus1s** [comment]
same problem
![](https://content.markdowner.net/pub/dGN5q0-EM5eB83)

repeat render when input chinese directly after the decorated text

**Comment by Q-Qplus1s** [comment]
@emmkong 即使不用 placeholder 问题同样存在

**Comment by Xheldon** [comment]
你可能需要在 Editable 中的 compositionStart 中和 End 中做一些处理
