### ISSUE TITLE
scroll to caret  Incorrect

### ISSUE THREAD

**Issue by usecodelee** [ianstormtaylor/slate#3920]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
![我的影片](https://user-images.githubusercontent.com/32923083/102490184-73b7ad00-40a9-11eb-97e4-9768f829661a.gif)

![image](https://user-images.githubusercontent.com/32923083/102489585-a4e3ad80-40a8-11eb-9cb7-c16f0d2380f5.png)

When I type, the scroll bar scrolls to the middle

Slate: 0.59.0
Browser: Chrome
OS: Windows/MacOS

#### What's the expected behavior?

When I type, the scroll bar will not scroll to the middle

By reading the source code, I located the reason：
![image](https://user-images.githubusercontent.com/32923083/102490051-4bc84980-40a9-11eb-8612-3e5699ef7493.png)

The content in the red box caused this defect

**Comment by IsaacMSchultz** [comment]
It looks like this was fixed as part of #3866. I tried replicating the issue and it seems to focus correctly for me. The code you have highlighted in the red box is no longer there in the current codebase, and was replaced in #3866.

**Comment by usecodelee** [comment]
> current

thanks

**Comment by usecodelee** [comment]
@IsaacMSchultz 
I updated the issue

**Comment by dylans** [comment]
Fixed in #4037
