### ISSUE TITLE
Issue when editor loses focus before transform

### ISSUE THREAD

**Issue by roadscape** [ianstormtaylor/slate#395]
https://jsfiddle.net/esoxramp/2/

The `alert()` line in the click handler before the transform introduces buggy behavior. 

Comment it out to see how this case is expected to function.

Calling `this.refs.editor.focus()` after the alert does not fix it.

---

Trying to type 'abcde' after image insert:
![image](https://cloud.githubusercontent.com/assets/5168676/19529919/c8331558-95ff-11e6-8514-88d5948184c8.png)

---

After commenting out the `alert()` line:
![image](https://cloud.githubusercontent.com/assets/5168676/19529996/029a7c40-9600-11e6-993e-f842b6796ee3.png)

**Comment by arekkas** [comment]
I think this will be resolved with #418

**Comment by arekkas** [comment]
This now works in chrome but not in firefox. However, in both browsers, the command line shows the following error: `Uncaught TypeError: Cannot read property 'map' of null`, which is triggered by `onEvent`.

**Comment by arekkas** [comment]
@roadscape in general it's a good idea to wrap `onChange` in a `setTimeout` if you perform things like window.alert - this will ensure that the onChange is triggered after the activeElement updated.

**Comment by ianstormtaylor** [comment]
Closing since it sounds like @arekkas's solution is the way to go. If you run into more problems feel free to re-open or open a new issue
