### ISSUE TITLE
useEditor no Longer Exported from Package

### ISSUE THREAD

**Issue by mwood23** [ianstormtaylor/slate#3960]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

The use editor hook is no longer exported from `slate-react`. It happened in this PR https://github.com/ianstormtaylor/slate/pull/3941 and based on the conversation it sounds like the intended functionality was to add a duplicate hook with a more semantic name while keeping the old hook in there.

#### What's the expected behavior?

Based on the PR, both `useEditor` and `useSlateStatic` are exported from the package.

**Comment by timbuckley** [comment]
Good catch, thanks for noticing this!
