### ISSUE TITLE
Nested slate editor

### ISSUE THREAD

**Issue by ggunia** [ianstormtaylor/slate#3962]
#### Do you want to request a _feature_ or report a _bug_?
Feature request

#### What's the current behavior?
Can not nest slate editors.

Slate: 0.59.0
Browser: Chrome / Safari / Firefox / Edge
OS: Mac

#### What's the expected behavior?
It would be great to have ability to nest slate editor inside of another slate editor

**Comment by CameronAckermanSEL** [comment]
There's an example that showcases this functionality. Please see the embeds example.

In general though because slate can handle nested structures, it's not really recommended that you do this. It's generally avoidable
