### ISSUE TITLE
Traversing children in renderElement

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#3966]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Children is always single component, not collection.

Slate: 0.59.0

#### What's the expected behavior?

It would be nice to be able to traverse children provided in `renderElement` functions (with [React.Children](https://reactjs.org/docs/react-api.html#reactchildren)).

That way you can for example visually group/separate elements without actually changing document structure.

**Comment by Mangatt** [comment]
Alternatively, there could be `renderChildren` prop that would be used in `Children.jsx`, although traversing children directly with React is more by-the-book approach.

**Comment by Mangatt** [comment]
Any thoughts on this? This could greatly simplify creating plugins that need enforced structure like lists or tables.

**Comment by ianstormtaylor** [comment]
This would require someone researching whether it's possible. `React.Children` isn't an abstraction that always works.

My guess is that this won't really be possible since Slate expects a specific structure to the children, so allowing that structure to be dynamically changed wouldn't work. For lists/tables the structure would likely need to be enforced in a schema instead.

**Comment by Mangatt** [comment]
I'm aware of that, but React Components can have any internal HTML structure and Slate still works. This makes me believe that it should be possible, but I don't know Slate internals that well.

> If children is a Fragment it will be treated as a single child and not traversed.

Theoretically it should be matter just of changing `<React.Fragment />` into simple `array`. Good thing is it isn't event a breaking change.

**Comment by Mangatt** [comment]
Ok, I've just tested this and Slate appears to be just fine with structure changes on the fly.

Little bit problematic is rather fact that rendered children can't be encapsuled in `Children` component, but have to be rendered one by one in parent, otherwise React sees just single `Children` component while traversing with `React.Children.map`.

Simple solution would be to change `Children` component into plain function `getChildren` or hook `useChildren` that would return array with children to parent component. It does not change anything nor it is breaking change since `Children` is not public endpoint.

If maintainers are ok with this, I can push PR.

**Comment by ianstormtaylor** [comment]
@Mangatt nice, a `useChildren` hook sounds like a good way to do it. A PR would be great.

Can you explain the structure you'd like to impose by iterating children, or provide any pseudo-code snippets of the kind of functionality you're trying to achieve? (Often helps in PRs for people to understand what you're asking for.)

**Comment by Mangatt** [comment]
Great, I'll do that next week.

Nested lists are good example, as managing proper structure is immense amount of work and results are still not bulletproof. With this change you can have just flat `list-item` type with depth prop and render proper structure on the fly.

After this change you can produce from following structure:

```js
{
	type: 'list',
	children: [
		{type: 'list-item', children:['Item 1']},
		{type: 'list-item', children:['Item 1.1'], depth: 1},
		{type: 'list-item', children:['Item 2']},
	]
}
```
this HTML:

```html
<ul>
	<li>
		<div>Item 1</div>
		<ul>
			<li>Item 1.1</li>
		</ul>
	</li>
	<li>Item 2</li>
</ul>
```
