### ISSUE TITLE
Proposal - path parameter in match function

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#3967]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Match function gets just `node` as parameter.

```js
const match = (node) => boolean
```

Slate: 0.59.0

#### What's the expected behavior?

Since location of node actually matters, it would be helpful to have that information available in match function like this:

```js
const match = (node, path) => boolean
```

It is minor non-breaking change that grealy simplifies code dependent on location.

**Comment by BrentFarese** [comment]
Agree this could be a good improvement.  Do you want to draft a PR?  Thanks!

**Comment by reinvanimschoot** [comment]
Is there any update on this? I am looking for ways to get a reference to the node parent when matching but it seems every function requires a reference to the path.

**Comment by BrentFarese** [comment]
> Is there any update on this? I am looking for ways to get a reference to the node parent when matching but it seems every function requires a reference to the path.

Someone needs to submit a PR.  If you want to take a crack, it could get considered and possibly merged way faster.

**Comment by reinvanimschoot** [comment]
@BrentFarese But there is an open PR? https://github.com/ianstormtaylor/slate/pull/3968

**Comment by BrentFarese** [comment]
> @BrentFarese But there is an open PR? #3968

Should have looked at the linked PRs to this issue!  Thanks.  I think there are shortcomings to that PR that need to be fixed (see my comment), but otherwise I would be glad to take a look and merge if the comments are addressed.
