### ISSUE TITLE
Upgrade Immer

### ISSUE THREAD

**Issue by TheSpyder** [ianstormtaylor/slate#3969]
As I write this Slate still depends on [immer version 5](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/package.json#L19), last released 9 months ago, the library is now up to version 7. There are [quite a lot of changes](https://openbase.io/js/immer/versions).

From my initial testing v7 is a drop-in replacement that provides significant code size benefits:

Before:
```
322196 plugin.min.js
 91081 plugin.min.js.gz
```
After:
```
307494 plugin.min.js
 87064 plugin.min.js.gz
```

And this is just my initial debug build without full optimisation enabled.

**Comment by macrozone** [comment]
this would also help to reduce the bundle size for https://github.com/react-page/react-page !

**Comment by gitcatrat** [comment]
@thesunny Closed by https://github.com/ianstormtaylor/slate/pull/3850?

**Comment by thesunny** [comment]
@gitcatrat Thanks. Closing!
