### ISSUE TITLE
Feature request: Work with ids in slate like DOM concept

### ISSUE THREAD

**Issue by masihjahangiri** [ianstormtaylor/slate#3983]
# Feature request: Work with ids in slate like DOM concept

Slate.js is great to create a full custom editor. To improve working with slate API I think is better to add some method to work with node id. for example I need to have a method to remove a node by id. Or get it by id.
What is the best approach to implement a button in a node to delete It?

Slate: 0.59
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

**Comment by BrentFarese** [comment]
This question is best left for Slate's Slack channel.  Thanks!
