### ISSUE TITLE
Duplicate default branches - Main vs. Master

### ISSUE THREAD

**Issue by BrentFarese** [ianstormtaylor/slate#3996]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Currently, we have 2 default branches, Master and Main after merging #3770.  We need to:

1. Retire the Master branch.
2. Make all existing PRs point to Main.
3. Anything else?

Slate: 0.60.0
Browser: Chrome
OS: Mac

#### What's the expected behavior?

See above we need to retire Master and change all existing work to point to Main.

**Comment by thesunny** [comment]
Based on the conversations on our Slack channel, just updating this issue to reflect that for the time being, we will be changing the default branch from `main` back to `master`. This won't happen immediately as we will first fix an issue on the `main` branch.

The description of the solution can be found on this issue: #4003

**Comment by BrentFarese** [comment]
Closing as mentioned in #4003.  Will make `main` default when GitHub supports it better/easier.
