### ISSUE TITLE
Cursor move unexpectedly when two editor have the same value.

### ISSUE THREAD

**Issue by walkdoer** [ianstormtaylor/slate#3997]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

I have two editor that come from the same value, and when I move the cursor, the cursor will jump to another editor. As you may see in the gif record. And after dig into the code. I found that it's because the WeakMap `KEY_TO_ELEMENT` , `NODE_TO_ELEMENT`, `ELEMENT_TO_NODE` were share between the editors. So the DOM of the element will be overwrite d if they have the same value. 

```
Slate: 0.59.0
Browser : Electron V9.x
OS:  Mac
```

**Real word screen record**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/543407/100307043-cee10d00-2fdf-11eb-9928-2bae5396fc5d.gif)

**Sandbox:** [https://jsfiddle.net/g1q2phzm/](https://jsfiddle.net/g1q2phzm/)

And Here is the code I found that might related to this issue. 

```js
const key = ReactEditor.findKey(editor, element)

// Update element-related weak maps with the DOM element ref.
  useIsomorphicLayoutEffect(() => {
    if (ref.current) {
      KEY_TO_ELEMENT.set(key, ref.current)
      NODE_TO_ELEMENT.set(element, ref.current)
      ELEMENT_TO_NODE.set(ref.current, element)
    } else {
      KEY_TO_ELEMENT.delete(key)
      NODE_TO_ELEMENT.delete(element)
    }
  })

// react-editor.ts

findKey(editor: ReactEditor, node: Node): Key {

    let key = NODE_TO_KEY.get(node)

    if (!key) {

      key = new Key()

      NODE_TO_KEY.set(node, key)

    }
    return key
  }

```

#### What's the expected behavior?

I think although the two editor came from the same value in memory, but the cursor ought to move independently.

#### Thanks
Slate is awesome! Thank you for your work!

**Comment by bryanph** [comment]
I'm running into the same problem, a solution might be to keep the weak-maps state in the editor object instead of in a global map (in slate-react).

**Comment by BrentFarese** [comment]
What is the use case for having the same in-memory value be used in 2 different `editor` instances?  Am I reading that correctly?  That does not strike me as a proper thing to do.

**Comment by bryanph** [comment]
I'm working on an app where you can embed part of a document in another document and the documents can be shown side-by-side. I use Node.fragment() to get a sub-section of a document and display it in another component. That's the context In which this bug was appearing for me. So yes some nodes share a memory location which causes conflicts in the weak map.

**Comment by walkdoer** [comment]
> What is the use case for having the same in-memory value be used in 2 different `editor` instances? Am I reading that correctly? That does not strike me as a proper thing to do.

Hi @BrentFarese , In my use case,  while user editing in the editor,  Sometime they  want to split the editor into two separate editor, For example, like cross reference. It's like when you are using VS Code, the same file can split into two editor,  and whenever change the content in one of these editors, the content should all synced.  but when using slate,  although the content will be sync, because it came from the same memory value,  but the cursor can not move independently, in the issue I reported above, the cursor will  jump to another editor. You can check it out in this [demo]( https://jsfiddle.net/4zxr5q1h/7/).

**Comment by bryanph** [comment]
@walkdoer See https://slate-js.slack.com/archives/CC58ZGGU9/p1612453448053300.

> Thinking about it again I might be able to solve this problem differently by deep cloning the fragment on initial render and then keep it up-to-date by applying operations to this editor instead of keeping it up-to-date with a shared value object.

**Comment by skogsmaskin** [comment]
This is also being discussed in https://github.com/ianstormtaylor/slate/issues/3380

Closing this one.

**Comment by bryanph** [comment]
I think this is not quite fixed yet as there is also an `ELEMENT_TO_NODE` mapping used here: https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/plugin/react-editor.ts#L381-L395

It still reuses the same mapping for both editors, causing errors.
