### ISSUE TITLE
When using `Command-A` to select all text, and use IME to input and replace the text, the editor break.

### ISSUE THREAD

**Issue by BiosSun** [ianstormtaylor/slate#4008]
#### What's the current behavior?

This problem only occurs when there are multiple paragraphs:

![CleanShot 2020-12-04 at 18 13 58](https://user-images.githubusercontent.com/2755933/101151386-8a4b1680-365c-11eb-9c04-71dd08b779de.gif)

```
Unhandled Runtime Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

Slate: 0.60.0
Browser: Chrome 86.0
OS: Mac OS Big Sur 11.0.1

**Comment by Q-Qplus1s** [comment]
[#3342](https://github.com/ianstormtaylor/slate/pull/3342)

**Comment by BiosSun** [comment]
repeated issue
