### ISSUE TITLE
setNodes not work with nested properties （children）

### ISSUE THREAD

**Issue by Q-Qplus1s** [ianstormtaylor/slate#4020]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?
```javascript
        Transforms.setNodes(editor, {
          type: T.CODE_FENCE, tag: 'code', markup: '```',
          info: (split[1] || '').trim(),
          children: [{ text: '', type: T.CODE_TEXT }]
        }, { at: path });
```

Slate: 0.59.0
Browser: Chrome
OS:  Linux

#### What's the expected behavior?
update nested properties 

#### current solution:

```javascript
        Transforms.setNodes(editor, {
          type: T.CODE_FENCE, tag: 'code', markup: '```',
          info: (split[1] || '').trim(),
          children: [{ text: '', type: T.CODE_TEXT }]
        }, { at: path });
        // fixed 
        Transforms.setNodes(
          editor,
          { text: '', type: T.CODE_TEXT },
          { at: path.concat(0) }
        );
```

**Comment by ianstormtaylor** [comment]
I understand your use case, but this isn't a bug, this is by design. Setting only acts on a single node, not any of its children—this is an important quality for making OT-style collaboration viable.

**Comment by josoroma** [comment]
@ianstormtaylor Yeah, so what process would you suggest to add new properties to a fragment with children:

![image](https://user-images.githubusercontent.com/69951/119066310-bce39400-b99c-11eb-83f3-d21d5f27438e.png)

I meant, I am trying to find a way to add the bold attribute to any selected/fragment children with text:

![image](https://user-images.githubusercontent.com/69951/119066369-e00e4380-b99c-11eb-9de4-c5a20373a0cd.png)

**Comment by fedorin-git** [comment]
> I understand your use case, but this isn't a bug, this is by design. Setting only acts on a single node, not any of its children—this is an important quality for making OT-style collaboration viable.

Hi. So no way to replace `children[0].text` when Editor is loaded?
My initial value is
```
[
  {
    "type": "paragraph",
    "children": [
      {
        "type": "company",
        "children": [
          {
            "text": "My Company"
          }
        ]
      }
    ]
  }
]
```

Each time when the Editor is loaded, I want to replace initial value of 'My Company' with the current value (e.g 'My Updated Company').

**Comment by tomaszferens** [comment]
> Each time when the Editor is loaded, I want to replace initial value of 'My Company' with the current value (e.g 'My Updated Company').

Have you figured out how to do it? @fedorin-git
