### ISSUE TITLE
Select all + delete does not work when an image is at the bottom of the document

### ISSUE THREAD

**Issue by vpontis** [ianstormtaylor/slate#4021]
#### What's the current behavior?

If an image element is at the end of the document, then selecting the whole document and hitting backspace will not delete everything. 

Here is a video showing the current behavior: https://www.loom.com/share/e7c9cc4f5da8405ba673fdbf09a03b7c

I have tested this on MacOS on Chrome and Safari.

You can reproduce this by getting the images example such that there are two paragraphs below the image and no text below the image. If you then try to cmd+A and delete everything, the image will not be deleted. 

![image](https://user-images.githubusercontent.com/1319079/102040349-72bd0d80-3d81-11eb-844b-d37d3f2671e4.png)

Slate: 0.59
Browser: Chrome / Safari 
OS: Mac

When I have time, I'll poke around a bit to see how Slate is handling this under the hood.

**Comment by RavenColEvol** [comment]
I have a work around where I add {props.children} at the bottom it solves the problem.
So basically you'll have 2 children around image tag.

**Comment by vpontis** [comment]
> I have a work around where I add {props.children} at the bottom it solves the problem.
> So basically you'll have 2 children around image tag.

Where are you adding `{props.children}`?

For context, my image element looks like this:

```typescript
const SlateImageElement = ({
  attributes,
  children,
  element,
}: {
  attributes: any;
  children: React.ReactNode;
  element: LumaSlateImageNode;
}) => {
  const selected = useSelected();
  const focused = useFocused();
  const readOnly = useReadOnly();

  let blobUrl;
  let isUploading = false;
  if (!element.url) {
    blobUrl = LocalImageStore.get(element);
    isUploading = Boolean(blobUrl);
  }

  if (!element.url && !blobUrl && readOnly) {
    return <div {...attributes}>{children}</div>;
  }

  return (
    <div {...attributes}>
      <div contentEditable={false}>
        <img
          className={"animated"}
          src={element.url || blobUrl || PLACEHOLDER_IMAGE}
          style={{
            display: "block",
            maxWidth: "100%",
            maxHeight: "20em",
            boxShadow: selected && focused ? "0 0 0 3px #B4D5FF" : "none",
            opacity: isUploading ? 0.5 : 1,
            marginBottom: "1rem",
          }}
        />
      </div>
      {children}
    </div>
  );
};
```

**Comment by RavenColEvol** [comment]
Something like this
```
<span {...attributes} >
      {children}
      <span
        ref={parentRef}
        contentEditable={false}
        style={{
          paddingTop: '3px',
          paddingBottom: '3px',
          display: `${isInline ? 'block' : 'flow-root'}`
        }}
      >
       
            <Image/>
      </span>
      {children}
    </span>
```

**Comment by vpontis** [comment]
> Something like this
> 
> ```
> <span {...attributes} >
>       {children}
>       <span
>         ref={parentRef}
>         contentEditable={false}
>         style={{
>           paddingTop: '3px',
>           paddingBottom: '3px',
>           display: `${isInline ? 'block' : 'flow-root'}`
>         }}
>       >
>        
>             <Image/>
>       </span>
>       {children}
>     </span>
> ```

Hmm, I'm pretty rendering children twice will cause other issues, won't it? 

And I just tried the solution and I still am not able to select+all and delete the whole document...

**Comment by beqaweb** [comment]
https://github.com/ianstormtaylor/slate/issues/3989
