### ISSUE TITLE
Identifiers for PointRef, RangeRef

### ISSUE THREAD

**Issue by ovionlogis** [ianstormtaylor/slate#4026]
### Feature request

Add the ability to define custom identifiers when creating a `PointRef`, `RangeRef`

>Editor.rangeRef(editor, at, { id: 42 });

or something like this

>Editor.rangeRef(editor, at, { data: { id: 42 } });

**Comment by BrentFarese** [comment]
What is the use case for this?  This needs more info, really.

**Comment by ovionlogis** [comment]
@BrentFarese Hi, I apologize for such a late reply.
In general, the problem is not relevant, since bookmarks are mutable, you can add any fields to them.
But in general, my case is this: I wanted to make something like invisible bookmarks that do not affect the markup of the text. I keep the bookmarks separate from the text, but when changing the text I need to keep the bookmarks up to date. Therefore, I preliminarily put bookmarks on the text, change the text, then save the bookmarks and text separately.

**Comment by ianstormtaylor** [comment]
Depending on how you've architected your codebase this should be solveable with a `Map` or `WeakMap` outside of Slate's concern I think. So I don't think it makes sense to add extra metadata to core to handle it.
