### ISSUE TITLE
Editor.before breaks when in first node with an inline, non-void node

### ISSUE THREAD

**Issue by skokenes** [ianstormtaylor/slate#4032]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
I have a Slate editor with inline, non-void nodes that users can insert into the text.
For the current cursor position, I get the text before the cursor position on the current line like so:
```javascript
const getCurrentLineTextBeforeCursor = (editor) => {
  if (editor.selection) {
    const start = editor.selection.anchor;
    const lineBefore = Editor.before(editor, start, { unit: "line" });
    const lineRange = lineBefore && Editor.range(editor, lineBefore, start);
    const lineText = lineRange && Editor.string(editor, lineRange);
    return lineText;
  }
};
```
This works as expected except in one edge case: If the cursor is in the first block of the document and that block contains an inline, non-void node before the cursor. In that scenario, `Editor.before` returns undefined and the text cannot be found.
In this video, I have 3 lines. Each line has an INLINE_NODE inserted at the end. If you click anywhere in lines 2 or 3, the text before the cursor is returned properly. However, if you click after the start of the inline node in line 1, no text is received because Editor.before returns `undefined`.

https://user-images.githubusercontent.com/5554373/103292046-11b94a80-49bb-11eb-8b64-c494b4d18a5c.mov

Sandbox link: https://codesandbox.io/s/modest-euclid-t616q?file=/src/App.js

Slate: 0.59.0
Browser: Chrome 
OS: Mac 

#### What's the expected behavior?
The expected behavior is that Editor.before returns the range before position, regardless of inline nodes and the block index within the document.

**Comment by UdaraJay** [comment]
Seeing the same; trying to select text before the cursor and `before` is `undefined` when it's the first block. 
But I wonder if it could be because `range` selects for the leaf `text` nodes, and that doesn't exist before the first block?

**Comment by etiennelunetta** [comment]
Did you end up working around this?

**Comment by deepaksisodiya** [comment]
any solution found?

**Comment by samarsault** [comment]
Hey @skokenes, can you still reproduce this issue in the latest version?
I forked your sandbox with the latest version and it seems to work fine - https://codesandbox.io/s/throbbing-frost-cp510?file=/src/App.js

**Comment by skokenes** [comment]
Looks like it is fixed in latest versions of slate
