### ISSUE TITLE
Error when deselecting or pasting: Cannot add property 0, object is not extensible

### ISSUE THREAD

**Issue by niieani** [ianstormtaylor/slate#4034]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Regression in 0.60.1 (from 0.60.0).

Reproduction:

1. Select any text
2. Either: Copy & paste the same text or copy & unselect it
3. Error: Cannot add property 0, object is not extensible

The error will continue happening for any action in the editor.

Sandbox: https://codesandbox.io/s/slate-0601-bug-usbf4

If you downgrade Slate to 0.60.0, the error goes away.

https://user-images.githubusercontent.com/563469/103475325-230aaa00-4d61-11eb-87e1-109fda8716b6.mov

Slate: 0.60.1
Browser: Chrome 88.0.4324.50 and Safari 14.0 (15610.1.28.1.9, 15610).
OS: Mac

#### What's the expected behavior?

No error is shown.

**Comment by jacob-lcs** [comment]
I fixed the problem
https://github.com/ianstormtaylor/slate/pull/4035

**Comment by Q-Qplus1s** [comment]
@jacob-lcs 
Cannot undo after pasting text

**Comment by jacob-lcs** [comment]
This is the [preview page](https://deploy-preview-4035--slatejs.netlify.app/examples/richtext), can you reproduce this bug? @Q-Qplus1s

**Comment by Q-Qplus1s** [comment]
@jacob-lcs 能否加下微信qiezhd，我们有个 slate.js 技术交流群，同时想问下你用的哪个版本的 slate，我 fork 了 0.60.1 版本，在上面改的

**Comment by BrentFarese** [comment]
Fixed by #3850.
