### ISSUE TITLE
Html Serializer continues to apply rules even though a valid rule has applied

### ISSUE THREAD

**Issue by LeeKevin** [ianstormtaylor/slate#404]
It's expected that the serializer use the returned object `ret` when a rule is successfully applied to the element; however, subsequent applicable rules are applied to the element and override the previous rules with higher priority.

At https://github.com/ianstormtaylor/slate/blob/f1a5d6f3b400c1b576ab4bcf6db97a6330d1d529/src/serializers/html.js#L179:

```
   for (const rule of this.rules) {
      if (!rule.deserialize) continue
      const ret = rule.deserialize(element, next)
      if (!ret) continue
      node = ret.kind == 'mark'
        ? this.deserializeMark(ret)
        : ret
    }
```

The for loop should break once the node is deserialized the first time.

**Comment by roadscape** [comment]
I was puzzled by this as well, I expected it to break after finding the first matching rule.
