### ISSUE TITLE
Problem to add a new block right after the current one

### ISSUE THREAD

**Issue by templth** [ianstormtaylor/slate#4051]
Hello,

I'm trying to add a new block right after the block where the cursor is located / where I click on a button.

My questions are:

* How can I determine the path for the current block?
* Which method can I use to add a block after? I use `insertNode` but you can't specify a path when calling it...

Thanks,
Thierry

**Comment by BrentFarese** [comment]
Going to close as this is best left for Slate [Slack](https://slate-slack.herokuapp.com/).  Feel free to head over and join up!  But, you can use `ReactEditor.findPath` I think and then I believe `insertNodes` or some other `Transform` will insert a node(s) and take a `Location` (a Path, Point, or Range).  Thanks!

**Comment by templth** [comment]
Thanks very much!
