### ISSUE TITLE
Get error when I override default editor.apply function

### ISSUE THREAD

**Issue by masihjahangiri** [ianstormtaylor/slate#4058]
I have an issue when I want to override default editor.apply function. In a scenario I want to return without any any thing but it throw a weird error:
``` js
editor.apply = (operation: OperationWithTag) => {
  if (operation.type === 'insert_node' && operation?.node?.label) {
    const currentLength = (editor as EditorWithMaxLength).getStringLength();
    const getNodeLength = operation.node.label.length;
    const totalLength = currentLength + getNodeLength;
    if (totalLength <= limit) apply(operation);
    else return; // it cause throw an weird error
  } else apply(operation);
};
```
![Screenshot (1568)](https://user-images.githubusercontent.com/35561271/105807866-035f4e00-5fbc-11eb-94ff-29f38517b460.png)

**Comment by BrentFarese** [comment]
I don't think this is an error with Slate.  It is more likely an error in your code somewhere.  Glad to take a look and keep it as an open issue if you can provide a reproduction?  Going to close for now tho and glad to reopen if you can provide a repro that shows an issue with Slate's internals.
