### ISSUE TITLE
Committing .yarnrc.yml or move to yarn 2 (pnp)

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#4059]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the expected behavior?
I'm running the repository as a git submodule in a monorepo which uses yarn 2 (the only way to make this kind of setup work currently is with yarn 2 afaik because of the changed node_modules resolution behavior). 

In order to make sure slate builds properly I fix the yarn version of slate to what's in package.json (1.23.0). When I do that yarn generates a bunch of files like `.yarnrc.yml` and a `.yarn` folder which includes the binary for the yarn release mentioned in `.yarnrc.yml`. The recommended way in yarn 2 currently is to commit the binary along with a .yarnrc.yml file (for example in babel they do that here https://github.com/babel/babel/tree/main/.yarn/releases).

It would be very useful for me (and I'm sure others) to commit these files into the main repository here so that this kind of setup is supported out of the box. Alternatively we can go even further and migrate to yarn 2, projects like babel and jest are already using it and imo it is a great improvement over the non-strict behavior of node's resolution strategy. Is is also possible to use yarn 2 and still use the node_modules strategy and slowly migrate later on.

Looking for some opinions before I make a PR

**Comment by TheSpyder** [comment]
Checking in yarn binaries seems to be the general recommendation now, including when migrating a project that can't run in PnP mode to Yarn 2.
