### ISSUE TITLE
editor will crash when input Chinese in the end of link element

### ISSUE THREAD

**Issue by sennpang** [ianstormtaylor/slate#4060]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### Chrome behavior
input **Chinese** at end of **link** element, character will input twice, then move focus to left, the editor crush
![Kapture 2021-01-28 at 12 05 09_Chrome](https://user-images.githubusercontent.com/16861647/106089562-25df9b80-6163-11eb-953b-b99171b6f3e4.gif)

#### Safari behavior
input **Chinese** at end of **link** element, then move focus to left, the editor crush
![Kapture 2021-01-28 at 12 11 09_Safari](https://user-images.githubusercontent.com/16861647/106089564-28da8c00-6163-11eb-9fe0-7ee6ce8e749b.gif)

#### Firefox behavior
input **Chinese** at end of **link** element, then **move focus to link element**, then came back, input Chinese, the editor crush
![Kapture 2021-01-28 at 12 15 07_Firefox](https://user-images.githubusercontent.com/16861647/106089566-29732280-6163-11eb-8105-1b51f2399155.gif)

Slate: 0.XX.X (https://www.slatejs.org/examples/links)
Browser: Chrome / Safari / Firefox
OS: Mac

#### What's the expected behavior?
input Chinese with no errors

**Comment by ulion** [comment]
This only happens in chrome, imo. For now, I only figured out some ugly workaround for this, no idea whether has other side effect. The idea is to document.execCommand("undo") to remove the first unexpected input by ime, in custom onCompositionEnd.

**Comment by 1c7** [comment]
Hi, Any update on this?

**Comment by OldDream** [comment]
> This only happens in chrome, imo. For now, I only figured out some ugly workaround for this, no idea whether introduce other side effect. The idea is to document.execCommand("undo") to remove the first unexpected input by ime, in custom onCompositionEnd.


Thanks !
document.execCommand("undo")   helps me out  in 0.81.1. 
When I use sogou input before a inline element, the whole editor crashed.
