### ISSUE TITLE
Bug in Path.transform()

### ISSUE THREAD

**Issue by Sigkill79** [ianstormtaylor/slate#4063]
#### Do you want to request a _feature_ or report a _bug_?

We use Path.transform() _alot_ in our Operational transform code. I believe I have found a __bug__ with this code. 

#### What's the current behavior?

It computes an off-by-one error when a path is transformed by a move_node that moves within the same branch.

Example: If mv is a move node operation that moves [0] to [3], Path.transform([0], mv) will result in [3]. To me, that is incorrect, since the new path of [0] will be [2]. It does handle all other addresses as I expect. This off-by-one error causes a lot of special handling in our OT code.

The bug is probably caused by an off-by-one error around line 431 in https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/interfaces/path.ts

Slate: 0.60.2
Browser: Any
OS: Any

#### What's the expected behavior?

In the above example Path.transform([0],mv) should result in [2].

**Comment by tiberiuichim** [comment]
Just adding a permalink: https://github.com/ianstormtaylor/slate/blob/dd351c9d0aca2599f9375e707361feff370996bb/packages/slate/src/interfaces/path.ts#L431

**Comment by BrentFarese** [comment]
Do you want to put in some tests for the behavior you think should happen and submit a PR to `Path.transform`?  I bet/hope @TheSpyder might look at it.  I know at TinyMCE @TheSpyder is working a lot with Slate OT code.

**Comment by Sigkill79** [comment]
I did work more on this last night, and I've now figured that this is not a bug at all. The fix above would simply correct some other off-by-one errors caused by myself (and not understanding how the move_node operation works on siblings), but the current Path.transform() seems to have the correct behavior in this case. That is at least my understanding now.

This took me a few hours to figure out...

That also means that this PR is not correct as it fixes the same problem: https://github.com/ianstormtaylor/slate/pull/3831

**Comment by TheSpyder** [comment]
Yeah move node is confusing but I think the current code is correct. It had some tweaks last year that fixed a few things.

@BrentFarese I'll take a look over this (and the related PR) sometime this week to make sure.

**Comment by BrentFarese** [comment]
> Yeah move node is confusing but I think the current code is correct. It had some tweaks last year that fixed a few things.
> 
> @BrentFarese I'll take a look over this (and the related PR) sometime this week to make sure.

Thank you!  Yes that'd be appreciated if you chime in on #3831  if it's not correct as well.
