### ISSUE TITLE
Bug: Range.includes(range, targetRange) missed for range fully inside targetRange case

### ISSUE THREAD

**Issue by ulion** [ianstormtaylor/slate#4064]
#### Do you want to request a _feature_ or report a _bug_?
report a bug.

#### What's the current behavior?
Range.includes(range, targetRange) does not cover `range fully inside targetRange` case, it will return false for this case. As discussed at: https://github.com/ianstormtaylor/slate/pull/3093#discussion_r567308300

Slate: since https://github.com/ianstormtaylor/slate/pull/3093 until now (0.60.2)
Browser: Not related
OS: Not related

#### What's the expected behavior?
return true

**Comment by BrentFarese** [comment]
This issue needs more description about what the actual bug is.  Please add/elaborate.

**Comment by ulion** [comment]
@BrentFarese The name is indeed not clear for this. depends on the function description in the comment `Check if a range includes a path, a point or part of another range.` if it's targeting the `part of another range`, the current implement is incomplete for the fully inside targetRange case.

**Comment by BrentFarese** [comment]
> @BrentFarese The name is indeed not clear for this. depends on the function description in the comment `Check if a range includes a path, a point or part of another range.` if it's targeting the `part of another range`, the current implement is incomplete for the fully inside targetRange case.

Got it.  Do you want to submit a PR?  It seems like a relatively easy fix.  Might just add a `Range.includes(target, range)` check and flip the order of arguments and then it would encompass what you want?  We also need a test case(s) and I would say maybe we consider changing the name to `Range.overlaps` but that would be a breaking change so maybe not for now.

**Comment by ulion** [comment]
Let's say maybe we just leave it here for now, since Range.includes for target range is indeed not used by any popular slate library as far as I know. So, if any one want to use it for range includes check (indeed intersection as we see), he need fix it first.
