### ISSUE TITLE
Feature: Find the element by its unique id 

### ISSUE THREAD

**Issue by nivekithan** [ianstormtaylor/slate#4068]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Only able to find the path of node with ReactEditor.findPath()

#### Explanation of Feature

In my project each Element have unique _id field.  And I would really love a feature where I can just find the path of element by `RectEditor.findPathById()`.

As of now I am using `Node.elements()`  which works fine but if the element at the end of the document it may long time to find the path. And I think ReactEditor maintains some sort of Map/WeakMap to store path. So if you are able to implement something like that for `_id` then that would be great.

I am not sure if lot of people will get benefit from this feature. But still I think it is a great feature to have.

**Comment by BrentFarese** [comment]
Slate is really agnostic to whether any given node stores an id so I am not sure this type of feature will ever make it into the core library.  As you've done though, any user can implement the feature on top of Slate, or feel free to release a plugin.  Thanks!

**Comment by raitucarp** [comment]
@BrentFarese when I try to implement it, I got an issue, please see: https://github.com/ianstormtaylor/slate/issues/4641
