### ISSUE TITLE
Is Slate dead?

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#4075]
I understand that Slate is still beta, but as of right now, there are PRs that solve real problems that are not merged for months. There is active community around this editor, but without merging I feel that our work goes to vain. Does that mean that Slate is pretty much dead?

We're currently using custom fork of Slate, but that is temporary solution, not permanet one. Are there any plans how to solve current situation or should we move to Draft.js?

**Comment by Mangatt** [comment]
Last stable version on NPM is 0.59.0 (released on 25 Sep 2020), changelog has last entry for 0.58.0.

**Comment by Mangatt** [comment]
Just for clarification - we really appreciate huge amount of work that was put into this project. We have spent with Slate quite a lot of time as well.

But since we are building product that is used in production (and not just us), we need to know where we stands, hence this issue.

**Comment by ianstormtaylor** [comment]
> I understand that Slate is still beta, but as of right now, there are PRs that solve real problems that are not merged for months. There is active community around this editor, but without merging I feel that our work goes to vain. Does that mean that Slate is pretty much dead?
> 
> Last stable version on NPM is 0.59.0 (released on 25 Sep 2020), changelog has last entry for 0.58.0.

The last release of `next` was 3 days ago, which included PRs merged by contributors. I'm sure once @thesunny feels it's good he'll release it to `latest` as well.

As for the changelog, that sounds like a perfect thing to PR then.

> We're currently using custom fork of Slate, but that is temporary solution, not permanet one. Are there any plans how to solve current situation or should we move to Draft.js?
> 
> Just for clarification - we really appreciate huge amount of work that was put into this project. We have spent with Slate quite a lot of time as well.
> 
> But since we are (and not just us) building product that is used in production, we need to know where we stands, hence this issue.

Slate has been pretty clear about the level of commitment it guarantees for a long time, which is "not a lot". 

I understand your frustration, but there's not tons I can do without working for free.

As always, if anyone who's been made good contributions wants to help maintain with commit/merge/release access I'd be happy to grant it. There are currently 15+ people with commit access right now, which is more than most projects. The tough part is that people are busy and Slate is inherently complex.

There are other ways you can help... if anyone is down to help with triaging/closing issues and pull requests that would be great too, I can give access for that. Or people can just go through older issues and comment that they can be closed and that's helpful too.

You're obviously free to use Draft.js or any other editor if you want if those guarantees aren't enough for whatever your needs are.
