### ISSUE TITLE
Node.isNodeList returns true if it contains plainobject

### ISSUE THREAD

**Issue by nivekithan** [ianstormtaylor/slate#4077]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

 `Node.isNodeList([{children : value}, {}])` returns true

`value` implements the `Node[]` interface

 sandbox  : https://codesandbox.io/s/slate-reproductions-forked-8qw2q
recordit : https://recordit.co/ucTIMx5Wq3

Slate: 0.59.0
Browser:  Edge
OS: Windows

#### What's the expected behavior?

`Node.isNodeList([{children : value}, {}])` should return false

#### Some more Information

When I checked using the debugger, I was able to find the error here
```javascript
 isNodeList(value: any): value is Node[] {
    return Array.isArray(value) && (value.length === 0 || Node.isNode(value[0]))
  },
```
But when I checked the code in github I found out this code

```javascript
isNodeList(value: any): value is Node[] {
    return Array.isArray(value) && value.every(val => Node.isNode(val))
  },
```

Which would solve the problem.

But for some reason that's not the code I found through debugger

**Comment by nivekithan** [comment]
The workaround I created is this

```javascript
export const DevNode = {
    isNode(value : any) : value is Node {
        return (
            Text.isText(value) || DevElement.isElement(value) || DevEditor.isEditor(value)
        )
    },

    
  isNodeList(value: any): value is Node[] {
    return Array.isArray(value) && value.every(val => DevNode.isNode(val))
  },
}


export const DevElement = {
    isElement(value: any): value is Element {
        return (
          isPlainObject(value) &&
          DevNode.isNodeList(value.children) &&
          !Editor.isEditor(value)
        )
      },
}

export const DevEditor = {
    isEditor(value: any): value is Editor {
        return (
          isPlainObject(value) &&
          typeof value.addMark === 'function' &&
          typeof value.apply === 'function' &&
          typeof value.deleteBackward === 'function' &&
          typeof value.deleteForward === 'function' &&
          typeof value.deleteFragment === 'function' &&
          typeof value.insertBreak === 'function' &&
          typeof value.insertFragment === 'function' &&
          typeof value.insertNode === 'function' &&
          typeof value.insertText === 'function' &&
          typeof value.isInline === 'function' &&
          typeof value.isVoid === 'function' &&
          typeof value.normalizeNode === 'function' &&
          typeof value.onChange === 'function' &&
          typeof value.removeMark === 'function' &&
          (value.marks === null || isPlainObject(value.marks)) &&
          (value.selection === null || Range.isRange(value.selection)) &&
          DevNode.isNodeList(value.children) &&
          Operation.isOperationList(value.operations)
        )
      },
}
```

We cant just replace `Node.isNodeList()` with the code
```javscript
isNodeList(value: any): value is Node[] {
    return Array.isArray(value) && value.every(val => Node.isNode(val))
  },
  ```
  Since internally `Node.isNode()` calls `Element.isElement()` and `Editor.isEditor()` which both calls `Node.isNodeList()`. So we also have to rewrite those

**Comment by anishagg17** [comment]
Can someone assign me this issuse?

**Comment by anishagg17** [comment]
@nivekithan can you please try to reproduce the issue? I updated the slate, slate-react version in the `sandbox` that you shared and it seems like it has been fixed already.

**Comment by nivekithan** [comment]
In future version this issue is fixed. I thought maintainers will close this issue not really sure why they didn't do though. 

In sandbox,  use version 0.58 or 0.59 instead of latest version. The error will be reproduced.

 I am on my phone that's why I am not creating  sandbox myself.

**Comment by timbuckley** [comment]
As mentioned, we believe this is completed, so I will close. Create a new issue if this arises again/or is made reproducible.
