### ISSUE TITLE
Can not use keyboard to navigate to the end of line after formatted word

### ISSUE THREAD

**Issue by gbalint** [ianstormtaylor/slate#4097]
**Description**
If there is an unformatted space at the end of a line, and a formatted range before that, you can not navigate to the end of the line with the right arrow key.

**Recording**
![Feb-26-2021 13-59-56](https://user-images.githubusercontent.com/127662/109303332-f0e66780-783a-11eb-8e31-ca6af5bc24ad.gif)

**Sandbox**
This is reproducable in https://www.slatejs.org/examples/richtext

**Steps**
Type some text into single line with space as the final character.
Set the final word to bold.
Click on the end of the line to focus the editor with cursor at the end.
Press the left arrow in the keyboard the navigate one step to the left.
Press the right arrow to navigate back: this will fail.

**Expectation**
You should be able to go the end of the line with the right arrow.

**Environment**
- Slate Version: 0.59
- Operating System: MacOS
- Browser: Chrome, Safari

**Comment by aliak00** [comment]
This can be reproduced with a smaller test case.

Type two letters. Make the second one bold. Try and hit back arrow to go to beginning of line. You can't pass the bold letter. First letter can be a space or any other character.

Also reproducible in the sandbox.

At least I think that's the same issues?

**Comment by aliak00** [comment]
on a mac you can COMMAND+LEFT_ARROW and you can navigate to the beginning. And in the OP's example you can COMMAND+RIGHT_ARROW and you'll get to the end.
