### ISSUE TITLE
Selection issue with editable elements nested inside noneditable.

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#410]
I'm writing an app based on Slate to take math notes.
It uses few custom blocks: `definition`, `proposition`, `proof`; they are containers for other blocks like text, lists, images.
Definition blocks are, essentially, rendered as

```
<section className="definition" contentEditable={false}>
  <h3> Definition.</h3>
  <div className="content" contentEditable={true}>
    {props.children}
  </div>
</section>
```

The others are rendered in a similar manner.

Unfortunately there are issues editing those nodes.

It happens because Slate uses `isNonEditable` function from `content.js` to check if the target of a `select` event is a descendant of some `contenteditable="false"` element and in such a case it ignores the event even if the target itself is actually editable.

I wonder why not using [`isContentEditable` html element property](https://developer.mozilla.org/it/docs/Web/API/HTMLElement/isContentEditable) to make the check.

The only reason I can think of is to construct a node non-editable from the point of view of Slate but still editable, that is a node, the editable parts of which are not handled by Slate.

Anyway that behavior can be achieved attaching to the root element of the node a special attribute, something like `data-noneditable`, and then ignoring `select` events targeting elements with ancestors having such an attribute.

If you agree with this proposal I will happy to make  a PR.

**Comment by ianstormtaylor** [comment]
Hey @AlbertHilb, good question. I had no idea the `isContentEditable` property existed, but that does sound like a better alternative. I'd be open to a PR if you were to make it. Just double-check that the current behavior for void nodes (like in the images and embeds examples) still works! Thank you :D

**Comment by ianstormtaylor** [comment]
Thanks for the pull request @AlbertHilb!
