### ISSUE TITLE
It is impossible to write after a Void element (if it is the last element)

### ISSUE THREAD

**Issue by fulviodan** [ianstormtaylor/slate#4115]
First of all thank you for your work: wonderful project:)

The issue is reproducible also in the online demo ([slate image](https://www.slatejs.org/examples/images)): if one deletes everything and add a new image it is impossible to add textual content **after** the image tag.
I tried also, in my code, to add an empty text node after this node but it doesn't work:

` Transforms.insertNodes(editor, [
            {
              type: "acronym",
              children: [{ text: state.item }],
              ttt: state.item,
            },
            {text:""}
          ]);`

**Comment by rneiss** [comment]
adding another block element that includes a text child as the second element seems to work as a workaround for us.

**Comment by juliankrispel** [comment]
@fulviodan this isn't a bug as such, it's left up to the user to deal with this. I've seen and built a couple of different coping mechanisms:

1. Use normalization to ensure there is always a text element before and after a void element
2. Add buttons to insert new blocks, here's how notion does it: ![image](https://user-images.githubusercontent.com/1188186/114387390-488e2780-9b8a-11eb-924b-67f4cea413fd.png)
3. Always insert your void node with a following text node (if it is the last in the document)

**Comment by fulviodan** [comment]
Ok thank you for your reply!

**Comment by ruslansavenok** [comment]
@fulviodan did you manage to fix this using normalisation? If yes, could you please share the code?
