### ISSUE TITLE
Improve performance of `paste`

### ISSUE THREAD

**Issue by skhavari** [ianstormtaylor/slate#412]
#### Repro

Copy and paste the following into a vanilla editor

```text
class App extends React.Component {

  state = {
    state: initialState,
    schema: {
      marks: {
        bold: props => <strong>{props.children}</strong>
      }
    }
  }

  render() {
    return (
      <Editor
        schema={this.state.schema}
        state={this.state.state}
        onChange={state => this.setState({ state })}
        onKeyDown={(e, data, state) => this.onKeyDown(e, data, state)}
      />
    )
  }

  onKeyDown(event, data, state) {
    if (!event.metaKey || event.which != 66) return
    return state
      .transform()
      .toggleMark('bold')
      .apply()
  }

}
```

#### Expect
Finish rendering in milliseconds

#### Actual
It takes a few seconds

**Comment by arekkas** [comment]
Can not reproduce here, are you building a production bundle?

**Comment by skhavari** [comment]
using 0.14.16 from npm

### Repro the build

- `yarn init`
- `yarn add next slate`
- `mkdir pages && touch pages/index.js`
- export the simple react component above in index.js

running in latest chrome on mac sierra

**Comment by arekkas** [comment]
hey @skhavari that list isn't including how you build your bundle :)

**Comment by skhavari** [comment]
my bad, 

the last step should be `next run dev` which builds a development bundle.

**Comment by arekkas** [comment]
Right, building the release bundle will result in better performance than development builds

**Comment by skhavari** [comment]
Will give it a shot.  Is the demo on slatejs.org using a production build (assuming so since the network trace shows build.prod.js - fyi, perf there looks about the same.

**Comment by ianstormtaylor** [comment]
Hey @skhavari I can't reproduce this in `0.15`, so it might be fixed. If you see that it is still happening feel free to re-open
