### ISSUE TITLE
slate-react placeholder unable to change the style

### ISSUE THREAD

**Issue by meowWhat** [ianstormtaylor/slate#4123]
**Problem**
![image](https://user-images.githubusercontent.com/59830413/111122784-798a3500-85a9-11eb-8267-ee09d90785d8.png)

the leaf with placeholder use the inline-styles，user cannot change the placeholder style ，Can I make the placeholder render configurable .

Even if I rewrite RenderLeaf, I can't  find the placeholder node by *symbol* tag .

**Comment by juliankrispel** [comment]
> I think if people want to do this it should like be as a `renderPlaceholder=` overrideable prop, which defaults to the current built-in behavior.

https://github.com/ianstormtaylor/slate/pull/4190
