### ISSUE TITLE
data-gramm not actually disabling Grammarly

### ISSUE THREAD

**Issue by koralarts** [ianstormtaylor/slate#4124]
**Description**
The Grammarly extension is still enabled even though the `data-gramm` attribute is set to `false`.

**Steps**
To reproduce the behavior:
1. Install the Grammarly extension
2. Go to: [https://www.slatejs.org/examples/richtext](https://www.slatejs.org/examples/richtext)
3. Notice the Grammarly extension enabled on the Editor

**Expectation**
The Grammarly extension should not be enabled in the Editor when the `data-gramm` attribute is set to `false`

**Environment**
- Slate Version: v0.60+
- Operating System: Mac / Windows
- Browser: Chrome

**Context**
The issue seems to stem from the `data-slate-editor` attribute that's added. Having said attribute makes Grammarly ignore the `data-gramm` attribute. 

This is a Codepen that simulates the issue outside of Slate but with the relevant attributes ([https://codepen.io/koralarts/pen/MWbRRwM](https://codepen.io/koralarts/pen/MWbRRwM)).

**Comment by ianstormtaylor** [comment]
Does the Grammarly extension being enabled still result in broken editing experience?

It sounds like they are purposely ignoring their own attribute.

**Comment by koralarts** [comment]
The editing itself isn't broken but more of having the `data-gramm` attribute doesn't work in combination with `data-slate-editor`. So if you want to disable Grammarly which `data-gramm="false"` should do based on https://github.com/ianstormtaylor/slate/issues/733, it will still be enabled.

It does seem like Grammarly only looks for the existence `data-gramm` to determine whether or not to disable the extension but having `data-slate-editor` seem to negate that.

**Comment by ianstormtaylor** [comment]
I think the question to answer is whether editing is broken in any way (not just a quick pass). It sounds like Grammarly is purposely circumventing the attribute. 

If editing is totally fine these days, we can remove the attribute by default. If not, we can escalate.

**Comment by e1himself** [comment]
> I think the question to answer is whether editing is broken in any way (not just a quick pass). It sounds like Grammarly is purposely circumventing the attribute.
> If editing is totally fine these days, we can remove the attribute by default. If not, we can escalate.

Editing does work fine indeed. Thanks to how Grammarly team reworked the underlining logic: https://www.grammarly.com/blog/engineering/making-grammarly-feel-native-on-every-website/

But applying corrections from Grammarly doesn't seem to work at the moment: #4579.

**Comment by e1himself** [comment]
Related issue: #733
