### ISSUE TITLE
Caret: <enter> misbehaving on leaf edges

### ISSUE THREAD

**Issue by marco-bor** [ianstormtaylor/slate#4130]
**Description**
Caret holds previous location when pressing \<enter> on a leaf edge. Ideal behavior would be to go to the start of the new block.

**Recording**
![slate](https://user-images.githubusercontent.com/5829628/111869168-4d423000-897e-11eb-955d-6d8ee6218fe3.gif)

**Sandbox**
[Rich text example](https://www.slatejs.org/examples/richtext)

**Steps**
To reproduce the behavior:
1. Go to [Rich text example](https://www.slatejs.org/examples/richtext)
2. Place caret before/after any leaf ("rich", "much", "<textarea>")
3. Press \<enter>
4. See caret location

**Expectation**
See Draft.js equivalent
![draft](https://user-images.githubusercontent.com/5829628/111869210-867aa000-897e-11eb-836d-4eda8199a7c2.gif)

**Comment by marco-bor** [comment]
Currently using this workaround

``` typescript
import { Editor, Point, Transforms } from 'slate'

export function withFix(editor: Editor) {
    var a = editor
    var { insertBreak } = editor

    a.insertBreak = function () {
        const { selection: beforeSelection } = a

        insertBreak()

        const afterLocation = Editor.after(a, a.selection!!, { unit: "block" })!!
        if (Point.equals(beforeSelection!!.anchor, a.selection!!.anchor)) {
            Transforms.select(a, afterLocation)
        }
    }

    return a
}
```

**Comment by toboid** [comment]
Just retested and this appears to be resolved, can it be closed @thesunny @marco-bor?
