### ISSUE TITLE
Proposal: Improve Issue Template for TypeScript

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#4134]
**Problem**
One of the issues I expect to see more of are TypeScript related issues. One of them, which has bitten me more than once, is that the new typings require a recent version of TypeScript in the project. This can lead to issues which can be solved by ensuring that a recent version of TypeScript is used in the issue submission form.

**Solution**
I see two ways to approach this:

1. Create an issue template for "TypeScript" issues only and then have a checkbox that says something like "I have checked and am using a version of TypeScript X or newer"
2. Modify the "Bug: Core" template to have a checkbox with something like "If you are using TypeScript, you have made sure you are using a version of TypeScript X or newer"

I already saw one issue which I think would have been resolved with this and at the very least, would have not required me to ask them to make sure they had the right version of TypeScript. In reality, it is really a dependency, but I'm not sure how you could make it into one since the library itself doesn't depend on it, but getting the correct types does have a dependency on the version.

The versioning issue has caused me problems personally more than once, and I'm the one that wrote much of the new TypeScript stuff. So I can imagine that this would affect others.

I can flesh this out a little more in terms of copy as I think we need users to make sure that they have the correct version of TypeScript BOTH in their editor (like VSCode) and in their NPM project. I've had issues where VSCode was using a new version of TypeScript but my package had an older version so the issues only came up at build time.

**Alternatives**
Two approaches listed above.

**Context**
n/a

**Comment by ianstormtaylor** [comment]
@thesunny I think adding a TypeScript bullet point to the "environment" section of the bug templates might make the most sense, since we're asking for similar things there already.

**Comment by thesunny** [comment]
@ianstormtaylor Thanks and done.
