### ISSUE TITLE
Type `Text` and `Editor` should alias `CustomX` like `Element` aliases `CustomElement`

### ISSUE THREAD

**Issue by mikestopcontinues** [ianstormtaylor/slate#4153]
**Description**
There are numerous places where I should be able to use `Descendent` or `Node` but can't because `Text` isn't referencing `CustomText`. This means referencing `as`ing where it shouldn't be required or strange type unions.

Right now, 
`Descendant` resolves to `CustomElement | BaseText` and
`Node` resolves to `BaseEditor | CustomElement | BaseText`.

I think these should use the custom types. This might turn out to be a can of worms, but if you agree with the solution, I'm happy to open a PR for the above changes.

**Environment**
- Slate Version: 0.61.3
- TypeScript Version: 4.2.3

**Comment by mikestopcontinues** [comment]
Sure! Thanks for getting back to me!

`Node` and `Descendent` don't support CustomText or CustomEditor. I hit against these in my (de)serialization code and my react components. Also, `RenderLeafProps` doesn't support CustomText (while `RenderElementProps` does). 

```ts
export interface CustomText {
  text: string;

  del?: boolean;
  strong?: boolean;
  code?: boolean;
  em?: boolean;
  u?: boolean;
}

export interface CustomElement {
  children: Descendant[];

  type: 'p' | 'blockquote' | 'h1' | 'h2' | 'h3' | 'ol' | 'ul' | 'li';
}

declare module 'slate' {
  interface CustomTypes {
    Element: CustomElement;
    Text: CustomText;
  }
}
```

**Comment by thesunny** [comment]
Hi @mikestopcontinues ,

I'm not seeing this issue. I copy and pasted your code directly into a \`custom-types.d.ts\` file.

I created a new file with two lines to see what the types are returning and it seems to be current (see two screenshots below).

Are you using the most recent version of TypeScript? Slate is sensitive to having a recent version.

![](https://user-images.githubusercontent.com/469587/114248117-b26cbe00-994b-11eb-82bf-0f2e493452d6.png)

![](https://user-images.githubusercontent.com/469587/114248140-bac4f900-994b-11eb-9113-e3b3f943f727.png)

**Comment by thesunny** [comment]
Just for clarity, in your example and my screenshot, we aren't seeing `CustomEditor` because it wasn't defined. See [https://docs.slatejs.org/concepts/12-typescript#defining-editor-element-and-text-types](https://docs.slatejs.org/concepts/12-typescript#defining-editor-element-and-text-types)

```typescript
// This example is for an Editor with `ReactEditor` and `HistoryEditor`
import { BaseEditor } from 'slate'
import { ReactEditor } from 'slate-react'
import { HistoryEditor } from 'slate-history'

type CustomText = { text: string; bold: boolean; italic: boolean }

declare module 'slate' {
  interface CustomTypes {
    Editor: BaseEditor & ReactEditor & HistoryEditor
    Element: { type: 'paragraph'; children: CustomText[] }
    Text: CustomText
  }
}
```

**Comment by thesunny** [comment]
`RenderLeafProps` appear to be working for me as well.

![](https://user-images.githubusercontent.com/469587/114248802-86ead300-994d-11eb-9800-f16a52330f96.png)

**Comment by mikestopcontinues** [comment]
Hi @thesunny, something in your message just clicked for me. I was under the impression you could extend an interface from anywhere, not just `.d` files. That's all it took, and everything's working perfectly now. Sorry for the trouble!
