### ISSUE TITLE
slate-react 0.62.0 - Chromium iframe crash

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#4170]
**Description**
When you try to use `[Editable]` inside `iframe`, your app will crash with `Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement]` error. Version `0.61.3` do not have this issue.

**Recording**
Not necessary, just open sandbox.

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-rzk5c?file=/index.js

**Steps**
To reproduce the behavior:
1. See sandbox with error
2. Remove `TextEditor` from iframe and everything works just fine

**Expectation**
Editable should work in every `window` context, as it used to work.

**Environment**
- Slate Version: 0.62.0
- Operating System: Win10
- Browser: Any Chromium based (works just fine in FF)

**Comment by codercodingthecode** [comment]
I have the exact same error with Editable under a chrome extension I'm building with slate.

**Comment by karudo** [comment]
https://www.slatejs.org/examples/iframe
Iframe example does not work for me in Chrome 89.0.4389.114

**Comment by dusty-phillips** [comment]
I think this is the underlying issue behind some odd failures in my cypress tests.
