### ISSUE TITLE
Add `Transforms.moveChildren` method

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#4172]
**Problem**
There are use cases where we want to move the children from one node to another node. It should also safely take the cursor with it.

The problem with using `Transforms.moveNodes` is that there is no easy way to move a specific set of `children` nodes to another parent. When we use the range to select at the edges of the sibling nodes, it takes the parent with it too. This is unpredictable and often not what we want.

I've on more than one occasion went looking for this method and feeling like it exists but never finding it.

**Solution**
Have an explicit method named `Transforms.moveChildren`.

It's really short and looks like this.

```typescript
function moveChildren(editor: Editor, { from, to }: { from: Path; to: Path }) {
  const reverseChildEntries = Node.children(editor, from, { reverse: true })
  for (const [child, childPath] of reverseChildEntries) {
    Transforms.moveNodes(editor, { at: childPath, to })
  }
}
```

Before adding it, I want to get an okay from @ianstormtaylor since it affects the API.

**Alternatives**
I ended up having to do a number of tests with `Transforms.moveNodes` until I found out that it doesn't work. The option is everybody writes their own version of this method but it feels like it's useful enough and yet small enough to include in core.

**Context**
I am using this myself now but feels like it should be in core.

**Comment by ianstormtaylor** [comment]
@thesunny I believe this is possible with ‘moveNodes’ by using a ‘match’ function that checks for the right path length. 

Can you explain your use cases for when you’re moving children only?

**Comment by thesunny** [comment]
One use case I needed it for was to create the `rewrapNode` method which is here #4173. In this example, I want to take the children of a `list-item` and convert it into a `heading` or a `paragraph`. The element types are incompatible (ie. they have different properties) but the children are compatible. So the process is to create a new element `heading`, move the children of the `list-item` to it, and then delete the original element `list-item`.

You're probably correct that it can be done using a `match` option; however, it's challenging. I think you need to create a range from the element using its path to create the anchor/focus from the start/end of the element using the `edge` method calls to find them, then you need to take the current length of the path of the element, and then do a match that compares to that length +1.

I can't remember other specific use cases at the moment but in the years that I've been using Slate, wanting to move `children` has come up and when it did I felt like there should be a method that handles it (usually after searching for it feeling like I just missed it the last time). I think I always ended up writing a method that selects the elements individually.

**Comment by ianstormtaylor** [comment]
Yeah that’s fair that it comes up a decent amount. My only issue is that I’d rather not have to maintain lots of helpers that each do slightly different things—that was one reason for the refactor into the existing smaller set of transforms we have today. I’d rather the core ones be very flexible to help achieve all use cases, even if it means they are slightly more verbose for some. 

I believe you can do move all children as:

```
const [node, path] = Node.get(...)

Transforms.moveNodes(editor, {
  at: path,
  match: n => node.children.includes(n),
  to: ...
})
```

**Comment by thesunny** [comment]
That's a great answer (!) and one that I had no idea was possible. I thought `at` with a Path only selected the one node at the path.  
  
I think one thing that would help is to improve the documentation on how to do matching for all kinds of use cases.  I can see this being an entire page in itself. Generally, I feel like matching is powerful, but not well documented and therefore hard to understand. For example, it was surprising to me that one I select the beginning of the first child node to the end of the last child node, that the range would include the parent. I also didn't know until now that you can select using a Path and then `match` to its children (hence why I used the `Range`).

**Comment by ianstormtaylor** [comment]
Good call, just added a new concepts doc for it!

**Comment by thesunny** [comment]
OMG! This is so awesome! I like how you described from a technical perspective what was happening. I didn't know until right now how it worked.

**Comment by ianstormtaylor** [comment]
@thesunny glad to hear it 😄 I should have added it a long time ago then!
