### ISSUE TITLE
ReactEditor.toSlateNode should add a direction of search

### ISSUE THREAD

**Issue by Xheldon** [ianstormtaylor/slate#4176]
**Problem**
I use `ReactEditor.toSlateNode` API, and find that if the dom isn't a slate node dom, then Slate React will look up untill the editor dom(use js `Element.closest` API inner). 

There is a generic scenario where I will wrap some container around a slate-element, so looking for the Slate node through that container use `toSlateNode` will find the DOM of the Editor(up), but I actually want to look for the children of that container(down), so is it possible to add a parameter to control the direction of the lookup?

**Solution**

Add a parameter to toSlateNode like `ReactEditor.toSlateNode('down')`, and the default parameter is 'up'

@ianstormtaylor  I would be happy to submit a PR if needed.

**Comment by ianstormtaylor** [comment]
@Xheldon can you explain your use case a little more? That method is already pretty complex, so it seems like maybe it should be implemented in user land if others aren’t needing this.

**Comment by Xheldon** [comment]
> @Xheldon can you explain your use case a little more? That method is already pretty complex, so it seems like maybe it should be implemented in user land if others aren’t needing this.

emmmm, yes, maybe I should implement a solution myself, but if there are more people with this need, a more convenient way to call the API could be considered, no? @ianstormtaylor 

My usage scenario is that I will add a button to the left side of the block that mouseover passes through, and this button will display different menus according to the type of the block when clicked to perform corresponding operations on the block. However, the outer layer of elements such as table, image, etc. will be wrapped with an extra div container when renderElement, so when mouseover, e.target gets the dom of the container, and at this time, I use ReactEditor. toSlateNode(editor, dom), if I find that e.target's dom is not a slate node (that is, there is no data-slate-node attribute on the dom), it will look up untill the editor dom (I found that the API internally uses the DOM's native API Element.closest), but I'm actually trying to find the inner elements of the DOM when I mouseover.
Of course, I can use e.target.querySelector('[data-slate-node]') on e.target to get the right DOM and then use ReactEditor.toSlateNode(editor, dom), but I also wish there was a way to directly use toSlateNode to look down and get the corresponding node.

**Comment by ianstormtaylor** [comment]
Thanks for the explanation. I see what you mean, but I’m a little hesitant to add it because it’s not really converting to the nearest node anymore but searching for one in a specific way, which won’t be invoked under the covers by the editor. (Eg. if you clicked on that DOM element the editor would still it as having clicked on the parent.)

Is there a reason you’re not adding the attribute to the wrapper instead?

**Comment by Xheldon** [comment]
> Is there a reason you’re not adding the attribute to the wrapper instead?

Yes, putting properties on the container returned by renderElement is also a solution, but I didn't consider this scenario at the beginning of my project design😂, so now when I use it, I realize how nice it would be if the toSlateNode API provided a convenient parameter so that I don't have to refactor my project code.

But you're right, I shouldn't have implemented it that way, but I don't want to refactor the huge code base I have now, so I decided to use querySelector to find nodes down... Thanks for the suggestion!
