### ISSUE TITLE
Integration tests for slate

### ISSUE THREAD

**Issue by juliankrispel** [ianstormtaylor/slate#4196]
**Problem**

Slate doesn't currently have integration tests. Because of this:

- Accepting changes is high risk.
- Reviewing changes requires thorough manual testing.

**Solution**

Introduce automated integration tests (ideally via gh-actions to be consistent) using cypress

### Cypress
- Great developer ergonomics and debuggability (GUI for stepping through tests, automatic screenshots and video recording)
- Designed to make it easy to avoid flake
- Supports chromium browsers (Edge, Chrome) as well as Firefox

**Alternatives**

### Puppeteer
- Less opinionated than cypress but more configurable
- Supports chromium browsers only (Edge, Firefox, Chrome)

### Webdriver aka selenium
- Has support for all modern browsers
- Third-party support for mobile browsers (look at appium for example)
- Poor developer ergonomics

**Context**

I believe adding good integration tests (for slate-react) could significantly increase confidence and reduce the maintenance burden.

Although there are many options to choose from for integration testing I strongly believe that optimizing for developer ergonomics is the key to success here. Let's make it as easy as possible to increase coverage and debug failing tests.

**Comment by juliankrispel** [comment]
Full disclosure: I've been using both puppeteer and cypress to test slate-editors on a daily basis at work and would like to use what I've learned to help slate.js. I think we could quite easily catch bugs such as #4170 for example by smoke testing the examples.

To keep it small as a first pr I was thinking one could install cypress (or another framework) and write a simple test.

wdyt @ianstormtaylor - would love to get your input

**Comment by ianstormtaylor** [comment]
@juliankrispel that sounds amazing, and would be immensely appreciated. I think the first PR being a single test sounds good too, will give an idea for what the setup looks like. Maybe it can just be writing a single character in an editor? Not sure—trust your decision on whatever it is!

**Comment by TheSpyder** [comment]
> * Supports chromium browsers (Edge, Firefox, Chrome)

nitpick: firefox is not a chromium browser 😂 

Any automated testing is better than no testing, but browser-specific issues will still need to be manually tested.

**Comment by juliankrispel** [comment]
> nitpick: firefox is not a chromium browser 😂

You're right, corrected. However - [Firefox is supported by cypress](https://www.cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/) hence browser specific issues could indeed be tested in cypress.
