### ISSUE TITLE
Raise error when using invalid schema node

### ISSUE THREAD

**Issue by aehlke** [ianstormtaylor/slate#420]
Maybe there's a good reason for the current behavior, but I lost time to a stupid typo (`sceham={schema}` inside my `Editor` component) which meant that calls to `insertInline`/`insertBlock` only inserted a zero-width space.

It seems like it would be better to raise an error in this case, rather than silently fail.

(Otherwise, great plugin and great introduction material, btw! 😸)

**Comment by ianstormtaylor** [comment]
Hey @aehlke I'm not sure there's much we can do about this one, except for raise a warning for any unknown properties passed into the `Editor`. Unless that's a common thing that other React libraries are doing, I'd rather avoid it.

**Comment by aehlke** [comment]
@ianstormtaylor  I wasn't suggesting to raise a warning on an invalid property put into the component - I meant that when using e.g. `wrapInline` with `type: 'myCustomNode'`, if `myCustomNode` doesn't actually exist in the schema, raise an error rather than fail silently. That `myCustomNode` did not exist in my case due to a typo in a property was incidental - I wouldn't do something special for that, yeah.

**Comment by ianstormtaylor** [comment]
Ah interesting, that makes more sense! For now I'd like to hold off, since that same behavior is what allows for a "default block" node with a placeholder, which has seemed helpful in other examples. But if it becomes a big problem for people we can revisit and remove the defaults.
