### ISSUE TITLE
Double click selects next Element

### ISSUE THREAD

**Issue by turbiarz** [ianstormtaylor/slate#4213]
That's pretty annoying, is there any solution how to prevent tis behaviour? 

https://user-images.githubusercontent.com/38399239/115392341-be287200-a1e0-11eb-8d8d-cb9e5dff8a45.mov

https://user-images.githubusercontent.com/38399239/115392878-57f01f00-a1e1-11eb-806a-17ab44211958.mov

**Comment by frnkvieira** [comment]
I'm having the same bug in Chrome but not in Firefox. @turbiarz did you manage to fix it ?
