### ISSUE TITLE
MacOS. Safari. The cursor disappears when deleting text in the editor.

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#4220]
**Description**
If you select a text in the editor (via hotkey or cursor selection), then delete it, then the cursor disappears.

**Recording**
![Apr-23-2021 11-31-31](https://user-images.githubusercontent.com/8024592/115843602-aa228180-a427-11eb-91a4-d017dfcfdeb1.gif)

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. Select text (via cmd + a or cursor).
2. Delete text.
4. See error.

**Expectation**
The cursor is supposed to be displayed.

**Environment**
Slate Version: 0.62.0
Operating System: macOS BigSur 11.2.2 (20D80)
Browser: Safari 14.0.3 (16610.4.3.1.4)

**Comment by arminbro** [comment]
We see the same issue on Safari as well. 

One other thing that I've noticed is when you delete everything, and the cursor disappears and then try to hit the delete key one more time, and you'll see the placeholder disappear as well.

Then when we try to start typing something in the slate editor, we see this error in the console:
```
Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
```

Removing the placeholder seems to fix the problem altogether (including the cursor from disappearing). Removing the placeholder is not a real solution, but I hope it gives a clue to solving this bug.

I'm wondering if it's related to this [bug](https://github.com/ianstormtaylor/slate/issues/3421).

**Comment by imhoffd** [comment]
Seeing this as well even in the plain text example. To demonstrate, I've left the Safari DevTools open in the following video, where I select all and backspace two times. Notice how the placeholder div itself is deleted.

https://user-images.githubusercontent.com/236501/117058540-9a325980-acd3-11eb-9c31-e6fa2a6e9e7f.mp4

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/236501/117058170-285a1000-acd3-11eb-9ea1-e62e41b9aae8.png">

Slate 0.62.0
Safari 14.1

**Comment by kainosnoema** [comment]
Also running into this after upgrading recently. Really surprised this hasn't been resolved yet—such a bad bug in a common feature (placeholder) affecting both Mac and iOS Safari. 😦

**Comment by Belline** [comment]
no updates on this one? I'm also running into issues when using Safari, the only way to make it work consistently is by not using the placeholder object at all.

**Comment by kainosnoema** [comment]
@Belline I take it back! It looks like a bugfix in `slate-react@0.69.0`, just a few days ago, may have fixed this. I recommend trying it along with `slate@0.67.1`.

**Comment by dylans** [comment]
> @Belline I take it back! It looks like a bugfix in `slate-react@0.69.0`, just a few days ago, may have fixed this. I recommend trying it along with `slate@0.67.1`.

Awesome, the community has put in a lot of effort the past two months to try to resolve these types of issues. We've had a bit of instability along the way as these are not easy issues to solve, but hopefully things have improved!
