### ISSUE TITLE
D'n'D. When dragging, the text jumps to the beginning of the editor.

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#4222]
**Description**
If you select text at the beginning or in the middle of the editor, drag it to the end, the selected text moves to the beginning of the editor.

**Recording**
![Apr-23-2021 18-29-51](https://user-images.githubusercontent.com/8024592/115894426-effc3b80-a461-11eb-8d77-864c7e91ae5d.gif)

**Sandbox**
https://www.slatejs.org/examples/plaintext

**Steps**
To reproduce the behavior:
1. Select text not at the beginning of the editor
2. Move selected text to the end of the editor
3. See error

**Expectation**
The selected text is expected to move to the specified location

**Environment**
Slate Version: 0.62.0.
Operating System: all.
Browser: Google Chrome 88.0.4324.192.

**Comment by juliankrispel** [comment]
Pretty sure this is a regression since I've seen this work previously, when we fix this let's add a test to make sure it doesn't happen again.

**Comment by clauderic** [comment]
Solved by #4238
