### ISSUE TITLE
Shadow DOM example is broken

### ISSUE THREAD

**Issue by juliankrispel** [ianstormtaylor/slate#4229]
**Description**
Shadow dom example is currently broken https://www.slatejs.org/examples/shadow-dom

**Recording**
![image](https://user-images.githubusercontent.com/1188186/116562627-38e93f80-a8fb-11eb-9b15-d4b8bee097cd.png)

**Sandbox**
https://www.slatejs.org/examples/shadow-dom

**Steps**
To reproduce the behavior:
1. Go to '...'https://www.slatejs.org/examples/shadow-dom

**Expectation**
It shouldn't be broken

**Environment**
any

**Comment by always-maap** [comment]
It's merged to main but not shipped yet.
https://github.com/ianstormtaylor/slate/pull/4226

**Comment by cameracker** [comment]
This issue has been resolved, thanks for filing it!
