### ISSUE TITLE
The slatejs.org examples page will not load in Internet Explorer 11 (IE 11)

### ISSUE THREAD

**Issue by warnwar** [ianstormtaylor/slate#4235]
**Description**
Apologies if this is the wrong place place for this, but your website does not load the example page in IE 11. A syntax error is shown in the console.

**Recording**
![image](https://user-images.githubusercontent.com/44714486/116894991-4f8fdf00-abf8-11eb-8cf2-56e75d4142b8.png)

**Steps**
To reproduce the behavior:
1. Use IE 11
2. Go to https://www.slatejs.org/examples/richtext
3. See nothing
4. Check console

**Expectation**
Page should load so I can take a closer look at your example code

**Environment**
- Slate Version: whatever your website runs
- Operating System: Windows 10 Enterprise 64-bit, Build 18363
- Browser: Internet Explorer 11

**Context**
We use your HtmlParser on a web app in the Healthcare realm. Every hospital in the US is consistently a few generations behind in technology, so we have to support IE 11.

**Comment by kashi-halma** [comment]
I am also experiencing this same issue on a project. The issue appears to stem from the usage of ES6. Perhaps a babel plugin can be added?

**Comment by thesunny** [comment]
At the moment, IE11 is not supported in Slate and therefore I think it's reasonable that the examples page wouldn't support IE either.

Here is a link to the FAQ on browser support [https://docs.slatejs.org/general/faq#what-browsers-and-devices-does-slate-support](https://docs.slatejs.org/general/faq#what-browsers-and-devices-does-slate-support)

It sounds like it may be possible to get IE11 working, but I don't personally know of any successful attempts at it.

Thanks for the report. Closing for now.
