### ISSUE TITLE
MacOS. Safari. When press the "delete" key in the empty text node that is after the void node, the cursor jumps to the beginning of the editor

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#4242]
**Description**
When you press the delete key in the node that is after the node, the cursor jumps to the beginning of the editor. If you then start to enter text, the cursor will go back. The cursor at the beginning of the editor will not disappear (we get two cursors).

**Recording**
https://user-images.githubusercontent.com/8024592/117205531-6d2c9680-adfa-11eb-91dd-326d98995f5d.mp4

**Sandbox**
https://www.slatejs.org/examples/images

**Steps**
To reproduce the behavior:
1. Place the cursor at the beginning of the paragraph that follows the image.
2. Press "enter" for a new empty paragraph to appear.
3. Press "delete".
4. See error.

**Expectation**
The cursor is expected to stay where it was and remove an empty paragraph (similar to behavior in google chrome).

**Environment**
Slate Version: 0.62.0
Operating System: macOS BigSur 11.2.2 (20D80)
Browser: Safari 14.0.3 (16610.4.3.1.4)

**Comment by liangxiwei** [comment]
My Safari has not problem in example.
safari: 13.1.1 (15609.2.9.1.2)

**Comment by albertputrapurnama** [comment]
This does not happen on Safari 14.1.1

Does this still happen for you @fredure ?

**Comment by fredure** [comment]
The error is not repeated.
