### ISSUE TITLE
Link example does not allow removing links

### ISSUE THREAD

**Issue by aehlke** [ianstormtaylor/slate#427]
Under http://slatejs.org/#/links?_k=sh1amz if you click inside the sample link, or select it, then click the link button, nothing happens. According to the example source, it reads as if it ought to remove the link upon clicking that button.

**Comment by roadscape** [comment]
Is there an error in the console? This may be a dupe of #376

**Comment by aehlke** [comment]
Yep, thanks! Sorry for the dupe
