### ISSUE TITLE
Updating node's data and re-rendering to reflect the updated data?

### ISSUE THREAD

**Issue by aehlke** [ianstormtaylor/slate#428]
I asked my question in a closed ticket, so I'm opening a new one instead as a follow-up:

If the rendered node includes something from the data, how can we re-render the node after updating its data this way? I'd prefer to not have to just remove and reinsert the node.

I'm taking the approach suggested in https://github.com/ianstormtaylor/slate/issues/273 to update a node's data.

My use case: I have a custom node which includes a button; clicking the button allows the user to change part of the node's content, which needs to be reflected in both the node's data and in its rendered form.

**Comment by ianstormtaylor** [comment]
Weird, it definitely should be rerendering for data changes. Can you give me more information on your case? What is the data change, and how is it rendered?

It might be a bug in `shouldComponentUpdate` somewhere if it's not rerendering.

**Comment by aehlke** [comment]
It's entirely possible I'm doing something wrong. I'll try to put something together.

Do you know of an existing example that does something like this?

**Comment by aehlke** [comment]
Can I try to set `shouldComponentUpdate` myself before/after the data update to see if that's the reason?

**Comment by ianstormtaylor** [comment]
@aehlke from our Slack convo, it sounded like you investigated and it was due to something other than re-rendering, so I'm going to close this out.

**Comment by aehlke** [comment]
Yep, thanks.

**Comment by mkampik** [comment]
@aehlke, do you remember what you were doing wrong by any chance?

Tried finding your convo on slack, but looks like it was too long ago :/

I'm having a similar problem of changes to node's data object not causing a re-render the second time I update it...

**Comment by aehlke** [comment]
@mkampik I don't recall but my (extremely messy) source is here: https://github.com/aehlke/manabi/tree/master/manabi/static/js/draft-js-furigana-plugin

**Comment by mkampik** [comment]
@aehlke thanks, appreciate it! Will have a browse ;)
