### ISSUE TITLE
Can't compile the quickstart on typescript

### ISSUE THREAD

**Issue by thorlucas** [ianstormtaylor/slate#4280]
**Description**
I'm following the quickstart guide with typescript and it will not compile.

Here's my code, as per the quickstart:

```typescript
import React, { useEffect, useMemo, useState} from 'react';
import { render } from 'react-dom';
import { BaseEditor, createEditor } from 'slate';
import { Slate, ReactEditor, Editable, withReact } from 'slate-react';

type CustomElement = { type: 'paragraph'; children: CustomText[] }
type CustomText = { text: string }

declare module 'slate' {
  interface CustomTypes {
    Editor: BaseEditor & ReactEditor
    Element: CustomElement
    Text: CustomText
  }
}

const App = () => {
  const editor = useMemo(() => withReact(createEditor()), [])
  // Add the initial value when setting up our state.
  const [value, setValue] = useState([
    {
      type: 'paragraph',
      children: [{ text: 'A line of text in a paragraph.' }],
    },
  ])

  return (
    <Slate
      editor={editor}
      value={value}
      onChange={newValue => setValue(newValue)}
    >
      <Editable />
    </Slate>
  )
}

render(<App />, document.getElementById('root'));
```

Here are the errors I get:

```
TS2322: Type '{ type: string; children: { text: string; }[]; }[]' is not assignable to type 'Descendant[]'.
  Type '{ type: string; children: { text: string; }[]; }' is not assignable to type 'Descendant'.
    Type '{ type: string; children: { text: string; }[]; }' is not assignable to type 'CustomElement'.
      Types of property 'type' are incompatible.
        Type 'string' is not assignable to type '"paragraph"'.

TS2345: Argument of type 'Descendant[]' is not assignable to parameter of type 'SetStateAction<{ type: string; children: { text: string; }[]; }[]>'.
  Type 'Descendant[]' is not assignable to type '{ type: string; children: { text: string; }[]; }[]'.
    Type 'Descendant' is not assignable to type '{ type: string; children: { text: string; }[]; }'.
      Type 'CustomText' is missing the following properties from type '{ type: string; children: { text: string; }[]; }': type, children
```

Here is my tsconfig:

```json
{
  "compilerOptions": {
	"module": "commonjs",
	"noImplicitAny": true,
	"removeComments": true,
	"preserveConstEnums": true,
	"sourceMap": true,
	"esModuleInterop": true,
	"jsx": "react"
  },
  "include": ["src/ts/*"],
}
```

**Environment**
- Slate Version: 0.63.0
- Operating System: macOS
- TypeScript Version: 4.2.4

**Comment by thorlucas** [comment]
It turns out that using `useState<Descendant[]>(...)` rather than just `useState(...)` (as per the quickstart) fixed it. The quick start guide needs to be changed to reflect this.

**Comment by thesunny** [comment]
@thorlucas Thanks. Would you be up for making the PR?

**Comment by cmditch** [comment]
Thanks for figuring out the correct annotation @thorlucas. I went ahead and opened a PR @thesunny.
Cheers.

**Comment by EKOLX** [comment]
What to do with this line?
`const editor = useMemo(() => withHistory(withReact(createEditor())), []);`
it complains:
`Argument of type 'BaseEditor' is not assignable to parameter of type 'ReactEditor'.
  Type 'BaseEditor' is missing the following properties from type 'ReactEditor': insertData, setFragmentData, hasRange`

**Comment by cmditch** [comment]
@EKOLX check out the custom Editor type in the docs.

https://docs.slatejs.org/concepts/12-typescript#defining-editor-element-and-text-types

**Comment by raitucarp** [comment]
@cmditch still complains about BaseEditor, 
![image](https://user-images.githubusercontent.com/163585/124061591-5781c900-da59-11eb-8830-e7bc60bc58c9.png)

![image](https://user-images.githubusercontent.com/163585/124061620-6b2d2f80-da59-11eb-81cb-be7358c9bd4f.png)

**Comment by SylvainBigonneau** [comment]
> @cmditch still complains about BaseEditor,
> ![image](https://user-images.githubusercontent.com/163585/124061591-5781c900-da59-11eb-8830-e7bc60bc58c9.png)
> 
> ![image](https://user-images.githubusercontent.com/163585/124061620-6b2d2f80-da59-11eb-81cb-be7358c9bd4f.png)

I am getting that same error (without using History). Did you manage to solve it?

**Comment by raitucarp** [comment]
> > @cmditch still complains about BaseEditor,
> > ![image](https://user-images.githubusercontent.com/163585/124061591-5781c900-da59-11eb-8830-e7bc60bc58c9.png)
> > ![image](https://user-images.githubusercontent.com/163585/124061620-6b2d2f80-da59-11eb-81cb-be7358c9bd4f.png)
> 
> I am getting that same error (without using History). Did you manage to solve it?

solved with dirty trick: type casting, `createEditor() as ReactEditor`

**Comment by filkalny-thimble** [comment]
> > > @cmditch still complains about BaseEditor,
> > > ![image](https://user-images.githubusercontent.com/163585/124061591-5781c900-da59-11eb-8830-e7bc60bc58c9.png)
> > > ![image](https://user-images.githubusercontent.com/163585/124061620-6b2d2f80-da59-11eb-81cb-be7358c9bd4f.png)
> > 
> > 
> > I am getting that same error (without using History). Did you manage to solve it?
> 
> solved with dirty trick: type casting, `createEditor() as ReactEditor`

https://docs.slatejs.org/concepts/12-typescript#defining-editor-element-and-text-types
