### ISSUE TITLE
Cannot prevent blur from escape key using key down

### ISSUE THREAD

**Issue by lukesmurray** [ianstormtaylor/slate#4282]
**Description**
Cannot use `e.preventDefault` to avoid blur with `onKeyDown`. the Blur event is fired before the keydown handler is called.

**Sandbox**

https://codesandbox.io/s/slate-reproductions-forked-61xil

**Steps**

Type some text

press escape

the blur event fires, the onKeyDown event is never called.

**Expectation**

onKeyDown fires before blur so that we can prevent the default behavior for the key press.

**Comment by lukesmurray** [comment]
This is very weird, it's reproducible in the mentions example https://www.slatejs.org/examples/mentions

When you have mentions open and press escape the code prevent's default but it's not reproducible if you run the mention's example locally.

**Comment by lukesmurray** [comment]
I think this is a chrome bug 👀, I can't reproduce in safari or firefox.

**Comment by lukesmurray** [comment]
and it's my vimium extension... 🥲

**Comment by laurentsenta** [comment]
Damn, thanks for sharing, you saved me hours of debugging.

https://github-wiki-see.page/m/philc/vimium/wiki/Tips-and-Tricks

> Using the Escape key in inputs
> Vimium uses the <Escape> key to exit insert mode. Some web sites use the <Escape> key to perform actions (like closing a window) from within inputs. For such web sites, Vimium effectively blocks the site’s own functionality. One example of this is the Messenger popups used by Facebook.
