### ISSUE TITLE
yarn test not passed

### ISSUE THREAD

**Issue by liangxiwei** [ianstormtaylor/slate#4286]
**Problem**
yarn test has error,not pass

**Solution**
pls fix it.

**Alternatives**

**Context**
yarn
yarn test

**Comment by TheSpyder** [comment]
You need to actually post the error. Tests pass on main.
https://github.com/ianstormtaylor/slate/actions/runs/865607739

Did you run `yarn build`?

**Comment by liangxiwei** [comment]
> You need to actually post the error. Tests pass on main.
> https://github.com/ianstormtaylor/slate/actions/runs/865607739
> 
> Did you run `yarn build`?

my fault....I just run yarn test....:)
