### ISSUE TITLE
Backwards text typing on empty, nested, editable void Slate Editor

### ISSUE THREAD

**Issue by davidruisinger** [ianstormtaylor/slate#4293]
**Description**
When there is NO text, yet within a nested, editoable void Slate Editor (see [editable voids example](https://www.slatejs.org/examples/editable-voids), starting to type some text leads to backwards typing.

**Recording**
![khkYcJF2rp](https://user-images.githubusercontent.com/5305150/119672292-c3f62080-be3a-11eb-98a6-226d59e13524.gif)

**Sandbox**
Can be reproduced in the [editable voids example](https://www.slatejs.org/examples/editable-voids).

**Steps**
To reproduce the behavior:
1. Go to [editable voids example](https://www.slatejs.org/examples/editable-voids)
2. Delete all text within the nested Slate Editor
3. Start typing
4. See the first letter beeing shifted to the very beginning

**Expectation**
Text should be added as it is typed

**Environment**
- Slate & Slate-React Version: 0.63.0
- Operating System: MacOS
- Browser: Chrome & Safari

**Context**
This might be connected to #4275

**Comment by moxxuk** [comment]
Can this ticket please be re-opened, as the fix was reverted?

**Comment by angjiang** [comment]
this is also extremely problematic for us. having nested editable voids is a big part of our app but this bug makes the nested editor unusable. is there anything we can do try to normalize or force the selection while the root is being addressed?

**Comment by nalband** [comment]
This is causing major issues for our product too. It totally breaks one of our core integrations.
