### ISSUE TITLE
Inserting new-line before anchor renders two inlines

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#430]
JSFiddle: https://jsfiddle.net/aeneas/te8ow3nh/2/

To reprodue use `shift+enter` somewhere in the text, and then just before the link as you can see in this gif:

![broken-newline](https://cloud.githubusercontent.com/assets/3372410/20405899/78cbc816-ad0b-11e6-9b15-5df2d425fea4.gif)

I checked the transform, it's not the culprit. Also it isn't solved with #396 unfortunately. Probably a bug in the leaf or something?

**Comment by arekkas** [comment]
It looks like because of some reasons two newlines are rendered instead of one.

**Comment by ianstormtaylor** [comment]
Doesn't seem to be happening for me actually. Can you double check? If not, what browser?

**Comment by arekkas** [comment]
Weird, this happens in both latest firefox and chrome!

**Comment by arekkas** [comment]
@ianstormtaylor what does this snippet ( https://jsfiddle.net/aeneas/te8ow3nh/3/ ) look like in your browser? Here it looks like this:

![slatesnippet](https://cloud.githubusercontent.com/assets/3372410/20406350/4b78e7de-ad0d-11e6-9045-21412ed29ee0.PNG)
