### ISSUE TITLE
Links break selection

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#432]
Go to http://slatejs.org/#/links?_k=kigr00 and place the selection before `hyperlinks`, then press enter, delete, enter and start typing. You should see something like this:

![slate-link](https://cloud.githubusercontent.com/assets/3372410/20407594/500be6ca-ad12-11e6-91b5-a8befc502b9b.gif)

**Comment by ianstormtaylor** [comment]
Fixed now, thanks for the test case!
