### ISSUE TITLE
Blinking spelling highlight

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#4320]
**Description**
When you enter text with spelling errors, the highlighting of words blinks

**Recording**
https://user-images.githubusercontent.com/8024592/120894087-58bd0300-c61f-11eb-9c5d-f7f0229aa10e.mp4

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1.  Type misspelled word
2. See error

**Expectation**
Spelling highlighting is expected not to blink. For example, TinyMCE and DraftJS no blinking.

**Environment**
Slate Version: 0.62.0.
Operating System: all.
Browser: Google Chrome 91.0.4472.77, (x86_64).

**Comment by jaked** [comment]
this should be fixed by #3888 / #4605, give it a try with the just-released version 0.67.0

**Comment by juliankrispel** [comment]
This has regressed by the looks of it, therefore reopening it.
Here's a loom reproducing the issue https://www.loom.com/share/879b476cc884477597801d7a58819483

Trying to debug currently why `TextString` is re-rendering even though the updated content is no different from what's in the dom. If anyone has any suggestions please let me know.

**Comment by fredure** [comment]
With Cyrillic letters the issue is repeated.
