### ISSUE TITLE
Migrate from 0.57.1 to 0.63.0

### ISSUE THREAD

**Issue by cdprete** [ianstormtaylor/slate#4321]
Hi.
I've a React + TypeScript project which is using `slate`, `slate-react`, `slate-history` and `slate-hyperscript`.

Even by following the migration guide, things doesn't look to work. In particular, the properties like `type` are not recognized even when checking for the type of the node as suggested in the [migration guide](https://docs.slatejs.org/concepts/12-typescript#migrating-from-0-47-x).

Another example is the `createEditor` which returns an `Editor` but `withReact` expects a `ReactEditor`.
Or, for example, how to check if a node is `underline`? Before `node.underline` was enough, but now I cannot find such property anywhere.

Or, the fact that `className` has been removed from the `Slate` component...

Are there some pre <-> post migration examples somewhere, ideally in TypeScript?

**Comment by golota60** [comment]
> Another example is the createEditor which returns an Editor but withReact expects a ReactEditor.

In https://docs.slatejs.org/walkthroughs/01-installing-slatethere's a paragraph which states

> If you are using TypeScript, you will also need to extend the Editor with ReactEditor as per the documentation on TypeScript. The example below also includes the custom types required for the rest of this example.

And underneath it there's a code snippet which declares a module that should resolve that (i think this code snippet is also in the migration guide link you provided). Hope that helps a little!

**Comment by cdprete** [comment]
That link you posted is not resolved (not found) 🙈

**Comment by golota60** [comment]
sorry, i forgot to put a space there - i fixed it, it should work now 😄

**Comment by BrentFarese** [comment]
Great questions, but I think these are best asked in the Slack community vs. a GitHub issue.  Going to close but please feel free to move the discussion to Slack.  Thanks!
