### ISSUE TITLE
Firefox shadow dom bug

### ISSUE THREAD

**Issue by ghingis** [ianstormtaylor/slate#4336]
**Description**
If slate is in a shadow dom it starts writing backwards

**Steps**
To reproduce the behavior:
[https://www.slatejs.org/examples/shadow-dom](https://www.slatejs.org/examples/shadow-dom)
Start typing

**Expectation**
Work as intended..

**Environment**
Firefox 89.0

**Comment by cguellner** [comment]
what was the solution?
