### ISSUE TITLE
Incorrect indentation for lists and quotes when using the richtext example. 

### ISSUE THREAD

**Issue by slightknack** [ianstormtaylor/slate#4401]
**Description and Recording**
This looks like a cool project — opening an issue because I'm hoping to help it improve.

Using the example editor: https://www.slatejs.org/examples/richtext.
Was messing around and got a bullet point without any indentation:

![Screen Shot 2021-07-30 at 9 28 39 AM](https://user-images.githubusercontent.com/54823450/127617398-d804a1ec-2de5-47f1-b3a6-402167341a43.png)

Also got a quote stuck at the front of the list with additional indentation:

![Screen Shot 2021-07-30 at 9 33 34 AM](https://user-images.githubusercontent.com/54823450/127617888-52964eb8-542d-4062-8d3b-dbc6eaf34a42.png)

Not 100% sure why this is indented, is it a feature?

Here's another gif showing general unexpected behavior:

![output](https://user-images.githubusercontent.com/54823450/127619854-5d6ac8df-8298-4caf-bb56-2852f2db5776.gif)

Although the second item is highlighted, clicking turn this into a bulleted list, etc affects the unrelated 4th element. 

**Steps**
Again, not entirely sure, but here's what I did. To reproduce the behavior:

1. Go to 'https://www.slatejs.org/examples/richtext'
2. Delete the default example
3. Make a list
4. Highlight different portions and enter different text, trying to switch types using the menu
5. Something should break?  

I apologize for not being more specific. I was just messing around and don't remember the exact steps, and don't really have enough time to take a deep dive to determine what the heart of the issue is. Sorry for not being of more help.

**Expectation**
Switching the type of element should not invoke any hidden state that is opaque to the end user. If I highlight the second element to make it a bulleted list, it should be a bulleted list.

**Environment**
- Slate Version: Latest as of today used on the website I linked. Probs 0.59 or something.
- Operating System: MacOS Big Sur, Intel
- Browser: Firefox 90.0.2

**Context**
Wanted to give it a try, but ran into some basic issues while messing around.

**Comment by dylans** [comment]
I believe this will be fixed as a result of the fix in #4489 though it requires verification.

**Comment by slightknack** [comment]
I no longer have the hardware on which I originally produced the issue, and haven't been able to reproduce it on this machine. Unless something similar pops up in the future, I'll close this issue for now. Thanks for your work on this project!
