### ISSUE TITLE
Example: Forced Layout doesn't work

### ISSUE THREAD

**Issue by dvacreative** [ianstormtaylor/slate#4407]
When I delete all the content in the [Force Layout Example](https://www.slatejs.org/examples/forced-layout) in google chrome nothing happens ('Untitled' is not inserted in the title block).

I also noticed that when children[0] text:"" the "length" property still equals 1 (see below)
![Capture](https://user-images.githubusercontent.com/48662754/127785784-82822289-9d64-483a-8558-cbfc476305ab.PNG)

I think this prevents transforms from executing.

**Comment by dylans** [comment]
I believe this is now working after landing #4463.

**Comment by cmmartin** [comment]
Looks like "Untitled" is still not inserted as the text of the Title block
