### ISSUE TITLE
copy list-number & paste list-number

### ISSUE THREAD

**Issue by huangxok** [ianstormtaylor/slate#4408]
**Description**
when I copy a list-number , the copy structure is:
![image](https://user-images.githubusercontent.com/7628834/127801927-8549108d-2af2-4911-87ca-af378b1f70a1.png)
fragment JSON :
`
{
    type:'list-number',
    children: [{
        type:'list-item',
        children:[{
             text: 'test1'
        }]
    },{
        type:'list-item',
        children:[{
             text: 'test2'
        }]
    },{
        type:'list-item',
        children:[{
             text: 'test3'
        }]
    }]
}
`
and exec paste, this structure is parsed in html
`
{
    type:'paragraph',
    children:[{text: 'test1'}]
}
{
    type:'list-item',
    children:[{text: 'test2'}]
}
{
    type:'list-item',
    children:[{text: 'test3'}]
}
`
and the same is true of the online example
![image](https://user-images.githubusercontent.com/7628834/127802722-cf8b0367-e617-4d25-bede-41a1da929a76.png)

**Recording**
![image](https://user-images.githubusercontent.com/7628834/127802722-cf8b0367-e617-4d25-bede-41a1da929a76.png)

**Sandbox**
test with demo [https://www.slatejs.org/examples/richtext](rich-text)

**Steps**
1. insert mutiple line paragraph
2. click list-number 
3. select the list-number , copy
4. insert a line paragraph
5. paste the copy content
6. it occurs 

**Expectation**

**Environment**
- Slate Version: 0.63.0
- Operating System: MacOS 11.5.1
- Browser: Chrome

**Context**
is it a bug? or how to handle the situation?

**Comment by dylans** [comment]
Fixed in #4489 0.66.0 release will include it.
