### ISSUE TITLE
Undo Error: first.getLastText is not a function

### ISSUE THREAD

**Issue by khrykin** [ianstormtaylor/slate#441]
Repro *(Chrome, OSX)*
__Case 1__
  - open http://slatejs.org/#/links
  - add link to existing text
  - hit `⌘Z`

![link](https://cloud.githubusercontent.com/assets/5675885/20457864/00a3f808-aea6-11e6-8383-1db27d102eac.gif)

__Case 2__
  - open http://slatejs.org/ (any example)
  - select text by double-click
  - hit `⌘C` and then `⌘V` somewhere
  - hit `⌘Z`

![paste](https://cloud.githubusercontent.com/assets/5675885/20457882/6bc2adfa-aea6-11e6-9750-3ce594ea911a.gif)

**Comment by ianstormtaylor** [comment]
Thanks for reporting this @khrykin!
