### ISSUE TITLE
Suggestion: avoid delete keyword

### ISSUE THREAD

**Issue by TheSpyder** [ianstormtaylor/slate#4425]
Once #4276 is merged, we could look at swapping `set_node` to do `node[key] = undefined` and improve performance instead of using `delete node[key]`.
https://github.com/ianstormtaylor/slate/blob/796389c7d3d9cead1493abcba6c678cb9dfa979f/packages/slate/src/transforms/general.ts#L202-L206

It seems like a potentially risky change, but standardising on `undefined` being the same as the property not existing would help avoid serialisation bugs (where keys with undefined values are omitted).

There's plenty of evidence to suggest that while there's no reason to completely avoid `delete`, it can have performance implications:
https://www.google.com/search?q=javascript+delete+is+slow

**Comment by dylans** [comment]
While this was once true (delete being slow), I think there's sufficient evidence that it's no longer a primary issue:

* https://github.com/googleapis/google-api-nodejs-client/issues/375#issuecomment-567833079
* https://news.ycombinator.com/item?id=4744314

TypeScript 4.4 would likely complian about this change. Per https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#exact-optional-property-types:

> While this works most of the time, not all code in JavaScript makes the same assumptions. Functions and operators like `Object.assign`, `Object.keys`, object spread `({ ...obj })`, and for–in loops behave differently depending on whether or not a property actually exists on an object. In the case of our Person example, this could potentially lead to runtime errors if the age property was observed in a context where its presence was important.

So given the above (doesn't appear to improve performance, risky, with unclear benefit), I don't think this would improve Slate at this time.

Feel free to close if you agree @TheSpyder or elaborate if I'm missing something here. Thanks!

**Comment by TheSpyder** [comment]
I'm not 100% convinced but you're right performance characteristics can change.
