### ISSUE TITLE
Suggestion: Convert tests from Mocha to Jest (and more jest tests in slate-react)

### ISSUE THREAD

**Issue by timbuckley** [ianstormtaylor/slate#4453]
**Problem**

We are writing sorely needed testing for `slate-react`. And specifically we need React-level tests there.

**Solution**

Jest has better support for React testing, so I recomment we use Jest in `slate-react`.

Consequently, since it's better to have one testing library than two similar ones, I recommend we change the existing mocha testing  to jest. Since mocha and jest have similar setup, this should be a simple task.

**Comment by echarles** [comment]
> Since mocha and jest have similar setup, this should be a simple task.

Initial attempt on https://github.com/ianstormtaylor/slate/pull/4459. Any help to get it working appreciated.
