### ISSUE TITLE
No mention of the <SlateProvider> anywhere

### ISSUE THREAD

**Issue by mihainsto** [ianstormtaylor/slate#4479]
https://github.com/ianstormtaylor/slate/blob/0b0328b2d0a595d48905b41c6afcc4f65bc352c6/packages/slate-react/src/hooks/use-slate.tsx#L21

Hello, I think this error isn't explained well, I can't find any ```SlateProvider```. I tried to import the provider but there is nowhere to be found, I can't find any mention also in the repo, it does not exist any provider named 

```<SlateProvider> </SlateProvider>```

**Comment by gitcatrat** [comment]
This is probably a leftover name of old API, currently all the contexts are in Slate component. 

https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/slate.tsx#L72-L78

I.e in this one that wraps your editor: 
`import { Slate } from 'slate-react';`
