### ISSUE TITLE
Inline elements is not deleted when all the child text is deleted

### ISSUE THREAD

**Issue by imdbsd** [ianstormtaylor/slate#4481]
**Description**
When deleting all the text inside link element, the element is not deleted from value and still rendered with empty content. It cannot selected by moving the cursor to element, so the element still remain in the value. 

**Recording**
![slate-inlines-bug-1](https://user-images.githubusercontent.com/16449020/131448552-003ea67d-0901-40ba-bc12-12864f1e7866.gif)

**Sandbox**
https://codesandbox.io/s/slate-inlines-8oct4?file=/src/App.js
but it also can be replicated on slate links example

**Steps**
To reproduce the behavior:
1. Go to https://codesandbox.io/s/slate-inlines-8oct4?file=/src/App.js
2. place cursor after link
3. try delete all the link
4. link element is still remain in the value and rendered with empty content

**Expectation**
The link element should be deleted since user delete it

**Environment**
- Slate Version: 
   - slate: 0.65.3
   - slate-react: 0.65.3
- Operating System: MacOS Catalina 10.15.7
- Browser: Chrome

**Context**
----

**Comment by imdbsd** [comment]
should be done with normalization since my current work around is checking on normalization, if my inline element doesn't has any text inside it, delete it. but i will check it again

**Comment by Sebbiditaic** [comment]
@imdbsd 这问题解决了吗

**Comment by Cypherjac** [comment]
The issue actually arises from the padding that is being applied to the link element:

`style={{ padding: "10px", backgroundColor: "red" }}`

Without the padding, it works as expected and the link element does not persist.
I believe the issue arises from the fact that the cursor isn't actually placed at the end of the element including padding.

Also when you backspace, the cursor jumps to the text which is located at the centre of the element. I believe this is how it's supposed to behave.

One way you can fix this is to remove the padding from the link element entirely

Another way is to implement a remove link button that will work even with the padding present:
[Slate Demo - Links](https://www.slatejs.org/examples/links)
[Slate Examples - Links](https://github.com/ianstormtaylor/slate/blob/main/site/examples/links.tsx)

**Comment by Sebbiditaic** [comment]
No, after deleting the content of the linked child node, the child node actually becomes a zero-width assertion
Has nothing to do with fill properties
`<a
            data-slate-node="element"
            data-slate-inline="true"
            href="https://nipponcolors.com/#usukoh"
          >
            <span data-slate-node="text">
              <span data-slate-leaf="true">
                <span data-slate-zero-width="z" data-slate-length="0" />
              </span>
            </span>
          </a>
`

**Comment by imdbsd** [comment]
if you remove the padding, the inline element is still there, it just hard to see. Im adding the padding so it still viewable in the sandbox. if you remove the padding, you still can see the element exist in the value.

<img width="1440" alt="Screen Shot 2021-09-06 at 10 45 10" src="https://user-images.githubusercontent.com/16449020/132153451-f3574dbe-0dd4-47ca-90f2-da210f44a7c6.png">

**Comment by dylans** [comment]
So I think this is the same issue as #3379, so closing this in favor of the older issue. I think we'd like to find a solution and fix this, so we may finally give this one a closer look.

**Comment by dylans** [comment]
P.S. As others have noted, normalization is the most likely solution (it's how this gets resolved in Plate for example)
