### ISSUE TITLE
Copying and pasting images doesn't work on iOS Safari

### ISSUE THREAD

**Issue by churichard** [ianstormtaylor/slate#4491]
**Description**
In the "Images" Slate example, if you use iOS Safari and copy and paste an image inside, it does not render like it's supposed to.

**Recording**
![Simulator Screen Recording - iPhone 12 Pro - 2021-09-04 at 13 41 05](https://user-images.githubusercontent.com/4218237/132103638-87fe34c1-efcb-4703-a837-8ed547882111.gif)

**Sandbox**
https://www.slatejs.org/examples/images

**Steps**
To reproduce the behavior:
1. Use iOS Safari
2. Copy an image from somewhere
3. Go to https://www.slatejs.org/examples/images
4. Paste image in and observe that nothing renders

**Expectation**
The image should render

**Environment**
- Slate Version: 0.65.3
- Operating System: iOS
- Browser: Safari

**Context**
I did a little bit of debugging and observed that the "files" array is empty, which is why nothing happens. In other browsers this behavior works fine and the files array is populated.

**Comment by dylans** [comment]
Same issue as https://github.com/ianstormtaylor/slate/issues/4465 . tl;dr; Safari intentionally did not files as part of the API. There’s a newer API that may work but we haven’t explored that yet and it’s a bit more annoying from a UX perspective (eg prompts user to allow access to the buffer). See notes in the other issue.
