### ISSUE TITLE
insert_text operations are applied twice

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#4502]
**Description**
This is not immediately obvious from the editor but when hooking into `editor.apply` it becomes clear that `insert_text` operations are applied doubly (or at least passed back to the plugins) for some reason. It seems to only happen for alphabetic characters as well.

Can be reproduced by applying this patch in main and going to the links example and check the console (this is simply logging whenever `apply` is called.

```
diff --git a/site/examples/links.tsx b/site/examples/links.tsx
index ab66fd2d..087575b4 100644
--- a/site/examples/links.tsx
+++ b/site/examples/links.tsx
@@ -36,7 +36,12 @@ const LinkExample = () => {
 }
 
 const withLinks = editor => {
-  const { insertData, insertText, isInline } = editor
+  const { apply, insertData, insertText, isInline } = editor
+
+  editor.apply = op => {
+    console.log(op)
+    apply(op)
+  }
 
   editor.isInline = element => {
     return element.type === 'link' ? true : isInline(element)
```

Happens in current master, wasn't able to reproduce in latest release in a sandbox (0.65.3). Also happens in both firefox and chrome so seems browser independent.

**Expectation**
Only only `insert_text` op to be shown :grin:

**Comment by bryanph** [comment]
Seems that the `withReact` plugin does some logic to handle these duplicate operations. I was applying the `withReact` plugin last which caused this bug to suddenly show up for me. Putting `withReact` as the first plugin in the stack makes it work as expected again. So this might just be expected behavior.

**Comment by jameshfisher** [comment]
I'm new to Slate and just hit this issue. It's actually much worse than "applied twice": the first insert is applied once, the second is applied twice, the third is applied three times, and so on with quadratic blowup, so it quickly gets really bad! Here's a complete example that shows the problem:

```
<!doctype html>
<html lang="en">
  <body>
    <div id="root"></div>
    <script src="https://unpkg.com/react@17.0.2/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17.0.2/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/slate@0.65.3/dist/slate.js"></script>
    <script src="https://unpkg.com/slate-react@0.65.3/dist/slate-react.js"></script>
    <script>
      const App = () => {
        const editor = React.useMemo(() => SlateReact.withReact(Slate.createEditor()), []);
        const { apply } = editor;
        editor.apply = op => {
          console.log("apply", op);
          apply(op);
        };
        const [value, setValue] = React.useState([ { type: 'p', children: [{ text: 'Some text' }] } ]);
        return React.createElement(
          SlateReact.Slate, 
          {
            editor: editor,
            value: value,
            onChange: newValue => setValue(newValue),
          },
          React.createElement(SlateReact.Editable, {})
        );
      };
      ReactDOM.render(React.createElement(App), document.querySelector('#root'));
    </script>
  </body>
</html>
```

And here is an example showing @bryanph's fix (customizing the editor before wrapping with `withReact`):

```
<!doctype html>
<html lang="en">
  <body>
    <div id="root"></div>
    <script src="https://unpkg.com/react@17.0.2/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17.0.2/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/slate@0.63.0/dist/slate.js"></script>
    <script src="https://unpkg.com/slate-react@0.63.0/dist/slate-react.js"></script>
    <script>
      const App = () => {
        const editor = React.useMemo(
          () => {
            let editor = Slate.createEditor();

            // Make any customizations to editor here, before .withReact 
            const { apply } = editor;
            editor.apply = op => {
              console.log("apply", op);
              apply(op);
            };

            return SlateReact.withReact(editor);
          }, 
          []
        );

        const [value, setValue] = React.useState([ { type: 'p', children: [{ text: 'Some text' }] } ]);
        return React.createElement(
          SlateReact.Slate, 
          {
            editor: editor,
            value: value,
            onChange: newValue => setValue(newValue),
          },
          React.createElement(SlateReact.Editable, {})
        );
      };
      ReactDOM.render(React.createElement(App), document.querySelector('#root'));
    </script>
  </body>
</html>
```

I don't really understand the cause of this issue, or why the fix works, but it seems like a massive footgun.

**Comment by bryanph** [comment]
@jameshfisher your problem was that the `editor.apply` modification in the first example is not inside the `useMemo` and hence it gets called on every render. So unrelated to this issue. I'll close this issue as it's intended behavior.

**Comment by jameshfisher** [comment]
@bryanph ahh you're right! Thanks for debugging my code for me 🤦
