### ISSUE TITLE
Text is always being inserted, even when using auto markdown

### ISSUE THREAD

**Issue by churichard** [ianstormtaylor/slate#4527]
**Description**
Slate seems to always be inserting text on every key press, even when you're not explicitly calling `editor.insertText`. This is especially a problem if you're using Markdown Shortcuts: the last key you type will always be inserted into the editor. If you continue typing, that piece of text will be deleted and overwritten with whatever you type.

This bug does not happen on 0.65.3.

**Recording**
https://user-images.githubusercontent.com/4218237/133479278-1761fd91-6119-46db-8a03-1a84b3bed359.mp4

Basically what's happening is that there is an extra space being inserted after typing `# ` for the Heading 1 auto markdown shortcut. You can tell by inspecting the DOM or by seeing that the cursor is misaligned with the other lines. It's even more noticeable if your trigger character is not a space, because then it will insert that trigger character directly.

**Sandbox**
https://www.slatejs.org/examples/markdown-shortcuts

**Steps**
To reproduce the behavior:
1. Type the auto markdown shortcut for Heading 1: `# `
2. Observe that a space is inserted even though it's not supposed to

**Expectation**
Text should only be inserted when you're calling `editor.insertText`.

**Environment**
- Slate Version: 0.66.1
- Operating System: Windows
- Browser: Chrome

**Comment by nemanja-tosic** [comment]
Tracked the issue down to https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L314 as part of #3888

**Comment by dylans** [comment]
@churichard could you please try out #4529 and verify this works for you as well? Thanks!

**Comment by churichard** [comment]
> @churichard could you please try out #4529 and verify this works for you as well? Thanks!

I don't know how to try it out in my own codebase, but I can verify that it works on the Markdown Shortcuts example on the Slate website. So likely should be fine for me too 👍
