### ISSUE TITLE
[Firefox] Deletion of expanded range causes the editor to crash

### ISSUE THREAD

**Issue by clauderic** [ianstormtaylor/slate#4546]
**Description**
There was a regression introduced in Firefox by https://github.com/ianstormtaylor/slate/pull/4529 which causes the editor to crash when deleting an expanded range that spans across more than a single node.

**Recording**

https://user-images.githubusercontent.com/1416436/134736968-4c1534bb-ab90-463f-a4fb-8cfb52bb9c8f.mp4

**Steps**
To reproduce the behavior:
1. Select an expanded range that spans across more than a single node
2. Press deletet
3. Editor crashes

**Environment**
- Browser: Any version of Firefox (tested in Firefox 92, 91 and 90)

**Comment by nemanja-tosic** [comment]
Introduced by #4529. Namely, i wanted to be smart and have only one `event.preventDefault()`, but missed an early return so it wasn't called for delete on an expanded selection. PR coming shortly.

**Comment by nemanja-tosic** [comment]
@clauderic could you test #4549 please
