### ISSUE TITLE
Docs: Saving to database, serialization to localStorage not working

### ISSUE THREAD

**Issue by LaloLoop** [ianstormtaylor/slate#455]
Hi!
I was testing the [Saving to Database](https://github.com/ianstormtaylor/slate/blob/master/docs/walkthroughs/saving-to-a-database.md) docs to learn how to serialize and deserialize the state with rich text.
While testing the following pieces of code, I found out that they do not work properly, causing some errores while loading the component and restoring the state.
```javascript
// 1
const initialState = (
  Raw.deserialize(localStorage.getItem('content')) ||
  {
    nodes: [
      {
        kind: 'block',
        type: 'paragraph'
      }
    ]
  }
)

// 2
onDocumentChange = (document, state) => {
    // Switch to using the Raw serializer.
    localStorage.setItem('content', Raw.serialize(state))
}
```

Initially the page loads with the following exception.

> Uncaught TypeError: Cannot read property 'document' of null(…)

I modified the code and managed to save the state properly by changing how the state is loaded, but then I noticed that when `onDocumentChange` calls `localStorage.setItem`, the state is stored as `[Object object]` in local storage, and can not be properly restored.

I managed to get a working copy of the example by storing the string version of the serialized state using `JSON.stringify`, thus the initialState needs to be deserialized after `JSON.parse` is applied.

The final two pieces ended up like this:

```javascript
const parsed = JSON.parse(localStorage.getItem('content'));

const initialState = (
  Raw.deserialize(parsed ||
  {
    nodes: [
      {
        kind: 'block',
        type: 'paragraph'
      }
    ]
  }, {terse: !parsed})
);

onDocumentChange (document, state) {
    localStorage.setItem('content', JSON.stringify(Raw.serialize(state)));
}
```

Is this truly an error or am I doing something wrong?

Thanks!

**Comment by ianstormtaylor** [comment]
Absolutely right @LaloLoop, thanks for reporting this! I've just updated that walkthrough.
