### ISSUE TITLE
Bug: applying an autocorrect / spellcheck correction duplicates text

### ISSUE THREAD

**Issue by FlopieUtd** [ianstormtaylor/slate#4550]
**Description**
When I have the spellCheck enabled, and apply a suggestion from the spellcheck, the corrected word gets duplicated. This only happens when some marks (fonts, sizing etc) are applied to the text. 'Normal' text without any styling does not have this problem. 

**Recording**
https://user-images.githubusercontent.com/23555863/134923680-21c755d6-f44d-4647-8182-045f7112e85f.mov

**Steps**
To reproduce the behavior:
1. Create a text element in slate
2. Add marks to the text (underlined, bold, etc...)
3. Apply a suggestion from the spellchecker
4. The suggested word will be duplicated.

**Environment**
- Slate Version: 0.47.8
- Slate-React Version: 0.22.9
- Operating System: MacOS
- Browser: Chrome 94.0.4606.61

**Comment by dylans** [comment]
> Slate Version: 0.47.8
> Slate-React Version: 0.22.9

We're on version 0.66.x for both, and I don't believe either exhibit this issue. Those versions are at least two years old and we don't backport fixes to old versions of Slate.

**Comment by TrySpace** [comment]
Same problem on Android... When using autcomplete function of keyboard (tried different keyboards)
