### ISSUE TITLE
Is the key a reliable block identifier between saves?

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#456]
First of all, this is an absolutely amazing project. I rewrote a huge chunk of a DraftJS editor in a tiny fraction of the code. The abstractions and thought put into this are top notch.

The question is, is the block.key a reliable unique identifier for a block between saves?

Raw.serialize throws away the keys and that's fine. But assuming I write a serialize/deserialize where it saves out the keys and load them back in, can I expect that the Editor won't just throw away the keys in a future version?

Specifically, I use the keys as a simple but effective way to keep track of edits that happened on a page since the user last visited. So, if a user goes away and a page was updated by another team member, the blocks that have been updated have a little highlight on their right edge. This is so that the user doesn't have to read through an entire page trying to figure out what has changed. The user just has to look through the highlighted blocks.

I currently use DraftJS block keys to track this. I'd like to switch the Editor to SlateJS and use the keys in the same way.

Given the change to discard keys on serialize/deserialize, I wanted to make sure that there were no future plans to simply do away with keys as a reliable indicator of a block's identity.

**Comment by ianstormtaylor** [comment]
Hey @thesunny, good question!

There short answer is no, but I've added a few sections to the docs so that hopefully it's easier to find the answer for others in the future. Here they are:

> ### `key`
> `String`
> 
> A short-lived, unique identifier for the node.
> 
> By default, keys are **not** meant to be long-lived unique identifiers for nodes that you might store in a database, or elsewhere. They are meant purely to identify a node inside of a single Slate instance. For that reason, they are simply auto-incrementing strings. (eg. `'0'`, `'1'`, `'2'`, ...) 
> 
> If you want to make your keys uniqueness long-lived, you'll need to supply your own key generating function via the [`setKeyGenerator`](../utils/utils.md#setkeygenerator) util.

And:

> ### `setKeyGenerator`
> `setKeyGenerator(generator: Function) => Void`
> 
> Allows you to specify your own key generating function, instead of using Slate's built-in default generator which simply uses auto-incrementing number strings. (eg. `'0'`, `'1'`, `'2'`, ...)
> 
> This will act globally on all uses of the Slate dependency.
