### ISSUE TITLE
Docs missing info on how to get the path to an Element

### ISSUE THREAD

**Issue by jabbawookiees** [ianstormtaylor/slate#4566]
**Problem**
I can't find out how to get the Path to an Element. Should I be writing my own utility function for this? It seems really basic.

**Solution**
Add it to the docs? Or make it clear that we need to roll our own functions (and hopefully tell us why this isn't part of the core, e.g. for optimization reasons)

**Context**
I wanted to add a void Element and I wanted it to be selectable so users can delete it, which is no problem when you're using the keyboard. `useSelected` works fine for this.

But when the user clicks the void element, for one thing it throws an error if the element isn't set to `contentEditable={false}`. But on top of that, it sets `editor.selection` to `null`. So I figure the correct course of action is to add an `onClick` handler to my void element and forcibly update the selection. But now I'm not sure if there's already some utility method inside slate or if I should implement some sort of `getPathToElement` method myself while ensuring referential integrity to my elements via some key system perhaps?

For what it's worth, I just want to draw, say, a red border around my void element when it's selected.

**Comment by echarles** [comment]
> For what it's worth, I just want to draw, say, a red border around my void element when it's selected.

The image example does that: Image is void, and when you select the image, you get a blue border.

https://github.com/ianstormtaylor/slate/blob/main/site/examples/images.tsx

**Comment by echarles** [comment]
You can try it on https://www.slatejs.org/examples/images

**Comment by jabbawookiees** [comment]
You're right. Thank you!
