### ISSUE TITLE
Grammarly autocorrections don't work

### ISSUE THREAD

**Issue by churichard** [ianstormtaylor/slate#4579]
**Description**
Grammarly autocorrections don't seem to work anymore.

From looking at [this PR](https://github.com/ianstormtaylor/slate/pull/2855), it seems like they did indeed work in a previous version of Slate. And I seem to recall them working not too long ago as well, so this is likely a regression.

Now when you select a correction, the text is inserted at the cursor position and does not overwrite the misspelled word.

**Recording**
![grammarly](https://user-images.githubusercontent.com/4218237/136622334-9ac0c734-3201-4eab-8794-31152b334551.gif)

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext
2. Install + enable Grammarly on the website
3. Type a misspelled word
4. Hover over the misspelled word and select a correction
5. Observe that the correction is inserted at the cursor and does not overwrite the misspelled word

**Expectation**
Autocorrections should overwrite the misspelled word.

**Environment**
- Slate Version: 0.66.6
- Operating System: Windows
- Browser: Chrome

**Comment by dylans** [comment]
This looks like the same issue as the currently broken application of suggestions from spell checking.
