### ISSUE TITLE
Nested layout model to render a combination of different paragraph styles is breaking design 

### ISSUE THREAD

**Issue by mtuchkov** [ianstormtaylor/slate#458]
Hi there, 

I started to integrate the slate into my project and faced an issue (or just misunderstanding) of how to render blocks of formatted data. Here is an example similar to what you have in Rich-Text:
1. Paragraph can be formatted as:
- Bullet list or Ordered List
- Normal paragraph, Heading 1, Heading 2, Blockquote, etc.
- Aligned(Left|Right|Center|Justify)

2. Here is the difference from Rich-Text example you have: all the groups above can be used in different combinations. 

It looks like I have only two options here:
1. Make a flat schema (enumerate all invariants ), for instance:
'h1_alignleft': props => <h1 className="aligned-left" {...props.attibutes}>{props.children}</h1>

2. Make a nested layout with a level per used group, for instance: 
'h1': props => <h1 {...props.attibutes}>{props.children}</h1>
'alignleft': props => <p className="aligned-left" {...props.attibutes}>{props.children}</p>

Obviously, both approaches have big disadvantages: in first case it just is not scalable and any new dimension will be a nightmare, and even with generated schema it is still is not clear how to write a good transformation from 'h1_alignedleft_orderedlist' => 'h1_alignedcenter_orderedList'

in the other case: the output is getting dirty in a sense that the html will be like:
```
<h1>
  <p class="align-left">
   Blah
  </p>
<h1>`
```

Instead of 
```
<h1 class="align-left">
  Blah
</h1>
```

the first one would break an existing design of the website. 

Are there any other solutions for this problem? This is a very generic thing for text editing, so I believe there should be a graceful solution already.

**Comment by ianstormtaylor** [comment]
Hey @mtuchkov! Good question, and @markvankampen is absolutely right that setting the alignment in `node.data` is the way to do it!

**Comment by ianstormtaylor** [comment]
For anyone in the future finding this, I happened to accidentally throw together a JSFiddle that shows this behavior exactly, so here it is:

https://jsfiddle.net/tkt270r9/1/

**Comment by mikecrittenden** [comment]
Just FYI, that fiddle seems to be broken now. I'm just seeing an empty white box.
