### ISSUE TITLE
Minor inconsistency in models/document.js

### ISSUE THREAD

**Issue by simen** [ianstormtaylor/slate#460]
The default value for `nodes` in a `Document` is an empty `OrderedMap`:

```javascript
const DEFAULTS = {
  key: null,
  nodes: new OrderedMap(),
}
```
https://github.com/ianstormtaylor/slate/blob/master/src/models/document.js#L26

While immediately upon creation this becomes a `List`:

```javascript
   properties.nodes = Block.createList(properties.nodes)
```
https://github.com/ianstormtaylor/slate/blob/master/src/models/document.js#L48

Not an actual bug, but if I understand the code correctly a mild inconsistency that threw me off for a while expecting `nodes` to be an `OrderedMap`.

**Comment by ianstormtaylor** [comment]
Good catch @simen, thanks for reporting. I just pushed up a fix!
