### ISSUE TITLE
Cursor goes back to the start of the editor after inserting a bullet or number list on Safari

### ISSUE THREAD

**Issue by georgesbiaux** [ianstormtaylor/slate#4601]
**Description**
Cursor goes back to the start of the editor after inserting a bullet or number list on Safari

**Recording**

https://user-images.githubusercontent.com/22441392/137275736-b5eee0a3-5419-42a2-bf8d-95b5017f81a0.mp4

**Sandbox**
Reproductible on the demo here: https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext
2. Click on the insert a bullet list button
3. See cursor go back to start of editor

**Expectation**
Cursor stay at the new list point

**Environment**
- Slate Version: 0.66.5
- Operating System: macOS
- Browser: Safari
- TypeScript Version: 4.4.3

**Context**
Problem was not occurring when slate was in version 0.63.0

**Comment by georgesbiaux** [comment]
@dylans I checkout to the `slate-react@0.67.0` branch, and the problem is still there 😕:

https://user-images.githubusercontent.com/22441392/137927537-a8d2a302-aa3d-4011-a2d8-6dfde091852d.mp4

**Comment by jameshfisher** [comment]
I might take a look at this today. I'm now facing a different bug due to exactMatch:false. There was talk in #4304 of a better solution; I'll try to understand it.
