### ISSUE TITLE
Duplicate characters when typing at the end of a link decorator

### ISSUE THREAD

**Issue by kellyjosephprice** [ianstormtaylor/slate#4608]
**Description**
If you insert anchor tags via decorators, and then type at the end of the anchor/decorator, duplicate characters get inserted.

**Recording**
![links-demo](https://user-images.githubusercontent.com/451488/137786655-3754a339-0732-4f47-b5c7-989d29156d01.gif)

**Sandbox**
[Code sandbox][sandbox]

**Steps**
To reproduce the behavior:
1. Go to [code sandbox][sandbox]
2. Click on `example.com`
3. Type at the end of `example.com`

**Expectation**
It should insert characters as normal

**Environment**
- Slate Version: 0.66.5
- Operating System: Linux
- Browser: Chrome

**Context**

---

[sandbox]: https://codesandbox.io/s/slate-anchor-decoration-8rg8k

**Comment by kellyjosephprice** [comment]
> * works OK with Slate 65.3

Oh thanks, I hadn't tested prior versions.

> * works OK if I change the `a` to something else (like `b`)

I should have specified that. My current workaround is to style a `span` as if it's an `a`.

**Comment by kellyjosephprice** [comment]
Thanks!

**Comment by SirensOfTitan** [comment]
This still looks broken to me in the latest releases: `0.76.0`

**Comment by kellyjosephprice** [comment]
[Code Sandbox witht 0.76.0](https://codesandbox.io/s/slate-anchor-decoration-0-76-0-u329gz)

Yea, I see it's inserting duplicates, but at least it doesn't error out now?

**Comment by kellyjosephprice** [comment]
@dylans could you re-open this issue please?

**Comment by SirensOfTitan** [comment]
@kellyjosephprice: So the behavior here seems to differs by browser:
* Chromium seems to insert double characters with no errors.
* Safari and Firefox both throw an error: `Cannot resolve a Slate point from DOM point: [object Text],19`
