### ISSUE TITLE
Can I work on something?

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#463]
Hi @ianstormtaylor 

I literally just set up my system so that I could start working on doing some Slate pull requests and went for coffee.

When I came back, I saw that you already knocked the issue off (less than 30 minutes ago!).

Let me know if there is anything simple I can work on that you aren't working on right now. :)

**Comment by ianstormtaylor** [comment]
Hey @thesunny, great question! 😄 

There are a few issues currently tagged with the [`pull-request-please`](https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+is%3Aopen+label%3Apull-request-please) label that might be contenders to work on. They vary in complexity.

There are also a few recent [`bug`](https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+is%3Aopen+label%3Abug) issues that I haven't had time to check out yet.

If you're looking for something slightly less open-ended, there is almost always a need for additional test coverage. There are some bigger things to tackle around adding new types of tests (check out the [`debt`](https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+is%3Aopen+label%3Adebt) issue label if you're interested in that), but there are also some simple matters too. 

The simplest would be to add a bunch more tests for the selection transforms. Right now in `./test/transforms/fixtures/on-selection` you'll see a series of tests, but not all of the selection-based transforms are covered, and even the ones that are have low coverage. (Check out the other transform tests in `at-range` or `at-current-range` for an example of the coverage that would be good to achieve.) So any added tests there would be awesome.

Similarly, the `by-key` transforms could use a bit more coverage in certain cases, although they're better than the selection ones.

(I'm going to close this one, just to get closer to zero open issues, but thank you for asking!)

**Comment by thesunny** [comment]
Thanks Ian,

Since you fixed a bunch of nav related issues, I went looking for some more navigation related bugs (hey, let's get it perfect right?) and I found one which I will post an issue for and try to fix.

Really loving this project.
