### ISSUE TITLE
Double clicking on nodes with active marks don't work properly - Firefox

### ISSUE THREAD

**Issue by bishoymelek** [ianstormtaylor/slate#4634]
**Description**
double click on a word which has a different mark from the rest of the line, will consider it to be an active mark when testing in firefox.

**Recording** 
![bold](https://user-images.githubusercontent.com/69328362/139248823-05248caf-ba81-4e59-9900-72ce2bc12418.gif)

**Sandbox**
[Test it here in the example](https://www.slatejs.org/examples/richtext)  

**Steps**
To reproduce the behavior:
1. Go to sandbox
2. Double click on a word
3. Mark the word with bold
4. select any normal text, it should let the mark inactive (that works 👍)
5. then double click again on the first word we used, the mark we used should be active (doesn't work)
6. if you clicked on the mark again, nothing changes (an error)

**Environment**
- Slate Version: [e.g. 0.62.0]
- Operating System: [e.g. Mac OS]
- Browser: [e.g. FireFox]

**Comment by imdbsd** [comment]
im facing this issue and when try to debug it, domSelection is difference between firefox and chrome. https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L488. The domSelection is return a same object if select it with shit + arrow. Still searching for the workaround and fix.
