### ISSUE TITLE
State is uncontrolled in slate-react@0.70.0

### ISSUE THREAD

**Issue by lynxtaa** [ianstormtaylor/slate#4646]
**Description**
Changing state programmatically won't work in slate-react@0.70.0. For example, setting value from useEffect doesn't work:
```jsx
  useEffect(() => {
    let timer = setTimeout(
      () =>
        setValue([
          { type: "paragraph", children: [{ text: "Hello world!" }] },
        ]),
      5000
    );

    return function () {
      clearTimeout(timer);
    };
  }, []);

  return (
    <Slate editor={editor} value={value} onChange={setValue}>
      <Editable renderElement={renderElement} />
    </Slate>
  );
```

**Recording**
I really hope sandbox will be sufficient for observing this behaviour.

**Sandbox**
https://codesandbox.io/s/slate-set-value-4fxxc?file=/src/Editor/index.js

**Steps**
To reproduce the behavior:
1. Go to sandbox https://codesandbox.io/s/slate-set-value-4fxxc?file=/src/Editor/index.js
2. Wait 5 sec
3. Editor won't show text `Hello world`. But it should
4. Set in package.json `slate-react@0.66.7`
5. Now it works

**Expectation**
I expect slate state to be controlled as in slate-react@0.66.7

**Environment**
- Slate Version: 0.70.0
- Operating System: Windows
- Browser: Firefox, Chrome

**Comment by lynxtaa** [comment]
I think it's because of https://github.com/ianstormtaylor/slate/pull/4540

If so, what is the best way right now for changing state as a whole?

**Comment by aboveyunhai** [comment]
Refer to #4612 and the PR
it can be changed directly by `editor.children = value` above your return statement.
But the approach is still questionable for me. I don't have a complex project that is able to test against the effect of this breaking change.

**Comment by lynxtaa** [comment]
@aboveyunhai Thanks! Closing as duplicate
