### ISSUE TITLE
Pressing keys around hashtag (#) makes cursor jump more than one character

### ISSUE THREAD

**Issue by hitochan777** [ianstormtaylor/slate#4649]
**Description**
From slate 0.70.0, pressing keys around hashtag (#) makes cursor jump more than one character.

**Recording**
![jumping](https://user-images.githubusercontent.com/6002787/140957287-36ee0a24-d20f-44b2-aa5f-a450b47f4ef6.gif)

**Sandbox**
https://codesandbox.io/s/slate-0-5x-forked-xdp6z

**Steps**
To reproduce the behavior:
1. Go to Sandbox from the link above
2. Type `# # foobar`
3. Press arrow key around `#`
4. The cursor moves more than one character

**Expectation**
Cursor moves only one character around `#`

**Environment**
- Slate Version: 0.70.0
- Operating System: CodeSandbox and Ubuntu 20.04
- Browser: Chrome 95

**Context**
Having tested locally I found that I can observe this behavior from https://github.com/ianstormtaylor/slate/commit/5818aca5038f38465a5769fe944f184be0255341. #4565 
Taking look at the code and running additional unit tests (`packages/slate/test/utils/string.ts`) locally I found that `getCharacterDistance` handles KeyCap improperly.
Below are the test cases I found failing.

```javascript
const codepoints = [
  ...
  [' #', 1],
  ['# ', 1],
  ...
]
```
I am not familiar with code point so I might be misunderstanding stuff. Thanks in advance.

**Comment by vnoxxx** [comment]
Same problem with 0,
You can try to type abc 0, abc on the demo page, and move the cursor around pressing the arrow keys... same behavior

**Comment by hitochan777** [comment]
I think you can observe this behavior with `0`~`9`, `#`, `*`, which are defined as start of keycap according to the code below.
https://github.com/ianstormtaylor/slate/commit/5818aca5038f38465a5769fe944f184be0255341#diff-001e36e9a2288ef4288edd68ebe520ae52443df1f4cb5a2e11f21ebaa94f26daR253

**Comment by unageek** [comment]
I think this code:

https://github.com/ianstormtaylor/slate/blob/3ad3aaccad5b3aae335eea21e03866e2c266f5a6/packages/slate/src/utils/string.ts#L133-L135

should be:

```ts
if (previousType === CodepointType.Character || previousType === CodepointType.Keycap) break
```

**Comment by dylans** [comment]
> I think this code:
> 
> https://github.com/ianstormtaylor/slate/blob/3ad3aaccad5b3aae335eea21e03866e2c266f5a6/packages/slate/src/utils/string.ts#L133-L135
> 
> should be:
> 
> ```ts
> if (previousType === CodepointType.Character || previousType === CodepointType.Keycap) break
> ```

Seems reasonable, if you have a moment please raise a PR and we can run it through the automated tests and verify. Thanks!

**Comment by hitochan777** [comment]
@unageek Thank you so much for your investigation!

> if (previousType === CodepointType.Character || previousType === CodepointType.Keycap) break

This change was not enough to make the additional tests pass. Here's the change I made on my forked repository that passes additional tests.
https://github.com/hitochan777/slate/commit/522dbbe2c06aabea31b008e4e3d8ece16b414b78

**Comment by unageek** [comment]
@hitochan777 Thank you for your suggestion! I've just opened PR #4671 and added the additional tests.

**Comment by hitochan777** [comment]
@unageek 
Thank you! I am not familiar with unicode grapheme boundary so I am curious about how you derived `NonBoundaryPairs`?
(I found [a boundary pair table in unicode spec](https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/GraphemeBreakTest.html), is this related?)

**Comment by unageek** [comment]
I'm also not familiar with the grapheme boundary, and I even wasn't aware of the spec you linked to. Thank you for letting me know about that!

I made the table above the definition of `NonBoundaryPairs` based on a little googling for each type of code points and experimenting with a text editor, so there should be many errors.

**Comment by hitochan777** [comment]
@unageek I see! Anyways thank you for your great work :100:
