### ISSUE TITLE
Slate can not handle cursor key on simple text

### ISSUE THREAD

**Issue by drop1down** [ianstormtaylor/slate#4655]
Open any example (plain text or so)
and enter simple word like H2O4
Now press cursors left, right many times

You should see that you can not move cursor by 1 char.
Instead it skip some chars and jump

tested in FF and Chrome

**Comment by rgrzywinski** [comment]
This seems to only affect text that includes numbers (where there is at least one character after the number).

(FYI -- slate 0.70.0)
