### ISSUE TITLE
Pressing enter when inline void selected has different behaviours

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#466]
In the [emoji example](http://slatejs.org/#/emojis?_k=tvbfnq) (latest update: 0.15.12).

You can test it with the smiley emoji and the burger emoji.

### Emoji is followed by an empty text node

*Expected behaviour 🎉 *, pressing enter one time, move the cursor after the emoji, pressing another time split the paragraph, and creates an empty one.

![normal](https://cloud.githubusercontent.com/assets/845425/20743844/d07d3564-b6d8-11e6-96cf-2e55839b2261.gif)

### Emoji is followed by a non empty text node

*Unexpected behaviour 💥 *, pressing enter one time, move the cursor after the emoji, pressing another time split the paragraph but duplicates the emoji.

![bug](https://cloud.githubusercontent.com/assets/845425/20743795/8e9b13aa-b6d8-11e6-994b-6b4e8b3da9b8.gif)

**Comment by ianstormtaylor** [comment]
Fixed! Thanks for the detailed report 😄
