### ISSUE TITLE
examples/richtext.tsx - isBlockActive logic is broken

### ISSUE THREAD

**Issue by greypants** [ianstormtaylor/slate#4663]
**Problem**
The [richtext.tsx](https://github.com/ianstormtaylor/slate/blob/main/site/examples/richtext.tsx#L99) example `isBlockActive`  is not working for me in my environment because `Editor.nodes` returns a `Generator`, not an `Array`. So `isBlockActive` always retruns `false`. 

**Solution**
Wrapping it in `Array.from` fixes the example. PR here: https://github.com/ianstormtaylor/slate/pull/4662

**Comment by Miggz** [comment]
I think this problem is also in the documentation as well under Custom Formatting and Executing Commands.  Adding Array.from() seems to fix the examples.
