### ISSUE TITLE
Performance issue with slate-react: everything is rerender on each character input

### ISSUE THREAD

**Issue by htulipe** [ianstormtaylor/slate#4670]
**Description**
I don't know if it's expected behavior or not but the whole Slate component gets re-render on each character input.

One can see this on the image example for instance (see images below). When I input the "d" character in the first paragraph, I can see that both paragraphs and the image element gets re-render.

This is OK in simple use case such as this example but can severely harm performances when using complex widgets (such as editable voids).

**Recording**
![image_example](https://user-images.githubusercontent.com/1255457/142629880-41471935-5995-4b30-bc3f-709dd5744b6d.png)
![image_example_profiler](https://user-images.githubusercontent.com/1255457/142629931-5f4668f6-2c10-45b4-b252-69872a6dedfd.png)
On can even see that the rendering of the last paragraph takes too long according to profiler.

**Steps**
1. Run the image example
2. Start a React Profiler recording
3. Input a character in the first paragraph
4. Stop the recording

**Expectation**
I would expect only the first paragraph and its ancestors to re-rerender but not the image component, nor the second paragraph.

**Environment**
- Slate Version: 0.59
- Operating System: MacOS
- Browser: Chrome

**Comment by dylans** [comment]
Out of curiosity, did you really run a test now against 0.59 (which is now pretty old)? Or is that just the default in the issue template?

**Comment by htulipe** [comment]
My bad, the latest, 0.70.0 also has this behavior.

**Comment by dylans** [comment]
The out of the box experience might be this way, but use of memo and other techniques will re-render just the changes iirc. In particular the use of plugins (like image) need to be memoized to prevent full re-rendering.

**Comment by htulipe** [comment]
Thanks for your reply.

I tried this but wrapping the image component does not prevent rendering. I dug into the code and found that, between two renders, the `attributes` and `children` props of any given element will never be the same objects. This is explained because [`attributes` is defined for every render](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/element.tsx#L59) as well as [children](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/element.tsx#L48) (event though, children being a special property it might get a different treatment, idk).

On another note, React.memo is useless as soon as your component [uses useState, useReducer or useContext](https://reactjs.org/docs/react-api.html#reactmemo). It's not the case here but might be when you have more complex components.

**Comment by skogsmaskin** [comment]
Also noticed an extreme change in performance. The Huge Document test is basically impossible to write something in now. 

https://www.slatejs.org/examples/huge-document

**Comment by htulipe** [comment]
For what it worth, [the huge document example](https://www.slatejs.org/examples/huge-document) also have performance issues, try typing fast and you'll see an increasing latency between your keyboard input and the time at which it appears on screen.

**Comment by dylans** [comment]
I will try to find time in the next few days to document what we do in our app to prevent unnecessary re-renders. It makes an obviously substantial improvement in performance.

**Comment by skogsmaskin** [comment]
> For what it worth, the huge document example also have performance issues, try typing fast and you'll see an increasing latency between your keyboard input and the time at which it appears on screen.

Make sure not to confuse bad performance with this one, which is not a Slate, but Chromium issue:

https://github.com/ianstormtaylor/slate/issues/4699

**Comment by htulipe** [comment]
Indeed @skogsmaskin I can use the example on Firefox without any issue. Nevertheless, I'm not sure rendering the whole tree is a good thing.

**Comment by htulipe** [comment]
> I will try to find time in the next few days to document what we do in our app to prevent unnecessary re-renders. It makes an obviously substantial improvement in performance.

@dylans I'd be interested if you can share you knowledge

**Comment by htulipe** [comment]
I'm closing this issue. My perf issues where mainly caused by custom contexts that triggered too many renders and too much code executed inside renderElement. Thanks to anybody who helped

**Comment by jiazheng** [comment]
Maybe a huge table can better show input performance issue. Say a table with 500 rows and 10 columns. When input in just one cell, all table rows element should be checked whether need to be updated or not.
