### ISSUE TITLE
How to add custom font-size and font color to the editor?

### ISSUE THREAD

**Issue by tiavina-mika** [ianstormtaylor/slate#4679]
**Problem**
I want a button with color palette and buttons (or select) for font size to change the color or the text size of a selected text

**Solution**
I've searched but not found a solution.

**Comment by christian-schulze** [comment]
I suggest looking through the examples here - https://www.slatejs.org/examples

**Comment by dylans** [comment]
[Plate](https://plate.udecode.io/) (Plugins for slate) has examples of each.
