### ISSUE TITLE
Deleting extra "0" symbols when pressing Backspace

### ISSUE THREAD

**Issue by skolodyazhnyy** [ianstormtaylor/slate#4684]
**Description**

When cursor is placed after zero and another symbol, pressing backspace erases both symbols. In text `f(0)`, cursor is in the end, pressing Backspace will erase `)` and `0` in front of it.

**Recording**

![slate-bug_SparkVideo (1)](https://user-images.githubusercontent.com/576301/142921884-88f73b84-538d-4dd4-8893-3f91f2d77a53.gif)

On this recording I press `0`, `0`, `)`, `Backspace`.

**Sandbox**

It can be reproduced at the demo website: https://www.slatejs.org/examples/richtext.

**Steps**

To reproduce the behavior:
1. Place cursor after symbol which follows 0.
2. Press Backspace.

**Expectation**

One symbol is deleted, instead of two.

**Environment**
- Slate Version: 0.70.0
- Operating System: Mac OS
- Browser: Chrome 96.0.4664.55 (Official Build) (arm64) as well as in Safari.

**Comment by dylans** [comment]
While not identical to the reported issue, I am wondering if either #4671 or #4565 will resolve this by solving a shared underlying issue.

**Comment by skolodyazhnyy** [comment]
It does look related, I'm gonna try these fixes locally.

**Comment by skolodyazhnyy** [comment]
#4565 is already included in 0.70.0, so it does not fix the problem. 

But #4671 is about the same issue, actually if you try to navigate around 0 in my example cursor jumps it.

**Comment by unageek** [comment]
@skolodyazhnyy This issue has been fixed in v0.71.0. Could you give it another try?

**Comment by skolodyazhnyy** [comment]
Works like a charm! Thanks @unageek
