### ISSUE TITLE
Nested list gets deleted when the parent list item is changed.

### ISSUE THREAD

**Issue by miniwangdali** [ianstormtaylor/slate#4685]
**Description**
In a nested list, if you change the content of a list item, the nested list under that list item will disappear.
For example, here is a set of nested list:
1. item one
2. item two
    - sublist item one
    - sublist item two

If you change `item two` to `item`, the nested list under it will get erased as well.

**Recording**

https://user-images.githubusercontent.com/5415452/142957872-1c6acd77-4031-4a6a-b3ce-65ad8b674065.mp4

**Sandbox**
Use slate example: https://www.slatejs.org/examples/paste-html. Simply copy & paste the above list and do the changes.

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/paste-html
2. Copy the sample list above in this issue.
3. Create some newlines and paste the list.
4. try to edit `item two`
5. The nested list disappear

**Expectation**
The nested list under a list item should keep as it is when the list item text changes.

**Environment**
- Slate Version: 0.70.0
- Operating System:  Windows 10
- Browser: Microsoft Edge Version 96.0.1054.29
- TypeScript Version: I am using 4.1.2 but I think it does not matter in this case...

**Comment by dylans** [comment]
This is more an issue with the list example being overly simple, rather than a bug per se in slate. For example, the [list plugin in Plate](https://github.com/udecode/plate/tree/main/packages/elements/list) has worked through most of these types of issues, but the codebase is far more involved than what you would expect for a simple demo.

**Comment by miniwangdali** [comment]
I see. Thanks. I will close this issue.
