### ISSUE TITLE
The editor does not get updated when changing its value

### ISSUE THREAD

**Issue by delijah** [ianstormtaylor/slate#4689]
**Description**
The editor does not get updated when changing its value to something else than what we get in the change handler of slate. In older versions of slate this worked.

**Recording**
Version 0.71.0 (broken): 
![nothing-happens](https://user-images.githubusercontent.com/237739/143328160-613c6fd7-7e90-4528-a01e-5f4611c7db13.gif)
Version 0.66.0 (ok): 
![this-works](https://user-images.githubusercontent.com/237739/143328169-436f3a00-f296-43ff-ad67-c4af65d9cb57.gif)

**Sandbox**
Version 0.71.0 (broken): https://codesandbox.io/s/slate-does-not-change-its-value-1umkm?file=/src/App.js
Version 0.66.0 (ok): https://codesandbox.io/s/slate-does-change-its-value-bu6w6

**Steps**
To reproduce the behaviour:
1. Go to the sandbox
2. Click on the button
3. See wrong behaviour

**Expectation**
We should be able to set the editors value to any value and the editor must render it accordingly.

**Environment**
- Slate Version: As described above
- Operating System: macOS 11.6.1
- Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by dylans** [comment]
This is a deliberate change. Please see the discussion in https://github.com/ianstormtaylor/slate/pull/4540 and let us know if you have any questions. Thanks!

**Comment by delijah** [comment]
Ok i see. Is there a final recommendation how to handle updates from outside the component if we want to do that? By overwriting editor.children or by adding a key props to the Slate component or another approach?

**Comment by jmorganmartin** [comment]
I've seen recommendations for both `key` and `editor.children` methods. Release notes for `0.67` suggest `editor.children`: https://github.com/ianstormtaylor/slate/releases/tag/slate-react%400.67.0

**Comment by tamilvendhank-helptap** [comment]
@jmorganmartin, do you have a code samples of the recommended methods. Both, setting `key` & `editor.children` does not work!!

**Comment by TrySpace** [comment]
I had to resort to setting `key={JSON.stringify(value)}` on the `<Plate` component.
