### ISSUE TITLE
Deleting texts by holding backspace key skips some texts on Android

### ISSUE THREAD

**Issue by AkromDev** [ianstormtaylor/slate#4691]
**Description**
When I delete texts in slate editor by holding delete key, it skips some texts in android. 

**Recording**

<img src="https://user-images.githubusercontent.com/41626115/143512805-f826c75d-f531-4bb3-a6a0-17b4ec47b5ad.gif" width="400" />

**Sandbox**

[Codesandbox code](https://codesandbox.io/s/slate-test-knt01)
[Codesandbox App](https://knt01.csb.app/)

**Steps**
To reproduce the behavior:
1. Visit [Codesandbox App](https://knt01.csb.app/) on android phone
2. Delete texts by holding backspace key

**Expectation**
It should delete all texts in order like it should.

**Environment**
- Slate Version: Latest versions, only tested on `^0.71.0`, `^0.70.2` and `^0.66.5`. Happening on all.
- Operating System: Android, tested on Galaxy S21, Galaxy s8, galaxy a20. 
- Browser: Chrome, Samsung Internet.

**Comment by imdbsd** [comment]
looks same with this #4348

**Comment by AkromDev** [comment]
This issue was happening even when I run slate examples locally. But it is not happening anymore in latest main branch.
I assume the issue was due to editor performance on android and seems to have been fixed after https://github.com/ianstormtaylor/slate/pull/4706

**Comment by imdbsd** [comment]
thanks for commenting @AkromDev ! will try the latest version to

**Comment by TrySpace** [comment]
Seems related to: https://github.com/ianstormtaylor/slate/issues/4715
