### ISSUE TITLE
Performance issues in latest Chrome version

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#4699]
**Description**
There is a huge performance regression with the latest Chrome version. I have not pinpointed in which version this happened, but I have confirmed that when updating to latest there are performance issues which wasn't there before upgrading Chrome.

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/huge-document
2. Scroll down, try to type something.
3. Experience performance issues.

**Environment**
- Slate (slate & slate-react) Version: 0.71
- Operating System: Linux & MacOS
- Browser: Version 96.0.4664.45 (Official Build) (64-bit)

Other signals:
* https://discuss.prosemirror.net/t/performance-issue-with-chrome-v96/4208/3
* https://bugs.chromium.org/p/chromium/issues/detail?id=1271918
* https://jira.atlassian.com/browse/CONFCLOUD-73213

**Comment by skogsmaskin** [comment]
Seems to be related to spellchecking. If I disable spellcheck it's acting fast again.

**Comment by jameshfisher** [comment]
Can reproduce.

Tested multiple Slate versions back to 0.65; they all have the same issue.

Can reproduce with:
* macOS: 12.0.1 (21A559)
* Chrome: Version 96.0.4664.110 (Official Build) (x86_64)

Can also reproduce with:
* Opera 82.0
* Windows 10

**Comment by jameshfisher** [comment]
User-level workaround: visit `chrome://settings/languages` and disable spellcheck.

Developer workaround: remove `spellCheck` property, e.g. change:

```
      <Editable renderElement={renderElement} spellCheck autoFocus />
```

to

```
      <Editable renderElement={renderElement} autoFocus />
```

**Comment by skogsmaskin** [comment]
This is now fixed in v `97`. Closing this.
