### ISSUE TITLE
when updating value  of Editor with api returned data it doesn't update or retender to show that data in editor, was working fine with slate-react@0.65.2 but updating version greater > 0.65.2 introduced this issue.

### ISSUE THREAD

**Issue by sanj44** [ianstormtaylor/slate#4710]
when updating value  of Editor with api  returned data or load from local storage it doesn't update or retender to show that data in editor, was working fine with slate-react@0.65.2 but updating version greater > 0.65.2 introduced this issue.

**Comment by gaKoltai** [comment]
Have the same issue, except  that 0.66.5 works fine. Updated to 0.72.0, and the editor stopped updating its rendered value when value was changed dynamically (eg. fetch a list a certain value on click on a different element would still display the previously clicked element's value)

**Comment by GMkonan** [comment]
Same issue here. Editor is not rendering updated value (like loaded data from previously saved file).

**Comment by dylans** [comment]
Please look at closed issues such as #4689 before opening a roughly identical issue.

The discussion in #4540 explains the reason for the change in behavior (it didn't actually work reliably).

**Comment by jasperoosthoek** [comment]
Has this been fixed or is there any recommendation on how to change the editor contents dynamically in read only mode?

IMHO, when the editor is used in read only mode it is not an editor, it is a viewer. So there should be an easy way to set the value of what is being viewed. When I dynamically change `editor.children` a couple of times it sometimes triggers the following error:
```
Uncaught Error: Cannot find a descendant at path [4] in node: {"children":[{"type":"paragraph","children":[{"text":""}]},{"type":"paragraph","children":[ etc.
```
using the code:
```javascript
<Slate
  editor={{ ...editor, children: content }}
  value={content}
>
  <Editable
    renderElement={renderElement}
    renderLeaf={renderLeaf}
    autoFocus
    readOnly={true}
  />
</Slate>
```
Is there something I'm doing wrong here?

**Comment by jasperoosthoek** [comment]
I ran into this issue too and solved it this way :
```javascript
  editor.children = content; // <--- This line does the trick
  return (
    <Slate
      editor={editor}
      value={content}
    >
      <Editable
        renderElement={renderElement}
        renderLeaf={renderLeaf}
        autoFocus
        readOnly={true}
      />
    </Slate>
  )
  ```
Setting `editor.children = content` makes it work, however, setting `editor={{ ...editor, children: content }}` in the `Slate` component will not work even though this appears to do the same.

Hope this helps.

**Comment by adrianmgil** [comment]
Does it break when you add the hyperlink text in?

It does not work here when I use the editor.children = value;
slate: "^0.82.1"
slate-history: "^0.66.0"
slate-react: "^0.83.1"

**Comment by lostboy** [comment]
This is driving me insane. `useResetPlateEditor` no long clears the editor, nor does `editor.children = []`. With the latest version is there any way left to programmatically set or clear the editor value both the underlaying data and visually?

**Comment by BitPhinix** [comment]
You can either manually call onChange after setting the editor value to the new content (not recommended as this will mess with location refs etc.) or remove the old and insert the new content using `Transforms.removeNodes`/`Transforms.insertNodes` etc.
