### ISSUE TITLE
Long press backspace

### ISSUE THREAD

**Issue by YuriyMorkovnik** [ianstormtaylor/slate#4714]
**Description**
Long press a backspace button causes a concatenation a part of deleting word. Also you can't hold a backspace to delete a part of a word because it stops you after the first symbol.

**Recording**

https://user-images.githubusercontent.com/33699475/144739309-ba79b1da-db2c-413c-9c03-94edbf658886.mp4

**Sandbox**
There is just a copy of a official demo in sandbox
https://codesandbox.io/s/agitated-http-goi7b?file=/src/App.js

**Steps**
To reproduce the behavior:
1. Write a text
2. Hold a backspace button
3. See error

**Expectation**
Smooth deleting of symbols while you’re holding a backspace button

**Environment**
- Slate Version: 0.71
- Operating System: Android 10
- Browser: Chrome

**Comment by AkromDev** [comment]
I had the same issue on galaxy s8 but did not face the issue on s21 and galaxy a21. Maybe It seems that editor has some performance issues on slower/older phones and require more CPU/RAM power. I am not getting this issue anymore on latest examples. The backward delete seems to have been improved as well. My assumption is that https://github.com/ianstormtaylor/slate/pull/4706 has improved editor performance for android and some issues resulting from poor performance are now fixed.

**Comment by AkromDev** [comment]
I noticed it is happening near images while testing but it improved compared to slate@0.71.0

**Comment by TrySpace** [comment]
Seems related to this: https://github.com/ianstormtaylor/slate/issues/4715

**Comment by YuriyMorkovnik** [comment]
Updated slate to v0.80. Seems this issue is fixed. Thanks all!
