### ISSUE TITLE
Quick typing on android

### ISSUE THREAD

**Issue by YuriyMorkovnik** [ianstormtaylor/slate#4715]
**Description**
Quick typing causes missing some symbols

**Recording**

https://user-images.githubusercontent.com/33699475/144739634-77392f65-d46a-4168-9dcb-3e7270f79b92.mp4

**Sandbox**
There is just a copy of an official demo in sandbox
https://codesandbox.io/s/agitated-http-goi7b?file=/src/App.js

**Steps**
To reproduce the behavior:
1. Type words quickly
2. See error

**Expectation**
See correct pressed symbols when you're typing quickly

**Environment**

- Slate Version: 0.71
- Operating System: Android 10
- Browser: Chrome

**Comment by garymillergit** [comment]
I am also experiencing this issue in my react project, i.e. not just a sandbox. I'm hopeful for a solution.

**Comment by skogsmaskin** [comment]
Seems to be an issue with Swiftkey keyboard. I can't reproduce it on Gboard.

**Comment by YuriyMorkovnik** [comment]
Updated slate to v0.80. Seems this issue is fixed. Thanks all!
