### ISSUE TITLE
Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":30}

### ISSUE THREAD

**Issue by roshan1894** [ianstormtaylor/slate#4739]
**Description**
This error is thrown when I add a custom link into a slate editor at current cursor position and use tab or space after the inserted
link.

**Recording**
https://user-images.githubusercontent.com/86764119/146716602-657bf5ce-535a-4bdb-bb36-64c3fbb8d548.mp4

**Expectation**
We have a script which attaches our custom icon to the outreach email editor and apparently outreach email editor uses slate editor. After clicking upon this icon, it opens our extension application in a new tab[for now]. If user clicks on "INSERT LINK" button, link should be inserted at current cursor position which is happening as expected. But, I am unable to click the link and write any texts further after the insertion. If I use space or tab after the link insertion, this error shows up. You could see this clearly in the attached video. 

**Environment**
- Slate Version: No idea as this is happening in third party website
- Operating System: Windows
- Browser: Chrome

**Comment by roshan1894** [comment]
Closing this issue as it is duplicate of https://github.com/ianstormtaylor/slate/issues/3309

**Comment by VladosusCocosus** [comment]
The same problem occurred last 3 week

**Comment by sonhonglee** [comment]
I fixed it by adding css to span[data-slate-node="text"] {
display: inline-block;
width: 100%;
} and then clicking multiple times no longer has the full page error
