### ISSUE TITLE
change key logic to allow for keys with dashes in them

### ISSUE THREAD

**Issue by kommen** [ianstormtaylor/slate#474]
`setKeyGenerator` docs should state that the generated ids shouldn't contain dashes `-`.

Mine did (I used UUIDs), and this broke slate with very confusing errors, until I noticed slate appends `-0` to Leaf nodes and assumes the ids themselves don't contain dashes.

**Comment by ianstormtaylor** [comment]
Actually, I think using UUIDs sounds like a pretty valid case. I'd be open to a pull request that changes the core behavior to split on the final `-` in the string instead if you're open to writing it!

**Comment by ianstormtaylor** [comment]
Ehhh didn't fix it.
