### ISSUE TITLE
setState doesnt reflect in editor change since version 0.67.0

### ISSUE THREAD

**Issue by duc-gp** [ianstormtaylor/slate#4767]
**Description**
before 0.67.0 setState on the value changed the content of the Slate editor

**Recording**
https://user-images.githubusercontent.com/40763918/148194846-bd4685ee-2cc6-4577-b0f6-9c6a6fb7dcd5.mov

**Sandbox**
[A link to a sandbox where the error can be reproduced](https://codesandbox.io/s/slate-setstate-qhfnx?file=/src/App.js)

**Steps**
To reproduce the behavior:
1. visit code sandbox link
2. click on reset

**Expectation**
the text should be resetted but it doesnt. if you switch to version 0.66.7 it works

**Environment**
- every

**Comment by duc-gp** [comment]
okay nevermind, I didnt see the changelog that the this is intended behaviour now:
https://github.com/ianstormtaylor/slate/releases/tag/slate-react%400.67.0

for anyone seeing this, you can change the state now by doing something like this in a event handler:
```
editor.children = someValue;
editor.onChange();
```

**Comment by a-statefull-mind** [comment]
@duc-gp, it did not works for me. https://codesandbox.io/s/busy-ellis-di9vq

Initially, it appears to be working. But, when you click on the text box again, it gives various errors.

**Comment by duc-gp** [comment]
> @duc-gp, it did not works for me. https://codesandbox.io/s/busy-ellis-di9vq
> 
> Initially, it appears to be working. But, when you click on the text box again, it gives various errors.

i cannot follow you. in your codesandbox you are not using editor.children ...

**Comment by a-statefull-mind** [comment]
@duc-gp, sorry about that. I updated the codesandbox after posting the message here. 
What you see on the codesanbox also worked only when there is only one line. If there are 2 lines, it gives error.

Finally came to know about https://github.com/ianstormtaylor/slate/pull/4768/files. In there `resetNodes` implementation works great! Not the other one. 

But, are you sure that 
``
editor.children = someValue;
editor.onChange();

```
worked?

**Comment by a-statefull-mind** [comment]
@duc-gp, nevermind my question in previous comment. I can see that it is working in [here](https://codesandbox.io/s/busy-ellis-di9vq?file=/src/App.js).

**Comment by duc-gp** [comment]
> 

great, one hint, better call editor.onChange() directly after setting the children. otherwise at least on my machine I saw the changes delayed

so instead of 
```
editor.children = emptyValue;
setValue(emptyValue);
```

do this:
```
editor.children = emptyValue;
editor.onChange()
```

**Comment by a-statefull-mind** [comment]
@duc-gp, by delayed, you mean, text did not changed, until you placed the cursor on the editor?

**Comment by duc-gp** [comment]
> @duc-gp, by delayed, you mean, text did not changed, until you placed the cursor on the editor?

yes exactly

**Comment by a-statefull-mind** [comment]
@duc-gp, but yeah, `editor.onChange()` works. I did not knew `onChange` method available on `editor`. Thanks for the hint. 

Regarding the delay, I too faced that, with the following code:
```
export default function App() {
  const editor = useMemo(() => withHistory(withReact(createEditor())), []);
  const [value, setValue] = useState(emptyValue);

  function resetEditor() {
    editor.children = emptyValue;
    setValue(emptyValue);
  }

  return (
    <div className="App">
      <button onClick={resetEditor}>Clear Text</button>

      <Slate
        editor={editor}
        value={value}
        onChange={(newValue) => newValue}
      >
        <Editable placeholder="Type here..." />
      </Slate>
    </div>
  );
}
```

Note the `onChange` handler in `Slate` component.

That delay gone, when I did the following:
```
export default function App() {
  const editor = useMemo(() => withHistory(withReact(createEditor())), []);
  const [value, setValue] = useState(emptyValue);

  function resetEditor() {
    editor.children = emptyValue;
    setValue(emptyValue);
  }

  return (
    <div className="App">
      <button onClick={resetEditor}>Clear Text</button>

      <Slate
        editor={editor}
        value={value}
        onChange={(newValue) =>setValue(newValue)}
      >
        <Editable placeholder="Type here..." />
      </Slate>
    </div>
  );
}
```
Again, note the `onChange` handler in `Slate`.

**Comment by duc-gp** [comment]
ok then you can probably also leave it like this, oh i see, the previous onChange doesnt seem to make any sense
```
onChange={(newValue) => newValue}
```
