### ISSUE TITLE
Resetting editor is not possible @ 0.72.2

### ISSUE THREAD

**Issue by a-statefull-mind** [ianstormtaylor/slate#4780]
**Description**
Resetting editor is not possible.

**Recording**
https://user-images.githubusercontent.com/91463806/148670809-2ec54d15-b161-4e6b-aa19-cc374a0917c8.mov

**Sandbox**
https://codesandbox.io/s/strange-bardeen-nht71

**Steps**
To reproduce the behavior:
1. Click on "Clear Text" button
2. You will see the editor content gets changed.
3. Click on the updated text & start editing.

**Expectation**
Resetting the editor state is the expectation. On other words, the ability to programatically set the state of the editor.

**Comment by a-statefull-mind** [comment]
I had to adopt the idea mentioned here: https://github.com/ianstormtaylor/slate/issues/4564#issuecomment-989536838

For my use case, I did this:
```
Transforms.select(editor, [0, editor.children.length - 1]);
Transforms.delete(editor);
```

But, still, for such a basic, trivial use case, I had to look into so many data, for so long time.

**Comment by dylans** [comment]
This is probably covered by the PR at https://github.com/ianstormtaylor/slate/pull/4768/files to update the docs. If not let me know.

**Comment by a-statefull-mind** [comment]
@dylans, thanks for that. 
It indeed covers that use case.

**Comment by a-statefull-mind** [comment]
@dylans, I just went over the updates to the docs again. 

While the `resetNodes` implementation works as expected, the other example does not. ie: doing the following does not.
```
editor.children = [...];
setValue([...]);
```

It gives the following error: `Uncaught Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":4}
`

**Comment by beewolf233** [comment]
hello, excuse me, I am faced with the same problem， Do you solve it？？

**Comment by a-statefull-mind** [comment]
@beewolf233, yes. You can see it in [here](https://codesandbox.io/s/awesome-bardeen-7jvkq) & also in this [thread](https://github.com/ianstormtaylor/slate/issues/4767)
