### ISSUE TITLE
input Chinese at the end of link element, focus lose

### ISSUE THREAD

**Issue by sennpang** [ianstormtaylor/slate#4811]
**Description**
input **Chinese** at the **end of link element**, focus lose

**Recording**
https://user-images.githubusercontent.com/16861647/151319338-747db06d-6fd7-4f67-8e00-a61241456bfe.mp4

**Steps**
1. open  https://www.slatejs.org/examples/inlines
2. input Chinese at the end of link element
3. focus lose
![image](https://user-images.githubusercontent.com/16861647/151319278-ccef0671-f869-4b0c-9911-aae0508bd9bb.png)

**Expectation**
A clear and concise description of what you expected to happen. (Often it's helpful to test out the behavior of other editors like Google Docs, Medium, Notion, etc. to see how they handle the same issue.)

**Environment**
- Slate Version: latest
- Operating System: MacOS
- Browser: Chrome
- TypeScript Version: [e.g. 3.9.7 - required only if it's a TypeScript issue]

**Context**
when i comment this lines, everything seem fine,
packages/slate-react/src/components/editable.tsx

![image](https://user-images.githubusercontent.com/16861647/151319690-0b97f7b8-146d-4ff4-a3e9-ec8cc2e8dfe1.png)

i wonder known **why we should change selection when input end of inline element** on **compositionstart**,

**Comment by beewolf233** [comment]
hello I miss this quesiton too, do you  have answer??

**Comment by sennpang** [comment]
https://user-images.githubusercontent.com/16861647/151319690-0b97f7b8-146d-4ff4-a3e9-ec8cc2e8dfe1.png

**Comment by dylans** [comment]
It seems all the issues and PRs on this topic have been closed. At least one of them should be open unless it's not an issue.

**Comment by 13940217916** [comment]
解决了我的问题 谢谢了

**Comment by 13940217916** [comment]
@sennpang 非常感谢 困扰我好久
