### ISSUE TITLE
Value won't update when switching between values

### ISSUE THREAD

**Issue by emasovic** [ianstormtaylor/slate#4812]
**Description**
When switching between values, editor wont update.

**Recording**
https://vimeo.com/user164829126/review/670661135/1dc679e103
**Sandbox**
  https://codesandbox.io/s/slate-reproductions-forked-9pkul?file=/index.js

Environment
Slate Version: latest
Operating System: Ubuntu
Browser: Chrome

**Comment by dylans** [comment]
See https://github.com/ianstormtaylor/slate/pull/4540 and https://github.com/ianstormtaylor/slate/pull/4768

**Comment by emasovic** [comment]
Thanks, it works now.
