### ISSUE TITLE
suggestion for non-core transform syntax

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#482]
`slate-edit-table` is an example of a Slate plugin that exports its own transforms.

The problem is that the transform syntax is rather ugly when using non-core transforms.

Here is an example to illustrate:

```js
const {insertRow, moveSelectionBy} = slateEditTableInstance.transforms;
let transform = state.transform();

insertRow(transform);
transform.moveTo(state.selection);
moveSelectionBy(transform, 1, 0);
return transform.apply();
```

What I don't like about the syntax is that

* because core transforms are chained, it helps to show that they are all part of the same transform
* non-core transforms lose this clarity

I would like to add a method, maybe something like `call` that is just syntactic sugar for calling a non-core transform with the first argument being the `transform` object and the remaining arguments being being the remaining arguments in the call.

The code below would then be equivalent to the code above but more readable.

```js
const {insertRow, moveSelectionBy} = slateEditTableInstance.transforms;

return state.transform()
  .call(insertRow)
  .moveTo(state.selection)
  .call(moveSelectionBy, 1, 0)
  .apply();
```

What do you (a) think of the idea and (b) the name of the method `call`. I can create a pull request for this if you think this is a good idea.

**Comment by ianstormtaylor** [comment]
Hey @thesunny, interesting idea. I definitely feel the pain you're talking about with not being able to chain. 

@samypesse @soreine what do you think?

I think it's an interesting solution. Another would be to be able to define transforms upfront somewhere, like on `State` object but I don't think that's flexible enough. 

Another might be to be able to pass in extra transforms when invoking `state.transform`. 

But the `.call()` approach might actually be the lest boilerplate-y that still preserves chaining. I just don't know if it's too weird or not.

**Comment by thesunny** [comment]
Just to go through my entire thought process, to potentially help evaluate the proposal, my initial instinct was to extend the native transforms by adding `transforms` to the plugin architecture.

The idea would be then that you could call the methods directly off of the Transform object like this:

```js
// original idea was this
return transform.insertRow().apply();

// instead of this
return transform.call(insertRow).apply();
```

I ended up with some issues which caused me to reject this:

- Plugins may come to rely on transforms from other plugins and then you have this issue where the end-developer needs to handle dependencies themselves.
- High probability of name conflicts
- Probably the most important, some plugins instantiate with options. If you add more than one instance of a plugin and they have different options, which transform do you run? They will have the same name but different options.

**Comment by ianstormtaylor** [comment]
@thesunny very good issues to bring up! I think I'm sold. If you write up the pull request I'd be happy to merge 😄

**Comment by Soreine** [comment]
That's a good idea, and regarding the different raises issues with extending the Transform object, I think the initial `.call` solution is quite clean and simple to do. :+1:

**Comment by thesunny** [comment]
Worked on this last night including a unit test. Just need to clean up a little and will post a pull request.
