### ISSUE TITLE
Export slate-react/utils/hotkeys

### ISSUE THREAD

**Issue by philicious** [ianstormtaylor/slate#4821]
**Problem**
the editable component uses convenient hotkey definitions in its [onKeyDown func](https://github.com/ianstormtaylor/slate/blob/80661509ecf39b5d8256fa387c7eff15f60bf612/packages/slate-react/src/components/editable.tsx#L1029).

if as a user of Slate, I want to catch and prevent certain hotkeys to reach slate-reacts own handler, I want to use the same convenience hotkey funcs to test for those I want to prevent.

**Solution**
export the hotkeys from utils

**Alternatives**
Any other way 

**Context**
example
```typescript
  const hotKeyHandler = useCallback((event: React.KeyboardEvent<HTMLDivElement>) => {
    const { nativeEvent } = event

    if(Hotkeys.isDeleteForward(nativeEvent)) {
      event.preventDefault()
    }

    return
  }, [])
...
          <Editable
            onKeyDown={hotKeyHandler}
          />
```

**Comment by axelv** [comment]
Why not use https://github.com/ianstormtaylor/is-hotkey ?

**Comment by philicious** [comment]
> Why not use https://github.com/ianstormtaylor/is-hotkey ?

@axelv slates hotkey definitions https://github.com/ianstormtaylor/slate/blob/80661509ecf39b5d8256fa387c7eff15f60bf612/packages/slate-react/src/utils/hotkeys.ts are not part of the underlying is-hotkey lib 

so my current workaround actually is using the is-hotkey lib but I had to copy the hotkeys.ts . while this works fine, its unnecessary duplication of code and makes it harder to maintain when hotkeys might get added or removed

**Comment by dylans** [comment]
@philicious if you have time to raise a PR, I'll review and land it.

**Comment by thesunny** [comment]
It's a good idea but it's almost a year old now and using `is-hotkey` works so closing this.

**Comment by philicious** [comment]
@thesunny I am sorry for not delivering a PR. Drowned in all the other work and my code still uses the copy of slates hotkey code. 
If I get to refactoring, I will send a PR. 

Cheers :)

**Comment by thesunny** [comment]
No worries @philicious , I just happen to be in the issues and occasionally open up a random one or two. If I get a chance to clear out an old one from the rather long backlog, I try to take the opportunity. :)
