### ISSUE TITLE
Fix for #349 is not working if the link is the last node

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#483]
The fix https://github.com/ianstormtaylor/slate/commit/4c79d68cd2db950803ae0adc8d4413ed67f46a26 doesn't handle the case where `next` is null.

How to reproduce:
1. Go to http://slatejs.org/#/links
2. Remove the `!` after the link
3. Press <kbd>Enter</kbd> or insert text

**Comment by SamyPesse** [comment]
Since it'll be hard to update the document in the `onSelect`.

One solution may be to extend the [rule "Ensure that inline void nodes are surrounded by text nodes" of the core schema](https://github.com/ianstormtaylor/slate/blob/master/src/schemas/core.js#L168:L214) to all inline nodes.

@ianstormtaylor @Soreine What do you think ?

**Comment by ianstormtaylor** [comment]
@samypesse I was thinking the same! Are you down to write up a PR for it?

**Comment by SamyPesse** [comment]
Great! Yes, I'll publish on in the next few hours (lot of tests to adapt).

**Comment by ianstormtaylor** [comment]
Fixed now in `0.16.0`, be sure to check the change log.
