### ISSUE TITLE
Error when a multi-paragraph text is selected and something is typed

### ISSUE THREAD

**Issue by iliaznk** [ianstormtaylor/slate#4833]
**Description**
If the editor has some content that has more than one paragraph, you select that content (by pressing ctrl/cmd+A or with a mouse, as long as your selection covers more than one paragraph) and type something to replace it with (just a single letter on a keyboard), the selection disappears, but the new letter won't show up and an error appears in the console: `Uncaught TypeError: Cannot destructure property 'path' of 'i' as it is null.`.

**Recording**
https://user-images.githubusercontent.com/6253368/153609273-c5406e9e-bb58-4ffc-93a5-5d043680bdaf.mov

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. Select all text in the editor.
2. Type any letter on your keyboard.
3. See error in the console.

**Expectation**
The selection should be replaced with the typed letter without any errors.

**Environment**
- Slate Version: [0.72.8]
- Operating System: [macOS 11.1]
- Browser: [Chrome 98.0.4758.80]

**Comment by dylans** [comment]
Ok, I can confirm this is occurring on Chrome and Firefox. I thought it might be a recent regression but it seems to have been an issue for a while based on some quick tests.

**Comment by tmadeira** [comment]
I can confirm this too, from Slate 0.72.3 (which I'm using in my project) to Slate 0.73 (any example in https://www.slatejs.org/examples/).

Step 2 (typing any letter on your keyboard) can be replaced with "pasting any text from your clipboard".

**Comment by dylans** [comment]
One additional note, the issue occurs when the selection starts at the first character in a block and the selection spans blocks (e.g. doesn't need to include all text in the document). It's not an issue if the selection starts at the second character or beyond.

**Comment by dylans** [comment]
I believe this is fixed in the latest release. Please verify and close @iliaznk

**Comment by tmadeira** [comment]
Thank you, @dylans. I just upgraded to Slate 0.73.1 and the issue seems to be fixed.

**Comment by iliaznk** [comment]
Works as expected now. Thank you! Closing the issue.
