### ISSUE TITLE
Add font selector

### ISSUE THREAD

**Issue by konfilios** [ianstormtaylor/slate#4854]
**Problem**
Currently there's no way to specify a font in the editor. All text is rendered in the same font.

**Solution**
There could be a font selector in the toolbox, where a dropdown list of (system?) fonts is displayed. When the user clicks the specified font, it's applied to the currently active selection.

**Comment by JustinBeaudry** [comment]
Just set the font-family via CSS

**Comment by JustinBeaudry** [comment]
You could also just create a plug-in.

**Comment by dylans** [comment]
Plate has various Slate plugins for font family, size, color, etc. I'd suggest looking at those if interested, https://plate.udecode.io/docs/plugins/font .
