### ISSUE TITLE
Implementing uploads?

### ISSUE THREAD

**Issue by wmertens** [ianstormtaylor/slate#486]
I would like to have drag & drop image uploads. Suppose I already have a React-based solution for drag & drop image upload, and it would result in a URL after the upload, how would I go about making a plugin that allows the same in Slate?

**Comment by SamyPesse** [comment]
Take a look at https://github.com/ianstormtaylor/slate-drop-or-paste-images

@ianstormtaylor had already everything planned for you 🙌

**Comment by wmertens** [comment]
W00t awesome! I missed it while reading the list of plugins :( Maybe this plugin deserves specific mention at https://github.com/ianstormtaylor/slate#plugins ?
