### ISSUE TITLE
Bad UX / bug when we triple click on text and type over it

### ISSUE THREAD

**Issue by nitishrddy** [ianstormtaylor/slate#4862]
**Description**
If we triple click on a block, the whole block gets selected (this is expected). If we start typing, instead of the text in the current block being replaced with the new text, the text in current block gets deleted and the new text appear at the start of the next block. The expectation is that the text appears in the same block instead of the next. 

One observation: At this point of time the anchor is {path: [x,0], offset: 0} and focus is {path: [x+1,0], offset: 0}. The same bug reproduces when we drag the mouse manually and select text until the anchor and focus are similar to the above anchor and focus or vice-vera.

This is reproducible in the Slate examples too. Sharing a recording of it below

**Recording**
(https://youtu.be/Xc7eMPxCNek)

**Sandbox**

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext
2. Triple Click with mouse on any text in the first block
3. Start typing

**Expectation** 
Expected the text to appear in the first block instead of the second.

**Comment by jameshfisher** [comment]
I agree that this is undesirable behavior, but I strongly disagree with the breaking change in https://github.com/ianstormtaylor/slate/pull/4868.

The behavior you're seeing here is actually Chromium's default contenteditable behavior; not a Slate bug. See demo: https://codepen.io/jameshfisher/pen/dyewjee

Note this does not happen in Firefox. I believe it's Firefox's behavior that we all expect and want.

The precise difference is that [Chrome triple-click creates a "hanging range"](https://docs.slatejs.org/api/nodes/editor#editor.unhangrange-editor-editor-range-range-options-greater-than-range). We should consider that the underlying bug, and push Chromium to fix the bug.

Relevant Chromium bug reports:

* https://bugs.chromium.org/p/chromium/issues/detail?id=862090
* https://bugs.chromium.org/p/chromium/issues/detail?id=59371

If we decide to fix this browser inconsistency in Slate, the correct fix cannot be to change the `insertText` behavior (as was done in https://github.com/ianstormtaylor/slate/pull/4868). This is a major breaking change, and is working around Chrome's bug at the wrong time. The correct fix would be to fix up the selection at triple-click time, presumably by using something like `unhangRange`.
