### ISSUE TITLE
"Cannot resolve from DOM point" error on onDomSelectionChange for readonly void elements

### ISSUE THREAD

**Issue by heyitsaamir** [ianstormtaylor/slate#4886]
**Description**
If you click / select a void element when the editor is in readonly mode, it throws a "Cannot resolve from DOM point" error.

**Recording**

https://user-images.githubusercontent.com/48929123/158026541-719c5c25-dde7-495c-907b-ab5ae2748d79.mov

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-g486e7?file=/index.js

**Steps**
To reproduce the behavior:
1. Create a new type of element that's void.
2. Put your editor in reaadonly mode
3. Click on the read only void element.

**Expectation**
Shouldn't crash.

**Environment**
- Slate Version: [e.g. 0.71.0]
- Slate React: 0.72.8
- Operating System: [macOS]
- Browser: [Firefox]

**Context**
I have a local fix in draft - https://github.com/ianstormtaylor/slate/pull/4887
More context: I took the image example and tried to reproduce it here: https://codesandbox.io/s/slate-reproductions-forked-g486e7?file=/index.js. It doesn't. The reason being that the image example has the `contentEditable` set to true. So I guess, the question then becomes, should all `void` elements set `contentEditable` to false?

**Comment by ahoisl** [comment]
I just tried to reproduce your problem to see how it differs from my original problem with readonly void element (#4726) and noticed that the error also happens if the editor is _not_ readonly:

https://codesandbox.io/s/slate-reproductions-forked-k8hnlz

**Comment by heyitsaamir** [comment]
> I just tried to reproduce your problem to see how it differs from my original problem with readonly void element (#4726) and noticed that the error also happens if the editor is _not_ readonly:
> 
> https://codesandbox.io/s/slate-reproductions-forked-k8hnlz

Thanks @ahoisl ! Seems like if we set `contentEditable` to false, then the problem goes away. (Added this in the original issue). I wonder if that's the recommended approach then?

**Comment by cmmartin** [comment]
@heyitsaamir I believe it is the recommended approach. IIRC there was a Firefox bug that required this previously anyway. You can see it's been done in the examples [here](https://github.com/ianstormtaylor/slate/blob/main/site/examples/editable-voids.tsx#L71) and [here](https://github.com/ianstormtaylor/slate/blob/main/site/examples/images.tsx#L102)

**Comment by ahoisl** [comment]
> Thanks @ahoisl ! Seems like if we set `contentEditable` to false, then the problem goes away. (Added this in the original issue). I wonder if that's the recommended approach then?

Ahh, yeah, we use `contentEditable=false` in our void elements, too, but we might just have copied that from the examples 😄

**Comment by heyitsaamir** [comment]
@cmmartin thank you! If that's the case I'll close this issue with that being the recommendation.

Also @ahoisl thanks for your help here :)
