### ISSUE TITLE
Triple click selection and copy&paste in read-only mode 

### ISSUE THREAD

**Issue by irynakoshynska** [ianstormtaylor/slate#4897]
**Description**
In Chrome in read-only mode, when we use triple-click selection and try to copy and paste: only one word is copied instead of the entire paragraph

**Recording**
https://user-images.githubusercontent.com/66263028/158982608-bada507e-2249-4b70-9c6c-906f687ee36a.mov
![Screen Recording 2022-03-18 at 10 59 34](https://user-images.githubusercontent.com/66263028/158985047-18f8c57d-0c58-4cef-bb2a-6c6630237fb7.gif)

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/read-only
2. Triple-click on the paragraph
3. Copy & Paste
5. Error: only one word is copied instead of entire paragraph

**Environment**
- Slate Version: 0.72.8
- Operating System:  iOS
- Browser: Chrome

**Comment by sowes** [comment]
I too have encountered this problem! It's preventing our users from quickly copying text in our social feed. +1 for visibility!
