### ISSUE TITLE
Editor missing from documentation

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#491]
I noticed this before and thought it was a temporary snafu but since it's been missing for a while now, I thought I'd mention that `Editor` is missing from the documentation here:

https://docs.slatejs.org/

I'm pretty sure it was there before under the "COMPONENT REFERENCE" section which currently has no children.

![image](https://cloud.githubusercontent.com/assets/469587/20844849/c5c19d00-b876-11e6-90dc-7066994ecaa5.png)

**Comment by ianstormtaylor** [comment]
Good catch, fixed!
