### ISSUE TITLE
refactor transform tests to include selection in fixture

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#492]
Right now in the transform tests the fixtures are YAML files that contain just the input and out `Document`. And the `Selection`-specific logic and assertions happen inside `index.js`. Instead, it would be nice if we could write the selections just as YAML as well in the same `input.yaml` and `output.yaml` files.

We would need to ensure that that the `key` for each node was properly specified in the document. And it might be necessary/good to use `resetKeyGenerator` before every test, to ensure that the keys are predictable.

**Comment by ianstormtaylor** [comment]
Actually when we do this, I think we could even combine the test fixtures into a single `index.js` file with separate exports. So that we could move from three files, like:

```js
export default function (state) {
  const { document, selection } = state
  const texts = document.getTexts()
  const first = texts.first()
  const range = selection.merge({
    anchorKey: first.key,
    anchorOffset: 0,
    focusKey: first.key,
    focusOffset: 0
  })

  return state
    .transform()
    .setBlockAtRange(range, { type: 'code' })
    .apply()
}
```
```yml
nodes:
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        text: word
```
```yml
nodes:
  - kind: block
    type: code
    nodes:
      - kind: text
        text: word
```

To a single file, like:

```js
export const transform = (state) => {
  return state
    .transform()
    .setBlockAtRange(state.selection, { type: 'code' })
    .apply()
}

export const input = `
  document:
    nodes:
      - kind: block
        type: paragraph
        nodes:
          - kind: text
            text: word
  selection:
    anchorKey: "1"
    anchorOffset: 0
    focusKey: "1"
    focusOffset: 0
`

export const output = `
  document:
    nodes:
      - kind: block
        type: code
        nodes:
          - kind: text
            text: word
  selection:
    anchorKey: "1"
    anchorOffset: 0
    focusKey: "1"
    focusOffset: 0
`
```

**Comment by SamyPesse** [comment]
I like the idea of having the selection in the YAML, but I think we should keep using 2 different files (`index.js`, `input.yaml`, `output.yaml`).

It makes it easy to edit the YAML (especially for large tests) in a code editor.

**Comment by ianstormtaylor** [comment]
Done now with the JSX!
