### ISSUE TITLE
Easy repro crash when triple clicking

### ISSUE THREAD

**Issue by scottlu** [ianstormtaylor/slate#4930]
**Description**

Very easy to reproduce crash. Simply triple click in an area of Editable not occupied by a child element. See Context below for the lines of code that are causing it.

The bug was introduced very recently, 4/4/22, PR #4914, meant to fix issue #3871

**Recording**

https://user-images.githubusercontent.com/82301/162357857-514f3563-a256-45e2-ab11-21f6c019ab0c.mp4

**Sandbox**

https://codesandbox.io/s/slate-reproductions-forked-j0e6qq

**Steps**
To reproduce the behavior:
1. Open the sandbox
2. Ensure the sandbox is using slate 0.76.1, slate-react 0.76.1, and slate-history 0.66.0
3. Triple click in the Editable's padding area, not on the child element
4. Crash

**Expectation**

Not to crash.

**Environment**
- Slate Version: slate 0.76.1, slate-react 0.76.1, slate-history 0.66.0 
- Operating System: [Debian Bullseye]
- Browser: [Chrome]

**Context**

The problem is the TRIPLE_CLICK code merged on 4/4/22, PR #4914, in slate-react/src/components/editable.tsx, line ~1503. In the case of triple clicking on the Editable component itself, the node returned from toSlateNode is the editor node, and the path returned from findPath is of zero length. The code inside the TRIPLE_CLICK conditional appears to not take into account the the node is the editor, or that the path length may be zero.

**Comment by benbrandt** [comment]
Also seeing this behavior

**Comment by zijizhu** [comment]
Yeah I can also reproduce this. Any potential fix?

**Comment by JosNun** [comment]
Is this fixed by #4944?

**Comment by BitPhinix** [comment]
Yes, this can be closed
