### ISSUE TITLE
Why can't we use tab to indent text?

### ISSUE THREAD

**Issue by max4all** [ianstormtaylor/slate#4938]
**Problem**
Tab key should indent text, if you are in a text editor.

**Solution**
I want the tab key back to where it belongs.

**Comment by horacioh** [comment]
as far as I know, if you want the tab key to indent text you need to handle that behavior yourself. that's what I did on my editor since tab key means something specific to our data layer. I'm sure it should mean something to yours too!

**Comment by max4all** [comment]
Can we do that? Ok, I'll try that. Is there any hint you can share on this?

**Comment by horacioh** [comment]
you can listen to the onKeyDown event in the editor and check gor the tab key. then you can do whatever you need to do to the slate tree inside that event.

you can check how Plate does this inside the list plugin: https://github.com/udecode/plate/blob/main/packages/nodes/list/src/onKeyDownList.ts
