### ISSUE TITLE
Slate sample code got an error with double or triple click

### ISSUE THREAD

**Issue by beyond-life-flux** [ianstormtaylor/slate#4941]
**Description**
Sample code didn't work when I double click editable content, I got error info 
```
undefined is not an object (evaluating 'path.length')
```
<img width="507" alt="image" src="https://user-images.githubusercontent.com/30022286/163120400-f2a05851-627b-4416-88fa-03e0f547d68b.png">

<img width="572" alt="image" src="https://user-images.githubusercontent.com/30022286/163120500-8584c457-a3e9-4bee-a5aa-a548310009f1.png">

Here is my custom editor code: 
```jsx
import React, { useMemo, useCallback } from 'react'
import { createEditor } from 'slate'
import { Slate, Editable, withReact } from 'slate-react'
import styles from './editor.less';

const value = [
  {
    type: 'paragraph',
    children: [
      {
        text: '',
      },
    ],
  },
]

const MyEditor = () => {
  const editor = useMemo(() => withReact(createEditor()), [])
  const renderElement = useCallback(({ attributes, children, element }) => {
    switch (element.type) {
      case 'quote':
        return <blockquote {...attributes}>{children}</blockquote>
      case 'link':
        return (
          <a {...attributes} href={element.url}>
            {children}
          </a>
        )
      default:
        return <p {...attributes}>{children}</p>
    }
  }, [])

  const onClick = event => {
    console.log(event)
  };

  const onDrop = event => {
    console.log(event)
    return true;
  };

  const onDragStart = event => {
    console.log(event)
    return false;
  };
  return (
    <div className={styles.wrapper}>
      <Slate editor={editor} value={value}>
        <Editable
          renderElement={renderElement}
          onClick={onClick}
          onDrop={onDrop}
          onDragStart={onDragStart}
          className={styles.editor}
          placeholder="Type some content here..."
        />
      </Slate>
    </div>
  )
}
export default MyEditor;
```

**Recording**
A GIF or video showing the issue happening. (If you don't include this, there's a very good chance your issue will be closed, because it's much too hard to figure out exactly what is going wrong, and it makes maintenance much harder.)

https://user-images.githubusercontent.com/30022286/163124639-bcdddc78-b461-4ecd-a5b1-60bc8f41b0dc.mp4

**Sandbox**
A link to a sandbox where the error can be reproduced. (You can start from the base sandbox here: https://codesandbox.io/s/slate-reproductions-c7gyg or refer to the Slate website too.)

**Steps**
To reproduce the behavior:

**Expectation**
A clear and concise description of what you expected to happen. (Often it's helpful to test out the behavior of other editors like Google Docs, Medium, Notion, etc. to see how they handle the same issue.)

**Environment**
- Slate Version: [e.g. 0.59]
- Operating System: [e.g. iOS]
- Browser: [e.g. Chrome, Safari]
- TypeScript Version: [e.g. 3.9.7 - required only if

 it's a TypeScript issue]

**Context**
Add any other context about the problem here. (The fastest way to have an issue fixed is to create a pull request with working, tested code and we'll help merge it. Slate is solving a pretty complex problem, and we can't do it without active contributors, so thank you so much for your help!)

**Comment by horacioh** [comment]
do you believe is related to #4933 ?
