### ISSUE TITLE
Checkbox example won't work in JS without onChange prop passed to <Slate />

### ISSUE THREAD

**Issue by pbenmoser4** [ianstormtaylor/slate#4947]
https://github.com/ianstormtaylor/slate/blob/5160efeea492fa52c462e0a9f14189b5dc18c48e/site/examples/check-lists.tsx#L76

This checkbox example was not working for me, with error `slate.tsx:51 Uncaught (in promise) TypeError: onChange is not a function` thrown when trying to delete any text (not thrown on adding new text).

Adding in an `onChange` prop to the `<Slate/>` component fixed the issue, with everything now working as expected. I just passed in a trivial `{()=>{}}` function.

**Comment by horacioh** [comment]
hey @pbenmoser4 !
thanks for adding this issue. One question, can you share your machine's system in which the example did not work?
I just ran the example on my machine (mac, chromium) and it is working correctly.

please let us know if this is in the actual slate website or where also with the versions in which this error appears.

thanks!

**Comment by pbenmoser4** [comment]
Sure @horacioh - I'm running Mac Monterey (12.2.1) and the example is throwing the error in Chrome - Version 99.0.4844.74 (Official Build) (x86_64). I just tried it in brave browser as well (both running on localhost) and the same error is thrown with inability to delete, fixed by adding the `onChange` handler.

**Comment by pbenmoser4** [comment]
Sorry didn't read the second half of your response - this is not the website, this is in my own `.js` file (which is just a copy of the example) using: 
```"slate": "^0.73.1",
    "slate-history": "^0.66.0",
    "slate-react": "^0.74.0"```

**Comment by BitPhinix** [comment]
This is expected as the onChange prop was made optional in slate-react 0.76 (https://github.com/ianstormtaylor/slate/releases/tag/slate-react%400.76.1). So you'll either have to update slate and slate-react or pass an onChange prop.

**Comment by pbenmoser4** [comment]
Thanks @BitPhinix. Closing this issue.
