### ISSUE TITLE
speed up tests

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#495]
The current test setup takes a long time to run. I haven't investigate, but I'm sure there a bunch of different things we could do to speed it up, potentially including trying out a different test runner.

**Comment by SamyPesse** [comment]
One solution might be to avoid the build step, by using `--compilers js:babel-register` and including slate from the `src` directory instead of `lib`.

This is what we are doing at GitBook for testing projects build with `babel` (ex: all of our slate plugins).

**Comment by ianstormtaylor** [comment]
Ah, I'm actually already using `npm run tests` (not `test`) with the watcher running, so that means that it doesn't have to build every time, but it's still more than 10 seconds to finish the suite on my computer.

**Comment by thesunny** [comment]
I wonder if we shouldn't also add arguments to `npm run tests` to selectively only run the tests that we're interested in at the moment.

While creating a unit test for a new transform, I commented out all the tests that weren't relevant to the unit test I was currently writing so I could get faster feedback.

Would have been nicer if I could just `npm run tests transform`, for example, to run all the tests with `transform` in the `it` or `describe`. Even better might be to tie that to a watch so that whenever I made code or unit test changes, the tests would rerun themselves.

There are probably ways to do this manually but it wasn't worth the effort for me to do it for my one-time use. Might be valuable if everybody could use the feature though.

**Comment by ianstormtaylor** [comment]
Migrating to Jest and changing the tests to use `async/await` when reading from the filesystem brought the execution time of `npm run tests` from 30 seconds to 5 seconds on my machine!

**Comment by Soreine** [comment]
I'm not fond of the new test runner. On my machine, it brought `npm run tests` from 6s (mocha) to 13s (jest). 

It became less verbose though, which is nice I guess. But in case of errors, we lost the JSON diff in the process. This is what get printed with Mocha:

```
  548 passing (6s)
  1 failing

  1) transforms at-range splitBlockAtRange() depth:

      AssertionError: { nodes: [ { kind: 'block', type: 'paragraph', nodes: [Object] } ] } === { nodes:
   [ { kind: 'block', type: 'paragraph', nodes: [Object] },
     { kind: 'block', type: 'paragraph', nodes: [Object]
      + expected - actual

                   }
                 ]
                 "type": "paragraph"
               }
      +      ]
      +      "type": "paragraph"
      +    }
      +    {
      +      "kind": "block"
      +      "nodes": [
               {
                 "kind": "block"
                 "nodes": [
                   {
```
Now with Jest:

```
 FAIL  test/transforms/index.js (5.205s)
  ● transforms › at-range › splitBlockAtRange() › depth

    Error
      AssertionError: { nodes: [ { kind: 'block', type: 'paragraph', nodes: [Object] } ] } === { nodes:
         [ { kind: 'block', type: 'paragraph', nodes: [Object] },
           { kind: 'block', type: 'paragraph', nodes: [Object]
```

Drop the 🎤

**Comment by ianstormtaylor** [comment]
Haha yup I agree with you @Soreine for the error handling. Unfortunate that Jest doesn't handle the native assert better. I opened an issue but it'll probably be a while before it's fixed. 

For the speed, was that after multiple Jest runs? It caches a bunch of stuff I believe so the runs after the first in should be faster. Let me know if not though. 

Looking into this today as I add tests for the event ha doing behavior. Might try Ava as well, or fall back to Mocha again. But open to ideas.

**Comment by ianstormtaylor** [comment]
What's your machines specs? Wonder why mine is so slow 😬

**Comment by Soreine** [comment]
I don't know why yours is so slow, I am running it on a recent MacBook though.

```
MacBook Pro (Retina, 13-inch, Early 2015)
Processor: 2.7 GHz Intel Core i5
Memory: 8 GB 1867 MHz DDR3
```
