### ISSUE TITLE
Cursor keeps jumping to unexpected position and number is being replaced with unexpected text.

### ISSUE THREAD

**Issue by antonbakinowsky** [ianstormtaylor/slate#4954]
**Description**
Cursor jumps on wrong position when typing special symbols or numbers together ( **(**, **+**, **7** on the video).

- from 27 sec in the video - when typing **(+7** then it changes to **((+** and cursor is moved to after first bracket. It is difficult to see in the video so i gif where i pause/unpause to caught the issue
![slate-seven-replaced-with-bracket](https://user-images.githubusercontent.com/10063600/164206413-a01ca519-2a2e-4b9d-bf18-92bd964cef4e.gif)
- from 46 sec in the video - after typing **7** i press enter to move on the next line. Cursor have been moved to next line but **7** from prev line was deleted. Also attach gif with slower repro.
![slate-seven-is-deleted-after-moving-to-next-line](https://user-images.githubusercontent.com/10063600/164209266-693c3442-dc0b-4e02-92ac-5b884877cbca.gif)
- from 50 sec typing **hello 7** is chnaged to **hhello** and cursor is placed after first **h**
- from 53 sec manually moving cursor to the end of the line moved cursor back to is prev position

**Recording**

https://user-images.githubusercontent.com/10063600/164204891-b8835aea-c967-4f53-b3ee-1f8f59124589.mp4

**Sandbox**
[https://www.slatejs.org/examples/richtext](https://www.slatejs.org/examples/richtext)

**Steps**
Introduced in the video and gifs above.

**Expectation**
Typing **7** is not replaced with something else. Moving cursor to the end of the line actually moves cursor there instead of returning it back to its prev position.

**Environment**
- Slate Version: from slate.js examples
- Operating System: Android 12
- Browser: Chrome 100.0.4896.127

**Comment by TrySpace** [comment]
I have similar issues with android input, especially when typing quickly.

For example typing Enter will often revert the cursor to the last position. Or sometimes pressing Enter will unfocus the editor/hide the keyboard...

**Comment by antonbakinowsky** [comment]
fixed by #4988
