### ISSUE TITLE
Bug with selection inline / inline void in 0.16.x

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#496]
The changes of 0.16.x (which are great 🎉 ) also added a bug when an inline contains a single inline void.

JS Fiddle to reproduce it: https://jsfiddle.net/zLa5pbd0/1/

In the JSFiddle, selecting the emoji, then pressing <kbd>Left</kbd> doesn't escape the emoji. But <kbd>Right</kbd> seems to work.  
In our application, the bug is even more important (the cursor can't escape the inline void with either <kbd>Left</kbd> or <kbd>Right</kbd>).

**Comment by ianstormtaylor** [comment]
I think this is fixed now, but there might be something else going on. Going to close, and we can re-open or open a new issue if it's a different bug.
