### ISSUE TITLE
Export standalone types for all nontrivial function parameters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ianstormtaylor/slate#4966]
**Problem**
There are quite a few `.d.ts` function types whose parameters have types that are more complex than just a primitive or union of primitives. For example, this is the start of `NodeTransforms` in `transforms/node.d.ts`:

```ts
export interface NodeTransforms {
    insertNodes: <T extends Node>(editor: Editor, nodes: Node | Node[], options?: {
        at?: Location;
        match?: NodeMatch<T>;
        mode?: 'highest' | 'lowest';
        hanging?: boolean;
        select?: boolean;
        voids?: boolean;
    }) => void;
```

Code that wants to refer to the type of `options` parameter has no easy way to do it. This is rather inconvenient in TypeScript if you have, say, a variable meant to be provided as `options`.

```ts
// What type is this?!
let options = {};

if (someCondition) {
  options.hanging = true;
}
```

**Solution**
Would you accept a PR that goes through and makes interfaces and union types for all these exported complex types, then exports them in the `slate` module?

**Alternatives**

Continuously using this kind of beast in userland:

```ts
import { NodeTransforms } from "slate/dist/transforms/node";

export type InsertNodesOptions = NonNullable<
  Parameters<NodeTransforms['insertNodes']>[2]
>;
```

**Comment by dylans** [comment]
Ha, small world… this has been on my list for a while @JoshuaKGoldberg . I would love to see a PR to fix this (and in general make parts of slate-react more extensible but that’s another topic).

**Comment by JoshuaKGoldberg** [comment]
Ha! Hello @dylans 😄! I thought "slate" for text editing sounded familiar... absolutely, I'll have a PR up soon. Thanks!
