### ISSUE TITLE
Safari paste handling and Clipboard API

### ISSUE THREAD

**Issue by dylans** [ianstormtaylor/slate#4998]
**Description**

A recent Safari update seems to have blocked all of Slate's attempts to append our syntax tree to `application/x-slate-fragment`. Previously this worked but [would exclude files](https://github.com/ianstormtaylor/slate/issues/4465).

**Sandbox**/**Steps**

Any slate example shows an empty `application/x-slate-fragment` when pasting.

**Expectation**

We can control what gets pasted. Currently we're falling back to HTML which isn't great for void elements that have behavior not contained in html.

**Environment**
- Slate Version: Any
- Operating System: macOS, probably iOS
- Browser: Safari

**Context**

We probably need to switch to the newer clipboard api for Safari, though it's annoying in that it asks for user approval. See various links in https://github.com/ianstormtaylor/slate/issues/4465#issuecomment-904567668

**Comment by IMSupperkaka** [comment]
same problem

**Comment by jdmanabat** [comment]
Currently, we are having an issue when pasting bullet and number lists in Safari. Do you think it's related to this?

**Comment by dylans** [comment]
> Currently, we are having an issue when pasting bullet and number lists in Safari. Do you think it's related to this?

What type of issue?

**Comment by jdmanabat** [comment]
> > Currently, we are having an issue when pasting bullet and number lists in Safari. Do you think it's related to this?
> 
> What type of issue?

When pasting the copied bullet or numbered lists the HTML tags are removed.

**Comment by Nikhil22** [comment]
When I paste plain text with line breaks in Safari, Slate does not honor the line breaks. End result is all one block of text.

**Comment by dylans** [comment]
Safari has progressively made the old copy/paste API less usable, a strong to push to use the newer API (which requires user consent). We need to implement that in 2023 to solve a number of problems with copy/paste in Safari.

**Comment by Nikhil22** [comment]
@dylans Sounds good. If you or the team need any help, I'm happy to contribute in any way I can.

**Comment by 12joan** [comment]
The Clipboard API doesn't require prompting for permission when writing to the clipboard from an event handler, only when reading it outside of a paste event. However, it won't work for copying `application/x-slate-fragment` data in Safari, since all major browsers only allow a limited set of data types when writing with `Clipbard.write()`. See https://webkit.org/blog/10855/.

I don't think there are any APIs that allow us to copy `application/x-slate-fragment` in Safari.
