### ISSUE TITLE
documents should be allowed to have no nodes

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#505]
This is an extreme edge case, but if a Slate document only contains a single void block node, the editor locks up and no changes can be made. This can be seen in the "Images" example on slatejs.org.

I attempted to fix this with a schema rule that added blocks before and after the void node, however this lead other issues with the node key. I also don't like that solution as it adds additional nodes that would be otherwise unnecessary.

I'm not sure the best way to fix this and I'm not totally sure this is Slate's responsibility. Just looking for some direction here.

**Comment by tyler-johnson** [comment]
Quick update, I wrote a schema rule to add a block node after the void node which satisfies me for the time being.

```js
{
  match(node) {
    return (node.kind === "block" || node.kind === "document") && !node.isVoid;
  },
  validate(node) {
    return node.nodes.size && node.nodes.last().type === "embed";
  },
  normalize(transform, node) {
    const block = Block.create({ type: "line" });
    transform.insertNodeByKey(node.key, node.nodes.size, block);
  }
}
```

I still think that attempting to delete the void node should not throw an error and that I do believe is a Slate issue.

**Comment by ianstormtaylor** [comment]
Damn, yeah I agree this is a bug. It's tricky because Slate can't get into adding a new block when the image is deleted, since it doesn't know what `type` it should add. But I'd agree that allowing the `document` to be in a state with zero nodes should be allowed.

And then it would be simpler to add a schema validation rule that inserts and empty default node whenever the document is totally empty.

I'd be open to a pull request that makes this possible!

**Comment by oyeanuj** [comment]
@skogsmaskin @ianstormtaylor With the PR #622, I am seeing the following error when I have an empty object (or an object with empty node array) as the initial state: 

```
error given was: TypeError: Cannot read property 'key' of undefined
[1]     at Object.deserializeDocument (node_modules/slate/lib/serializers/raw.js:101:18)
```

The error is thrown here:
https://github.com/ianstormtaylor/slate/blob/master/src/serializers/raw.js#L64

**Comment by skogsmaskin** [comment]
@oyeanuj I don't think that is related to this pull request. To me it sounds like something goes wrong when the deserializer tries to deserialize your object into a Slate document and that is before it is even put into Slate i guess. The #622  only deals with a situation where you have a non-empty document and it allows you to delete all it's nodes (which was not possible before).
