### ISSUE TITLE
add schema documentation

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#506]
The Slate documentation seems to be missing good Schema information. I did notice [docs/guides/schemas.md](https://github.com/ianstormtaylor/slate/blob/master/docs/guides/schemas.md) however it seems to be incomplete and outdated.

Updated docs would be wonderful as I am still trying to understand them. They seem so powerful and useful, it's a shame most users won't know they are available.

Thanks!

**Comment by ianstormtaylor** [comment]
Hey @tyler-johnson, thanks for catching that. The schema was missing from the docs sidebar, but I've just added it now, so you can check out the docs we do have here: https://docs.slatejs.org/reference/models/schema.html — hopefully that helps!
