### ISSUE TITLE
editor.deleteBackwards('word') has an inconsistent effect with math symbols.

### ISSUE THREAD

**Issue by JohnCosta27** [ianstormtaylor/slate#5072]
**Description**
If you use editor.deleteBackwards with the 'word' option, and you have the symbols (^ or +), then the editor will go past them, but it will not do this with (*, - or /).

**Recording**
https://user-images.githubusercontent.com/69081170/182817260-2148a00b-ee7d-4fdf-9ebb-328f5e940886.mp4

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-qm0vzv?file=/index.js

**Steps**
Open the sandbox, and press ctrl + b to delete backwards on each sentence.

**Expectation**
I expected all of them to be treated equally, for me it made most sense when the word was deleted until it met the maths symbols, so the + and ^ deleting beyond them seems inconsistent.

**Environment**
- Slate Version: Latest (0.82)
- Operating System: Linux
- Browser: Chrome

**Comment by dylans** [comment]
The implementation can be found at https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/utils/string.ts and follows the unicode guidelines from https://www.unicode.org/reports/tr29/#Default_Grapheme_Cluster_Table and https://unicode.org/reports/tr29/tr29-9.html#Word_Boundaries .

So I think the current definition of word is following the spec unless I'm misunderstanding which is entire possible.

Assuming my understanding is correct, we could consider an additional matching mode to not include math symbols in the definition of a word.

**Comment by JohnCosta27** [comment]
> The implementation can be found at https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/utils/string.ts and follows the unicode guidelines from https://www.unicode.org/reports/tr29/#Default_Grapheme_Cluster_Table and https://unicode.org/reports/tr29/tr29-9.html#Word_Boundaries .
> 
> So I think the current definition of word is following the spec unless I'm misunderstanding which is entire possible.
> 
> Assuming my understanding is correct, we could consider an additional matching mode to not include math symbols in the definition of a word.

Ah, I see - I wasn't aware of this, thank you for the reply.

The additional mode would be great :)

**Comment by dylans** [comment]
> Ah, I see - I wasn't aware of this, thank you for the reply.
> 
> The additional mode would be great :)

Probably the most challenging part would be defining the rules (as you can see from the code for the word mode). If you want to outline the rules, it should be a pretty easy PR.
