### ISSUE TITLE
SOLUTION : Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":18}"

### ISSUE THREAD

**Issue by JaganJonnala** [ianstormtaylor/slate#5073]
**I am getting this issue while using slate react. Unable to spellcheck and unable to save the correct spell. Went through so many blogs, slate related issues like below
https://github.com/ianstormtaylor/slate/issues/3145.

After spending and trying so many solutions nearly 24 hours. I have fixed the error part and the able to save the correct spelled word also for my application**

my packages : 

```
    "slate": "^0.58.4",
    "slate-history": "^0.58.4",
    "slate-hyperscript": "^0.59.0",
    "slate-react": "^0.58.4",
```

    
    and Editor code is as simple as that they provided from Slate.
   
    Wooooohahh..! Here is the solution for it:
    
   
```
const onInput = event => {
    setValue([
      {
        type: 'paragraph',
        children: [{ text: event?.currentTarget?.textContent }],
      },
    ]);

    const point = {
      path: [0, 0],
      offset: event?.currentTarget?.textContent?.length,
    };
    editor.selection = { anchor: point, focus: point };
  };
```

  
  
  
   ```
<Editable
          placeholder={placeholder}
          renderElement={renderElement}
          renderLeaf={renderLeaf}
          onKeyDown={handleKeydown}
          onInput={onInput}
        />
```

If you find this useful and your issue not resolved still, then you can use it.
@jessekelly881 , @DamareYoh , @ianstormtaylor, @gotoprototype, @Josh-McFarlin, @antonstjernquist, [hannahblair](https://github.com/hannahblair) , [arel](https://github.com/arel) , [cameracker](https://github.com/cameracker),

**Comment by palanand** [comment]
@JaganJonnala  it's really useful and resolve the current issue in DOM point
