### ISSUE TITLE
Previously working Slate app spontaneously broken from type mismatch

### ISSUE THREAD

**Issue by groneman7** [ianstormtaylor/slate#5077]
**Description**
I have been using Slate for a few months now. When I first started, I followed the Walkthroughs (adjusting for TypeScript as needed), and my apps worked fine. As I have continued adding on, I have made perfectly working versions of my app with Slate; however, I am now getting an error I have never seen before.

As per the Walkthrough, we initialize an editor as follows:
`const [editor] = useState(() => withReact(withHistory(createEditor())));`

Up until today, this has worked perfectly. However, I now get the following error:
```
Argument of type 'BaseEditor & HistoryEditor' is not assignable to parameter of type 'ReactEditor'.
  Type 'BaseEditor & HistoryEditor' is missing the following properties from type 'ReactEditor': insertData, insertFragmentData, insertTextData, setFragmentData, hasRange ts(2345)
```
Additionally, I have a separate file with my custom elements and text, as well as the TypeScript requirement:
```
declare module 'slate' {
    interface CustomTypes {
        Editor: BaseEditor & ReactEditor & HistoryEditor;
        Element: CustomElement;
        Text: CustomText;
    }
}
```

I also attempted to move this declare statement into the file with the <Slate> component itself, and that did not help.

**Environment**
- Slate Version: 0.81.1
- Operating System: macOS Monterey (12.5)
- Browser: Chrome
- TypeScript Version: 4.7.4

**Comment by latviancoder** [comment]
I can confirm that adding `HistoryEditor` to the mix breaks all the types.

**Comment by PangYiMing** [comment]
please try the code below
```
withHistory(withReact(createEditor()))
```
