### ISSUE TITLE
HMR in vite breaks Editable, cannot find a descendant at path [0]

### ISSUE THREAD

**Issue by Twiggeh** [ianstormtaylor/slate#5093]
**Description**
When triggering a HMR, slate's Editor component crashes.

**Recording**

https://user-images.githubusercontent.com/23149166/185919311-71964f48-e77c-4ec5-b73d-49113aa271a5.mp4

**Sandbox**
https://github.com/Twiggeh/slatebugreport

**Steps**
To reproduce the behavior:
# RUN

1. pnpm install
2. pnpm dev

# REPRODUCE

1. Open "Editor.tsx"
2. Trigger a HMR reload, change background to green on Toolbar
3. Error Boundary will be hit, originating in the EDITABLE component

**Expectation**
It shouldn't crash on HMR

**Environment**
- slate: [0.82.0]
- slate-history: [0.66.0]
- slate-react: [0.82.0]
- Operating System: [Linux]

**Comment by dylans** [comment]
@Twiggeh  I was going to perhaps ask in a snarky manner why this was a Slate problem and not a Vite problem, but seeing the obvious typo fixed in the PR, thanks for looking into this and giving me one less reason to be snarky today.
