### ISSUE TITLE
onChange event of Editable not working.

### ISSUE THREAD

**Issue by boyaq** [ianstormtaylor/slate#5134]
**Description**
fresh install of slate with react, everything is perfect other than onChange event is not working.

onKeyDown is working like a charm.

**Recording**
see it in Sandbox plz. 

**Sandbox**
[link of sandbox](https://codesandbox.io/s/quizzical-shape-g2hfym)

**Steps**
To reproduce the behavior:
1. create a new react app with create-react-app
2. install slate and slate-react `yarn add react react-dom`
3. copy paste the code in https://docs.slatejs.org/walkthroughs/01-installing-slate 
5. adding onChange by pasting the code in https://docs.slatejs.org/walkthroughs/06-saving-to-a-database
6. onChange not firing at all

**Expectation**
should fire onChange event to get the value of the editor

onKeyDown is working like a charm.

**Environment**
- Slate Version: [0.82.1]
- React Version: [18.2.0]
- Operating System: [osX catalina 10.15.7]
- Browser: [Chrome 104.0.5112.101]

**Context**

**Comment by zhyd1997** [comment]
@boyaq 

`onChange` event handler should be at `Slate` props not `Editable`.

**Comment by boyaq** [comment]
Thank u so much, and so sorry for the simple question, I don't know how i missed that.  really appriciate ur help~

**Comment by boyaq** [comment]
Thank u so much, and so sorry for the simple question, I don't know how i missed that.  really appriciate ur help~

**Comment by zhyd1997** [comment]
You're welcome, I encountered the same problem today, just posted the solution here.
