### ISSUE TITLE
ReactEditor.focus places the caret at the wrong position

### ISSUE THREAD

**Issue by mateuspiresl** [ianstormtaylor/slate#5169]
**Description**
`ReactEditor.focus` places the caret at the wrong position. Seems that Slate knows the correct position of the caret, at least internally, because a call to `editor.insertText` inserts the text at the correct position.

**Recording**

https://user-images.githubusercontent.com/6335577/198074164-7b025c9b-1831-49c5-a338-60a4ca73b0da.mov

**Sandbox**
Slate v0.84.0: https://codesandbox.io/s/slate-focus-bug-v0-84-0-z721fj
Slate v0.58.0: https://codesandbox.io/s/slate-focus-bug-v0-58-0-xtlz36

**Steps**
To reproduce the behavior:
1. Click at the end of the line to gain focus there
2. Click outside the editor to loose focus
3. Call `ReactEditor.focus` (by clicking on the button "Focus" in the sandbox)
4. See the caret at the beginning of the line

**Expectation**
The caret should have been placed at the end of the line.

**Environment**
- Slate Version: 0.84.0 (and also 0.58.0)
- Operating System: macOS Big Sur 11.6
- Browser: Chrome Version 106.0.5249.103 (Official Build) (arm64)

**Context**
It seems to be doable because calling focus on Draft.js would place the caret at the correct position. I'm currently switching from Draft.js to Slate.

**Comment by mateuspiresl** [comment]
Is this focus behavior above expected on the `ReactEditor.focus` method? If so, I can create a PR for that. I still have to work on Firefox to find what's wrong with `editor.insertText`.

**Comment by mateuspiresl** [comment]
The issue I mentioned about the `editor.insertText` is unrelated to this issue. The following sandbox fix both but I will create another issue for the unrelated one.

Sandbox: https://codesandbox.io/s/slate-focus-simple-alternative-9su7gr?file=/index.js.

Seems that Firefox doesn't clear its selection on blur, so changing the content of the contenteditable when it isn't focused (calling `editor.insertText`) makes the DOM fire a selection update. The problem is that this selection update is placed at the beginning of the document.

To fix that, I created a hook to listen to focus changes on the editor and clear the DOM selection on blur. It can be found at `./useBlurResolver` in the sandbox.

The solution for `ReactEditor.focus` is still the same and can be found at `./focusEditor.js` in the sandbox.

**Comment by VictorBaron** [comment]
IMO it should indeed move the caret to the current selection.
Or at least have an option to chose that behavior.

**Comment by cvalarida** [comment]
@mateuspiresl I also expected it to move the caret to the current selection. I've beating my head against this for three days now. What I had was _kind_ of working, but your solution works like a dream.

I did change it a little for my use case, though. For posterity, I did this:
```ts
const previousLocation = editor.selection ? Editor.rangeRef(editor, editor.selection) : null;

// ...
// Code to open a command palette modal which may mutate the text
// (e.g. format text by splitting nodes to add marks)
// ...

// When closing the command palette, refocus on the editor at the previous location,
// but at the new Range because the editor may have been mutated.
if (previousLocation?.current) {
  const editorEl = ReactEditor.toDOMNode(editor, editor);
  const domRange = ReactEditor.toDOMRange(
    editor,
    previousLocation.current
  );
  // Using findDocumentOrShadowRoot instead of window.
  // Not sure if that's overkill, though. :shrug:
  const root = ReactEditor.findDocumentOrShadowRoot(editor);
  if (root instanceof Document) {
    const domSelection = root?.getSelection();
    domSelection?.removeAllRanges();
    domSelection?.addRange(domRange);
    editorEl.focus();
  }
}
if (previousLocation) previousLocation.unref();
```
