### ISSUE TITLE
History.isHistory/HistoryEditor.isHistoryEditor now incorrectly computed

### ISSUE THREAD

**Issue by jacobcarpenter** [ianstormtaylor/slate#5177]
After seeing  #4717 might have addressed some selection-related history issues I was encountering, I upgraded to `"slate-history": "^0.85.0-2022101122024"` to try things out.

That release did improve cursor position-related history state! 🎉 ... But after making a real change in the editor, my conditionally rendered undo/redo controls disappeared. 😕 

After debugging a bit, it looks like `HistoryEditor.isHistoryEditor` (which depends on `History.isHistory`) no longer computes the correct value.

Specifically, `History`'s `undo` and `redo` properties are now `Batch` arrays, but the following check expects them to be operation lists:

https://github.com/ianstormtaylor/slate/blob/469bec3d040f6272d5066b94cc827c1bb7272709/packages/slate-history/src/history.ts#L25-L33

It looks like 30-31 should perhaps become:

```ts
      (value.redos.length === 0 || Operation.isOperationList(value.redos[0].operations)) &&
      (value.undos.length === 0 || Operation.isOperationList(value.undos[0].operations))
```

cc @bryanph

**Comment by bryanph** [comment]
@jacobcarpenter good catch, I didn't quite think about this function when making the change. Do you want to make a PR for your suggested solution?

**Comment by jacobcarpenter** [comment]
@bryanph sure; will do!
