### ISSUE TITLE
Cannot move text cursor one line up using `Transforms.move` 

### ISSUE THREAD

**Issue by BasLee** [ianstormtaylor/slate#5184]
When I use the `Transforms.move` helper function to move the text cursor one line up, the cursor does not move one line up. Instead the cursor moves to the beginning or ending of the previous paragraph.
 
<img src="https://user-images.githubusercontent.com/3323006/200576741-c4d0962b-4a49-4607-a9a2-9a80fb525986.gif" style="display: inline-block;" width="50%">

_Recording of pressing the up arrow_

Event handler to replicate the behavior:
```
onKeyDown={(event: React.KeyboardEvent<HTMLElement>) => {
  if (event.key === 'ArrowUp') {
    event.preventDefault();
    Editor.normalize(editor, { force: true })
    Transforms.move(editor, {distance: 1, reverse: true, unit: 'line'});
  }
}}
```
(I used the normalize helper to try to fix the problems as suggested in issue https://github.com/ianstormtaylor/slate/issues/4000 )

The behavior can be seen in this [sandbox](https://codesandbox.io/s/slate-reproductions-forked-issue-5184-ci8qzl).

**Steps to reproduce**
1. Click in editor
2. Press arrow up

**Expectation**
When pressing the up arrow, I expect the text cursor to move one line up, as seen when disabling the `onKeyDown` handler in the sandbox, or when pressing the down arrow (but then in reverse :)).

**Environment**
- Operating System: linux, pop_os
- Browser: electron & chrome
- Sandbox, but also in local setup with dependencies:
```
    "slate-history": "^0.66.0",
    "slate-hyperscript": "^0.77.0",
    "slate-react": "^0.83.2",
```

**Context**
Let me know if more context is needed.

**Comment by BasLee** [comment]
Fixed the sandbox link in the issue description

**Comment by ac-amygdala** [comment]
@BasLee
Unit `line` equals to `block` in terms of slate. Slate is a programmatic editor so its selection is not a browser selection. `Transforms.move` operates with slate selection (not browser) and `slate-react` updates browser selection to correspond slate selection.

In order to jump over browser lines programatically you need to determine next browser cursor position on your own.
```typescript
onKeyDown={(event: React.KeyboardEvent<HTMLElement>) => {
  if (event.key === 'ArrowUp') {
    event.preventDefault();
    Editor.normalize(editor, { force: true })
    requestAnimationFrame(() => window.getSelection().modify("move", "backward", "line"))
  }
}}
```
Then `slate-react` will handle `selectionchange` event and will update slate selection

**Comment by BasLee** [comment]
this works great, thank you so much!
