### ISSUE TITLE
[Android Cursor Issue]The cursor automatically move while deleting text aside an inline embed void Element 

### ISSUE THREAD

**Issue by qiooi** [ianstormtaylor/slate#5192]
**Description**
Deleting the element's front text to empty,Cursor will be moved to the back of it,Deleting the back text to empty,Cursor will be moved to the front of it.

**Recording**
![动画](https://user-images.githubusercontent.com/69415032/201137252-0853d1aa-4cce-4150-a48e-cdb6a843f369.gif)

**Steps**
To reproduce the behavior:
1. Change to Android mode on the Chrome Console
2. Go to 'https://www.slatejs.org/examples/mentions'
3. Delete text

**Environment**
- user-agent: [Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36]

**Comment by clauderic** [comment]
I can confirm this is still an issue and I can consistently reproduce it 👍 Will try to spend a bit of time looking into it.
