### ISSUE TITLE
Add `externalEditing` property to `State`

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#520]
I wrote a Slate plugin to insert display style mathematical formulas in a document.
It defines a custom void block rendered as

```
<DisplayMath>
  <CodeMirror />
  <MathCanvas />
</DisplayMath>
```

A CodeMirror editor instance is used to insert the TeX source code of the formula that is rendered by the `MathCanvas` component by means of KaTeX.

When the block is not in `editMode`, the source editor is hidden. Switching to `editMode`, the CodeMirror editor is shown and, to avoid unwanted interactions, the main editor (the Slate instance) is put in `readOnly` mode.

At moment, to put the Slate editor in `readOnly` mode I use a function passed to the plugin through the `options` object. However to share the plugin it would be more appropriate to avoid forcing the user to provide such a function and to rely on a `State` transform to change the main editor `readOnly` state.

Therefore I've been thinking of adding a boolean parameter to the editor State, `externalEditing` or, simply, `readOnly`, and to put the editor in `readOnly` mode whenever one of `Editor.props.readOnly` or `State.externalEditing` is true.

What do you think?

**Comment by ianstormtaylor** [comment]
Hey @AlbertHilb, good question, I'm not sure. Could you give a few code examples to show what you mean? I feel like `readOnly` makes sense as an editor prop, and isn't inherent to the `State` itself, but I could be wrong.

Would it solve the problem to instead have a method on the `editor` object called `updateReadOnly` or something similar, which would let you set it from inside a plugin?

**Comment by Slapbox** [comment]
I think adding it to state would be useful, at least for my usage with React-Redux.

**Comment by Slapbox** [comment]
Either would be fine IMO, but props maybe makes more sense for most uses I suppose, although maybe not for mine. I'd love to be able to pass a readOnly in and disable input.

**Comment by AlbertHilb** [comment]
Hi @ianstormtaylor.

This is how I see the situation.

An editor can stay in two similar but in fact different read-only states.
To distinguish them, let me call `readOnly` the former and `locked` the ladder.

When the editor is in `raedOnly` state no edits at all can happen.
Of course, that state is triggered by components higher in the hierarchy so the right place for the related `readOnly` property is the `props` object.

When the editor is in `locked` state, instead, no edits can happen apart from those to the document node which requested the lock. Those edits are handled by the node itself possibly by means of external tools and bypassing Slate.
`locked` state is triggered by the editor itself or by its extensions (Slate plugins) therefore the related `locked` property should lay within the editor `state` object.

Both properties are to be passed down to the components used to render custom nodes because some of those can implement nested editable content that must be switched off when the editor enters read-only states.

There are several different ways to translate this idea into code, one of those
is what I propose in the PR #541.

Let me know what do you think about it.

**Comment by ianstormtaylor** [comment]
Hey @AlbertHilb thanks for expanding.

What is the reason for needing the editor to be in a "locked" state? I don't think I understand that. It seems to be like focusing the CodeMirror instance inside of a void node shouldn't inherently need the rest of the editor to be locked.

It feels like the use case is too specific to warrant inclusion in core, and that since it's handled fine by passing functions around that would be better. But that's just my impression so far. It seems pretty normal/good to pass in a function such as `onCodeMirrorEditorOpen` or whatever, and use that the set the `props.readOnly` of the editor—since even that use case sounds user-specific instead of being inherent to the plugin.

If there are problems with the nested editor conflicting with DOM events of something else, there might be a valid need to further restrict event handlers for nested nodes?

**Comment by AlbertHilb** [comment]
Hi @ianstormtaylor, thanks for your reply. :blush:

> It seems to be like focusing the CodeMirror instance inside of a void node shouldn't inherently need the rest of the editor to be locked.

I want the edits to `DisplayMath` blocks to be atomic from the Slate point of view, that is, during an edit to a `DisplayMath` block no other changes to the document must take place. If for no other reason, I believe this is needed for the sake of undo/redo history.

> It seems pretty normal/good to pass in a function such as onCodeMirrorEditorOpen or whatever, and use that the set the props.readOnly of the editor

This is how `DisplayMath` works now, there are issues though.

First of all, there is no way for nested editable content blocks to adapt to editor `readOnly` state changes. They remain editable even when editor enters read-only state (see issue #543).

If the `DisplayMath` plugin must rely on the editor `props` to put it in read-only state then to use the plugin one have to write something like:

```
class MyEditor extends React.Component {
  constructor = (props) {
    super(props)
    const setReadOnly = this.setReadOnly
    this.state = {}
    this.state.plugins = [
      DisplayMathPlugin({setReadOnly})
    ]
  }

  setReadOnly = (readOnly) => {
    this.setState({readOnly})
  }

  render = () => {
    const {plugins, readOnly}

    return (
      <Editor
        plugins={plugins}
        readOnly={readOnly}
      />
    )
  }
}
```

While the above code is perfectly fine, it seems to me a bit odd that a plugin to work must depend on a user provided function just to put the editor in read-only mode.

Anyway, if you think the use case for a `locked` state or something similar is too specific and the way to go is `readOnly` editor property, for me it's ok provided issue #543 will be fixed.

**Comment by danielmariz** [comment]
hey @AlbertHilb is your katex plugin public and open source? 
I'm looking for somethink like that
