### ISSUE TITLE
Autocorrection side effects

### ISSUE THREAD

**Issue by ghost** [ianstormtaylor/slate#521]
On MacOS 10.12.1 in Safari 10.0.1 with "Edit > Spelling and Grammar" and "Edit > Substitutions" options all `on` I was able to produce an autocorrection which seems to be tracked in the model, but leaves an artefact text node in between the managed HTML node. Please see video attached for details. At the end of the video I do a couple of UNDO and REDO to show the model states.

Observation: It seems to be relevant if text has marks or not, because without the text being bold the problem is not reproducible.

Note: I used the online demo for demonstration http://slatejs.org/#/rich-text

[Screenshot 2016-12-12 58j5o.mp4.zip](https://github.com/ianstormtaylor/slate/files/645895/Screenshot.2016-12-12.58j5o.mp4.zip)

**Comment by ianstormtaylor** [comment]
This should be fixed now!
