### ISSUE TITLE
`Editor.isVoid` asserts `value is Element` but this is not strictly true in the TypeScript sense

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#5219]
**Description**
The type signature for `Editor.isVoid` looks like

```typescript
Editor.isVoid(editor: Editor, value: any) => value is Element
```

Which asserts that `value is Element`. This is wrong though because when you make an assertion, it also guarantees the opposite. Namely, that if we call `Editor.isVoid` and it is NOT a void element, then TypeScript believes that `value` is not an `Element`; however, it can still be an `Element` that is not `void`.

Consider this code:

```typescript
if (Editor.hasBlocks(editor, element) && !Editor.isVoid(editor, element)) {
  element // the type at this point is `never`
}
```
In the code above we check if `element` has block children and that it isn't void. The `element` value in the conditional is `never` but it should be `Element`.

**Recording**
n/a

**Sandbox**
n/a

**Steps**
This should probably do the trick. Note we are fake casting to `Element` just to trigger the TypeScript issue.

```typescript
const element = {} as Element
if (Editor.hasBlocks(editor, element) && !Editor.isVoid(editor, element)) {
  element // the type at this point is `never`
}
```

**Expectation**
`Editor.isVoid` should have a return type of `boolean`.

**Environment**
- Slate Version: 0.85.0
- Operating System: n/a
- Browser: n/a
- TypeScript Version: 4.9.3
- 
**Context**
This is an easy fix. :)

**Comment by RavenColEvol** [comment]
It's not easy as I thought 😆,
I'll start of the conversation to have this issue resolved.

Problem:
Right now isVoid code is something like this
```ts
isVoid(editor: BaseEditor, value: any): value is Element {}
```
because of which what's happening is
```ts
// right now if isVoid passed indicates value is Element else not
// probably that why
const element = {} as Element
if(!isVoid()) { // this won't ever happen as we are passing it a element }
```

Right now if I try to turn isVoid return type to boolean it has side affects on multiple places.
For example
```ts
match: n => isVoid(n) && isInline(n) // here it will give type error as isVoid passing doesn't insure that the node will be of type Element, will need do `as` in isInline(n as Element)
```

This is my understanding of what's going on behind the scene, would like to get corrected if I'm getting something wrong.

@thesunny

**Comment by thesunny** [comment]
Sorry @RavenColEvol,

I should know better by now to assume something that looks like an easy fix will be an easy fix!

In fact, I can also see that if we were to fix `isVoid`, we'd probably want to fix `isInline` and `isBlock` in the same way as they also return incorrect `is` assertions. Interestingly, I notice that `hasBlocks`, `hasInlines` and `hasTexts` are typed correctly but differently which is inconsistent with `isVoid`, `isInline` and `isBlock`. Namely, the `has...` check methods take an `Element` as its input argument, and return a `boolean` with no assertion.  
  
It feels like the cleanest fix is to make `isVoid`, `isInline` and `isBlock` to be consistent with `hasBlocks`, `HasInlines` and `hasTexts` by also taking an `Element` as the input argument and returning type `boolean`. This is also probably more correct and reduces some redundancy as well because you would only do the `Element.isElement` check once.

For example, if we wanted to know that something was a `void` `block` we would do:

```
Element.isElement(node) && isVoid(node) && isBlock(node)
```

We would modify `isVoid`, `isInline` and `isBlock` to make them take an `Element` as its input argument. In this way, the `Element.isElement` code only gets called once. Currently, `isVoid`, `isInline` and `isBlock` all internally execute the `Element.isElement` code.

The changes will be:

*   Change `isVoid`, `isInline` and `isBlock` to take `Element` argument.
*   Modify all code that uses these functions so that we manually do the `Element.isElement` check before calling them
*   Bump the semantic versioning to indicate a breakage as code that is depending on these methods to do the `Element.isElement` check will break (and the types will be different as well).

So I think it's still a doable PR and, in my opinion, this is the correct fix. But I think we might want to have some eyes on the code before accepting to make sure that there is agreement that this is the correct approach.

For clarity though, at the moment, the types are wrong and I don't think the correct approach is to just leave it. Furthermore, the `has` and `is` checks are similar in usage, but have inconsistent call signatures which I believe should be normalized.

**Comment by RavenColEvol** [comment]
@thesunny I was also thinking something on in the similar lines to have isElement check separated from isVoid, isInline, etc.
If it's in an open issue I would like to take up this.

**Comment by thesunny** [comment]
@RavenColEvol In my opinion, go for it, but for clarity, once the PR is in, I think we should ask some feedback from the community before we merge it into main.
