### ISSUE TITLE
Increase number of max normalization iterations

### ISSUE THREAD

**Issue by Jacfem** [ianstormtaylor/slate#5222]
**Problem**

The amount of max normalization iterations isn't enough for some large content in my app. It is set [here](https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/interfaces/editor.ts#L1060) as the number of dirty paths multiplied by 42. There's a comment next to the code that says `//HACK: better way?`. I'd love to learn more if bumping this multiplier is okay.

**Solution**

Either allow that `42` number to be configurable by the user, or increase that number. Locally, I've increased it to 100 and it fixes our use cases.

**Alternatives**
Open to suggestions!

**Context**
PR will be incoming.

I am curious if there are risks or concerns associated with this increase. I've applied the fix locally on my app and it fixes the issues. Thank you for your input!

**Comment by zbeyens** [comment]
I think that error is generally dangerous for apps in production. We should add an editor method to override that behavior: `editor.getMaxNormalizationIterations(dirtyPaths)` so we choose to reuse `dirtyPaths`
