### ISSUE TITLE
Bugs for example rich text

### ISSUE THREAD

**Issue by Birddle** [ianstormtaylor/slate#5243]
**Problem**
There is a bug in the case code:
error template: 
![image](https://user-images.githubusercontent.com/86408260/210495416-4baf3afb-bf20-401b-9348-390336cf6ebc.png)

example code : rich text  https://github.com/ianstormtaylor/slate/blob/main/site/examples/richtext.tsx
env:     
    "@emotion/css": "^11.10.5", 
    "is-hotkey": "^0.2.0", 
    "slate": "^0.87.0",
    "slate-history": "^0.86.0",
    "slate-react": "^0.88.0"

**Solution**

**Alternatives**

**Context**
I also use the MUI default plugin. When I copy the case code exactly, this is what happens. Maybe the code should be updated to accommodate the latest version?

**Comment by SeekerandLo** [comment]
hello, if your problem is that the icon does not display normally。you can add 
```
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
```
in ```<Head></Head>```，like https://github.com/ianstormtaylor/slate/blob/ce1e096df7e0decd2fecbe45af294a3839325582/site/pages/examples/%5Bexample%5D.tsx#L280
