### ISSUE TITLE
Space can not be added to the start of the last line in document

### ISSUE THREAD

**Issue by zengem** [ianstormtaylor/slate#5247]
**Description**
Space can not be added to the start of the last line in document

**Recording**
https://user-images.githubusercontent.com/18223962/211097518-0122fb25-56be-4eeb-82b8-0fa252d6b595.mov

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext
2. Type in a long line that would fill the whole doucument width and wrap to the next line, for example 'OOOOOOOOO...'
3. Try insert a space at start of the last line, the space is actually added to the line above. 

**Note:** It is easier to see this in Firefox, because it actually show the space is being added. For other browser, the cursor does not move, but the spaces are being added to the line above as well. You can verify this by copy the whole thing and paste it to somewhere else.

**Environment**
- Slate Version:  v0.87.0 and older versions
- Operating System: [e.g. iOS] OSX
- Browser: [e.g. Chrome, Safari] Firefox, Chrome, Safari. Didn't test others, but likely has same problme.

**Comment by ac-amygdala** [comment]
@zengem There is no bug here. Slate does not operate with _lines_, but with _blocks_ (e.g. paragraph). In your case you have one paragraph with long text and spaces are inserted between "words".
Moreover Word and Google Docs behave the same in such case

**Comment by zengem** [comment]
> 

Hi Andrey,

Thank you for the explanation. I just tried it on Word and Google Docs. They are indeed behave the same way. I'm closing this issue now.

Just curious, what is the difference between a 'space' and any other characters, which can be added at that position?

**Comment by ac-amygdala** [comment]
Basically it is a regular browser behaviour with large content inside one element.
Assume that you have infinite-width element (paragraph block in slate, div element in html, etc) and a very long content inside it. This content will be shown as single line. And now we are narrowing element width. At some point element will not be able to contain all the content within one line - so content will continue on the second line. Element tries to keep as much words as it can in one line. In case there is a word larger than element width - the word will splitted and will continue on next line. It is not a slate doing splits but just regular browser behaviour with regular content. Slate doesn't know anything about it.
So here is an example (`|` - will be used as indicator where to break the line, `.` will show a space symbol)
`somelongwordsomeotherveryve|rylongword`
`somelongword.|someotherveryverylongword`
`somelongword....|someotherveryverylongword`

So just don't treat visual text lines as separate blocks or paragraphs. And content in a block behaves just a regular html element in browser

**Comment by zengem** [comment]
> 

Thank you!

**Comment by zengem** [comment]
> Basically it is a regular browser behaviour with large content inside one element. Assume that you have infinite-width element (paragraph block in slate, div element in html, etc) and a very long content inside it. This content will be shown as single line. And now we are narrowing element width. At some point element will not be able to contain all the content within one line - so content will continue on the second line. Element tries to keep as much words as it can in one line. In case there is a word larger than element width - the word will splitted and will continue on next line. It is not a slate doing splits but just regular browser behaviour with regular content. Slate doesn't know anything about it. So here is an example (`|` - will be used as indicator where to break the line, `.` will show a space symbol) `somelongwordsomeotherveryve|rylongword` `somelongword.|someotherveryverylongword` `somelongword....|someotherveryverylongword`
> 
> So just don't treat visual text lines as separate blocks or paragraphs. And content in a block behaves just a regular html element in browser

Thank you!
