### ISSUE TITLE
Plus (+) is not included in the list of punctuation 

### ISSUE THREAD

**Issue by JoeVanGundy** [ianstormtaylor/slate#5255]
**Description**

The list of punctuation unicode symbols does not include plus (002B).

For the string `+sum`:
When I do` Editor.before(editor, start, { unit: 'word' });`:
It will count the `+` as part of the word.

For all the various other types of symbols `/`, `*`, `-`, etc, the symbol is not part of the word.

**Expectation**
Simply update the [list of punctuation](https://github.com/ianstormtaylor/slate/blob/cb133a785fe882a03f25d749a78110e20b3dd869/packages/slate/src/utils/string.ts#L78) to include +.

**Environment**
- Slate Version: 0.88.1
- Operating System: mac
- Browser: chrome

**Context**
We just started using slate and his is causing a lot of problems for us.
Please let me know if it is intentional that `+` doesn't count as punctuation.

**Comment by GeneralChauhan** [comment]
Hi Can this be assigned to me??
