### ISSUE TITLE
The property 'type' does not exists on 'Node' type

### ISSUE THREAD

**Issue by nonam4** [ianstormtaylor/slate#5264]
**Description**
I'm using TS and following the 'getting started' section from [this](https://docs.slatejs.org/walkthroughs/03-defining-custom-elements) doc page and I ended up with this type bug/error

**Steps**
The error is happening in the snippet bellow:

```
// Determine whether any of the currently selected blocks are code blocks.
const [match] = Editor.nodes(editor, {
    match: n => n.type === 'code' // 'type' does not exists on Node type
})
```

**Environment**
- Slate Version: always on latest - ^0.88.1
- Operating System: macOs 12.6.2
- Browser: Chrome
- TypeScript Version: 4.9.4

**Comment by gabetavares** [comment]
It's not a bug nor an error, it's just a ts warning, if you check the `Node` type:

```ts
export declare type Node = Editor | Element | Text;
```

The property `type:` does not exist in neither `Editor` nor `Text`. You must check if it's an `Element` first.

```ts
const [match] = Editor.nodes(editor, {
    match: n => Element.isElement(n) && n.type === 'code'
})
```

**Comment by nonam4** [comment]
> It's not a bug nor an error, it's just a ts warning, if you check the `Node` type:
> 
> ```ts
> export declare type Node = Editor | Element | Text;
> ```
> 
> The property `type:` does not exist in neither `Editor` nor `Text`. You must check if it's an `Element` first.
> 
> ```ts
> const [match] = Editor.nodes(editor, {
>     match: n => Element.isElement(n) && n.type === 'code'
> })
> ```

It worked, thanks 😁 😁
