### ISSUE TITLE
Crash when deleting last paragraph ending in `\n`

### ISSUE THREAD

**Issue by 12joan** [ianstormtaylor/slate#5273]
**Description**

This crash occurs in Firefox when the editor has at least two paragraphs and the last paragraph ends in `\n`. When selecting all text and deleting it, the editor crashes with the following error message:

```
Uncaught (in promise) Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":1}
    toDOMPoint https://zm8y60.csb.app/node_modules/slate-react/dist/index.es.js:508
    toDOMRange https://zm8y60.csb.app/node_modules/slate-react/dist/index.es.js:515
    setDomSelection https://zm8y60.csb.app/node_modules/slate-react/dist/index.es.js:2406
    Editable https://zm8y60.csb.app/node_modules/slate-react/dist/index.es.js:2419
    React 8
    unstable_runWithPriority https://zm8y60.csb.app/node_modules/scheduler/cjs/scheduler.development.js:255
    React 5
    onChange https://zm8y60.csb.app/node_modules/slate-react/dist/index.es.js:3677
    apply https://zm8y60.csb.app/node_modules/slate/dist/index.es.js:232
```

**Recording**

https://user-images.githubusercontent.com/4272090/214837667-36af22c8-da80-4ff4-bb57-f37ca0b171be.mov

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-zm8y60

**Steps**
To reproduce the behavior:
1. Go to the sandbox
2. Select all text (command+a)
3. Press backspace

**Environment**
- Slate Version: 0.88.1
- Operating System: macOS
- Browser: Firefox only (no error in Safari or Chrome)

**Context**
This bug was introduced in `slate-react@0.82.0` by PR #4988. (I discovered this by testing timestamped NPM releases; `0.82.0-2022629111111` is the first one to contain the bug.)

**Comment by Slapbox** [comment]
Why do you need a `\n` character within the editor? IT may be a change in behavior, but is it really a bug? Is it intended to allow `\n` in the editor nodes? I don't know.

**Comment by 12joan** [comment]
@Slapbox I do most of my work on and with Plate, so that's the perspective I'll speak from. I've got very little experience working with Slate directly.

From what I gather, the default Slate examples don't make a distinction between paragraphs and line breaks. In Plate, however, [`createSoftBreakPlugin`](https://github.com/udecode/plate/blob/d12c4e287436706859ed768f898bdae81367e97e/packages/editor/break/src/soft-break/onKeyDownSoftBreak.ts#L27) [(example)](https://plate.udecode.io/docs/plugins/soft-break) is commonly used to insert a line break `\n` within an existing paragraph on shift+enter, which is a common feature of rich text editors.

Even without `createSoftBreakPlugin`, it's proven surprisingly difficult to avoid `\n` characters slipping into paragraphs: from [pasted HTML](https://github.com/udecode/plate/pull/2156), for example, or when [unwrapping blockquotes](https://github.com/udecode/plate/issues/2169). (For some reason I've yet to determine, it tends to be only these indirect ways of inserting `\n` that cause this error, rather than the more intentional `createSoftBreakPlugin`.)

But I think the more pressing point is that yes, the editor crashing when a particular ASCII character happens to appear in a text node is a bug, even if we discourage use of that character from a stylistic perspective in favour of other approaches, such as an inline `<br />` element or treating paragraphs and line breaks indiscriminantly. 

I'm not sure whether the PR #5195 you referenced this issue from will cause breaking changes in the way Plate handles line breaks, but it probably wouldn't be difficult for us to patch that behaviour on our end if necessary. As for this bug, the fact remains that `\n` characters can end up in the editor through any number of ways.

**Comment by rcbevans** [comment]
I've been seeing rare instances of this in our site and have been banging my head on a desk trying to figure out why, but with a trailing `\n` I can repro it consistently.

For me the `\n` is ending up in the editor content due to pasting from other apps.

**Comment by Slapbox** [comment]
> For me the \n is ending up in the editor content due to pasting from other apps.

I'm only on Slate `0.45.x` iirc, but yes I can relate to that issue. It's quite frustrating. I remember I found a solution years ago for the pasting issue - but then by the time I went to implement it, I forgot it.

**Comment by 12joan** [comment]
I've made some progress discovering the root cause of this bug:

1. In `packages/slate-react/src/components/string.tsx`, if `isLast` and `leaf.text` ends in `\n`, we pass `isTrailing` to the `TextString` component.
    - The comment explains: "COMPAT: Browsers will collapse trailing new lines at the end of blocks, so we need to add an extra trailing new lines to prevent that."
2. Accordingly, when `isTrailing` is true, `TextString` inserts an extra `\n` at the end of the text. If our leaf originally read `"hello\n"`, it now reads `"hello\n\n"`.
   - This makes its way into the DOM, but all browsers render it visually as a single line break.
4. When pressing `command+a`, Firefox includes the extra `\n` in its DOM selection.
   - This results in a `focusOffset` of 7 instead of 6.
   - Chrome does not behave in this way, and sets the `focusOffset` to 6.
5. When the user presses the backspace key, a number of operations are applied. One of these is a `remove_text` operation with path `[1, 0]` and offset 0.
6. This `remove_text` operation is applied to a PointRef tracking the end of the range to be deleted ([this one](https://github.com/ianstormtaylor/slate/blob/47498cf8eae1fa3abf8ddd90ddae2ce3a47a902e/packages/slate/src/transforms-text/delete-text.ts#L130), to be precise).
   - In `packages/slate/src/interfaces/point.ts`, under the `remove_text` case of `transform`, we run `p.offset -= Math.min(offset - op.offset, op.text.length)`
   - `p.offset` starts as 7 (due to Firefox and the extra `\n`)
   - `offset` is the same as `p.offset`
   - `op.offset` is 0
   - `op.text.length` is 6 (`"hello\n"`)
   - The result is a decrease of 6
   - `p.offset` now equals 1
7. Once the deletion is complete, we attempt to set the selection to the new value of the PointRef
   - Since `editor.children` now consists of a paragraph with text `""`, this point does not exist.
   - Hence, we crash with the error, `Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":1}`.

**Comment by 12joan** [comment]
Things start going wrong at step 3, due to the browser inconsistency.

One potential fix would be to clamp the offset of the end point of the selection to the length of the text node that contains it. So if we have a `focusOffset` of 7 inside a text node of length 6, we set the focus to `{ path: ..., offset: 6 }`.
