### ISSUE TITLE
Consider moving most .md files into `docs`

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#528]
I wonder if it would be simpler if everything a user might want to know (less the source code) was found in one place like the GitBook.

I find myself switching back and forth between GitHub and GitBook and it's not clear for new users where to find a piece of information or whether it exists at all.

For example, information about Plugins is not in the docs and neither is information about contributing although both are available as `.md` files in the root directory of the source code.

Perhaps the `Readme.md` could provide a very short description (so users know they are in the right project) and other than that it points to the GitBook.

**Comment by ianstormtaylor** [comment]
What is the plugins info that's not available in the docs?

The `.md` files in the root directory I'd like to keep, since they are kind of standard across repositories, and specifically the `Contributing.md` is picked up by GitHub and showed above pull requests. But I'd definitely want to make sure that everything useful in `/docs` is reflected.

**Comment by thesunny** [comment]
Specifically, the following list of public plugins is not in the docs:

```
Plugins

Slate encourages you to write small, reusable modules. Check out the public ones you can use in your project!

slate-auto-replace-text auto-replaces a string of text when typed. Useful for "smart" typography!
slate-collapse-on-escape simply collapses the selection when escape is pressed.
slate-edit-code adds code editing behavior like tab-to-indent, and enter-to-soft-break.
slate-paste-linkify wraps the selected text in a link when a URL is pasted from the clipboard.
slate-prism highlights code blocks with Prism.js!
slate-soft-break adds a soft break when enter is pressed.
slate-drop-or-paste-images lets users drop or paste images to insert them!
View all plugins on npm...
```

Feel like it would be helpful there as when working with Slate, I think a lot of developers would just leave the docs open and use that as the canonical source of information about Slate.

Also the Principles, Contributing info, and links to examples can't be found in the docs but feels like they should be there.

I think it could make sense to mirror the information in both places. If you are okay with that, I could put together a PR for it.

**Comment by ianstormtaylor** [comment]
Ah nice, yeah mirroring it sounds good to me. Should be as easy as just copy-pasting most of `Readme.md`. Thanks!

**Comment by ianstormtaylor** [comment]
Mirrored the readme in the docs introduction now.

I'd like to keep the other, smaller readmes in the source intact since they are there to help explain the source, like comments.
