### ISSUE TITLE
slate-react doesn't use most up-to-date onChange callback

### ISSUE THREAD

**Issue by endercrest** [ianstormtaylor/slate#5289]
**Description**
slate-react `Slate` component does not use the most up-to-date `onChange` callback provided to the component.

It looks like https://github.com/ianstormtaylor/slate/pull/5261 introduced this bug. It does not update the onChange callback so it is always utilizing the first time provided onChange value.

**Recording**

https://user-images.githubusercontent.com/2616075/217894479-329ec616-a837-40b6-9cab-b8b47545be8e.mov

**Sandbox**
https://codesandbox.io/s/onchange-incorrectly-updates-0-89-0-or-above-bqmcu1?file=/index.js

**Steps**
To reproduce the behavior:
1. Type into the editor in sandbox above. The console will print out 0 as that is the initial value of the counter.
2. Increment the counter using the button above the editor.
3. Type into the editor again and observe that the counter is still printing the initial counter value.

**Expectation**
onChange callback should be using the latest onChange prop value instead of the first-time provided value.

Going down to 0.88.2 of slate-react fixes the problem.

**Environment**
- Slate Version: slate-react 0.89.0 or above
- Operating System: MacOS Ventura
- Browser: Chrome

**Comment by kaya-altin** [comment]
I switched back to version 0.88.2 for this reason. I am eagerly waiting for it to be fixed. :)

**Comment by shannonjarcher** [comment]
I've encountered this issue as well.
