### ISSUE TITLE
Can somebody explain the difference between `export` vs `export default`

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#529]
Sorry, I know this isn't for general JavaScript issues but I wasn't able to find any good documentation on why one would use both `export` and `export default` to export the same values.

The documentation on `export` vs `export default` is poor and after searching for a while, I don't understand this source code here where the values are both `export`ed and `export default`ed.

```js
export {
  Block,
  Character,
  Data,
  Document,
  Editor,
  Html,
  Inline,
  Mark,
  Placeholder,
  Plain,
  Range,
  Raw,
  Schema,
  Selection,
  Stack,
  State,
  Text,
  Transforms,
  findDOMNode,
  resetKeyGenerator,
  setKeyGenerator
}

export default {
  Block,
  Character,
  Data,
  Document,
  Editor,
  Html,
  Inline,
  Mark,
  Placeholder,
  Plain,
  Range,
  Raw,
  Schema,
  Selection,
  Stack,
  State,
  Text,
  Transforms,
  findDOMNode,
  resetKeyGenerator,
  setKeyGenerator
}
```

**Comment by thesunny** [comment]
For clarity, the JavaScript documentation on the Internet is poor, not Slate's documentation. :)

**Comment by cobbweb** [comment]
Pretty sure this just enabled different ways to import slate, e.g.

```js
// importing 'default'
import Slate from 'slate';
console.log(Slate.Editor);

// importing named exports using destructing-like syntax
import { Editor } from 'slate';
console.log(Editor);

console.log(Slate.Editor === Editor); // --> true
```

If you're writing ES6 code, I'd recommend the second option.

**Comment by thesunny** [comment]
@cobbweb Thanks.

I always assumed that you could already do:

```js
import {Editor} from 'slate';
```

even if you did this
```js
export default {
  Block,
  Character,
  Data,
  Document,
  Editor,
  Html,
  Inline,
  Mark,
  Placeholder,
  Plain,
  Range,
  Raw,
  Schema,
  Selection,
  Stack,
  State,
  Text,
  Transforms,
  findDOMNode,
  resetKeyGenerator,
  setKeyGenerator
}
```

I thought it was just a form of the ES6 syntax. Thanks for clarifying.

**Comment by ianstormtaylor** [comment]
@thesunny to be fair, I think in previous versions of the Babel transforms it did let you do that even though it technically wasn't following the spec, which led to a lot of confusion. It still trips me up every once in a while too. Glad you asked!
