### ISSUE TITLE
Can't paste into void elements

### ISSUE THREAD

**Issue by aspirisen** [ianstormtaylor/slate#5294]
**Description**
Looks like Slate forbids pasting into void elements. However, if you copy slate text and paste into void that works a bit (with runtime errors, but eventually you will see pasted text)

**Recording**
![2023-02-15 16 38 15](https://user-images.githubusercontent.com/3620639/219029517-0f7b11e3-78ae-4033-af74-61730103ae04.gif)

**Sandbox**
https://codesandbox.io/s/confident-orla-7wxwrd?file=/src/App.tsx

**Steps**
To reproduce the behavior:
1. Go to sandbox example
2. Copy some text outside of slate
3. Paste in input
4. The text will be not pasted

**Expectation**
Slate should not forbid pasting into void elements

**Environment**
- Slate Version: 0.90.0
- Operating System: MacOS
- Browser: Chrome

**Comment by yupeilin123** [comment]
can you see that？
![iShot_2023-02-21_17 49 27](https://user-images.githubusercontent.com/28672197/220310004-43f54c31-9344-4998-ab16-8a16584e0426.gif)
https://codesandbox.io/s/objective-bhaskara-qhqsc9?file=/src/App.tsx:421-436

**Comment by aspirisen** [comment]
Looks like copying from html works
Try to copy i.e. from address bar 
![2023-02-21 13 54 29](https://user-images.githubusercontent.com/3620639/220311277-00dd21fc-2025-4bcd-9d07-e7aa19eadb81.gif)

**Comment by yupeilin123** [comment]
I know why cannot copy content in input box. Because it's a void element. This is the default rule of slate.
But you know that input box can pasted some text. I guess this is a violation of browser rules，This is inconsistent with the behavior of slate

**Comment by aspirisen** [comment]
Yes, it is void element. But it is strange that you can copy-paste from slate content and it will work for void element, but it doesn't work if you copy-paste from plain text source.

**Comment by dylans** [comment]
The behavior changed a bit with https://github.com/ianstormtaylor/slate/pull/5121 but there may be a scenario that is failing.

Please read through the above issue and the PR that landed and see if that answers your question, or let me know if it's still not working for you.

**Comment by aspirisen** [comment]
@dylans I do not clear understand expected behavior
* Is it expected that you **can** paste into void elements - if yes then disability of plain text pasting into void elements is a bug
* Is it expected that you **can't** paste into void elements  - if yes then ability of copy-pasting slate content into void element is a bug
