### ISSUE TITLE
Shadow DOM example is not working correctly

### ISSUE THREAD

**Issue by safiaZihmou** [ianstormtaylor/slate#5321]
**Description**
Shadow dom example is not working properly. [https://www.slatejs.org/examples/shadow-dom](https://www.slatejs.org/examples/shadow-dom)

**Recording**
![slate_example_issue](https://user-images.githubusercontent.com/32685619/221583856-d6f88fe4-84d1-4180-aa91-22a713bc484f.gif)

**Sandbox**
[https://www.slatejs.org/examples/shadow-dom](https://www.slatejs.org/examples/shadow-dom)

**Steps**
To reproduce the behavior:
1. Go to: [https://www.slatejs.org/examples/shadow-dom](https://www.slatejs.org/examples/shadow-dom)
2. Try adding text at the beginning (we can only add 1 letter)
3. Try adding "Space" within the text (no space added)
4. Try to modify the text. (the text is not modified)
5. Try changing the text at the end (the text is deleted and the Slate example is broken)

**Expectation**
We can modify, change text 

**Environment**
- chrome, Microsoft Edge, Firefox

**Comment by NikolajHoggins** [comment]
![slate](https://github.com/ianstormtaylor/slate/assets/31845887/169bcb07-3cbf-49b3-b33f-8e9f67221241)

Seemingly all I need to do to make it break is add a space and then a dot. " ." and it will break.

**Comment by caycecollins** [comment]
> ![slate](https://user-images.githubusercontent.com/31845887/237629190-169bcb07-3cbf-49b3-b33f-8e9f67221241.gif)
> 
> Seemingly all I need to do to make it break is add a space and then a dot. " ." and it will break.
> 
> In the last example of the recording i add " f f f ." and it breaks on the "." again

I noticed the same thing, but with any number or special character after a space.

Additionally, simply typing very fast, "asdf" repeatedly, will cause the same behavior.

**Comment by A6Brgeuka** [comment]
is there any progress here? 👀
