### ISSUE TITLE
Buggy Interaction with Selection-Position

### ISSUE THREAD

**Issue by eugenkiss** [ianstormtaylor/slate#533]
Consider the following example: https://gomix.com/#!/project/helpless-almanac (https://helpless-almanac.gomix.me/)

Try to insert an '@' symbol somwhere in-between the text and observe that the remaining characters to the right of '@' disappear in Chrome. I have a similar problem in Safari in one of my projects. However, this minimal example does not seem to trigger the problem in Safari. Here's a video of the problem: https://streamable.com/12h9i 

The relevant parts are as follows:

```
class App extends React.Component {
  state = { state: Plain.deserialize('Insert an @ somewhere in-between') }
  onChange = (state) => { this.setState({ state }) }
  
  onKeyDown = (event, data, state) => {
    if (event.key === '@') {
      // Commenting this out makes the problem go away
      const bounds = caretPosition()
      // Imagine a suggestions portal here that needs the caret position
      return
    }
  }
  
  render() {
    return (
      <Editor
        state={this.state.state}
        onChange={this.onChange}
        onKeyDown={this.onKeyDown}
      />
    )
  }
}
```

The following parts in [selection-position](https://github.com/bmcmahen/selection-position) are responsible for the problem:

```
// if we only have a cursor, then we need to insert
// a dummy element and see what's what.
var dummy = document.createElement('span');
range.insertNode(dummy);
var pos = dummy.getBoundingClientRect();
dummy.parentNode.removeChild(dummy);
return pos;
```

The above workaround is necessary for at least Safari. 

(If you know of an alternative to selection-position that works better with Slate please let me know.)

Maybe this information helps debugging the issue: In my (more complicated) project I get the following exception when this problem occurs:

```
TypeError: undefined is not an object (evaluating '_char.marks')
  	getMarksAtRange	@	node.js:834
        object.(anonymous function)	@	memoize.js:109
        get	@	state.js:466
        ...
```

**Comment by eugenkiss** [comment]
Using another snippet to get the caret position as done in https://github.com/oozou/slate-suggestions/pull/11 seems to solve the problem. I'll keep this open nonetheless since the buggy interaction with `selection-position` might be a hint of problem still.

**Comment by ianstormtaylor** [comment]
Thanks @eugenkiss! Closing for sanity, but good for others in case they are searching.
