### ISSUE TITLE
Focus issue caused by placeholder

### ISSUE THREAD

**Issue by kaya-altin** [ianstormtaylor/slate#5331]
**Description**
After then slate-react 0.91.4 version, there is a problem of not being able to focus on the first click. I think it's related to the placeholder, the issue doesn't occur when the placeholder is removed.

**Recording**
https://user-images.githubusercontent.com/4608228/222789019-455ca226-04b9-4685-b80a-702f230d6867.mov

**Environment**
- Slate Version: 0.91.4
- Operating System: macOS
- Browser: Chrome, Safari

**Comment by jiabin-xu** [comment]
We also encountered the same problem. May I ask how it was eventually resolved?
