### ISSUE TITLE
how to upload local image

### ISSUE THREAD

**Issue by liSong5713** [ianstormtaylor/slate#535]
hi slate is excellent!

how to upload local image?

many thanks!

**Comment by Mavrin** [comment]
You could see example https://github.com/ianstormtaylor/slate/blob/master/examples/images/index.js

**Comment by liSong5713** [comment]
thanks!
  I realized to upload pictures, but pictures can't drag and drop, please help me find solution，Thanks!

**Comment by Slapbox** [comment]
Same developer: https://www.npmjs.com/package/slate-drop-or-paste-images

I think it requires Java though.

**Comment by ravsas3** [comment]
hello, iam trying to implement a RTE using slate, but when inserting an image it is crasing in the editor on change part, with the error.

slate-react.es.js:1229 Uncaught Error: Unable to find a DOM node for <DATA-LINKNO>. This is often because of forgetting to add `props.attributes` to a custom component.

**Comment by Kushan-** [comment]
Hey, followed module link and tried to integrate with my application, since your demo link is not working as well. I got stuck on how to make image drag and drop work. Any help??

**Comment by Slapbox** [comment]
@Kushan- 

Use `git clone` to clone this repo, then run `yarn && yarn start` and navigate in your browser to `localhost:1234`

Or if you use npm, `npm && npm start`

Then you can poke around the example as needed.

**Comment by devincma** [comment]
@Kushan- This may work:
``` javascript
case "image": {
      const src = node.data.get("src");
      return (
        <div>
          <img src={src} selected={isFocused} {...attributes} />
          <div className={styles.imageCaption}>{children}</div>
        </div>
      );
    }
```
where `{children}` displays a caption text underneath the image. Also, set the image block `isVoid: true` in the schema.

**Comment by Kushan-** [comment]
Thanks for updating, i am not longer working on it. But this may come handy. Did you try to run it from your end though? (I did run many hit and trial method and able to render the caption but unable to edit it as far i remember.)

**Comment by amirphp7** [comment]
How to upload image or file from local file browser in slate js editor. Basically I don't want to get image neither paste url nor drag and drop. please help

**Comment by dkchv** [comment]
I found this page while searching for example...
So, here is my implementation:

`
// in component:
const handleUpload = useCallback(async (e: any) => {
    const { files } = e.target;
    console.log('--files', );
    if (files.length === 0) {
      return;
    }
    await insertImagesFromFiles(editor, files);
    ReactEditor.focus(editor);
  }, [editor]);

export function insertImagesFromFiles(editor: Editor, files: FileList) {
  const promises: Promise<string>[] = [];
  for (const file of files) {
    promises.push(fileImageToBase64(file, (url: string) => {
      insertElementImage(editor, url);
    }));
  }
  // execute loading
  return Promise.all(promises);
}

export function fileImageToBase64(file: File, onLoad?: (url: string) => any): Promise<string> {
  return new Promise((resolve, reject) => {
    const [mime] = file.type.split('/');
    if (mime !== 'image') {
      reject();
    }
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const url = String(reader.result);
      onLoad?.(url);
      resolve(String(url));
    };
    reader.onerror = reject;
  });
}

// the same in drag-in-drop:
export function withImage(editor: Editor): Editor {
  const { insertData } = editor;

  editor.insertData = async (data) => {
    // parse files
    const { files } = data;
    if (files && files.length > 0) {
      await insertImagesFromFiles(editor, files);
      return;
    }

    insertData(data);
  };

  return editor;
}
`
