### ISSUE TITLE
No Line Breaks on Enter By Default?

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#537]
I just wanted to confirm this is the normal behavior and that I've not done something wrong in setup. Thanks!

**Comment by Slapbox** [comment]
I don't know what I did wrong, but I did manage to get it working. For reference to any future people, there should be line breaks on enter by default.

**Comment by mbessieres** [comment]
For anyone coming across this now, I discovered that returning false in your onKeyDown function when the enter key is pressed will prevent line breaks. So don't return anything and you're fine. It violates consistent-return considering when you do want something handled, you're returning true, but it solves the problem.

**Comment by ianstormtaylor** [comment]
@mbessieres I agree with you about that being confusing. I've opened https://github.com/ianstormtaylor/slate/issues/1311 to account for it in a future breaking release.

**Comment by mbessieres** [comment]
Awesome, thanks @ianstormtaylor.
