### ISSUE TITLE
onDocumentChange is not being called on changes to state

### ISSUE THREAD

**Issue by LeeKevin** [ianstormtaylor/slate#538]
Particularly with unwrapBlock/wrapBlock

See https://jsfiddle.net/pv95mqbo/

Open the console, type in some text, and toggle between the lists. You'll see that `onDocumentChange` is called for the text input, but not for the changes to blocks.

**Comment by ianstormtaylor** [comment]
Should be fixed by https://github.com/ianstormtaylor/slate/commit/1511d9f203455734065246d729bd8fb07cff264e
