### ISSUE TITLE
Placeholders not placed correctly on Safari 16.4

### ISSUE THREAD

**Issue by ashbork** [ianstormtaylor/slate#5386]
**Description**
Placeholders seem to be placed a line lower than they should be. This behavior didn't occur before 16.4

![image](https://user-images.githubusercontent.com/82605611/229818852-6d33c255-5701-487d-947a-627978bbb76d.png)

**Sandbox**
[One of Slate's examples](https://www.slatejs.org/examples/richtext)

**Steps**
To reproduce the behavior:
1. Go to ['the Slate playground](https://www.slatejs.org/examples/richtext)
2. Empty the text area
3. See the error

**Expectation**
The placeholder should be placed at the top of the text area.

**Environment**
- Slate Version: ^0.87.0 and current
- Operating System: macOS
- Browser: Safari 16.4

**Comment by Noothan-am** [comment]
hey @ashbork is this issue fixed ?

**Comment by ashbork** [comment]
You'd likely find an associated PR if it were, I can't check that now, you could just follow the reproduction steps

**Comment by Noothan-am** [comment]
i tried to reproduce it and i got this, iam not able to figure out what is problem here could you please give me some more info about this issue ?

![image](https://user-images.githubusercontent.com/100135382/236182984-cc7bb1b6-36f2-490c-8520-479efe321693.png)

**Comment by ashbork** [comment]
It's still reproducible for me and apparently 3 others, idk what to tell you - maybe the environment is different

**Comment by horacioh** [comment]
> i tried to reproduce it and i got this, iam not able to figure out what is problem here could you please give me some more info about this issue ?
> 
> ![image](https://user-images.githubusercontent.com/100135382/236182984-cc7bb1b6-36f2-490c-8520-479efe321693.png)

the placeholder looks in the middle because you have the alignment set to center.
I see this issue but the placeholder renders below the cursor. Does this happens to anyone else?
<img width="948" alt="Screen Shot 2023-05-10 at 13 05 11" src="https://github.com/ianstormtaylor/slate/assets/725120/3ca7b71b-72e5-40cf-a6f8-30baf5315865">

**Comment by ashbork** [comment]
That is the original issue I reported, yes

**Comment by horacioh** [comment]
> That is the original issue I reported, yes

@ashbork the placeholder have some inline styles that makes it a block element, can you try to uncomment the block styles (and even the width) to see if the problem still persist?

**Comment by ashbork** [comment]
Nope, removing `width` or `display:block` doesn't do anything to fix the alignment.

**Comment by horacioh** [comment]
Need to update my machine. Will do it and try to fix it because this is happening our app and is not acceptable 😅

**Comment by horacioh** [comment]
I fixed this issue by adding `top: 0;` to the placeholder in the styles. maybe this is something that can be set by default?
I also find hard to override the default styles for the placeholder, what if we set the styles for the placeholder in a different way so it can be easily overridden?

**Comment by horacioh** [comment]
I just saw that there's a `renderPlaceholder` prop. maybe I can just add the `top` style to the current style and that's it
