### ISSUE TITLE
HtmlSerializer cannot deserialize simple string

### ISSUE THREAD

**Issue by LeeKevin** [ianstormtaylor/slate#539]
`HtmlSerializer.deserialize('test')` will raise an error:

> TypeError: Cannot read property 'kind' of undefined

```
	getLeafText	@	get-leaf-text.js:15
        collapseToStartOf	@	selection.js:367
        create	@	state.js:537
        deserializeState	@	raw.js:238
        deserialize	@	raw.js:62
        deserialize	@	html.js:206
```

It should create a text block (or an equivalent) for the string. Currently the nodes passed to the Raw serializer is an empty array.

**Comment by ianstormtaylor** [comment]
Thanks for reporting this @LeeKevin. I agree with you, and I'd be happy to accept a pull request that allows for simple string deserializing! Let me know if you need any guidance on putting one together. Thanks!

**Comment by vpontis** [comment]
I was looking at this as a bug to fix but I didn't find the `HtmlSerializer` in the codebase... 

Ah, I think this is actually called `Html` in `/src/serializers/html.js`. Maybe it got updated...
