### ISSUE TITLE
Add a way to propagate `readOnly` state to nested editable content blocks

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#543]
Nested editable content blocks like:
```
<section className="definition" contentEditable={false}>
  <header>Definition.</header>
  <div className="content" contentEditable={true}>
    {props.children}
  </div>
</section>
```
remain editable even when the editor enters `readOnly` state.

A natural way to solve this is rewriting the block as
```
<section className="definition" contentEditable={false}>
  <header>Definition.</header>
  <div className="content" contentEditable={!editor.props.readOnly}>
    {props.children}
  </div>
</section>
```
Unfortunately this does not work because when `readOnly` editor property changes, only the nodes containing the selection edges are updated.

A possible solution is to update all the document nodes.
Another possible solution is to add an handler to the editor (and to the plugins), let's say `onReadOnlyChange`, that can be used by components to react to `readOnly` editor state mutations.

**Comment by ianstormtaylor** [comment]
Hey @AlbertHilb, I agree with you. It makes sense that `readOnly` would trigger re-renders across all nodes. Should be fairly easy to do by passing `readOnly` into the nodes themselves and tweaking `shouldComponentUpdate`. If you're down to submit a pull request for that, I'd be happy to merge it!
