### ISSUE TITLE
Support copying the style of word

### ISSUE THREAD

**Issue by moonlitusun** [ianstormtaylor/slate#5440]
![CleanShot 2023-06-07 at 19 15 13](https://github.com/ianstormtaylor/slate/assets/22940470/4219ba35-f976-4ad7-b825-24d5fc2cab9b)
This is My word content。
![CleanShot 2023-06-07 at 19 15 56](https://github.com/ianstormtaylor/slate/assets/22940470/2ac854a5-01b8-40cb-b293-a4ee480cca1e)
This is the Result！

can support copying the style of Word？

**Comment by dylans** [comment]
The Plate Docx plugin provides support for this:

https://plate.udecode.io/docs/serializing-docx
