### ISSUE TITLE
On viewing Editor's State in React Devtools: Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#545]
This occurs on my project in Electron, and in the `slate-drop-or-paste-images` example run in Chrome 55. As a result of the error the `state.state` is not viewable. All other trees are openable without error.

**Comment by ianstormtaylor** [comment]
I think this is due to https://github.com/facebook/react-devtools/issues/390, so I'm going to close here in favor of the issue over there.

**Comment by Slapbox** [comment]
Thanks Ian for all your help. I'll +1 that thread.

**Comment by murattishkul** [comment]
I run into the same problem and cannot figure out the solution, can someone help me out?

**Comment by Slapbox** [comment]
@murattishkul afraid not, I can't even get React developer tools to work anymore in my environment. Sorry.
