### ISSUE TITLE
Two examples at slatejs.org don't work

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#547]
**The one that doesn't work as best I can tell are:**

- Auto-markdown

I believe the others are all working properly. I tested these in Firefox and Chrome with several different attempts.

**Comment by Slapbox** [comment]
Scratch that - HTML works. I misunderstood the intention of that one.

**Comment by ianstormtaylor** [comment]
Hey @Slapbox they seem to work for me with a quick test. Can you provide more information on what's not working? and in what browser/os?

**Comment by Slapbox** [comment]
I tried this on two Windows 7 x64 machines in Chrome 55 and Firefox 45 just today. I also tried Internet Explorer, but it can't even load the SlateJS.org page because, you know, Microsoft...

**Comment by Slapbox** [comment]
Also tried Opera 37 just now. Also nothing on the Auto-markdown page. No console errors in any browsers except for favicon.ico not loading.

**Comment by Slapbox** [comment]
Automarkdown works fine. I was trying `>Test` for example when I should have been using `> Test`

(Note the space between the markdown character and the text)

**Comment by oyeanuj** [comment]
@ianstormtaylor Should this need a space between the shortcut and rest of the text? Looking at Github, Slack, etc. it seems that space shouldn't be required.

**Comment by oyeanuj** [comment]
Actually, I kinda take back my above comment. Seems like Medium and some other sites actually do require the space after the shortcut. UX-wise, it also seems to be a safer, and less limiting option (as it allows one to start a sentence with the number 1, for example).
