### ISSUE TITLE
 Node wrapped in Transforms. wrapNodes, with Chinese input method exception at the last position, Abnormal results

### ISSUE THREAD

**Issue by NgChiKin** [ianstormtaylor/slate#5471]
**Description**
 Node wrapped in Transforms. wrapNodes, with Chinese input method exception at the last position

**Recording**
English input method:
![1](https://github.com/ianstormtaylor/slate/assets/57823909/7c6aaca1-1e22-46d3-a9f8-a3d3b2a76e3a)

Chinese input method:
1.  Not focusing to the end

![2](https://github.com/ianstormtaylor/slate/assets/57823909/4efb8529-d611-4d7d-883a-27879959b5e4)

2. Focus to the end, Abnormal results
![3](https://github.com/ianstormtaylor/slate/assets/57823909/f50b44d2-e481-4d5f-b164-efb96839d33f)

**Sandbox**
 demo:  https://www.slatejs.org/examples/inlines

**Steps**
1. click to the last position of the wrapNodes
3. switch to Chinese input methods for computers
4. tap any letter on the keyboard
5. see error

**Expectation**
resolve

**Environment**
- Slate Version: www.slatejs.org/examples version
- Operating System: windows 10
- Browser: Chrome 114.0.5735.134

**Comment by OldDream** [comment]
`yarn run build:next` always fail in my computer, so I can't reproduce the bug in my computer. Any one start `next ` successfully ？
