### ISSUE TITLE
preserve block type when joining with empty adjacent node

### ISSUE THREAD

**Issue by eugenkiss** [ianstormtaylor/slate#548]
This issue is about discussing the general problem of what should happen when joining or splitting lines resp. adjacent block nodes where the types of the block nodes differ. Specifically, empty lines seem to make the problem more complicated.

The default behavior is as follows. Removing a line break joins the previous and current node such that "the current node gets the style of the previous node (e.g. header gets paragraph style)". Conversely, creating a new line applies the style of the previous line. In some sense it's a nice symmetric behavior but not conventional in all situations.

For example (https://streamable.com/z0v6c), suppose you have a header block node and a paragraph block node and the situation is the following:

```
Some paragraph text

<caret>Header
```

When you press backspace the `Header` block is joined with the previous empty line and the header styling is lost. It appears that the previous block is dominant by default. However, it would be more conventional if pressing backspace in the above situation would keep the header and its styling because the line above the header is empty. If you'd press backspace again then losing the header styling is justified (because there is no empty line between the paragraph and header anymore).

------------

I was thinking about adding special cases to the `onDocumentChange` handler. The idea for handling joins is to get the last transformation type, check if it's 'join_node', then check if the new node is empty and if yes "apply the style" of the second node. In code:

```
  getTopmostParent = (key: string) => {
    const parent = this.state.document.getParent(key)
    const depth = this.state.document.getDepth(parent.key)
    if (depth > 1) return this.getTopmostParent(parent.key)
    return parent
  }

  getLastTransform = (state) => {
    if (state.history.undos && state.history.undos._head && state.history.undos._head.value && state.history.undos._head.value.length) {
      return state.history.undos._head.value[state.history.undos._head.value.length - 1]
    }
    return null
  }

  onDocumentChange = (state) => {
    const lastTransform = this.getLastTransform(state)
    if (lastTransform != null && lastTransform.type === 'join_node') {
      const newNode = this.getTopmostParent(state.selection.startKey)
      const oldNode = this.getTopmostParent(this.prevState.selection.startKey)
      if (newNode.isEmpty && oldNode.type === 'header') {
        state = state.transform().setBlock('header').apply({ save: false })
      }
    }
    // ...
  }
```

What do you think. Is this a good approach?

Regarding splitting. The use case I want to implement is that you cannot have a header that contains a new line. If you press enter while the selection is somewhere in-between the characters of the header, it should be split into two headers. This works by default. However, when pressing at the end of a header a new paragraph should be inserted. This is how I implemented the latter behavior:

```
  onKeyDown = (event, data, state) => {
    if (event.key === 'Enter') {
      const node = this.getTopmostParent(state.selection.startKey)
      if (node.type === 'header' && state.selection.isAtEndOf(node)) {
        return state.transform().insertBlock('paragraph').apply()
      }
    }
  }
```

It works but I wonder if there is a better approach.

**Comment by ianstormtaylor** [comment]
Hey @eugenkiss thanks for bringing this up. I completely agree with you for the previous-empty-line use case, we should keep the current line's `type/data` in that case. 

As for where to add that, I think it would involve changing the logic inside the [`deleteAtRange` transform](https://github.com/ianstormtaylor/slate/blob/master/src/transforms/at-range.js#L102-L116) where it handles the case of delete's across blocks. I'd be happy to accept a pull request that updates that logic! Let me know if you need any more guidance on it.

And as for the `onKeyDown` behavior question, that looks good to me. There might be a slightly simpler way to do it though:

```js
if (event.key != 'enter') return
const { selection, startBlock } = this.state
if (selection.isExpanded) return
if (startBlock.type != 'header') return
if (!selection.isAtEndOf(startBlock)) return
return state.transform().insertBlock('paragraph').apply()
```
