### ISSUE TITLE
How to convert custom HTML?How to keep the property style?

### ISSUE THREAD

**Issue by saymy** [ianstormtaylor/slate#550]
How to convert custom HTML?Such as the following HTML:

`<div class="comp-text"><p style="text-align:justify;">富文<code>本模</code>块</p><h2>新内容</h2><p>增加了内容和颜色&nbsp;</p><p>no color<span style="color: rgb(251,160,38);">color01</span>no color<span style="color: rgb(0,168,133);">color01</span>no color</p></div>`

**How to keep the property style?**

**Comment by ianstormtaylor** [comment]
Hey @saymy it depends on your use case, but if you're just trying to keep the `color` style there you might want to create a `data.color` property in the `Node` in question's `data` property—which is reserved for custom data. Then you can render that `data.color` value as part of your rendering logic.

If you want to keep more complex information, you might need to store it as a string, or some other serialized format. But `Node.data` is a good starting point.

**Comment by saymy** [comment]
thanks
