### ISSUE TITLE
Soft breaks not detected in macOS Safari

### ISSUE THREAD

**Issue by peteshilling** [ianstormtaylor/slate#5500]
**Description**
Soft breaks (shift + enter) are interpreted as hard breaks in Safari. They are detected correctly in Chrome. I tested the 'is-hotkey' library and 'shift+enter' works fine in Safari, so the bug must be somewhere in the Slate library. If no one has any ideas I can dig deeper and attempt to identify the issue. 

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-kxss7c?file=/index.tsx

**Steps**
To reproduce the behavior:
1. Visit the sandbox above in Safari
2. Focus the editor and press shift + enter
3. An alert will appear saying that a hard break, not a soft break, was detected

**Expectation**
Soft breaks should be detected in Safari as they are in Chrome.

**Environment**
- Slate Version: 0.94.1
- Operating System: macOS 13.2.1  
- Browser: Safari 16..3

**Context**
One of the requirements for my editor is that hard and soft breaks are treated differently (double space vs single space)

**Comment by frellica** [comment]
I don't think it is a bug of slate. Please check this demo out: https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType . The behaviour is as same as your demo.
I also found this issue: https://github.com/ckeditor/ckeditor5/issues/13321

And, the "is-hotkey" lib seems only to be using under no HAS_BEFORE_INPUT_SUPPORT env. Enters are handled here: https://github.com/ianstormtaylor/slate/blob/a81f76f3a328869a20cc45cb581f6129eba7ccea/packages/slate-react/src/components/editable.tsx#L676

I suppose that there could be a new feature like checking the shift key's status in some ways if you wanna separate line breaks in safari

**Comment by peteshilling** [comment]
Thanks for your reply, @frellica. It looks like you are correct, I wasn't looking deep enough. For whatever reason Safari has designated control+return for the insertLineBreak event type. 

I may end up making a special rule for this, since our users expect shift + return to produce a line break, but it doesn't seem like something that Slate should need to account for.
