### ISSUE TITLE
How to get a selected text?

### ISSUE THREAD

**Issue by mkozhukharenko** [ianstormtaylor/slate#551]
If I have next text in the editor
```
Example text here
Another paragraph
```
And when I select word `text` and print to console `state.focusText.text` - I got whole `Example text here` sentence. Bu I wan to get `text` word instead. I tried bunch of methods - but no one seems to work.

I guess I can get selected work by using `state.startOffset` and `state.endOffset` properties  ( or `state.focusKey`) - but I don't know how.

Slate should have some convenient method for this case. Am I right?

**Comment by mkozhukharenko** [comment]
```js
let {startOffset, endOffset, focusText} = this.props.editorState
const text = focusText.text.slice(startOffset, endOffset)
```
This solution works. 

But is seems a little cumbersome.

**Comment by Mavrin** [comment]
@mkozhukharenko You can get selected text from fragment `salteState.fragment.text`

**Comment by bmsterling** [comment]
I know this was closed, but wanted to add for historical purposes.

I'm creating a plugin and listening to the `onSelect` and if I do `console.log(state.fragment.text)` it comes back empty, if do the following, it's set to the selected text:

```
setTimeout(() => {
  console.log(state.fragment.text);
}, 0);
```

Not sure if this is a bug or if I should be using something other than `onSelect`.

**Comment by linonetwo** [comment]
My god, why isn't these API in the document. Maybe I could make a PR.

**Comment by linonetwo** [comment]
It's now ```value.fragment.text```, where ```value``` is from ```change.value```.
https://docs.slatejs.org/slate-core/value#fragment

**Comment by rohmanhm** [comment]
@linonetwo what about now? I'm using `slate@0.57.1`

**Comment by 5-10** [comment]
There's `Editor.string` function that can be used to get the text at the selection.

`const selectedText = Editor.string(editor, editor.selection);`

**Comment by Pines-Cheng** [comment]
Thanks，This help me a lot~

**Comment by martinpi** [comment]
None of these seem to work for me. Any hint on what I could be doing wrong? Currently trying:

`editor.selection ? Editor.string(editor, editor.selection) : "<no selection>";`

It just returns an empty string.

**Comment by joschan21** [comment]
@martinpi what do you mean by "all works in the callback"? I'm having a similar issue and was wondering how you've solved it. 
The problem is that the editor.selection does not update, so it's never what's actually selected.

I've tried multiple ways of initializing the editor (useMemo, useState, useRef) and the closest I've gotten to actually logging out the selection text was either with setInterval logging it every few seconds or always being one step behind the actual selection through state.

You mind sharing your solution?

**Comment by martinpi** [comment]
I have switched over to useState:

`const [editor] = useState(() => withReact(withHistory(createEditor())))`

I have a function (in the React component) that gets called `onClick` that has a the correct selection set. I think my mistake was to call a function outside the component but honestly I don't remember.
