### ISSUE TITLE
Derive `onSelectionChange` and `onValueChange` from `onChange`

### ISSUE THREAD

**Issue by zbeyens** [ianstormtaylor/slate#5521]
**Problem**
`onChange` currently triggers for all changes: value and selection. When I only want to listen to value changes, this is not optimal.

**Solution**
Keep `onChange` and add `onSelectionChange` to listen to selection change only and `onValueChange` to listen to value change only.

Bounty: https://github.com/udecode/plate/issues/2700

**Comment by rishi-raj-jain** [comment]
@zbeyens 

`onValueChange` from useStateSelector where type of op is `set_selection` would the right logic, right?

**Comment by rishi-raj-jain** [comment]
@zbeyens @12joan 

`onValueChange` from useStateSelector where type of op is `set_selection` would the right logic, right?

**Comment by zbeyens** [comment]
The goal is to listen to value change only, all operations except `set_selection`. We want to avoid using an `equalityFn` like in `useSlateSelector`.

**Comment by rishi-raj-jain** [comment]
Ah so totally a different hook.

**Comment by zbeyens** [comment]
1. The ﻿`onSelectionChange` function should only listen to the ﻿`set_selection` operation, not all operations.
2. Conversely, the ﻿`onValueChange` function should only listen to the other operations, excluding ﻿`set_selection`.

The solution needs to be built exactly like `onChange` prop. No hook is expected, only `Slate` props.
