### ISSUE TITLE
Expose history

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#554]
Hi,
it would be great if history have exposed API. In our case there are multiple editors on page and we have to work with single history on whole page, not per every editor.

Right now we could not leverage Slate history and have to write all logic again.

**Comment by ianstormtaylor** [comment]
Hey @Mangatt, good call, I agree with you. We should figure out a way to make multiple-editor-history use cases easier. What API were you thinking about? Are you using Redux?

**Comment by Mangatt** [comment]
This question precedes my following issue. There should be way how to have only one state for multiple editors which could solve this immediatelly.

Now I know that even with exposed history there are cases that would render this API useless. Namely moving block between two editors, which would make snapshot in both editors. And even when moving block is single operation, it would require two undos, which is really counterintuitive.

Yes, I am using redux.

**Comment by marcusmateus** [comment]
👍 on this.  It would be great to be able to display undo / redo depth via history.undo.size.  Also, I was hoping to use history as a proxy of when to save the document to disk / cloud... though perhaps onDocumentChange works well enough for that.

**Comment by lxcid** [comment]
My use case is similar to @Mangatt. I would suggest that the history API is something we could remove from editor. As a separate pluggable component to editor.

**Comment by ianstormtaylor** [comment]
The `History` object is exposed now in `0.22`!
