### ISSUE TITLE
Single state for multiple editors

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#555]
We are currently using multiple editors at single page and quite a lot logic have to be overwritten. It would be great to have option to have only one single state for them and using only slice of state in editor.

I guess that since editor document is node as well, it should not be that complicated. State could have documents property and we could set document attribute when rendering editor.

This should make life a whole lot easier in lot of cases since this applies to nested editors as well and they are quite common use case.

**Comment by Mangatt** [comment]
After some research I think that this could be done with context. It would require creation of 2 new components: SlateContext as context provider and NodeEditor that would render editor for specific node.

```javascript
<SlateContext>
   <MyComponent />
   <NodeEditor key="8" />
   <OtherComponent>
      <NodeEditor key="11" />
   </OtherComponent>
</SlateContext>
```

That would effectively split current editor functionality into two separate pieces. SlateContext handles state but not rendering itself, that would be job of NodeEditor. Current Editor component would look like that:

```javascript
<SlateContext>
   <NodeEditor key={state.document.key} />
</SlateContext>
```

**Comment by Mangatt** [comment]
Ok, there's a quick fix that achieves this goal even without context.

`components/editor: 243-256 (pass down children)`
```javascript
return (
      <Content
        {...handlers}
        editor={this}
        onChange={this.onChange}
        schema={this.getSchema()}
        state={this.getState()}
        className={props.className}
        readOnly={props.readOnly}
        spellCheck={props.spellCheck}
        style={props.style}
	children={props.children}
      />
    )
```
`components/content: 725 (working with children)`
```javascript
if(props.children){
	return <div
			data-slate-editor
			key={this.forces}
			ref={this.ref}
			className={className}
			onBeforeInput={this.onBeforeInput}
			onBlur={this.onBlur}
			onCompositionEnd={this.onCompositionEnd}
			onCompositionStart={this.onCompositionStart}
			onCopy={this.onCopy}
			onCut={this.onCut}
			onDragEnd={this.onDragEnd}
			onDragOver={this.onDragOver}
			onDragStart={this.onDragStart}
			onDrop={this.onDrop}
			onInput={this.onInput}
			onKeyDown={this.onKeyDown}
			onKeyUp={this.onKeyUp}
			onPaste={this.onPaste}
			onSelect={this.onSelect}
			spellCheck={spellCheck}
		>
		{props.children(children.map(node => <div
			contentEditable={!readOnly}
			suppressContentEditableWarning
			style={style}
		>
			{node}
	        </div>
	       ))}
        </div>
}
```
This basically allows you to work with children nodes of document in this way:
```javascript
<Editor
	plugins={plugins}
	state={state}
	schema={schema}
	onChange={this.onChange}
	children={nodes => {
		return <div>
			<div className='area'>
				<h1>Area 1</h1>
				<div>{nodes[0]}</div>
			</div>
			<div className='area'>
				<h1>Area 2</h1>
				<div>{nodes[1]}</div>
			</div>
		</div>
	}}
/>
```

**Comment by Mangatt** [comment]
Of course better way would be with context and new DocumentNode component, but this will do as well.

**Comment by ianstormtaylor** [comment]
Hey @Mangatt thanks for opening this. My use case involves using multiple editors per page as well. Could you explain what specifically are the parts that become complex to manage when multiple editors are used? 

I imagine history management to be one of them, but not sure if there are others. I'd want to understand those things first before thinking of solutions because there might be very easy solutions. Thanks

**Comment by Mangatt** [comment]
History is probably most important, but working with blocks is way more complicated as well. Focusing is not ideal either, I have to keep track which editor should I focus instead of leveraging built in logic.

**Comment by Mangatt** [comment]
I have in mind something like react-dnd, which requires setting up context and then all targets/sources uses that no matter where are in component structure.

That would open possibilities for more use cases - Editor component could set up both context and DocumentNode, but when is someone working with multiple editors, he could split that up.

In last two days I tried to edit Content component in different ways and it works suprisingly well. But it is still kind of hack, it definitely needs more robust solution.

**Comment by Mangatt** [comment]
Ok, I have solved that and made a pull request: #563 

Summary
- no breaking changes
- no change in performace (context is set up only when required)
- new dependency react-broadcast (simplifies working with context)
- new component NodeEditor with single prop node

Usage is simple: when you pass children to Editor component, it will create editor context for NodeEditors inside that editor. Now you can make editor for any node, you are not even required to render all nodes.

**Comment by ianstormtaylor** [comment]
Hey @Mangatt I'm going to close this one out, since I believe we solved with via the `plugin.render` and this other solution isn't something that I think Slate will concentrate on.

**Comment by tuanhuu** [comment]
HI, how to use many editor in one page

**Comment by ericedem** [comment]
@tuanhuu you will get a better response to questions if you ask in [the slack channel](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md#asking-questions).
