### ISSUE TITLE
Regression: Firefox selection by double click

### ISSUE THREAD

**Issue by k0ka** [ianstormtaylor/slate#5560]
**Description**
Selecting a block in Firefox via double click doesn't allow to remove formatting.

**Recording**

https://github.com/ianstormtaylor/slate/assets/203597/a217e537-8060-4b5f-89f6-8382f4519217

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext
2. Double click on a word to select it.
3. Click on the "bold" button.
4. Deselect.
5. Double click on the same word again to select it.
6. Click on the "bold" button.

**Expectation**
The bold button must be active and the font must get to normal after clicking on the "bold" button again.

**Environment**
- Slate Version: 0.98.0, 0.98.4, 0.101.0
- Operating System: MacOS, Windows 10
- Browser: Firefox

**Context**
This bug was reintroduced in slate-react 0.98.0. It was working properly in slate-react 0.97.2

I think it is the same bug as https://github.com/ianstormtaylor/slate/issues/3336 (or https://github.com/ianstormtaylor/slate/issues/4793) which was fixed in https://github.com/ianstormtaylor/slate/pull/5275 and reintroduced in https://github.com/ianstormtaylor/slate/pull/5486

**Comment by Kaporos** [comment]
+1 with slate version 0.101.1 and firefox 120.0

**Comment by 12joan** [comment]
This can be closed as completed: #5580
