### ISSUE TITLE
Make event data consistent suggestion (breaking change)

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#559]
One reason I love Slate is that it is consistent and predictable and seems to gravitate towards this over time (as opposed to towards more complexity).

This is probably one of the reasons why the current event data helper bothers me. I really like the shortcuts (please don't remove!) but it is inconsistent. In fact, I couldn't remember so I had to look up the source code just now so I could give some examples such as:

- isCtrl: means the ctrl key was pressed but NOT the alt key. But it doesn't matter whether the shift key was pressed or not.
- isAlt: means the alt key was pressed. Any of the other modifier keys may also have been pressed.
- isShift: means the shift key was pressed. Any of the other modifier keys may also have been pressed.
- isMeta: means the meta key was pressed. Any of the other modifier keys may also have been pressed.
- isMod: means the mod key (ctrl on windows or cmd on mac) was pressed but NOT the alt key. The shift key may or may not be pressed.

So basically, there is a combination of sometimes it is checking to see if a modifier key was pressed and sometimes it is checking to see if that modifier key was pressed but not the alt modifier. But why isn't the shift taken into account (which has gotten me into trouble because I assumed it was checking this since it was checking alt).

My proposal is to fix this once and for all by adding both `has[Modifier]` properties that check to see if a key was pressed and ignoring all the other modifier keys and `is[OneOrMoreModifiers]` to check that only that specific combination of modifiers was pressed.

We end up with an object like this for (as an example, CMD-SHIFT on a Mac):

```js
{
  "hasShift": true,
  "hasCmd": true,
  "hasCtrl": false,
  "hasAlt": false,
  "hasMod": true,
  "isCmd": false,
  "isCmdAlt": false,
  "isCmdShift": true,
  "isCmdAltShift": false,
  "isCtrl": false,
  "isCtrlAlt": false,
  "isCtrlShift": false,
  "isCtrlAltShift": false,
  "isMod": false,
  "isModAlt": false,
  "isModShift": true,
  "isModAltShift": false
}
```

Note: The preceding JSON was generated from my actual running code. Just cut and pasted.

The following is the code that I developed that can be merged (with some tweaking of course to make it fit), into SlateJS:

```js
import IS_MAC from './isMac'

export default function (e) {
  const shift = e.shiftKey
  const ctrl = e.ctrlKey
  const alt = e.altKey
  const cmd = IS_MAC && e.metaKey
  const mod = IS_MAC ? cmd : ctrl
  return {
    hasShift: shift,
    hasCmd: cmd,
    hasCtrl: ctrl,
    hasAlt: alt,
    hasMod: mod,
    isCmd: cmd && !alt && !shift,
    isCmdAlt: cmd && alt && !shift,
    isCmdShift: cmd && !alt && shift,
    isCmdAltShift: cmd && alt && shift,
    isCtrl: ctrl && !alt && !shift,
    isCtrlAlt: ctrl && alt && !shift,
    isCtrlShift: ctrl && !alt && shift,
    isCtrlAltShift: ctrl && alt && shift,
    isMod: mod && !alt && !shift,
    isModAlt: mod && alt && !shift,
    isModShift: mod && !alt && shift,
    isModAltShift: mod && alt && shift,
  }
}
```

Noticed I have a few `is[modifier]` properties missing like `isShift`. Anyways, you get the idea. This would all be worked out before a formal PR.

**Comment by ianstormtaylor** [comment]
@thesunny I agree with you about the inconsistency being a problem. Ran into something similar (can't remember the exact case) with the shift key not being accounted for. 

I think I'd sooner lean towards removing the helpers altogether from core, and instead someone could package them as a separate module if they really wanted them. And the API could be made even nicer potentially, like:

```js
isKey(e, 'cmd', 'alt', 'x')
```

For handling arbitrary key commands too.

**Comment by thesunny** [comment]
@ianstormtaylor I'm behind this. I heard you mention it before.

One thing with the current version is that I do like the fact (immensely) that I didn't need to import a module to get access to data.isShift and friends. What do you think of adding `isKey` to `data` as a property. It should be cheap (performance-wise) to add since all we would do is bind `iskey` to the event and add it to `data`.

That way we could do something like

```js
{
  onKeyDown(e, {isKey}) {
    if (isKey('mod', 'b')) {
      // bold some text
    }
  }
}
```

This could also maintain backward compatibility. At some point, we could deprecate and then remove isMod, isShift, etc.

At the end, the `data` argument may end up with `isKey` only but it is also somewhat future proof. For example, maybe we want to have `hasKey` or some other helpers in the future.

But even with just `isKey` it should improve performance eventually because once we get rid of the other `data` properties, we would only be doing lazy key testing. With `isShift` and friends, they are pre-computed.

At any rate, if you like this idea, I would be willing to make an implementation.

**Comment by ianstormtaylor** [comment]
@thesunny I think there's an even simpler way which is to use from the `event` object properties instead, since they already have `shiftKey` and others. So you could do:

```js
onKeyDown(e, data) {
  if (data.key == 'b' && e.ctrlKey) {
    // do some stuff
  }
}
```

I do agree though that this is slightly less useful, since you'd need to do the `IS_MAC ? e.metaKey : e.ctrlKey` checking yourself which is a pain. For that reason, I could be convinced to change the `data` key helpers to more closely mimic the native ones:

```js
// the native ones
data.shiftKey
data.ctrlKey
data.altKey
data.metaKey
// an additional one (meta on mac, ctrl on windows)
data.cmdKey
// a few additional helpers
data.isCmd // cmdKey && !altKey && !shiftKey
data.isCmdAlt // cmdKey && altKey && !shiftKey
data.isCmdAltShift // cmdKey && altKey && shiftKey
// the existing helpers
data.isLine
data.isWord
// and remove the other existing ones
```

This way, the low-level key information is exposed and normalized usefully with the native defaults and `cmdKey` as a cross-platform convenience. And then we change the `is*` helpers slightly to make the super common "hotkey binding" use case easier.

Such that a basic hotkey would look like:

```js
onKeyDown(e, data) {
  if (data.key == 'v' && data.isCmdAlt) {
    // do stuff...
  }
}
```

What do you think of that? I'd definitely be willing to accept a PR if you're interested!

**Comment by thesunny** [comment]
@ianstormtaylor

There's a few things that I think could be improved:

- I think we should stick with `data.modKey` to mean meta on mac, ctrl on windows because (a) this is consistent with what you had before and made sense to me and (b) on Mac, the command key is a specific key. To have it then mean cmd or ctrl depending on the OS seems confusing.

- I feel like we need to support the other modifier key combinations. I already use more than just the meta on mac/ctrl on windows combinations and I don't think it's uncommon to do this. A change that just involves isCmd and friends won't help me personally at the least.

This is a list of Google Docs shortcuts https://support.google.com/docs/answer/179738?co=GENIE.Platform%3DDesktop&hl=en and you can see there are many key combinations that don't involve the `isCmd` and friend combinations.

I actually feel like it would be valuable (in my use case anyways) to have an isMac property. This would also jive with the requirements for implementing the Google Docs shortcuts for example.

**Comment by thesunny** [comment]
In going through that Google Docs list, there are actually some interesting combinations in there like Cmd+Ctrl+KEY in there. In this case, the Mac version even needs to support the less often seen combination of Cmd along with Ctrl.

I'm all in for either the `isKey('ctrl', 'shift', 'k')` type solution or the `data.isCtrlAlt` but only with all the possible combinations. I'm less in on a solution that feels like it only solves part of the use cases because I think we already have a useful-but-not-quite-perfect solution where we have to work around it. Feels like a waste to replace it with a better-but-still-not-quite-perfect-solution.

**Comment by thesunny** [comment]
I know you were leaning away from `isKey` for the moment but as a thought exercise I implemented an `isKey` method to see how much code would be required. I actually haven't run it so probably needs debugging but still useful to judge how much code would be executed and the complexity of such.

```js
import IS_MAC from './isMac'

export default function isKey(e, keys) {
  const shift = e.shiftKey
  const ctrl = e.ctrlKey
  const alt = e.altKey
  const meta = e.metaKey
  const mod = IS_MAC ? metaKey : ctrlKey

  const eventModifiers = {shift, ctrl, alt, meta}

  const matchModifiers = {
    shift: false,
    ctrl: false,
    alt: false,
    meta: false,
  }
  const matchKey = null

  keys.forEach((key) => {
    if (['shift', 'ctrl', 'alt', 'meta', 'mod'].includes(key)) {
      if (key === 'mod') key = IS_MAC ? 'meta' : 'ctrl'
      matchModifiers[key] = true
    } else {
      if (key.length > 1) throw new Error("Unrecognized key")
      if (keyToCheck) throw new Error("More than one non-modifier key was provided to the list of keys")
      matchKey = key
    }
  })

  if (e.key !== matchKey) return false

  for (let [eventKey, eventValue] of Object.entries(eventModifiers)) {
    const matchValue = matchModifiers[eventKey]
    if (eventValue !== matchValue) return false
  }
  return true

}
```

When I was done writing it (as often does) a new set of problems popped into my head. Namely that `isKey` would need to be executed for every plugin that had to parse the key. The specific problem is that the performance impact gets bigger the more hotkeys there are that need to be checked. In other words, this punishes apps with a lot of keys (where performance matters most). The pre-calc method is better when there are lots of plugins.

I also see the issue that I think you are trying to avoid which is having to many `data.isCmdCtrlAltShift` like combinations.

I have two alternatives to consider.

1. instead, we implement `isKey(key, modifiers)` which is called something like `isKey('k', ['ctrl', 'shift'])`. The reason why this is different and better is because we can short-circuit if the `key` argument doesn't match. We only do the relatively complex and compute-intensive modifiers tests if the key test passes.

2. Another alternative is to implement `isModifier` which doesn't check the specific key itself. The developer would be responsible for checking that him/herself. In order to improve performance, they would have to make sure they short-circuit based on the key first.

#1 is the safer route in that it doesn't allow the developer to forget to short-circuit based on the keypress. 

All this said, I also think it's not so bad to simply add all the modifiers to the `data` object.

Sorry for the extremely long discussion here. :)

**Comment by thesunny** [comment]
Also some sample code for handling all the key combinations.

```js
import IS_MAC from './isMac'

export default function getData(e) {
  const modKey = IS_MAC ? e.metaKey : e.ctrlKey
  const bools = [true,false]
  const keys = ['is']
  const data = {
    modKey,
    metaKey: e.metaKey,
    ctrlKey: e.ctrlKey,
    altKey: e.altKey,
    shiftKey: e.shiftKey,
  }
  bools.forEach((meta) => {
    const keysWithMeta = meta ? keys.concat('Meta') : keys
    const matchWithMeta = meta === e.metaKey
    bools.forEach((ctrl) => {
      const keysWithCtrl = ctrl ? keysWithMeta.concat('Ctrl') : keysWithMeta
      const matchWithCtrl = matchWithMeta && ctrl === e.ctrlKey
      bools.forEach((alt) => {
        const keysWithAlt = alt ? keysWithCtrl.concat('Alt') : keysWithCtrl
        const matchWithAlt = matchWithCtrl && alt === e.altKey
        bools.forEach((shift) => {
          const keysWithShift = shift ? keysWithAlt.concat('Shift') : keysWithAlt
          const matchWithShift = matchWithAlt && shift === e.shiftKey
          data[keysWithShift] = matchWithShift
        })
      })
    })
  })
}
```

A few comments on the code:

- It should execute actually quite fast. I moved as much code to the outer parts of the loop as I could so the actually total code running should be low. I haven't handled the special `mod` case in here but it should be just one more loop with a few if/else clauses in the inner loops.
- It's still not super optimizes so I could get it to run faster probably by using traditional `for` loops instead of `forEach` and I have a feeling it would run faster without using the ES6 style bound function declarations. Anyways, I think the impact on code execution time should be minimal, it would handle all the cases, and it's not a lot of code to add to the code base.

**Comment by ianstormtaylor** [comment]
Hey @thesunny thanks for thinking this through more.

Using `modKey` instead of `cmdKey` makes sense to me, I like that!

I think the `isKey` approach might have performance implications, like you alluded to. I'm less worried about the implications of having every plugin run the method, and more worried about adding too much functionality to the event handlers, especially creating many closured functions on each event.

I think if we add `modKey`, and change the `is*` keys to match, we'll end up with a very simple to implement strategy from contents's side that lets you do things like:

```js
onKeyDown(e, data, state) {
  if (data.modKey && !data.altKey && data.key == 'k') {
    // ...
  }
}
```

And then there's an option, if we really want to, to add a helper that makes key matching easier, and expose it as a util, similar to `findDOMNode`. Maybe something like:

```js
onKeyDown(e, data, state) {
  if (isHotkey(data, 'mod+k')) { // or isHotkey(e, 'mod+k')
    // ...
  }
}
```

And it would be smart about only triggering when the specific keys were pressed, and not other modifier combinations. But honestly, I'm leaning more towards just making that a completely separate, Slate-agnostic module that people can use if they want to. After a pretty in depth search of NPM it's insane that something simple like that doesn't exist.

**Comment by oyeanuj** [comment]
+1 to this thread and last solution above! I ran into the same issue as @thesunny, not knowing that `isMod` included (not `isAlt`).

**Comment by oyeanuj** [comment]
@thesunny @ianstormtaylor If we are going by the way of creating a utility, here is another suggestion request. 

Something I find myself craving for is something which indicates that none of the optional modifier keys were present (`hasNoSpecialKeys` or `onlySingleKeyPressed`). I have a few different plugins that look for shortcuts, markdown, etc and some of them where I want to just perform some behavior on, lets say, the `enter` key.  

It is easy to do for developers and make it a utility function within their code, but could also be nice to have in this keyboard utility proposed by @ianstormtaylor.

**Comment by danburzo** [comment]
In [Moqups](https://app.moqups.com) we define shortcuts as simple objects that contain a `match` against the event, and optional flags (`passthrough`, `triggerInInput`, etc.):

```js
import { keys } from 'js/constants';

/*
	Text style: Link Prompt
	Shortcut: Cmd + K
*/

export default {
	toString: () =>'link prompt',
	match: e => (e.metaKey || e.ctrlKey) && !e.shiftKey && !e.altKey && e.which === keys['k']
}
```

and then for mapping shortcuts to actions:

```js
const keydown_actions = [
	{ when: BoldShortcut, perform: PreventDefaultAction },
	{ when: ItalicShortcut, perform: PreventDefaultAction },
	{ when: UnderlineShortcut, perform: PreventDefaultAction },
	{ when: DeleteShortcut, perform: PreventDefaultAction },
	{ when: DuplicateShortcut, perform: PreventDefaultAction },
	{ when: SelectAllShortcut, perform: SelectAllAction },
	{ when: UndoShortcut, perform: UndoAction },
	{ when: RedoShortcut, perform: RedoAction },
	{ when: PanShortcut, perform: PanAction },
	{ when: DiagrammingToggleShortcut, perform: DiagrammingToggleAction },
	{ when: HotspotAddShortcut, perform: HotspotAddAction },
	{ when: HotspotAddForSelectionShortcut, perform: HotspotAddForSelectionAction },
	{ when: GridSnapShortcut, perform: UserOptionToggleAction('snap_grid') },
	{ when: GridToggleShortcut, perform: DocOptionToggleAction('grid_visible') },
	{ when: GuidesToggleShortcut, perform: DocOptionToggleAction('guides_visible') },
	{ when: LayoutToggleShortcut, perform: DocOptionToggleAction('columns_visible') },
	{ when: RulersToggleShortcut, perform: DocOptionToggleAction('rulers_visible') },
	{ when: ObjectSnapShortcut, perform: UserOptionToggleAction('snap_objects') },
	{ when: PageSnapShortcut, perform: UserOptionToggleAction('snap_page') },
	{ when: InspectShortcut, perform: InspectStartAction }
];
```

...and just iterate through the Array until the first shortcut matches. 

Because we often have shortcuts that apply to both RTE and outside, it makes for a useful abstraction that allows us to reuse these Shortcuts.

I find it's easier to reason about the state of the four default modifier properties on the `KeyboardEvent` then having to remember what the property name for a specific combination is.

The way I see it, I'd have a `shortcut-utils` from which I can import:

```js
import { Bold, Italic, Underline, ... } from 'shortcut-utils'

const keydownActions = [{ on: Bold, perform: this.doBold } ... ]

onKeyDown(e, data, state) {
   const action = keydownActions.find(action => action.on.matches(e))
   if (action) return action.perform(...args)
   return false
}
```

**Comment by danburzo** [comment]
As for how to handle they keyboard shortcuts, leaving these here for reference: https://developers.google.com/web/updates/2016/04/keyboardevent-keys-codes
