### ISSUE TITLE
add drag/drop support

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#56]

**Comment by oyeanuj** [comment]
DraftJS plugins that you referred to now has DnD support in their 2.0:

https://github.com/draft-js-plugins/draft-js-plugins/tree/master/draft-js-dnd-plugin

**Comment by ianstormtaylor** [comment]
Added to core in `0.6.3`!

It's handled similarly to contenteditable, in that you specific blocks aren't draggable, but when you create a selection, you can drag that selection to somewhere else in the document. And things can be dragged from outside of the document, by default only text is handled, but plugins can hook into the `onDrop` handler.

**Comment by RickBross** [comment]
Where is the documentation for this functionality @ianstormtaylor
