### ISSUE TITLE
Allow plugins to add transformations

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#561]
Since Slate is built around plugins I think that it would be nice if plugins could add transformations that we could use as those native ones.

Currenty when plugin adds those, we are forced to use them differently and final code is definitely much less straightforward.

**Comment by ianstormtaylor** [comment]
Hey @Mangatt thanks for opening this! We've considered a few similar ideas in the past, in https://github.com/ianstormtaylor/slate/issues/213 https://github.com/ianstormtaylor/slate/issues/482 but eventually decided that allowing plugins to have declare their own top-level transforms would get too complicated for a bunch of reasons, and instead @thesunny added the `.call()` syntax to help make third-party transforms nicer to work with. Feel free to ask more questions though if you see something we missed!

**Comment by Mangatt** [comment]
Sorry @ianstormtaylor , I should did my research first. I was aware of problems that comes with that, but this was more of a philosophical question. When Slate wants first class plugins, they should be able to work with core.

From my point of view, plugin capabilities are now somehow limited. And I don't think that making guidelines / boilerplate for plugin creation is necessarily a bad thing, it would definitely make whole Slate ecosystem more consistent.

**Comment by ianstormtaylor** [comment]
@Mangatt I'm not sure I understand. What are the plugin capabilities that are limited? And what boilerplate are you thinking of?

**Comment by Mangatt** [comment]
I was referring to discussion at #482 and to your comment about call solution is less boilerplate-y. Limited in way that they can only react to events from editor, they can't fully extend slate functionality.

I might be explaining this in wrong way, but I am trying to bend Slate to our needs for couple of days and in most cases plugins won't do. I have to stick with modifiying core itself.

Namely (from my other issues):
- play with the history
- modify rendering logic
- implement their own shouldComponentUpdate

But those are just my opinions, I'm sorry if that's becoming a bit annoying.

**Comment by ianstormtaylor** [comment]
No worries, it's not annoying—you've brought up some good points. I think in terms of the transforms (this issue) the plugins seem to be pretty fine. But it sounds like you're going for a use case that hasn't really been considered before, or at least in the way you're approaching it—splitting the editor up inside of document itself, instead of by using multiple documents. I think it has merit, and may even be a better way to do what I'm currently doing, it's just not something I've experimented with yet.
