### ISSUE TITLE
Question: How do i use this with webpack ?

### ISSUE THREAD

**Issue by eelsweb** [ianstormtaylor/slate#566]
While trying to integrate it with webpack, i get the following error:

```
ERROR in ./~/slate/~/cheerio/~/entities/maps/decode.json
Module parse failed: {path}\node_modules\slate\node_modules\cheerio\node_modules\entities\maps\decode.json Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
```

If I include the `json-loader` loader, then i start getting this error:

```
Module build failed: SyntaxError: Unexpected token i
    at Object.parse (native)
    at Object.module.exports ({path}\node_modules\json-loader\index.js:7:48)
 @ multi path
```

Am I doing something wrong here ?

**Comment by eelsweb** [comment]
I believe this has something to do with [this issue](https://github.com/webpack-contrib/json-loader/pull/11)

**Comment by eelsweb** [comment]
solved it

**Comment by oyeanuj** [comment]
@eelsweb Ran into this as well. Can you share your solution?

**Comment by pigareva** [comment]
Could someone share webpack config please! I stuck with `Module build failed: SyntaxError: Unexpected token`

**Comment by eelsweb** [comment]
hey @oyeanuj @pigareva .. sorry .. i no longer remember how exactly i solved this.. perhaps if you shared your `webpack.config` .. i might remember what i changes.. this is what the `module` key should look like (i hope :) )

 	module: {
		loaders: [{
			test: /\.js?/,
			include: srcDir,
			loaders: ['babel-loader']
		}, {
			test: /\.json$/,
			loaders: ['json-loader']
		}, {
			test: /\.scss/,
			loaders: ['style-loader', 'css-loader', 'sass-loader']
		}, {
			test: /\.css/,
			loaders: ['style-loader', 'css-loader']
		}]
	}

**Comment by pigareva** [comment]
@eelsweb thanks a lot! I solved it with a proper .babelrc, which is in my case 
`{
  "presets": [
    "react",
    ["env", {
      "targets": {
        "browsers": [
          "last 2 Chrome versions",
          "last 2 Firefox versions",
          "last 2 Edge versions"
        ]
      }
    }],
    "stage-0"
  ]
}`
"stage-0" preset looks to be very important.
