### ISSUE TITLE
ReactEditor.focus triggers onValueChange unexpectedly

### ISSUE THREAD

**Issue by gwy15** [ianstormtaylor/slate#5672]
**Description**
Playground: https://codesandbox.io/s/api-focus-triggers-onvaluechange-dlsfxx?file=/src/App.tsx:962-975

for a simple `<Slate />`, mannually focus / blur using cursor does not trigger its `onValueChange` event.
However if using `ReactEditor.focus(editor);`, `onValueChange` event is triggered (and only for the first call, weirdly).

**Recording**
![20240704170143_rec_](https://github.com/ianstormtaylor/slate/assets/23229760/cb6e4b04-d481-4d3b-aad4-43cac1a493fb)

**Sandbox**
https://codesandbox.io/s/api-focus-triggers-onvaluechange-dlsfxx?file=/src/App.tsx:962-975

**Steps**
To reproduce the behavior:
1. Go to [Sandbox](https://codesandbox.io/s/api-focus-triggers-onvaluechange-dlsfxx?file=/src/App.tsx:962-975)
2. Click on the button
3. a onValueChange event is triggered.

**Expectation**
A consistent behavior (i.e., either both mannually focus and api focus triggers the onValueChange event, or neither does, which I guess is more reasonable.

**Environment**
- Slate Version: 0.103
- Operating System: macOS
- Browser: Chrome and Safari
- TypeScript Version: 3.7.5

**Comment by WindrunnerMax** [comment]
In the current implementation, focusing (by ReactEditor.focus) from editor.selection being null to a specific value will inevitably trigger OnChange. 

Maybe handling it during the apply phase, [like here](https://github.com/WindrunnerMax/DocEditor/blob/master/packages/core/src/event/index.ts#L22), would be more appropriate.

**Comment by WindrunnerMax** [comment]
Before this issue is resolved, I think you can use `editor.apply` to dispatch events, something [like this](https://github.com/WindrunnerMax/DocEditor/blob/4adc9b8/packages/core/src/event/index.ts#L22).
