### ISSUE TITLE
InsertText operation find wrong editor when be in nested slate editor

### ISSUE THREAD

**Issue by kikouousya** [ianstormtaylor/slate#5687]
**Description**
InsertText operation find wrong editor when be in nested slate editor

**Recording**
![11](https://github.com/user-attachments/assets/d188ddc4-b0f0-4fda-800a-29370a2569ec)

**Steps**
when type something in nested sub editor, it selected to main editor in same path, and inserted words in main editor instead of in sub editor.
I found that many operation can find correct editor(like setSelection when click, setNodes, etc.), but when type words, it gose very wrong: if curSelection in sub editor (like [0,1]), it will firstly apply setSelection in main Editor with [0,1], and then insertText to main one.

**Expectation**
if main editor has no path that same to selection in sub editor, it would say
react-editor.ts:831 Uncaught Error: Cannot resolve a Slate point from DOM point: [object Text],1
    at Object.toSlatePoint (react-editor.ts:831:13)
    at Object.toSlateRange (react-editor.ts:994:32)
    at HTMLDivElement.<anonymous> (editable.tsx:623:39)

**Environment**
- Slate Version: latest
- Operating System: Window10
- Browser: Electron
- TypeScript Version: [e.g. 3.9.7 - required only if it's a TypeScript issue]

**Context**
A simplified code here
```typescript
const newEditor = (id) => {
  const editor = withReact(createEditor()) as any
  return({
    id,
    apply: o => {
      console.log(editor.id, o)
      editor.apply(o)
    },
    ...editor
  })
}


export const TestSlateEditor = (props) => {
  const editor = useMemo(() => newEditor("main"), [])
  return <>
    <SlateE editor={editor} initialValue={[
      {type: "paragraph", children: [{text: "t12323231"}]},
      {type: "subEditor", children: [{text: ""}]}
    ]} />

  </>
}
const ElemRenderer = ({element, children, attributes}) => {
  if (element.type == "subEditor") {
    return <p

      {...attributes}> {children} <SlateE editor={newEditor("sub")} initialValue={[{text: "editor2"}]} /></p>
  } else {
    return <p {...attributes}>{children}</p>
  }
}
const Leaf = ({attributes, children, leaf}) => {
  // console.log("leaf", {attributes, children, leaf})
  children = getMarked(leaf, children)
  return <span {...attributes}>{children}</span>
}
const SlateE = ({editor, initialValue}) => {
  const renderer = useCallback((props) => {
    return <ElemRenderer {...props} />
  }, [])
  const renderLeaf = useCallback(props => {
    return <Leaf {...props} />
  }, [])
  return <div style={{border: "1px solid darkgrey"}}>
    <Slate
      editor={editor}
      initialValue={initialValue}>
      <Editable renderElement={renderer} />
    </Slate>
    <DevInfo obj={{editor}} />
  </div>

}

```

**Comment by kikouousya** [comment]
I tried To record current selected editor, 
```typescript
export const SlateEditorInfo = {}
// ...
onMouseDown={event => {
      SlateEditorInfo.selectedEditorId = editor.id
      event.stopPropagation()
    }}>
```
and when it gose wrong, redirect operation to right one
```typescript
  editor.apply = (operation) => {
    try {
      if (SlateEditorInfo.selectedEditorId && SlateEditorInfo.selectedEditorId !== editor.id) {
        const targetEditor = SlateEditorInfo.editors[SlateEditorInfo.selectedEditorId]
        if (targetEditor) {
          return targetEditor.apply(operation)
        }
      }
```
It would works only first word, because the oparetion setSelected after a word inserted triggered, used a new path that relative to main editor. Applying that in sub editor would be a wrong selection.

**Comment by WindrunnerMax** [comment]
Maybe you can refer to this https://www.slatejs.org/examples/editable-voids

**Comment by kikouousya** [comment]
> Maybe you can refer to this example https://www.slatejs.org/examples/editable-voids

So what I need do is to set that to void following https://docs.slatejs.org/api/nodes/element#void-vs-not-void
It has been done! thanks!
