### ISSUE TITLE
Unable to restore caret position 

### ISSUE THREAD

**Issue by leo-petrucci** [ianstormtaylor/slate#5708]
**Description**
In my code I have a Notion-like popover that I use to issue commands (wrap in code block, create header, etc).

If the popover is dismissed, I want the caret to be reset to the previous position it was at when the popover was opened. To do this I save the `editor.selection` before I open the popover, and when I close it I use `Transforms.select` to restore it.

For whatever reason, using the value from `editor.selection` instead restores the caret to the beginning of the editor.

If instead I get a point with:

```
const positionBefore = Editor.before(editor, lastPosition, {
  unit: 'character',
});
```

This works correctly. (and so does `Editor.after`).

**Recording**

https://github.com/user-attachments/assets/c37a0f34-0fc6-4550-9c14-2a8c51e31602

**Sandbox**
https://stackblitz.com/edit/vitejs-vite-djlwkt?file=src%2Fcomponents.tsx,src%2Futils%2Fnormalize-tokens.ts,src%2FApp.tsx,src%2Fbasic.tsx,src%2FApp.css&terminal=dev

**Steps**
To reproduce the behavior:
1. Type something in the editor (this should change the selection JSON below it)
2. Unfocus the editor
3. Click on "Restore Positions"
4. Position will be set to the very first node

Similarly:
1. Type something in the editor (this should change the selection JSON below it)
2. Unfocus the editor
3. Click on "Restore Positions (before)"
4. Position will correctly be set to the character before 

**Expectation**
I'd expect the position to be set to the correct place. I honestly don't understand if it's me doing something wrong or not.

**Environment**
- Slate Version: [e.g. 0.103]
- Operating System: MacOs
- Browser: Chrome

**Comment by WindrunnerMax** [comment]
You should call ReactEditor.focus(editor) instead of ReactEditor.toDOMNode or Transforms.select to restore the focus position.
