### ISSUE TITLE
Could not add a new line in the tables

### ISSUE THREAD

**Issue by monolithed** [ianstormtaylor/slate#573]
Could not add a new line in [the tables](http://slatejs.org/#/tables?_k=wmf24y)

**Comment by ianstormtaylor** [comment]
Hey @monolithed, the tables example isn't a full-featured example, its goal is just to show you that tables are able to be rendered as nested elements. If you want to get full editability, checkout the [`slate-edit-table`](https://github.com/GitbookIO/slate-edit-table) plugin from Gitbook!
