### ISSUE TITLE
unwrapping multiple links at once fails

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#581]

**Comment by vpontis** [comment]
@ianstormtaylor can you elaborate on what this means?

**Comment by ianstormtaylor** [comment]
@vpontis good question! Unwrapping is really just "removing a link". In the "Links" example, the link button will be active when your selection contains a link, and clicking it when it's active will "unwrap" the link, removing it.

But I just tried to reproduce this, and can't so not sure what was going on.
