### ISSUE TITLE
add `defaultBlockType` option to Plain serializer

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#586]

**Comment by abobwhite** [comment]
@ianstormtaylor What are the plans for this? I am coming across an issue where I need to store both HTML and plain text and the Plan.serialize works fine but I have an issue where I need to add a space where new lines were added in the rich text. For now I'll just use regular JS replace: `String.replace(/[\n\r]+/g, ' ')`

**Comment by danburzo** [comment]
@abobwhite `Plain.serialize` is one line of code, so it's easy to make our own:

__MyPlainSerializer.js__

```js
import Plain from 'slate/serializers/plain'

export default {
  deserialize: Plain.deserialize,
  serialize: state => state.document.blocks.map(block => block.text).join(' ').replace(/\n+/g, ' ')
};
```

(You'd still need to replace newlines with spaces since blocks can potentially contain soft-breaks)

**Comment by abobwhite** [comment]
Thanks @danburzo ! Appreciate the quick tip! That combined with this: https://github.com/ianstormtaylor/slate/issues/599 will be very helpful

**Comment by abobwhite** [comment]
@danburzo Just want to note that the solution provides was slightly off: The serialize method should use `state.document.nodes` not `state.document.blocks`

**Comment by danburzo** [comment]
Oops, typo, corrected for posterity :)
