### ISSUE TITLE
Selection is not preserved when changing blocks from <select>

### ISSUE THREAD

**Issue by optimistiks** [ianstormtaylor/slate#593]
Fiddle: https://jsfiddle.net/36L9ot4v/3/

Steps to reproduce: 

1. Select both lines.
2. Pick one of the headings from the select.

Expected: both lines are changed to headers, and they are both stay selected.
Actual: both lines are changed to headers but only first one is selected.

With buttons it works fine though.

**Comment by vpontis** [comment]
This is not a simple bug. When your click on the `<select>` your browser fires a blur which defocuses the current selection in Slate. 

So either this shouldn't be supported or there might need to be a way to preserve selections in Slate without relying on the DOM to do it for us. But that seems bad. 

Maybe you can somehow prevent the blur in your `<select>`...

**Comment by ianstormtaylor** [comment]
Sounds good, thanks for investigating @vpontis. Sounds like you'd need to manually re-focus the editor in the transform to get it to work.
