### ISSUE TITLE
Selection focus warning on auto-markdown example

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#598]
On the[ Auto-Markdown example](http://slatejs.org/#/auto-markdown), seeing the following warning being invoked [here](https://github.com/ianstormtaylor/slate/blob/master/examples/auto-markdown/index.js#L140) on the use of `extendToStartOf` - 

```
Warning: The selection focus was set to a Node that is not a Text node. This should not happen and can degrade performance. The node in question was: Block {key: "12", nodes: List[1], type: "heading-one"}
warn @ build.prod.js:22519
normalize @ build.prod.js:11745
(anonymous) @ build.prod.js:20485
Transform.(anonymous function) @ build.prod.js:13942
AutoMarkdown._this.onSpace @ build.prod.js:185
```

The functionality works, but is there a better way of doing this instead?

**Comment by ianstormtaylor** [comment]
Fixed now!
