### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by tcrossland** [ianstormtaylor/slate#609]
This [issue](https://github.com/tcrossland/spacy-annotator/issues/1) was reported on a project of mine which uses slate. The error is thrown [here](https://github.com/ianstormtaylor/slate/blob/18ef4472cd67087d1e707c0c68eef6bee2a50390/src/constants/environment.js#L46). I haven't been able to reproduce the issue, but it looks like `process` has not been imported/required.

**Comment by ianstormtaylor** [comment]
Is this a problem with the brunch build tool?

I guess we can use something like `typeof document === 'undefined'` or something instead.

**Comment by tcrossland** [comment]
I don't think it's brunch-specific, it's just that `process` will be undefined in a browser environment. From what I can tell, it seems to be a global variable in Node, unless a polyfill is used (e.g. https://runkit.com/npm/process).
