### ISSUE TITLE
Using placeholder with custom renderer for default paragraph

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#615]
Hi @ianstormtaylor! I have a component that, ideally, I would like to use instead of the default paragraph renderer. But, the `placeholder` text prop on the editor seems to work when using the default but not the custom component. 

Is that expected? If yes, do you think it would make sense for the standard `placeholder` prop to the `Editor` to be used if `placeholder` is not supplied in the custom component?

I am hesitant to put the placeholder on the custom paragraph renderer, as then it would show up with every new paragraph. Is there an efficient way to prevent that, other than checking if it is the only node in its parent and that the parent is `Document`?

Thank you!

**Comment by ianstormtaylor** [comment]
Hey @oyeanuj check out the source for the Core plugin, which is the logic that creates the default placeholding logic. You can use the `<Placeholder>` component to achieve what you're trying to achieve I believe.

Right now the `placeholder` attribute only applies to the default block, which is a bit confusing I agree. Potentially should be removed altogether in the future. Or find a better way.

**Comment by laurensiusadi** [comment]
@oyeanuj I found a solution using CSS to add placeholder on custom component.
Leaving this here for future references.

In custom component render function
```
<span className={`${this.props.node.text.length > 0 ? '' : 'placeholder'}`}>
   {children}
</span>
```

Inside CSS file
```
.placeholder::before {
  content: "Placeholder goes here";
  display: block;
  position: absolute;
  color: grey;
  pointer-events: none;
}
```
