### ISSUE TITLE
Question: best way to handle saving to Firebase

### ISSUE THREAD

**Issue by optimistiks** [ianstormtaylor/slate#616]
Hi,

I have an issue when trying to set up editing flow while saving changes to Firebase.

1. I set up a listener to `/documents/:documentId` endpoint.
2. Listener loads the document for the first time.
3. I deserialize the document with `Raw.deserialize` and pass it to Editor state.
4. I make some change in the editor.
5. `onDocumentChange` handler triggers.
6. I serialize Editor state with `Raw.serialize` in the `onDocumentChange` handler and save the result to the `/documents/:documentId` endpoint.
7. At this moment the listener detects the change and gives me the new document (which is already in the Editor). 
If I deserialize it again and pass it to the Editor as new state, it seems like the Editor is re-rendered and it loses focus. 
And it doesn't feel right to deserialize it again, because the latest version of the document is already in the Editor state. 
But I don't see any way of checking that the document which came from the listener is the same as the document which is inside the editor, except deep equality check, which can be slow when documents are big. 
Other way could be to load the document only once, and don't establish the listener, but I would like to keep the realtime update. 

Thanks in advance for any advice

**Comment by jgrimes** [comment]
You could generate a `documentVersion` that is also saved in Firebase when serializing. You can check that before deserializing (or even retrieving) the results of the document Firebase listener.
