### ISSUE TITLE
Collaborative Editing

### ISSUE THREAD

**Issue by Wuyialex** [ianstormtaylor/slate#624]
I am currently working on creating collaborative editor using slate. I think slate is much more advanced than draft.js. I like this concept. However, there are many difficulties in creating collaboration tools. Communication through socket.io is somewhat difficult. Do you think it's possible to create collaborative editor through slate?

**Comment by ianstormtaylor** [comment]
Hey @Wuyialex, that's one of the goals for Slate!

Right now it's definitely missing some of the logic in core to make it easier, but might still be possible. Check out this older thread to see more information: https://github.com/ianstormtaylor/slate/issues/259

And also this search of issues for some other tangential things: https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+collaborative+is%3Aclosed

I'd love any and all help to get closer to making it happen!

**Comment by lingxiao** [comment]
Is there any update on collaborative pluggins with slate?

**Comment by FWirtz** [comment]
Would be interested in that as well.

**Comment by Kushan-** [comment]
any update on this post so far??
