### ISSUE TITLE
Bug with delete backward on image example

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#625]
There is a bug with backspace in the image example. I'm not sure what is the exact reason.

### Steps to reproduce:

1. Open http://slatejs.org/#/images?_k=f2krgi
2. Select the whole paragraph at the end (`This example ... in the editor!`)
3. Press <kbd>Backspace</kbd> once (the paragraph is now empty)
4. Press <kbd>Backspace</kbd> again
5. The cursor is now before the image (weird?)
6. Pressing character, insert it twice on different line (very weird)

### Tested on

- Chrome
- Safari

**Comment by skogsmaskin** [comment]
It could possibly have something to do with my PR https://github.com/ianstormtaylor/slate/pull/618

I will have a look!
