### ISSUE TITLE
refactor delete transforms to remove "backward/forward", and simplify

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#633]
Right now there's a distinction between "backward" and "forward" for delete transforms, and the API for deletes is a bit convoluted in general. Here's what it is currently...

```js
delete()
deleteForward(n = 1)
deleteBackward(n = 1)
deleteCharBackward()
deleteCharForward()
deleteWordBackward()
deleteWordForward()
deleteLineBackward()
deleteLineForward()
```

The `deleteForward` and `deleteBackward` are kind of a weird leftover from before "characters" were handled properly accounting for emojis. They're kind of like a buggy version of `deleteCharBackward/Forward`, except `deleteChar*` currently doesn't offer the ability to delete multiple characters.

Instead, I think the whole thing could be simplified to:

```js
delete()
deleteCharacters(n) // backwards with a negative `n`
deleteWords(n) // backwards with a negative `n`
deleteLines(n) // backwards with a negative `n`
```

Might be something I'm missing though, just a thought.

**Comment by dfrho** [comment]
the pattern with positive and negative integer parameters for direction seems intuitive.

**Comment by ianstormtaylor** [comment]
Nevermind, after working with the equivalent API's on `Range` and `Point` objects, I think the `*Forward` and `*Backward` suffixes are actually helpful to remember what's going on. Seeing a random negative integer isn't quite enough of a clue.

Instead, the selection-moving API should change to mimic the delete API. So we'd end up with:

```js
change.moveForward(1)
change.moveBackward(7)
change.moveWordForward(3)
change.moveWordBackward(2)
change.moveLineForward(1)
change.moveLineBackward(3)
```

And both should remove the idea of "char", since moving one character at a time should be the default, regardless of the actual length of those characters: 

```js
change.deleteForward(1)
change.deleteBackward(7)
change.deleteWordForward(3)
change.deleteWordBackward(2)
change.deleteLineForward(1)
change.deleteLineBackward(3)
```

If people really (for some strange reason) needed to move half a character in the case of emojis, they can work that out on their own.

I'm going to close this since it's not needed anymore.
