### ISSUE TITLE
Uncaught TypeError: node.getRanges is not a function

### ISSUE THREAD

**Issue by santiagopuentep** [ianstormtaylor/slate#641]
```
const firstNode = state.document.nodes.get(0);

state.transform().removeTextByKey(firstNode.key, 0, 3);
```

Throws "Uncaught TypeError: node.getRanges is not a function" at "Object.Transforms.removeTextOperation" at line 250

It seems like the node doesn't have a getRanges function.

**Comment by ianstormtaylor** [comment]
Hey @santiagopuentep, I think this is actually because `removeTextByKey` requires a `kind == 'text'` node, instead of a block or inline. I believe if you do:

```js
const firstText = state.document.getFirstText()
state.transform().removeTextByKey(firstText.key, 0, 3)
```

...it will work! Let me know if not though.

**Comment by santiagopuentep** [comment]
That worked. Thanks!

Shouldn't it have a check for the correct node? Or maybe a more descriptive error?

Also, I don't see `Document.getFirstText()` documented. I think it's missing.

Great job with the editor by the way, I love it, **much** better than draft.js that was driving me pretty crazy with some things and was hard to understand.
