### ISSUE TITLE
Raw.deserialize is around 60 times slower with isVoid nodes

### ISSUE THREAD

**Issue by bunterWolf** [ianstormtaylor/slate#647]
Raw.deserialize needs a very long time to deserialize nodes with isVoid: true
Shouldn't it be faster or at least the same speed of normal nodes?

Try it yourself: https://jsfiddle.net/akc8wu82/

```
createState() {

  const nodes = []

  for (var index = 0; index < 300; index++) {
    nodes.push({
      kind: 'block',
      type: 'any-type',
      isVoid: true || false
    })
  }

  console.time('Create Slate State')
  const state = Raw.deserialize({ nodes }, { terse: true }) 
  console.timeEnd('Create Slate State')
  // 60ms if isVoid is false, 5000ms if isVoid is true

  this.onChange(state)

}
```

**Comment by bunterWolf** [comment]
if there is a problem, I think it is located in: 
transforms/normalize.js: normalizeNodeAndChildren() https://github.com/ianstormtaylor/slate/blob/master/src/transforms/normalize.js#L112

**Comment by bunterWolf** [comment]
The Problem is that all void nodes getting normalized by the core schema: 

> Ensure that void nodes contain a text node with a single space of text.

https://github.com/ianstormtaylor/slate/blob/master/src/schemas/core.js#L113
That is a lot of transformation work to do.

I think the question is, is there a way to provide Raw.deserialize/State.create with a void node, that has not not to be serialized later?

(If I see it right, every void node, that runs from serialize back to deserialize has to be normalized?)

**Comment by bunterWolf** [comment]
Is it maybe a good idea to force a valid void block in Block.create ?
That would reduce the State.create from 5000ms to 140ms in my case ;)

```
  static create(properties = {}) {
    if (properties instanceof Block) return properties
    if (properties instanceof Inline) return properties
    if (properties instanceof Text) return properties
    if (!properties.type) throw new Error('You must pass a block `type`.')

    properties.key = properties.key || generateKey()
    properties.data = Data.create(properties.data)
    properties.isVoid = !!properties.isVoid
 -  properties.nodes = Block.createList(properties.nodes)

 +  if (properties.isVoid) {
 +    properties.nodes = Block.createList().set(0, Text.createFromString(' '))
 +  } else {
 +    properties.nodes = Block.createList(properties.nodes)
 +  }

    if (properties.nodes.size == 0) {
      properties.nodes = properties.nodes.push(Text.create())
    }

    return new Block(properties)
  }
```

https://github.com/ianstormtaylor/slate/blob/master/src/models/block.js#L49

**Comment by ianstormtaylor** [comment]
@bunterWolf thanks for submitting this, I totally agree, ran into this last week myself. I've just pushed a new release that adds a `normalize: false` option to `Raw.deserialize` (and `State.create`) which will skip the normalization step, and should greatly speed things up.

I'd only recommend using it when the input to `Raw.deserialized` was previously serialized from an existing in-memory state. (And not in cases like in the examples where it's a hand-written JSON document.)

Let me know if that doesn't help!
