### ISSUE TITLE
add `selection.inlines`, for inline creation on next char

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#651]
Right now we have `selection.marks` which keeps track of the marks that have been "added to the cursor", so that if you hit <kbd>cmd+b</kbd> and type a character, it will be bold. Right now it's hard to do a similar thing with links, so you have to manually maintain the state for "the next character should be a link" yourself. But we could probably do something similar, storing `selection.inlines` and when the next character is typed, wrap it with whatever the inline nodes are.

**Comment by doodlewind** [comment]
Well is this what we've got from `value.inlines` now?

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
