### ISSUE TITLE
Node.getFragmentAtRange method uses the deprecated Node.getChildrenBetweenIncluding

### ISSUE THREAD

**Issue by Rebulus** [ianstormtaylor/slate#652]
Hi.

I see warning in console when try to call `getTexts` from `editorState.fragment`:

```bash
Warning: The `Node.getChildrenBetweenIncluding(start, end)` method is deprecated.
warn	@	warn.js:32
getChildrenBetweenIncluding	@	node.js:1656
object.(anonymous function)	@	memoize.js:109
getFragmentAtRange	@	node.js:610
object.(anonymous function)	@	memoize.js:109
get	@	state.js:490
...
```

It happens, because, method `Node.getFragmentAtRange` uses the deprecated `Node.getChildrenBetweenIncluding`

Please, looks here
https://github.com/ianstormtaylor/slate/blob/master/src/models/node.js#L527

**Comment by Rebulus** [comment]
@ianstormtaylor Please, help me to understand future for the method `Node.getChildrenBetweenIncluding` in the scope of `Node.getFragmentAtRange`. I could create a pull request for fixing this situation.

**Comment by ianstormtaylor** [comment]
Hey @Rebulus that would be awesome! the `getChildrenBetweenIncluding` is only used in that one place I believe, so we can just inline it in `getFragmentAtRange` instead to fix it.

**Comment by Rebulus** [comment]
Thank you, you are absolutely right. I will do it 😉

**Comment by Rebulus** [comment]
I close the issue, because the warning is solved.
