### ISSUE TITLE
Can't set up dependency via git URL

### ISSUE THREAD

**Issue by lxcid** [ianstormtaylor/slate#653]
I was setting up slate in my project to pull from github… Something like this in my `package.json`:

```
  "dependencies": {
    "slate": "ianstormtaylor/slate",
  },
```

But the source code did not get distributed.

![screenshot 2017-03-06 21 26 05](https://cloud.githubusercontent.com/assets/297156/23611771/97d037ee-02b3-11e7-9985-4c8b280c1568.png)

I'm suspecting its something related to either `prepublish` or `postinstall`.

I'll post if I have more finding. I notice if I do a npm install on Slate repository, it throws this warning

```
npm WARN lifecycle slate@0.19.3~prepublish: cannot run in wd %s %s (wd=%s) slate@0.19.3 npm run build /path/to/slate
```

I believe this is related to downgrading of privilege by node, see https://docs.npmjs.com/misc/scripts#user

**Comment by ianstormtaylor** [comment]
Hey @lxcid this is due to the `./dist` files not being included in the git repository. I'm not sure if there's any solution here, although if other libraries have solved this I'd love to hear it! If you figure things out feel free to reply and we can reopen if there's a way to make this work!
