### ISSUE TITLE
change block style without changing block type?

### ISSUE THREAD

**Issue by amaau** [ianstormtaylor/slate#658]
is it possible to change block style without changing the type, or wrapping inside of another block?

**Comment by bunterWolf** [comment]
Im not sure, if I understand you question correct. But maybe that helps:

You can change the data of a block: https://docs.slatejs.org/reference/models/block.html#data
And render your block based on that data:

```
schema: {
  nodes: {
    [YOUR_BLOCK_TYPE]: function (editorProps) {
      const { node, state, editor } = editorProps
      const data = node.getIn(['data', 'yourProperty'])
      if (data == that)
        return <Style1>
      else 
        return <Style2>
    }
  },

```

**Comment by amaau** [comment]
thanks that's it!
