### ISSUE TITLE
add <Placeholder> component

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#66]
I think this could be block-independent, and take in a `node` and `state`. Then people can use it and add styles as they please.

Also, if it also took a `firstOnly={false}` property, you could use it for cases like image caption nodes, where you want the placeholder to render even though it's not the first node in the tree.

**Comment by oyeanuj** [comment]
@ianstormtaylor I didn't see the `firstOnly` property you mentioned above, in the source code. Is there an alternative way that you'd suggest implementing that functionality?

**Comment by ianstormtaylor** [comment]
I think as currently implemented you'd pass in a `parent` node that isn't the `document` to get the placeholding to trigger on its contents. Although that name isn't great
