### ISSUE TITLE
Right arrow key not working when inline node is at the start of the block

### ISSUE THREAD

**Issue by janjiss** [ianstormtaylor/slate#661]
Hey, so I encountered following problem. When I insert the inline at the beginning of the block and move cursor to the beginning of the same node, I'm unable to move to right with arrow key. Left arrow key works fine. If I remove the empty node at the start of the inline from DOM (Node with key "7") manually (via inspector), the problem goes away.

![image](https://cloud.githubusercontent.com/assets/600203/23859260/0ff38ace-07d1-11e7-8159-8cd66dc44bf4.png)

Here is a full code example that has this problem (Slate v 0.19.3): 

```
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import { Raw, Editor } from 'slate'

const initialState = {
  nodes: [
    {
      kind: "block",
      type: "paragraph",
      nodes: [
        {
          kind: "text",
          text: "Example text that we want to linkify"
        }
      ]
    }
  ]
}

const schema = {
  nodes: {
    'link': (props) => { return <a>{props.children}</a> },
  }
}

class MyEditor extends Component {
  constructor(props) {
    super(props)
    const editorState = Raw.deserialize(initialState, { terse: true })
    this.state = { editorState }
    this.onChange = (state) => this._onChange(state)
    this.wrapLink = (state) => this._wrapLink(state)
  }

  _onChange(editorState) {
    this.setState({ editorState })
  }

  _wrapLink(e) {
    this.onChange(this.state.editorState.transform().wrapInline('link').focus().apply())
  }

  render() {
    return (
      <div>
        <button onClick={this.wrapLink}>Wrap Link!</button>
        <div className="editable">
          <Editor
            schema={schema}
            state={this.state.editorState}
            onChange={this.onChange}
          >
          </Editor>
        </div> 
      </div>
    )
  }
}

const editorElement = document.getElementById('editor')

ReactDOM.render(
  <MyEditor />,
  editorElement
);

```

I'm a little puzzled that I don't see this problem on the Link example, since it uses the same transformations as I am.

**Comment by janjiss** [comment]
I was able to pinpoint down the issue. If we insert an inline while we don't maintain an active selection, it causes moving to the right not to work if the inline is at the beginning of the block. 

I'm currently working on a hover menu that also has an input text for link url:
![image](https://cloud.githubusercontent.com/assets/600203/23884885/aefae4a2-083d-11e7-9f6d-bbb931ebbdc7.png)

That means that it is impossible for me to maintain an active selection while I am working with the input. 

Hope this helps

**Comment by Rebulus** [comment]
@janjiss I pasted your code above in JSFiddle [playground](https://jsfiddle.net/b0chss0x/) and could not reproduce the error. Maybe, I did something wrong. Could you help me change the environment for understanding the issue?

But I had this error, when I tried to create link in collapsed selection (by cursor):
```console
Uncaught TypeError: Cannot read property 'isVoid' of undefined
    at Object.Transforms.wrapInlineAtRange (https://npmcdn.com/slate@0.19.3/dist/slate.js:45870:22)
    at Transform.(anonymous function) [as wrapInlineAtRange] (https://npmcdn.com/slate@0.19.3/dist/slate.js:40729:32)
    at Object.Transforms.wrapInline (https://npmcdn.com/slate@0.19.3/dist/slate.js:44533:13)
    at Transform.(anonymous function) [as wrapInline] (https://npmcdn.com/slate@0.19.3/dist/slate.js:40729:32)
    at MyEditor._wrapLink (eval at transform.run (https://fiddle.jshell.net/js/babel/babel.js:3192:10), <anonymous>:66:56)
    at MyEditor.wrapLink (eval at transform.run (https://fiddle.jshell.net/js/babel/babel.js:3192:10), <anonymous>:54:20)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:9017:16)
    at executeDispatch (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:3006:21)
    at Object.executeDispatchesInOrder (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:3029:5)
    at executeDispatchesAndRelease (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:2431:22)
```

**Comment by janjiss** [comment]
Interestingly enough, the same code that causes the problem for me locally works fine in `JSFiddle`. I'll experiment a little more and if it won't work, I will submit a repo with the problem. Would that work?

**Comment by janjiss** [comment]
Alright, should've checked my `yarn.lock` file where slate was at 0.16.x. Closing this issue as the problem does not surface on  0.19.3.

**Comment by Rebulus** [comment]
@janjiss you are welcome 😊
