### ISSUE TITLE
Suggestion to solve a Safari issue with onDrop/getTransferData when using slate-drop-or-paste-images

### ISSUE THREAD

**Issue by tobiastheil** [ianstormtaylor/slate#669]
Hey,

I use the [slate-drop-or-paste-images](https://github.com/ianstormtaylor/slate-drop-or-paste-images) plugin with Slate.

It works with Chrome but pasting/dropping images does not work in Safari (10.0.3).

Error message: `TypeError: Array.from requires an array-like object - not null or undefined`

It works when I change line 70-72 in `/src/utils/get-transfer-data.js` [link](https://github.com/ianstormtaylor/slate/blob/master/src/utils/get-transfer-data.js) to:

```
if (transfer.files && transfer.files.length) {
  files = Array.from(transfer.files); // before: files = Array.from(files);
}
```

Since it works in Chrome and the example works in Safari I am not sure if this change is right or if it misses some edge cases?

**Comment by ianstormtaylor** [comment]
Hey @tobiastheil thanks for reporting this! Your fix would indeed solve it I think. I realized that the code could be written slightly differently to make it more bulletproof, so I just committed the fix myself real quickly. Thanks!
