### ISSUE TITLE
get*AtRange could be short-circuited to improve performance

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#679]
When calling one of the `get*AtRange` methods of a node, it's always going to be getting all of the leaf text nodes first, and then filtering them to only the text nodes in the range, and then working from there.

But for the average editing case, 99% of the checks will be against a collapsed selection, which could be much more optimized by returning the list with the single text node in it to begin with.

**Comment by zhujinxuan** [comment]
Perhaps we need to write more benchmarks to test the short-circuit.  I checked out the benchmarks in https://github.com/ianstormtaylor/slate/pull/1765, it seems that all at-range benches are using `selectAll` to create range.  Perhaps we shall add more benchmarks with different ranges for common scenarios.

**Comment by ianstormtaylor** [comment]
With the newer iterable methods we're moving away from these `get*AtRange` methods instead.
