### ISSUE TITLE
onDrop data is now returning type files for text and html

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#680]
A recent change (#669 I think) has broken the onDrop for basic text and html types. It seems that the issue is that there is now an emtpy files array in the onDrop object, so the `getTransferType()` method just returns "files".

I'm not sure what exactly caused the change, but I think it was the removal of the if statement in this commit: 8e2dce111.

Here are two fiddles to show what I mean:
Slate 0.19.6 - https://jsfiddle.net/appleifreak/ht8wqm61/2/
Slate 0.19.3 - https://jsfiddle.net/appleifreak/ht8wqm61/3/

**Comment by tyler-johnson** [comment]
Just noticed that paste is also broken as onPaste seems to be using the same methods as onDrop.

**Comment by ianstormtaylor** [comment]
Thanks @tyler-johnson, fix incoming!
