### ISSUE TITLE
Deserializing code and pre

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#685]
In my schema, I have two possible code layouts, one is for inline elements:

```html
<p>
  Foo <code>foo</code> foo
</p>
```

and one is for blocks:

```html
<pre>
  <code>foo</code>
</pre>
```

Now, I have the following deserialization rule:

```js
  deserialize = (el, next) => {
    switch (el.tagName) {
      case 'code':
        return {
          kind: 'mark',
          type: CODE,
          data: Data.create({}),
          nodes: next(el.children)
        }
      case 'pre':
        return {
          kind: 'block',
          type: CODE,
          nodes: next(el.children)
        }
    }
  }
```

Unfortunately, this causes that `<pre><code>asdf</code></pre>` will result in the following diff:

```
    - Expected
    + Received

    @@ -3,11 +3,20 @@

         Object {
           "kind": "block",
           "nodes": Array [
             Object {
               "kind": "text",
    -          "text": "asdf",
    +          "ranges": Array [
    +            Object {
    +              "marks": Array [
    +                Object {
    +                  "type": "CODE/CODE",
    +                },
    +              ],
    +              "text": "asdf",
    +            },
    +          ],
             },
           ],
           "type": "CODE/CODE",
         },
```

which looks wrong because we have a mark and a pre, which will result in `<pre><code><code>asdf</code></code></pre>`. On next import, this will get even more nested, and so on.

So, how do I get the output I desire?

**Comment by thepian** [comment]
It seems to me that you want to define a node type for code as well as a mark for code. If you have <pre><code></code></pre> you don't add the mark inside a pre block

**Comment by ianstormtaylor** [comment]
The way to solve this is to have your serializer rule for marks check first that the `<code>` element isn't inside a `<pre>` parent I think.
