### ISSUE TITLE
Meta+` doesn't work

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#690]
`if (event.which != 192 || !event.metaKey) return`

This line didn't work for me. I was testing [this](https://docs.slatejs.org/walkthroughs/defining-custom-block-nodes.html) on a Mac in Chrome. Everything else worked fine, and when I replaced "192" with anything else, it worked too. My guess is that Chrome doesn't pass this particular key combination through.

**Comment by ianstormtaylor** [comment]
Ah, good catch @AlexeiAndreev! I think you're right. I'd be happy to merge a pull request that changed that hotkey to being <kbd>control-`</kbd> instead if you're down to make it! Thanks!

**Comment by ianstormtaylor** [comment]
Fixed now!

**Comment by potatopotaro** [comment]
Just a heads up, Meta + ` is still in the instructions/Documentation for:
https://docs.slatejs.org/walkthroughs/defining-custom-block-nodes
Which isn't detected, on Chrome or Safari.
