### ISSUE TITLE
Selecting actual "typed content" when rendered content is selected.

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#695]
Let's say I type `(c)` and convert it to ©. Or, maybe I convert `:)` to 😄 .
Is it possible to get actual typed content when I selected rendered content. So, selecting the emoji should give me `:)`. 

Essentially mapping selection/cursor position from rendered content to typed content.

Is something like that possible?

**Comment by ianstormtaylor** [comment]
Hey @jatins, I'm not totally sure what you mean, but Slate is only concerned with the actual content, and not any previous representation that happened to be converted. So my guess is the answer is no. Of course, you can keep your own mapping around to do that if you want, but it wouldn't be handled by core. Feel free to ask follow up questions though!

**Comment by jatins** [comment]
What I meant was, let's say I have a plugin which converts `:)` to 😄 .

So, in this case, the _typed content_ (the thing that was actually typed) is `:)` and rendered content being the emoji.

Now when I select the emoji, I want to know what is selected in the _typed content_. However, I guess it wouldn't be possible since, as you mentioned, slate only knows about what's rendered.

**Comment by ianstormtaylor** [comment]
Yup, unfortunately not. What's your use case?

**Comment by jatins** [comment]
@ianstormtaylor I have some custom parsing logic for the text. So, `onKeyDown()` I parse the _entire content_ of current block, create a new slate block from parsed content and replace the existing block with new block.

So, let's say `-[ ] ` at the start of line becomes a check box. But `abcd -[ ]` should be rendered as plain text.

Consider this scenario:
1. User types `-[ ] ` -> renders a check box.
2. User goes to the start of this block (that is the places his cursor before the check box) and types `abcd`. So, essentially the user _typed content_ now is `abcd-[ ] ` which should not be rendered as a check list. 

I can save what the user types in separate model. But now I have to map actions in _rendered content_ to actions in _typed content_ but unless I have a mapping between two, I am not sure how that'll work.

**Comment by oyeanuj** [comment]
@jatins For things like emojis and checkboxes, if you use inline nodes, then you could use the `data` property of the node to store the original text?

**Comment by jatins** [comment]
@oyeanuj Thanks for the suggestion! 
Yes, that's probably something I could do. I'll look into it.

**Comment by michaelpietrykowski** [comment]
@jatins That will work, I am doing basically the same thing.
Just iterate over the nodes and check if `node.type === yourEmojiType`. If true, do `result += node.data.get('originalText')`, otherwise `result += node.text`.
