### ISSUE TITLE
fix scroll updating logic to work with new selection updating logic

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#698]
Right now there's a case where the `state.selection` is focused, but was previously blurred, where the `Node#updateScroll` fires first, without any native selection and breaks.

Reproducable in this fiddle:

https://jsfiddle.net/uk6rwfqj/1/

Select all, then try to use the select to change the block type.

**Comment by lxcid** [comment]
I love to help out in this. Is the any pointer?

**Comment by ianstormtaylor** [comment]
@lxcid I don't have any specific pointers, would have to dive in again to remember what was going on. But would love any help you can offer!

**Comment by ianstormtaylor** [comment]
This appears to not be a problem anymore?

**Comment by lxcid** [comment]
You are right! Weird! I'll keep a look out! Thanks!
