### ISSUE TITLE
upgrade to immutable@4.x for faster Record behavior

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#703]
Looks like records in `immutable@4.x` have faster internals for getting/setting, so upgrading could make some of the iterative stuff faster, not sure how much.

**Comment by ianstormtaylor** [comment]
Can't right now because it makes the tests fail. But once it's out of release candidate mode this will be a very good improvement!

**Comment by crisward** [comment]
Perhaps this answers #747 ? You'd just need to change the install instructions to 
```
npm install --save immutable slate
```

**Comment by ianstormtaylor** [comment]
Yup, great call @crisward. Closing in favor of #747
