### ISSUE TITLE
the slatejs.org Website SSL appears to have expired

### ISSUE THREAD

**Issue by export-mike** [ianstormtaylor/slate#711]

**Comment by ianstormtaylor** [comment]
I don't think it ever had SSL?

**Comment by export-mike** [comment]
<img width="303" alt="screen shot 2017-04-12 at 9 21 09 am" src="https://cloud.githubusercontent.com/assets/2983327/24934828/6d024d3e-1f61-11e7-8b18-9d6c23bc8bff.png">
I seem to see this ^

**Comment by ianstormtaylor** [comment]
@export-mike where'd you find the link to it with `https:`? I don't think I've ever setup SSL for it, so all of the links should be using `http:` anyways

**Comment by export-mike** [comment]
@ianstormtaylor it redirects for me
