### ISSUE TITLE
add spellCheck, autoCorrect, autoFocus, role <Editor> properties to docs 

### ISSUE THREAD

**Issue by thepian** [ianstormtaylor/slate#714]
I currently just need the default browser spell check, but it seems that you'd want to pass a `spellCheck` property to the root `<div>` (along with other standard event handlers like onClick).

**Comment by Slapbox** [comment]
In my experience browser spellcheck is currently not possible. I did get spellcheck working in Electron though.

**Comment by thepian** [comment]
That's a very interesting finding, but it does anyhow seem like something that should be passed through as it's a standard attribute.

I actually since realised that we will be doing custom spell check, as whatever is built in isn't sufficient.

**Comment by ianstormtaylor** [comment]
Hey @thepian, I'm not sure I totally understand, but if you pass `<Editor spellCheck={true}>` that should enable spellcheck. Although I think it's actually true by default. (Unless you're in Firefox, where I think we turn it off since there's a browser compatibility issue.)

**Comment by Slapbox** [comment]
Actually I believe spellcheck works, but text correction does not. I may be mistaken, I think this is how Gitbook for example is.

**Comment by thepian** [comment]
I can see `spellCheck` on Content. Not sure, perhaps I got the idea that it wasn't a property as I didn't see it in the documentation. Sorry for the confusion I guess this is a docs ticket.

You might want to add the following to list of Editor properties in docs

- spellCheck
- autoCorrect
- autoFocus
- role

**Comment by bengotow** [comment]
Hey folks—the docs seem to be updated, I think this issue can be closed.

**Comment by ianstormtaylor** [comment]
Thanks @bengotow!

**Comment by MerlinMason** [comment]
Has this been removed fro the docs again? Can't seem to see it anywhere.

ps, I'm kinda a n00b to Slate but would be happy to assist with some docs.

**Comment by Slapbox** [comment]
@MerlinMason this would be for an old version of Slate. See the docs for the old version here: https://docs.slatejs.org/v/v0.47/

I don't know if that version includes these particular things, since it's still quite a bit newer than when this issue was created. Your best bet to get answers for these sorts of things is to sign up for the Slack channel.

**Comment by MerlinMason** [comment]
Ahh right, yeah I'm using the latest version but couldn't find anything in the [docs](https://docs.slatejs.org/libraries/slate-react#editable) for these options... Searching through the source code I've managed to get the following working.

```
import { Editable } from "slate-react";

...

<Editable
    autoCapitalize="sentences"
    autoCorrect="true" // "true" should be passed as string
/>
```

Hopefully that's useful to someone else :)

**Comment by padunk** [comment]
If someone need it:
```jsx
<Editable
    autoCapitalize="false"
    autoCorrect="false"
    spellCheck="false"
/>
```
Slate 0.65..3
