### ISSUE TITLE
Passing props to plugins via Editor

### ISSUE THREAD

**Issue by thepian** [ianstormtaylor/slate#715]
Could there perhaps be a method on plugins `pluginWillReceiveProps` fired when the Editor props are set in constructor or changed.

The examples for plugins are shown with options being passed and the plugin constructed and then potentially shared among all editor instances. That seems like a good default approach, but you'd quite often want the plugin to be "configured" for the concrete editor.

This could be done by 

```
pluginWillReceiveProps(newProps, editor) {
  editor.setState({ forPlugin: { p1: newProps.p1 }});
}
```

**Comment by oyeanuj** [comment]
@ianstormtaylor @thepian another related thought. While working on solutions discussed in #644, and trying to implement an external spellcheck solution, I was finding myself looking for a way to communicate from the `Editor` component to the plugins. For example, after fetching result from an external for the document, I'd want a plugin to take that result and do its thing.

At this moment, plugins are activated only when some change happens via the user, in the Editor. One could change some editor prop to force a re-render but that doesn't sound efficient or clean.

Do we think there should be a first-class way for the editor to pass props to the plugins, like @thepian suggested above?

(happy to open a different issue if this seems like a separate ask)

**Comment by thepian** [comment]
@oyeanuj I will need to deal with external spell check as well, would love to hear more.

@oyeanuj I think we are talking about the same type of use case.

**Comment by ianstormtaylor** [comment]
Hey you two, check out the `react-broadcast` component for a way to pass props down to the nodes underneath. I don't think we'll support this natively in Slate, but that library should help!
