### ISSUE TITLE
Selection and Focus with embedded images/videos/..

### ISSUE THREAD

**Issue by thepian** [ianstormtaylor/slate#719]
I'm trying to understand how custom nodes focus/select is handled. There doesn't seem to be any way concept of the component of a node gaining focus, or at least nothing documented.

What am I missing?

**Comment by thepian** [comment]
A side question is how to move the insertion/cursor point during onDrop. If I do an insertBlock call it seems to put it before the drop point.

**Comment by oyeanuj** [comment]
I have run into this as well. I've been using `collapseToStartOf` transform to get close to the desired UX but feel like we need a method to focus or select a block.

Example: if we have a non-void block with a void and non-void blocks within it, there doesn't seem to be a way to just select the parent block. A common example for that structure will be Figure/Image with captions like shown below.

```yaml
- Figure (non-void)
  - Image (void)
  - Caption (non-void)
```
If I use the arrow keys to navigate to this embed, the focus ends up in the children blocks but not with the parent block which is the desired behavior, ideally.

**Comment by oyeanuj** [comment]
Another related way this shows up is in the examples. If you [go to the images example](http://slatejs.org/#/images?_k=b38rxs), and add two images side by side, there isn't actually a way to select both the images together. (My guess is it is related to my previous comment).

**Comment by yuraji** [comment]
In the "Emojis" example there's a similar issue, as you cannot keep typing after inserting an emoji from the bar. With what @oyeanuj noted above I figured I could use `.collapseToStartOfNextText()` to move the cursor to after the emoji, which lets keep typing after inserting an emoji.

**Comment by oyeanuj** [comment]
@ianstormtaylor If and when you have a moment, any pointers or thoughts on what might be going on?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
