### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by LintonBlack** [ianstormtaylor/slate#720]
Hi

Thanks for your work your tool is just amazing. I'm just having a look at it and i was wondering if they was a way to implement some rules according to a Json Schema ? and then have some restriction in term of edition and even we can imagine tools and menus available if it make sense.

Any thought ?

Have a great one

Linton

**Comment by ianstormtaylor** [comment]
Hey @LintonBlack! Thanks 😄 

There isn't currently the ability to define things with JSON Schema, but I'm definitely open to the idea. Do you have more details on what you were thinking? Potentially even pseudo-code examples? That would help me get a sense for it.

Right now all of the "rules" are defined via the `schema` property, using functions.

**Comment by LintonBlack** [comment]
Hi Ian,

thanks for your reply.

don t know yet. here is my scope, I have a xml with a specific schema, I convert this xml in Json and as I wanna develop on your "slate" editor I try to find a way to keep things related to the Json (xml) schema.
it is a bit abstract for now, but at the end I try to create a proper collaborative tools on wich people can add comments, make changes or correction but without messing up with the schema.

I tell you more next time, still have a long way to go

Have a nice easter

**Comment by dwstevens** [comment]
I like the thought of using JSON Schema Forms https://github.com/mozilla-services/react-jsonschema-form within a slate.js document. You could create a plugin that allowed you to defined some structure text/form content for inclusion in the slate doc.

**Comment by ianstormtaylor** [comment]
Hey all, these are interesting ideas. I think I'm going to close this since I don't think it would be part of Slate's core, but I think they could make great candidates for user-land plugins/tooling. Thanks!

**Comment by oyeanuj** [comment]
@dwstevens Did you ever end up using `react-jsonschema-form` with Slate? I feel like a plugin like that for Slate could be super useful in testing and understanding Slate for folks.
