### ISSUE TITLE
read-only with hovering menu

### ISSUE THREAD

**Issue by Harryhaha** [ianstormtaylor/slate#722]
Hi, I am new to editor field. My question is that is it possible to make slate editor read-only and also can popup hovering menu at the same time ? Thank you !

**Comment by ianstormtaylor** [comment]
Hey @Harryhaha yes this should be possible, but since it's read-only you won't be able to position it based on the selection, and would need to figure out another way to position it instead.

**Comment by coniel** [comment]
For anyone looking for an easy way to implement this (it's a bit hacky but it works):

I added a `selectionOnly` prop to my editor. When enabled, the `onChange` callback does nothing (so the content can't be modified) and the caret is made invisible using the style prop.

```
style={{ caretColor: selectionOnly ? 'transparent' : 'auto' }}
```

The end result is the equivalent of a `readOnly` editor but with functioning selection.
