### ISSUE TITLE
How does slate map DOM selection to internal selection model?

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#723]
I wanted to understand how the selection mapping works, could you give a brief overview of that?
Or, any place in code I can look into to understand how this mapping is done?

**Comment by jatins** [comment]
Digging through the code, I think this selection mapping is done here: https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js

**Comment by ianstormtaylor** [comment]
Yup @jatins that's the spot! Specifically: https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L138-L222

It used to happen in the `<Leaf>` components, but recently moved up into the `<Content>` components to avoid some of the complexity issues when doing it at the leaf level.
