### ISSUE TITLE
Adding an example for custom schema based editor in the examples list

### ISSUE THREAD

**Issue by anilgulecha** [ianstormtaylor/slate#726]
I would like to restrict the type of document created by a rich-text-editor. Let's assume color/styling is handled via CSS, and I only want the content editable document to be of the type:

```html
<p class="r">I am red</p>
<p class="g">I am green</p>
<p class="b">I am blue</p>
<p class="b">I am <b>blue bold</b></p>
```

The rules are: 
```
1. All content are in <p> tags.
2. Every <p> node *must* have a class assigned to it, which can be 'r', 'g' or 'b'.
3. The content inside the tag can be only styled by <b> or <i>.
4. No nested <p> tags.
```
Is it possible to initialize an editor to only allow documents of this types. Note that ```<p>``` and ```<b>``` are stand-ins.

This is not a bug per-se, just a request for additional documentation to help those who're looking to define custom schemas.

**Comment by anilgulecha** [comment]
(I'm unable to add a questions tag on this -- can someone with permission to edit labels do it)

**Comment by ianstormtaylor** [comment]
This has been added now!

**Comment by anilgulecha** [comment]
@ianstormtaylor can you add a link here for reference? To the Example/doc page. thanks

**Comment by ianstormtaylor** [comment]
Yup, it's the "forced layout" example: https://github.com/ianstormtaylor/slate/tree/master/examples/forced-layout
