### ISSUE TITLE
a list of potential future x-browser issues

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#73]
Culled from a bunch of the other editors. Not clear whether these are actually issues with Slate too yet, but it might be helpful to have this list for when weird things are encountered, so that we can save more time. If you notice one of these, feel free to comment and we can get it fixed.
- [ ] [IE doesn't support "input" event for spellchecking.](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L44)
- [ ] [IE has "autourldetect" feature which needs to be turned off.](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L298)
- [ ] [IE doesn't record clicks without a background style.](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.css#L21)
- [ ] [Safari cursor disappears.](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.css#L26)
- [ ] [Chrome and Safari focus the first character on focus.](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L350)
- [ ] [IE spans with br elements render as two newlines.](https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorTextNode.react.js#L20)
- [x] [Chrome and Safari need an attribute on lowest leaf node.](https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorTextNode.react.js#L34)
- [ ] [Firefox "quickfind" hotkeys break input.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBeforeInput.js#L26)
- [ ] [IE sometimes there is no data to insert.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBeforeInput.js#L78)
- [ ] [Webkit blur sometimes doesn't remove the selection.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBlur.js#L23)
- [ ] [Chrome "find-in-page" loses the selection when coming back to tab.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnFocus.js#L27)
- [ ] [Firefox doesn't change the selection while context menu is open.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnInput.js#L105)
- [ ] [Non-firefox change the selection inaccurately while context menu is open.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnInput.js#L114)
- [ ] [OSX pressing option-space inserts a non-breaking space?](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnKeyDown.js#L111)
- [ ] [Safari does not properly store text/html in paste events sometimes.](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnPaste.js#L133)
- [ ] [IE does not support "extending" selections.](https://github.com/facebook/draft-js/blob/master/src/component/selection/setDraftEditorSelection.js#L25)
- [ ] [IE throws an error when readding changed ranges to a selection.](https://github.com/facebook/draft-js/blob/master/src/component/selection/setDraftEditorSelection.js#L136)
- [ ] [IE "contains" does not work.](https://github.com/quilljs/quill/blob/3b2167f8d6d8d23a848d72cd50ebc216574e2111/core/selection.js#L280)
- [ ] [Firefox insert inaccessible nodes around video elements.](https://github.com/quilljs/quill/blob/3b2167f8d6d8d23a848d72cd50ebc216574e2111/core/selection.js#L275)
- [ ] [IE clipboard data `types` can be null.](https://github.com/quilljs/quill/blob/8f2e1993532a6b9d53b0153a8cfaaf53dbe8f7dc/modules/clipboard.js#L154)
- [x] [iOS adds extra Bold, Italic, Underline controls to the `contenteditable` selection menu.](https://github.com/facebook/draft-js/issues/214)
- [ ] [Firefox adds extra resizing controls to tables and other elements.](https://github.com/ProseMirror/prosemirror/issues/432)

**Comment by oyeanuj** [comment]
Not sure if this is in other browsers but I only had a chance to check this on chrome. On the rich editor main demo, I was trying to select the second paragraph by double or triple clicking and it wasn't working. It works for the first paragraph though..

**Comment by ianstormtaylor** [comment]
@oyeanuj good find! Just opened a new issue for that bug: https://github.com/ianstormtaylor/slate/issues/109

**Comment by arekkas** [comment]
Opening http://slatejs.org on IE11 gives a blank, grey page ("'Symbol' is undefined") ;) Works fine in edge though.

**Comment by arekkas** [comment]
Oh, there's a carret bug in edge 25.10586.0.0:

![slate-edge](https://cloud.githubusercontent.com/assets/3372410/16987758/33275b1c-4e8e-11e6-9692-1eb1251cddae.gif)

**Comment by ianstormtaylor** [comment]
Closing for sanity, because the main goal was just to get it indexed in issue search for people who are running into similar things
