### ISSUE TITLE
Add sample code for inserting inline

### ISSUE THREAD

**Issue by thepian** [ianstormtaylor/slate#731]
There seems to be no examples of inserting inline. I looked at examples and tests for insertInline. I tried the insertInline call, and nothing seemed to work. Then I tried to insert with a serialiser and insertFragment, which didn't work either.

I could only get it to work when inserting a block.

In general the tests are very limited and seem like a warning sign for the project for people evaluating. I think adding tests that cover the API well would be very helpful to show how to use Slate.

**Comment by ianstormtaylor** [comment]
Hey @thepian, happy to accept PRs that add tests. There are quite a few for transforms, but testing the browser interaction with `contenteditable` is a bit harder to mock, so I haven't dug into it yet.

**Comment by ianstormtaylor** [comment]
Closing this since it's old. There are examples of inserting inlines I believe (emoji, link, etc.) and if anyone wants to help with the docs or tests they are welcome!
