### ISSUE TITLE
Using Slate without React

### ISSUE THREAD

**Issue by popey456963** [ianstormtaylor/slate#732]
Hey,

We would love to use SlateJS in our project, but don't currently use React.  All the tutorials we've seen for Slate seem to require it and we were wondering if there was a way to do it without React?

Thanks in advance,
Popey.

**Comment by ianstormtaylor** [comment]
Hey @popey456963, thanks for asking! There isn't a way to do that right now. It's something that I'd consider in the further future, but it won't be possible for quite some time is my guess. Sorry for the let down!

**Comment by tiptronic** [comment]
Too bad :( - everything else reads awesome!

**Comment by tamilvendhank-helptap** [comment]
@ianstormtaylor, is it possible now? To use slate in a React-less environment?

**Comment by dylans** [comment]
> @ianstormtaylor, is it possible now? To use slate in a React-less environment?

Absolutely. There are Angular and Vue implementations maintained by the community, TinyMCE uses Slate but not slate-react, and many of the [products using Slate](https://docs.slatejs.org/general/resources#products) do not use slate-react.

**Comment by tamilvendhank-helptap** [comment]
@dylans, great! Thanks for the reply.
