### ISSUE TITLE
add `data-gramm="false"` to disable Grammarly

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#733]
Grammarly works by editing the HTML out from under the editors in weird ways that it's not expecting, which results in glitchy selections and content changes. But apparently this attribute disables it. Grammarly's team has already disabled it internally for all Draft.js editors, but we can do it on our side to avoid the wait.

**Comment by imrameez** [comment]
How to stop Grammarly extension on my website using javascript
