### ISSUE TITLE
Clarify Placeholder props

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#737]
Hi @ianstormtaylor! In the [`Placeholder` docs](https://docs.slatejs.org/reference/components/placeholder.html), we have two props: `node` and `parent`.

My understanding based on the docs is that the former is used to determine what to render and position on the top of, and the latter to determine the node whose content triggers the `Placeholder`. I imagine they are usually the same. I ask because with that assumption, the `Placeholder` doesn’t render.

```jsx
//In the node being rendered
<div {...attributes}>
  <Placeholder node = {node} parent = {node} state = {state} >
    {placeholderText}
  </Placeholder>
  {children}
</div>
```

It fails in the `isVisible` function here - https://github.com/ianstormtaylor/slate/blob/master/src/components/placeholder.js#L55

So, I am not sure what to pass as the `node` prop. The text node of the node for which it is a placeholder?

Alternatively, I feel this is a place where the `firstOnly` prop that [you referred to](https://github.com/ianstormtaylor/slate/issues/66#issue-164915571) can be used. I'm happy to make a PR that checks for the line linked above in `isVisible` only if `firstOnly` is set to true. 

Thoughts?

**Comment by ianstormtaylor** [comment]
Hey @oyeanuj sorry for the delay on this.

You've got the `parent` and `node` understanding correct. I think `parent` should actually be renamed to `target`, since that might be more helpful in understanding it.

I'm not sure exactly what you mean though about what's not working. What is your use case? The default case is that `node` might be something like a `Block(type:paragraph)` and the `parent` would be `Document`.

**Comment by oyeanuj** [comment]
Thanks for the clarification! I think it helps me see the root issue. I think this part of the doc confused me:

**`parent`**: The node to check for non-empty content...
**`node`**: The node to render the placeholder element on top of...

Let's say we have a structure like the one below and we want a placeholder for each block if they are empty.
```yaml
Document
-- FirstBlock
-- SecondBlock
-- ThirdBlock
```
If `parent` is supposed to refer to the Document, then I am not sure if `target` helps.. it might be more confusing since in the above case, Document is not the `target`.

It seems like there are two distinct cases -
1. `Placeholder` if the document is empty.
2. `Placeholder` if a particular node is empty.

Maybe I can modify the PR #765 to use the `parent` prop only if `firstOnly` is true. Does that work for you?

**Comment by ianstormtaylor** [comment]
Hey @oyeanuj what are you trying to achieve with the placeholder?

**Comment by oyeanuj** [comment]
I am trying to have placeholders show up for Caption fields inside embeds (and elsewhere). And I feel like in those cases, their parent shouldn't affect whether the placeholder shows up or not (2nd case mentioned above). It should only depend upon whether that field has content or not.

The way Placeholder works right now seems to be for cases like placeholder for the document (first case mentioned above).

Happy to clarify more!

**Comment by oyeanuj** [comment]
I've also updated the PR (#765) to reflect my thinking. It seems to make both cases work cleanly.
