### ISSUE TITLE
Use removeNodeByKey on the last node breaks editor's state

### ISSUE THREAD

**Issue by ingro** [ianstormtaylor/slate#739]
Hello! Not sure if this is intended or not but if you remove the last node in a editor's state with `removeNodeByKey` the editor state became unworkable, the documents nodes became an empty `List` and I got a warning and an error in console every time I try to type something in the editor:

`Warning: An object was passed to a Node method instead of a `key` string. This was previously supported, but is being deprecated because it can have a negative impact on performance. The object in question was: null`

and the error:

`Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".`

**Comment by skogsmaskin** [comment]
Hi! I think you should set up a rule in you schema that takes care of this for you, as Slate doesn't have any idea in it self of what should happen in that State (which is a good thing).

```
    rules: [
      // Rule to insert a default block when document is empty
      {
        match: node => {
          return node.kind === 'document'
        },
        validate: document => {
          return document.nodes.size ? null : true
        },
        normalize: (transform, document) => {
          const block = Block.create({
            type: 'contentBlock',
            data: {style: SLATE_DEFAULT_STYLE}
          })
          transform
            .insertNodeByKey(document.key, 0, block)
            .focus()
        }
      }
    ]
```

**Comment by ingro** [comment]
Well thanks for the clarification, I'm using `slate` only from few days and I've missed the `rules` section on the schema! Thanks again, I can close this!
