### ISSUE TITLE
mentions plugin?

### ISSUE THREAD

**Issue by omgj** [ianstormtaylor/slate#743]
for others or will you?

**Comment by oyeanuj** [comment]
@omgj there is this one - https://github.com/oozou/slate-suggestions

**Comment by dfrho** [comment]
https://github.com/oozou/slate-suggestions is currently not supported. Can we re-open in case anyone else has suggestions? Thanks

**Comment by Hongbo-Miao** [comment]
Same here, seems that plugin is not maintained any more. https://github.com/oozou/slate-suggestions/issues/24

**Comment by rcarubbi** [comment]
https://github.com/rcarubbi/slate-suggestions.git I've made a fork that works fine with the latest versions of slate and react.

**Comment by cmenge** [comment]
@rcarubbi looks like that is gone now, too?

**Comment by Domino987** [comment]
Any news on this?

**Comment by rcarubbi** [comment]
There is a official one now https://www.slatejs.org/#/mentions

**Comment by rcarubbi** [comment]
Sorry, actually I haven't worked on this since 2019
