### ISSUE TITLE
BYO immutable.js?

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#747]
Right now Slate pins it's own version of Immutable as a dependency but since it's something that is fairly common to use in your own apps, should we not be doing that and having people bring their own like we do with React? Thoughts anyone?

**Comment by thepian** [comment]
I would assume that immutable is fairly stable, so why not?

**Comment by jtadmor** [comment]
On the topic, BYO lodash methods would be kinda nice.

**Comment by ianstormtaylor** [comment]
@jtadmor what do you mean?

**Comment by jtadmor** [comment]
Ignore that, when I installed this it installed a bunch of `lodash.map` type libs when I already have the whole lib, but it looks like that's cheerio's fault.
