### ISSUE TITLE
Embedded inputs + textareas lose focus on input

### ISSUE THREAD

**Issue by conorcussell** [ianstormtaylor/slate#749]
Since [this commit](https://github.com/ianstormtaylor/slate/commit/619870808699ed853ca153419e616b764c639762), an embedded input, like the one seen in the [embed example](http://slatejs.org/#/embeds?_k=ee57v6), loses focus when it is changed. Meaning you can only type 1 character at a time. 

I'm not sure what is the best way of preventing [this](https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L160) being called when the input is a child of the editor, or if that would cause any other bugs. Any ideas?

**Comment by ianstormtaylor** [comment]
Hey @conorcussell I think the codebase has changed such that I'm not sure what line you were referencing there any more. 

But maybe that `element.contains` check needs to be altered to account for nested `contenteditable="false"` elements. Not totally sure on this one off the top of my head.

**Comment by conorcussell** [comment]
Updated my comment so it points to the correct method `updateSelection` now on line 160.

Yeah, I'll writing something which checks for nested elements and submit a PR if I get something that works. Thanks for the hint!

**Comment by ianstormtaylor** [comment]
Realized what was going on, and just releasing a fix for it now!
