### ISSUE TITLE
Selection is displayed incorrectly after applying code span

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#751]
http://slatejs.org/#/rich-text?

Triple click to select the first paragraph. Click "code span" button. Note that the selection appears changed. Click "code span" button again and everything looks correct.

**Comment by marekolszewski** [comment]
@AlexeiAndreev I've also noticed that there is something weird going on when you double or triple click to select an entire line. I wonder if this is related.

In the same example (http://slatejs.org/#/rich-text), try triple clicking on the second paragraph. You'll notice that the 'quote' button lights up even though the line has no quoted content. It appears that when you select a whole line, Slate thinks that part of the next line is also selected. This has caused problems for me when changing lines to headers, which unexpectedly also converts the following line to a header.

Best,

Marek

**Comment by ianstormtaylor** [comment]
It looks like this is fixed in the latest versions of Slate.
