### ISSUE TITLE
Editor loses focus when browser tab loses/regains focus

### ISSUE THREAD

**Issue by mernen** [ianstormtaylor/slate#756]
Steps to reproduce: (tested on Chrome and Safari, macOS Sierra)

1. Open any page with a Slate editor, like the one on https://slatejs.org
2. Click the editor to focus it
3. Switch to another app, or another tab in your browser
4. Switch back to the browser/tab

Expected: focus should return to the editor.

Actual result: focus is on the page itself.

(For comparison, other editors like Draft.js handled it just fine)

---

This is pretty annoying for the user, when they want to quickly look something up in another page/app.

I haven’t looked at the code, but my hunch is that it is indirectly invoking `blur()` when the `blur` event is triggered. This is a no-op when focus is going to some other element in the same page, but kills your chance of retaining focus in case of app/tab switching.

**Comment by ianstormtaylor** [comment]
Good call @mernen that sounds like exactly what's happening right now. Thanks for reporting this

**Comment by eden-lane** [comment]
@ianstormtaylor why do we need this code in core plugin?
```
function onBlur(e, data, state) {
  debug('onBlur', { data })
    
  return state
    .transform()
    .blur()
    .apply()
  }
```
If we remove it, it still correctly loses the focus on blur, but doesn't lose it when we switch tabs. Could it be the possible solution to remove this code?

**Comment by mernen** [comment]
@eden-lane Just tried it without this transform. The problem is that `state.isFocused` is then never set to `false`.

**Comment by ianstormtaylor** [comment]
Thanks for finding this @mernen, I've added a commit to master that monitors the windows focus and avoids blurring Slate when the tab changes. I'm going to cut a release with a few more fixes soon!
