### ISSUE TITLE
Images example throws error message: "Uncaught TypeError: Cannot read property 'ownerDocument' of null"

### ISSUE THREAD

**Issue by kellyjosephprice** [ianstormtaylor/slate#757]
If you drag and drop the image to a new location, it throws that error. This is reproducible locally and on the demo site. 

browser: Chrome Version 58.0.3029.81 (64-bit)
os: macOS Sierra Version 10.12.4
slate version: whichever build is on the demo's page. And v0.19.20.

![image-drag-n-drop](https://cloud.githubusercontent.com/assets/451488/25544498/965fca5c-2c0f-11e7-8a30-a02fa6a8d846.gif)

**Comment by ianstormtaylor** [comment]
Hey @kellyjosephprice! I can't reproduce this, can you provide more info, like browser, OS, version of Slate? A GIF showing the behavior would be ideal.

**Comment by kellyjosephprice** [comment]
@ianstormtaylor I updated the main comment. Also, thanks!

**Comment by ianstormtaylor** [comment]
Thanks @kellyjosephprice!
