### ISSUE TITLE
Updating a custom block takes focus away from it

### ISSUE THREAD

**Issue by mernen** [ianstormtaylor/slate#766]
When a block includes editable controls inside (like `<input>`), it’s pretty much impossible to type in, if the block’s data is updated on every change.

Steps to reproduce:

1. Open an editor with blocks that include focusable fields, like http://slatejs.org/#/embeds
2. Change the field in any way, like trying to type in a new URL

Expected: should be possible to continue typing like in any `<input>` field.

Actual result: block is apparently rebuilt and focus is lost after the first change.

**Comment by alexeygolev** [comment]
Duplicate #749

**Comment by mernen** [comment]
Indeed, sorry. Should this be closed then?

**Comment by alexeygolev** [comment]
I can't really close it as I'm not a contributor. Just referencing the original issue to ease the tracking and for people who might stumble upon the same problem

**Comment by ianstormtaylor** [comment]
Closing for cleanup, thanks @mernen!
