### ISSUE TITLE
Exposing onDocumentChange to the plugins

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#770]
Hey @ianstormtaylor, I was going to build an autosave plugin that saves on debounced `onDocumentChange`. Currently, I have that functionality in the `onDocumentChange` method passed to the editor. And I'd like to move it to a plugin.

To do that, I'd need `onDocumentChange` available to the plugins. Is that something you'd like as a PR? Are there any implications of this that you can foresee?

At a quick glance, it seems like [this line here](https://github.com/ianstormtaylor/slate/blob/master/src/components/editor.js#L233) needs to call `stack.onDocumentChange`.

**Comment by ianstormtaylor** [comment]
Hey @oyeanuj! I think for now I'd rather not expose that, since I'm not even sure about keeping `onDocumentChange` around. I believe this can be implemented by just caching the `state` from `onChange` and comparing `state.document != prevState.document` though inside a plugin closure.

**Comment by oyeanuj** [comment]
No problem, I'll implement your suggestion - thanks! I am curious though what makes you want to remove `onDocumentChange`?

**Comment by ianstormtaylor** [comment]
I'm not set on removing it or anything, just that I'm not yet sure it should be handled natively by Slate, and not by users instead. So for that reason, I wouldn't want to create plugin dependencies on it that make it harder to remove later. Just seems like there have been weird issues that crop up related to it

**Comment by dklanac** [comment]
@ianstormtaylor First off. I have to thank you for your work here with Slate. It's so well done. I have a key project I'm working on that needed a flexible editor, and your approach is how I hope to see DraftJS core eventually go. 

I do support the idea of getting rid of `onDocumentChange` in favor of allowing devs to use the built in React callbacks like `componentDidUpdate` to decide when to serialize. It feels more natural to me after I saw your suggestion earlier in this thread.

Thanks again for your work here.

**Comment by dmitrizzle** [comment]
lol I built exact same plugin, but used _.throttle() instead. Same issue. Will try both componentDidUpdate and `state.document != prevState.document` - thank you for exposing this info.
