### ISSUE TITLE
onBlur handler not called on defocusing the editor?

### ISSUE THREAD

**Issue by deep-c** [ianstormtaylor/slate#773]
Hi,

Just noticed this, when I hooked slate up to redux-forms and the onBlur event never fired. I think this is a bug?

The onFocus event does get fired but not the onBlur event as seen here [fiddle](https://jsfiddle.net/2zokvrvt/92/)

**Comment by tyler-johnson** [comment]
Yep, and this was working in the previous version, 0.19.20: https://jsfiddle.net/2zokvrvt/93/

**Comment by ianstormtaylor** [comment]
Thanks for opening this @deep-c. Cutting a release now that fixes this and maintains the new window checking behavior!
