### ISSUE TITLE
rule doesn't get revalidated until backspace is pressed

### ISSUE THREAD

**Issue by bodyflex** [ianstormtaylor/slate#774]
I have the following rules in my schema:
```js
const isNumeric = value => String(parseFloat(value)) === value;
// ...
    {
      match: node => node.kind === 'block',
      validate: block => block.nodes.find(node => {
        return node && node.kind === 'text' && isNumeric(node.text);
      }),
      normalize: (transform, block, textNode) => {
        return transform.wrapInlineByKey(textNode.key, 'numeric');
      }
    },
    {
      match: node => node.type === 'numeric',
      validate: numericNode => !isNumeric(numericNode.text),
      normalize: (transform, numericNode) => {
        return transform.unwrapInlineByKey(numericNode.key, 'numeric');
      }
    }
```
this is supposed to wrap all text nodes that contain numeric values in an inline block of type "numeric", and unwrap all "numeric" inline blocks if they contain non-numeric text.

this is how this behaves though:
1) when typing `123`: wraps in numeric block
2) when adding `.`: unwraps numeric block (`123.` is not numeric)
3) when adding `45`: *incorrectly* doesn't wrap in numeric block (`123.45` is numeric)
4) when pressing backspace: correctly formats again (`123.4` is numeric)

`match` or `validate` don't get called for some reason in step 3, only when pressing backspace. am I doing something wrong?

**Comment by bodyflex** [comment]
here's an example replicating this behaviour: https://jsfiddle.net/q9us4n1y/1/

**Comment by soulwire** [comment]
It looks like plugin schema rules aren't being called on all of the same transforms as the core plugin rules are. Some initial debugging shows that `normalizeNode` is called as expected when you insert text, but it's only being passed the core schema—hit backspace though and it does get the plugin schema 🤔

**Comment by soulwire** [comment]
Perhaps this is related to what you described in #750 @ianstormtaylor, insofar as if a change to a text node `isNative`, then it skips parts of the stack for perf reasons?

**Comment by bodyflex** [comment]
apparently this is caused by `isNative` at [src/plugins/core.js:145](https://github.com/ianstormtaylor/slate/blob/master/src/plugins/core.js#L145)

if I'm understanding this correctly, we'd also have to check if the schema would have an effect on `startText` so that a re-render would be required?

is this perf improvement actually significant? what was the reason for introducing it?

**Comment by soulwire** [comment]
Interested to know whether there's a significant performance impact too, since between this and #750 I can't think of a way to get around this behaviour and implement the kind of rule @bodyflex described (since modifying state in `onChange` causes duplicate characters).

Perhaps a simple interim solution would be a flag (as an Editor prop) to override `isNative`? I'll put in a PR if that sounds ok.

**Comment by bodyflex** [comment]
@soulwire that temporary solution crossed my mind as well, would be fine by me!

**Comment by ianstormtaylor** [comment]
Should be fixed with `isNative` removed now!
