### ISSUE TITLE
node.insertText is not a function

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#775]
Hey @ianstormtaylor, it seems like when trying to insert text inside a node using `insertTextByKey`, I am getting this error. On searching through the repo, I can't seem to find `insertText` as a function on the `node` model either.

Here is the line where it is failing: https://github.com/ianstormtaylor/slate/blob/master/src/transforms/apply-operation.js#L119

And here is a simple JSFiddle illustrating it (insert text in the default node): https://jsfiddle.net/c77z6ax4/2/

**Comment by ianstormtaylor** [comment]
I believe this is happening because `insertTextByKey` expects a `key` that refers to a Text node, but it's probably getting passed a Block or Inline.

I'd be open to a pull request that allows it to handle either though.

**Comment by oyeanuj** [comment]
@ianstormtaylor you were right, passing a text node works. I've issued a PR that clarifies the doc as well. 

As for allowing other node, to be honest, I don't feel confident enough to mess within the core but I will try to come back to it. But On a quick investigation, it seems that the node model would need to implement an `insertText` method which would select the first text of the node and then call `Text.insertText` on that text node. 

Does that sound right?

**Comment by ianstormtaylor** [comment]
@oyeanuj I think instead if implementing `insertText` on all nodes, we'd instead want to use the key and offset to fetch the leaf text node with updated offset, and then run the insert text operation on that new leaf text node.

**Comment by oyeanuj** [comment]
Thanks @ianstormtaylor! Implemented in #784.
