### ISSUE TITLE
Use Google Input (Or other Input)  to modify text,  it will cover other content.

### ISSUE THREAD

**Issue by FrankQiang** [ianstormtaylor/slate#783]
Maybe I found a bug

For example
 1. I write "I love slate so much" on slate.
 2. "We love slate so much" is better, so I change "I" to "We". 
 3. But it will be "Weove slate so much" when I use Google Input

Meanwhile, It's ok when I don't use Input

**Comment by ianstormtaylor** [comment]
Hey @FrankQiang what is "Google Input"? What OS/browser are we talking about?

**Comment by FrankQiang** [comment]
Somthing like this [https://www.google.com/inputtools/services/features/input-method.html](https://www.google.com/inputtools/services/features/input-method.html)  

I use this application on my browser

**Comment by ianstormtaylor** [comment]
Ah thank you! I spent some time a while back to get it working with IME, but I didn't have a reliable way to test it, so it could definitely have broken since then sadly.

**Comment by ianstormtaylor** [comment]
Closing in favor of #854
