### ISSUE TITLE
Using plugin transforms

### ISSUE THREAD

**Issue by jtadmor** [ianstormtaylor/slate#785]
Hi,

Just starting to play around with this lib and its great, so thanks!

One thing I noticed is that using transforms from plugins (specifically using the `slate-edit-list` plugin right now) is a little bit clumsy.

It seems like if a plugin is already going to expose a `transforms` property, that we ought to beable to just do something like:

```
const nextState = state
  .transform()
  .wrapInList(true)
  .apply()
```

Instead of (as I understand current behavior):
 
```
const t = state.transform()
const nextState = ListPlugin.transforms
  .wrapInList(t, true)
  .apply()
```

The latter doesn't compose nearly as nicely, for instance if we wanted a particular event handler to use transforms from multiple plugins.

A couple concerns I can think of: namespacing, making sure the plugin methods are properly bound to utils from the lib.

It seems like this wouldn't be too involved, just need to pass the plugins into some code like this:

```
plugins.forEach(p => {
  Object.keys(p.transforms || {}).forEach((type) => {
    Transform.prototype[type] = function (...args) {
      debug(type, { args })
      p.transforms[type](this, ...args)
      return this
    }
  })
})
```

I'd be happy to try to work on a PR for this if it seems like a reasonable idea.

**Comment by ianstormtaylor** [comment]
Hey @jtadmor good question. Check out the [`call`](https://docs.slatejs.org/reference/models/transform.html#call) transform method, which lets you do:

```js
const nextState = state
  .transform()
  .call(wrapInList, true)
  .apply()
```

Not quite as nice as the mixin approach, but avoids a bunch of the concerns around namespacing, and having to have the state aware of plugins. Hope that helps!

**Comment by jtadmor** [comment]
Ah, very nice! Thank you.
