### ISSUE TITLE
Freezing and crashing when selecting a large amount of text

### ISSUE THREAD

**Issue by SamWyld** [ianstormtaylor/slate#791]
I assume this is a bug -

When the editor holds a large amount of text (20 thousand or more words), the editor's speed seems to greatly decrease. Selecting all of the text with the use of cmd+a (shift-cmd-down arrow at the top of the editor has the same effect) leads to the whole browser either crashing or freezing for around 30 seconds, if you are able to select all of the text if you un-focus the problem will re-occur. This problem only seems to arise when there is a toolbar/buttons using the editor state.
Without the toolbar as seen in the [large text example](http://slatejs.org/#/dev-large) the editor seems to work as expected. If you paste the text from the "large document" example into the "rich text" example and attempt to select all of the text, the freezing happens. From what I can tell this happens in all of the demos that use a toolbar (including the hovering toolbar).
I attempted to see if this was a problem with the number of buttons that were being rendered by the toolbar. However, no matter how many buttons are being rendered by the toolbar the same problem outlined happens.

I'd assume that selecting all of the text and deselecting it would work smoothing without a prolonged freeze or crashing.
Trying to do the same things in all of these editors works smoothly -
https://draftjs.org/
http://prosemirror.net/
https://quilljs.com/

jsfiddle https://jsfiddle.net/ben_davis/nrgtj7nq/11/

**Comment by alexeygolev** [comment]
Pasting large text takes a noticeable amount of time as well. According to chrome's timeline it spends a huge amount of time [here](https://github.com/ianstormtaylor/slate/blob/master/src/plugins/core.js#L845).

**Comment by ianstormtaylor** [comment]
Hey @SamWyld thanks for opening this! I've just opened #794 which makes this significantly faster. I think there are definitely a lot more places in the code base with low-hanging fruit like that that we can find. 

I'm going to close this issue in a bit because it's hard to "resolve" completely, but if you profile specific places where you think Slate is wasting a lot of time, please open more!
