### ISSUE TITLE
change pasteText to construct and insert a fragment

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#795]
As @alexeygolev pointed out in #791 the `pasteText` handler in the core plugin takes a lot of time. It's currently running many transforms, but that's kind of weird. It could probably just construct the fragment beforehand, and use `insertFragment` instead for a boost in performance. Not sure.

**Comment by alexeygolev** [comment]
@ianstormtaylor I tried constructing a fragment but couldn't figure out how do it properly:) I can't seem to understand what arguments the constructor accepts

**Comment by ianstormtaylor** [comment]
Off the top of my head, we'd need to create a `Block` with `Text` for each line, and then a `Document` with all of the blocks, and then insert that with `insertFragment(document)`

**Comment by alexeygolev** [comment]
Tried this
```js
function onPasteText(e, data, state) {
    debug('onPasteText', { data })

    const blocks = data.text.split('\n').map(
      line =>
        new Block({
          isVoid: false,
          type: 'paragraph',
          nodes: List([ Text.createFromString(line) ]),
        })
    )
    const fragment = new Document({ nodes: List(blocks) })

    return state.transform().insertFragment(fragment).apply()    
  }
```
Pasting takes about 500ms on 100,000 words as opposed to ~1200ms with the current solution. I still think we can maybe shave off some more time if we can construct a json structure and then transform it into a fragment just before applying the transformation. I couldn't figure out what that json structure should be though

**Comment by ianstormtaylor** [comment]
@alexeygolev we can use `Raw.deserializeNode` for this I think! And then it's just like the normal raw deserializing from other places.
