### ISSUE TITLE
state.{edge}Marks

### ISSUE THREAD

**Issue by mxstbr** [ianstormtaylor/slate#803]
#### Do you want to request a *feature* or report a *bug*?

Feature

#### What's the current behavior?

You can get `state.{edge}Block` and `state.{edge}Text`, where edge is one of `start`, `end`, `focus` or `anchor`.

#### What's the expected behavior?

I should be able to get `state.{edge}Mark` to get the current mark the user is on.

**Comment by mxstbr** [comment]
Looking a `node.js` this should just be a matter of adding

```JS
  getClosestMark(key) {
    return this.getClosest(key, parent => parent.kind == 'mark')
  },
```

and then using that upstream in `state.js` to implement `{edge}Mark` with `this.selection.{edge}Key` I think?

**Comment by ianstormtaylor** [comment]
I believe this should be `{edge}Marks`, I like this idea! Open to a PR that adds this.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
