### ISSUE TITLE
Wrong cursor position after deleting an empty line, then undoing

### ISSUE THREAD

**Issue by pa-nam** [ianstormtaylor/slate#805]
#### Do you want to request a *feature* or report a *bug*?
*bug*

#### What's the current behavior?
Deleting an empty line, then undo, the cursor will keep staying at the last line.
Here a gif image for that bug on our slate home page example:
![slate-backspace-empty-line-bug](https://cloud.githubusercontent.com/assets/19988263/25837872/1e6d9980-34ba-11e7-9eb7-f6e572ff8be7.gif)

#### What's the expected behavior?
As the above image, after undoing, the cursor should stay at the next line.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
