### ISSUE TITLE
Contributing.md: running examples

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#81]
Contributing.md says, to run the examples, we first run:

```
make install
```

then "And then build the source and run the examples server:"

```
make dist
make start-examples
```

A few things:

1. `make install` seems to automatically do `make dist`, so it should only be `make install`, correct?
2. `make start-examples` is nonexistent. `make examples` and `make start` are separate commands. Should `make start-examples` be changed to `make start`, or should the `start` command in the Makefile be changed to `start-examples`?
3. Or, should the Contributing.md be updated to be:

```
make dist
make examples
make start
```

**Comment by ianstormtaylor** [comment]
Good call, thanks for catching this. Just pushed updated instructions that take everything you mentioned into account. Moved the examples instructions into the `./examples` directory so that they're easier to find accidentally, but linked to them still from `Contributing.md`!
