### ISSUE TITLE
`onChange` is fired before `onBeforeChange`

### ISSUE THREAD

**Issue by soulwire** [ianstormtaylor/slate#811]
I'm really enjoying working with Slate—thanks so much for all the hard work @ianstormtaylor!

I've noticed something that seems to be a bug. When a plugin provides `onBeforeChange` and `onChange` handlers, `onChange` appears to be called _before_ `onBeforeChange`.

Here's an example:

https://jsfiddle.net/se37n326/1/

![gif](http://g.recordit.co/V3edCBhVZb.gif)

Perhaps my understanding on the stack execution order isn't up to scratch and this is desired behaviour. If so would you mind clarifying?

Thanks

**Comment by ianstormtaylor** [comment]
Hey @soulwire, I'm actually not sure why that's happening. If you investigate and figure out what the situation/bug is I'd love a PR if it's wrong!

**Comment by soulwire** [comment]
Hi @ianstormtaylor,

It looks like what's happening is that since `onBeforeChange` is called when [componentWillReceiveProps](https://github.com/ianstormtaylor/slate/blob/master/src/components/editor.js#L155), this gets run after [onChange](https://github.com/ianstormtaylor/slate/blob/master/src/components/editor.js#L224).

This suggests to me that this might be the intended behaviour, with the understanding that 'change' in the context of `onChange` means _'the state has changed'_, whereas in the context of `onBeforeChange` it means _'the editor is about to adopt the new (changed) state'_. Although the docs do mention that `onBeforeChange` is:

> invoked whenever the editor receives a new state and before propagating a new state to onChange

I can certainly work on a PR that makes this behave in the way the docs suggest, if you agree that it's not currently working as expected?

**Comment by ianstormtaylor** [comment]
Ah nope, you're right it is currently working as architected. I'm actually considering removing the `onBeforeChange` handler to get rid of weird cases like this in the future. Thanks for investigating!
