### ISSUE TITLE
Cursor moves out of view on carriage return at bottom of containing element

### ISSUE THREAD

**Issue by malloryerik** [ianstormtaylor/slate#819]
_On Mac, in Chrome, Safari, and Firefox, using the latest version of Slate._

Typing return while the character is at the lowest line in an editor's window, the cursor moves out of view, "below" the bottom of the editor window.  Only when two characters/keys have been entered does the cursor jump back into view.

This is different from all text editors I've used in the past, and may may Slate unusable as a long-form editor, since writing very often happens at the bottom of an editor window.

![slatejscursorissue](https://cloud.githubusercontent.com/assets/10395849/26182512/b56e5306-3bb3-11e7-949a-6493449070e7.gif)

You can do it yourself here: https://jsfiddle.net/malloryerik/61obtfja/2/ 

![draftjscursor](https://cloud.githubusercontent.com/assets/10395849/26182716/e892d382-3bb4-11e7-9cde-38d3229a8c59.gif)

Btw, thanks for all of the work you've done on Slate.

**Comment by malloryerik** [comment]
Is this really not a problem for anyone but me?

**Comment by dmitrizzle** [comment]
I can reproduce this too.

**Comment by ianstormtaylor** [comment]
I believe this is fixed now.
