### ISSUE TITLE
add the ability to add marks to the collapsed cursor

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#82]
Steps:

1. Open editor and begin typing
2. Hit Command+B to start formatting text as bold
3. Continue typing
  - Expected behavior: Text typed after hitting bold formatted as bold
  - Actual behavior: Text is not bold

Seems like text can only be made bold by selecting already-typed text and hitting the Command+B key (or selecting bold in the toolbar). This applies for other common formatting like italics, underline, etc. 'Expected behavior' based on [ContentEditable behavior](http://html5demos.com/contenteditable).

**Comment by ianstormtaylor** [comment]
Good call, I'd like to get this behavior added in!
