### ISSUE TITLE
BBCode serialization

### ISSUE THREAD

**Issue by Soletiq** [ianstormtaylor/slate#823]
#### Do you want to request a *feature* or report a *bug*?
Request feature

My application has to be able to convert to and from bbcode. The serialization slate already offers is great, but this would make it even better!

**Comment by ianstormtaylor** [comment]
Hey @Soletiq, good question. Serializing to/from BBCode is a good use case, but it's not something that Slate's core logic is going to provide. Instead, it's definitely something that would work as a third-party module, so I'd encourage you to create it!
