### ISSUE TITLE
The placeholder doesn't take up width

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#825]
When I have an `Editor` inline with other elements, or within a table cell, the `Editor` placeholder won't take up width, so it overlaps the element to the right.

I tried setting `placeholderStyle` to `display: inline-block`, which doesn't help this problem.

I tried setting `placeholderStyle` to `white-space: nowrap`, which prevents the text from wrapping when it's a squooshed cell of a table.

I tried setting `placeholderStyle` to `position: static`, which does make the placeholder take up  width, but it puts the editor cursor *above* the placeholder.

**Comment by ianstormtaylor** [comment]
Hey @tashburn in the newest version of Slate the placeholder logic has changed, and you can define your own components to render for the placeholder, so you should have complete control over this now!

**Comment by tashburn** [comment]
@ianstormtaylor Fantastic. Thanks for letting me know.
