### ISSUE TITLE
isNative breaks Node.shouldComponentUpdate

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#829]
When `isNative` flag is set to `true`, the component [`Content` blocks the React update](https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L104), so the underlying `Node` component don't get any update with their props.

Later, if we reset the editor state (reset feature, or custom undo handling), the `Node.shouldComponentUpdate` fails to detect change because they get `nextProps.node === prevProps.node` to be true [here](https://github.com/ianstormtaylor/slate/blob/master/src/components/node.js#L110).

[JSFiddle](https://jsfiddle.net/10fzuat1/1/)

**Comment by ianstormtaylor** [comment]
Ah damn. I'd be curious to know if the `isNative` is still saving us tons of performance. There might be other places to earn that performance back, and have it not be an issue. If it is possible to remove it without bad performance that would be amazing.

**Comment by bzafar-npr** [comment]
The issue I am experiencing seems to be related to this bug.  I am applying an error CSS class to the editor in certain cases, via props.  Sometimes the editor component update is blocked, even when the prop values change, so the error CSS class is not applied and users don't see the editor highlighted.  The update is blocked until a user clicks into the editor field and it has focus.  I can programmatically apply focus (blur also works), but this is hacky and also buggy.  Do you have any suggestions?

**Comment by ianstormtaylor** [comment]
Should be fixed with `isNative` removed now!
