### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by mitermayer** [ianstormtaylor/slate#83]
Great job, and great effort! looking forward to see how the project will shape it self!

Would be great if this could export some type definitions for either typescript or flow.

**Comment by ianstormtaylor** [comment]
Thanks :) glad you're interested! I'd definitely be down for this. I haven't used either myself, and would want to wait a little bit more until API's stabilize, but at that point I'd be +1 someone contributing them!

**Comment by ianstormtaylor** [comment]
Closing in favor of @joehua87's mention of `flow-typed` in #148.

**Comment by arekkas** [comment]
@ianstormtaylor there are still no type definitions, right? Maybe re-open this issue?

**Comment by frederickfogerty** [comment]
Please re-open this issue - there are no type definitions on `flow-typed`.
