### ISSUE TITLE
Empty lines don't show a selected space on Mac

### ISSUE THREAD

**Issue by natew** [ianstormtaylor/slate#838]
#### What's the current behavior?
Selecting lines that are empty doesn't show any selection.

#### What's the expected behavior?
On macs, usually it shows an empty space that is selected, even if the line is empty. This helps you to see that there is a line there.

Just opening to track this.

**Comment by davolokh** [comment]
Few corrections about empty lines selection.
This is not a macOS specific issue. Checked on HightSierra and ArchLinux.
Screenshots are taken from [http://slatejs.org/#/rich-text](http://slatejs.org/#/rich-text).

**Works as expected in Safari:**
<img width="731" alt="screen shot 2018-05-21 at 11 57 03 am" src="https://user-images.githubusercontent.com/2715874/40299220-4385bef2-5cee-11e8-9b48-c244ef105f89.png">

**Doesn't work as expected in Chrome (Mac):**
![screen shot 2018-05-21 at 11 56 39 am](https://user-images.githubusercontent.com/2715874/40299254-58623922-5cee-11e8-9825-1d777c67506c.png)

**Doesn't work as expected in Chrome (Linux):**
![image](https://user-images.githubusercontent.com/2715874/40299451-f4d8ccee-5cee-11e8-870e-f019c7828e94.png)


My guess, this is how zero width whitespaces work in chrome.

**Comment by brendancarney** [comment]
What should be done here? Other editors use:

CKEditor: `<br/>`
Google Docs: &nbsp;

**Comment by Slapbox** [comment]
Works as intended in Chrome on Mac, Windows, and Linux. It highlights exactly as I'd expect in every circumstance. Can someone show an example of this issue today?

The way Safari highlights text won't be the same as in other browsers, but every browser does what I'd expect.
