### ISSUE TITLE
onSelect doesn't fire when using right/left arrows on Mac

### ISSUE THREAD

**Issue by natew** [ianstormtaylor/slate#839]
1. Create empty lines in document
1. Add plugin with onSelect
2. console.log() there
3. Move cursor using left/right arrows on mac
4. onSelect doesn't log
5. onSelect does log when using up/down

**Comment by danburzo** [comment]
Confirming that `onSelect` is not triggered on plugins when navigating a set of empty blocks with the left/right arrow keys.

**Comment by ianstormtaylor** [comment]
@natew what are you looking to do with `onSelect`? I think this is slightly confusing from a UX perspective, but you are probably looking to use `onChange` instead. 

The `onSelect` plugin handler is for handling DOM-level selections, in case you wanted to coerce them into a selection change. Mostly this is all handled by the core plugin, so you'd never need to use it. I'm going to close this one on that assumption, but feel free to respond if you have a use case that I'm not considering. Thanks!

**Comment by hanstar17** [comment]
Hi @ianstormtaylor, my use case for onSelect is to make something like the hovering menu in the examples, but I want to make it appear only when selection by user is done, like Medium's editor. onSelect event is triggered when selection is complete in textarea, so I thought that onSelect in Slate would behave in the same way, but it's not. What is the recommended way to implement that in Slate?
