### ISSUE TITLE
Embeds example completely broken on Firefox

### ISSUE THREAD

**Issue by AlbertHilb** [ianstormtaylor/slate#843]
Embeds example completely broken on Firefox 53 (Ubuntu 16.04). :cry:

1. Insert cursor in the first line of text above the video, let's say just after the word "this" and then press `down-arrow` key, the caret jumps to the `input` element below the video but pressing `backspace` or `delete` keys still removes text from the line above the video.

2. Clicking on the input element below the video, put the caret inside it. Then, try to move the caret using the mouse or pressing `left-arrow` or `right-arrow` keys, the caret doesn't move.

3. Look at console while editing `input`element content. A lot of errors of the type
    ```
    Error: Permission denied to access property "isContentEditable"
    ```
    are raised.

The main problem is this: in Firefox, when the selection is inside an `input` element,  `anchorNode` and `focusNode` are **private** text nodes living inside it and accessing their properties or methods is denied.

**Comment by geakstr** [comment]
I see `Error: Permission denied to access property "window"` in Firefox (63) when clicking on input in embed youtube example. In my project as well, I have void blocks with inputs, can't find workaround for that.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1496368/49668143-b126e000-fa76-11e8-8900-095a35f5f85a.png">

**Comment by brendancarney** [comment]
I can't recreate this error. It may be resolved. Should we close the issue?

**Comment by brendancarney** [comment]
Unable to recreate, please comment on the issue if you can and would like it reopened.
