### ISSUE TITLE
how to insert a node with child nodes

### ISSUE THREAD

**Issue by chengzhenping** [ianstormtaylor/slate#849]
I want insert a link,
i used  transform's  insertInline  api to insert a link,
but can't insert a text node  in the same time.
how can i do this

**Comment by oyeanuj** [comment]
@chengzhenping You can use create an inline first using `Inline.create`, then insert it using `insertInline` and then use `insertNodeByKey` and pass the inline created as the parent to insert it in. 

Btw, I'd recommend joining the Slack channel as there are more folks out there who can help with these issues.

**Comment by soulwire** [comment]
Just to supplement @oyeanuj's comment with an example (slightly different approach, adding the text when constructing the inline.)

```javascript
const link = Inline.create({
  type: 'link', // or whatever you have in your schema
  data: { href: 'http://foo.bar' },
  nodes: [ Text.createFromString('foo') ]
})
// Then use insertInline however you're already doing it
onChange(state
  .transform()
  .insertInline(link)
  .apply()
)
```
And I second the suggestion of joining the Slack channel! Lots of helpful folks in there like @oyeanuj and plenty of code snippets floating around :)

**Comment by chengzhenping** [comment]
can you supply  the  slack channel  name ,thks

**Comment by chengzhenping** [comment]
my email  chengzhenping@gmail.com ,or you can invite me,  thks a lot
