### ISSUE TITLE
Enforce document structure restrictions in node constructors

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#859]
Right now there are a few different constraints on the document structure that we enforce in the schema...

- Children of the document must be blocks. 
- Children of other nodes can either be all blocks or all inlines and texts. 
- etc. 

But when created a new node via `Block.create` or similar, there's no schema validation. And there's no indication if you initialize it with an invalid structure. This leads to hard to debug edge cases. 

I don't have a great solution in mind. It seems like we'd need to run the same sorts of checks for the schema on every node creation. If anyone has ideas I'd love to hear them!

**Comment by dmitrizzle** [comment]
Have you tried this tool? https://www.npmjs.com/package/slate-schema
I thought it might be relevant. Haven't tested myself, the docs and Git repo aren't available (anymore?)

**Comment by oyeanuj** [comment]
@ianstormtaylor +1 to that, would really also help with the developer experience (even if that check was turned off in production mode, sort of like React?)

**Comment by ianstormtaylor** [comment]
@oyeanuj ah very good idea! I often forget that pattern of separating warnings to be only in development. That could definitely be good for performance if it is a bottleneck! Nice 😄

**Comment by ianstormtaylor** [comment]
Nevermind, I think this would be too much magic. There are scenarios where you want to create empty nodes for instance. If you need this, you'll have to enforce it yourself. Although I'd recommend trying to code such that you don't need this.

**Comment by oyeanuj** [comment]
@ianstormtaylor Did you mean the warnings or the logic would be too much magic? If you think adding warnings is helpful in development mode, I could create a separate ticket, and could start a  list of places where Slate could help the developers with those warnings.

**Comment by ianstormtaylor** [comment]
Sorry for not being clear—I think the logic is too much magic, since there are cases where you don't want it to normalize for you.
