### ISSUE TITLE
how do you change a link's HREF

### ISSUE THREAD

**Issue by joshmarinacci** [ianstormtaylor/slate#861]
The Link example shows how to create and delete a link. It doesn't show how to update the href of a link, however.  If the cursor is over a link I can detect this, grab the existing href, and try to delete then insert a new link, but that gives me an error. I'm assuming there's a way to just update the href on the map, right?

**Comment by 282159468** [comment]
and when i click link in editor, it's does not jump

**Comment by pizn** [comment]
@joshmarinacci my solution:

![image](https://cloud.githubusercontent.com/assets/986480/26708607/5f5f1338-477f-11e7-9b0a-ac93526258d5.png)

Anchor or focus the link inline, show the popover with link input. User can update the link url at this time. When input change, use `setNodeByKey` to change the link data.

Notice: Link input element can add `onClick` method and `stopPropagation`, it will not jump to editor. cc @282159468 

PS: It's hard to autoFocus to input.

**Comment by joshmarinacci** [comment]
Thanks. This is what I ended up using:

```
        this.reallyCreateLink = (href) => {
            console.log("making link with text",href);

            var state = this.state.state;
            var link = state.inlines.find(inline => inline.type === 'link');
            if(link) {
                state = state
                    .transform()
                    .setNodeByKey(link.key, {data: link.data.set('href', href)})
                    //.collapseToEndofNextText()
                    .apply();
            } else {
                state = state
                    .transform()
                    .wrapInline({
                        type: 'link',
                        data: {href}
                    })
                    .collapseToEndOfNextText()
                    .apply();
            }

            this.setState({
                state:state,
                linkDialogVisible:false
            });
        };
```

**Comment by LarsAsDev** [comment]
How would one go about it in the current version?

I can't find a demo anywhere on how to change props on an element in the current version.
