### ISSUE TITLE
link problems

### ISSUE THREAD

**Issue by chengzhenping** [ianstormtaylor/slate#866]
i insert a link in editor
const link = Inline.create({
type: 'link', // or whatever you have in your schema
data: { href: linkUrl },
nodes: [ Text.createFromString(linkDescript) ]
});
const newState = state.transform()
.focus()
.insertInline(link)
.apply();

and i defined a shema of it .
then  i got the correct html as below:
<a href="http://www.baidu.com" target="_blank" data-key="58"><span data-key="57"><span data-offset-key="57-0">百度</span></span></a>
but this link is unclickable.
is there some way to let it clickable

**Comment by pizn** [comment]
@chengzhenping You maybe handle the link node click function, such like this:

```
// Schema
const schema = {
    nodes: {
        link: LinkNode,
    }
}

// The Link Component
class LinkNode extends React.Component {
    onClick = (e) => {
        e.stopPropagation();
        // maybe you can do the link open on the window here
       ...
   }
   
   render = () => {
       const { children, attributes, node } = this.props;
       const href = node.data.get('href');
       return (
           <a href={href} onClick={this.onClick} {...attributes}>{children}</a>
      )
   }
}
```

!!! Hey, please use code format when you post an issue.
