### ISSUE TITLE
Chinese input methods breaks. " Cannot read property 'firstChild' of null". (with official demo)

### ISSUE THREAD

**Issue by FateRiddle** [ianstormtaylor/slate#871]
#### Do you want to request a *feature* or report a *bug*?

bug.

#### How to produce the bug?

1. Using the official demo here: https://jsfiddle.net/2zokvrvt/7/
2. Download a Chinese input method, like [https://www.google.com/intl/zh-CN/ime/pinyin/](https://www.google.com/intl/zh-CN/ime/pinyin/) or
or [http://pinyin.sogou.com/mac/](http://pinyin.sogou.com/mac/)
3. Enter the demo, press **ENTER** to start a new line(must be an empty new line), 
4. Switch to Chinese input method(usually **ctrl + space** to switch input method), 
5. Type something and the help tool will show, then press **space**(important) to choose the default first option. A bug will show as "Cannot read property 'firstChild' of null", and only a space will show on the line you type in. 
6. (Then press **ENTER** or **backspace**, the actual Chinese characters will show this time.)

#### What's the expected behavior?

Chinese character properly shown when you press space and no error pops. like [https://www.google.com/intl/zh-CN/inputtools/try/](https://www.google.com/intl/zh-CN/inputtools/try/)

btw, I tried draft.js, and they don't have the same issue. I switch to draft.js only temporarily as I love the api of slate.js so much more. Hope this one gets solved soon :D

**Comment by FateRiddle** [comment]
btw, I tried draft.js, and they don't have the same issue. I switch to draft.js only temporarily as I love the api of slate.js so much more. Hope this one get solved soon :D

**Comment by liSong5713** [comment]
I found the same issue too ,need some help!

**Comment by ianstormtaylor** [comment]
Closing in favor of #854

**Comment by FateRiddle** [comment]
@ianstormtaylor  I switched back from draft.js to slate.js today，installed latest slate, and the error is still there, same problem, same behavior.

**Comment by YurkaninRyan** [comment]
@FateRiddle This wasn't closed because a fixed was introduced, it was closed because there are other issue tickets with more history on them, with PR's that are out.

Currently it's hung up because no one has explained what we should do with the fixes.  Do we need to merge both?  Is a device problem or device agnostic?  I think once someone can give an informed opinion the fix will get in

**Comment by FateRiddle** [comment]
@YurkaninRyan This problem is serious that slate will lose at least every Chinese user. 
It seems mobile works fine, only happen in PC/mac. Looking into the related issue  #854 , they are the same error. And none is fixed.

You can install a Chinese input method, and open  http://slatejs.org, place cursor at the start of a line( or enter to start a new line), and try typing something. 

If you have a good recording tools recommendation, I think I can explain it better.
