### ISSUE TITLE
[IME] Should not be re-rendered when use input method

### ISSUE THREAD

**Issue by pizn** [ianstormtaylor/slate#879]
The case:

![slate-re-render](https://user-images.githubusercontent.com/986480/27017434-ec888d60-4f5a-11e7-8610-f7e8de5137dc.gif)

When the editor has video, iframe, or some complex component like MathJax, it will very clear to see the html DOM re-render.

I found [`onCompositionEnd`](https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L357) event  has some problems with use setTimeout to listen another composition event, and increment the `forces` key, and I will try to fixed it.

**Comment by ms88privat** [comment]
Did you find a solution? The problem is, that the components do not only re-render, but they do re-mount!

**Comment by danburzo** [comment]
Hi @pizn, could you add _[IME]_ to the title of this issue? It makes it easier to round up bugs related to IMEs by a simple search. I want to investigate the problem, and this would help a lot!

**Comment by ianstormtaylor** [comment]
I believe this is due to forced re-rendering for IME changes in `<Content>`.

**Comment by sethmcleod** [comment]
@ms88privat Would you mind providing more details on how you solved this using keys?

I'm running into a similar issue where the the iframe component inside my editor is being remounted every time the user makes a change to text, causing a lot of flickering.

**Comment by ms88privat** [comment]
@sethmcleod I can't find it in the new documentation anymore.

You have to identify your exact problem first. Does your iframe component `re-render` every time or does it get `instantiated` over and over?

In the first case, try to prevent the re-render with `shouldComponentUpdate`. The second case shouldn't happen normally, but it can happen if you serialise and deserialise meanwhile. By default it will loose the keys in the state and then the component will get destroyed and instantiated again. This can be avoided if you pass a specifc option to the (de)serialise process to preserve the keys.
