### ISSUE TITLE
add the ability to disable marks while typing

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#88]
Expected behavior compared to [ContentEditable](http://html5demos.com/contenteditable).

Steps:

1. Open editor.
2. Type text and hit Command-B. Thanks to @82, this now makes text bold.
3. Type some more text, see that it is bold as expected.
4. Hit Command-B to disable bold for the following text.
5. Type some more text.
  - Expected behavior: Text is not bold.
  - Actual behavior: Text continues to be bold.

In a general sense, hitting hotkeys while typing seems to only enable marks, not disable them.

**Comment by ianstormtaylor** [comment]
Haha shoot, that was dumb of me. I'll get this fixed!

**Comment by ianstormtaylor** [comment]
Fixed in `0.1.12`! Thanks for catching that.

**Comment by markbao** [comment]
Awesome, thanks!
