### ISSUE TITLE
`setBlock` with `unwrapBlock` and no text doesn't set type correctly

### ISSUE THREAD

**Issue by revillan** [ianstormtaylor/slate#883]
#### Do you want to request a *feature* or report a *bug*?
Report a bug

#### What's the current behavior?

When there are three or more wrapped block nodes and a middle node without text is unwrapped and its type set with `setBlock()`, the node is unwrapped correctly but its type isn't set. 

![screen recording 2017-06-13 at 04 55 pm](https://user-images.githubusercontent.com/12904088/27109872-5ce23778-505a-11e7-9b0a-63ef01b65943.gif)

On OS X using Chrome and Slate 0.20.2

#### What's the expected behavior?

The node that's unwrapped gets the type that's set by `setBlock()`.

**Comment by doodlewind** [comment]
Seems to be fixed by #912, @ianstormtaylor hopefully this one can also be closed!
