### ISSUE TITLE
Editable image caption

### ISSUE THREAD

**Issue by dmitrizzle** [ianstormtaylor/slate#887]
I'm having trouble understanding how to get Slate to allow editing image captions.

This is the component I get Slate to render for all inserted images:
```javascript
export class Image extends React.Component {
  state = {};
  componentDidMount() {
    const { node } = this.props
    const { data } = node
    this.load(data.get("file"), data.get("src"))
  }
  load(file, src) {
  	if(!file || !file.name) this.setState({ src })
  	else {
			const reader = new FileReader()
			reader.addEventListener("load", () => this.setState({ src: reader.result }))
			reader.readAsDataURL(file)
		}
  }
  render() {
    const { attributes, state, node } = this.props
    const { src } = this.state
    const focus = state.isFocused && state.selection.hasEdgeIn(node)
		const className = focus ? "focus" : "nofocus"
    return src
      ? <Figure {...attributes} src={src} className={className} >Add caption to your image.</Figure>
      : <Figure {...attributes} src="" className={className}>Loading your image...</Figure>      
  }
}
```

The <Figure/> renders something like this:
```javascript
export const Figure = props => {
	return (
		<figure>
			<img { ...props } />
			<figcaption>
				<span>{ props.children }</span>
			</figcaption>
		</figure>
	);
}
```

However, it doesn't work:
![caption](https://user-images.githubusercontent.com/8587882/27203310-71c8bc60-524f-11e7-89f9-43e340cbb208.gif)

I've searched around on GitHub and Slack but wasn't able to find an answer.

**Comment by dmitrizzle** [comment]
Found a solution thanks to conorcussell on Slack.
For those who looking, it's an HTML input field that remembers the value in `data`.

**Comment by Kushan-** [comment]
Hey, i am trying to play around with caption using slatejs but unable to figure out how it will work.

I am calling image from renderNode 
`case 'image':{
        
          const src = node.data.get('src')
          return (
            <figure>
              <Image src={src} selected={isFocused} {...attributes} />
              <figcaption {...attributes}>
              
              <span>{ props.children }</span>
              </figcaption>
                
            </figure>
            
          )
        
      }`

and one is inertImage plugin 
  `InsertImages({
    extensions: ['png', 'jpeg', 'jpg' ],
    insertImage: (transform, file) => {
      console.log(`${transform} transform to ${file}`)
      return transform.insertBlock({
        type: 'image',
        isVoid: true,
        data: { file }
      })
    }
  })`

Being a newbie with slatejs, any help will be appreciate.

**Comment by dmitrizzle** [comment]
You can use this component as a guide on how it should work: https://github.com/dmitrizzle/Analog.Cafe/blob/develop/src/app/core/components/vignettes/Picture/index.js - `<PlainTextarea />` is the text field.

**Comment by Kushan-** [comment]
any luck with slatejs?
