### ISSUE TITLE
Characters are entered twice after backspacing into previous block

### ISSUE THREAD

**Issue by swhopkins** [ianstormtaylor/slate#889]
#### Do you want to request a *feature* or report a *bug*?

Reporting a bug

#### What's the current behavior?

https://jsfiddle.net/68x56tas/

When backspacing into a previous block, then entering any key, the key is entered twice and the selection is moved an extra character

![](http://g.recordit.co/1MerTsKQuo.gif)

#### What's the expected behavior?

Character should only be entered once, and selection should not jump an extra character

**Comment by ianstormtaylor** [comment]
Hey @swhopkins I think this is happening because you're rendering blocks as inline elements in the DOM since they are `<span>` nodes. If you change the to be rendered as blocks that should fix it.
