### ISSUE TITLE
Table Edit with GUI

### ISSUE THREAD

**Issue by worifon** [ianstormtaylor/slate#89]
Is there plan to implement features for create and edit table with GUI?

**Comment by ianstormtaylor** [comment]
Hey, good question!

As far as the "core" logic of Slate goes, it doesn't prescribe any notion of what your "schema" should be, so it won't have any knowledge of tables, nope. 

That being said, tables are a good example of what would go in a plugin. There's an example in the `./examples` directory that shows the beginnings of how tables might be implemented, but it's very basic, and leaves out lots of logic. 

For one of the editors I'm working on, I plan to need to implement tables a bit down the road, so I might create an open-sourced plugin for them then. They'd be more like how Dropbox Paper's tables work than Google Sheets. But it's still a ways away as a need for me. 

Hope that explains it! Feel free to follow up with more questions.
