### ISSUE TITLE
Checkbox Example Inconsistent Across Browsers

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#891]
http://slatejs.org/#/check-lists

Firefox works properly, but IE and Chrome do not.

## On pressing enter to create a new checkbox line item (with cursor at the end of a line):

**Chrome:** Creates the checkbox. Cursor disappears and focus is not on the new checkbox

**Internet Explorer:** Creates the checkbox. Cursor moves to the new line, but focus does not actually move.

**Firefox:** Creates the checkbox. Cursor moves to the new line and focus moves as well
____
- There are similar issues on IE and Chrome on backspacing. Here too, Firefox works fine.
- These issues are not present if you press enter in the middle of text in a checkbox, such that the new checkbox is immediately populated with some text.

**Comment by AlbertHilb** [comment]
This is related to the `onBlur`issue described in #853.

**Comment by danburzo** [comment]
I just want to add that Firefox/macOS also seems to have some problems with clicking on the text for the check items — it randomly selects text or makes the cursor jump to the beginning of the content area.
