### ISSUE TITLE
Decoration updates breaks selection

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#893]
In the case where the decorations of a text node depend on something external to this text node, the decorations may be updated as the selection enters this node. This breaks the selection update logic.

# Reproducing

Let's take this live example: https://soreine.github.io/slate-prism/

Steps to reproduce:

1. We will edit the last code block:
   ```html
   <!-- Some HTML -->
   <b>Hello World</b>
   ```
2. Delete the end of the comment tag
   ```html
   <!-- Some HTML
   <b>Hello World</b>
   ```
3. Point the cursor at the end of the second line `<b>Hello World</b>|`
4. The error is thrown
  ```
  bundle.js:77822 Uncaught TypeError: Cannot read property 'text' of undefined
    at findBounds (https://soreine.github.io/slate-prism/bundle.js:77822:23)
    at Object.findPoint (https://soreine.github.io/slate-prism/bundle.js:77882:21)
    at getPoint (https://soreine.github.io/slate-prism/bundle.js:76917:35)
    at onSelect (https://soreine.github.io/slate-prism/bundle.js:61544:45)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://soreine.github.io/slate-prism/bundle.js:47800:16)
    at executeDispatch (https://soreine.github.io/slate-prism/bundle.js:41728:21)
    at Object.executeDispatchesInOrder (https://soreine.github.io/slate-prism/bundle.js:41751:5)
    at executeDispatchesAndRelease (https://soreine.github.io/slate-prism/bundle.js:41155:22)
    at executeDispatchesAndReleaseTopLevel (https://soreine.github.io/slate-prism/bundle.js:41166:10)
    at Array.forEach (native)
  ```
5. If you start typing, you will probably encounter weird bugs because of an out of sync selection

# Explanation

This example showcases a decorator for code highlighting. Each code block is made of several code lines (for performance in case of large code blocks).
The decorator is applied to every code line, but takes into account the whole text of the parent code block (to support multi-line comments for example).
When you mess with the HTML comment on the first line, it will affect the result of the decoration on the second line. However, the decoration of the second line is not yet updated.
Moving the selection to the second line will trigger the decoration update, which changes the ranges of texts. This change in the ranges of text breaks [Slate's `onSelect` logic](https://github.com/ianstormtaylor/slate/blob/56e568d063537c3267f944fd616cc0989fd4f0f0/src/components/content.js#L743). Indeed, `onSelect` receives on the one hand the native selection ranges corresponding to the outdated decorations, and on the other hand the editor state with updated decorations.

**Comment by ianstormtaylor** [comment]
Hmm interesting. It sounds like we need to have the decorations actually update even when they are updating because of a change to a separate text node. I'd gladly accept a PR that fixes this. (Or with another solution if that one is wrong!)

**Comment by NA-Dev** [comment]
I had this or a similar issue. I solved it by adding event.PreventDefault() to the subsequent handler (onChange, onClick, etc).

**Comment by linonetwo** [comment]
I'm trying to add decoration on selection:
```js
// @flow

export default function MarkOnSelect({ hotKey, type } = {}) {
  if (!hotKey) {
    return {
      onSelect(event, change, editor) {
        console.log(change.value);
        const { anchorKey, anchorOffset, focusKey, focusOffset } = change.value;
        return new Promise(resolve => {
          setTimeout(
            () =>
              resolve(
                editor.onChange(
                  change.setValue({
                    decorations: [
                      {
                        anchorKey,
                        anchorOffset,
                        focusKey,
                        focusOffset,
                        marks: [{ type }],
                      },
                    ],
                  }),
                ),
              ),
            100,
          );
        });
      },
    };
  }
  return {};
}

```
But it just don't work, is it related to this issue?

**Comment by linonetwo** [comment]
Ok solved, it just need debounce when you use onSelect.

```js
// @flow
import { debounce } from 'lodash';

export default function MarkOnSelect({ hotKey, type, debounceTime = 500 } = {}) {
  const debouncedChange = debounce((change, onChange) => onChange(change.toggleMark({ type }).blur()), debounceTime);
  if (!hotKey) {
    return {
      onSelect(event, change, editor) {
        const { anchorOffset, focusOffset } = change.value;
        if (anchorOffset !== focusOffset) {
          return debouncedChange(change, editor.onChange);
        }
      },
    };
  }
  return {};
}
```
