### ISSUE TITLE
Make TEXT_RULE overridable

### ISSUE THREAD

**Issue by SamWyld** [ianstormtaylor/slate#896]
In the Html deserializer there is a `TEXT_RULE` that is being appended to a list of rules by default. This works perfectly for 99% of the use cases but for 1% (which might be a huge 1% for some) it prevents the lib user from working on a `text` level when pasting. Pasting from word brings in an armageddon of html with four horsemen of weird symbols and edge cases. At the moment there is no way to just "skip this mess" for text elements because if we return nothing from our rule the `TEXT_RULE` will handle it. It would be nice to have a way to tell the deserializer not to append a `TEXT_RULE` to a stack of rules that user provides. We have to basically fork the deserializer and use our own version that only differs in the `TEXT_RULE`.

**Comment by ianstormtaylor** [comment]
I think you can return `null` and further rules will be skipped.

**Comment by SamWyld** [comment]
I thought that would be the case however when returning null from any of the rules, this error occurs: `Uncaught TypeError: Cannot read property 'kind' of undefined`

**Comment by ianstormtaylor** [comment]
Are you on the latest version of Slate? (Just checking.) If so, I'd be open to a pull request that fixes whatever it was. I thought I had already used the `null` in practice myself, but maybe not.
