### ISSUE TITLE
Can't paste into editor in IE 11

### ISSUE THREAD

**Issue by jwoldan** [ianstormtaylor/slate#897]
A bug exists which prevents pasting text into the editor on IE11.  When attempting, nothing is pasted and an error occurs in the `getTransferData` method.

 #### To Reproduce:
1. Copy text from anywhere outside the editor
2. Click in the editor and paste, either using a keyboard shortcut, or by right-clicking and selecting "Paste"

#### Expected behavior: 
The copied text is pasted into the editor

#### Actual behavior:
Nothing is pasted and a console error occurs.

**Comment by ianstormtaylor** [comment]
Hey @jwoldan thanks, I think this is related to this PR: https://github.com/ianstormtaylor/slate/pull/882

**Comment by jwoldan** [comment]
@ianstormtaylor Thanks, looks like it!

**Comment by bendulum** [comment]
Pasting text seems to work in IE11 (Version 11.1176.10586.0), Chrome (Version 62.0.3202.94), and Firefox (Version 56.0) on Windows 10 when removing the lines:

```
  if (event.nativeEvent) {
    event = event.nativeEvent
  }
```
from `get-event-transfer.js`.

**Comment by DylanPaulusSEL** [comment]
Getting this error, and came to the same conclusion as @bendulum. Is `event.nativeEvent` something we need to be checking for? I'll be willing to work on this bug if no one else is currently!

Let me know if this seems to be on the right path. I see two solutions:

1. Remove the whole if-statement if checking for `event.nativeEvent` isn't needed.
2. Using `IS_IE` from `slate-dev-environment`, change the if-statement to ignore IE instances.
