### ISSUE TITLE
Compatibility workarounds in browser(s) introduces markup differences with server side rendering

### ISSUE THREAD

**Issue by markgarcia** [ianstormtaylor/slate#904]
I encountered this issue in Firefox caused by the following line: https://github.com/ianstormtaylor/slate/blob/56e568d063537c3267f944fd616cc0989fd4f0f0/src/components/content.js#L838

I also observed other similar workarounds which may or may not affect consistency with server side rendering.

I understand that these workarounds are very important to make things work in the browser, which is a priority above all else, including server side rendering. The solution would then be for server side rendering to be able to apply these workarounds. A way to do this is to be able to set/override the browser environment.

Until there is a formal way to handle this, I can think of the following workarounds:
 * For the above specific case, I could specify `spellCheck=false` in the React markup and it would be consistent across all environments. I am not sure if this technique would be applicable to other compatibility workarounds I will encounter.
 * Don't use server side rendering. Too bad, but for my case it is more important for things to work correctly. Less surprises this way.

**Comment by ianstormtaylor** [comment]
Extremely good call @markgarcia. And unfortunate 😄 

The ability to override the environment sounds like it's required? Either that or finding workarounds to these problems that don't affect the rendered output, but that sounds like it will be hard. I'm open to suggestions!

**Comment by ianstormtaylor** [comment]
Might be [solved in React 16](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#better-server-side-rendering)?

**Comment by markgarcia** [comment]
Sure looks like it does! I didn't quite expect that to happen. Aside from pre-v16 React's requirement on consistent server side rendering, I can't think of any other areas wherein in server-browser markup differences would matter.

Also I think having to incorporate browser-specific quirks in SSR could prove detrimental in the long run. Maybe someone in the future thinks it's a good idea to cache renders.

I'm voting to close this issue, unless pre-v16 React SSR support is really important.

**Comment by ianstormtaylor** [comment]
@markgarcia awesome! I wasn't expecting that either 😄
