### ISSUE TITLE
Spellcheck removes entire line when used with bold

### ISSUE THREAD

**Issue by Soletiq** [ianstormtaylor/slate#909]
Go here http://slatejs.org/#/rich-text
Type a line in the editor, intentionally misspelling something "Paraggraphs are cool"
Make that line bold
Right click the misspelled word, correct it, and the entire line is removed except that one word.

It shouldn't be removing the entire line..

**Comment by ianstormtaylor** [comment]
Hey @Soletiq can you add a video showing the issue? Thanks!

**Comment by SebAshton** [comment]
@ianstormtaylor I've experience this too, so have created a gif of the issue @Soletiq describes:

![error](https://user-images.githubusercontent.com/881759/29023057-dd191964-7b63-11e7-8381-3f801c06dcd6.gif)

While trying to reproduce the error I also experienced an issue whereby the cursor was writing to two places in the document after a spell check:

![error2](https://user-images.githubusercontent.com/881759/29023113-36f13016-7b64-11e7-8075-9b9b1119e03d.gif)

**Comment by danburzo** [comment]
More generally, in Chrome/macOS, correcting the spelling of a marked word:

1. Makes the corrected word lose its marks
2. Introduces a state inconsistency that breaks in all sorts of ways.

Some steps to repro:

1. Open the editor http://slatejs.org/#/rich-text
2. Misspell a word, then __bold it__
3. Right-click on the word and correct it — notice how it's introduced as plain text
4. Press Cmd + Z to undo

When correcting the first word in the paragraph:

<img width="1279" alt="screen shot 2017-08-17 at 16 31 35" src="https://user-images.githubusercontent.com/205375/29414804-927bb278-8369-11e7-89ae-123cd5c76ec0.png"> 

When correcting a word in the middle of the paragraph:

<img width="1279" alt="screen shot 2017-08-17 at 16 32 50" src="https://user-images.githubusercontent.com/205375/29414854-bcb30924-8369-11e7-96bf-ab2fad132255.png">

**Comment by bengotow** [comment]
Hmm I'm seeing this too... In Chrome, the browser inserts the correction by running `document.execCommand('insertText', false, correction)` so we might be able to identify / test the issue using the behavior of `insertText`.

I'm fixing this in Mailspring (an Electron app) by implementing my own `contextmenu` event handler on the Editor component and then displaying a custom menu that performs Slate changes rather than native DOM changes, but I'm not sure if there's a general purpose fix.

**Comment by ianstormtaylor** [comment]
I think this is fixed in the latest versions of Slate.
