### ISSUE TITLE
Focused void blocks should not bring up touch keyboard

### ISSUE THREAD

**Issue by dmitrizzle** [ianstormtaylor/slate#911]
#### What's the current behavior?

Any void block, when focused on a touch device brings up mobile keyboard, which is an undesirable effect.

<img width="300" alt="mobile" src="https://user-images.githubusercontent.com/8587882/27841013-f71f8862-6127-11e7-9d2a-2767fcfad249.PNG">

***
Void blocks are used for images and other interactive elements in the document. Although it's useful to hit backspace to delete one, that might not be the desirable effect even on desktop. For example, I used void block to create an inline menu that splits the editable content and therefore needs to be a part of it. I can't imagine any user would expect to be able to close menus with backspace:

<img width="300" alt="screen shot 2017-07-05 at 2 15 08 am" src="https://user-images.githubusercontent.com/8587882/27841000-d7ee11b6-6127-11e7-9927-fa7258396220.png">

#### What's the expected behavior?
1. The current functionality that creates that empty input field (?) in the top left of a void node on focus should be a plugin and developed separately.
1. Or it should not bring up touch keyboard (however, devices that have both touch screen and keyboard could make for a difficult case, thanks for pointing that out, bmsterling on Slack).

Personally I think option 1 would be a better choice in the long-run, but number 2 could be a faster fix.

**Comment by ianstormtaylor** [comment]
Hey @dmitrizzle thanks for opening this. The void node logic doesn't actually create an empty `<input>` element, but I think the keyboard is opening purely from `contenteditable` behavior. I'm not sure how to close it, but if you (or anyone else) has a way to do that let me know. I'm not sure if this should be in core, or if users should opt-in to closing the keyboard, since like you mentioned pressing <kbd>delete</kbd> seems like a valid use case.

**Comment by dmitrizzle** [comment]
Hi @ianstormtaylor thank you for the tip! Here's what I dug up so far (I'm quite new to this):

- Draft.JS: same behaviour with [this plugin](https://www.draft-js-plugins.com/plugin/image).
- ProseMirror: same behaviour with [this example](http://prosemirror.net/examples/dino/).
- Quill: does [not](https://github.com/primefaces/primeng/issues/2050) support image selection inline.
- TinyMCE: same behaviour with [this example](https://www.tinymce.com/docs/demo/image-tools/).
- `contenteditable` with [Webkitresize](http://www.editorboost.net/Webkitresize/Demos): same behaviour.

Draft, Mirror, and Webkit all treat images as if they are `isVoid: false` blocks in Slate.

We should be able to copy that behaviour, which is a nice to have option that might solve [this](https://github.com/ianstormtaylor/slate/issues/719#issuecomment-296880782) issue:
```javascript
.transform()
.insertBlock({
	type: "image",
	isVoid: false
})
````

Coming back to keyboard on iOS thing, I can only think of switching focus to another element outside of `<Editor/>`. Has anyone tried that?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
