### ISSUE TITLE
Warning: Failed prop type: Invalid prop `state` of type `State` supplied to `Editor`, expected instance of `State`.

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#924]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?
<img width="1016" alt="screen shot 2017-07-12 at 2 19 53 am" src="https://user-images.githubusercontent.com/1556536/28090052-a79fb952-66a8-11e7-80b7-9c4f551ec20d.png">

#### What's the expected behavior?
no error

**Comment by jatins** [comment]
Seems to be failing some type check.

<img width="908" alt="screen shot 2017-07-12 at 6 50 18 pm" src="https://user-images.githubusercontent.com/1556536/28119606-151edb0e-6733-11e7-8441-7187b2d7fcad.png">

Although, looking at `Watch` tab, it should not happen.

**Comment by jatins** [comment]
Ah, I think I figured out the issue. I am using [lerna](https://github.com/lerna/lerna) to manage packages in my code. 

* The component I was passing props _from_ and the editor component which is using those props are two different (npm) packages.
* Both of them have `slate` as their dependency. 

That's why the `instanceof` check is failing. Because the instance is created using one instance of slate, and being checked against other.

**Comment by YurkaninRyan** [comment]
I've encountered similar problems using other Plugins with instanceof

**Comment by ianstormtaylor** [comment]
Open to ideas on how to get around this, based on what other libraries are doing.

**Comment by YurkaninRyan** [comment]
@ianstormtaylor I'm gonna do some research and see if I can get a pull request rolling.  There must be a standard way seems like a common problem

**Comment by YurkaninRyan** [comment]
Looks like moment sets a "private" property on the prototype.  Should we just set a flag somewhere to compare against?

**Comment by ianstormtaylor** [comment]
Is there any prior art from other projects that use Immutable.js that use a different approach?

**Comment by YurkaninRyan** [comment]
Hmm, well look at immutable itself they use this https://github.com/facebook/immutable-js/blob/master/src/Predicates.js#L10

Which seems to be a combination of private flag checking and internal instance checking?

**Comment by ianstormtaylor** [comment]
Doing that way with pseudo-Symbols sounds good to me.
