### ISSUE TITLE
DnD text sometimes inserted in wrong location - also no drop cursor

### ISSUE THREAD

**Issue by mjadobson** [ianstormtaylor/slate#927]
#### Do you want to request a *feature* or report a *bug*?

Bug/feature

#### What's the current behavior?

![](http://g.recordit.co/Yd9Uw3fs2v.gif)

- Text sometimes inserted at wrong location.
- No visual cursor visible to show insertion location while dragging text.

#### What's the expected behaviour?

- Text should be inserted at correct drop location.
- Visual cursor should be visible to show insertion location while dragging text.

---

- I'm not sure why the insertion point sometimes isn't correct, will investigate.
- In Prosemirror there is a plugin that adds a fake dropcursor (1px border-left `<span>`) [1]

[1] https://github.com/ProseMirror/prosemirror-dropcursor

**Comment by mjadobson** [comment]
Ok, so the drop cursor can be brought back quite simply by only calling `e.preventDefault()` for external drags (to prevent some browsers loading dropped external files/links).

However, this change breaks Edge support again. I've looked into it some more and bizarrely the main issue is the `<span>` elements used in Slate. For some reason Edge doesn't let you drop onto inline elements such as `<span>` or `<a>`. The fix seems to be set the style of these elements to `display: inline-block`.

https://jsfiddle.net/69z2wepo/82817/
![](http://g.recordit.co/ovpnVh32Hi.gif)

**Comment by mjadobson** [comment]
Looked into this some more, and Trix fixes this by calling preventDefault in ondragover, and then brings back the cursor by using the mouse pointer location to manually set the selection during the drag. This approach works in Edge & Chrome

**Comment by ianstormtaylor** [comment]
I believe this is fixed in the newest version of Slate. Let me know if you're still seeing it though!

**Comment by mjadobson** [comment]
The cursor is now visible, but as discussed above, it has brought back the issue in Edge where it is impossible to drag+drop text.  Without `e.preventDefault()`, dragging text in Slate displays a stop/restricted sign blocking drops. The only fix for this would be to preventDefault, then manually set the cursor position, as in Trix, or add a fake cursor, as in Prosemirror.

**Comment by ichbinedgar** [comment]
Hi, this issue should be open. The cursor is visible now, but it's still inserting in the wrong location sometimes.
