### ISSUE TITLE
fix malformed handling of marks on iOS

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#93]
This might be an x-browser issue, but thought it would be worth reporting. Steps:

1. Open editor on iOS (or iOS Simulator).
2. Type some text.
3. Select a portion of the text, and apply some marks to it (B/I/U). Marks are applied.
4. Select the end of the paragraph and continue typing.
  - Expected behavior: Marks are applied and text continues after.
  - Actual behavior: Marks are removed and text continues after.

Screencast:

![slatebug](https://cloud.githubusercontent.com/assets/27594/16886622/2b125f7e-4a8a-11e6-8204-860e66c48504.gif)

**Comment by ianstormtaylor** [comment]
Interesting, I'll check this one out early next week! Hopefully there's an easy fix.

**Comment by ianstormtaylor** [comment]
Fixed this with the latest release. Turns out that **BIU** formatting menu acts in weird ways, so it's now disabled (similarly to how the native bold hotkey in browsers is disabled by default too).
