### ISSUE TITLE
Any example for using Placeholder component?

### ISSUE THREAD

**Issue by huozhi** [ianstormtaylor/slate#931]
I found that there was only illustration for placeholder component props in https://docs.slatejs.org/reference/components/placeholder.html. And I couldn't find out some examples in slate codebase.

Now I use the default paragraph type placeholder in my app, which works well in `examples/rtl`.

I would like to know if slate could provide some demo or example code for `Placeholder` component ? Then I can do more customized things.

Thanks a lot. : )

**Comment by dmitrizzle** [comment]
Here's how I used it in my project:

**Placeholder.js**
```javascript
// tools
import React from "react"
import { Placeholder } from "slate"

// return
export default class extends React.Component {
  render(){
    const { node, state, parent } = this.props
    return (
      <Placeholder
        firstOnly={ true }
        parent={ parent }
        node={ node }
        state={ state }
        style={{ opacity: "0.65" }}
      >
        { this.props.children }
      </Placeholder>
    )
  }
}
```

**schema.js**
```javascript
// tools
import React from "react"

// components
import Placeholder from "./containers/Placeholder"


// return
export const schema = {
	nodes: {
		paragraph: props => <p { ...props.attributes } style={{ position: "relative" }}><Placeholder { ...props }>Write your story...</Placeholder>{ props.children }</p>
	}
}
```

... Then added this schema to the state.

**Comment by huozhi** [comment]
Thanks for @dmitrizzle 's example. But I think that it is a little bit obscure to know use `Placeholder` in editor schema. And the props `parent` and `node` are should not be cared by developers. Using in schema is more like customizing the content paragraph.

Why not just give the customized component as prop `placeholder={<MyComponent />}` ? It might be easier for user to learn.

**Comment by dmytro-shchurov** [comment]
I define my schema in a separate module. Could anyone suggest how I can pass the placeholder parameter from Slate editor wrapper component into that schema module? Without using of experimental context feature it seems impossible. But usage of the context seems a bit ugly, doesn't it?

**Comment by dmytro-shchurov** [comment]
@dmitrizzle example misses two thing. The first is that `Placeholder` is implemented in `slate-react`, not `slate`; the second is that `style` needs `position: 'inherit'`

**Comment by conorcussell** [comment]
Closing this as the Placeholder component was removed in [slate-react@0.7.0](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md#070--october-18-2017)
