### ISSUE TITLE
Raw serialization does not preserve selection.

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#932]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?
Raw serialization does not save current selection.

Fiddle: https://jsfiddle.net/2zokvrvt/164/

#### What's the expected behavior?
Save the selection state also.

**Comment by terryoy** [comment]
My opinion is that selection is kind of an editing state and should not be saved as a serialized state. Perhaps it is better provided as an optional feature enabled by a function parameter.

**Comment by ianstormtaylor** [comment]
On my phone now, but I believe there is an option argument that covers it. If it's not documented, I'd appreciate a PR that documents it! Thanks

**Comment by danburzo** [comment]
@jatins that would be the `preserveSelection` option for the Raw serializer.

**Comment by ianstormtaylor** [comment]
@danburzo is right.
