### ISSUE TITLE
Composite characters (e.g: accents or korean) "eats" following characters

### ISSUE THREAD

**Issue by jpreynat** [ianstormtaylor/slate#937]
#### Do you want to request a *feature* or report a *bug*?

Report a bug

#### What's the current behavior?

1. Type hello
2. Place cursor at beginning of line, just before hello
3. Type an `î` (ALT+i then i)
4. Notice that it "eats" the following h

![](http://g.recordit.co/Erwdh7dA8A.gif)

#### What's the expected behavior?

Inserting new characters should not delete existing ones.

**Comment by danburzo** [comment]
Supplementing this with some browser information:

* Firefox/macOS _swaps around accented letter and next one_: `wîorld` instead of `îworld`
* Safari works correctly
* Chrome/macOS removes the next character as per original bug description

**Comment by ianstormtaylor** [comment]
I believe this is fixed in the newer versions of Slate!
