### ISSUE TITLE
IME inputting characters overlapped with placeholder

### ISSUE THREAD

**Issue by terryoy** [ianstormtaylor/slate#939]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

![image](http://g.recordit.co/IZs4QLYOWK.gif)

#### What's the expected behavior?

When the characters are inserted in the editor in temporary status, the placeholder should hide.

**Comment by danburzo** [comment]
This behavior refers to Safari and Chrome/macOS. Firefox [exhibits a different problem](https://github.com/ianstormtaylor/slate/issues/1008).

**Comment by blakeembrey** [comment]
I was playing around with Draft.js and noticed it doesn't have this issue. It seems in `oncompositionstart` they add a flag to their state which is used when deciding to render the placeholder. Reference: https://github.com/facebook/draft-js/blob/cd20b992d4b054d70f756c258e5e75e518995e12/src/component/base/DraftEditor.react.js#L197
