### ISSUE TITLE
Please add a Changelog.md for transparency

### ISSUE THREAD

**Issue by davydog187** [ianstormtaylor/slate#940]
First off, slate.js is such a great project and I love the work thats being done here :)

It would be extremely helpful to those depending on slate to have a Changelog to catalog the contents of each release.

Thanks!

**Comment by ezakto** [comment]
What about the history.md file? https://github.com/ianstormtaylor/slate/blob/master/History.md

**Comment by davydog187** [comment]
I guess that's exactly what I'm looking for! Thoughts on changing the name
to 'Changelog.md' to make it more obvious and in sync with most other
projects?

**Comment by ianstormtaylor** [comment]
Renaming it to `Changelog.md` sounds good to me, thanks for the suggestion @davydog187!

**Comment by oyeanuj** [comment]
@ianstormtaylor Now that we have the API mostly stabilized, do you think we could have PR authors add to the changelog with their PRs, so that it is a bit easier to track what might have changed?

**Comment by ianstormtaylor** [comment]
@oyeanuj I think until `1.0` I'll keep the current behavior, cuz it's already hard enough to get PR's that are great quality without adding extra stuff. And we merge a decent amount of random fixes and little tweaks that are still a hassle to document right now. But maybe in the future!

(For anyone that wants to track the repo more closely, I recommend "watching" with GitHub.)
