### ISSUE TITLE
Link example breaks with Chinese IME

### ISSUE THREAD

**Issue by J22Melody** [ianstormtaylor/slate#942]
I'm using MacOS 10.12, Chrome 59 and Pinyin - Simplified input method.

In the link example(http://slatejs.org/#/links) I try to add Chinese character after the link, but when I insert the first Chinese character the link breaks and after I insert the second the link appear again, which seems wired.

I have made a gif to record this(open in new tab to see the gif):

![slate](https://user-images.githubusercontent.com/2316987/28355747-e7516984-6c97-11e7-97d3-900e6d282844.gif)

I think for me one workaround is to add a space character after every link to avoid the wired behavior, but it's a little hack.

**Comment by chemzqm** [comment]
Same here, it works well on Safari, I think that's because the upgrade of Chrome, the `compositionend` event have changed it's trigger time.

**Comment by chemzqm** [comment]
https://github.com/ianstormtaylor/slate/pull/880/files could fix this issue, but there's still issue with placeholder when using IME.

**Comment by J22Melody** [comment]
@chemzqm 谢谢, I just patched the PR and tested locally, sadly the problem stills. Do you have a working example?

**Comment by chemzqm** [comment]
That PR works well for me(it's not online), you might have rerender issue or your webpack didn't compile as expected.

**Comment by J22Melody** [comment]
@chemzqm I solved the problem by patching https://github.com/ianstormtaylor/slate/pull/881 firstly, thx anyway.
