### ISSUE TITLE
A 'Made with Slate' showcase section please!

### ISSUE THREAD

**Issue by gavinhewitt** [ianstormtaylor/slate#943]
#### Do you want to request a *feature* or report a *bug*?

Maybe it qualifies as a feature? Not sure...

#### What's the current behavior?

There is no showcase!

#### What's the expected behavior?

To see what awesome stuff people have already made with Slate.

I only know of one:

- ORY Editor: https://editor.ory.am/

**Comment by ianstormtaylor** [comment]
Good call @gavinhewitt! I've just added a **Showcase** section to the resources docs page, so anyone can feel free to add things there!
