### ISSUE TITLE
Loose selection event in IE11 [BUG]

### ISSUE THREAD

**Issue by ddivin-sc** [ianstormtaylor/slate#946]
Test to reproduce for IE11:
* select any word
* click into selection area (this event will be loose)
* set mark with bold in this cursor position

I'm expected mark will be apply for the current cursor position.

**Comment by brendancarney** [comment]
I was unable to reproduce this in IE11 using browserstack on the rich text example. @ddivin-sc if you can provide more info, we'd be happy to reopen this issue.
