### ISSUE TITLE
core schema rule to "Ensure that inline void nodes are surrounded by text nodes" operates on non-void nodes...

### ISSUE THREAD

**Issue by busticated** [ianstormtaylor/slate#953]
#### Do you want to request a *feature* or report a *bug*?

bug i think?

#### What's the current behavior?

slate's core schema includes a [rule](https://github.com/ianstormtaylor/slate/blob/v0.21.0/src/schemas/core.js#L175) which specifies that void inline nodes be surrounded by empty text nodes but this rule is actually applied regardless of `isVoid` value.

#### What's the expected behavior?

nodes with `isVoid: false` are ignored?

the [rule immediately below](https://github.com/ianstormtaylor/slate/blob/v0.21.0/src/schemas/core.js#L254) also claims to target void nodes but doesn't check `isVoid` so perhaps it's just that comments are out of sync?

if so, i'm curious why non-void nodes are included?

anyway, thanks for an awesome lib! 👍

**Comment by YurkaninRyan** [comment]
@SamyPesse could probably explain it looks like the comment just wasn't updated https://github.com/ianstormtaylor/slate/commit/8738b0a48da752d93950acb0654d121f724cbdef

**Comment by busticated** [comment]
thanks @YurkaninRyan 

assuming this change was intentional, the question becomes why? (cc @SamyPesse)

in my case, i'm building a custom serializer in order to transform my own document format into slate's (and back) and need to understand what nodes / node hierarchy i ultimately need to create.

currently, i'm doing `Slate.State.create({ document: doc }, { normalize: false });` after building up the slate document structure. initial render is fine, updates work fine except for constructs which include sibling inline nodes. if i re-add the `if (!child.isVoid) return list` line that was removed from the core schema, those work fine as well. so, i'm not sure which case the linked change was meant to address.

strongly suspect i'm just not hitting the target case :)

**Comment by busticated** [comment]
i was able to track down some history [here](https://github.com/ianstormtaylor/slate/issues/483) and [here](https://github.com/ianstormtaylor/slate/issues/349). relevant PR [here](https://github.com/ianstormtaylor/slate/pull/494)
