### ISSUE TITLE
Editor (containing some text) doesn't regain focus after switching to another browser tab and back

### ISSUE THREAD

**Issue by zoltanbiber** [ianstormtaylor/slate#957]
Hi, using slate 0.20.4 within React and having an issue with editor focus. I am trying to isolate the problem and see if this is a slate bug/intended behaviour or I should look for the fix outside of slate.

Basically we are rendering the Slate editor on various ‘pages’ within the single-page-application. We want the editor to have focus on every page automatically as we switch between them so we don't have to explicitly click into the editor. We achieve that by calling `state.transform().selectAll().collapseToEnd().focus().apply()` after a page loads and it works fine so we can switch between application pages and even browser tabs and the cursor is nicely focused in the editor.

However when we write something in the editor and then switch to a different page the editor does contain the text we typed but I cannot make it focused. Is `.focus()` not meant to work when the editor is not empty or are we facing some kind of a bug? The most related issue I could find was https://github.com/ianstormtaylor/slate/issues/756 but it has been fixed/closed since…

I’ve thought the issue might be that somehow the `state.selection.isFocused` is not updating to `false` when we click outside of the editor in other words the internal `onBlur` is not firing and so because `.isFocused` stays true the `.focus()` has no effect. I was trying to fix this by putting an explicit `onBlur` callback on the editor itself which in return calls `state.transform().blur().apply()` to no avail. Have also tried using the latest version of slate but that had no effect either.

**Comment by ianstormtaylor** [comment]
Hey, thanks for reporting this. Can you please include more information? Specifically, we need every bug issue to include a simplified JSFiddle which can reproduce the issue, and a GIF showing the broken behavior in action. Without these, issues are much harder to debug, and won't be fixed anywhere near as fast. Thanks.

**Comment by zoltanbiber** [comment]
I'll see if I can re-create this bug inn a simplified fiddle.

**Comment by conorcussell** [comment]
Closing this as it's likely out of date by now
