### ISSUE TITLE
Tables pasted from Excel do not remain as tables

### ISSUE THREAD

**Issue by deepwell** [ianstormtaylor/slate#96]
Pasting a table (CTRL-P) from Microsoft Excel is converted to a tabular input and table formatting is lost.

Expected: Tables pasted from Excel retain their table cells and border colours.

**Comment by ianstormtaylor** [comment]
Hey @deepwell, thanks for opening this! This is probably one of the more confusing parts about Slate, I've added a ["FAQ" page](https://github.com/ianstormtaylor/slate/blob/master/docs/concepts/faq.md) with this as the first question to future folks with this. Here's the answer:

> One of Slate's core principles is that, unlike most other editors, it does **not** prescribe a specific "schema" to the content you are editing. This means that Slate's core has no concept of "block quotes" or "bold formatting". 

> For this most part, this leads to increased flexbility without many downsides, but there are certain cases where you have to do a bit more work. Pasting is one of those cases.

> Since Slate knows nothing about your schema, it can't know how to parse pasted HTML content (or other content). So, by default whenever a user pastes content into a Slate editor, it will parse it as plain text. If you want it to be smarter about pasted content, you need to define an [`onPaste`](https://github.com/ianstormtaylor/slate/blob/master/docs/reference/components/editor.md) handler that parses the content as you wish.
