### ISSUE TITLE
Website gives inaccurate information about ProseMirror

### ISSUE THREAD

**Issue by marijnh** [ianstormtaylor/slate#965]
While these may have had some merit back when you wrote them, I don't think they are a fair characterization of the current ProseMirror system anymore:

>  the API is hard to understand, that the codebase wasn't structured around common node module practices, that lots of magic was built into the core library that was hard to customize, that toolbars and buttons are too tied to the editor itself,

So I'd appreciate it if you'd remove or update that section, in the interest of not spreading FUD.

**Comment by ianstormtaylor** [comment]
@marijnh absolutely, thanks for pointing that out. Going to re-read and update it now!

**Comment by ianstormtaylor** [comment]
Okay @marijnh I've updated the description after reading through the Prosemirror docs and source quickly to get a sense for the changes, and added the "schemas" to the list of things that Slate borrowed from Prosemirror. Let me know if you'd like further changes!

**Comment by marijnh** [comment]
Hi @ianstormtaylor, thanks for the quick turnaround. Still pretty negative, but I guess you have to distinguish your project somehow.
