### ISSUE TITLE
[IME] Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by pizn** [ianstormtaylor/slate#967]
The current behavior?

![removechild](https://user-images.githubusercontent.com/986480/28872520-26ea7598-77bc-11e7-81f6-0ecf9e448a20.gif)

---

macOS + Chrome 60 

1. Select two lines
2. Use IME input some word
3. Enter and the console will throw error

--- 

with #854

**Comment by chemzqm** [comment]
#885 should fix this, instead of #880 , I hope it could get merged.

**Comment by Soreine** [comment]
Can reproduce using dead keys, on Chrome (not Firefox).

1. Switch to a French keyboard layout
2. Type twice the ` character at the start of the document (under the `\` key on US layouts).
3. Slate crashes

**Comment by Soreine** [comment]
Possibly the same issue: https://github.com/ianstormtaylor/slate/issues/1229

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368.
