### ISSUE TITLE
KeyDown `Space` eat some characters

### ISSUE THREAD

**Issue by pizn** [ianstormtaylor/slate#968]
The current behavior?

![space](https://user-images.githubusercontent.com/986480/28872938-e561354c-77bd-11e7-852e-500a95cb3c59.gif)

---

macOS + Chrome 60

1. Anchor at one lines first character
2. Keydown `Space`
3. It will eat some characters

**Comment by schneidmaster** [comment]
This is a duplicate of #938. (I have been working on-and-off on a PR to fix but it's trickier than you might think.)

**Comment by ianstormtaylor** [comment]
Closing as it's a dupe, thanks @pizn!
