### ISSUE TITLE
How to allow HTML blocks to breakout on enter?

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#97]
How can we allow HTML blocks to 'break out' when the user hits enter? In essence, when in an h1, if I hit enter, I want to set the default behavior to 'break out' of the h1 into a p.

1. Open editor.
2. Begin an h1 block and type.
3. Hit enter.
4. Continue typing.
  - Desired behavior: second line should be in a `<p>`, not an `<h1>`.
  - Actual behavior: second line is in an `<h1>`

This is handled in Draft.js with this plugin: https://github.com/icelab/draft-js-block-breakout-plugin.

![block](https://cloud.githubusercontent.com/assets/27594/16889965/50f7e974-4a9f-11e6-84b5-534570e54a53.gif)

**Comment by mathieudutour** [comment]
you might want to look at this: https://github.com/ianstormtaylor/slate-soft-break

**Comment by ianstormtaylor** [comment]
Hey @markbao good question. I've actually implemented similar functionality for my own editor, and will probably pull it out into a separate plugin early next week.

The general idea is we want to have an `onKeyDown` event handler, which will both `splitBlock()` and `setBlock('my-default-type')`. (By default the core plugin just does a `splitBlock()`.) 

Off the top of my head it might look like:

```js
function onKeyDown(e, state) {
  if (state.startBlock != 'header-one') return
  return state
    .transform()
    .splitBlock()
    .setBlock('paragraph')
    .apply()
}
```

**Comment by iKorso** [comment]
So, is there any methods to do what @markbao said? sorry, but i still cant understand.

``` javascript
onKeyDown = (e, change) => {
    if (e.keyCode === 13 && !e.shiftKey) {
        change.setBlock('paragraph')
        this.onChange(change)
    }
}
```

this code still not doing what we want - it changes previous block to 'paragrap', and if you will do `change.splitBlock().setBlock('paragraph')` it will add 2 blocks instead of one.
What im doing wrong?

**Comment by jay-shah** [comment]
Hey @iKorso if you do a `return` rather than `this.onChange(change)` it will work:

```
onKeyDown = (e, change) => {
    if (e.keyCode === 13 && !e.shiftKey) {
        return change.splitBlock().setBlock('paragraph')
    }
}
```

**Comment by achimkoellner** [comment]
**insertBlock** worked for me:

```
onKeyDown = (e, change) => {
    if (e.keyCode === 13 && !e.shiftKey) {
        return change.splitBlock().insertBlock('paragraph')
    }
}
```

**Comment by emperor-orbitz** [comment]
Has anyone experienced problems with rendering <h1> on the editor.
My serialised data is correct and the elements change when I inspect.
But the editor only boldens the text and it doesn't increase in size like h1, h2.....
Any help please?

**Comment by simpleshadow** [comment]
Got it working in 0.57 with:

```javascript
if (event.key === 'Enter' && !event.shiftKey) {
     setTimeout(() => {
         Transforms.setNodes(editor, { type: 'paragraph' })
     }, 1)
}
```

Some sort of timing issue — either due to rendering, the key down, or Slate. Not ideal so will dig into it.

**Comment by zxkxyz** [comment]
@simpleshadow I did something similar but eliminated the need for a setTimeout because it was causing the new line to temporarily glitch. I just override the default behavior of the enter key and instead manually insert a new paragraph node with empty text:

```javascript
if (event.key === "Enter" && !event.shiftKey) {
    event.preventDefault();
    const newLine = {
        type: "paragraph",
        children: [
            {
                text: "",
                marks: []
            }
        ]
    };
    Transforms.insertNodes(editor, newLine);
}
```

**Comment by simpleshadow** [comment]
@zxkxyz 👍 

I've had a couple of other scenarios where I need `setTimeout` so a series of transforms occur on the next tick.

For example, when overriding the `insertBreak` command, I allow the `insertBreak` call to complete (for all other plugin overrides to apply) and then have transforms on the next tick. Not sure if this helper is right, but has been working for me!

```javascript
// withBlurt.ts

export const withBlurt = <T extends Editor>(editor: T, options: { debug?: boolean } = { debug: false}) => {
    const e = editor as T & BlurtEditor

    e.nextTick = cb => {
        setTimeout(cb, 0)
    }

    return e
}
```

**Comment by PaddyMann** [comment]
I had issues with some of the solutions above:

- The solution from @simpleshadow (using setTimeout) leads to a flicker effect in the UI
- The solution from @zxkxyz works well if pressing enter at the end of some text, but not if you press enter in the middle of some text.

To fix this:

```javascript
if (event.key === 'Enter') {
  const selectedElement = Node.descendant(editor, editor.selection.anchor.path.slice(0, -1));

  // Replace 'title' with the type of the element which you wish to "break out" from
  if (selectedElement.type === 'title') {
    event.preventDefault();
    const selectedLeaf = Node.descendant(editor, editor.selection.anchor.path);

    if (selectedLeaf.text.length === editor.selection.anchor.offset) {
      Transforms.insertNodes(editor, {
        type: 'paragraph',
        children: [{text: '', marks: []}],
      });
    }
    else {
      Transforms.splitNodes(editor);
      Transforms.setNodes(editor, {type: 'paragraph'});
    }
  }
}
```

**Comment by alexperetti** [comment]
@PaddyMann Thanks that solution is working for me! 
I just had to tweak for my use-case (check-lists) `Transforms.splitNodes(editor, { always: true })` so the node always splits even when `editor.selection.anchor.offset === 0`.

**Comment by mwalkerr** [comment]
Just a note on UI flicker with the setTimeout approach - it's possible that such an approach might work without the flicker if a promise is used instead since the callback should be a "microtask" instead of a new task (or "macrotask"?). Using a promise to schedule an asynchronous callback is already used internally in Slate, in `create-editor.ts` for example:
```
Promise.resolve().then(() => {
    FLUSHING.set(editor, false)
    editor.onChange()
    editor.operations = []
})```
The task / microtask distinction is only something I learned about recently after looking into the difference between Promise.resolve().then vs setTimeout, so I don't know much about the actual difference in effect.
https://stackoverflow.com/q/38752620/828584
https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/
The quote from javascript.info ([Event loop: microtasks and macrotasks](https://javascript.info/event-loop)) suggests that this _would_ avoid the ui flicker since rendering should be delayed until after all microtasks:

> Immediately after every macrotask, the engine executes all tasks from microtask queue, prior to running any other macrotasks or rendering or anything else

**Comment by volnei** [comment]
> How can we allow HTML blocks to 'break out' when the user hits enter? In essence, when in an h1, if I hit enter, I want to set the default behavior to 'break out' of the h1 into a p.
> 
> 1. Open editor.
> 2. Begin an h1 block and type.
> 3. Hit enter.
> 4. Continue typing.
>    
>    * Desired behavior: second line should be in a `<p>`, not an `<h1>`.
>    * Actual behavior: second line is in an `<h1>`
> 
> This is handled in Draft.js with this plugin: https://github.com/icelab/draft-js-block-breakout-plugin.
> 
> ![block](https://cloud.githubusercontent.com/assets/27594/16889965/50f7e974-4a9f-11e6-84b5-534570e54a53.gif) [ ![block](https://cloud.githubusercontent.com/assets/27594/16889965/50f7e974-4a9f-11e6-84b5-534570e54a53.gif) ](https://cloud.githubusercontent.com/assets/27594/16889965/50f7e974-4a9f-11e6-84b5-534570e54a53.gif) [ ](https://cloud.githubusercontent.com/assets/27594/16889965/50f7e974-4a9f-11e6-84b5-534570e54a53.gif)

How could achieve this using slate 0.97?
