### ISSUE TITLE
Consider using state changes instead of operation + inverse operation for updating state

### ISSUE THREAD

**Issue by ExplicitlyImplicit** [ianstormtaylor/slate#971]
#### Do you want to request a *feature* or report a *bug*?

Feature

#### What's the current behavior?

Currently, undo/redo functionality is implemented using inverse operations (i.e. if I perform a split node operation, a join node operation is pushed to the undo stack), this makes it difficult to extend or fix Slate functionality as there are two operations (instead of one) that can introduce bugs. I would also argue that implementing an inverse operation is even more difficult to reason about and may have a higher complexity which could introduce even more special cases and bugs.

Inverse operations also makes it difficult to view/modify the history as you cannot see what changes is actually made to the state. We are also not able to squash operations if we don't want our transforms to map 1:1 to our undo/redo stack.

#### What's the expected behavior?

Instead of implementing consistent inverse operations we could let operations push state changes onto the document. Transforms would define a state change which would be pushed when calling `apply`. I'm picturing something like how version control systems, like git, works.

You would no longer need to implement inverse operations as undo/redo would be solved by reverting the applied state changes. Operations can also be separated from the undo/redo functionality by giving the developer a way of grouping a bunch of operations into one (kind of like squash in git).

The history can be exposed and more easily viewed/modified as you have access to the actual changes each operation (or commit if you would continue with the VCS analogue) does. 

Moving closer to a VCS kind of functionality for state changes might also be good for extending slate for collaborative editing?

**Comment by ianstormtaylor** [comment]
Hey @ExplicitlyImplicit, do you mean that way change would save the newly changed full state in the history? Such that history is a list of previous entire states, and to undo you'd just set the state to the previous version?

If so, we actually used to do that. Before going down the path of operational transform for collaborative editing. But for collaboration the individual operations and their inverses are key. 

That said, there's talk of splitting history out of core, and if that did happen I would definitely be open to allowing for both kinds. If someone wanted to sketch out how the API would work and contribute it.

**Comment by ExplicitlyImplicit** [comment]
Hi @ianstormtaylor, thank you for explaining the reasoning behind using inverse operations, I've read #259 and what I had in mind is not going to improve anything. I was thinking about modeling the current state as an ordered set of changes on an initial/intermediate state (like commits in git) but it would fall short (long) as a CRDT so it would be more like a step back from the current solution.

Separating history is a cool idea indeed but I don't think I can be of help for that unfortunately.

Thank you for your time, I'll go ahead and close this.
