### ISSUE TITLE
Unordered list button in rich text editor deletes blocks

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#98]
In the [rich text editor example](http://slatejs.org/#/rich-text), clicking the bullet button deletes blocks instead of toggling an unordered list.

![listicon](https://cloud.githubusercontent.com/assets/27594/16890011/ab2067be-4a9f-11e6-88d1-f0a3a2da9110.gif)

**Comment by ianstormtaylor** [comment]
Oops, fixed the example. Looks like there's actually a need for a `liftBlock()` transform type, since if you create a list item and then convert it back into a block quote, it's hard to get it "un-nested". Opening an issue for that...
