### ISSUE TITLE
Slate fails in IE11. Objects are not valid as a React child (found: List)

### ISSUE THREAD

**Issue by kvolkovich-sc** [ianstormtaylor/slate#983]
Bug in IE11.

Slate fails in IE because it uses `Symbol` data type. 

I have add this to my webpack config to polyfill `Symbol`:

```
config.entries = [
  "core-js/es6/array.js", // because Slate uses Array.prototype.find
  "core-js/es6/symbol.js",
  "core-js/fn/symbol/iterator.js",
  ...
]
```

But still get an error in IE11.

`Objects are not valid as a React child (found: List [ [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of Node.`

I found, it can be fixed by modify Slate's **Node** code. We should add `.toJS()` call

```
renderText() {
   ...
   return (
     <span data-key={node.key}>
        {leaves.toJS()}
     </span>
    );
   ...
}
```

Will you approve pull request with this change or easier just make a fork?

Or maybe someone have another idea how to fix it in better way?

**Comment by kvolkovich-sc** [comment]
Have made changes [here](https://github.com/OpusCapita/slate/compare/master...OpusCapita:ie11-compat). `leaves.toJS()` were redundant.

**Comment by ianstormtaylor** [comment]
For the `for of` loops, wouldn't it just be a question of tweaking that Babel config that Slate uses for its exported files? I'm assuming that `for of` is supported everywhere else, so we haven't been transpiling it before now, but I'm open to adding support for that.

**Comment by kvolkovich-sc** [comment]
I found old [discussion](https://github.com/babel/babel/issues/1534) at babel repo.
@kittens (main contributor of babel) claims that:

> This is expected behaviour. It's impossible to replicate for...of without a Symbol and iterator polyfill. Babel ships with a version of core-js that you can use, see the docs for more info.

**Comment by kvolkovich-sc** [comment]
@ianstormtaylor can i make a pull request?

**Comment by ianstormtaylor** [comment]
@kvolkovich-sc that would be great, thank you! For the `find` util, can we use `lodash/find` instead? Thanks!

**Comment by kvolkovich-sc** [comment]
@ianstormtaylor see:
https://github.com/ianstormtaylor/slate/pull/996
https://github.com/ianstormtaylor/slate/pull/997

**Comment by kvolkovich-sc** [comment]
Pull requests merged in master.

**Comment by danburzo** [comment]
@kvolkovich-sc did you get to the bottom of Objects being Lists in IE11? Was that a problem with your code?

**Comment by kvolkovich-sc** [comment]
@danburzo  As it turned out, this was not a problem. I did not go into details. Works - do not touch. =)
