### ISSUE TITLE
HTML deserializeMark function no longer allows for Data on mark creation

### ISSUE THREAD

**Issue by YurkaninRyan** [ianstormtaylor/slate#984]
Assume when you are deserializing HTML you hit a span, that you want to represent text color.  on this span, it has a `style` attribute, that you want to parse to get a base color in your data.

Previously you could return this from the deserializer
```js
  return {
    type:  "text-color",
    kind: "mark",
    data: {
      color: getColorFromElement(el),
    },
  }
```

and then in your schema access that in your render as `props.mark.data.get("color").  However do to this line change

https://github.com/ianstormtaylor/slate/commit/4bbf7487ea827bffa5a253fd0649190944dfb4ee#diff-223f3c7786c59981c20d377fdf6ff99fL240

Was this name change intentional?  What is the `value` of a `mark` now?

**Comment by YurkaninRyan** [comment]
@schneidmaster I figure you would probably be able to add some insight to this, is this more so a documentation issue that I can contribute to?  Can we switch it back to data?

**Comment by schneidmaster** [comment]
Hmmm. I had thought this was necessary when switching from cheerio to parse5, a lot of the node syntax changed because they're now DOM elements instead of cheerio objects. However your PR seems to work fine for me and the tests pass so I must have been mistaken 👍
