### ISSUE TITLE
toggleMark should behave as per RTE conventions

### ISSUE THREAD

**Issue by danburzo** [ianstormtaylor/slate#988]
#### Do you want to request a *feature* or report a *bug*?

A bug regarding the behavior of `toggleMark`.

#### What's the current behavior?

Currently, `toggleMark` removes the mark if it already exists in some part of the selection, and adds it otherwise.

#### What's the expected behavior?

The convention (followed by most if not all text editing apps, and on the web by `document.execCommand`) is to:
* remove the mark if _the entire selection_ contains it
* add the mark otherwise

**Comment by danburzo** [comment]
This should be an easy fix, along the lines of replacing a `some()` with `every()`, however there doesn't seem to be a way to tell there is _unmarked_ text in the selection? 

And since figuring out if the `B` button in a RTE toolbar should be pressed looks  at `state.marks.some()`, it exhibits a second deviation (albeit the two are inextricably linked) from the convention of only showing the button as active/pressed if the entire selection contains is marked with that particular mark.

**Comment by ianstormtaylor** [comment]
Hey @danburzo, I'm very down for this. I'd love a PR if you or anyone was willing to make one. Thanks!

**Comment by danburzo** [comment]
Hi @ianstormtaylor, I'd love to tackle this after I wrap my head around the Slate source code. 

To my mind, `state.marks` should also accumulate some sort of qualifier for the each mark — _some_, _every_, or _none_ characters are marked with that specific `Mark` (latter value is inferred by the the mark missing from the Set). 

Having these qualifiers would allow us to:

1. make `toggleMark` work as in other RTEs / apps
2. show toolbar button states appropriately for both simple marks (Bold, Italic) and marks that include dynamic data (Font size, color)

Now, if we were to piggyback on the computation already done when getting `state.marks` we would obviously need to make a breaking change in what it returns. 

We could introduce another property (`state.markQualifiers`?) to read this data in addition to `state.marks`, but it seems like a waste of cycles since the qualifiers can be derived along with the marks.

Any pointers, anyone?

**Comment by danburzo** [comment]
Okay, so far so good. I've started work on this here:
https://github.com/ianstormtaylor/slate/pull/990

`toggleMark` works appropriately now for the basic use case, but I still need to figure out the two aspects:

1. need to bake in `selection.isUnset` and `selection.marks`, and not go for `getMarksAtRange` directly
2. confirm that I've not impacted the performance of `getMarksAtRange`.

Anyone who can help me sort these out?

**Comment by danburzo** [comment]
I now have my full proposal on the pull request above, including docs and tests. Please let me know what you think!

**Comment by danburzo** [comment]
In regards to having `activeBlocks` and `activeInlines`, that would definitely help with toggling buttons in RTE toolbar. I wonder, however, how the _equality_ between blocks/inline would work, and whether `activeBlockTypes` and `activeInlineTypes` (with equality on the `type` attribute) would be a clearer (and still sufficient) abstraction — although to draw a parallel with `activeMarks`, we'd need to also account for the `data` object.
