### ISSUE TITLE
add `insertFragmentByKey` transform

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#989]
I think lots of the confusion around `insertFragment` stems from it being used to insert fragments at specific ranges—the way that copy/paste works—instead of being used to insert a group of nodes all at the same time in a specific location.

If we added an `insertFragmentByKey(key, index, fragment)` transform I think that would give people the other option they're often looking for. The implementation would be pretty simple, it would just loop the `fragment.nodes` and call into `insertNodeByKey(key, index + i, node)`.

**Comment by linonetwo** [comment]
Should I provide a unique key to each node in the Fragment?

I'm doing so on click a button, loads `section` from server, to solve https://github.com/ianstormtaylor/slate/issues/790 :

```js
props.editor.insertFragmentByKey(props.node.key, 0, new Document({ nodes: section }));
```

But it will warn a lot about `A node with a duplicate key of "139" was found! Duplicate keys are not allowed, you should use `node.regenerateKey` before inserting if you are reusing an existing node.`.
