### ISSUE TITLE
Placeholder doesn't clear when clicked inside a check-list-item, which has non-content-editable parts

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#998]
I need to add a placeholder for my checklists. My code is very similar to your [check-list example](https://github.com/ianstormtaylor/slate/tree/master/examples/check-lists).

The placeholder does appear (though I have to put css `position:relative` on its parent component, otherwise the placeholder shows up in the upper left of the screen, not over the component).

However, when I click on the placeholder text with the mouse, the placeholder should disappear and the cursor should appear and accept keypresses. Nothing happens.

I've tried putting the `<Placeholder>` component several places (inside the contentEditable span, outside it), but get the same results. Should I do something different, or is this a bug?

Here's an example of adding a `Placeholder` to the `check-list-example` render function in [this file](https://github.com/ianstormtaylor/slate/blob/master/examples/check-lists/index.js), which has the issues described above.

```
render() {
  const { attributes, children, node, parent, state } = this.props
  const checked = node.data.get('checked')
  return (
    <div
      className="check-list-item"
      contentEditable={false}
      {...attributes}
    >
      <span>
        <input
          type="checkbox"
          checked={checked}
          onChange={this.onChange}
        />
      </span>
      <span contentEditable suppressContentEditableWarning>
        
        <Placeholder
          parent={ parent }
          node={ node }
          state={ state }
        >
          Placeholder...
        </Placeholder>
        
        {children}
      </span>
    </div>
  )
}
```

**Comment by conorcussell** [comment]
Closing this as the Placeholder component was removed in [slate-react@0.7.0](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md#070--october-18-2017)
