### ISSUE TITLE
Add ability to discern the "kinds" of blocks/inlines are active in a selection?

### ISSUE THREAD

**Issue by danburzo** [ianstormtaylor/slate#999]
[As suggested by @ianstormtaylor here](https://github.com/ianstormtaylor/slate/pull/990#issuecomment-322612917) and as a supplement to [state.activeMarks](https://github.com/ianstormtaylor/slate/issues/988), we suggest adding `state.activeBlocks` and `state.activeInlines`, with the purpose of allowing authors to easily handle the on/off state of buttons in a RTE toolbar. 

The approach/scope/implications of the feature are not entirely clear for me at this point, so I'm starting a discussion on the topic. 

I also propose as a litmus test being able to implement a _text alignment_ (left/right/center/justify) button group for a RTE editor.

## Pros & cons

Since `state.marks` was not sufficient information to implement classic RTE behavior, we needed a separate `state.activeMarks` to achieve it. But `state.blocks` and `state.inlines` do contain all the information needed to derive the state of RTE buttons, so I think it becomes a question of whether to provide `activeBlocks` / `activeInlines` as conveniences, and for symmetry with marks.

On the other hand, the developer needs to call `every()`-type code on every change, and we could arguably provide better performance if we abstract this away into a memoized function.

One thing that complicates having `activeBlocks` is a mixed-scenario situation where I've selected:

```
- 
  type: paragraph
  data: { align: left }
- 
  type: heading
  data: { align: left } 
```
where the intersection of the blocks' metadata would yield an empty set, but the aspect `align: left` would still be "active" as per RTE conventions, so I guess we either leave the computation to userland, or split it into `activeBlocksByType` and `activeBlocksByData`...

...or, to cast even more uncertainty into the discussion, maybe modeling alignment as a data property on blocks is not the right approach? (e.g. [here it's modelled as a block](https://github.com/nossas/slate-editor/blob/master/src/package/plugins/slate-alignment-plugin/AlignmentUtils.js), but it strikes me as odd) :)

**Comment by ianstormtaylor** [comment]
@danburzo I think you're right that with the differences in `type` vs. `data` it's going to end up being too opinionated to even solve fairly common cases. So it sounds like we shouldn't bother with it, and leave it to user land instead. Unless an easier idea comes to us.

**Comment by danburzo** [comment]
Good call! I agree that it sounds like the ROI is too small to bother. Closing this down for now.
